### ISSUE TITLE
GPU isolation problem on nvidia-docker 2

### ISSUE THREAD

**Issue by Eloring** [NVIDIA/nvidia-docker#1000]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 7.6
- CPU architecture: ppc64le
- Docker version: 1.13.1
- nvidia-container-runtime-hook: 1.4.0 (i.e. nvidia-docker 2)
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6
- GPU model and memory: 2 GPUs, both are Tesla K80, 12G

**Issue**

Attempt 1:

~~~
   $ docker run -e NVIDIA_VISIBLE_DEVICES=0 --rm nvidia/cuda-ppc64le nvidia-smi
~~~

Attempt 2:

~~~
  $ NV_GPU=0 docker run --rm nvidia/cuda-ppc64le nvidia-smi 
~~~

Attempt 3:

~~~
  $ export CUDA_VISIBLE_DEVICES=0
  $ docker run --rm nvidia/cuda-ppc64le nvidia-smi 
~~~

Both GPU are always used, how to isolate them?

**Comment by Eloring** [comment]
solved

**Comment by yxchng** [comment]
@Eloring How did you solve this?

**Comment by Eloring** [comment]
@yxchng 
In fact, `docker run -e NVIDIA_VISIBLE_DEVICES=0` works for me.
I met such an isolation problem because I mistakenly wrote _NVIDIA_VISIBLE_DEVICES_ into _CUDA_VISIBLE_DEVICES_
LOL...
