### ISSUE TITLE
Failed to start nvidia-docker.service: Unit nvidia-docker.service not found.

### ISSUE THREAD

**Issue by Heaguang** [NVIDIA/nvidia-docker#1003]
求问：
先安装了docker，sudo docker run hello-world测试成功;
接着按照官网步骤安装后，用sudo systemctl start nvidia-docker出现错误：
Failed to start nvidia-docker.service: Unit nvidia-docker.service not found.
使用命令sudo systemctl status nvidia-docker查看状态，如下：
● nvidia-docker.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
搜了一下，机器上确实没有nvidia-docker.service这个文件，但用官网上面的sudo nvidia-docker run --rm nvidia/cuda:9.0-base nvidia-smi可以显示信息。

**Comment by RenaudWasTaken** [comment]
Hello!

Please update your installation of nvidia-docker to nvidia-docker2.

Thanks!

**Comment by TIANRENK** [comment]
@Heaguang 最后怎么解决的，我也遇到了这个问题

**Comment by TIANRENK** [comment]
> Hello!
> 
> Please update your installation of nvidia-docker to nvidia-docker2.
> 
> Thanks!
Hello!
I have install the nvidia-docker2,but i have the same trouble.

**Comment by Heaguang** [comment]
你重装一下nvidia-docker2和cuda试试？我这边是重新装了一下nvidia-docker2，然后使用命令sudo systemctl status nvidia-docker查看还是和之前一样，但是我后续的命令可以起来了，就没再管了，也是一直没弄明白怎么回事。
你参考这个问题看看 https://github.com/NVIDIA/nvidia-docker/issues/135

**Comment by aoqixiaoning** [comment]
整个过程，主机上必须有cuda吗
