### ISSUE TITLE
Support  Docker version 18.06.3-ce for AMZN/RHEL 7 OS.

### ISSUE THREAD

**Issue by aqua0ps** [NVIDIA/nvidia-docker#1006]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by aqua0ps** [comment]
[ec2-user@xxxxx ~]$ DOCKER_VERSION="18.06.3-ce"
[ec2-user@xxxx ~]$ echo $DOCKER_VERSION
18.06.3-ce
[ec2-user@xxxx ~]$ sudo yum install -y \
>     system-release-graphics \
>     cuda \
>     pciutils \
>     xorg-x11-server-Xorg \
>     oci-add-hooks \
>     libnvidia-container1 \
>     libnvidia-container-tools \
>     nvidia-container-runtime-hook \
>     yum-plugin-versionlock \
>     docker-runtime-nvidia \
>     docker-${DOCKER_VERSION}*





2 packages excluded due to repository priority protections
Package pciutils-3.5.1-3.amzn2.x86_64 already installed and latest version
Package xorg-x11-server-Xorg-1.19.5-6.amzn2.0.2.x86_64 already installed and latest version
No package docker-18.06.3-ce* available.
Resolving Dependencies

**Comment by aqua0ps** [comment]
Some additional information [ec2-user@xxxx ~]$ uname -a
Linuxxxxxx 4.14.123-111.109.amzn2.x86_64 #1 SMP Mon Jun 10 19:37:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux



rpm -qa '*nvidia*'
nvidia-container-runtime-hook-1.4.0-1.amzn2.x86_64
docker-runtime-nvidia-1-1.amzn2.noarch
nvidia-dkms-418.40.04-0.amzn2.x86_64
libnvidia-container-tools-1.0.0-1.amzn2.x86_64
nvidia-418.40.04-0.amzn2.x86_64
libnvidia-container1-1.0.2-1.x86_64



docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

nvidia-container-cli -V
version: 1.0.0

**Comment by RenaudWasTaken** [comment]
With the new architecture, this should be automatically supported.
