### ISSUE TITLE
docker stack deploy with GPU , but can't find nvidia devices

### ISSUE THREAD

**Issue by xinge333** [NVIDIA/nvidia-docker#1008]
# docker stack deploy with GPU , but can't find nvidia devices

## description:
When I use `docker-compose up` start the program, the code works well! But when I use `docker stack deploy -c docker-compose.yml test` to start the program, it can't find visible nvidia devices. My docker-compose.yml and error logs are shown as below.

 I'am very confused about that why I have same configures, using different lanching way of `docker-compose up` and `docker stack deploy -c docker-compose.yml test`, the first working well, but the second not. Is it currently not perfect for docker swarm supporting for GPUs, or there are other ways I have not found?

## environmental configuration
```
docker version: 18.06.0-ce
NVIDIA Docker: 1.0.1
Ubuntu: 16:04
```

### docker-compose.yml configure file
```
version: "3"

volumes:
  nvidia_driver_430.14:
    external: true

services:
  tts-server:
    build:
      context: ./
      dockerfile: ./docker/tts_server/Dockerfile
    deploy:
      replicas: 1
    image: tts-system/tts-server-gpu
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    volumes:
      - ./models:/tts_system/models:ro
      - ./config:/tts_system/config:ro
      - nvidia_driver_430.14:/usr/local/nvidia:ro
    networks:
      - overlay
    ports:
      - "9091:9090"
```

### error logs of program
```
2019-07-02 07:50:24.805114: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499885000 Hz
2019-07-02 07:50:24.808418: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4112870 executing computations on platform Host. Devices:
2019-07-02 07:50:24.808457: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-02 07:50:24.811640: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-07-02 07:50:24.811684: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:155] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
E0702 07:50:24.811846     1 decoder.cc:80] Filed to create session: Invalid argument: 'visible_device_list' listed an invalid GPU id '0' but visible device count is -1
```

This problem has been bothering me for a long time, thanks very much.

**Comment by RenaudWasTaken** [comment]
You'll need to set the default runtime to nvidia on all your nodes.
Unfortunately that's a longstanding issue we need to address.

**Comment by xinge333** [comment]
@RenaudWasTaken Sorry , I do it like this in the first, but it  doesn't work.
### /etc/docker/daemon.json
Of course, I modify the file /etc/docker/daemon.json, changed the runtime type. And restart it.
```
{
  "default-runtime": "nvidia",
  "runtimes": {
    "nvidia": {
      "path": "/usr/bin/nvidia-container-runtime",
      "runtimeArgs": []
    }
  }
}
```

```
sudo systemctl daemon-reload
sudo systemctl start docker
```

**Comment by RenaudWasTaken** [comment]
OK so looking a bit more at your compose file, you shouldn't be mounting the devices.

What would be the output of you ran nvidia-smi?

**Comment by xinge333** [comment]
What do you mean running nvidia-smi, in container or in local machine ?I have shown above compose file - docker-compose.yml . I just want to know what difference between `docker-compose up` and `docker stack deploy -c docker-compose.yml test`, why the first works, the second not ?

**Comment by RenaudWasTaken** [comment]
Ah sorry I meant what is the output of nvidia-smi when ran from the compose file?
It should help narrow down the difference :)

**Comment by xinge333** [comment]
Sorry, I don't know how to run `nvidia-smi` from the compose file. Could you give an example? And I found that either I use `docker-compose up` or `docker swarm` , when I enter the launched container, I can't execute the command `nvidia-smi`, because this command does not exist. I don't know whether it is normal or not.

**Comment by RenaudWasTaken** [comment]
If the command doesn't exist, it's likely that your container doesn't become gpu enabled.

Can you make sure that :
- docker info shows the nvidia runtime
- you are able to run nvidia-smi with normal cuda container (docker run - it nvidia/cuda:9.0-base nvidia-smi)
- you are able to run nvidia-smi in the container you defined above


Thanks!

**Comment by xinge333** [comment]
OK, I will execute the commands as you said.
* First, docker info about runtime:
```
Runtimes: nvidia runc
Default Runtime: nvidia
```
* Second, I can execute `docker run -it  nvidia/cuda:9.0-base  nvidia-smi` and acquire gpu info successfully.
![gpu_info](https://user-images.githubusercontent.com/17525326/60638805-6d505980-9e52-11e9-800e-e45478f7557a.png)

* If I launch container through cmd `docker run --runtime=nvidia`, I can run `nvidia-smi` in the container. But when I use `docker-compose up` or `docker stack deploy` cmd to launch container, I can't run nvidia-smi.

**Comment by RenaudWasTaken** [comment]
OK so can you confirm that  ./docker/tts_server/Docker file extends from a cuda image? 

Can you remove the environment variable, devices and the nvidia volume and from your compose file? 

Also if you execute the nvidia-smi command from that composé file what does it say? 
Do you mind also pasting the updated file?

**Comment by xinge333** [comment]
Sorry, I am sorry to have delayed your time.
Are you mean that `image: tts-system/tts-server-gpu` extends from a cuda image? I don't know why dockerfile needs to extend from cuda image? Could you give me a demo?

Now, I will try to remove `the environment variable, devices and the nvidia volume` in my compose file.

Finally, how can I execute the nvidia-smi command from the compose file? Exactly, I don't know how to edit it. Any demo?

**Comment by RenaudWasTaken** [comment]
Just use `nvidia/cuda:9.0-base` instead of `tts-system/tts-server-gpu`
For the command part see: https://devhints.io/docker-compose

**Comment by jerinka** [comment]
Hi, any soln for this? I am also facing same issue.

**Comment by elezar** [comment]
Hi @jerinka. Since this issue is very old and a number of new versions of the underlying components have been released since then, it might be a good idea to create a new issue describing the behaviour that you're seeing.

Please include any debug information as described in https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#troubleshooting
