### ISSUE TITLE
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' does not have a Release file

### ISSUE THREAD

**Issue by dittothat** [NVIDIA/nvidia-docker#1009]
### 1. Issue or feature description
In nvidia/cuda:10.1-devel-ubuntu18.04 when I run apt-get update, I get the error:

Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Err:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 10.41.13.6 3128]
Err:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 10.41.13.6 3128]

E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' does not have a Release file.
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' does not have a Release file.

### 2. Steps to reproduce the issue
Build this dockerfile:
FROM nvidia/cuda:10.1-devel-ubuntu18.04
RUN apt-get update 

I note that apt-get is functioning fine in a container I build and run using:
docker build .
FROM nvidia/cuda:9.1-devel-ubuntu16.04
RUN apt-get update

**Comment by demizer** [comment]
I have been building ubuntu images all morning without issue. Are you behind a proxy by chance? We've had users behind proxies have had issues clear up a few hours later. The CDN can be sensitive at times.

**Comment by dittothat** [comment]
Yes, I am behind a proxy. I will try again tomorrow. Thanks.

**Comment by dittothat** [comment]
Yes, this was a proxy issue. All is well now. Thank you.

**Comment by zoltan-fedor** [comment]
I have the exact same issue and also behind a proxy, but the issue does not "clear up a few hours later". I have so far waited 14 hours and no change.

Maybe a better solution would be required then just waiting a few hours and hoping that the CDN will start working, as it seems lot of people are facing this same problem.

Thanks

**Comment by zhanghming** [comment]
@dittothat I encoutered this problems as well, I wonder how to solve this if I behind the proxy?

**Comment by sliang11** [comment]
> @dittothat I encoutered this problems as well, I wonder how to solve this if I behind the proxy?

Same issue here. The thing is that at least for me, I am in China and there is no way I can reach the repository without a proxy...

**Comment by uonxhou** [comment]
Have you resolved this problem?

**Comment by drjasonharrison** [comment]
How would we know if we're behind a proxy and it is causing the problem. Is there a curl or wget command that can be used to test the network connection to the PPA?

**Comment by taoisu** [comment]
This issue happens again for me today. It seems something is wrong on the nvidia side, it was working yesterday.
```
The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' does not have a Release file
```
The repo returns 404

**Comment by jimsparkman** [comment]
See https://github.com/NVIDIA/nvidia-docker/issues/1624

**Comment by taoisu** [comment]
Thanks for the link!

**Comment by gaitanignacio** [comment]
I'm getting the same issue right now on a docker build from an old Dockerfile that I saw working properly before!

Basically:

```
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu110-ubuntu18.04

RUN apt-get update
```


```
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by pensapav** [comment]
Yup, same for us:

```
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' does not have a Release file.
The command '/bin/sh -c apt-get update && apt-get install -y         libceres1         libcgal13         libfreeimage3         libglew2.0         libopengl0' returned a non-zero code: 100
make: *** [Makefile:7: docker-build] Error 100
```

The whole `https://developer.download.nvidia.com/compute/machine-learning/repos/` repository is returning a 404.

It seems that what is failing is an `apt-get update` call, so if we ignore that failure, then move onto our `apt-get install` flow things work just fine.

**Comment by seonho** [comment]
Same for me.

See https://forums.developer.nvidia.com/t/failed-to-fetch-https-developer-download-nvidia-com-compute-machine-learning-repos-ubuntu1804-x86-64-packages-gz/156287/3

**Comment by Goddard** [comment]
2022 still getting this issue

**Comment by 0xleowang** [comment]
Starting having this issue since yesterday.

**Comment by AlexandreBrown** [comment]
We started hitting this issue today.

**Comment by Hariraj** [comment]
We too started getting this issue today.

**Comment by AlexandreBrown** [comment]
I found a fix that works (at least for me under ubuntu 18.04), see https://forums.developer.nvidia.com/t/error-during-apt-update-on-ubuntu-18-04-file-has-unexpected-size/220436/2

**Comment by muzuiget** [comment]
2022 and a half still getting this issue

```
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/Packages.gz  File has unexpected size (580845 != 580040). Mirror sync in progress?
```

**Comment by figkim** [comment]
In my case, add `RUN rm /etc/apt/sources.list.d/cuda.list` before `apt-get update` solves the issue temporarily while using dockerfile.

**Comment by jesusa-nv** [comment]
Hi folks,

Sorry about these constant CDN troubles. We are working to resolve these issues, but due to the nature of the CDN and our workflows, it will take some time.

In the future, please report issues with the CUDA repo to https://github.com/NVIDIA/cuda-repo-management.

Thanks!
