### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by bmaltais** [NVIDIA/nvidia-docker#101]
How about support for OSX? Will it eventually be possible?

**Comment by 3XX0** [comment]
Last time I checked, xhyve (the hypervisor Docker relies on) doesn't support PCI passthrough. So unless this changes, unfortunately no it's not possible.

**Comment by flaviostutz** [comment]
Guys, now Docker runs natively on MacOS. Is it possible for nvidia-docker to work now on MacOS? Thanks

**Comment by narfanator** [comment]
Heyo - I have an AWS instance set up with Docker, via `docker-machine`. I can configure my terminal to connect to the AWS docker (`eval $(docker-machine env aws1`), and then connect to it with regular docker (`docker ps`), but not with nvidia-docker... since nvidia-docker can't be installed on Mac.

Is there a way to provide support for this use-case?

**Comment by achaiah** [comment]
@3XX0  Has anything changed in a year?  Nvidia 10xx drivers are out for Mac (finally!) so I'm hoping we can also use nivida-docker in the near future.

**Comment by 3XX0** [comment]
No see https://github.com/mist64/xhyve/issues/108

**Comment by RudyAramayo** [comment]
we need this, what is going on?

**Comment by RockNHawk** [comment]
Is there any follow up?

**Comment by briandilley** [comment]
+1

**Comment by menhuan** [comment]
+1

**Comment by simonrouse9461** [comment]
+1

**Comment by sebastianfelipe** [comment]
+1

**Comment by tcorvazier1A** [comment]
+1

**Comment by jgladch** [comment]
🌮

**Comment by inesbenamor** [comment]
Is there anything new here?

**Comment by quintendewilde** [comment]
Yes anything new here?

**Comment by iseeag** [comment]
anything new here?

**Comment by lunesco** [comment]
week ago i was able to run nvidia/cuda:latest on my MAC, but it became deprecated and now i cant use any nvidia docker image on my MAC

**Comment by mariarabeleroenvato** [comment]
> week ago i was able to run nvidia/cuda:latest on my MAC, but it became deprecated and now i cant use any nvidia docker image on my MAC

Where you able to use the M1 GPUs?

**Comment by saint1729** [comment]
+1

> > week ago i was able to run nvidia/cuda:latest on my MAC, but it became deprecated and now i cant use any nvidia docker image on my MAC
> 
> Where you able to use the M1 GPUs?

**Comment by pejrich** [comment]
+1

**Comment by ShahNewazKhan** [comment]
+1
