### ISSUE TITLE
NVIDIA Container Runtime on Jetson /  Typos

### ISSUE THREAD

**Issue by helmuthva** [NVIDIA/nvidia-docker#1013]
### 1. Issue or feature description

NVIDIA Container Runtime on Jetson documentation at https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson image references contain typos and image not accessible.

### 2. Steps to reproduce the issue

```
one:l4t hhva$ docker --version
Docker version 19.03.0-rc2, build f97efcc
one:l4t hhva$ docker login nvcr.io
Authenticating with existing credentials...
^[Login Succeeded
one:l4t hhva$ docker pull nvcr.io/nvidia/l4t-base:r32.2
Error response from daemon: pull access denied for nvcr.io/nvidia/l4t-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

The referenced pages contains the references`nvcr.io/nvidia/l4t-base:r32.2` and `nvcr.io/nvidian/nvidia-l4t-base:r32.1`  -  none of them  work and `nvidian` seems to be a typo.

**Comment by RenaudWasTaken** [comment]
Hello!

This is still unreleased, thanks for looking into it!

**Comment by helmuthva** [comment]
Hello,

Jetpack 4.2.1 has been released by now and references the NVIDIA Container Runtime in https://docs.nvidia.com/jetson/jetpack/release-notes/index.html.

Unluckily the `nvcr.io/nvidia/l4t-base:r32.2` image that is now consistently referenced in the Documentation cannot be pulled,  see below.

Is there anything special that has to be done before pulling?

```
one:jetson hhva$ docker --version
Docker version 19.03.0-rc2, build f97efcc
one:jetson hhva$ docker logout nvcr.io
Not logged in to nvcr.io
one:jetson hhva$ docker pull nvcr.io/nvidia/l4t-base:r32.2
Error response from daemon: pull access denied for nvcr.io/nvidia/l4t-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
one:jetson hhva$ docker login nvcr.io
Username: $oauthtoken
Password: 
Login Succeeded
one:jetson hhva$ docker pull nvcr.io/nvidia/l4t-base:r32.2
Error response from daemon: pull access denied for nvcr.io/nvidia/l4t-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by rsippl** [comment]
@helmuthva: build your own container image, like I did: https://github.com/jetsistant/docker-cuda-jetpack. I'm uploading a couple of images to Docker Hub right now.

**Comment by helmuthva** [comment]
@rsippl - in the process of it ... :-) Would however be nice if the official image would be pullable to reduce confusion for others @RenaudWasTaken

**Comment by helmuthva** [comment]
@rsippl - in case you need an approach to get CUDNN, TensorRT etc. into the containers as well you might want to have a look at https://github.com/helmuthva/jetson/blob/master/workflow/deploy/tools/nano-cuda-deb-extract

**Comment by rsippl** [comment]
Thanks for the hint, @helmuthva. I totally agree, this issue needs to be fixed -- @RenaudWasTaken, please reopen.

**Comment by RenaudWasTaken** [comment]
Image is live here: https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base

**Comment by jlucier** [comment]
Can anyone shed light on building images as it pertains specifically to including header files? I read the [docs](https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson) and can't really figure out the right strategy.

The examples (deviceQuery and nbody) both compile against CUDA, for which the header files are available at build time (via the l4t-base image I assume?). However, I need to compile a few things against TensorRT as an example, and `NvInfer.h` is nowhere to be found during build. Obviously the container runtime need not inject headers at actual runtime, but how should we go about populating the build environment with them?

Additionally, I want to move away from building images on the Jetson's themselves, so how is this intended to work when the NCR mounted parts (CUDA, cuDNN, TensorRT, etc.) aren't necessarily installed on the machine doing the building? Is it sufficient to install the _same_ versions on another machine expecting the headers will be the same? Or is the intention that you would pre-download and inject the Jetson versions of these libraries into the build context? Is this where multi-stage building comes in?

Please advise, thank you.

**Comment by ilanbiala** [comment]
It's also unclear to me how to get cuDNN and TensorRT available through the use of mount plugins. Can someone clarify? @RenaudWasTaken @helmuthva?

**Comment by ilanbiala** [comment]
Also, I've already set up the nvidia runtime as the default runtime, and yet when I build an image and run its container also with the nvidia runtime I don't see the cuDNN or TensorRT headers in `/usr/include/aarch64-linux-gnu/`.

**Comment by ilanbiala** [comment]
I checked the debug log while building a container, and I can see lines like:
```
I0813 22:19:33.187602 28881 nvc_info.c:154] selecting /usr/lib/aarch64-linux-gnu/libcudnn.so.7.5.0
...
I0813 22:19:33.191194 28881 jetson_mount.c:50] mounting /usr/lib/aarch64-linux-gnu/libcudnn.so.7.5.0 at /var/lib/docker/overlay2/78ec300c823921805fe85c76838d00b04e9c74823be0fece8bb7903e8aac07d6/merged/usr/lib/aarch64-linux-gnu/libcudnn.so.7.5.0
```
that indicate the cuDNN and TensorRT are being pulled in, but none of the header files for cuDNN or TensorRT are being pulled in. Why is that? Also, it seems like all of these libraries are only pulled in at build time, so how does this work when actually running the container?

**Comment by jlucier** [comment]
You're missing a fairly key bit about what the container **runtime** is for.

NCR patches in the runtime libraries, not the headers. Headers are not required at runtime. I also was curious if there was a solution for patching in headers at build time, but this stuff is all very new and it seems like it's the wild west out there. See #1032 for more discussion.

**Comment by ilanbiala** [comment]
@jlucier I'm building some libraries that require the headers as well, such as PyTorch. Those are required at build time, and my image is failing to build. #1032 didn't specifically answer how to include the headers, but did you find a way to do that?

**Comment by jlucier** [comment]
Answered in #1032, more relevant thread.
