### ISSUE TITLE
glxinfo SIGSEGV error

### ISSUE THREAD

**Issue by david-gwa** [NVIDIA/nvidia-docker#1014]
### 1. Issue or feature description

when run glxinfo in container,  it reports:
`Error: couldn't get an RGB, Double-buffered visual  ` 

when strace glxinfo, it shows:
`  libGLX_nvidia.so  libnvidia-tls.so,  libnvidia-glcor.so  No such file or directory `

so copy these libs from host to the container, `strace glxinfo` again, it shows:

```shell
readlink("/procs/113/exe",  "/usr/bin/glxinfo", 4095) = 16 
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
```
 
### 2. Steps to reproduce the issue

docker pull [docker image ](https://github.com/coreyryanhanson/dockerfiles/tree/master/glxgears)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

* uname -a
Linux e226af410012 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* nvidia-smi
Thu Jul 18 16:08:54 2019
| NVIDIA-SMI 384.130 Driver Version: 384.130

* docker --version
Docker version 18.09.6, build 481bc77

**Comment by rajatchopra** [comment]
` libnvidia-glcor.so` ? Something wrong there? Should have been `libnvidia-glcore.so`.
Can you run glxinfo on host? It seems that the library and the links are broken.

Also, the copy didn't work alright into the container. Can you also produce the output of 
`sudo nvidia-container-cli -k -d /dev/tty info`

**Comment by RenaudWasTaken** [comment]
I would suggest you follow the tutorial on our blog post :
https://devblogs.nvidia.com/gpu-containers-runtime/

The error you are seing is usually tied to your image not specifying the right runtime capabilities. You probably need to extend from the cudagl image: https://hub.docker.com/r/nvidia/cudagl

As well as add the display capability: 
```
ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES},display
```

or `docker run -it -e NVIDIA_DRIVER_CAPABILITIES=all nvidia/cudagl`

Here is the example dockerfile used in the blog post:https://gitlab.com/nvidia/samples/blob/master/cudagl/ubuntu16.04/nbody/Dockerfile
