### ISSUE TITLE
Run container fails due to not found in path

### ISSUE THREAD

**Issue by KacperLegowski** [NVIDIA/nvidia-docker#1019]
### 1. Issue or feature description
Fail to start container.
### 2. Steps to reproduce the issue
1. Install Jetpack 4.2.1 on Jetson Nano
2. Run 
`sudo docker run --runtime=nvidia --rm nvidia/cuda:10.1-base nvidia-smi`
3. Output:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.`

**sudo nvidia-docker version** outpus is:
`sudo nvidia-docker version
NVIDIA Docker: 2.0.3
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:51:35 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/arm64
  Experimental:     false`

**Ubuntu version**
Description:	Ubuntu 18.04.2 LTS
Release:	18.04

When I try to run
sudo docker run --rm --runtime=nvidia -ti nvidia/cuda

I get
standard_init_linux.go:207: exec user process caused "exec format error"

$ sudo nvidia-container-cli --load-kmods info
NVRM version: (null)
CUDA version: 10.0

Device Index: 0
Device Minor: 0
Model: NVIDIA Tegra X1
Brand: (null)
GPU UUID: (null)
Bus Location: (null)
Architecture: 5.3

**Comment by KacperLegowski** [comment]
When I try to run 
`sudo docker run --rm --runtime=nvidia -ti nvidia/cuda`

I get 
`standard_init_linux.go:207: exec user process caused "exec format error"`

$ sudo nvidia-container-cli --load-kmods info
NVRM version:   (null)
CUDA version:   10.0

Device Index:   0
Device Minor:   0
Model:          NVIDIA Tegra X1
Brand:          (null)
GPU UUID:       (null)
Bus Location:   (null)
Architecture:   5.3

**Comment by rajatchopra** [comment]
Two problems here:
1. `nvidia-smi` will not run on Jetson devices.. long story with nvml etc.
2. The image `nvidia/cuda` will not run on the Tegra architecture. The right image is `nvcr.io/nvidia/l4t-base:r32.2`. See this portion of the blog: https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson#building-cuda-in-containers-on-jetson

**Comment by rajatchopra** [comment]
Closing the issue. Please re-open if anyone feels the matter is not addressed yet.
