### ISSUE TITLE
Error: Package: nvidia-docker2-2.0.3-1.docker18.06.1.ce.noarch (nvidia-docker)

### ISSUE THREAD

**Issue by golisandeep3** [NVIDIA/nvidia-docker#1020]
### 1. Issue or feature description
Failed to install nvidia-docker-2 using yum package manager.
### 2. Steps to reproduce the issue

distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | \
sudo tee /etc/yum.repos.d/nvidia-docker.repo
yum install -y nvidia-docker2-2.0.3-1.docker18.06.1.ce.noarch

20:37:11 2019-07-22 03:37:11.345 | --> Processing Dependency: nvidia-container-runtime = 2.0.0-1.docker18.06.1 for package: nvidia-docker2-2.0.3-1.docker18.06.1.ce.noarch
20:37:11 2019-07-22 03:37:11.582 | Package nvidia-container-runtime is obsoleted by nvidia-container-runtime, but obsoleting package does not provide for requirements
20:37:11 2019-07-22 03:37:11.951 | --> Finished Dependency Resolution
20:37:11 2019-07-22 03:37:11.955 | Error: Package: nvidia-docker2-2.0.3-1.docker18.06.1.ce.noarch (nvidia-docker)
20:37:11 2019-07-22 03:37:11.955 |            Requires: nvidia-container-runtime = 2.0.0-1.docker18.06.1
20:37:11 2019-07-22 03:37:11.955 |            Available: nvidia-container-runtime-1.0.0-1.docker1.12.6.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.955 |                nvidia-container-runtime = 1.0.0-1.docker1.12.6
20:37:11 2019-07-22 03:37:11.955 |            Available: nvidia-container-runtime-1.0.0-1.docker17.03.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.955 |                nvidia-container-runtime = 1.0.0-1.docker17.03.2
20:37:11 2019-07-22 03:37:11.955 |            Available: nvidia-container-runtime-1.0.0-1.docker17.06.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.955 |                nvidia-container-runtime = 1.0.0-1.docker17.06.1
20:37:11 2019-07-22 03:37:11.955 |            Available: nvidia-container-runtime-1.0.0-1.docker17.06.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.0.0-1.docker17.06.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.0.0-1.docker17.09.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.0.0-1.docker17.09.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.0-1.docker1.12.6.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.0-1.docker1.12.6
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.0-1.docker1.13.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.0-1.docker1.13.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.0-1.docker17.03.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.0-1.docker17.03.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.0-1.docker17.06.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.0-1.docker17.06.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.0-1.docker17.09.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.0-1.docker17.09.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.0-1.docker17.09.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.0-1.docker17.09.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker1.12.6
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker1.13.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker1.13.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker17.03.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker17.03.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker17.06.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker17.06.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker17.09.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker17.09.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker17.09.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker17.09.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-1.1.1-1.docker17.12.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 1.1.1-1.docker17.12.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker1.12.6.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker1.12.6
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker1.13.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker1.13.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker17.03.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker17.03.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker17.06.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker17.06.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker17.09.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker17.09.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker17.09.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker17.09.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker17.12.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker17.12.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker17.12.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker17.12.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.03.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.03.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.03.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.03.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.06.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.06.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.06.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.06.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.06.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.06.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.09.0.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.09.0
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.09.1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.09.1
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.09.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.09.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.09.3.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.09.3
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.09.4.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.09.4
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-1.docker18.09.5.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-1.docker18.09.5
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-2.docker18.06.2.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-2.docker18.06.2
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-3.docker18.06.3.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-3.docker18.06.3
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-3.docker18.09.5.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-3.docker18.09.5
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-3.docker18.09.6.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-3.docker18.09.6
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-2.0.0-3.docker18.09.7.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 2.0.0-3.docker18.09.7
20:37:11 2019-07-22 03:37:11.956 |            Available: nvidia-container-runtime-3.0.0-1.x86_64 (nvidia-container-runtime)
20:37:11 2019-07-22 03:37:11.956 |                nvidia-container-runtime = 3.0.0-1
20:37:11 2019-07-22 03:37:11.956 |  You could try using --skip-broken to work around the problem

**Comment by RenaudWasTaken** [comment]
Hello!

The packages were broken yesterday, sorry about that.
We've released new packages yesterday, you should be good to upgrade now.

Thanks for reporting the issue, closing for now!
