### ISSUE TITLE
[l4t-base] Is there any way to install cicc on l4t-base:r32.2?

### ISSUE THREAD

**Issue by seiya0412** [NVIDIA/nvidia-docker#1024]
### 1. Issue or feature description
When I tried to build a CUDA application in a Docker image which is based on l4t-base:r32.2, the build was terminated with `cicc: not found` error.
I ran a l4t-base container and I found that `/usr/local/cuda/nvvm` did not exist in l4t-base docker image.

Is there a recommended way to install nvvm/cicc on l4t-base or do you have any plan to release a cicc-preinstalled version of l4t-base?

### 2. Steps to reproduce the issue
On Jetson Xavier (w/ JetPack 4.2.1),
```
git clone https://github.com/seiya0412/docker-libSGM_jetson.git
cd docker-libSGM_jetson
docker build -t libsgm_jetson .
```

**Comment by RenaudWasTaken** [comment]
Looking into this, hoping to release the fix soon :)
Thanks for bringing this up!

**Comment by RenaudWasTaken** [comment]
A new image is now up with the fix!

**Comment by seiya0412** [comment]
Successfully built! Thank you!

**Comment by rcoh** [comment]
I'm having the same issue in the r32.3.1 image

**Comment by prutschman** [comment]
I am as well

**Comment by KamelAbdelouahab** [comment]
I'm having the same problem on R32.3.1. Adding `/usr/local/cuda-10.0/nvvm/bin/` to my path didn't solve the issue

**Comment by pfichtner** [comment]
Directory /usr/local/cuda/nvvm missing again in r32.3.1 (r32.2 did work)

**Comment by OYTIS** [comment]
Same with the latest r32.4.2. @RenaudWasTaken, please reopen.

**Comment by srinivasbakki** [comment]
I couldn't build darknet in docker based on l4t-base:r32.2 with cuda. 
 /dev/null || pkg-config --libs opencv` -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand -L/usr/local/cudnn/lib64 -lcudnn -lstdc++
/usr/bin/ld: cannot find -lcuda
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: cannot find -lcublas
/usr/bin/ld: cannot find -lcurand
/usr/bin/ld: cannot find -lcudnn
collect2: error: ld returned 1 exit status
Makefile:168: recipe for target 'darknet' failed
make: *** [darknet] Error 1

Any help on this please ?
