### ISSUE TITLE
nvidia-docker: command not found

### ISSUE THREAD

**Issue by ChaooMa** [NVIDIA/nvidia-docker#1028]
Have done all the command：

> # Add the package repositories
> $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> $ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> $ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee > > /etc/apt/sources.list.d/nvidia-docker.list
> 
> $ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
> $ sudo systemctl restart docker

And then, do:
> nvidia-docker

Get an Error:
> nvidia-docker: command not found

Thanks.

**Comment by scaleoutsean** [comment]
How is that an issue?

**Comment by RenaudWasTaken** [comment]
Hello!
This is the expected behavior and is documented in the README. 

Please install the Legacy packages of you want the nvidia-docker cli.

**Comment by hygxy** [comment]
@RenaudWasTaken Hi, do you mean the following command in README:
- $ sudo apt-get update
- $ sudo apt-get --only-upgrade install docker-ce nvidia-docker2
- $ sudo systemctl restart docker

After that I still get this error:
- nvidia-docker: command not found

Any suggestions?

**Comment by PiseyYou** [comment]
same issue, after run`docker run --gpus '"device=0"' nvidia/cuda:9.0-base nvidia-smi` sucessfully, when nvidia-docker, it show command not found, have you solve these problems? @ChaooMa @hygxy

**Comment by hygxy** [comment]
@PiseyYou 
I didn't solve it yet, I just turn back use to nvidia-docker instead of nvidia-docker2

**Comment by whoszus** [comment]
same issue here @PiseyYou

**Comment by zzmingxxxx** [comment]
I've encountered the same issue... :(

**Comment by annasamt** [comment]
I also get the same error: nvidia-docker: command not found, although:
1) I have installed latest Docker version and 
2) followed the instructions from https://github.com/NVIDIA/nvidia-docker for Ubuntu 16.04 to install nvidia-docker
3) nvidia-drivers are also installed.

Reg. above comments on nvidia-docker2, this is a deprecated version so I see no reason to use it.

Can anyone please support us on this issue?
Thanks in advance

**Comment by ccssmania** [comment]
I solved the problem running sudo apt-get install nvidia-docker2

**Comment by zzmingxxxx** [comment]
If you have chosen to install the newest nvidia enabled docker, "nvidia-container-toolkit", follow https://github.com/NVIDIA/nvidia-docker#quickstart, in order to run a docker contain instance with nvidia GPU capacity enabled, just use command like "$ docker run --gpus all nvidia/cuda:9.0-base nvidia-smi", no need use legacy "nvidia-docker" command.

**Comment by gocpplua** [comment]
> I solved the problem running sudo apt-get install nvidia-docker2

E: Unable to locate package nvidia-docker2

**Comment by arkadyeye** [comment]
> > I solved the problem running sudo apt-get install nvidia-docker2
> 
> E: Unable to locate package nvidia-docker2

You should add the Keys
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

look [at the documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)

**Comment by gocpplua** [comment]
> > > I solved the problem running sudo apt-get install nvidia-docker2
> > 
> > 
> > E: Unable to locate package nvidia-docker2
> 
> You should add the Keys
> 
> ```
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
>    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
>    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> ```
> 
> look [at the documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)

i will try it， thanks

**Comment by ndvbd** [comment]
Any solutions?

**Comment by Sadwy** [comment]
use `--gpus` instead of `nvidia-docker`
for example, replace this command:
```shell
nvidia-docker run -it -v `pwd`/../data:/dataset --shm-size 16g my-container /bin/bash
```
with this command:
```shell
docker run --gpus all -it -v `pwd`/../data:/dataset --shm-size 16g my-container /bin/bash
```

there is an another example using `--gpus` in [wiki](https://github.com/NVIDIA/nvidia-docker/wiki#i-have-multiple-gpu-devices-how-can-i-isolate-them-between-my-containers):
```shell
docker run --gpus device=2,3 nvidia/cuda:9.0-base nvidia-smi
```
