### ISSUE TITLE
Underlying dependencies change across pulls for a fixed container tag

### ISSUE THREAD

**Issue by adragoset** [NVIDIA/nvidia-docker#1030]
### 1. Issue or feature description
When using nvidia docker containers underlying dependencies change across pulls for a fixed container tag which indicates tags are being overwritten on docker hub

### 2. Steps to reproduce the issue

Pull an nvidia docker container nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

nccl versions change to new versions from day to day which breaks several build processes im using this container for.

Is there a way to use a truly unique tagged container that will not be overwritten with new versions in docker hub? Overwriting release tags is extremely bad practice for exactly the reason that processes built on whats thought to be a static environment break when that environment gets overwritten or patched without a separate release tag.

**Comment by RenaudWasTaken** [comment]
Sorry I never answered this question, I'll restart a thread internally on this.

> Overwriting release tags is extremely bad practice for exactly the reason that processes built on whats thought to be a static environment break when that environment gets overwritten or patched without a separate release tag.

Pretty much everyone does it (e.g: ubuntu's 16.04 tag), I think what you are pointing here is that you would like to have a more stable tag to point to where when we update the dependencies you have stronger guarantees as to what will change and how it will change (i.e: not breaking backwards compat).
