### ISSUE TITLE
Building Jetson images for use with NCR

### ISSUE THREAD

**Issue by jlucier** [NVIDIA/nvidia-docker#1032]
This is a higher level question regarding building container images for Jetson devices specifically, which I don't think is really documented sufficiently yet. Please excuse me if I've missed some issues or docs that explain all the following, but I have sincerely spent days on this. Hopefully other people will find this discussion useful.

---

I'm confused as to how we should be building container images with NCR + the l4t-base image. What libraries (or stubs) and headers are provided, which need to be installed, and which are overwritten at runtime? The build process has been quite confusing thus far, and yielding far larger containers than I was expecting.

My application uses TensorRT mainly, so we indirectly require CUDA and cuDNN as well because of that. From digging through the mount-plugin files at `/etc/nvidia-container-runtime/host-files-for-container.d`, I can see that the NCR is mounting specifically TensorRT, CUDA, cuDNN, a large amount of L4T specifc things, etc. Thus, I would expect the base image to have them stubbed, include headers, and not have to install those libraries in my image.

From the samples and digging through the base image (using runtime = `runc` and `nvidia` to see the differences) I can see that cuda headers and stubs for the cuda library exist in the base image. This enables one to compile the cuda samples at build time. However, when compiling my code which requires TensorRT none of the required headers are present, but neither are the compiled libraries or stubs for them. Where are we intended to get these? I've seen #1013, and found related docker files like [this](https://github.com/helmuthva/jetson/blob/master/workflow/deploy/ml-base/src/Dockerfile) which seemingly copy the deb files from SDKManager and install the libs/headers into the container, but isn't that defeating the whole purpose of NCR?

Why are we installing libraries in the image that will just getting overwritten at runtime? Is NCR just handling CUDA and not dealing with TensorRT (despite the `tensorrt.csv` in the `/etc/nvidia-container-runtime/host-files-for-container.d`)? Are we supposed to install the version of TensorRT we'd like to use into our image, then rely on NCR to patch in just the local Jetson's CUDA binary? I assume I'm misunderstanding something here.

My goal is to create a portable container that will be able to run across Jetson devices, as advertised for this nvidia docker stuff. However, everything I've seen online as it pertains to the TensorRT/CUDA relationship suggests that we're still installing versions of these libs into the images and rendering them non-portable across L4T releases. Some guidance/clarification would be greatly appreciated, thank you.

**Comment by RenaudWasTaken** [comment]
The current support for images is still very early access. We expect to be publishing full containers in the future.

Currently as you've noticed, some of the compile time libraries are present in the container at build time, others aren't. There is definitely a size constraint here that is hard to ignore and we are working internally to reduce the overall size of our components.

In the meantime you can use a simple workaround which would be to set the nvidia runtime as the default runtime. It would allow you to have all the libraries exposed at build time.
https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup

**Comment by jlucier** [comment]
Will do, I suppose that fixes the library issues.

What about headers? Is there are good solution for getting them into the image (possibly using some experimental syntax in the Dockerfile for build-time mounts)? Are we stuck just installing the libraries, especially when building on non-jetson devices?

Also, how portable is code compiled against different major versions of CUDA/cuDNN/TensorRT? If the point is that these libraries don't exist in the container, but on the device itself, isn't that pretty risky and a bit of an anti-pattern as far as containerization goes? Would we be better off installing TensorRT and whatnot in the containers and using NCR just for the CUDA binary bundled with the drivers?

**Comment by RenaudWasTaken** [comment]
> Also, how portable is code compiled against different major versions of CUDA/cuDNN/TensorRT?

I don't have a good answer for TensorRT, but CUDA and cuDNN should have the exact same guarantees than on x86. Meaning that as long as you dynamically link against libcuda.so, your code will be backwards compatible.

**Comment by ilanbiala** [comment]
@RenaudWasTaken is there a way to include the headers in the image? The headers are also needed when building from source.

**Comment by jlucier** [comment]
This should give you a starting point: https://github.com/jetsistant/docker-cuda-jetpack/blob/master/Dockerfile.base

You can download the deb files from nvidia (shown in that ^ dockerfile), install the relevant "-dev" packages into the build environment, compile code, then uninstall them before completing your image. That's more or less what I was doing when trying this, however we have some PCB compatibility issues with L4T 32.1/2, so we've abandoned that OS / NCR for now. Here's a good reference [Dockerfile](https://github.com/open-horizon/cogwerx-jetson-tx2/blob/master/tensorrt/Dockerfile.tensorrt3.0-CUDA9) for images intended for L4T 28.2 (pre-NCR). That's pretty much what I'm using in production.

P.S. We opted using L4T 28.2 without NCR, because the investment required to get 32.2 up and running with our hardware was too much for such little workflow improvement, maybe even a detraction honestly. The point of containerization is "build once, run anywhere", and it gives me some amount of anxiety building against versions of libraries (CUDA, cuDNN, TensorRT) that will be different in the field. Not to mention the lack of tooling for the build process (having to install/delete headers and whatnot).

The moral of the story is pretty clearly stated in the docs: "this software is beta". It's simply not ready for production workflows. It needs tooling, documentation, validation, etc.
