### ISSUE TITLE
Performance problem with Theano container on AWS GPU instance

### ISSUE THREAD

**Issue by Fengyboy** [NVIDIA/nvidia-docker#104]
I wrote a piece of Theano/Lasagne code and am trying to deploy it on 2 AWS G2 GPU instances with Grid K520 and an AWS EC2 standard CPU instance (all running the standard AWS Ubuntu 14.04 image), the settings are as follows:
1. One GPU instance with `CUDA 7.5.18`, `Theano/Lasagne` etc. installed and the code running naively on the host
2. The other instance with `Nvidia 361.42` driver, `docker` and `nvidia-docker` installed, a customised docker image based on `nvidia-docker/ubuntu-14.04/cuda/7.5/devel/` is pulled and its container is being run
3. The CPU instance with only `docker` installed, the same `docker image` is pulled and its container is being run

My findings on the runtimes are very strange. The timings of the same `segmentation` procedure are `Segmentation took 0:00:02.855872 (h:m:s)`, `Segmentation took 0:00:12.879373 (h:m:s)`, `Segmentation took 0:00:05.176853 (h:m:s)`. As you can see the GPU instance running `nvidia-docker` is much slower the GPU instance running naively, and even more than 2 times slower than the CPU instance running `docker`. So could someone please tell me if this is normal? Do I need to do something special for the `docker container` to use all the available GPU resources, e.g. `CUDA cores` and `VRAM`? Many thanks in advance.

**Comment by flx42** [comment]
Performance should be the same, I tested multiple ML/DL frameworks and performance was identical.

Theano is a bit particular though, are you sure you are using the same theanorc file?
Also, Theano compiles CUDA code on the fly inside the container and then caches the result for future execution. If you rerun the segmentation code inside the same container, is the execution time still the same?

**Comment by flx42** [comment]
The only difference could be network or filesystem I/O, it might be slower inside a container (but that's not a `nvidia-docker` problem). If possible, use host volumes for your input and output directories.

**Comment by Fengyboy** [comment]
@flx42 Thanks for the quick reply. I am using the same `.theanorc` file for running in the container and running natively. I ran the `segmentation code` in the same container multiple times, and the execution time stayed the same. Later on, I also measured the part of code doing forward pass of the network, which did not involve network or filesystem I/O, and the situation did not change at all. 

I used `nvidia-docker run -it docker-image-name /bin/bash` to start a container, am I doing anything wrong here?

**Comment by flx42** [comment]
The command you used looks fine.

Recently I tried `convnet-benchmarks`  with Theano and saw no performance difference, you could try that.
Also try to use `nvidia-smi` when you run on the GPU and check if there is a difference in the GPU utilization percentage.

**Comment by Fengyboy** [comment]
@flx42 After some experimenting with the `Dockerfile`, I've resolved the problem. It was due to that `cuDNN` was not installed properly in the docker image, and thus was not used by the container. The new timing is `Segmentation took 0:00:02.337906 (h:m:s)`, which is identical to running on the host. 

This is wired, as the convolution layers and pooling layers used in my code are set to be the standard ones of `Theano`, instead of the `cuDNN` based implementation. In any case, thank you very much for the help.

**Comment by KleinYuan** [comment]
I'm running a similar issue:

Issue description: 
I run a caffe based algorithm on the EC2 natively with CUDA 7.0 and cuDNN 3, only taking ~*3 sec*;
However, when built with https://gitlab.com/nvidia/cuda/blob/ubuntu14.04/7.0/devel/cudnn3/Dockerfile , the performance goes down to ~ *15 sec*.

I build with cmake and in the summary it shows that

```
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Open)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.8)
--   CUDA              :   Yes (ver. 7.0)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
--   cuDNN             :   Yes
```

I'm pretty sure it doesn't run against CPU cuz I tested it, which takes ~ 28 sec.

Any thoughts on that?

@Fengyboy I wonder whether it also resulted from CUDA installation not correct? But the summary seems saying it's ok.

**Comment by flx42** [comment]
@KleinYuan please open a new issue instead.

**Comment by KleinYuan** [comment]
Made it work as expected... Same speed as native one. I changed several things and am gonna run more tests to identify the final cause. Will post it here in case others run into same issue.

**Comment by KleinYuan** [comment]
I changed several things, which made it work:
1) I changed caffe/cmake/Cuda.cmake line7, which was `set(Caffe_known_gpu_archs "20 21(20) 30 35  50")` to `set(Caffe_known_gpu_archs "20 21(20) 30 35 37 50")`, i.e., adding `37` in there since I noticed the native one detect the GPU arch during the build as `sm_37` while nvidia-docker detection failed

2)When I run cmake, I added a flag to force it using `sm_37`: `cmake -arch=sm_37 -DBLAS=open .. ` 

3) One more thing that I changed which might not be the cause is that before I installed both `ATLAS` and `OpenBLAS`. And I removed `libatlas-base-dev ` from installation

**Comment by flx42** [comment]
Yes OpenBLAS is probably faster here. You should also consider using a newer version of cuDNN (v5).

**Comment by KleinYuan** [comment]
@flx42 Yes, OpenBLAS is way faster than ATLAS since more CPUs could be used. We will move on to v5 versions once everything is setup. Thanks
