### ISSUE TITLE
RHEL 8 Support

### ISSUE THREAD

**Issue by bdurepo1** [NVIDIA/nvidia-docker#1040]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

Request RHEL 8 support from nvidia docker repository.

### 2. Steps to reproduce the issue

NA 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by RenaudWasTaken** [comment]
@Ethyling @rajatchopra can on you take a stab at testing if the normal RHEL 7.5 packages work on RHEL8 ?

If so we'll just symlink the RHEL8 folder to the RHEL 7.5 folder :)

**Comment by nhubbard** [comment]
I'd like to request that this is re-opened. Information about Docker in RHEL 8 is available [here](https://red.ht/2ZnZCly). If you don't have a Red Hat Access subscription, I'll save you the cost:

> # Is the `docker` package available for Red Hat Enterprise Linux 8?
> 
> ### Environment
> 
> * Red Hat Enterprise Linux 8
> 
> ### Issue
> 
> * I can't find the `docker` package in RHEL 8.
> * The `docker` package is not available from the Red Hat repositories.
> 
> ### Resolution
> 
> * The `docker` package is not shipped or supported by Red Hat for Red Hat Enterprise Linux (RHEL) 8. The Docker container engine is replaced by a suite of tools in the Container Tools module.
> * The `podman` container engine replaced `docker` as the preferred, maintained, and supported container runtime of choice for Red Hat Enterprise Linux 8 systems. Podman provides a docker compatible command line experience enabling users to find, run, build, and share containers. Podman uses Buildah and Skopeo as libraries for the build and push.
> * The `buildah` utility replaced `docker build` as the preferred, maintained, and supported container images build tool in Red Hat Enterprise Linux 8 systems.
> * The `skopeo` utility replaced `docker push` as the preferred, maintained and supported utility for moving container images between registries, and container engines.
> * For an overview of all of these tools, please see: [Building, running and managing containers - Chapter 1. Starting with containers](https://red.ht/2Z8wYFR)
> * For a deeper dive on podman specifically, please see: [Building, running and managing containers - Chapter 7. Container command line reference](https://red.ht/2MtO1vq)
> 
> ### Root Cause
> 
> * The `docker` package has been replaced by the `container-tools` module.

Because of this change, we either need to:
* Look into integrating with Podman ***best solution, most intensive***
* Only work with RHEL 7 until it leaves extended support, and actively recommend using another operating system ***last resort if Podman is incapable***

**Comment by RenaudWasTaken** [comment]
Ah sorry I didn't mean to close this issue.

Podman should already be supported if you install the toolkit package (`yum install nvidia-container-toolkit`)

**Comment by bdurepo1** [comment]
> Ah sorry I didn't mean to close this issue.
> 
> Podman should already be supported if you install the toolkit package:
> `yum install nvidia-container-toolkit`

Please update this webpage to reference the RHEL 8 repository if there is one.
https://nvidia.github.io/nvidia-docker/

**Comment by bdurepo1** [comment]
Please reopen this issue so that we can track integration of podman.
