### ISSUE TITLE
[performence problem] tensor2tensor run slower 6.37% in container than on the host

### ISSUE THREAD

**Issue by fengyul** [NVIDIA/nvidia-docker#1050]
1. Q: When I run tensor2tensor, I found the speed in container is much slower (6.37%) than on the host. What happened with this and how can I reduce the performance loss? We are sure that the envs are same. Please see the blow to get more details.
2. ENV：
ubuntu16.04 (kernel 4.4.0-116-generic)
nvidia-container-toolkit 1.0.1-1
anaconda3

3. the container image and the env. 
We install the anaconda3 in docker image and install the tensorflow by `conda install cudatoolkit=10.0.130 tensorflow`. And we also install the anaconda3 on the host by the same way.
The 'docker run' command is `docker run --gpus all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility -e NVIDIA_VISIBLE_DEVICES=all -it  -v /home/pai/Desktop/code:/home/ anaconda:v1 bash`
4. the test command in docker and on the host:
 `time  t2t-trainer   --generate_data   --data_dir=~/t2t_data   --output_dir=~/t2t_train/qa  --problem=babi_qa_concat_task1_10k  --model=transformer   --hparams_set=transformer_small   --train_steps=20000   --eval_steps=10`
5. the test results:
the time in docker is 5m14s, but the time on the host is 4m56s. We tried many times.
![image](https://user-images.githubusercontent.com/20762421/63489180-02331300-c4e4-11e9-8f54-2254f211898e.png)
![image](https://user-images.githubusercontent.com/20762421/63489199-0fe89880-c4e4-11e9-9fd2-4abdbf1fae2e.png)

But  when we test the intel's benchmark and nvidia's bandwidthtest, we didnot find such big performence loss.
Left is on the host, right is in docker.
![image](https://user-images.githubusercontent.com/20762421/63489525-f267fe80-c4e4-11e9-94fb-36c1d47b6b2d.png)

**Comment by RenaudWasTaken** [comment]
Try with `--security-opt seccomp=unconfined --security-opt apparmor=unconfined` these tend to have a noticeable performance impact

**Comment by fengyul** [comment]
> Try with `--security-opt seccomp=unconfined --security-opt apparmor=unconfined` these tend to have a noticeable performance impact

It helped, but still has 1.0% of performence loss. Is that normal?

**Comment by fengyul** [comment]
> Can you link to the container image?

Sorry to reply so late. 
What dose the 'link to container image' means? I couldn't get your point.

**Comment by RenaudWasTaken** [comment]
It's probably due to some of the other namespace features you can always try with "--net=host --ip=host, ....
I would expect that these would account for that 1% difference
