### ISSUE TITLE
packer automation templates

### ISSUE THREAD

**Issue by lmeyerov** [NVIDIA/nvidia-docker#1053]
We've been using Packer to setup nvidia environments for AWS and  Azure. They take & update a base OS, install nvidia drivers, docker, and the nvidia-docker runtime. This is especially helpful in Azure as deriving from the Azure Marketplace NGC image causes certain broken behavior, requiring a manual bootstrap instead. 

Would it make sense to contribute a folder like `/automation/packer/templates/<cloud>/<os>` ? We're maintaining on our own, but seems a bit silly.

**Comment by RenaudWasTaken** [comment]
Hello!

With the driver container and the soon to be runtime container, packer templates should mainly be just:
- docker run -it ... nvidia/driver:driver-version
- docker run -it ... nvidia/container-toolkit:latest

I'm happy to link in the docs to any packer templates on your own repos though :)!

**Comment by lmeyerov** [comment]
@RenaudWasTaken I may be misunderstanding -- packer is to install the host driver, not create the container. Or are nvidia drivers and nvidia docker runtimes no longer necessary in the host?

**Comment by lmeyerov** [comment]
+ @felipeblazing @mike-wendt (following convs that blazing had similar issues)

**Comment by RenaudWasTaken** [comment]
Right now there's still some host config but there's work being done to help with reducing that.
For the driver see this wiki page: https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta)

By the way this wouldn't be virtualization :)

**Comment by lmeyerov** [comment]
Yep that's the problem, e.g., all the cloud/OS/orchestrator-specific host code in https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta). 

It sounds like you're saying this repo is scoped to docker-only and not host automation (which is needed for the forseeable future). Maybe the `NVIDIA/samples` repo used for this repo's host automations or maybe the GPU CI effort would be more appropriate place for host automation scripts across clouds/OS's?
