### ISSUE TITLE
cudaSuccess (48 vs. 0) no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by chaosRLo** [NVIDIA/nvidia-docker#1055]
I use nvcr.io/nvidia/digits:17.10 to run mnist classication by caffe and fined these error
cudaSuccess (48 vs. 0) no kernel image is available for execution on the device

how i solve these problem?

my environment as below
ubuntu 16.04
CUDA Version 8.0.61
cuDNN Version 6.0.21

**Comment by RenaudWasTaken** [comment]
Hello!

Please fill the issue template. Feel free to open a new issue with the correct information :)
