### ISSUE TITLE
nvidia-docker2 for SUSE Linux Does Not exist

### ISSUE THREAD

**Issue by rohank2002** [NVIDIA/nvidia-docker#1057]
I have been trying to install nvidia-docker2 on SUSE Linux. The nvidia-docker repo has been updated 5 days ago with a version for SUSE Linux.

### 1. Issue or feature description
The repo for Nvidia docker 2 for SLES does not exist.

### 2. Steps to reproduce the issue
`
$ zypper ar https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo
`
ERROR:
File '/nvidia-docker/sles15/nvidia-docker.repo' not found on medium 'https://nvidia.github.io/'

Details of my system:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:03:00.0 Off |                    0 |
| N/A   84C    P0    53W /  70W |  14723MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:82:00.0 Off |                    0 |
| N/A   60C    P0    30W /  70W |    205MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Docker version 19.03.1, build 74b1e89e8ac6
SUSE Linux Enterprise Server 15

**Comment by Ethyling** [comment]
Hey, this should be working for opensuse-leap15.1 now

**Comment by dkuchay** [comment]
this package for opensuse looks to have been last updated here, upon this request. We are on opensuse 15.3 now and errors are same as OP.
