### ISSUE TITLE
Restrict CUDA cores and GPU memory resources at the container level

### ISSUE THREAD

**Issue by chasenicholl** [NVIDIA/nvidia-docker#1059]
### 1. Issue or feature description

Maybe this is possible, but I'm failing to find any documentation?

Add the ability to limit available CUDA cores and GPU memory per container, similar to how one can limit CPUs and Memory resources. This would be extremely helpful when running multiple GPU intensive container tasks on a machine with one GPU device. `NVIDIA_VISIBLE_DEVICES` Lets you isolate to a card, but, it would be wonderful to restrict resources on a device level as well.

i.e. Say my GPU has 2048 available CUDA cores, being able to do something like....

`--cuda-cores=1024 --gpu-memory=4gb` Now my container only has access to have my half my GPU's resources, and I could safely run 2 containers at once without running into resource allocation issues.

For example, in Tensorflow, it attempts to internally load balance the allocation, but I find it fails under heavy load, it would be _wonderful_ if you could virtualise a single GPU device, just like one can with CPU/Memory resources.

**Comment by ppomelo** [comment]
[https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL)](url)
I think you can do it with MPS if your GPU support it. The compute resources can be limited by the parameter "CUDA_MPS_ACTIVE_THREAD_PERCENTAGE". And I recommand to limit memory resources in your code.

**Comment by RenaudWasTaken** [comment]
Hello!

As mentioned above you can somewhat do it with MPS but this isn't really supported in the NVIDIA stack.

We don't really have a good software answer for fine grained control.

**Comment by lhty24** [comment]
Hi @chasenicholl  , I'm facing the same issue. Did you find another way to allocate gpu resources by any chance? Thx in advance :)

**Comment by chasenicholl** [comment]
@lhty24 I solved the issue by calculating my needed parallelism up front. Instead of running multiple Docker Containers on the same host, of which would compete for GPU resources, I run the smallest host possible so I end up with 1 container per host in my deployment.

It's not ideal, but solves the problem for me. Ideally, we could virtualize GPU resources in the same way Docker lets you virtualize / gate CPU and Memory.

**Comment by mortium91** [comment]
Wondering if this still isnt possible? I would also want to limit the gpu memory usage per container level.
