### ISSUE TITLE
nvidia-docker | 2016/06/06 22:49:17 Error: Could not load UVM kernel module

### ISSUE THREAD

**Issue by martende** [NVIDIA/nvidia-docker#106]
I have just installed nvidia-docker and receive
on ubuntu 14

```
sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2016/06/06 22:49:17 Error: Could not load UVM kernel module

```

**Comment by 3XX0** [comment]
How did you install the NVIDIA drivers?
Can you try doing `nvidia-modprobe -u -c=0` in a terminal?

**Comment by martende** [comment]
I have just used ubuntu packages 
```
root@belka2-500-311ng:/home/belka# nvidia-modprobe -u -c=0 
root@belka2-500-311ng:/home/belka# 

```

**Comment by flx42** [comment]
After doing that, can you retry your initial command?

**Comment by martende** [comment]
```
root@belka2-500-311ng:/home/belka# nvidia-modprobe -u -c=0 
root@belka2-500-311ng:/home/belka# sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2016/06/07 18:49:33 Error: unsupported CUDA version: driver 7.0 < image 7.5

```

**Comment by flx42** [comment]
It means your driver is too old to run CUDA 7.5 code, you must either install a newer driver, or run CUDA 7.0 containers: `nvidia-docker run --rm nvidia/cuda:7.0 nvidia-smi`

Did you install the `nvidia-modprobe` package through `apt` after your first message? If the `nvidia-modprobe` binary was present, it's surprising that it failed.

**Comment by martende** [comment]
> Did you install the nvidia-modprobe package through apt after your first message? If the nvidia-modprobe binary was present, it's surprising that it failed.
