### ISSUE TITLE
nnvidia-container-cli: initialization error: cuda error: invalid device ordinal\\\\n\\\"\"": unknown.  

### ISSUE THREAD

**Issue by jobvarkey** [NVIDIA/nvidia-docker#1060]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by jobvarkey** [comment]
I am running Ubuntu 18.04 and Docker 19.03. successfully Installed nvidia-docker as per the documentation. Now i am trying to test it CUDA image using command 

'docker run --gpus all nvidia/cuda:9.0-base nvidia-smi' but getting the following error:  

 docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0  --pid=9566 /var/lib/docker/overlay2/fc4fb6106474edc50c26ae325ce82884816db6cec9c09001f682ec7502e476e0/merged]\\\\nnvidia-container-cli: initialization error: cuda error: invalid device ordinal\\\\n\\\"\"": unknown. ERRO[0000] error waiting for container: context canceled. 

Any help to resolve this is greatly appreciated..

**Comment by Ethyling** [comment]
Hey,

Could you provide us the libnvidia-container logs? You can follow this link to enable the logging https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting

**Comment by RenaudWasTaken** [comment]
Please fill the template, this helps us debug your issue.
Feel free to reopen an issue with the correct debug information :)

**Comment by DamiaPoquet** [comment]
Hi!

I'm having the same issue, fresh install on Ubuntu 18.04.3 wih Docker 19.03.4 and I got the same error. Here you are some data:

` nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I1019 11:22:23.704461 2426 nvc.c:281] initializing library context (version=1.0.5, build=13b836390888f7b7c7dca115d16d7e28ab15a836)
I1019 11:22:23.704504 2426 nvc.c:255] using root /
I1019 11:22:23.704510 2426 nvc.c:256] using ldcache /etc/ld.so.cache
I1019 11:22:23.704515 2426 nvc.c:257] using unprivileged user 1000:1000
W1019 11:22:23.710159 2427 nvc.c:186] failed to set inheritable capabilities
W1019 11:22:23.710203 2427 nvc.c:187] skipping kernel modules load due to failure
I1019 11:22:23.710382 2428 driver.c:133] starting driver service
I1019 11:22:23.816925 2426 driver.c:233] driver service terminated with signal 15
nvidia-container-cli: initialization error: cuda error: invalid device ordinal
`

`sudo dmesg
[  318.488140] NVRM: GPU 0000:04:00.0: RmInitAdapter failed! (0x23:0x56:498)
[  318.488275] NVRM: GPU 0000:04:00.0: rm_init_adapter failed, device minor number 0
`

**Comment by kfryklund** [comment]
I recommend running "nvidia-smi".  This helped me troubleshoot the issue.  In my case it had to do with insufficient power.

**Comment by flavienbwk** [comment]
Personally, I've just restarted and it worked again.

**Comment by jobvarkey** [comment]
Thanks for the update.. Yes, the restart worked.. this can be closed. Thanks

**Comment by murthy95** [comment]
@Ethyling  I face the same problem I am unable to run container using --gpus option. 
I get this error 
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.`

This is what is saved under my logs
`-- WARNING, the following logs are for debugging purposes only --

I0408 11:20:16.021933 850 nvc.c:281] initializing library context (version=1.0.7, build=b71f87c04b8eca8a16bf60995506c35c937347d9)
I0408 11:20:16.022240 850 nvc.c:255] using root /
I0408 11:20:16.022310 850 nvc.c:256] using ldcache /etc/ld.so.cache
I0408 11:20:16.022405 850 nvc.c:257] using unprivileged user 65534:65534
W0408 11:20:16.022518 850 nvc.c:166] skipping kernel modules load due to user namespace
I0408 11:20:16.022867 855 driver.c:133] starting driver service
I0408 11:20:16.049609 850 driver.c:233] driver service terminated with signal 15`
 
I have the latest driver installed 440.64.00  and I installed `nvidia-container-toolkit` using the instructions from [here](https://github.com/NVIDIA/nvidia-docker#nvidia-container-toolkit) on my ubuntu 16.04 machine.

**Comment by Ethyling** [comment]
Hi @murthy95, the error seems to be different. I would recommend you to open another issue following the issue template.

**Comment by murthy95** [comment]
@Ethyling  I opened a new issue. please check [here](https://github.com/NVIDIA/nvidia-docker/issues/1245).

**Comment by tongchao199** [comment]
I use nvidia-container-cli reload kernel modules, fix this problem。



error info
  ```shell
  root@my-gpu-ser:~$ nvidia-container-cli info
  nvidia-container-cli: initialization error: cuda error: unknown error
  
  root@my-gpu-ser:~$ nvidia-container-cli list
  nvidia-container-cli: initialization error: cuda error: unknown error
  ```

correct info
  ```shell
  root@my-gpu-ser:~$ lsmod | grep nvidia
  nvidia              17900596  141
  ipmi_msghandler        56032  1 nvidia

  root@my-gpu-ser:~$ nvidia-container-cli -k -d /dev/tty info

  -- WARNING, the following logs are for debugging purposes only --

  I1225 03:31:09.129585 1885 nvc.c:281] initializing library context (version=1.0.0, build=881c88e2e5bb682c9bb14e68bd165cfb64563bb1)
  I1225 03:31:09.129707 1885 nvc.c:255] using root /
  I1225 03:31:09.129724 1885 nvc.c:256] using ldcache /etc/ld.so.cache
  I1225 03:31:09.129736 1885 nvc.c:257] using unprivileged user 65534:65534
  I1225 03:31:09.134168 1886 nvc.c:191] loading kernel module nvidia
  I1225 03:31:09.134656 1886 nvc.c:203] loading kernel module nvidia_uvm
  I1225 03:31:09.218783 1886 nvc.c:211] loading kernel module nvidia_modeset
  I1225 03:31:09.283210 1920 driver.c:133] starting driver service
  I1225 03:31:09.421667 1885 nvc_info.c:433] requesting driver information with ''
  I1225 03:31:09.423306 1885 nvc_info.c:147] selecting /usr/lib64/vdpau/libvdpau_nvidia.so.418.67
  I1225 03:31:09.423932 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-tls.so.418.67
  I1225 03:31:09.424736 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-ptxjitcompiler.so.418.67
  I1225 03:31:09.425863 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-opencl.so.418.67
  I1225 03:31:09.425937 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-ml.so.418.67
  I1225 03:31:09.426779 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-ifr.so.418.67
  I1225 03:31:09.427466 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-glsi.so.418.67
  I1225 03:31:09.428336 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-glcore.so.418.67
  I1225 03:31:09.429235 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-fbc.so.418.67
  I1225 03:31:09.429340 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-fatbinaryloader.so.418.67
  I1225 03:31:09.430157 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-encode.so.418.67
  I1225 03:31:09.430972 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-eglcore.so.418.67
  I1225 03:31:09.432136 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-compiler.so.418.67
  I1225 03:31:09.433283 1885 nvc_info.c:147] selecting /usr/lib64/libnvidia-cfg.so.418.67
  I1225 03:31:09.434236 1885 nvc_info.c:147] selecting /usr/lib64/libnvcuvid.so.418.67
  I1225 03:31:09.434689 1885 nvc_info.c:147] selecting /usr/lib64/libcuda.so.418.67
  I1225 03:31:09.435728 1885 nvc_info.c:147] selecting /usr/lib64/libGLX_nvidia.so.418.67
  I1225 03:31:09.436583 1885 nvc_info.c:147] selecting /usr/lib64/libGLESv2_nvidia.so.418.67
  I1225 03:31:09.437132 1885 nvc_info.c:147] selecting /usr/lib64/libGLESv1_CM_nvidia.so.418.67
  I1225 03:31:09.437992 1885 nvc_info.c:147] selecting /usr/lib64/libEGL_nvidia.so.418.67
  I1225 03:31:09.438917 1885 nvc_info.c:147] selecting /usr/lib/vdpau/libvdpau_nvidia.so.418.67
  I1225 03:31:09.439432 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-tls.so.418.67
  I1225 03:31:09.439947 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-ptxjitcompiler.so.418.67
  I1225 03:31:09.440746 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-opencl.so.418.67
  I1225 03:31:09.441454 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-ml.so.418.67
  I1225 03:31:09.442324 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-ifr.so.418.67
  I1225 03:31:09.443718 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-glsi.so.418.67
  I1225 03:31:09.445824 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-glcore.so.418.67
  I1225 03:31:09.446514 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-fbc.so.418.67
  I1225 03:31:09.447132 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-fatbinaryloader.so.418.67
  I1225 03:31:09.447863 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-encode.so.418.67
  I1225 03:31:09.448790 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-eglcore.so.418.67
  I1225 03:31:09.449402 1885 nvc_info.c:147] selecting /usr/lib/libnvidia-compiler.so.418.67
  I1225 03:31:09.450498 1885 nvc_info.c:147] selecting /usr/lib/libnvcuvid.so.418.67
  I1225 03:31:09.451069 1885 nvc_info.c:147] selecting /usr/lib/libcuda.so.418.67
  I1225 03:31:09.453065 1885 nvc_info.c:147] selecting /usr/lib/libGLX_nvidia.so.418.67
  I1225 03:31:09.453681 1885 nvc_info.c:147] selecting /usr/lib/libGLESv2_nvidia.so.418.67
  I1225 03:31:09.454241 1885 nvc_info.c:147] selecting /usr/lib/libGLESv1_CM_nvidia.so.418.67
  I1225 03:31:09.455188 1885 nvc_info.c:147] selecting /usr/lib/libEGL_nvidia.so.418.67
  W1225 03:31:09.455231 1885 nvc_info.c:302] missing compat32 library libnvidia-cfg.so
  I1225 03:31:09.457155 1885 nvc_info.c:228] selecting /usr/bin/nvidia-smi
  I1225 03:31:09.457211 1885 nvc_info.c:228] selecting /usr/bin/nvidia-debugdump
  I1225 03:31:09.457265 1885 nvc_info.c:228] selecting /usr/bin/nvidia-persistenced
  I1225 03:31:09.457319 1885 nvc_info.c:228] selecting /usr/bin/nvidia-cuda-mps-control
  I1225 03:31:09.457373 1885 nvc_info.c:228] selecting /usr/bin/nvidia-cuda-mps-server
  I1225 03:31:09.457439 1885 nvc_info.c:365] listing device /dev/nvidiactl
  I1225 03:31:09.457454 1885 nvc_info.c:365] listing device /dev/nvidia-uvm
  I1225 03:31:09.457466 1885 nvc_info.c:365] listing device /dev/nvidia-uvm-tools
  I1225 03:31:09.457479 1885 nvc_info.c:365] listing device /dev/nvidia-modeset
  W1225 03:31:09.457537 1885 nvc_info.c:273] missing ipc /var/run/nvidia-persistenced/socket
  W1225 03:31:09.457581 1885 nvc_info.c:273] missing ipc /tmp/nvidia-mps
  I1225 03:31:09.457596 1885 nvc_info.c:489] requesting device information with ''
  I1225 03:31:09.464245 1885 nvc_info.c:519] listing device /dev/nvidia0 (GPU-e8ae61f2-78a9-5aae-34d7-9eadc9648b84 at 00000000:02:00.0)
  I1225 03:31:09.470744 1885 nvc_info.c:519] listing device /dev/nvidia1 (GPU-504d0b86-c3fb-98df-b82a-6c3e59c21e66 at 00000000:03:00.0)
  I1225 03:31:09.477331 1885 nvc_info.c:519] listing device /dev/nvidia2 (GPU-62c74d5a-2a78-07b3-3d42-6bcbafcaafec at 00000000:83:00.0)
  I1225 03:31:09.483989 1885 nvc_info.c:519] listing device /dev/nvidia3 (GPU-5453951c-5c0c-1305-78ed-44b5d764abbd at 00000000:84:00.0)
  NVRM version:   418.67
  CUDA version:   10.1

  Device Index:   0
  Device Minor:   0
  Model:          Tesla P40
  Brand:          Tesla
  GPU UUID:       GPU-e8ae61f2-78a9-5aae-34d7-9eadc9648b84
  Bus Location:   00000000:02:00.0
  Architecture:   6.1

  Device Index:   1
  Device Minor:   1
  Model:          Tesla P40
  Brand:          Tesla
  GPU UUID:       GPU-504d0b86-c3fb-98df-b82a-6c3e59c21e66
  Bus Location:   00000000:03:00.0
  Architecture:   6.1

  Device Index:   2
  Device Minor:   2
  Model:          Tesla P40
  Brand:          Tesla
  GPU UUID:       GPU-62c74d5a-2a78-07b3-3d42-6bcbafcaafec
  Bus Location:   00000000:83:00.0
  Architecture:   6.1

  Device Index:   3
  Device Minor:   3
  Model:          Tesla P40
  Brand:          Tesla
  GPU UUID:       GPU-5453951c-5c0c-1305-78ed-44b5d764abbd
  Bus Location:   00000000:84:00.0
  Architecture:   6.1
  I1225 03:31:09.484259 1885 nvc.c:318] shutting down library context
  I1225 03:31:09.485258 1920 driver.c:192] terminating driver service
  I1225 03:31:09.552574 1885 driver.c:233] driver service terminated successfully
  ```

and restart docker, nvidia-smi execute normally
  ```shell
  [root@k8s-deploy-vcxohs-1602835630852-54cff75dd-dn56j release]$ nvidia-smi -L
  GPU 0: Tesla P40 (UUID: GPU-e8ae61f2-78a9-5aae-34d7-9eadc9648b84)
  GPU 1: Tesla P40 (UUID: GPU-504d0b86-c3fb-98df-b82a-6c3e59c21e66)
  GPU 2: Tesla P40 (UUID: GPU-62c74d5a-2a78-07b3-3d42-6bcbafcaafec)
  GPU 3: Tesla P40 (UUID: GPU-5453951c-5c0c-1305-78ed-44b5d764abbd)
  [root@k8s-deploy-vcxohs-1602835630852-54cff75dd-dn56j release]$ ./simpleMultiGPU 
  Starting simpleMultiGPU
  CUDA-capable device count: 4
  Generating input data...
  
  Computing with 4 GPUs...
    GPU Processing time: 12.055000 (ms)
  
  Computing with Host CPU...
  
  Comparing GPU and Host CPU results...
    GPU sum: 16777304.000000
    CPU sum: 16777294.395033
    Relative difference: 5.724980E-07 
  ```
