### ISSUE TITLE
how can i use docker images nvidia/cuda  select gcc4.9

### ISSUE THREAD

**Issue by 15838028035** [NVIDIA/nvidia-docker#1061]
Hi, i use gpu to run docker ,
centos7
gcc4.9
cuda8 or cuda9.0

how can i use docker images nvidia/cuda  select gcc4.9

cloud you help me ?

how can i pull docker images ?

**Comment by Ethyling** [comment]
Hey,

Sorry but I don't fully understand your problem. Could you describe it a little bit more? You can find all the valid docker images for cuda here https://hub.docker.com/r/nvidia/cuda/tags

**Comment by RenaudWasTaken** [comment]
Closing as no details provided.
