### ISSUE TITLE
nvidia-docker2 installs with docker.io debian/ubuntu package but does not work.

### ISSUE THREAD

**Issue by tzickel** [NVIDIA/nvidia-docker#1062]
### 1. Issue or feature description

the nvidia-docker 2 package used to depends on docker-ce or docker-ee, and would not install on docker.io (the default package). This was removed in recent versions, and thus users can install it by accident with docker.io which does not really work.

### 2. Steps to reproduce the issue

```bash
apt install docker.io
apt install nvidia-docker2
sudo pkill -HUP dockerd
```

no docker --runtime=nvidia :(

**Comment by Ethyling** [comment]
Hey,

I can't reproduce the bug. What do you mean by `no docker --runtime=nvidia`?

**Comment by tzickel** [comment]
```bash
docker info
```
shows no nvidia runtime in the list... which docker.io version do you have ?
```bash
dpkg -l | grep docker
```

**Comment by Ethyling** [comment]
Hey, I used Docker 18.09.7
