### ISSUE TITLE
Docker SDK for Python about gpu configuration api

### ISSUE THREAD

**Issue by rush9838465** [NVIDIA/nvidia-docker#1063]
I used the Docker SDK for Python, but did not find the gpu configuration api. May I ask where I can find the API of gpu configuration?
I can't find it on the web https://docker-py.readthedocs.io/en/stable/containers.html#

**Comment by Ethyling** [comment]
Hey,

I don't think the Docker SDK for Python currently support the new `--gpus` option. Otherwise, you can use the `nvidia-docker2` package and specify the runtime as `nvidia` for your container. See https://docker-py.readthedocs.io/en/stable/containers.html, `runtime` option.

**Comment by DragonDriver** [comment]
> Hey,
> 
> I don't think the Docker SDK for Python currently support the new `--gpus` option. Otherwise, you can use the `nvidia-docker2` package and specify the runtime as `nvidia` for your container. See https://docker-py.readthedocs.io/en/stable/containers.html, `runtime` option.


could you give an example about how to use `runtime` option with `nvidia`?

Thank you very much!

**Comment by alex9311** [comment]
@DragonDriver 
if you install [nvidia-docker](https://developer.nvidia.com/blog/nvidia-docker-gpu-server-application-deployment-made-easy/) on the host machine, you would do:

```python
client.containers.run('alpine', 'echo hello world', runtime="nvidia")
```
