### ISSUE TITLE
installation failed on ubuntu16.04 and docker19.03

### ISSUE THREAD

**Issue by leerumor** [NVIDIA/nvidia-docker#1065]
I have ubuntu16.04 and docker19.03, nvidia driver 418.67 installed.
I followed the **Getting started** and **Usage** instructions.
but I cannot run nvidia-docker:
```
$ nvidia-docker run nvidia/cuda:9.0-base nvidia-smi
nvidia-docker: command not found
```
I also tried 
```
$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: Unknown runtime specified nvidia.
```
I've been reading some discussion, but most of them is about installing navidia-docker2, so I'm not sure what to do next...

**Comment by psyhtest** [comment]
@leerumor Try installing:
```
$ sudo apt install nvidia-docker2
```
restarting your machine, and then:
```
$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```

**Comment by Ethyling** [comment]
Hey, using `nvidia-docker` and `--runtime` is now deprecated with Docker19.03. You should use the `--gpus` option. Please follow instructions here: https://github.com/NVIDIA/nvidia-docker#usage

**Comment by leerumor** [comment]
I understand! thanks!
