### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version when runing ./deviceQuery in docker

### ISSUE THREAD

**Issue by 0801130205** [NVIDIA/nvidia-docker#1066]
I install cuda in the docker image, ubuntu:16.04. I ran to a problem when running ./deviceQuery.
cuda:                                 cuda_8.0.61_375.26_linux.run
nvidia Driver Version:       384.111
gpu:                                  1050TI

In the container, runing nvidia-smi and received the following:
![Screenshot from 2019-09-06 11-53-28](https://user-images.githubusercontent.com/29110881/64399956-f7a87a00-d09c-11e9-9216-ca72972a178b.png)

But when running ./deviceQuery, I received the following:
![Screenshot from 2019-09-06 11-55-09](https://user-images.githubusercontent.com/29110881/64400014-30e0ea00-d09d-11e9-9e65-71798ed16861.png)

Can you help me?

**Comment by RenaudWasTaken** [comment]
Hello!

You really should update your driver to a new version :)
You have a pretty old version, or you can pull an earlier image (cuda:9.0-base)
