### ISSUE TITLE
Error NVIDIA-SMI couldn't find libnvidia-ml.so library in your system

### ISSUE THREAD

**Issue by volkovichRan** [NVIDIA/nvidia-docker#107]
Hey,
i got environment at aws instance type:g2.2xlarge
ubuntu 14.04 when i use the command from the host: nvidia-smi 
i get this result:

+------------------------------------------------------+                       
| NVIDIA-SMI 352.93     Driver Version: 352.93         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   44C    P8    17W / 125W |     11MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

but when i run
 nvidia-docker run -ti  nvidia/cuda nvidia-smi
result: 
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.

Any idea what I'm missing ?

**Comment by flx42** [comment]
Worked fine for me using a g2.8xlarge instance and the instructions here:
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2
I used the same driver as you, no issue.

How did you install the driver?

**Comment by 3XX0** [comment]
How did you install the driver?
Did you follow the [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2) or did everything manually?

**Comment by volkovichRan** [comment]
i solved it i done docker inspect and saw the path to the driver and it had it wrong. 

p.s 
sorry for late answer was at vacation

p.s-2 
sorry that its off the topic but 
i wounder if i got server with few gpu 
if i can make it run that 1 docker will use 1 gpu with driver x 
and anther docker that use anther gpu with anther driver  y

**Comment by flx42** [comment]
>  if i can make it run that 1 docker will use 1 gpu with driver x
> and anther docker that use anther gpu with anther driver y

You can't have multiple versions of the driver, but you can use multiple versions of CUDA or cuDNN on the same machine.

**Comment by flx42** [comment]
@volkovichRan I'm not sure how you solved the problem, was it an issue with the driver installation? Or with Docker/nvidia-docker?
Let me know if we can close, or if you have repro steps for a bug.

**Comment by volkovichRan** [comment]
i am sorry but my instance was deleted.
but i guess its was my mistake of installation 
because it was my first time i install 
cuda/nvidia driver/caffe/py-faster 
and the environment was messy >.<

Thanks for the help

**Comment by flx42** [comment]
Ok, let us know if you stumble into this issue again!

**Comment by deep-pipeline** [comment]
Hi @fix42 & @3XX0 - sorry to bother you but I think I may have had a similar problem not on AWS, but Fedora, as yet not solved and possibly an nvidia-docker issue?

On a fairly clean minimal fresh Fedora23 then upgraded ->FC24 install - no X if that makes a difference - I followed NVIDIA's steps for installing NVIDIA 367.27 CUDA driver (removing nouveau driver etc). I had some trouble with docker/docker-compose installation (to do with distribution repos and docker.socket.. anyway, I solved that with the 'manual' script install - seems to be correct version and operate) then I progressed to nvidia-docker installation - which itself seemed to work fine..  and then I hit a problem:

when I tried to do `nvidia-docker run --rm nvidia/cuda nvidia-smi`.... I get the same error message/problem `NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.`

but I do get a sensible output from nvidia-smi executed at the host level.

Looking further into this I found that the output of 
`find / -name libnvidia-ml.so` at the host gives only

`/usr/lib/libnvidia-ml.so
/usr/lib64/libnvidia-ml.so`

but `ls -al $(find / -name 'libnvidia-ml*')
lrwxrwxrwx. 1 root          root               17 Jul 14 14:51 /usr/lib64/libnvidia-ml.so -> libnvidia-ml.so.1
lrwxrwxrwx. 1 root          root               22 Jul 14 14:51 /usr/lib64/libnvidia-ml.so.1 -> libnvidia-ml.so.367.27
-rwxr-xr-x. 2 root          root          1153696 Jul 14 14:51 /usr/lib64/libnvidia-ml.so.367.27
lrwxrwxrwx. 1 root          root               17 Jul 14 14:51 /usr/lib/libnvidia-ml.so -> libnvidia-ml.so.1
lrwxrwxrwx. 1 root          root               22 Jul 14 14:51 /usr/lib/libnvidia-ml.so.1 -> libnvidia-ml.so.367.27
-rwxr-xr-x. 2 root          root          1174636 Jul 14 14:51 /usr/lib/libnvidia-ml.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker      22 Jul 25 14:15 /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/libnvidia-ml.so.1 -> libnvidia-ml.so.367.27
-rwxr-xr-x. 2 root          root          1153696 Jul 14 14:51 /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/libnvidia-ml.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker      22 Jul 25 14:15 /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib/libnvidia-ml.so.1 -> libnvidia-ml.so.367.27
-rwxr-xr-x. 2 root          root          1174636 Jul 14 14:51 /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib/libnvidia-ml.so.367.27`

so there is a more sophisticated structure of chained links libnvidia-ml.so -> libnvidia-ml.so.1 -> libnvidia-ml.so.367.27 but there aren't any libnvidia-ml.so as such linked within what I presume to be the nvidia-docker files..?

So, I tried to stick in some links..

`ln /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib/libnvidia-ml.so.1 /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib/libnvidia-ml.so
ln /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/libnvidia-ml.so.1 /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/libnvidia-ml.so`

but that failed to make any difference..

following the tip from the earlier bug reporter of looking further into the nvidia/cuda file I used

`docker inspect nvidia/cuda` 

and in that I find:

`           "Env": [
                "PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CUDA_VERSION=8.0",
                "CUDA_DOWNLOAD_SUM=9edcebbe8b646e40317f9ab822a733e10146003a73fc775a089226630121da7b",
                "CUDA_PKG_VERSION=8-0=8.0.27-1",
                "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:",
                "LIBRARY_PATH=/usr/local/cuda/lib64/stubs:"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ENV LIBRARY_PATH=/usr/local/cuda/lib64/stubs:”
`
and, further down in that file,

`  "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:",
                "LIBRARY_PATH=/usr/local/cuda/lib64/stubs:"
`

which I take to mean that the nvidia/cuda image configuration expects /usr/local/nvidia/lib to be provided either by the host or within the image?? sorry don't quite understand the output of docker inspect - am pretty new to this stuff.

Anyway, none of those files seem to exist within the FC24+Nvidia driver installation+docker+nvidia-docker installation as I have it. There's no bespoke software and nobody else running on this machine, so were talking only Fedora installation, upgrades, distribution-upgrade and Nvidia or Docker software on here..

Any thoughts? is this an nvidia-docker configuration bug?

**Comment by flx42** [comment]
@deep-pipeline please don't start messing with `/var/lib/nvidia-docker/volumes`!
Can you run the following command?
```
nvidia-docker run -ti nvidia/cuda ls -l /usr/local/nvidia/lib64
```
Then, please also try the following:
```
curl -s http://localhost:3476/v1.0/docker/cli
```

**Comment by flx42** [comment]
Also, please check that your host system is fine by running `nvidia-smi` outside of Docker.

**Comment by deep-pipeline** [comment]
Hi @flx42 - OK! will steer clear of the (scary!) volumes - haven't done anything explicitly with volumes (other than experiment with the two ln commands I previously tried when trying to fix things myself..

Info as requested:

`nvidia-docker run -ti nvidia/cuda ls -l /usr/local/nvidia/lib64
ls: cannot open directory /usr/local/nvidia/lib64: Permission denied`

just to extend that..

`[root@dell ~]# nvidia-docker run -ti nvidia/cuda ls -l /usr/local/nvidia/
ls: cannot open directory /usr/local/nvidia/: Permission denied

[root@dell ~]# nvidia-docker run -ti nvidia/cuda ls -l /usr/local/
total 0
drwxr-xr-x.  2 root root   6 Jul 11 23:22 bin
lrwxrwxrwx.  1 root root   8 Jul 22 21:59 cuda -> cuda-8.0
drwxr-xr-x. 11 root root 194 Jul 22 22:04 cuda-8.0
drwxr-xr-x.  2 root root   6 Jul 11 23:22 etc
drwxr-xr-x.  2 root root   6 Jul 11 23:22 games
drwxr-xr-x.  2 root root   6 Jul 11 23:22 include
drwxr-xr-x.  3 root root  23 Jul 11 23:23 lib
lrwxrwxrwx.  1 root root   9 Jul 11 23:22 man -> share/man
drwxr-xr-x.  5  984  984  41 Jul 25 13:15 nvidia
drwxr-xr-x.  2 root root   6 Jul 11 23:22 sbin
drwxr-xr-x.  4 root root  40 Jul 22 21:58 share
drwxr-xr-x.  2 root root   6 Jul 11 23:22 src`

and as requested:

`curl -s http://localhost:3476/v1.0/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_367.27:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia0`

and as proof of GPU-life..

`nvidia-smi
Wed Jul 27 17:44:48 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.27                 Driver Version: 367.27                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 730      Off  | 0000:02:00.0     N/A |                  N/A |
| N/A   28C    P8    N/A /  N/A |      0MiB /  2001MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+`

**Comment by flx42** [comment]
`/usr/local/nvidia` is owned by  984:984?
```
drwxr-xr-x. 5 984 984 41 Jul 25 13:15 nvidia
```

Do you have a funky Docker install?

**Comment by deep-pipeline** [comment]
ok, so /usr/local/nvidia is not where you think it is...

`[root@dell ~]# ls /usr/local/nvidia`

>
ls: cannot access '/usr/local/nvidia': No such file or directory
>

so, let's find it..

`[root@dell ~]# which nvidia`

>
/usr/bin/which: no nvidia in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
>

odd.. so let's *find* it..

`[root@dell ~]# find / -name nvidia`

> 
/proc/irq/31/nvidia
/proc/driver/nvidia
/sys/bus/pci/drivers/nvidia
/sys/module/nvidia
/var/lib/dkms/nvidia
/var/lib/nvidia
/usr/lib/firmware/nvidia
/usr/lib/modules/4.5.7-202.fc23.x86_64/kernel/drivers/net/ethernet/nvidia
/usr/lib/modules/4.6.4-201.fc23.x86_64/kernel/drivers/net/ethernet/nvidia
/usr/lib/modules/4.6.4-301.fc24.x86_64/kernel/drivers/net/ethernet/nvidia
/usr/share/nvidia
/usr/src/kernels/4.5.7-202.fc23.x86_64/arch/arm64/boot/dts/nvidia
/usr/src/kernels/4.5.7-202.fc23.x86_64/drivers/net/ethernet/nvidia
/usr/src/kernels/4.5.7-202.fc23.x86_64/drivers/video/fbdev/nvidia
/usr/src/kernels/4.6.4-201.fc23.x86_64/arch/arm64/boot/dts/nvidia
/usr/src/kernels/4.6.4-201.fc23.x86_64/drivers/net/ethernet/nvidia
/usr/src/kernels/4.6.4-201.fc23.x86_64/drivers/video/fbdev/nvidia
/usr/src/kernels/4.6.4-301.fc24.x86_64/arch/arm64/boot/dts/nvidia
/usr/src/kernels/4.6.4-301.fc24.x86_64/drivers/net/ethernet/nvidia
/usr/src/kernels/4.6.4-301.fc24.x86_64/drivers/video/fbdev/nvidia
/usr/src/nvidia-367.27/nvidia
>

in my defence, I didn't put any special installation paths when I kept hitting ok on the Docker and Nvidia installers!

As for the Docker installation.. looking at my notes I followed the instructions at
https://docs.docker.com/engine/installation/linux/fedora/

and I did
 
`curl -fsSL https://get.docker.com/ | sh`

for nvidia-docker I did:

`wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker-1.0.0.rc.3-1.x86_64.rpm`

followed by

`rpm -i /tmp/nvidia-docker*.rpm && rm /tmp/nvidia-docker*.rpm`

**Comment by deep-pipeline** [comment]
Nvidia driver installer is this one:
`-rwxr-xr-x.  1 root root 76945324 Jun 10 10:25 NVIDIA-Linux-x86_64-367.27.run`

**Comment by flx42** [comment]
`/usr/local/nvidia` is a container path, it's a volume created by `nvidia-docker`. It doesn't exist on the host.

On the host, do the following to find the libraries:
```
ldconfig -p | grep nvidia
```
Then, depending on the paths you get:
```
ls -la /usr/lib/x86_64-linux-gnu/libnvidia*
```

Also, there is now driver `367.35`, you should use this one.

**Comment by deep-pipeline** [comment]
ah ok, so first of all here's the ownership info for the container path /usr/local - yes it's 984:984

>nvidia-docker run nvidia/cuda ls -al /usr/local
total 0
drwxr-xr-x. 12 root root 156 Jul 27 17:10 .
drwxr-xr-x. 10 root root 105 Jul 22 22:04 ..
drwxr-xr-x.  2 root root   6 Jul 11 23:22 bin
lrwxrwxrwx.  1 root root   8 Jul 22 21:59 cuda -> cuda-8.0
drwxr-xr-x. 11 root root 194 Jul 22 22:04 cuda-8.0
drwxr-xr-x.  2 root root   6 Jul 11 23:22 etc
drwxr-xr-x.  2 root root   6 Jul 11 23:22 games
drwxr-xr-x.  2 root root   6 Jul 11 23:22 include
drwxr-xr-x.  3 root root  23 Jul 11 23:23 lib
lrwxrwxrwx.  1 root root   9 Jul 11 23:22 man -> share/man
drwxr-xr-x.  5  984  984  41 Jul 25 13:15 nvidia
drwxr-xr-x.  2 root root   6 Jul 11 23:22 sbin
drwxr-xr-x.  4 root root  40 Jul 22 21:58 share
drwxr-xr-x.  2 root root   6 Jul 11 23:22 src
>

**Comment by deep-pipeline** [comment]
so, the filtered ldconfig output is long.. not sure what you were suggesting next?

is it worth me just trying to upgrade to the 367.35 driver at this point..?

>
ldconfig -p | grep nvidia
	libvdpau_nvidia.so (libc6,x86-64, OS ABI: Linux 2.3.99) => /lib64/libvdpau_nvidia.so
	libvdpau_nvidia.so (libc6, OS ABI: Linux 2.3.99) => /lib/libvdpau_nvidia.so
	libnvidia-tls.so.367.27 (libc6,x86-64, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /lib64/tls/libnvidia-tls.so.367.27
	libnvidia-tls.so.367.27 (libc6,x86-64, OS ABI: Linux 2.2.5) => /lib64/libnvidia-tls.so.367.27
	libnvidia-tls.so.367.27 (libc6, OS ABI: Linux 2.2.5) => /lib/libnvidia-tls.so.367.27
	libnvidia-ptxjitcompiler.so.367.27 (libc6,x86-64) => /lib64/libnvidia-ptxjitcompiler.so.367.27
	libnvidia-ptxjitcompiler.so.367.27 (libc6) => /lib/libnvidia-ptxjitcompiler.so.367.27
	libnvidia-opencl.so.1 (libc6,x86-64) => /lib64/libnvidia-opencl.so.1
	libnvidia-opencl.so.1 (libc6) => /lib/libnvidia-opencl.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /lib64/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /lib/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /lib64/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /lib/libnvidia-ml.so
	libnvidia-ifr.so.1 (libc6,x86-64) => /lib64/libnvidia-ifr.so.1
	libnvidia-ifr.so.1 (libc6) => /lib/libnvidia-ifr.so.1
	libnvidia-ifr.so (libc6,x86-64) => /lib64/libnvidia-ifr.so
	libnvidia-ifr.so (libc6) => /lib/libnvidia-ifr.so
	libnvidia-gtk3.so.367.27 (libc6,x86-64) => /lib64/libnvidia-gtk3.so.367.27
	libnvidia-gtk2.so.367.27 (libc6,x86-64) => /lib64/libnvidia-gtk2.so.367.27
	libnvidia-glsi.so.367.27 (libc6,x86-64) => /lib64/libnvidia-glsi.so.367.27
	libnvidia-glsi.so.367.27 (libc6) => /lib/libnvidia-glsi.so.367.27
	libnvidia-glcore.so.367.27 (libc6,x86-64) => /lib64/libnvidia-glcore.so.367.27
	libnvidia-glcore.so.367.27 (libc6) => /lib/libnvidia-glcore.so.367.27
	libnvidia-fbc.so.1 (libc6,x86-64) => /lib64/libnvidia-fbc.so.1
	libnvidia-fbc.so.1 (libc6) => /lib/libnvidia-fbc.so.1
	libnvidia-fbc.so (libc6,x86-64) => /lib64/libnvidia-fbc.so
	libnvidia-fbc.so (libc6) => /lib/libnvidia-fbc.so
	libnvidia-fatbinaryloader.so.367.27 (libc6,x86-64) => /lib64/libnvidia-fatbinaryloader.so.367.27
	libnvidia-fatbinaryloader.so.367.27 (libc6) => /lib/libnvidia-fatbinaryloader.so.367.27
	libnvidia-encode.so.1 (libc6,x86-64) => /lib64/libnvidia-encode.so.1
	libnvidia-encode.so.1 (libc6) => /lib/libnvidia-encode.so.1
	libnvidia-encode.so (libc6,x86-64) => /lib64/libnvidia-encode.so
	libnvidia-encode.so (libc6) => /lib/libnvidia-encode.so
	libnvidia-eglcore.so.367.27 (libc6,x86-64) => /lib64/libnvidia-eglcore.so.367.27
	libnvidia-eglcore.so.367.27 (libc6) => /lib/libnvidia-eglcore.so.367.27
	libnvidia-egl-wayland.so.367.27 (libc6,x86-64) => /lib64/libnvidia-egl-wayland.so.367.27
	libnvidia-compiler.so.367.27 (libc6,x86-64) => /lib64/libnvidia-compiler.so.367.27
	libnvidia-compiler.so.367.27 (libc6) => /lib/libnvidia-compiler.so.367.27
	libnvidia-cfg.so.1 (libc6,x86-64) => /lib64/libnvidia-cfg.so.1
	libnvidia-cfg.so (libc6,x86-64) => /lib64/libnvidia-cfg.so
	libGLX_nvidia.so.0 (libc6,x86-64) => /lib64/libGLX_nvidia.so.0
	libGLX_nvidia.so.0 (libc6) => /lib/libGLX_nvidia.so.0
	libGLESv2_nvidia.so.2 (libc6,x86-64) => /lib64/libGLESv2_nvidia.so.2
	libGLESv2_nvidia.so.2 (libc6) => /lib/libGLESv2_nvidia.so.2
	libGLESv1_CM_nvidia.so.1 (libc6,x86-64) => /lib64/libGLESv1_CM_nvidia.so.1
	libGLESv1_CM_nvidia.so.1 (libc6) => /lib/libGLESv1_CM_nvidia.so.1
	libEGL_nvidia.so.0 (libc6,x86-64) => /lib64/libEGL_nvidia.so.0
	libEGL_nvidia.so.0 (libc6) => /lib/libEGL_nvidia.so.0
>

**Comment by flx42** [comment]
I suspect a Docker issue, not a nvidia-docker issue, can you try the following?
```
docker run -ti -v /usr/local:/mnt/usr/local ubuntu:14.04 ls -l /mnt/usr
```

**Comment by deep-pipeline** [comment]
No prob:

>
docker run -ti -v /usr/local:/mnt/usr/local ubuntu:14.04 ls -l /mnt/usr
total 0
drwxr-xr-x. 12 root root 131 Feb  3 22:10 local
>

is that what you were expecting?

and in case you wanted this..

>
[root@dell ~]# docker run -ti -v /usr/local:/mnt/usr/local ubuntu:14.04 ls -l /mnt/usr/local/
total 0
drwxr-xr-x. 2 root root  6 Feb  3 22:10 bin
drwxr-xr-x. 2 root root  6 Feb  3 22:10 etc
drwxr-xr-x. 2 root root  6 Feb  3 22:10 games
drwxr-xr-x. 2 root root  6 Feb  3 22:10 include
drwxr-xr-x. 2 root root  6 Feb  3 22:10 lib
drwxr-xr-x. 2 root root  6 Feb  3 22:10 lib64
drwxr-xr-x. 2 root root  6 Feb  3 22:10 libexec
drwxr-xr-x. 2 root root  6 Feb  3 22:10 sbin
drwxr-xr-x. 5 root root 49 Feb  3 22:10 share
drwxr-xr-x. 2 root root  6 Feb  3 22:10 src
>

no obvious error?

**Comment by flx42** [comment]
Never mind, false lead, it's actually normal.

But it's weird that root can't access `/usr/local/nvidia` inside the container. Can you open a new issue now instead of spamming this old one? :)

**Comment by deep-pipeline** [comment]
LOL - ok.. :-)

**Comment by Jiri-Kremser** [comment]
for me the easy (and dirty) workaround was to disable selinux temporarily

**Comment by ink1** [comment]
still the same problem related to container root can't read /usr/local/nvidia
disabling selinux fixes the issue.
centos 7, NVIDIA driver 384.90, docker-1.12.6-55, nvidia-docker-1.0.1-1

**Comment by Jiri-Kremser** [comment]
btw. it's because the files that are going to be mounted have to have a proper se linux context. This should work as well:

```
chcon -Rt container_file_t /usr/lib{64,}/libnvidia*
```

**Comment by kunth** [comment]
well no offense but I do not use NVIDIA-DOCKER. I use "docker run -v" to mount devices and binaries like /dev/nvidia* into the container. I also bump into this problem when I exec nvida-smi in the container. I solve this problem by creating the file "/etc/ld.so.conf.d/nvidia.conf" and write the path of libnvidia-ml.so to the file in container. e.g.
```golang
[root@a6e81762a915 run_files]# ls /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
[root@a6e81762a915 run_files]# cat /etc/ld.so.conf.d/nvidia.conf
/usr/lib/x86_64-linux-gnu/
```
and then
``` golang
ldconfig
```
after that, I execute the nvidia-smi successfully.

**Comment by ntomita** [comment]
@kunth I somehow encountered the same issue with apptainer with clean ubuntu 20.04. Your method still works. I appreciate it.
