### ISSUE TITLE
WARNING: The NVIDIA Driver was not detected

### ISSUE THREAD

**Issue by paolorota** [NVIDIA/nvidia-docker#1071]
I also posted in a closed and related issue (#464 ).

With the last upgrades I have the same problem on 5/5 machines. 
`WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker`

So basically docker does not see the drivers and therefore Tensorflow does not work anymore.

I am using the following image: `nvcr.io/nvidia/tensorflow:19.08-py3` and I have installed the following nvidia drivers: 390.116

![image](https://user-images.githubusercontent.com/6144618/64905554-5e9be380-d6da-11e9-9015-844e3696b3bf.png)

Docker version:
`Docker version 19.03.1, build 74b1e89`

Anyone can help? I tried to purge drivers, reinstall a different version but the result is the same. nvidia-docker is not found, I run docker normally as described in the guide.

EDIT:
On a 6th machine (an NVIDIA DGX1), it only works if I launch `nvidia-docker `instead of just `docker`. I wonder if I have to rolback to the old nvidia-docker....

**Comment by paolorota** [comment]
Possible walkaround:

Add  `--gpus all`:

```
docker run --gpus all -it --rm  nvcr.io/nvidia/tensorflow:19.08-py3
```

**Comment by RenaudWasTaken** [comment]
Yep, this is the expected invocation of the command!

**Comment by roadev** [comment]
> Possible walkaround:
> 
> Add `--gpus all`:
> 
> ```
> docker run --gpus all -it --rm  nvcr.io/nvidia/tensorflow:19.08-py3
> ```

You're a genious, thank you so much!
