### ISSUE TITLE
docker run --gpus 2 nvidia/cuda:9.0-base /bin/bash

### ISSUE THREAD

**Issue by songziqin** [NVIDIA/nvidia-docker#1078]
just as example states:
   docker run --gpus 2 nvidia/cuda:9.0-base nvidia-smi, it will display and the container will exit.
and I execute command 'docker run --gpus 2 nvidia/cuda:9.0-base /bin/bash' and it exit quickly,and I want to know does it support like 'docker run -it nvidia/cuda:9.0-base nvidia-smi /bin/bash' and can enter the container and not exit . and how can do that.

**Comment by RenaudWasTaken** [comment]
Hello!

This is more of a docker / shell question but you can always run:
```
docker run -it nvidia/cuda:9.0-base nvidia-smi /bin/bash
```

**Comment by kwende** [comment]
root@APOLLO-Linux:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              2ca708c1c9cc        4 days ago          64.2MB
nvidia/cuda         8.0-runtime         ade105f97ddf        3 weeks ago         796MB
nvidia/cuda         9.0-base            1443caa429f9        3 weeks ago         137MB

root@APOLLO-Linux:~# docker run -it nvidia/cuda:9.0-base nvidia-smi /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.
