### ISSUE TITLE
nvidia.github.io unreachable

### ISSUE THREAD

**Issue by jdestefani** [NVIDIA/nvidia-docker#1079]
### 1. Issue or feature description
The nvidia.github.io site is unreachable, both using a web browser (giving 404 status code) or by trying to install a package through `apt-get` yielding the following error:

`Err:8 https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  InRelease
  Could not resolve host: nvidia.github.io`

### 2. Steps to reproduce the issue

I was following the installation guide for Ubuntu 16.04 of
https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta)

The error occurs while reaching the line: 
`sudo apt-get update && sudo apt-get install -y nvidia-docker2`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

No further information other than the guide (https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta)) is added since the problem seems unrelated to the configuration of my computer (all the other packages list are read fine)

**Comment by RenaudWasTaken** [comment]
Helo!

This is most likely an issue on your side :)
Check with your network admin if github.io isn't blacklisted!

**Comment by jdestefani** [comment]
By trying to reach the website both from my workplace and my home, I get the following error:
![UnreachableNvidiaGithub](https://user-images.githubusercontent.com/5686218/65427750-5008a700-de13-11e9-8a07-ed9ec1a6ad54.png)

Could you please verify that everything is OK from your side?

**Comment by RenaudWasTaken** [comment]
https://nvidia.github.io/ does not exist
But these exist:
- https://nvidia.github.io/nvidia-docker
- https://nvidia.github.io/nvidia-container-runtime
- https://nvidia.github.io/libnvidia-container
