### ISSUE TITLE
OCI runtime create failed (moby?)

### ISSUE THREAD

**Issue by deepdad** [NVIDIA/nvidia-docker#1084]
### 1. Issue or feature description
While on Ubuntu18 with a new installation of everything. I try https://devblogs.nvidia.com/object-detection-gpus-10-minutes/ (Ha! 10 minutes). smi image doesn't work either with similar output. Earlier on, myuser couldn't issue docker commands and adding it to the docker group remained ephemeral but that was solved. I don't want to reinstall the driver because it took me a while to get it installed but I thought I had 435 not 418
![Screenshot from 2019-09-22 16-24-35](https://user-images.githubusercontent.com/22483621/65389356-8a137380-dd55-11e9-837c-976c6ead60f8.png)

 sudo apt list  | grep nvidia | grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvidia-cfg1-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
libnvidia-common-418/unknown,now 418.87.00-0ubuntu1 all [installed,automatic]
libnvidia-container-tools/bionic,now 1.0.5-1 amd64 [installed,automatic]
libnvidia-container1/bionic,now 1.0.5-1 amd64 [installed,automatic]
nvidia-compute-utils-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
nvidia-container-toolkit/bionic,now 1.0.5-1 amd64 [installed]
nvidia-dkms-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
nvidia-driver-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
nvidia-kernel-common-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
nvidia-kernel-source-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
nvidia-prime/bionic-updates,bionic-updates,now 0.8.8.2 all [installed,automatic]
nvidia-settings/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
nvidia-utils-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-418/unknown,now 418.87.00-0ubuntu1 amd64 [installed,automatic]

### 2. Steps to reproduce the issue
~/object-detection-tensorrt-example$ ./setup_environment.sh 
Setting envivonment variables for the webcam
non-network local connections being added to access control list
xauth:  /tmp/.docker.xauth not writable, changes will be ignored
VOCdevkit has already been downloaded
Dockerfile has already been built
Starting docker container
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/e8c55672995ac2a5f13306e75753b49b84d2a7c73dd2660aae35bcb3c7c6f6b0/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: : unknown.

or

docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/37521252cf65b6309846c004be5745ac04ead2974cc14139ec00afcb621cc3e1/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: unknown.

$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
object_detection_webcam   latest              f594e35d12b8        6 hours ago         5.56GB
nvidia/cuda               9.0-base            1443caa429f9        3 weeks ago         137MB
nvidia/cuda               latest              946e78c7b298        3 weeks ago         2.83GB
nvidia/cuda               10.1-base           a5f5d3b655ca        3 weeks ago         106MB
nvcr.io/nvidia/tensorrt   19.05-py3           de065555c278        4 months ago        3.83GB
hello-world               latest              fce289e99eb9        8 months ago        1.84kB

I have seen a lot of closed issues here, that are similar but slightly different.  I don't kno what the issue is exactly. Please advice.

**Comment by zeroepoch** [comment]
What version of docker are you using?  If it's 19.03+ can you replace `--runtime=nvidia` with `--gpus=all`?

**Comment by deepdad** [comment]
$ docker run --gpus=all --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.
$ docker -v
Docker version 19.03.2, build 6a30dfc

**Comment by deepdad** [comment]
rebooting and gpus=all resolved it for ...-smi

**Comment by deepdad** [comment]
~/object-detection-tensorrt-example$ ./setup_environment.sh
Setting envivonment variables for the webcam
non-network local connections being added to access control list
xauth:  file /tmp/.docker.xauth does not exist
VOCdevkit has already been downloaded
Dockerfile has already been built
Starting docker container
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/7714905a676d8ca62784d688e1eb722145103f4e18e808b38461b926b572f42a/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: : unknown.

**Comment by deepdad** [comment]
so it still exists, this issue

**Comment by adrianosantospb** [comment]
sudo apt-get install nvidia-container-runtime
