### ISSUE TITLE
can i run nvidia-docker on NVIDIA Geforce GTX 1050/NVIDIA Geforce GTX 1050 Ti

### ISSUE THREAD

**Issue by naveen584** [NVIDIA/nvidia-docker#1089]
can i run nvidia-docker on NVIDIA Geforce GTX 1050/NVIDIA Geforce GTX 1050 Ti

**Comment by nvjmayo** [comment]
https://developer.nvidia.com/cuda-gpus indicates that CUDA is supported on GeForce GTX 1050. 

I haven't tried it myself, are you facing a specific problem?

**Comment by naveen584** [comment]
@nvjmayo  this is my card sorry for previous, **GeForce GTX 1660**  , i have ubuntu 19.4 but i am unable to install please help.

**Comment by nvjmayo** [comment]
Have you removed old versions of the driver and libraries?

**Comment by naveen584** [comment]
i just freshly installed ubuntu19.4 into new machine, and install nvidia
driver.

**Comment by neumartin** [comment]
Im interested too, can I use GeForce GTX 1660 GPU?

**Comment by naveen584** [comment]
@neumartin please read this article you will get your answer, 
 Workstation Setup for Docker with the New NVIDIA Container Toolkit (nvidia-docker2 is deprecated)
https://www.pugetsystems.com/labs/hpc/How-To-Install-Docker-and-NVIDIA-Docker-on-Ubuntu-19-04-1460/

**Comment by RenaudWasTaken** [comment]
For 19.04 you can just run the following instructions:
```
# Add the package repositories
$ distribution="ubuntu18.04"
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
$ sudo systemctl restart docker

```
