### ISSUE TITLE
Support for CentOS 8

### ISSUE THREAD

**Issue by 0xDFDFDFDF** [NVIDIA/nvidia-docker#1092]
### 1. Issue or feature description
CentOS 8 is not supported by nvidia-docker. It seems that it'll require podman as a default container engine, as with the issue #1040. Are there any plan to fix it soon, or should I downgrade the operating system?

### 2. Steps to reproduce the issue

```
[root@turing ~]# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
[root@turing ~]# curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | \
>   sudo tee /etc/yum.repos.d/nvidia-docker.repo
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker
[root@turing ~]# echo $distribution
centos8
```

**Comment by RenaudWasTaken** [comment]
I'll look into centos8 support sometime this month (pretty sure there's no difference).
In the meantime you can probably just set the distribution variable to `centos7` that would allow you not to downgrade.

**Comment by RenaudWasTaken** [comment]
I did this sometime in the past week :)!
