### ISSUE TITLE
Building docker container image on x86 PC for Jetson aarch64 

### ISSUE THREAD

**Issue by mkomuro** [NVIDIA/nvidia-docker#1093]
According to the following description, Jetson aarch64 container image can be built on x86 Linux host PC.

https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson
 
I succeeded deviceQuery CUDA sample image creation and it worked well in JAX.
But nbody sample didn’t work as follow (simpleGL sample didn’t work too).
Is it known issue and/or limitation?

Host (x86):

- Ubuntu 18.04
- CUDA Driver 430.50 (nvidia-smi)
- Installed CUDA 10.0
- Docker version 19.03.2

JAX:

- Installed Jetpack 4.2.2 

Here is command output on Jetson (JAX):
```
nvidia@JAX-JP422:~$ sudo docker run --runtime nvidia --network host -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix docker.io/mkomuro/nbody:test
Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.
        -fullscreen       (run n-body simulation in fullscreen mode)
        -fp64             (use double precision floating point values for simulation)
        -hostmem          (stores simulation data in host memory)
        -benchmark        (run benchmark to measure performance)
        -numbodies=<N>    (number of bodies (>= 1) to run in simulation)
        -device=<d>       (where d=0,1,2.... for the CUDA device to use)
        -numdevices=<i>   (where i=(number of CUDA devices > 0) to use for simulation)
        -compare          (compares simulation results running once on the default GPU and once on the CPU)
        -cpu              (run n-body simulation on the CPU)
        -tipsy=<file.bin> (load a tipsy model file for simulation)
 
NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
 
> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Xavier" with compute capability 7.2
 
> Compute 7.2 CUDA device: [Xavier]
CUDA error at bodysystemcuda_impl.h:281 code=13(cudaErrorInvalidSymbol) "setSofteningSquared(softeningSq)"
```

Thanks,
mkomuro

**Comment by RenaudWasTaken** [comment]
Hello!

Thanks for opening an issue on here.
I found the layering of your image here: https://hub.docker.com/layers/mkomuro/nbody/test/images/sha256-f34f5e388e2d03aae938874885c21f85bfff7d8b2f94c361a1df8a1dd22e1a76

As indicated in the documentation, with this feature you can build images but you won't be able to run GPU code (in other words you can call into regular linux functionality but not nvidia).
This is because the driver on x86 is largely different from the driver on jetson.

**Comment by mkomuro** [comment]
Thanks for your prompt reply.
I see, it still has a limitation.
Thanks.
