### ISSUE TITLE
Availability of nvidia official images for arm64 

### ISSUE THREAD

**Issue by payalgaikwad42** [NVIDIA/nvidia-docker#1098]
Hi, 
I am containerizing my darknet application on xavier with jetpack 4.2.2, ubuntu 18.04, arm64 device. I can build the image successfully but when I run it image is unable to find the cuda libraries inside docker container. 

Right now I am using ubuntu image `FROM ubuntu:16.04`
and mounting the volumes and devices while running the docker image in order to use underlying cuda dependencies. But it is not working. 

Is there any official cuda image by nvidia for arm64 architecture which I can use as base image while writing the Dockerfile ? 
I have search nvidia/cuda repository by nvidia on dockerhub and NCG but couldn't find any.

**Comment by RenaudWasTaken** [comment]
Hello!

I think the below link will help you: 
https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson
