### ISSUE TITLE
repo urls aren't working - tested only ubuntu18.04

### ISSUE THREAD

**Issue by akimyonoglu** [NVIDIA/nvidia-docker#1099]
https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/ is returning
```
# Unsupported distribution! # Check https://nvidia.github.io/nvidia-docker
```

if urls changed, please update https://nvidia.github.io/nvidia-docker/

**Comment by stiv-yakovenko** [comment]
I confirm the same problem.

**Comment by RenaudWasTaken** [comment]
Hello!

You'll find the full directory on the gh-pages branch: https://github.com/NVIDIA/nvidia-docker/tree/gh-pages

The fact that these specific pages you are pointing to are not accessible is inconsequential to your package manager as it doesn't attempt to download them.

If you are facing any error please open an issue with that error.
Hope this helps!
