### ISSUE TITLE
CUDA 8.0 (RC) for Ubuntu 14.04

### ISSUE THREAD

**Issue by Kaixhin** [NVIDIA/nvidia-docker#110]
With CUDA 8.0 builds now available for Ubuntu 16.04 would it be possible to also set up builds for Ubuntu 14.04?

**Comment by flx42** [comment]
Not sure we will have a Dockerfile for **RC** on 14.04.
Why do you need it, if I may ask? Why can't you transition to 16.04?

**Comment by Kaixhin** [comment]
It'll take a while for DL frameworks (e.g. https://github.com/torch/torch7/issues/670, https://github.com/BVLC/caffe/issues/4046) to iron out problems with installing on 16.04, but CUDA 8.0 can still be used on 14.04. Feel free to close this if you're not planning to do a **RC** build.

I see that according to https://github.com/NVIDIA/nvidia-docker/issues/81 it's possible to mix OS versions, which is awesome. I guess a use case might be to run 16.06 with CUDA 8.0 and still use 14.04 containers.

**Comment by flx42** [comment]
No, Caffe works fine on 16.04, the problem that you mentioned is caused by trying to use 7.5 on 16.04, it doesn't work.
The torch issue seems to be the same problem.

**Comment by Kaixhin** [comment]
Thanks for the clarification. I'll close this and work with 16.04 for >= 8.0 and 14.04 for <= 7.5.
