### ISSUE TITLE
nvidia-docker.service not found  and nvidia-docker-plugin: command not found

### ISSUE THREAD

**Issue by wangjunfeng90214** [NVIDIA/nvidia-docker#1100]
when I installed cuda 10.1,  
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

and nvidia-418.56
Mon Oct 14 22:07:39 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:01:00.0  On |                  N/A |
| 23%   31C    P8    12W / 250W |    681MiB / 12192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1069      G   /usr/lib/xorg/Xorg                           397MiB |
|    0      2785      G   compiz                                        96MiB |
|    0      3318      G   ...quest-channel-token=4301984073224121266   185MiB |
+-----------------------------------------------------------------------------+

then I install docker-ce, nvidia-docker2,
I tested the docker and nvidia-docker,
wangjunfeng@PVG-Dsk-009:/lib/systemd/system$ sudo docker run hello-world
[sudo] password for wangjunfeng: 

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

wangjunfeng@PVG-Dsk-009:/lib/systemd/system$ sudo docker run --gpus all nvidia/cuda nvidia-smi
Tue Oct 15 01:36:33 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:01:00.0  On |                  N/A |
| 23%   30C    P8    10W / 250W |    733MiB / 12192MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
but when I tested nvidia-docker.service and nvidia-docker-plugin,

wangjunfeng@PVG-Dsk-009:/lib/systemd/system$ sudo systemctl start nvidia-docker
Failed to start nvidia-docker.service: Unit nvidia-docker.service not found.
wangjunfeng@PVG-Dsk-009:/lib/systemd/system$ sudo nvidia-docker-plugin
sudo: nvidia-docker-plugin: command not found

How can I fix this issue?

**Comment by RenaudWasTaken** [comment]
Hello!

The nvidia-docker service and nvidia-docker-plugin are components that were deprecated a few years ago and don't need to be enabled or started anymore.

You should be good to go with your current setup :)!
