### ISSUE TITLE
RHEL / CentOS Repo's are not working

### ISSUE THREAD

**Issue by write2sathyan** [NVIDIA/nvidia-docker#1101]
As per the repo file downloaded from the below URL, none of baseurl's are working
https://nvidia.github.io/nvidia-docker/rhel7.5/nvidia-docker.repo 

So I am not able to install the packages.

Surfing through the baseurl, https://nvidia.github.io/libnvidia-container/centos7/x86_74, its states unsupported.

"# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container"

**Comment by RenaudWasTaken** [comment]
Hello!

You'll find the full directory on the gh-pages branch: https://github.com/NVIDIA/nvidia-docker/tree/gh-pages

The fact that these specific pages you are pointing to are not accessible is inconsequential to your package manager (I assume yum here) as it doesn't attempt to download them.

Please open an issue with the specific error you are facing :) 
We will be more efficient in helping you
