### ISSUE TITLE
TF throws error: failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by yuanzhedong** [NVIDIA/nvidia-docker#1106]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
I use the same nvidia docker image built with `nvidia/cuda:8.0-cudnn5-devel`. If I run it on K80 everything works fine, when I run the same image on RTX2080, I got error `E tensorflow/stream_executor/cuda/cuda_blas.cc:698] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED`. I'm using TF 1.13.1 but I think it shouldn't be an issue of TF since this same image runs on K80

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
RTX2080
    
```
NVRM version:   418.74
CUDA version:   10.1

Device Index:   0
Device Minor:   0
Model:          GeForce RTX 2080 with Max-Q Design
Brand:          GeForce
GPU UUID:       GPU-353d15df-a182-1a37-b7ff-f6593e0a387b
Bus Location:   00000000:01:00.0
Architecture:   7.5
I1024 23:59:46.360655 18504 nvc.c:318] shutting down library context
I1024 23:59:46.361378 18507 driver.c:192] terminating driver service
I1024 23:59:46.515857 18504 driver.c:233] driver service terminated successfully

```

K80

```
NVRM version:   418.40.04
CUDA version:   10.1

Device Index:   0
Device Minor:   0
Model:          Tesla K80
Brand:          Tesla
GPU UUID:       GPU-904a90bf-1d49-e273-88fa-e0ca0dcc3ef6
Bus Location:   00000000:00:1e.0
Architecture:   3.7
I1025 00:00:55.048232 11513 nvc.c:318] shutting down library context
I1025 00:00:55.048542 11515 driver.c:192] terminating driver service
I1025 00:00:55.049209 11513 driver.c:233] driver service terminated successfully
```

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`

K80:
```
version: 1.0.2
build date: 2019-03-26T03:56+00:00
build revision: ff40da533db929bf515aca59ba4c701a65a35e6b
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -\
fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-\
attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-arg\
s -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```
2080:
```
version: 1.0.4
build date: 2019-08-23T22:49+00:00
build revision: 67b384e9768f692581d08aecb8088f4dd09ea59d
build compiler: x86_64-linux-gnu-gcc-7 7.4.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -\
fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-\
attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-arg\
s -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by RenaudWasTaken** [comment]
Hello!

**Comment by RenaudWasTaken** [comment]
Hello!
You can find the support matrix for CUDA here:
- https://docs.nvidia.com/deeplearning/sdk/cudnn-support-matrix/index.html#cudnn-cuda-hardware-versions
- https://docs.nvidia.com/deploy/cuda-compatibility/index.html#support-hardware

Updating to a newer version (CUDA 8.0 is pretty old) should solve your issue.

**Comment by yuanzhedong** [comment]
I see, thanks!
