### ISSUE TITLE
'nvidia-docker' command not be used anymore?

### ISSUE THREAD

**Issue by jinyuan30** [NVIDIA/nvidia-docker#1107]
I have installed the nvidia-docker by the installation of wiki.
But my terminal tell me there is no command nvidia-docker when I run nvidia-docker .
I want to konw that did you change `nvidia-docker run` as  `docker run --gpus`?
Because all the blogs tell me use nvidia-docker command.

**Comment by RenaudWasTaken** [comment]
If you have installed the package `nvidia-docker2` and not `nvidia-container-toolkit` you will find the binary in /usr/bin/nvidia-docker

Hope this helps!

**Comment by jinyuan30** [comment]
@RenaudWasTaken Thanks a lot! I got it!
