### ISSUE TITLE
Ubuntu 19.10 support?

### ISSUE THREAD

**Issue by vak** [NVIDIA/nvidia-docker#1108]
it would be great to support Ubuntu 19.10. 

Any hints on how to get nvidia-container-toolkit on Ubuntu 19.10?

**Comment by vak** [comment]
ok, got it installed with a minor change:

url -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

gonna test it now

**Comment by RenaudWasTaken** [comment]
This is the correct way to install nvidia-docker on 19.10 :)

**Comment by julien-c** [comment]
Should this be mentioned in the README?

**Comment by stephane-schwarz-unicamp** [comment]
> ok, got it installed with a minor change:
> 
> `curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`
> 
> gonna test it now

This did not work for me, are there any other option?
