### ISSUE TITLE
nvidia driver cannot be identified by docker

### ISSUE THREAD

**Issue by L-CY** [NVIDIA/nvidia-docker#1109]
### Issue or feature description
I installed Driver 418.87.00 and CUDA 10.1 on Tesla V100 * 8 server.

When I create a docker from image of CUDA10.1 (ufoym/deepo:pytorch-py3.6-cu101), it can be created. However when I go into the docker, the driver can not be identified.
```
test@bbb:/# nvidia-smi
bash: nvidia-smi: command not found
```

If I create a docker from image of CUDA9.0 (ufoym/deepo:pytorch-py3.6-cu90), I can not even create the docker.
```
fly@GPU:~$ nvidia-docker run -itd --privileged --name test --shm-size=8g --ulimit memlock=-1 -v /data2/fly:/base -p 508 ufoym/deepo:pytorch-py36-cu90 /bin/bash
docker: Error response from daemon: create nvidia_driver_418.87.00: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.
```

My docker version is:
```
Docker version 17.03.2-ce, build f5ec1e2
```

**Comment by RenaudWasTaken** [comment]
Hello!

You seem to be running very old versions of both docker and nvidia-docker (which aren't supported anymore).
Can you update to the latest version?
