### ISSUE TITLE
Up-to-date DIGITS version in docker image

### ISSUE THREAD

**Issue by koallen** [NVIDIA/nvidia-docker#111]
Hi, I've been using the docker image for DIGITS and that is great. However, I noticed that the DIGITS system in the docker image is version `3.0.0`. Since that version, many great features have been added to DIGITS (e.g. new solver support, new login system, testing model with LMDB).

Can we have a docker image with the most up-to-date DIGITS?

**Comment by flx42** [comment]
Done, `latest` will be 4.0.0 RC for now, but there will also be a tag for `3.3`.
Note that there are now two volumes in the Dockerfile `/data` and `/jobs`. `/jobs` replaces '/usr/share/digits/digits/jobs'
