### ISSUE TITLE
Docker cannot use GPU even having ENV NVIDIA_VISIBLE_DEVICES=all in the Dockerfile

### ISSUE THREAD

**Issue by gofortargets** [NVIDIA/nvidia-docker#1113]
### 1. Issue or feature description
I use this Docker image: [https://hub.docker.com/layers/pytorch/pytorch/latest/images/sha256-c3f6590d7263c67c8d1423badcd732607fa86c14e7acfa7843df25e07562828a](https://hub.docker.com/layers/pytorch/pytorch/latest/images/sha256-c3f6590d7263c67c8d1423badcd732607fa86c14e7acfa7843df25e07562828a) with the command:
 
```
docker pull pytorch/pytorch:latest
docker run  -it -p 5911:8888 --name atnguyen2  -v /mnt/StorageArray2_DGX1/atnguyen/sharedir:/sharedir pytorch/pytorch:latest /bin/bash
```

But I cannot use `nvidia-smi` and Pytorch cannot detect the GPUs. Although NVIDIA devices are enable in the Dockerfile: 

```
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
```

As I read from this tutorial [https://github.com/NVIDIA/nvidia-docker/wiki/Installation-%28Native-GPU-Support%29#dockerfiles](url), it said that 

> If the environment variables are set inside the Dockerfile, you don't need to set them on the docker run command-line.

So I suppose that I can use GPUs in this container. Can you help me why this happens? The thing is that I am using Pycharm and I cannot include `--gpus `option in my run configuration. I tried to add option `-e  NVIDIA_VISIBLE_DEVICES=all` when running Docker but Pycharm still cannot detect GPUs when running python code. 

### 2. Version information
Nvidia DGX station 
NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     
Docker version: 
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by rajatchopra** [comment]
We need some way of telling docker to invoke the nvidia-container-runtime. So either one has to:

1. Use `--gpu` option
2. Run with `--runtime=nvidia` in command line e.g. `docker run --runtime=nvidia -it -p 5911:8888 --name atnguyen2  -v /mnt/StorageArray2_DGX1/atnguyen/sharedir:/sharedir pytorch/pytorch:latest /bin/bash`
3. Set the default runtime in `/etc/docker/daemon.json` to `nvidia`!

The last two options assume that you have the runtime declared in `/etc/docker/daemon.json`. See [this](https://github.com/nvidia/nvidia-container-runtime#daemon-configuration-file).
