### ISSUE TITLE
[question] Pre-Volta MPS Support

### ISSUE THREAD

**Issue by gaocegege** [NVIDIA/nvidia-docker#1115]
### 1. Issue or feature description

Hi, I saw the wiki page about the experimental support for MPS:

> Only Volta MPS is supported.

And I am wondering why we cannot support Pre-Volta MPS. Is it in the plan?

I'd appreciate it if anyone could help.

**Comment by rajatchopra** [comment]
Pre-Volta MPS is quite a challenge (address space is not isolated etc) and not sure if it is a task worth chasing (sub-par performance - it is 3 generations old).

If there is enough interest (upvotes needed), then this could be part of the this project's roadmap, why not !

**Comment by gaocegege** [comment]
@rajatchopra Thanks for the explanation!
