### ISSUE TITLE
build_docker_container.sh fails on Jetson Xavier

### ISSUE THREAD

**Issue by DennisFaucher** [NVIDIA/nvidia-docker#1117]
Thanks in advance.

### 1. Issue or feature description
build_docker_container.sh fails on Jetson Xavier
### 2. Steps to reproduce the issue
sudo ./build_docker_container.sh
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Step 5/9 : RUN apt-get update && apt-get install -y --no-install-recommends         build-essential         cmake         git         wget         sudo         python         libcudnn7=$CUDNN_VERSION-1+cuda10.0         libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 &&     apt-mark hold libcudnn7 &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 78be558a9e67
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends         build-essential         cmake         git         wget         sudo         python         libcudnn7=$CUDNN_VERSION-1+cuda10.0         libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 &&     apt-mark hold libcudnn7 &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
dennis@xavier:~/object-detection$

**Comment by rajatchopra** [comment]
@DennisFaucher Can you convey what the base image for the Dockerfile is?
On the assumption that your Dockerfile starts with `FROM nvidia/cuda:10.0-devel-ubuntu18.04` or something similar, please note that nvidia/cuda is not a multi-arch image yet. 

Please use nvcr.io/nvidia/l4t-base instead in your Dockerfile e.g.
```
FROM nvcr.io/nvidia/l4t-base:r32.2.1
..
..
```

**Comment by DennisFaucher** [comment]
@rajatchopra Thank you. I am trying to follow these instructions: https://github.com/enesozi/object-detection. I will try your idea.

**Comment by DennisFaucher** [comment]
@rajatchopra I edited the Makefile and got much further. Thank you. I have a feeling that libcudnn is not available for Jetson aarch64. (https://developer.nvidia.com/rdp/cudnn-download)

E: Unable to locate package libcudnn7
E: Unable to locate package libcudnn7-dev
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends         build-essential         cmake         git         wget         sudo         python         libcudnn7=$CUDNN_VERSION-1+cuda10.0         libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 &&     apt-mark hold libcudnn7 &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by rajatchopra** [comment]
@DennisFaucher libcudnn should already be part of your Jetson Xavier l4t. Do not need to bring it as part of your container. Chuck that unnecessary bit out. 
To see if your container will get the host-mounted libcudnn and other libraries, see the contents of files in `/etc/nvidia-container-runtime/host-files-for-container.d/` ! They all get provided for automatically in your docker container on Jetson. 

Note: automount of libraries in the above path will happen only on Jetson :).
Also note: you are now in `experimental` territory :) (as of this writing)

**Comment by DennisFaucher** [comment]
@rajatchopra Thank you.
