### ISSUE TITLE
nvidia-docker2 install error

### ISSUE THREAD

**Issue by stehp** [NVIDIA/nvidia-docker#1118]
### 1. Issue or feature description
Cannot install nvidia-docker2 (Ubuntu 16.04).
### 2. Steps to reproduce the issue
[works] `sudo apt-get update`
[fails] `sudo apt-get --only-upgrade install docker-ce nvidia-docker2`

![install-error](https://user-images.githubusercontent.com/57459066/68340679-e25bc600-00b4-11ea-82df-ec28011321ca.png)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
![container](https://user-images.githubusercontent.com/57459066/68340746-061f0c00-00b5-11ea-86a8-22d42ce2947e.png)

 - [x] Kernel version from `uname -a`
`Linux mylab 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`
`nvidia-smi: command not found` (this command used to work before, but it looks like I broke it when trying to install NVIDIA-DRIVER incorrectly)
 - [x] Docker version from `docker version`
![docker-version](https://user-images.githubusercontent.com/57459066/68340937-5a29f080-00b5-11ea-90c7-4d0e860e574f.png)

 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
![dpkg](https://user-images.githubusercontent.com/57459066/68340994-7d54a000-00b5-11ea-91db-203e460a854e.png)

 - [x] NVIDIA container library version from `nvidia-container-cli -V`
![container-cli](https://user-images.githubusercontent.com/57459066/68341031-93626080-00b5-11ea-8f35-bf58e2551120.png)

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by rajatchopra** [comment]
Can you run `sudo nvidia-container-cli -k -d /dev/tty info` please and paste the output. Thanks!

**Comment by RenaudWasTaken** [comment]
Hello!

nvidia-docker2 is installed on your machine as shown in your screenshot (`nvidia-docker2 is already at the newest version`).

Please follow the instructions your package manager is instructing you to execute :)
