### ISSUE TITLE
no nvidia-container-cli found in  nvidia-container-toolkit-1.0.5-2.x86_64.rpm  

### ISSUE THREAD

**Issue by tanguofu** [NVIDIA/nvidia-docker#1119]
i can't find `nvidia-container-cli` but nvidia-container-cli is in /usr/bin/nvidia-container-cli in uubntu 18.04, so is centos7  with docker 19.03 is not need `nvidia-container-cli`?

**Comment by rajatchopra** [comment]
`nvidia-container-toolkit` wants `libnvidia-container-tools` package which brings in the `nvidia-container-cli` file!
We may eventually have a future where `nvidia-container-cli` is not needed but we are far away from optimizing for that.
Hope this helps.
