### ISSUE TITLE
Does NVIDIA_VISIBLE_DEVICES still work on MPS client container?

### ISSUE THREAD

**Issue by zw0610** [NVIDIA/nvidia-docker#1120]
### 1. Issue or feature description

Assume there is a node with 3 GPUs. The device ids are A, B and C.

Start the mps server in a container with `NVIDIA_VISIBLE_DEVICES=A,B`.

As far as I understand, any client cuda process (in a container) with shared host ipc will be able to send context to mps server, which in this scenario means GPU A or B.

If I set `NVIDIA_VISIBLE_DEVICES=A` for an MPS client container, will it be guaranteed that the cuda process from this container will be executed on GPU A?

Or if I set  `NVIDIA_VISIBLE_DEVICES=C`, what will the mps server do?
If the mps server still accept client context from a container with `NVIDIA_VISIBLE_DEVICES=C`, does `NVIDIA_VISIBLE_DEVICES` still make any sense to the client container?

Any feedback will be appreciated.

**Comment by RenaudWasTaken** [comment]
Hello!


**scenario 1: Incompatible devices (server sees A, client sees B)**:  Should not work
**scenario 2: subset devices (server sees A and B, client sees B)**: Should work as expected, in other words, cuda process should only work on GPU B.
