### ISSUE TITLE
Sometimes creating a pod sandbox container is slow

### ISSUE THREAD

**Issue by Syulin7** [NVIDIA/nvidia-docker#1124]
### 1. Issue or feature description
When kubernetes create a pod, the sandbox container slow to start, it use between 30 and 60 seconds, but init container and container start fast (about 1 second).

I have enable persistence mode
It happens randomly, this happened about once in a hundred times. Most of the time, creating pods is fast.

Both kubelet log and docker log no error, just after 30 second, docker print a log: msg="shim containerd-shim started"

### 2. Steps to reproduce the issue
This situation is difficult to reproduce, I opened docker's debug mode, waiting for it to happen again

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
OS: Ubuntu 16.04.1
kubernetes: v1.11.5
NVIDIA Docker: 2.0.3
docker version: v18.09.2
nvidia-container-runtime --version: runc version 1.0.0-rc6+dev
nvidia-container-cli -V: version: 1.0.1

I have enable persistence mode a few days ago, It doesn't seem to work, I don't know what causes this to happen and how to solve this problem

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [x] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [x] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by RenaudWasTaken** [comment]
Hello!

You haven't attached any logs :)
> docker print a log: msg="shim containerd-shim started"

This points to an issue that happens before we get called so it could be related to kubernetes.
