### ISSUE TITLE
how to run tensorflow/serving:gpu in docker 19.03

### ISSUE THREAD

**Issue by YelongYin** [NVIDIA/nvidia-docker#1127]
Some ERRORs occured When I try to run tensorflow/serving:latest-gpu.
 Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
Ubuntu 16.04.6 LTS
docker version: 19.03
cuda version:9.0

**Comment by nvjmayo** [comment]
Please check that ldconfig is picking up the libraries correctly:
`ldconfig-p | grep libcuda`

how are you launching tensorflow/serving:latest-gpu ?

**Comment by RenaudWasTaken** [comment]
Closing since original author did not comment further.
