### ISSUE TITLE
run vulkan app in docker without display

### ISSUE THREAD

**Issue by david-gwa** [NVIDIA/nvidia-docker#1132]
#### 1. Issue or feature description

how to configure an openGL/Vulkan app in docker without display 

#### 2. vulkan sample image 

[glxgears](https://gitlab.com/nvidia/container-images/samples/blob/master/opengl/ubuntu16.04/glxgears/Dockerfile)

#### 3. docker run 

```
 docker run --runtime=nvidia -ti --rm --env DISPLAY  -v /tmp/.X11-unix:/tmp/.X11-unix glxgears
```

#### 4. docker service create 

```
docker service create --name glx --generic-resource "gpu=1" --constraint 'node.role==manager'  --env DISPLAY glxgears  
```

I follow this issue [Support for swarm mode in Docker 1.12](https://github.com/NVIDIA/nvidia-docker/issues/141#issuecomment-356458450) to configure the swarm.

but it always failed: ` verify: Detected task failure ` -->  ` Error: couldn't open display :0`

wonder Can I just disable display when running OpenGL/Vulkan apps in docker ?  OR is it a bad idea to run/host Vulkan apps in Docker swarm ? 

Thanks
David

**Comment by RenaudWasTaken** [comment]
My guess is that you forgot to run `sudo xhost +`

**Comment by david-gwa** [comment]
yes, additionaly need copy .X11 and Xauthority from host
