### ISSUE TITLE
Issue Log

### ISSUE THREAD

**Issue by Neerucoder** [NVIDIA/nvidia-docker#1138]
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=supervisely-agent-nvIRrxReD45ZBGxFQzVTlI1vV1ALy1H4: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

How to tackle this?

**Comment by RenaudWasTaken** [comment]
Hello!

For all docker issues, please open an issue against Docker. 

Note that this looks like a permission issue. Did you try using sudo?
