### ISSUE TITLE
why all the lib in stubs has the link except libnvidia-ml.so and libcuda.so? (image :nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04)

### ISSUE THREAD

**Issue by ling2yt** [NVIDIA/nvidia-docker#1139]
###  1. Issue or feature description
why all the lib in stubs has the link except libnvidia-ml.so and libcuda.so? 
### 2. Steps to reproduce the issue
docker run --runtime=nvidia --rm nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 /bin/bash -c "ldconfig && find / -name 'libnvidia-ml.so' "

It's just a question but not a issue
Thank you

**Comment by RenaudWasTaken** [comment]
Hello!

They are available :)!
```
docker run -it --gpus all nvidia/cuda:10.0-devel  ls -la /usr/local/cuda/lib64/stubs
total 1140
...
-rw-r--r-- 1 root root  47792 Sep 12  2018 libcuda.so
...
-rw-r--r-- 1 root root  31664 Sep 12  2018 libnvidia-ml.so
```
