### ISSUE TITLE
Wrong cuDNN version in docker image

### ISSUE THREAD

**Issue by ArtanisCV** [NVIDIA/nvidia-docker#114]
The cuda:7.5-cudnn5-devel docker image provided by NVIDIA seems to have a wrong cuDNN version.

Execute `nvidia-docker run nvidia/cuda:7.5-cudnn5-devel dpkg -l | grep libcudnn` produces the following results:
![image](https://cloud.githubusercontent.com/assets/3304030/16106104/00a3cdc2-33c4-11e6-9a54-066512e8f409.png)
It can be seen that libcudnn5 is bound to CUDA 8.0.

I think this may be the reason for the libcudnn initialization failure in #109 . I have met the same initialization problem in another project.

One way to get around this problem is to downgrade the libcudnn (`apt-get install libcudnn5=5.0.5-1+cuda7.5`). But it may be better to re-build the docker image with a correct libcudnn. 

Interestingly, the Dockerfile on the Github(https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/7.5/devel/cudnn5/Dockerfile) seems correct. Is the provided image built from a different Dockerfile?

**Comment by flx42** [comment]
It was a transient problem with our repo, see https://github.com/NVIDIA/DIGITS/issues/801#issuecomment-224331396
It is fixed now.

Please do `docker pull nvidia/cuda:7.5-cudnn5-devel`
