### ISSUE TITLE
RHEL Docker README Section

### ISSUE THREAD

**Issue by rmccorm4** [NVIDIA/nvidia-docker#1140]
### 1. Issue or feature description

[RHEL Docker Section](https://github.com/NVIDIA/nvidia-docker#rhel-docker) has debian/ubuntu-based commands instead of their RHEL/CentOS equivalents.

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the delay, addressed in https://github.com/NVIDIA/nvidia-docker/commit/8d5755fc59a02620dfc55703ee4410ab623c16f2

Thanks for signaling!
