### ISSUE TITLE
Cannot install on Ubuntu 19.10 even with hack

### ISSUE THREAD

**Issue by catskillsresearch** [NVIDIA/nvidia-docker#1142]
distribution=ubuntu18.04
(base) <font color="#4E9A06"><b>catskills@catskills-Z390-AORUS-MASTER</b></font>:<font color="#3465A4"><b>~/Desktop</b></font>$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
OK
(base) <font color="#4E9A06"><b>catskills@catskills-Z390-AORUS-MASTER</b></font>:<font color="#3465A4"><b>~/Desktop</b></font>$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
(base) <font color="#4E9A06"><b>catskills@catskills-Z390-AORUS-MASTER</b></font>:<font color="#3465A4"><b>~/Desktop</b></font>$ sudo apt-get update &amp;&amp; sudo apt-get install -y nvidia-container-toolkit
Get:1 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease [1,106 B]
Get:2 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  InRelease [1,103 B]                 
Get:3 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease [1,096 B]                                                
Hit:4 http://us.archive.ubuntu.com/ubuntu eoan InRelease                                                                           
Get:5 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  Packages [5,948 B]                                 
Get:6 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]                                                         
Get:7 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  Packages [4,712 B]                                      
Ign:8 https://download.docker.com/linux/ubuntu eoan InRelease                                                                      
Get:9 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  Packages [3,864 B]        
Get:10 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]                            
Get:11 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]   
Err:12 https://download.docker.com/linux/ubuntu eoan Release                                
  404  Not Found [IP: 2600:9000:211c:9600:3:db06:4200:93a1 443]
Get:13 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 DEP-11 Metadata [25.5 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu eoan-updates/main DEP-11 48x48 Icons [7,788 B]
Get:15 http://us.archive.ubuntu.com/ubuntu eoan-updates/main DEP-11 64x64 Icons [11.4 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe amd64 DEP-11 Metadata [24.3 kB]                
Get:17 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe DEP-11 48x48 Icons [14.6 kB]                                      
Get:18 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe DEP-11 64x64 Icons [22.9 kB]                                      
Get:19 http://us.archive.ubuntu.com/ubuntu eoan-backports/universe amd64 DEP-11 Metadata [7,752 B]                                 
Get:20 http://security.ubuntu.com/ubuntu eoan-security/main amd64 DEP-11 Metadata [204 B]                           
Hit:21 http://linux.teamviewer.com/deb stable InRelease                       
Get:22 http://security.ubuntu.com/ubuntu eoan-security/universe amd64 DEP-11 Metadata [1,416 B]
Reading package lists... Done                
E: The repository &apos;https://download.docker.com/linux/ubuntu eoan Release&apos; does not have a Release file.
N: Updating from such a repository can&apos;t be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
(base) <font color="#4E9A06"><b>catskills@catskills-Z390-AORUS-MASTER</b></font>:<font color="#3465A4"><b>~/Desktop</b></font>$ curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
(base) <font color="#4E9A06"><b>catskills@catskills-Z390-AORUS-MASTER</b></font>:<font color="#3465A4"><b>~/Desktop</b></font>$ 

</pre>

**Comment by catskillsresearch** [comment]
PS I guess I can build it from scratch, that seems to be working so far.  But still, 19.10 anybody?

**Comment by catskillsresearch** [comment]
This seemed to improve matters:

base) catskills@catskills-Z390-AORUS-MASTER:~/Desktop$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-runtime nvidia-container-toolkit
The following NEW packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-runtime nvidia-container-toolkit
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 1,262 kB of archives.
After this operation, 4,136 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  libnvidia-container1 1.0.5-1 [59.2 kB]
Get:2 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  libnvidia-container-tools 1.0.5-1 [15.6 kB]
Get:3 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  nvidia-container-toolkit 1.0.5-1 [575 kB]
Get:4 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  nvidia-container-runtime 3.1.4-1 [612 kB]
Fetched 1,262 kB in 1s (1,931 kB/s)               
Selecting previously unselected package libnvidia-container1:amd64.
(Reading database ... 199908 files and directories currently installed.)
Preparing to unpack .../libnvidia-container1_1.0.5-1_amd64.deb ...
Unpacking libnvidia-container1:amd64 (1.0.5-1) ...
Selecting previously unselected package libnvidia-container-tools.
Preparing to unpack .../libnvidia-container-tools_1.0.5-1_amd64.deb ...
Unpacking libnvidia-container-tools (1.0.5-1) ...
Selecting previously unselected package nvidia-container-toolkit.
Preparing to unpack .../nvidia-container-toolkit_1.0.5-1_amd64.deb ...
Unpacking nvidia-container-toolkit (1.0.5-1) ...
Selecting previously unselected package nvidia-container-runtime.
Preparing to unpack .../nvidia-container-runtime_3.1.4-1_amd64.deb ...
Unpacking nvidia-container-runtime (3.1.4-1) ...
Setting up libnvidia-container1:amd64 (1.0.5-1) ...
Setting up libnvidia-container-tools (1.0.5-1) ...
Setting up nvidia-container-toolkit (1.0.5-1) ...
Setting up nvidia-container-runtime (3.1.4-1) ...
Setting up nvidia-docker2 (2.2.2-1) ...
Processing triggers for libc-bin (2.30-0ubuntu2) ...
/sbin/ldconfig.real: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

**Comment by catskillsresearch** [comment]
And yikes I guess I'll close this one, but I have no idea how I got here:

(base) catskills@catskills-Z390-AORUS-MASTER:~/Desktop/nvidia-docker/dist/ubuntu18.04/amd64$ sudo systemctl restart docker
(base) catskills@catskills-Z390-AORUS-MASTER:~/Desktop/nvidia-docker/dist/ubuntu18.04/amd64$ Reading state information... Done
Reading: command not found
(base) catskills@catskills-Z390-AORUS-MASTER:~/Desktop/nvidia-docker/dist/ubuntu18.04/amd64$ docker --version
Docker version 19.03.2, build 6a30dfca03

(base) catskills@catskills-Z390-AORUS-MASTER:~/Desktop/nvidia-docker/dist/ubuntu18.04/amd64$ sudo docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
Unable to find image 'nvidia/cuda:9.0-base' locally
9.0-base: Pulling from nvidia/cuda
976a760c94fc: Already exists 
c58992f3c37b: Already exists 
0ca0e5e7f12e: Already exists 
f2a274cc00ca: Already exists 
708a53113e13: Pull complete 
371ddc2ca87b: Pull complete 
f81888eb6932: Pull complete 
Digest: sha256:56bfa4e0b6d923bf47a71c91b4e00b62ea251a04425598d371a5807d6ac471cb
Status: Downloaded newer image for nvidia/cuda:9.0-base
Sun Dec  1 19:50:17 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   42C    P8     2W / 300W |    311MiB / 11016MiB |     11%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   34C    P8     4W / 120W |      2MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by RenaudWasTaken** [comment]
I want to point out that you seemed to start from an unclean install, where the docker repos weren't correctly setup :) 

```
E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
You probably didn't need to manually compile the packages.

**Comment by catskillsresearch** [comment]
> I want to point out that you seemed to start from an unclean install, where the docker repos weren't correctly setup :)
> 
> ```
> E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> You probably didn't need to manually compile the packages.

Please post a clean uninstall / install procedure for Docker followed by Nvidia docker for Ubunto 19.10.

**Comment by catskillsresearch** [comment]
Seek advice

**Comment by RenaudWasTaken** [comment]
Hello!

> Please post a clean uninstall / install procedure for Docker followed by Nvidia docker for Ubunto 19.10.

This is up to your installation, you should checkout the docker docs though: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by catskillsresearch** [comment]
@RenaudWasTaken ,  I am not the only person to make the mistake of installing the latest and greatest Ubuntu instead of 18.04, and then trying to do NVidia stuff, where NVIdia has only release 18.04 procedures.  For those of us happening onto the bleeding edge by accident, the NVidia docs on how to install nvidia-docker are hopelessly confusing, especially when nvidia-docker has morphed into nvidia-container-ecosystem-appliance-assembly and nvidia-docker2 and it wasn't clear to begin with what the difference between nvidia-docker and plain old docker was to begin with.  Ubuntu also comes with several different ways of installing things, such as snap install, apt-get install, and download the git and build it yourself install.  In the end I just want a vanilla docker and a vanilla ndvidia-docker, whatever that is.  Since you are an NVidia employee, and the customer is always right, I am phrasing this in customer to vendor terms: it's a mess, please make it easier.  The way you could make it easier, as an NVidia guru, is to post the 5 or 10 lines it would take to uninstall docker, uninstall any remnants of nvidia-docker, and install docker and then ndvidia-docker, however named, from scratch, on the latest version of Ubuntu.  I am reasonably certain it would be 10 lines max.
