### ISSUE TITLE
How to upgrade the container from 1 gpu to 2 gpus via API interface

### ISSUE THREAD

**Issue by deepbraindeveloper** [NVIDIA/nvidia-docker#1144]
How to upgrade the container from 1 gpu to 2 gpus via API interface？

update API  REQUEST
{
    "Env": [
        "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
        "NVIDIA_VISIBLE_DEVICES=2,3"
    ],
    "Memory": 31600000000,
    "MemorySwap": 61600000000,
    "CpuShares": 1600,
    "StorageOpt": {
        "size": "270G"
    }
}
No effect whatsoever

**Comment by RenaudWasTaken** [comment]
Hello!

This is currently not possible. We will keep that in mind as a feature request, though this is typically not something that fits very well with the container model.
e.g: Though Docker allows you to change the amount of CPUs, it doesn't allow you to attach volumes.
