### ISSUE TITLE
Improve instructions for updating repository keys for RHEL-based distributions

### ISSUE THREAD

**Issue by masterleinad** [NVIDIA/nvidia-docker#1147]
The steps for updating the repository keys for RHEL-based distributions in https://nvidia.github.io/nvidia-docker/ should read:
```bash
$ DIST=$(sed -n 's/releasever=//p' /etc/yum.conf)
$ DIST=${DIST:-$(. /etc/os-release; echo $VERSION_ID)}
$ sudo rpm -e gpg-pubkey-f796ecb0
$ sudo gpg --homedir /var/lib/yum/repos/$(uname -m)/$DIST/*/gpgdir --delete-key f796ecb0
$ sudo gpg --homedir /var/lib/yum/repos/$(uname -m)/*/nvidia-docker/gpgdir --delete-key f796ecb0
$ sudo gpg --homedir /var/lib/yum/repos/$(uname -m)/*/nvidia-container-runtime/gpgdir --delete-key f796ecb0
$ sudo gpg --homedir /var/lib/yum/repos/$(uname -m)/*/libnvidia-container/gpgdir --delete-key f796ecb0
$ sudo yum update
```
similar to the instructions for `Amazon Linux`. Using `latest` instead of `*` (or `$DIST`) didn't work for me and it cost me some time to figure out the problem.

**Comment by discordianfish** [comment]
This is also not updating the keys, it's just removing the old key. It's missing how to explicitly add the keys so that non-interactive install of the package works. Everywhere people seem to disable gpg verification instead..

**Comment by Jnifong** [comment]
Besides disabling the gpg verification (which is not preferred) what is the fix for getting a working key installed that works. Seems like a long time to have a issue open with no response.

**Comment by nvjmayo** [comment]
The above isn't the recommend process for updating. Renewing the GPG keys by following the same steps as initially performed is recommend. 

Distribution's key management is outside the scope of this project. closing.
