### ISSUE TITLE
Running GUI apps under nvidia-docker

### ISSUE THREAD

**Issue by Suhail** [NVIDIA/nvidia-docker#1148]
I'd like to:

- Run Google Chrome under X
- For X to store its pixels in VRAM with the GPU

I noticed this FAQ item: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-opengl-supported and noticed that `nvidia-xconfig` command is not bundled with the 430.50 driver that it normally comes with.

Is it possible to run X, google chrome, etc. like you normally would outside of a container with this?

This is possible without nvidia-docker so I am wondering what I could do to solve this.

I tried to install X and run nvidia-xconfig using the image specified in the README.

**Comment by Suhail** [comment]
I also noticed this issue that's 2 years old: https://github.com/NVIDIA/nvidia-docker/issues/529

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the lack of answer, there are numerous articles that discuss this topic among them you probably want to take a look at:
- https://devblogs.nvidia.com/gpu-containers-runtime/
- https://blog.jessfraz.com/post/docker-containers-on-the-desktop/
- ...
