### ISSUE TITLE
Creating Docker container extend from 7.5-cudnn5-runtime does not have cudnn libs installed

### ISSUE THREAD

**Issue by hsaputra** [NVIDIA/nvidia-docker#115]
I am creating Dockerfile that extend from 7.5-cudnn5-runtime:
`FROM nvidia/cuda:7.5-cudnn5-runtime`

and when I run the Docker image, the container does not have cuDNN installed:

```
ls -ltr /usr/local/cuda/lib/*dnn*
ls: cannot access '/usr/local/cuda/lib/*dnn*' : No such file or directory
```

**Comment by flx42** [comment]
```
nvidia-docker run -ti nvidia/cuda:7.5-cudnn5-runtime sh -c 'ldconfig -p | grep cudnn'
        libcudnn.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so.5
```

**Comment by hsaputra** [comment]
Ah, so thats where it is installed. Thanks!

**Comment by flx42** [comment]
Yes, that's because the deb package of cuDNN installs at this location, that's the standard install path for packages.
For cuDNN v3 we didn't have a deb package so I installed in `/usr/local/cuda` with the rest of the CUDA libs.

**Comment by hsaputra** [comment]
Thanks @flx42. Wonder why CUDA installed in the `/user/local/cuda` instead.
