### ISSUE TITLE
Docker Behind a Proxy in a Shared Computer

### ISSUE THREAD

**Issue by walsanie** [NVIDIA/nvidia-docker#1150]
I am using nvidia-docker in an Ubuntu 18.04 shared server behind a corporate proxy. I tried to build a docker image using the:

nvidia-docker build --build-arg http_proxy=http://credential@host:port --build_arg https_proxy=http://credential@host.port -t image_name .

But it always gives me:

Get https://registry-1.docker.io/v2/: Proxy Authentication Required

I tried to set the environment variables separately as:

export http_proxy=…
export https_proxy=…
export HTTP_proxy=…
export HTTPS_PROXY=…

But all the above didn’t work and the same error message comes again!

The error message comes aslo with “docker” not just “nvidia-docker”

Setting the proxy in system files like /etc/default/docker is not an option for me as the computer is shared and this will disclose my credentials.

Any solution for this please?

**Comment by useafterfree** [comment]
I think this is related to Docker on Ubuntu 18 hard-wired to 8.8.8.8, which likely is blocked on your proxied network.

You can fix that by using the host resolver, and adding in your own DNS server.

Fix resolver on Ubuntu18:
```
    rm /etc/resolv.conf
    ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```

Wire docker machine `/etc/docker/daemon.json` to use a custom DNS (in this case 1.1.1.1):
```
{
    "dns": ["1.1.1.1"]
}
```


good luck!

**Comment by walsanie** [comment]
I am afraid this didn't solve the problem. 

Thank you very much for the response.

**Comment by useafterfree** [comment]
I think you may want to build the docker image, and then pass in the proxy settings at runtime, but creating a localfile which contains the settings necessary (i.e. `proxySettings.sh`)
`nvidia-docker run --env-file ./proxySettings.sh image`

from: https://docs.docker.com/engine/reference/commandline/run/

**Comment by walsanie** [comment]
Thank you for the response. However, this unfortunately does not solve the problem. Storing the proxy setting in a file will disclose the credential.

**Comment by useafterfree** [comment]
Will using --env like:
`docker run -it --env http_proxy="http://192.168.33.10:3128/"  ubuntu:latest`
work?

**Comment by RenaudWasTaken** [comment]
Hello!

This looks like a docker issue rather than an nvidia-docker issue :)
That being said @useafterfree is correct, you probably want to go the --env-file or --env route.

Closing for now :)
