### ISSUE TITLE
apt-get update failure on image

### ISSUE THREAD

**Issue by didibaba** [NVIDIA/nvidia-docker#1151]
When apt updating nvidia/cudagl:9.0-devel-ubuntu16.04, I got the error E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by cliffwoolley** [comment]
@demizer

**Comment by lingchen1991** [comment]
same issue there!!!

**Comment by demizer** [comment]
Hi. Occasionally when the machine learning repos are update this issue occurs. It's fixed now. Thanks!

**Comment by dualvtable** [comment]
Thanks - closing this issue. Please re-open if seen again.
