### ISSUE TITLE
nvidia-docker keep saying: Unit nvidia-docker.service could not be found.

### ISSUE THREAD

**Issue by 652994331** [NVIDIA/nvidia-docker#1156]
Guy, really need some help here. I installed docker-ce 18.03 and the  installed the nvidia-docker2. I started the docker-ce, the status is runing(green button). My nvidia driver and cuda version is :418.116 and cuda 10. When i started to start nviida-docker. it said:Unit nvidia-docker.service could not be found.
Can anyone help me out? thanks so much.

**Comment by RenaudWasTaken** [comment]
Hello!

With nvidia-docker2 you don't need to start a service, follow the readme here to get quickly to a running container: https://github.com/NVIDIA/nvidia-docker
