### ISSUE TITLE
Error occurred when apt-get nvidia-container-toolkit

### ISSUE THREAD

**Issue by lingchen1991** [NVIDIA/nvidia-docker#1157]
When I use the command 'sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit' to install nvidia-docker,

the following 'hash sum mismatch' error come up.

====Error====

Get:1 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial InRelease [247 kB]
Get:2 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-backports InRelease [107 kB]
Hit:4 https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  InRelease
Hit:5 https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64  InRelease
Get:6 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease [3959 B]
Get:7 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages [166 kB]
Hit:8 https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64  InRelease
Hit:9 http://security.ubuntu.com/ubuntu xenial-security InRelease
Err:7 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
  Hash Sum mismatch
Ign:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Ign:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Hit:12 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release
Hit:14 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release
Fetched 589 kB in 11s (52.2 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/dists/xenial/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
===========

**Comment by NullYing** [comment]
```
E: Failed to fetch https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (30448 != 25522). Mirror sync in progress? [IP: 27.148.207.26 443]
   Hashes of expected file:
    - Filesize:25522 [weak]
    - SHA256:4cf1bcf406c9e03c5baae892f19587313985016da984db7bce4d6314feb5c42a
    - SHA1:87db0aa018f610eb6e8098f7c1d49d5dbdac9597 [weak]
    - MD5Sum:ab5112ddc609b0e2b30980304796378d [weak]
   Release file created at: Wed, 04 Dec 2019 20:16:09 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead
```

**Comment by RenaudWasTaken** [comment]
Hello!

The above error message also seems to specify an issue with the microsoft package repositories:
```
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/dists/xenial/main/binary-amd64/Packages.gz Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

You probably want to try to cleanup your machine and try again :)
Package installation seems to be working on my side.

I hope this helps!
