### ISSUE TITLE
The following packages have unmet dependencies: nvidia-container-toolkit , nvidia-cuda-toolkit 

### ISSUE THREAD

**Issue by AzmHmd** [NVIDIA/nvidia-docker#1158]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by AzmHmd** [comment]
here is the error:

(base) A@MOPLT:~$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
[sudo] password for A: 
Get:1 file:/var/cuda-repo-10-2-local-10.2.89-440.33.01  InRelease
Ign:1 file:/var/cuda-repo-10-2-local-10.2.89-440.33.01  InRelease
Get:2 file:/var/cuda-repo-10-2-local-10.2.89-440.33.01  Release [574 B]
Get:2 file:/var/cuda-repo-10-2-local-10.2.89-440.33.01  Release [574 B]
Hit:3 http://gb.archive.ubuntu.com/ubuntu bionic InRelease                                                                         
Get:4 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                    
Hit:5 http://192.168.213.104/deb xenial InRelease                                                                               
Hit:6 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                                                        
Get:7 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                     
Ign:8 http://dl.google.com/linux/chrome/deb stable InRelease                                                                       
Hit:9 https://download.docker.com/linux/ubuntu bionic InRelease                                                                    
Hit:10 http://dl.google.com/linux/chrome/deb stable Release                                                               
Get:11 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                        
Hit:13 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease
Hit:14 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  InRelease
Hit:15 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
Fetched 252 kB in 3s (100 kB/s)                    
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://192.168.213.104/deb xenial InRelease' doesn't support architecture 'i386'
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 nvidia-container-toolkit : Depends: libnvidia-container-tools (>= 0.1.0) but it is not going to be installed
                            Depends: libnvidia-container-tools (< 2.0.0) but it is not going to be installed
 nvidia-cuda-toolkit : Depends: nvidia-cuda-dev (= 9.1.85-3ubuntu1) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

-------------------------------------------------------------------------------------------------------------------------------
here is some information:
(base) A@MOPLT:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

(base) A@MOPLT:~$ uname -a
Linux 20345MOPLT 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

(base) A@MOPLT:~$ nvidia-smi 
Fri Dec 13 16:06:30 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        On   | 00000000:B3:00.0  On |                  Off |
| 31%   44C    P0    34W / 250W |   1846MiB / 32505MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1616      G   /usr/lib/xorg/Xorg                           214MiB |
|    0      1833      G   /usr/bin/gnome-shell                          25MiB |
|    0     13460      G   /usr/lib/xorg/Xorg                           150MiB |
|    0     13624      G   /usr/bin/gnome-shell                         406MiB |
|    0     28881      G   /usr/lib/xorg/Xorg                           649MiB |
|    0     29047      G   /usr/bin/gnome-shell                         327MiB |
|    0     29439      G   ...quest-channel-token=7449607639174773349    68MiB |
+-----------------------------------------------------------------------------+

**Comment by AzmHmd** [comment]
(base) A@MOPLT:~$ uname -a
Linux 20345MOPLT 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AzmHmd** [comment]
$ nvidia-smi 
Fri Dec 13 16:06:30 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        On   | 00000000:B3:00.0  On |                  Off |
| 31%   44C    P0    34W / 250W |   1846MiB / 32505MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1616      G   /usr/lib/xorg/Xorg                           214MiB |
|    0      1833      G   /usr/bin/gnome-shell                          25MiB |
|    0     13460      G   /usr/lib/xorg/Xorg                           150MiB |
|    0     13624      G   /usr/bin/gnome-shell                         406MiB |
|    0     28881      G   /usr/lib/xorg/Xorg                           649MiB |
|    0     29047      G   /usr/bin/gnome-shell                         327MiB |
|    0     29439      G   ...quest-channel-token=7449607639174773349    68MiB |
+-----------------------------------------------------------------------------+

**Comment by AzmHmd** [comment]
(base) A@MOPLT:~$ docker version
Client: Docker Engine - Community
Version: 19.03.5
API version: 1.40
Go version: go1.12.12
Git commit: 633a0ea838
Built: Wed Nov 13 07:29:52 2019
OS/Arch: linux/amd64
Experimental: false
Server: Docker Engine - Community
Engine:
Version: 19.03.5
API version: 1.40 (minimum version 1.12)
Go version: go1.12.12
Git commit: 633a0ea838
Built: Wed Nov 13 07:28:22 2019
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.2.10
GitCommit: b34a5c8af56e510852c35414db4c1f4fa6172339
runc:
Version: 1.0.0-rc8+dev
GitCommit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
docker-init:
Version: 0.18.0
GitCommit: fec3683

**Comment by RenaudWasTaken** [comment]
Hello!

It looks like your machine is misconfigured :)

```
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
```

You should probably remove the following file: `/etc/apt/sources.list.d/nvidia-container-runtime.list`
Or just run `apt --fix-broken install`

```
nvidia-cuda-toolkit : Depends: nvidia-cuda-dev (= 9.1.85-3ubuntu1) but it is not going to be installed
```

Looks like you didn't install the nvidia driver, start with that first: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by FranciscoReveriano** [comment]
I am su ffering from the same problem.
