### ISSUE TITLE
If I install CUDA and CUDNN on the host machine, will it affect the use of nvidia docker ?

### ISSUE THREAD

**Issue by zdptrsz** [NVIDIA/nvidia-docker#1159]
My OS is Ubuntu 18.04.
If I install CUDA and CUDNN on the host machine, will it affect the use of nvidia docker  ?

Because i encountered an error，I'm not sure if it's because I installed CUDA on the host machine?
2019-12-18 11:53:50.903484: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (-1)

**Comment by dualvtable** [comment]
hi there,

No - this should not affect the use of CUDA within the containers. Is your CUDA installation on the host working ok? I.e. have you verified this by running CUDA samples for example? 

What driver versions do you have on the host? What CUDA version is your container based on?
