### ISSUE TITLE
nvidia-docker-plugin not started

### ISSUE THREAD

**Issue by cracker0dks** [NVIDIA/nvidia-docker#116]
I installed from the mainpage on ubuntu and got the error:

`docker: Error response from daemon: create nvidia_driver_352.63: create nvidia_driver_352.63: Error looking up volume plugin nvidia-docker: plugin not found.`

when i tried to test:
`nvidia-docker run --rm nvidia/cuda nvidia-smi`

so you have start it manually now ? after:
`nvidia-docker-plugin`
everything is fine! 

I think this is a bug :)

**Comment by 3XX0** [comment]
If you are running Ubuntu the package install should setup everything automatically.

You can check the status of the plugin using
`service nvidia-docker status` or `systemctl status nvidia-docker`

**Comment by cracker0dks** [comment]
I thought this as well... but did not work for me...

**Comment by 3XX0** [comment]
What is the output of the above commands? Can you check the upstart/systemd logs as well

**Comment by cracker0dks** [comment]
`$: service nvidia-docker status`
gives
`nvidia-docker stop/waiting` 

but I started nvidia-docker-plugin manually. Which logfile should I look at in systemd?

**Comment by 3XX0** [comment]
If you are running upstart (Ubuntu 14.04): `/var/log/upstart/nvidia-docker.log`
Otherwise, with systemd (Ubuntu 16.04): `journalctl -n -u nvidia-docker`

**Comment by cracker0dks** [comment]
this is the log:
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:37 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:37 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Error: listen unix /var/lib/nvidia-docker/nvidia-docker.sock: bind: permission denied
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:38 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Error: listen unix /var/lib/nvidia-docker/nvidia-docker.sock: bind: permission denied
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Error: listen unix /var/lib/nvidia-docker/nvidia-docker.sock: bind: permission denied
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Error: listen unix /var/lib/nvidia-docker/nvidia-docker.sock: bind: permission denied
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Error: listen unix /var/lib/nvidia-docker/nvidia-docker.sock: bind: permission denied
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/06/28 22:02:39 Error: listen unix /var/lib/nvidia-docker/nvidia-docker.sock: bind: permission denied


what can I do?

**Comment by flx42** [comment]
Did you install an old version of nvidia-docker previously on this machine?
Try purging nvidia-docker totally and reinstalling it:
```
apt-get purge nvidia-docker
rm -rf /var/lib/nvidia-docker
```

**Comment by cracker0dks** [comment]
yeah thats it! reinstalled and worked! thanks ;)

**Comment by shadiakiki1986** [comment]
My 2 cents: I had installed `nvidia-docker` before installing the GPU drivers, CUDA libraries, ...
 was `failed to start`. Installing all necessary drivers/libraries followed by a `service nvidia-docker restart` resulted in a `service nvidia-docker status` showing `running`

**Comment by lijecaru** [comment]
@shadiakiki1986 works very well, thanks!
