### ISSUE TITLE
observing the ERRO[0003] error waiting for container: context canceled when I use "docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi"

### ISSUE THREAD

**Issue by krishnadasari610** [NVIDIA/nvidia-docker#1161]
**command :** docker run -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:9.0-base nvidia-smi
**output** : docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused "process_linux.go:432: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\n\""": unknown.
ERRO[0003] error waiting for container: context canceled

**Method 2**
**command**nvidia-docker run nvidia/cuda:9.0-base nvidia-smi
**output**
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused "process_linux.go:432: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\n\""": unknown.
ERRO[0002] error waiting for container: context canceled

followed link:
https://github.com/NVIDIA/nvidia-docker
https://docs.nvidia.com/deeplearning/frameworks/user-guide/index.html#runcont
![Screenshot from 2019-12-19 12-39-27](https://user-images.githubusercontent.com/19946280/71154602-de00fc00-2261-11ea-9a05-6c3498981bad.png)
The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [x] Docker command, image and tag used

**Comment by krishnadasari610** [comment]
When I use Dockerfile.ubuntu for my pc I am seeing the below issue. can someone provide the fix for the same.
**https://github.com/NVIDIA/nvidia-docker/Dockerfile.ubuntu**


Step 20/21 : RUN sed -i "s;@VERSION@;${REVISION};" debian/changelog &&     sed -i "s;@VERSION@;${PKG_VERS};" $DIST_DIR/nvidia-docker &&     if [ "$REVISION" != "$(dpkg-parsechangelog --show-field=Version)" ]; then echo "$(dpkg-parsechangelog --show-field=Version)" && exit 1; fi
 ---> Running in f3fc7672310d
dpkg-parsechangelog: warning:     debian/changelog(l1): version '-' is invalid: upstream version cannot be empty
LINE: nvidia-docker2 (-) UNRELEASED; urgency=medium
dpkg-parsechangelog: warning:     debian/changelog(l1): version '-' is invalid: upstream version cannot be empty
LINE: nvidia-docker2 (-) UNRELEASED; urgency=medium
unknown
The command '/bin/sh -c sed -i "s;@VERSION@;${REVISION};" debian/changelog &&     sed -i "s;@VERSION@;${PKG_VERS};" $DIST_DIR/nvidia-docker &&     if [ "$REVISION" != "$(dpkg-parsechangelog --show-field=Vadmin@test-Precision-5820-Tower:~/Desktop/BIO_Docker_Project/nvidia-docker-master$ returned a non-zero code: 1
![Screenshot from 2019-12-19 13-09-48](https://user-images.githubusercontent.com/19946280/71154446-8793bd80-2261-11ea-9e35-a800debadc1d.png)

**Comment by RenaudWasTaken** [comment]
Hello!

The error you are getting is: `no cuda-capable device is detected`
Additionally, it looks like you didn't attach any logs (e.g: `nvidia-container-cli -k -d /dev/tty info`).

In any case here is a quick checklist:
- [ ] Do you have a GPU on the machine
- [ ] Did you install the nvidia driver
- [ ] What is nvidia-smi's output on the host

**Comment by RenaudWasTaken** [comment]
Closing with no answer.

**Comment by krishnadasari610** [comment]
Hi Team, I found the solution and it got worked for me.Thanks for the reply  Sent from Mail for Windows 10 From: Renaud GaubertSent: 11 February 2020 03:27To: NVIDIA/nvidia-dockerCc: krishna dasari; AuthorSubject: Re: [NVIDIA/nvidia-docker] observing the ERRO[0003] error waiting for container: context canceled when I use "docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi" (#1161) Closing with no answer.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
