### ISSUE TITLE
unknown flag: --gpus

### ISSUE THREAD

**Issue by DawnChou** [NVIDIA/nvidia-docker#1165]
I'm a user who used nvidia-docker2 package and I have finished the update according to " “Upgrading with nvidia-docker2” section.". 
However, the instrument` docker run --gpus all nvidia/cuda:9.0-base nvidia-smi` could not work and it showed `unknown flag: --gpus`. While the `docker run --runtime nvidia nvidia/cuda:9.0-base nvidia-smi` can still work successfully,  I suppose that I've upgrade the nvidia-docker, so why it still shows`unknow flag: --gpus`? 
Here is my docker info:
`Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 6
Server Version: 19.03.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-66-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.8GiB
Name: user-ubuntu
ID: 3ALP:YNHK:JKZJ:3VV2:NAZ5:OGAQ:PPVX:K6K5:U4OV:FLEZ:DP5H:JIXM
Docker Root Dir: /home/software/docker2
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Comment by dualvtable** [comment]
hi there,

Are you using Docker >= 19.03? If so, you will need to use the `nvidia-container-toolkit` package as specified in this section of the README
[https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster](url)

After you restart the Docker daemon, you should be able to use the `--gpus` option. Please let us know if there are still issues. 

Thanks

**Comment by root20** [comment]
Hi, I have same problem. 
Followed the instruction in the link, but still got same error message.

Also, I got the following error (or warning) while running command:
`$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit` 

error (or warning):

> W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages Failed to download files.  403  Forbidden [IP: 91.189.95.83 80]
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by DawnChou** [comment]
> hi there,
> 
> Are you using Docker >= 19.03? If so, you will need to use the `nvidia-container-toolkit` package as specified in this section of the README
> [https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster](url)
> 
> After you restart the Docker daemon, you should be able to use the `--gpus` option. Please let us know if there are still issues.
> 
> Thanks

Thanks for your reply. "Docker info" shows the server Version is 19.03.5. And the `nvidia-container-toolkit` has already been installed. However,the problem still exists, `unknown flag: --gpus`

**Comment by root20** [comment]
@DawnChou 
Is Client docker engine version >= 19.03?
I solved this problem by upgrading docker client.
`$ sudo apt-get install docker-ce-cli`

**Comment by DawnChou** [comment]
Thank you very much! This really helps me! I've never thought of it. And I just checked the "docker version" and found that the Client Version is different with the Server Version, after I upgraded docker. So the problem indeed results from the client version is still 18.03 and not upgraded with Server.



At 2019-12-30 15:48:59, "Younggun Lee" <notifications@github.com> wrote:

@DawnChou
Is Client docker engine version >= 19.03?
I solved this problem by upgrading docker client.
$ sudo apt-get install docker-ce-cli

**Comment by mianasbat** [comment]
> @DawnChou Is Client docker engine version >= 19.03? I solved this problem by upgrading docker client. `$ sudo apt-get install docker-ce-cli`

To update to 5.19.03 I have added the following steps [steps](https://stackoverflow.com/a/69480298/610607
)
