### ISSUE TITLE
Possible to run (software-rendered) opengl application inside nvidia-docker? 

### ISSUE THREAD

**Issue by kohillyang** [NVIDIA/nvidia-docker#1166]
Our lab share a workstation  with 8 P40 GPUs. The workstation has no monitor. We access its docker-image  via ssh and remote-desktop installed inside nvidia-docker. The only problem is that all applications needing opengl greater than 1.2 crashed. For example, Pangolin crashes with:
```bash
terminate called after throwing an instance of 'std::runtime_error'
what(): Pangolin X11: Unable to retrieve framebuffer options
Aborted (core dumped)
```

So, Is it possible to run opengl application inside nvidia-docker? I just want these application does not crash and don't care the performance. Thanks.

**Comment by kohillyang** [comment]
I know hardware-accelerated opengl is almost impossible, but I'm wondering if using software emulated opengl is possible.

**Comment by RenaudWasTaken** [comment]
Hello!

It should be possible to run OpenGL applications in a container.
You can take a look at our images and blog:
- https://hub.docker.com/r/nvidia/opengl
- https://devblogs.nvidia.com/gpu-containers-runtime/

That being said it could be an issue with your software and how it uses X11.
I hope this helps you!
