### ISSUE TITLE
container usr/local/nvidia  is empty

### ISSUE THREAD

**Issue by lvcaiping** [NVIDIA/nvidia-docker#1167]
@flx42
hi，i  have  install docker-ce and navida-docker1 on  Gpu device，and diver  is  intall ok.
then i run   nvidia-docker run --rm nvidia/cuda  nvidia-smi  is fail， error is

container_linux.go:247: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH"

**Comment by lvcaiping** [comment]
the  direct reason  is /usr/local/nvidia is empty, but i do not know the  real reason.

the VM volume is ok
# docker volume ls
DRIVER              VOLUME NAME
nvidia-docker       nvidia_driver_410.48

**Comment by RenaudWasTaken** [comment]
Hello!

nvidia-docker1 is deprecated (for now 2 years), you really should update to nvidia-docker2!
I'd be happy to help you if you encounter any issue with the newest version :)
