### ISSUE TITLE
Building TF in l4t-base

### ISSUE THREAD

**Issue by maingoh** [NVIDIA/nvidia-docker#1169]
I am trying to build tensorflow from l4t-base image but it looks like some files are missing at build time (libdevice*.10.bc, libcudart.so.10*, cupti.h).

I have read the wiki but I am a bit confused, is the mount plugins able to mount files at build time, or just for runtime ? Can we use `RUN --mount` with `# syntax = docker/dockerfile:experimental` ?

What would be the best way to get them ? With a maximum of portability. 
Is there a plan to provide them in the future images ?

Thank you very much,

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the long delay. Jetson support is still pretty experimental and suject to a lot of change.
TF support and better CUDA images is definitely on the roadmap! Unfortunately the team is currently focused on our GPU Operator work. We are more likely to handle this in the second part of the year.

Keeping open until we resolve this.
