### ISSUE TITLE
small doc issue

### ISSUE THREAD

**Issue by saurabhRTR** [NVIDIA/nvidia-docker#117]
I had to sudo this command -

````
sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
````

not a big issue, just something small for the documentation (assuming I'm not alone)

**Comment by Kaixhin** [comment]
This is a Docker issue - more details can be found in the [official docs](https://docs.docker.com/engine/installation/linux/ubuntulinux/#create-a-docker-group). Basically it is possible to run `docker`/`nvidia-docker` without sudo, but most people choose not to.

**Comment by saurabhRTR** [comment]
thanks... 
PS, also this is an amazing resource.
