### ISSUE TITLE
Failed to run nvidia-docker container

### ISSUE THREAD

**Issue by yuanbing** [NVIDIA/nvidia-docker#1170]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

I cannot run nvidia container with GPU enabled. 

### 2. Steps to reproduce the issue

docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`

-- WARNING, the following logs are for debugging purposes only --

I0115 09:20:37.294036 4304 nvc.c:281] initializing library context (version=1.0.6, build=0000000000000000000000000000000000000000)
I0115 09:20:37.294142 4304 nvc.c:255] using root /
I0115 09:20:37.294166 4304 nvc.c:256] using ldcache /etc/ld.so.cache
I0115 09:20:37.294182 4304 nvc.c:257] using unprivileged user 1000:1000
W0115 09:20:37.297221 4305 nvc.c:186] failed to set inheritable capabilities
W0115 09:20:37.297314 4305 nvc.c:187] skipping kernel modules load due to failure
I0115 09:20:37.297949 4306 driver.c:133] starting driver service
I0115 09:20:37.340783 4304 nvc_info.c:437] requesting driver information with ''
nvidia-container-cli: detection error: driver error: failed to process request
I0115 09:20:37.341021 4304 nvc.c:318] shutting down library context
W0115 09:20:37.351295 4304 driver.c:220] terminating driver service (forced)
I0115 09:20:37.483188 4304 driver.c:233] driver service terminated with signal 9

 - [x] Kernel version from `uname -a`

Linux byuan-desktop 5.3.0-7625-generic #27~1576337086~18.04~787b29e-Ubuntu SMP Sat Dec 14 18:28:42 UTC  x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`

==============NVSMI LOG==============

Timestamp : Wed Jan 15 17:21:42 2020
Driver Version : 440.44
CUDA Version : 10.2

Attached GPUs : 1
GPU 00000000:04:00.0
Product Name : GeForce GTX 1060 6GB
Product Brand : GeForce
Display Mode : Enabled
Display Active : Enabled
Persistence Mode : Disabled
Accounting Mode : Disabled
Accounting Mode Buffer Size : 4000
Driver Model
Current : N/A
Pending : N/A
Serial Number : N/A
GPU UUID : GPU-ce0f01b1-4ce8-cedf-87bd-a1dd645be8d7
Minor Number : 0
VBIOS Version : 86.06.27.00.9B
MultiGPU Board : No
Board ID : 0x400
GPU Part Number : N/A
Inforom Version
Image Version : G001.0000.01.03
OEM Object : 1.1
ECC Object : N/A
Power Management Object : N/A
GPU Operation Mode
Current : N/A
Pending : N/A
GPU Virtualization Mode
Virtualization Mode : None
Host VGPU Mode : N/A
IBMNPU
Relaxed Ordering Mode : N/A
PCI
Bus : 0x04
Device : 0x00
Domain : 0x0000
Device Id : 0x1C0310DE
Bus Id : 00000000:04:00.0
Sub System Id : 0x85B61043
GPU Link Info
PCIe Generation
Max : 3
Current : 1
Link Width
Max : 16x
Current : 16x
Bridge Chip
Type : N/A
Firmware : N/A
Replays Since Reset : 0
Replay Number Rollovers : 0
Tx Throughput : 1000 KB/s
Rx Throughput : 1000 KB/s
Fan Speed : 0 %
Performance State : P8
Clocks Throttle Reasons
Idle : Active
Applications Clocks Setting : Not Active
SW Power Cap : Not Active
HW Slowdown : Not Active
HW Thermal Slowdown : Not Active
HW Power Brake Slowdown : Not Active
Sync Boost : Not Active
SW Thermal Slowdown : Not Active
Display Clock Setting : Not Active
FB Memory Usage
Total : 6070 MiB
Used : 583 MiB
Free : 5487 MiB
BAR1 Memory Usage
Total : 256 MiB
Used : 14 MiB
Free : 242 MiB
Compute Mode : Default
Utilization
Gpu : 3 %
Memory : 4 %
Encoder : 0 %
Decoder : 0 %
Encoder Stats
Active Sessions : 0
Average FPS : 0
Average Latency : 0
FBC Stats
Active Sessions : 0
Average FPS : 0
Average Latency : 0
Ecc Mode
Current : N/A
Pending : N/A
ECC Errors
Volatile
Single Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Double Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Aggregate
Single Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Double Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Retired Pages
Single Bit ECC : N/A
Double Bit ECC : N/A
Pending Page Blacklist : N/A
Temperature
GPU Current Temp : 32 C
GPU Shutdown Temp : 102 C
GPU Slowdown Temp : 99 C
GPU Max Operating Temp : N/A
Memory Current Temp : N/A
Memory Max Operating Temp : N/A
Power Readings
Power Management : Supported
Power Draw : 9.43 W
Power Limit : 120.00 W
Default Power Limit : 120.00 W
Enforced Power Limit : 120.00 W
Min Power Limit : 60.00 W
Max Power Limit : 140.00 W
Clocks
Graphics : 139 MHz
SM : 139 MHz
Memory : 405 MHz
Video : 544 MHz
Applications Clocks
Graphics : N/A
Memory : N/A
Default Applications Clocks
Graphics : N/A
Memory : N/A
Max Clocks
Graphics : 1974 MHz
SM : 1974 MHz
Memory : 4004 MHz
Video : 1708 MHz
Max Customer Boost Clocks
Graphics : N/A
Clock Policy
Auto Boost : N/A
Auto Boost Default : N/A
Processes
Process ID : 1573
Type : G
Name : /usr/bin/gnome-shell
Used GPU Memory : 95 MiB
Process ID : 3412
Type : G
Name : /usr/lib/xorg/Xorg
Used GPU Memory : 158 MiB
Process ID : 3656
Type : G
Name : /usr/bin/gnome-shellnvidia-smi -a

==============NVSMI LOG==============

Timestamp : Wed Jan 15 17:21:42 2020
Driver Version : 440.44
CUDA Version : 10.2

Attached GPUs : 1
GPU 00000000:04:00.0
Product Name : GeForce GTX 1060 6GB
Product Brand : GeForce
Display Mode : Enabled
Display Active : Enabled
Persistence Mode : Disabled
Accounting Mode : Disabled
Accounting Mode Buffer Size : 4000
Driver Model
Current : N/A
Pending : N/A
Serial Number : N/A
GPU UUID : GPU-ce0f01b1-4ce8-cedf-87bd-a1dd645be8d7
Minor Number : 0
VBIOS Version : 86.06.27.00.9B
MultiGPU Board : No
Board ID : 0x400
GPU Part Number : N/A
Inforom Version
Image Version : G001.0000.01.03
OEM Object : 1.1
ECC Object : N/A
Power Management Object : N/A
GPU Operation Mode
Current : N/A
Pending : N/A
GPU Virtualization Mode
Virtualization Mode : None
Host VGPU Mode : N/A
IBMNPU
Relaxed Ordering Mode : N/A
PCI
Bus : 0x04
Device : 0x00
Domain : 0x0000
Device Id : 0x1C0310DE
Bus Id : 00000000:04:00.0
Sub System Id : 0x85B61043
GPU Link Info
PCIe Generation
Max : 3
Current : 1
Link Width
Max : 16x
Current : 16x
Bridge Chip
Type : N/A
Firmware : N/A
Replays Since Reset : 0
Replay Number Rollovers : 0
Tx Throughput : 1000 KB/s
Rx Throughput : 1000 KB/s
Fan Speed : 0 %
Performance State : P8
Clocks Throttle Reasons
Idle : Active
Applications Clocks Setting : Not Active
SW Power Cap : Not Active
HW Slowdown : Not Active
HW Thermal Slowdown : Not Active
HW Power Brake Slowdown : Not Active
Sync Boost : Not Active
SW Thermal Slowdown : Not Active
Display Clock Setting : Not Active
FB Memory Usage
Total : 6070 MiB
Used : 583 MiB
Free : 5487 MiB
BAR1 Memory Usage
Total : 256 MiB
Used : 14 MiB
Free : 242 MiB
Compute Mode : Default
Utilization
Gpu : 3 %
Memory : 4 %
Encoder : 0 %
Decoder : 0 %
Encoder Stats
Active Sessions : 0
Average FPS : 0
Average Latency : 0
FBC Stats
Active Sessions : 0
Average FPS : 0
Average Latency : 0
Ecc Mode
Current : N/A
Pending : N/A
ECC Errors
Volatile
Single Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Double Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Aggregate
Single Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Double Bit
Device Memory : N/A
Register File : N/A
L1 Cache : N/A
L2 Cache : N/A
Texture Memory : N/A
Texture Shared : N/A
CBU : N/A
Total : N/A
Retired Pages
Single Bit ECC : N/A
Double Bit ECC : N/A
Pending Page Blacklist : N/A
Temperature
GPU Current Temp : 32 C
GPU Shutdown Temp : 102 C
GPU Slowdown Temp : 99 C
GPU Max Operating Temp : N/A
Memory Current Temp : N/A
Memory Max Operating Temp : N/A
Power Readings
Power Management : Supported
Power Draw : 9.43 W
Power Limit : 120.00 W
Default Power Limit : 120.00 W
Enforced Power Limit : 120.00 W
Min Power Limit : 60.00 W
Max Power Limit : 140.00 W
Clocks
Graphics : 139 MHz
SM : 139 MHz
Memory : 405 MHz
Video : 544 MHz
Applications Clocks
Graphics : N/A
Memory : N/A
Default Applications Clocks
Graphics : N/A
Memory : N/A
Max Clocks
Graphics : 1974 MHz
SM : 1974 MHz
Memory : 4004 MHz
Video : 1708 MHz
Max Customer Boost Clocks
Graphics : N/A
Clock Policy
Auto Boost : N/A
Auto Boost Default : N/A
Processes
Process ID : 1573
Type : G
Name : /usr/bin/gnome-shell
Used GPU Memory : 95 MiB
Process ID : 3412
Type : G
Name : /usr/lib/xorg/Xorg
Used GPU Memory : 158 MiB
Process ID : 3656
Type : G
Name : /usr/bin/gnome-shell
Used GPU Memory : 152 MiB
Process ID : 9323
Type : G
Name : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=6741434274533593519,9565514079066516768,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=16605780180680635404
Used GPU Memory : 165 MiB

        Used GPU Memory         : 152 MiB
    Process ID                  : 9323
        Type                    : G
        Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=6741434274533593519,9565514079066516768,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=16605780180680635404
        Used GPU Memory         : 165 MiB

 - [x] Docker version from `docker version`

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-================================================
un  libgldispatch0-nvidia <none>          <none>          (no description available)
ii  libnvidia-cfg1-435:am 440.44-1pop1~15 amd64           Transitional package for libnvidia-cfg1-440
ii  libnvidia-cfg1-440:am 440.44-1pop1~15 amd64           NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any    <none>          <none>          (no description available)
un  libnvidia-common      <none>          <none>          (no description available)
ii  libnvidia-common-435  440.44-1pop1~15 all             Transitional package for libnvidia-common-440
ii  libnvidia-common-440  440.44-1pop1~15 all             Shared files used by the NVIDIA libraries
rc  libnvidia-compute-430 435.21-1pop1~15 amd64           Transitional package for libnvidia-compute-435
ii  libnvidia-compute-435 440.44-1pop1~15 amd64           Transitional package for libnvidia-compute-440
ii  libnvidia-compute-435 440.44-1pop1~15 i386            Transitional package for libnvidia-compute-440
ii  libnvidia-compute-440 440.44-1pop1~15 amd64           NVIDIA libcompute package
ii  libnvidia-compute-440 440.44-1pop1~15 i386            NVIDIA libcompute package
ii  libnvidia-container-t 1.0.6-1pop1~157 amd64           NVIDIA container runtime library (command-line t
ii  libnvidia-container1: 1.0.6-1pop1~157 amd64           NVIDIA container runtime library
un  libnvidia-decode      <none>          <none>          (no description available)
ii  libnvidia-decode-435: 440.44-1pop1~15 amd64           Transitional package for libnvidia-decode-440
ii  libnvidia-decode-435: 440.44-1pop1~15 i386            Transitional package for libnvidia-decode-440
ii  libnvidia-decode-440: 440.44-1pop1~15 amd64           NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-440: 440.44-1pop1~15 i386            NVIDIA Video Decoding runtime libraries
un  libnvidia-encode      <none>          <none>          (no description available)
ii  libnvidia-encode-435: 440.44-1pop1~15 amd64           Transitional package for libnvidia-encode-440
ii  libnvidia-encode-435: 440.44-1pop1~15 i386            Transitional package for libnvidia-encode-440
ii  libnvidia-encode-440: 440.44-1pop1~15 amd64           NVENC Video Encoding runtime library
ii  libnvidia-encode-440: 440.44-1pop1~15 i386            NVENC Video Encoding runtime library
un  libnvidia-fbc1        <none>          <none>          (no description available)
ii  libnvidia-fbc1-435:am 440.44-1pop1~15 amd64           Transitional package for libnvidia-fbc1-440
ii  libnvidia-fbc1-435:i3 440.44-1pop1~15 i386            Transitional package for libnvidia-fbc1-440
ii  libnvidia-fbc1-440:am 440.44-1pop1~15 amd64           NVIDIA OpenGL-based Framebuffer Capture runtime 
ii  libnvidia-fbc1-440:i3 440.44-1pop1~15 i386            NVIDIA OpenGL-based Framebuffer Capture runtime 
un  libnvidia-gl          <none>          <none>          (no description available)
ii  libnvidia-gl-435:amd6 440.44-1pop1~15 amd64           Transitional package for libnvidia-gl-440
ii  libnvidia-gl-435:i386 440.44-1pop1~15 i386            Transitional package for libnvidia-gl-440
ii  libnvidia-gl-440:amd6 440.44-1pop1~15 amd64           NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and V
ii  libnvidia-gl-440:i386 440.44-1pop1~15 i386            NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and V
un  libnvidia-ifr1        <none>          <none>          (no description available)
ii  libnvidia-ifr1-435:am 440.44-1pop1~15 amd64           Transitional package for libnvidia-ifr1-440
ii  libnvidia-ifr1-435:i3 440.44-1pop1~15 i386            Transitional package for libnvidia-ifr1-440
ii  libnvidia-ifr1-440:am 440.44-1pop1~15 amd64           NVIDIA OpenGL-based Inband Frame Readback runtim
ii  libnvidia-ifr1-440:i3 440.44-1pop1~15 i386            NVIDIA OpenGL-based Inband Frame Readback runtim
un  libnvidia-ml1         <none>          <none>          (no description available)
un  nvidia-304            <none>          <none>          (no description available)
un  nvidia-340            <none>          <none>          (no description available)
un  nvidia-384            <none>          <none>          (no description available)
un  nvidia-390            <none>          <none>          (no description available)
un  nvidia-common         <none>          <none>          (no description available)
ii  nvidia-compute-utils- 440.44-1pop1~15 amd64           Transitional package for nvidia-compute-utils-44
ii  nvidia-compute-utils- 440.44-1pop1~15 amd64           NVIDIA compute utilities
ii  nvidia-container-runt 3.1.4-1         amd64           NVIDIA container runtime
un  nvidia-container-runt <none>          <none>          (no description available)
ii  nvidia-container-tool 1.0.5-1         amd64           NVIDIA container runtime hook
ii  nvidia-dkms-435       440.44-1pop1~15 amd64           Transitional package for nvidia-dkms-440
ii  nvidia-dkms-440       440.44-1pop1~15 amd64           NVIDIA DKMS package
un  nvidia-dkms-kernel    <none>          <none>          (no description available)
ii  nvidia-driver-390     418.56-0ubuntu1 amd64           Transitional package for nvidia-driver-418
ii  nvidia-driver-418     440.44-1pop1~15 amd64           Transitional package for nvidia-driver-440
ii  nvidia-driver-430     440.44-1pop1~15 amd64           Transitional package for nvidia-driver-440
ii  nvidia-driver-435     440.44-1pop1~15 amd64           Transitional package for nvidia-driver-440
ii  nvidia-driver-440     440.44-1pop1~15 amd64           NVIDIA driver metapackage
un  nvidia-driver-binary  <none>          <none>          (no description available)
un  nvidia-kernel-common  <none>          <none>          (no description available)
ii  nvidia-kernel-common- 440.44-1pop1~15 amd64           Shared files used with the kernel module
un  nvidia-kernel-source  <none>          <none>          (no description available)
ii  nvidia-kernel-source- 440.44-1pop1~15 amd64           NVIDIA kernel source package
un  nvidia-legacy-304xx-v <none>          <none>          (no description available)
un  nvidia-legacy-340xx-v <none>          <none>          (no description available)
un  nvidia-libopencl1-dev <none>          <none>          (no description available)
un  nvidia-opencl-icd     <none>          <none>          (no description available)
un  nvidia-persistenced   <none>          <none>          (no description available)
ii  nvidia-prime          0.8.8.2         all             Tools to enable NVIDIA's Prime
ii  nvidia-settings       418.56-0ubuntu0 amd64           Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binar <none>          <none>          (no description available)
un  nvidia-smi            <none>          <none>          (no description available)
un  nvidia-utils          <none>          <none>          (no description available)
ii  nvidia-utils-435:amd6 440.44-1pop1~15 amd64           Transitional package for nvidia-utils-440
ii  nvidia-utils-440      440.44-1pop1~15 amd64           NVIDIA driver support binaries
un  nvidia-vdpau-driver   <none>          <none>          (no description available)
ii  xserver-xorg-video-nv 440.44-1pop1~15 amd64           Transitional package for xserver-xorg-video-nvid
ii  xserver-xorg-video-nv 440.44-1pop1~15 amd64           NVIDIA binary Xorg driver

 - [x] NVIDIA container library version from `nvidia-container-cli -V`

version: 1.0.6
build date: 2019-10-17T03:23+00:00
build revision: 0000000000000000000000000000000000000000
build compiler: x86_64-linux-gnu-gcc-7 7.4.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -I/usr/include/tirpc -g -O2 -fdebug-prefix-map=/build/libnvidia-container-Q2bRCn/libnvidia-container-1.0.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections -Wl,-Bsymbolic-functions -Wl,-z,relro

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by RenaudWasTaken** [comment]
Hello!

Please run this command as root: `sudo nvidia-container-cli -k -d /dev/tty info`.
It will load the kernel modules and allow you to run CUDA processes
