### ISSUE TITLE
use NVLINK across containers

### ISSUE THREAD

**Issue by WencongXiao** [NVIDIA/nvidia-docker#1172]
Hi, folks

Is it possible to communicate through NVLINK among different containers? 
An example scenario described as below:
A machine has two GPUs connected with NVLINK.
I found that even when I mount both GPUs to both these two containers,  two jobs (tf1.12 with nccl) running in two containers respectively are not able to communicate through NVLINK but still through PCIe. 

I wonder whether I am in a wrong config when launching containers (like missing some parameters), or it is impossible according to the nvidia-docker container design.

Thanks!

**Comment by RenaudWasTaken** [comment]
Yes you should be able to use NVLINK, I believe you will however need to share the IPC namespace.
Feel free to reopen if this doesn't solve your isssue!
