### ISSUE TITLE
Advice monitoring inside another company's Docker Container (DataDog)

### ISSUE THREAD

**Issue by cep21** [NVIDIA/nvidia-docker#1175]
### 1. Issue or feature description
Getting libnvidia-ml.so loaded inside another company's official docker container

### 2. Steps to reproduce the issue

Try to use the nvml python library inside DataDog's docker image.  Here is one example:

```
FROM datadog/agent:7.16.1
ARG NVML_VERSION=e3d4399bdea6b48814524aa6cb7ec9d2011492f6
RUN /opt/datadog-agent/embedded/bin/pip install nvidia-ml-py3
RUN curl https://raw.githubusercontent.com/ngi644/datadog_nvml/${NVML_VERSION}/nvml.py > /checks.d/nvml.py
```

### 3. Longer examplation

Hi,

I would like to monitor my Nvidia GPU's utilization inside my k8s cluster.  [DataDog](https://www.datadoghq.com/) is a SaaS company that assists monitoring.  I am deploying DataDog's official docker image inside my cluster, but their official docker image is unable to find libnvidia-ml.so when I use nvidia-ml-py

```
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
```

When I look for other examples of people using libnvidia-ml.so inside their docker images, they are all from the nvidia-docker base images.  I need assistance or advice on how I can start from something like `FROM datadog/agent:7.16.1` and get libnvidia-ml.so correctly installed.

Thanks!

**Comment by RenaudWasTaken** [comment]
Hello!

We've started migrating our documentation, and you can find documentation on that topic here: https://nvidia.github.io/container-wiki/toolkit/container-images.html#using-non-cuda-images

You can also take a look at our Dockerfile for CUDA: https://gitlab.com/nvidia/container-images/cuda

We're also happy to accept Pull Requests on the documentation!
Hope this helps!
