### ISSUE TITLE
Should I be able to build without cuda driver

### ISSUE THREAD

**Issue by wohlbier** [NVIDIA/nvidia-docker#1177]
Trying to use `nvidia-docker` to build a container, but I do not have a nvidia gpu. I have cuda installed, but no driver. Should I be able to do this?

```
(base) [jgwohlbier@lx-peppercorn object_detection]$ sudo nvidia-docker build . -t mlperf/object_detection
/usr/bin/nvidia-docker: line 34: /usr/bin/docker: Permission denied
/usr/bin/nvidia-docker: line 34: /usr/bin/docker: Success
```
There is no `Success`, actually.

**Comment by RenaudWasTaken** [comment]
nvidia-docker doesn't work without the NVIDIA driver or an NVIDIA GPU as indicated in the prerequisite section: https://github.com/NVIDIA/nvidia-docker#quickstart
