### ISSUE TITLE
invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>

### ISSUE THREAD

**Issue by Satilicus** [NVIDIA/nvidia-docker#1178]
The issue is still hapenning (from Canada).
Same problem as #969 

I am using nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>

**Comment by jwitos** [comment]
Just got this error too, in the US.

**Comment by kennyhelsens** [comment]
+1 from Belgium 

```
...
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' is not signed.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

**Comment by CathalMullan** [comment]
Same here in the UK.

```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' is not signed.
```

**Comment by rorph** [comment]
+1 from Brazil

```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' is not signed.
```

```
curl -sL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add -
```

Doesn't work

```
apt-get -o APT::Get::AllowUnauthenticated=true -o Acquire::AllowInsecureRepositories=true
```
Doesn't work

;(

**Comment by prashantsathe** [comment]
+1 from canada

**Comment by Alex-Linhares** [comment]
+1 from Brazil, and also from a US Denver-based VPN.

**Comment by Alex-Linhares** [comment]
Just in case it's of help to someone else, I could avoid this error and install CUDA+the NVIDIA driver on Mint19.3.  Here's what I did:

clean install of mint (let nouveau drivers be installed, do not upgrade to NVIDIA).  Follow the deb-local installation method (under a VPN @ California):

    https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal 

goto 1. and repeat the process around 50 times.  

Voilá!  NVIDIA drivers and CUDA running on your system!  Wasn't that easy?

**Comment by CathalMullan** [comment]
Seems like the issue might be fixed now.
I'm currently able to pull from the repo consistently.

**Comment by matthaeusheer** [comment]
Still facing the same issue when running ```sudo apt update```:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Release.gpg  The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by marskong88** [comment]
house or home is a private and personal place.if you all can doing like easy come easy go den same the way to you and all you family too.what you doing for den what will begin to you and all your family too.

**Comment by praveenbadimala** [comment]
+1 from India

**Comment by vitahlin** [comment]
Same issue in China

**Comment by klueska** [comment]
This is not an issue for `nvidia-docker` itself.

All issues related to images running on top of `nvidia-docker` should be directed here:
https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/25

**Comment by RiaanLab** [comment]
+1 South Africa.
