### ISSUE TITLE
nvidia-docker: plugin not found

### ISSUE THREAD

**Issue by lforehan** [NVIDIA/nvidia-docker#118]
I am using an Amazon Linux AMI with latest nvidia driver installed.  I run this command to start nvidia-docker-plugin:
```
sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log
```

Strangely, nothing shows up in the /tmp/nvidia-docker.log file.  Then I run a simple command with nvidia-docker:
```
nvidia-docker run -it nvidia/cuda bash
docker: Error response from daemon: create nvidia_driver_367.27: create nvidia_driver_367.27: Error looking up volume plugin nvidia-docker: plugin not found.
```

Normal docker command works
```
docker run -it nvidia/cuda bash
root@addc86a1ca92:/# 
```

This error occurs about 1/3 of the time when I launch new instances.  Any ideas what is the problem?  Is there a plan to write a real service script for non-ubuntu/centos systems?

**Comment by lforehan** [comment]
I was not able to reproduce

**Comment by flx42** [comment]
Great, let us know if you have any problem.
