### ISSUE TITLE
no valid openPGP data found

### ISSUE THREAD

**Issue by Gahui** [NVIDIA/nvidia-docker#1183]
Hi.
I was trying to install nvidia-docker2 under ubuntu 16.04.
I followed the install guide of Ubuntu 16.04/18.04, Debian Jessie/Stretch/Buster

# Add the package repositories
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
after entering curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
I got the error "gpg: no valid OpenPGP data found." 

Any advices and help are welcome :)

**Comment by Gahui** [comment]
This is a problem of firewall in network :) Thank you

**Comment by lakshminarayanareddybn** [comment]
unset http_proxy
unset https_proxy
if working behind firewall
