### ISSUE TITLE
rhel7.7 unsupported ?

### ISSUE THREAD

**Issue by j1mmc1v3r** [NVIDIA/nvidia-docker#1187]
### 2.  Follow steps in the web page for RH distributions:
            $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
            $ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo

### 3. This was working fine for me yesterday (6th Feb 2020), so not sure what's happened since then.  

Would appreciate your (urgent) assistance to correct this.

Thanks,

Jim McIver

**Comment by RenaudWasTaken** [comment]
Hello!

I'm not able to reproduce, this could have been an issue with the github CDN or your particular corporate network.
Feel free to reopen if that issue persists.
