### ISSUE TITLE
Missing part of documentation - how to add CUDA support to existing image/container

### ISSUE THREAD

**Issue by VorontsovIE** [NVIDIA/nvidia-docker#1188]
Hello,
I was trying to slightly non-standard workflow and instead of use of `nvidia/cuda:base` base image for my image, I tried to add support of CUDA into existing container with a different base image (also ubuntu-based though).
For that purpose I've manually applied all instructions from `nvidia/cuda:base` Dockerfile inside of existing container bash session and it failed. It took me a very long time to catch that it's not enough to invoke `export CUDA_VERSION=...` from running container but that this environment variable should be set **before** container started (using either `ENV` directive in an image or command-line switch for `docker start --env ...` syntax for existing image).
I'm not an experienced user of docker or CUDA but I suppose, it's because of nvidia-container-runtime pre-start hooks, am I right? Should I add any other env-variables before container start?

I think it'd be beneficial to other users to add a section to Readme/wiki which describes
* a recommended way to patch an existing image (or container) so that it supports CUDA
* pitfalls which may happen on the way. I found one, but not sure, is it the only pitfall

**Comment by RenaudWasTaken** [comment]
Hello!

We've started migrating our documentation, and you can find documentation on that topic here: https://nvidia.github.io/container-wiki/toolkit/container-images.html#using-non-cuda-images

You can also take a look at our Dockerfile for CUDA: https://gitlab.com/nvidia/container-images/cuda

We're also happy to accept Pull Requests on the documentation!
Hope this helps!
