### ISSUE TITLE
Error while using nvidia-docker

### ISSUE THREAD

**Issue by venkatsatish** [NVIDIA/nvidia-docker#119]
Error while using the nvidia-docker in the presence of weave. nvidia-docker shows me the following error . if we run the docker without nvidia-docker it works fine.

nvidia-docker | 2016/06/21 17:16:50 Error: invalid remote host URI

**Comment by 3XX0** [comment]
Interesting, can you output the environment variable `DOCKER_HOST`?

**Comment by venkatsatish** [comment]
DOCKER_HOST variable is not set , but i am still able to use nvidia-drivers inside docker using REST API of nvidia-docker plugin

**Comment by 3XX0** [comment]
`DOCKER_HOST` or `NV_HOST` is set somehow in your environment (maybe Weave does it) otherwise the error wouldn't occur.

**Comment by venkatsatish** [comment]
weave sets DOCKER_HOST variable
echo $(weave env) 
export DOCKER_HOST=unix:///var/run/weave/weave.sock ORIG_DOCKER_HOST=

**Comment by 3XX0** [comment]
Ok yes that's an issue in the parsing of `DOCKER_HOST`. I think you can workaround it for now by setting `NV_HOST`:

`export NV_HOST=localhost:`

**Comment by flx42** [comment]
Ping @venkatsatish

**Comment by flx42** [comment]
It should be supported with the latst commit 7a61e9b, but for now you will need to generate the package yourself (`make deb` or `make rpm`) until we publish `1.0.0` (or `rc4`)
