### ISSUE TITLE
Docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error exec: "nvidia-container-runtime": executable file not found in $PATH: : unknown.

### ISSUE THREAD

**Issue by sudo-G41** [NVIDIA/nvidia-docker#1190]
1. Issue or feature description

I'm tring to install nvidia-docker, and follow the steps
at the last step:
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
sudo docker run --runtime=nvidia -v $(pwd):/workspace --rm -it nvcr.io/hpc/lammps:24Oct2018 <- error line

it will have error message:
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/830bcc6e9c64f307f5ca111b5efa08cdde3246cabf937e5740d12dc26c5e6939/log.json: no such file or directory): exec: "nvidia-container-runtime": executable file not found in $PATH: : unknown.

2. Steps to reproduce the issue

    Just the same as the readme here

3. Information to attach (optional if deemed irrelevant)

    Some nvidia-container information: nvidia-container-cli -k -d /dev/tty info
     ` 812b6-304f-572c-7dcb-a41fa085677e at 00000000:08:00.0 )
    NVRM version: 440.44
    CUDA version: 10.2

Device Index: 0
Device Minor: 0
Model: GeForce RTX 2080 SUPER
Brand: GeForce
GPU UUID: GPU-c50812b6-304f-572c-7dcb-a41fa085677e
Bus Location: 00000000:08:00.0
Architecture:   7.5
I0210 17:49:58.319930 18606 nvc.c:318] shutting down library context
I0210 17:49:58.320194 18608 driver.c:192] terminating driver service
I0210 17:49:58.321103 18606 driver.c:233] driver service terminated successfully

Kernel version from uname -a
Linux G41 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Any relevant kernel output lines from dmesg

    Driver information from nvidia-smi -a
    `Timestamp : Tue Feb 11 03:00:29 2020
    Driver Version : 440.44
    CUDA Version : 10.2

Attached GPUs : 1
GPU Tue Feb 11 03:00:29 2020
Product Name : GeForce RTX 1080 SUPER

    Docker version from docker version
    `Client:
    Version: 19.03.5-ce
    API version: 1.40
    Go version: go1.12.12
    Git commit: 633a0ea838
    Built: Wed Nov 13 07:29:52 2019
    OS/Arch: linux/amd64
    Experimental: false

Server:
Engine:
Version: 19.03.5-ce
API version: 1.40 (minimum version 1.12)
Go version: go1.12.12
Git commit: 633a0ea838
Built: Wed Nov 13 07:29:52 2019
OS/Arch: linux/amd64
Experimental: false`

NVIDIA container library version from nvidia-container-cli -V
version: 1.0.5

NVIDIA container library logs (see troubleshooting)

Docker command, image and tag used
nvcr.io/hpc/lammps:24Oct2018

**Comment by RenaudWasTaken** [comment]
Hello!

Please file the issue template correctly :)
Namely the tow important fields would here be:
 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

Thanks!

**Comment by sudo-G41** [comment]
Thank you for your reply!
I just copied the information.

G41@ps:~$ nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I0211 20:42:44.282867 8111 nvc.c:281] initializing library context (version=1.0.5, build=13b836390888f7b7c7dca115d16d7e28ab15a836)
I0211 20:42:44.282911 8111 nvc.c:255] using root /
I0211 20:42:44.282924 8111 nvc.c:256] using ldcache /etc/ld.so.cache
I0211 20:42:44.282933 8111 nvc.c:257] using unprivileged user 1002:1002
W0211 20:42:44.284260 8112 nvc.c:186] failed to set inheritable capabilities
W0211 20:42:44.284305 8112 nvc.c:187] skipping kernel modules load due to failure
I0211 20:42:44.284497 8113 driver.c:133] starting driver service
I0211 20:42:44.305225 8111 nvc_info.c:437] requesting driver information with ''
I0211 20:42:44.305657 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvoptix.so.440.44
I0211 20:42:44.305779 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.440.44
I0211 20:42:44.305976 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.440.44
I0211 20:42:44.306175 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.440.44
I0211 20:42:44.306365 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.440.44
I0211 20:42:44.306574 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.440.44
I0211 20:42:44.306613 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.440.44
I0211 20:42:44.306825 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.440.44
I0211 20:42:44.307037 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.440.44
I0211 20:42:44.307222 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.440.44
I0211 20:42:44.307411 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.44
I0211 20:42:44.307607 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.440.44
I0211 20:42:44.307801 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.440.44
I0211 20:42:44.307976 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.440.44
I0211 20:42:44.308191 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.440.44
I0211 20:42:44.308374 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.440.44
I0211 20:42:44.308565 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.440.44
I0211 20:42:44.308778 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.440.44
I0211 20:42:44.309037 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.440.44
I0211 20:42:44.309349 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.440.44
I0211 20:42:44.309534 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.440.44
I0211 20:42:44.309702 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.440.44
I0211 20:42:44.309895 8111 nvc_info.c:151] selecting /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.440.44
I0211 20:42:44.310180 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-tls.so.440.44
I0211 20:42:44.310382 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-ptxjitcompiler.so.440.44
I0211 20:42:44.310630 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-opticalflow.so.440.44
I0211 20:42:44.310839 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-opencl.so.440.44
I0211 20:42:44.311044 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-ml.so.440.44
I0211 20:42:44.311260 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-ifr.so.440.44
I0211 20:42:44.311469 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-glvkspirv.so.440.44
I0211 20:42:44.311652 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-glsi.so.440.44
I0211 20:42:44.311843 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-glcore.so.440.44
I0211 20:42:44.312034 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-fbc.so.440.44
I0211 20:42:44.312221 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-fatbinaryloader.so.440.44
I0211 20:42:44.312391 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-encode.so.440.44
I0211 20:42:44.312595 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-eglcore.so.440.44
I0211 20:42:44.312776 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvidia-compiler.so.440.44
I0211 20:42:44.312974 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libnvcuvid.so.440.44
I0211 20:42:44.313194 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libcuda.so.440.44
I0211 20:42:44.313412 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libGLX_nvidia.so.440.44
I0211 20:42:44.313581 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libGLESv2_nvidia.so.440.44
I0211 20:42:44.313726 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libGLESv1_CM_nvidia.so.440.44
I0211 20:42:44.313922 8111 nvc_info.c:151] selecting /usr/lib/i386-linux-gnu/libEGL_nvidia.so.440.44
W0211 20:42:44.313946 8111 nvc_info.c:302] missing library libvdpau_nvidia.so
W0211 20:42:44.313955 8111 nvc_info.c:306] missing compat32 library libnvidia-cfg.so
W0211 20:42:44.313963 8111 nvc_info.c:306] missing compat32 library libvdpau_nvidia.so
W0211 20:42:44.313974 8111 nvc_info.c:306] missing compat32 library libnvidia-rtcore.so
W0211 20:42:44.313983 8111 nvc_info.c:306] missing compat32 library libnvoptix.so
I0211 20:42:44.314191 8111 nvc_info.c:232] selecting /usr/bin/nvidia-smi
I0211 20:42:44.314217 8111 nvc_info.c:232] selecting /usr/bin/nvidia-debugdump
I0211 20:42:44.314233 8111 nvc_info.c:232] selecting /usr/bin/nvidia-persistenced
I0211 20:42:44.314251 8111 nvc_info.c:232] selecting /usr/bin/nvidia-cuda-mps-control
I0211 20:42:44.314271 8111 nvc_info.c:232] selecting /usr/bin/nvidia-cuda-mps-server
I0211 20:42:44.314292 8111 nvc_info.c:369] listing device /dev/nvidiactl
I0211 20:42:44.314296 8111 nvc_info.c:369] listing device /dev/nvidia-uvm
I0211 20:42:44.314304 8111 nvc_info.c:369] listing device /dev/nvidia-uvm-tools
I0211 20:42:44.314313 8111 nvc_info.c:369] listing device /dev/nvidia-modeset
I0211 20:42:44.314342 8111 nvc_info.c:273] listing ipc /run/nvidia-persistenced/socket
W0211 20:42:44.314360 8111 nvc_info.c:277] missing ipc /tmp/nvidia-mps
I0211 20:42:44.314366 8111 nvc_info.c:493] requesting device information with ''
I0211 20:42:44.320234 8111 nvc_info.c:523] listing device /dev/nvidia0 (GPU-c50812b6-304f-572c-7dcb-a41fa085677e at 00000000:08:00.0)
NVRM version:   440.44
CUDA version:   10.2

Device Index:   0
Device Minor:   0
Model:          GeForce RTX 2080 SUPER
Brand:          GeForce
GPU UUID:       GPU-c50812b6-304f-572c-7dcb-a41fa085677e
Bus Location:   00000000:08:00.0
Architecture:   7.5
I0211 20:42:44.320271 8111 nvc.c:318] shutting down library context
I0211 20:42:44.320706 8113 driver.c:192] terminating driver service
I0211 20:42:44.321965 8111 driver.c:233] driver service terminated successfully

G41@ps:~$ dpkg -l '*nvidia*'
un  libgldispatch0-nvidia                         <none>                      <none>                      (설명 없음)
ii  libnvidia-cfg1-440:amd64                      440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any                            <none>                      <none>                      (설명 없음)
un  libnvidia-common                              <none>                      <none>                      (설명 없음)
ii  libnvidia-common-440                          440.44-0ubuntu0~0.18.04.1   all                         Shared files used by the NVIDIA libraries
ii  libnvidia-compute-440:amd64                   440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA libcompute package
ii  libnvidia-compute-440:i386                    440.44-0ubuntu0~0.18.04.1   i386                        NVIDIA libcompute package
ii  libnvidia-container-tools                     1.0.5-1                     amd64                       NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                    1.0.5-1                     amd64                       NVIDIA container runtime library
un  libnvidia-decode                              <none>                      <none>                      (설명 없음)
ii  libnvidia-decode-440:amd64                    440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-440:i386                     440.44-0ubuntu0~0.18.04.1   i386                        NVIDIA Video Decoding runtime libraries
un  libnvidia-encode                              <none>                      <none>                      (설명 없음)
ii  libnvidia-encode-440:amd64                    440.44-0ubuntu0~0.18.04.1   amd64                       NVENC Video Encoding runtime library
ii  libnvidia-encode-440:i386                     440.44-0ubuntu0~0.18.04.1   i386                        NVENC Video Encoding runtime library
un  libnvidia-fbc1                                <none>                      <none>                      (설명 없음)
ii  libnvidia-fbc1-440:amd64                      440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-440:i386                       440.44-0ubuntu0~0.18.04.1   i386                        NVIDIA OpenGL-based Framebuffer Capture runtime library
un  libnvidia-gl                                  <none>                      <none>                      (설명 없음)
ii  libnvidia-gl-440:amd64                        440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-440:i386                         440.44-0ubuntu0~0.18.04.1   i386                        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
un  libnvidia-ifr1                                <none>                      <none>                      (설명 없음)
ii  libnvidia-ifr1-440:amd64                      440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ifr1-440:i386                       440.44-0ubuntu0~0.18.04.1   i386                        NVIDIA OpenGL-based Inband Frame Readback runtime library
un  libnvidia-ml1                                 <none>                      <none>                      (설명 없음)
un  nvidia-304                                    <none>                      <none>                      (설명 없음)
un  nvidia-340                                    <none>                      <none>                      (설명 없음)
un  nvidia-384                                    <none>                      <none>                      (설명 없음)
un  nvidia-390                                    <none>                      <none>                      (설명 없음)
un  nvidia-common                                 <none>                      <none>                      (설명 없음)
ii  nvidia-compute-utils-440                      440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA compute utilities
ii  nvidia-container-runtime                      3.1.4-1                     amd64                       NVIDIA container runtime
un  nvidia-container-runtime-hook                 <none>                      <none>                      (설명 없음)
ii  nvidia-container-toolkit                      1.0.5-1                     amd64                       NVIDIA container runtime hook
ii  nvidia-cuda-dev                               9.1.85-3ubuntu1             amd64                       NVIDIA CUDA development files
ii  nvidia-cuda-doc                               9.1.85-3ubuntu1             all                         NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                               9.1.85-3ubuntu1             amd64                       NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                           9.1.85-3ubuntu1             amd64                       NVIDIA CUDA development toolkit
ii  nvidia-dkms-440                               440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA DKMS package
un  nvidia-dkms-kernel                            <none>                      <none>                      (설명 없음)
rc  nvidia-docker                                 1.0.0-1                     amd64                       NVIDIA Docker container tools
ii  nvidia-docker2                                2.2.2-1                     all                         nvidia-docker CLI wrapper
un  nvidia-driver                                 <none>                      <none>                      (설명 없음)
ii  nvidia-driver-440                             440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA driver metapackage
un  nvidia-driver-binary                          <none>                      <none>                      (설명 없음)
un  nvidia-kernel-common                          <none>                      <none>                      (설명 없음)
ii  nvidia-kernel-common-440                      440.44-0ubuntu0~0.18.04.1   amd64                       Shared files used with the kernel module
un  nvidia-kernel-source                          <none>                      <none>                      (설명 없음)
ii  nvidia-kernel-source-440                      440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA kernel source package
un  nvidia-legacy-304xx-vdpau-driver              <none>                      <none>                      (설명 없음)
un  nvidia-legacy-340xx-vdpau-driver              <none>                      <none>                      (설명 없음)
un  nvidia-libopencl1                             <none>                      <none>                      (설명 없음)
un  nvidia-libopencl1-dev                         <none>                      <none>                      (설명 없음)
ii  nvidia-opencl-dev:amd64                       9.1.85-3ubuntu1             amd64                       NVIDIA OpenCL development files
un  nvidia-opencl-icd                             <none>                      <none>                      (설명 없음)
un  nvidia-persistenced                           <none>                      <none>                      (설명 없음)
ii  nvidia-prime                                  0.8.8.2                     all                         Tools to enable NVIDIA's Prime
ii  nvidia-profiler                               9.1.85-3ubuntu1             amd64                       NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                               418.56-0ubuntu0~gpu18.04.1  amd64                       Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                        <none>                      <none>                      (설명 없음)
un  nvidia-smi                                    <none>                      <none>                      (설명 없음)
un  nvidia-utils                                  <none>                      <none>                      (설명 없음)
ii  nvidia-utils-440                              440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA driver support binaries
un  nvidia-vdpau-driver                           <none>                      <none>                      (설명 없음)
ii  nvidia-visual-profiler                        9.1.85-3ubuntu1             amd64                       NVIDIA Visual Profiler for CUDA and OpenCL
ii  xserver-xorg-video-nvidia-440                 440.44-0ubuntu0~0.18.04.1   amd64                       NVIDIA binary Xorg driver

**Comment by guptaNswati** [comment]
Your packages looks okay. What steps did you follow to install the nvidia-docker? Also what do you see when you do` $ docker run --rm --gpus all nvidia/cuda nvidia-smi`

**Comment by RenaudWasTaken** [comment]
Can you also do something along the lines of `which nvidia-container-runtime` ?
I suspect your Docker daemon's path is not correctly set :)

**Comment by sudo-G41** [comment]
Installation looked here.(https://hiseon.me/linux/ubuntu/install-docker/)

The result of  `$ docker run --rm --gpus all nvidia/cuda nvidia-smi` is this

G41@ps:~$ docker run --rm --gpus all nvidia/cuda nvidia-smi
Thu Feb 13 04:52:11 2020      
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:08:00.0 Off |                  N/A |
| 33%   31C    P8     6W / 250W |   2984MiB /  7974MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                              
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by guptaNswati** [comment]
Okay so your installation is correct but you were not using the right command. With docker 19.03, the right command is `docker run —gpus all`. This should resolve your issue. Closing for now.

**Comment by ksemaev** [comment]
@guptaNswati the --gpus is a correct option for docker 19.03
```
docker -v
Docker version 19.03.6-ce, build 369ce74
```

```
docker run --help | grep gpu
      --gpus gpu-request               GPU devices to add to the container ('all' to pass all GPUs)
```
