### ISSUE TITLE
Docs misleading for RHEL 8

### ISSUE THREAD

**Issue by olivier-dj** [NVIDIA/nvidia-docker#1192]
Docs misleading for RHEL/CentOS 8:
https://github.com/NVIDIA/nvidia-docker#rhel-docker

Please exchange:
`sudo systemctl restart docker`
`docker run -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:9.0-base nvidia-smi`
by
`podman run -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:9.0-base nvidia-smi`

The fork of RHEL is podman. The docs make the reader think that somehow the `--gpus` option is not supported when using docker instead of podman on RHEL8 (no mentions to podman, making the docker service restart), even though it's totally wrong and even more annoying the old interface with environment variables doesn't work at all with docker. I thought for a time that docker will simply not work for nvidia devices on RHEL8.

I assumed you meant that the `--gpus` doesn't work with podman, which is something I can confirm (and `-e NVIDIA_VISIBLE_DEVICES=all` works).

This work totally fine (on centos 8 at least) with docker-ce 19.03:
`docker run --gpus all,capabilities=utility nvidia/cuda:9.0-base nvidia-smi`
While
`docker run -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:9.0-base nvidia-smi`
will badly fail.

**Comment by RenaudWasTaken** [comment]
Hello there!

On RHEL7, the fork of RHEL isn't podman which is why this requires us to restart the docker service :)
I'll add a line for RHEL8 to point to podman. 

Feel free to make a pull request to update the documentation if you encounter any other issues!

**Comment by RenaudWasTaken** [comment]
Closed in https://github.com/NVIDIA/nvidia-docker/commit/bf3d3d1aed91ab0efa91148d78238e52b4dcffed
