### ISSUE TITLE
"distribution" variable during instalation on Linux Mint

### ISSUE THREAD

**Issue by mombip** [NVIDIA/nvidia-docker#1194]
For Linux Mint
command: `distribution=$(. /etc/os-release;echo $ID$VERSION_ID)`
gives: `linuxmint19.1`

For Linux Mint with Bash (4.x+) it should be:
`distribution=$(. /etc/upstream-release/lsb-release;echo ${DISTRIB_ID,,}$DISTRIB_RELEASE)`
For Linux Mint with Zsh it should be:
`distribution=$(. /etc/upstream-release/lsb-release;echo ${DISTRIB_ID:l}$DISTRIB_RELEASE);`

**Comment by RenaudWasTaken** [comment]
Hello!

We don't really support Linux Mint, so I'm not sure this fits in the README.
We have a good issue that shows how to install nvidia-docker with linux mint though: https://github.com/NVIDIA/nvidia-docker/issues/848
