### ISSUE TITLE
Support for Docker Compose / Docker Swarm

### ISSUE THREAD

**Issue by sebastianfelipe** [NVIDIA/nvidia-docker#1196]
### Feature description
Hi, is there a support for a docker swarm deployment? I have read about it and haven't found a way to do it. Is it implemented?

Thanks!

**Comment by RenaudWasTaken** [comment]
Hello!

This is probably the place this should be discussed: https://github.com/docker/compose/issues/6691

**Comment by sebastianfelipe** [comment]
I know, I commented it few days ago. I just had the hope it aldeary have been released u.u
