### ISSUE TITLE
nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 is missing development toolchain components 

### ISSUE THREAD

**Issue by pliablepixels** [NVIDIA/nvidia-docker#1197]
### Issue or feature description

I have a container that is derived `FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04`. Based on the description of this container, it should include all the development toolchain for CUDA+CUDNN. However, trying to compile OpenCV 4.2.1 inside the docker image results in it neither finding CUDA not CUDNN libraries, even if I specify the architecture, toolkit dir etc.

Note that I have OpenCV 4.2.1 working perfectly well on the host system with the GPU, so I know it is not an OpenCV issue.

### More details

* I run the docker image using `--gpus all` in the docker run command. I an running docker version `19.03.6` on Ubuntu 18.04.

* This correctly exposes my GPU card in the docker container:
```
root@1525535c7a9b:/config/foo/opencv/build# nvidia-smi
Wed Feb 19 10:12:39 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:02:00.0 Off |                  N/A |
| 34%   34C    P0    N/A /  75W |      0MiB /  4039MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

* Note however, that when I do an `ls` on what is installed:
```
root@1525535c7a9b:/config/foo/opencv/build# ls /usr/local/cuda
LICENSE  README  compat  doc  include  lib64  nvml  targets  version.txt
```
The `bin/` directory is missing, which include mvcc and others. If this is a devel environment, should this not be bundled? If not, what do I need to install?

* I then looked at #806 where @flx42 suggested we look at [this](https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.caffe_server#L26-L41) Dockerfiles to see how to get OpenCV 3.1 working. However, this does not work and CUDA/CUDNN libraries are not found in the build process. The differences are, that example uses OpenCV 3.1 and `FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` while I am using OpenCV 4.2 and  `FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04`

### Hack

* To fix this, I then had to do `apt-get install cuda` in my docker, which did _not_ install cleanly (see [output](https://gist.github.com/pliablepixels/adb3928b97a37a260594c31149d288d1#file-gistfile1-txt)), but did install whatever missing files were needed, because after that I checked `/usr/local/cuda` now had a `bin/` directory and OpenCV 4.2.1 was automatically able to detect both CUDA and CUDNN. However, this step should *not be needed*

I'd appreciate if anyone could tell me what is missing. Have things changed in  `nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04` with respect to the requirement for additional packages that need to be installed? And if so, what exactly do we need to install? I am pretty sure using `nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04` should not need a full cuda reinstallation, so if there is a smaller package that needs to be installed, or inadvertently left out in this image, I'd love to know what.

Thanks

**Comment by pliablepixels** [comment]
ouch I think this was my error.

**Comment by himty** [comment]
How was this fixed?

**Comment by kameel2311** [comment]
> How was this fixed?

Are you also recently having this error while it the image used to be working before ?

**Comment by elezar** [comment]
Note that the CUDA Images had the following [support policy](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md) defined. 

Please direct issues with missing images to the GitLab repo.
