### ISSUE TITLE
CUDA not accessible from inside imported container

### ISSUE THREAD

**Issue by ahmedshoaib** [NVIDIA/nvidia-docker#1198]
### 1. Issue or feature description
I built a CUDA container using the official [Dockerfile](https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubuntu16.04/10.2/base/Dockerfile) . When I export this container and import it elsewhere; CUDA seems to be invisible to the `nvidia-smi` command and it shows :

> _+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
.
.
.

Cuda files are present at /usr/local/ but $CUDA* environment variables seem to be missing/uninitialised.
Starting the container with --env-file with appropriate ENV variables as in the [Dockerfile](https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubuntu16.04/10.2/base/Dockerfile) seems to work.
Does this mean that I have to initialise env variables each time I import a CUDA container? 

### 2. Steps to reproduce the issue
Download the [Dockerfile](https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubuntu16.04/10.2/base/Dockerfile) from here.
Get a container running using the dockerfile and export the container to a .tar file
`docker export <CONTAINERID> > image.tar`
Import the tar file and run the imported image.
`docker import image.tar <image_ID>:<TAG>`.
Run the `nvidia-smi` command. It doesn't detect the CUDA

Host Machine : Ubuntu 18.04

**Comment by RenaudWasTaken** [comment]
Hello!

Please use the issue template so that we can help debug the issue you are facing :)
