### ISSUE TITLE
unknown flag: --gpus with docker server version 19.03.6

### ISSUE THREAD

**Issue by chunniunai220ml** [NVIDIA/nvidia-docker#1199]
I have installed docker refer to the docker official documents .docker version:
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server: Docker Engine - Community
 Engine:
  Version:	19.03.6
  API version:	1.40 (minimum version 1.12)
  Go version:	go1.12.16
  Git commit:	369ce74a3c
  Built:	Thu Feb 13 01:26:38 2020
  OS/Arch:	linux/amd64
  Experimental:	false
 containerd:
  Version:	1.2.10
  GitCommit:		b34a5c8af56e510852c35414db4c1f4fa6172339
 nvidia:
  Version:	1.0.0-rc4+dev
  GitCommit:		b2567b37d7b75eb4cf325b77297b140ea686ce8f
 docker-init:
  Version:	0.13.0
  GitCommit:		949e6fa

then I installed navidia-docker by the instruction in readme. failed  test :
sudo docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
unknown flag: --gpus
See 'docker run --help'.

I also see the issue(https://github.com/NVIDIA/nvidia-docker/issues/1165).but the command 
sudo apt-get install docker-ce-cli ,does not work for me. the  client also 17.12.0-ce.

What should i do to solve the  problem?

**Comment by RenaudWasTaken** [comment]
You can update the docker-client to 19.03 :)
