### ISSUE TITLE
Large Image Sizes

### ISSUE THREAD

**Issue by ruffsl** [NVIDIA/nvidia-docker#12]
So I was probing the current cuda image, and I'm thinking it could stand to shed a little weight:

``` console
$ docker images
REPOSITORY                                TAG                    IMAGE ID            CREATED             VIRTUAL SIZE
cudnn                                     v2-7.0                 80a8e0efea8d        21 hours ago        2.041 GB
cuda                                      7.0                    f8abb195d52b        21 hours ago        2.012 GB
ubuntu                                    14.04                  e9ae3c220b23        9 days ago          187.9 MB
```

A quick check on the just the size of the cuda libraries reviles:

```console
$ docker run -it cuda:7.0 du -sh usr/local/cuda-7.0/
1.5G	usr/local/cuda-7.0/

$ docker run -it cuda:7.0 du -sh usr/local/cuda-7.0/*
4.0K	LICENSE
4.0K	README
43M		bin
170M	doc
5.9M	extras
0		include
0		lib64
180M	libnsight
122M	libnvvp
22M		nvvm
184M	samples
272K	share
592K	src
790M	targets
160K	tools
```

So we've have about about 324.1 megabytes coming in elsewhere. I'm seeing Xserver and perhaps other unessential deps installed that users could get themselves if need be. So perhaps we could cut a little fat by tweaking call to [`apt-get install`](https://github.com/NVIDIA/nvidia-docker/blob/f715448fe5dcaaeda9e8758b89c59ae4dc0a028d/ubuntu-14.04/cuda/7.0/Dockerfile#L15). Also, not sure if the samples could be installed later, but that might be nice thing to toss into a higher tag. Others not deploying cuda containers to cloud instances might still want it.

**Comment by 3XX0** [comment]
Agreed, after discussion we're going to split cuda into devel/runtime.
