### ISSUE TITLE
How to connect to non-defult docker daemon? (-H is not working?)

### ISSUE THREAD

**Issue by agilmor** [NVIDIA/nvidia-docker#120]
We are setting up a small HPC with the following requeriments:
- slurm scheduler
- docker available but not forced (not all jobs will we dockerized)
- gpus acces for native and docker jobs
- access to network filesystem (nfs or whatever) from native and docker jobs
- multiple users... without root access!

Following the idea of using multiple docker daemons with usernamespaces ([by Matthieu Fronton](https://medium.com/@frntn/not-your-grandmother-s-docker-environment-c3c5c1a5aab)) we already have almost everything working... except for the GPUs access from docker containers.

In [this issue](https://github.com/NVIDIA/nvidia-docker/issues/113#issuecomment-227996349) @3XX0 explained a way to use `nvidia-docker` with slurm (thanks Jonathan!).
Altough it works with a default docker daemon,  I've noted that `nvidia-docker` is not passing the `-H` parameters to the `docker` client, so I cannot connect to any other `docker` daemon that the default one?
If we cannot use the `-H` parameter, then I cannot have the multiple daemons, not multiple users (namespaces), wich is a key part in our framework...

My first approach was learning about the magic of `nvidia-docker` and use the internals to create ourown reduced and integrated version... but @3XX0 is convicing me that `nvidia-docker` could provide a better isolation, and probably a more extended suport... so, I'm tring to integrate the whole tool and not only its magic! ;-)

So, my question is, is `nvidia-docker` able to connect to multiple `docker` daemons in the same host using the `-H` parameter somehow?

I see that I can use the `-l` parameter of the plugin to listen from different ports... but I don't see how to tell the plugin or the client how to connect to an specific daemon port?

Any suggestion to achieve our requeriments will be welcome!
;-)

Thanks!

Albert

**Comment by 3XX0** [comment]
What do you mean by `nvidia-docker` is not passing the -H option?
`nvidia-docker` arguments are passthrough to `docker`, you should be able to use the -H.

I think you are referring to internal `docker` calls failing, if that's the case you can either use `DOCKER_HOST` instead of -H or define `NV_DOCKER` with the -H option in it (see [here](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#description))
