### ISSUE TITLE
Support for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by vak** [NVIDIA/nvidia-docker#1204]
see $title.

UPDATE: I've successfully installed `nvidia-container-toolkit` in Ubuntu 20.04 LTS Focal Fossa by using the artifacts provided for Ubuntu 19.10, i.e. via:

`curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu19.10/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
`

so, it would be nice at least to redirect URL

`https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list`

to:

`https://nvidia.github.io/nvidia-docker/ubuntu19.10/nvidia-docker.list`

all runs fine so far.

**Comment by RenaudWasTaken** [comment]
Hello!

I'll look into it during the march time frame :)
In the mean time I've labelled your issue for better visibility.

**Comment by zloidemon** [comment]
Do you have any repos for 20.04?

**Comment by RenaudWasTaken** [comment]
Added the links to the repos :) !

**Comment by FrancisLeung** [comment]
Hi, Everyone,
 Who can answer my problem about installing nvidia-docker on Ubuntu 20.04? I got GTX 960M GPU installed on Dell Inspiron 7559 PC; I have set up dual boot for Ubuntu-mate 20.04 separated from Windows 10 Pro already, but I cannot install nvidia-docker and it showed error message:
"Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown."
Can anyone help please?
I had checked additional driver on ubuntu-mate 20.04 and key in command of ubuntu-drivers device on terminal to confirm that there is nvidia driver-440 installed already. I could install docker, but can't install nvidia-docker when I key in command of nvidia-smi for double confirmation and then the above error messages prompted up.
