### ISSUE TITLE
> Hey, I got a same problem.

### ISSUE THREAD

**Issue by LinoSun** [NVIDIA/nvidia-docker#1205]
> Hey, I got a same problem but, solved.
> 
> `sudo usermod -a -G docker $USER`
> 
> After terminate your SSH session and re-connect.
> 
> `$ groups`
> And check docker is in this list. If docker appears, it will work
> 
> Ref : https://techoverflow.net/2018/12/15/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/

Thanks for helping me. 

I tried your solution just now, unfortunately it didn't work for me. It's the same error as before. Maybe there are something missing on the server.

Again, I really appreciate your help and patience.

Have a nice day.

_Originally posted by @ianniu in https://github.com/NVIDIA/nvidia-docker/issues/1029#issuecomment-516869922_

**Comment by RenaudWasTaken** [comment]
Hello!

This looks like a docker issue, I suggest you look into the installation steps of docker: https://docs.docker.com/install/

And open an issue on the docker forums if you still see an issue.
