### ISSUE TITLE
Small suggestion, about installtion guide, which make big difference

### ISSUE THREAD

**Issue by Hasankanso** [NVIDIA/nvidia-docker#1206]
in the installation tutorial ,specifically this section:
https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster

this works:
sudo apt-get update
sudo apt-get install -y nvidia-container-toolkit

but this doesn't work:
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit

reason:
Data from such a repository can't be authenticated

so maybe change it a bit since there's no real difference?

**Comment by RenaudWasTaken** [comment]
Hello!

This looks like an issue on your installation, I would suggest you follow the stackoverflow answer and try to re-install or use apt with the unsecure option :)

https://askubuntu.com/questions/995484/data-from-such-a-repository-cant-be-authenticated
