### ISSUE TITLE
Failed to start NVIDIA Docker plugin

### ISSUE THREAD

**Issue by JuanDavidG1997** [NVIDIA/nvidia-docker#1207]
### 1. Issue or feature description
Unable to start NVIDIA docker plugin
### 2. Steps to reproduce the issue
sudo apt-get install nvidia-docker
after install nvidia-container-tools
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

NVRM version:   435.21
CUDA version:   10.1

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 1060
Brand:          GeForce
GPU UUID:       GPU-b68d7049-c349-5ca4-82ad-f8f1b5c43e33
Bus Location:   00000000:01:00.0
Architecture:   6.1

Linux juan-GL63-8RE 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Timestamp                           : Mon Mar  2 08:14:34 2020
Driver Version                      : 435.21
CUDA Version                        : 10.1

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1060
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-b68d7049-c349-5ca4-82ad-f8f1b5c43e33
    Minor Number                    : 0
    VBIOS Version                   : 86.06.60.00.25
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A

Docker version 19.03.6, build 369ce74a3c

version: 1.0.7
build date: 2020-01-21T18:59+00:00
build revision: b71f87c04b8eca8a16bf60995506c35c937347d9
build compiler: x86_64-linux-gnu-gcc-7 7.4.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

uber/horovod        0.15.2-tf1.12.0-torch1.0.0-py3.5   acbf5231dabb        15 months ago       6.04GB

Trying to ru this image to use PocketFlow

Thank you!

**Comment by RenaudWasTaken** [comment]
Hello!

There isn't any NVIDIA plugin since 1.0 got deprecated (end of 2017). This is probably why you are seing that error :)
