### ISSUE TITLE
Installation failure on Ubuntu

### ISSUE THREAD

**Issue by vmarkovtsev** [NVIDIA/nvidia-docker#121]
```
sudo dpkg -i nvidia-docker_1.0.0.rc.3-1_amd64.deb 
(Reading database ... 143942 files and directories currently installed.)
Preparing to unpack nvidia-docker_1.0.0.rc.3-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0~rc.3-1) over (1.0.0~rc.3-1) ...
Setting up nvidia-docker (1.0.0~rc.3-1) ...
Setting up permissions
chown: invalid spec: ‘nvidia-docker:’
dpkg: error processing package nvidia-docker (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 nvidia-docker

```

**Comment by 3XX0** [comment]
I guess you tried to install RC3 after RC2?
Can you try purging the package first? Our old packages had an issue with user creation.

```
sudo apt-get purge nvidia-docker
sudo dpkg -i nvidia-docker_1.0.0.rc.3-1_amd64.deb
```

**Comment by vmarkovtsev** [comment]
Nope, it was a clean install on a clean machine. I cured it by manually executing
```
sudo useradd -r -M -d /var/lib/nvidia-docker -s /usr/sbin/nologin -c "NVIDIA Docker plugin" nvidia-docker
```
Somehow it thinks in postinst that $2 is defined.

**Comment by flx42** [comment]
We never had this problem on a fresh install, so that's surprising. Which OS version did you use?

**Comment by zeryx** [comment]
I had the same problem, purge all docker installation information and follow the steps to install docker for ubuntu: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

Once you have the docker daemon working, _then_ install nvidia-docker.

**Comment by flx42** [comment]
Yes, you need to fully install docker first before installing nvidia-docker.

Closing for now, please reopen if anyone encounters the problem again on a fresh install.
