### ISSUE TITLE
How to change gpu for a container? docker update doesn't work.

### ISSUE THREAD

**Issue by AeroXi** [NVIDIA/nvidia-docker#1211]
[https://docs.docker.com/engine/reference/commandline/update/](url)
I tried using docker update command to change specific gpu for a stopped container, but is doesn't support the --gpus argument.
I have several people using one multi gpu server, so sometimes a container may need to change gpu it mounted, to use a free gpu. Maybe there're other ways to achieve this?

**Comment by RenaudWasTaken** [comment]
Hello!

Unfortunately you cannot do this. GPUs are similar to volumes in that once the container is started, you won't be able to change them.
