### ISSUE TITLE
Centos 7: Unable to install docker

### ISSUE THREAD

**Issue by gsunilkumar1** [NVIDIA/nvidia-docker#1212]
I tried using this steps  given in documentation but unable to uninstall and run docker

distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo

sudo yum install -y nvidia-container-toolkit
sudo systemctl restart docker

yum install -y nvidia-container-toolkit
Loaded plugins: aliases, auto-update-debuginfo, copr, fastestmirror, filter-data, fs-snapshot, keys, langpacks, list-data, local, merge-conf, ovl,
              : post-transaction-actions, pre-transaction-actions, priorities, protectbase, ps, remove-with-leaves, rpm-warm-cache, show-leaves,
              : tmprepo, tsflags, upgrade-helper, verify, versionlock
Repository cuda is listed more than once in the configuration
Repository libnvidia-container is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirror.sfo12.us.leaseweb.net
 * centos-sclo-rh: centos.sonn.com
 * centos-sclo-sclo: mirror.keystealth.org
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.sfo12.us.leaseweb.net
 * updates: mirror.sfo12.us.leaseweb.net
Skipping filters plugin, no data
0 packages excluded due to repository protections
Resolving Dependencies
Skipping filters plugin, no data
--> Running transaction check
---> Package nvidia-container-toolkit.x86_64 0:1.0.5-2 will be installed
--> Processing Dependency: libnvidia-container-tools < 2.0.0 for package: nvidia-container-toolkit-1.0.5-2.x86_64
--> Processing Dependency: libnvidia-container-tools >= 0.1.0 for package: nvidia-container-toolkit-1.0.5-2.x86_64
--> Running transaction check
---> Package libnvidia-container-tools.x86_64 0:1.0.7-1 will be installed
--> Processing Dependency: libnvidia-container1(x86-64) >= 1.0.7-1 for package: libnvidia-container-tools-1.0.7-1.x86_64
--> Processing Dependency: libnvidia-container.so.1(NVC_1.0)(64bit) for package: libnvidia-container-tools-1.0.7-1.x86_64
--> Processing Dependency: libnvidia-container.so.1()(64bit) for package: libnvidia-container-tools-1.0.7-1.x86_64
--> Running transaction check
---> Package libnvidia-container1.x86_64 0:1.0.7-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================================
 Package                                          Arch                          Version                           Repository                     Size
======================================================================================================================================================
Installing:
 nvidia-container-toolkit                         x86_64                        1.0.5-2                           _local                        616 k
Installing for dependencies:
 libnvidia-container-tools                        x86_64                        1.0.7-1                           _local                         36 k
 libnvidia-container1                             x86_64                        1.0.7-1                           _local                         77 k

Transaction Summary
======================================================================================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 730 k
Installed size: 2.1 M
Downloading packages:
warning: /var/lib/yum/plugins/local/libnvidia-container-tools-1.0.7-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID ac1160cd: NOKEY
Public key for libnvidia-container-tools-1.0.7-1.x86_64.rpm is not installed
------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                 182 MB/s | 730 kB  00:00:00

Public key for libnvidia-container-tools-1.0.7-1.x86_64.rpm is not installed

Please suggest

**Comment by RenaudWasTaken** [comment]
Hello!

it looks like for some reason yum is not pulling the GPG key, it is here if you want to manually add it: https://github.com/NVIDIA/nvidia-docker/blob/gh-pages/gpgkey

It's possible you are on an old version of yum or have configured it not to pull the key. Hope this helps!

**Comment by smogsy** [comment]
so been battling with this for quite some time, however i think their is in an issue with the GPGkeys

See below my testing

gpg gpgkey
```
pub  4096R/F796ECB0 2017-09-28 NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
sub  2048R/AC1160CD 2019-09-18 [expires: 2020-09-17]
```

sudo yumdownloader libnvidia-container-tools

sudo rpm --checksig libnvidia-container-tools-1.1.1-1.x86_64.rpm
`libnvidia-container-tools-1.1.1-1.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#ac1160cd)`

`rpm --import gpgkey.1`

rpm --checksig libnvidia-container-tools-1.1.1-1.x86_64.rpm
`libnvidia-container-tools-1.1.1-1.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#ac1160cd)`

**Comment by jonathan-dill-nih** [comment]
% wget https://nvidia.github.io/libnvidia-container/gpgkey
...
% gpg -v gpgkey
gpg: NOTE: signature key AC1160CD expired Tue 15 Jun 2021 08:16:24 PM EDT
pub  4096R/F796ECB0 2017-09-28 NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
sig        F796ECB0 2017-09-28   [selfsig]
sub  2048R/AC1160CD 2019-09-18 [expires: 2021-06-16]
sig        F796ECB0 2020-06-16   [keybind]
