### ISSUE TITLE
pytorch multi gpu issue

### ISSUE THREAD

**Issue by SlowMonk** [NVIDIA/nvidia-docker#1213]
#model = DataParallelModel(model)
#criterion = nn.NLLLoss()
#criterion = DataParallelCriterion(criterion) 

#import torch.nn as nn
#model = nn.DataParallel(model)

after using multi gpu. when it shut down the gpu memory is not released

**Comment by ptrblck** [comment]
Hi @SlowMonk,

how are you shutting down the GPU? Does your script exit properly or are you killing your run?

Also, could you post a minimal code snippet to reproduce this issue as well as your setup (i.e. PyTorch, CUDA, cudnn, NCCL version)?
