### ISSUE TITLE
Dockerfile behavies differently on different Host OS

### ISSUE THREAD

**Issue by mmichailidis** [NVIDIA/nvidia-docker#1214]
Hello,
I am trying to build a Dockerfile that will be `cuda-enabled` and cuda will work with the GPU that my machine has.  
My initial Dockerfile is the following : 
```
FROM ubuntu:18.04

RUN apt update -y
RUN apt upgrade -y

RUN apt install \
    nvidia-cuda-toolkit \
    -y
```
DLib when compiles it requires some stuff from cuda-toolkit so I have to include this. Its not on the example as this is the minimal Dockerfile that produced the error. 

I have two different machines with different host OS and different GPU cards. 

The first machine runs `Debian:Buster` with docker version `Docker version 19.03.5, build 633a0ea838`  

`nvidia-container-runtime --version` output : 
```
runc version 1.0.0-rc8+dev
commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
spec: 1.0.1-dev
```
and `nvidia-smi` output :  `418.74       Driver Version: 418.74       CUDA Version: 10.1` 

The second machine runs `Ubuntu:18.04` with docker version `Docker version 19.03.6, build 369ce74a3c` 

`nvidia-container-runtime --version` output: 
```
runc version 1.0.0-rc8+dev
commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
spec: 1.0.1-dev
```
and `nvidia-smi` output:  `435.21       Driver Version: 435.21       CUDA Version: 10.1`

If I build (`docker build -t some-name:1 -f Dockerfile .` ) on the ubuntu machine the container is going to work as expected ( `docker run --rm --gpus all some-name:1 nvidia-smi` )
but if I build the image on the debian machine the response of the run will be `Failed to initialize NVML: Driver/library version mismatch`. 

If I change the Dockerfile to start from `debian:buster` ( and include the appropriate debs to apt in order for apt to find cuda-toolkit )
the response of the image when I try to run it with the previous command changes for BOTH machines to 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/d5ef8a4b0895396626bc93ee684dae88b020423f2f2d092c2d72e9ce0ec52b1d/merged/usr/bin/nvidia-smi: file exists\\\\n\\\"\"": unknown.
``` 

Is there something I am doing wrong and it behaves that way or there is an actual problem? 
I can provide more information incase its needed. The cuda drivers are correct as on the host machine nvidia-smi works and gpu is discoverable. The two gpus are not the same. 

Thank you in advance

**Comment by RenaudWasTaken** [comment]
First, you can find examples of the CUDA images here: https://gitlab.com/nvidia/container-images/cuda/-/tree/master/dist

Note that the environment variables have their importance and should be included in the dockerfile (see: https://github.com/NVIDIA/nvidia-container-runtime).

My initial guess here is that you also installed the NVIDIA driver in your container, usually the way you would bypass this is to just pull from the nvidia/cuda images rather than building your own :)

There's a lot of details about these issues and what the NVIDIA Container Toolkit does to help in this case, on the wiki if you are interested.

Hope this helps!
