### ISSUE TITLE
Update driver inside Docker?

### ISSUE THREAD

**Issue by ricshaw** [NVIDIA/nvidia-docker#1215]
Is it possible to update the nvidia driver version inside a Dockerfile?
I have tried putting FROM nvidia/driver:440.33.01-ubuntu18.04 in my Dockerfile, but this seems to have no effect on the driver when I do nvidia-smi which just says my host driver 384.125.

**Comment by RenaudWasTaken** [comment]
Hello!

You shouldn't build any images from the NVIDIA driver but from nvidia/cuda.

Additionally, the NVIDIA driver container is expected to be ran on a machine that doesn't already have the NVIDIA driver installed. See https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta)

I would suggest you to update your host driver using the mechanism you used to install it in the first place :)
