### ISSUE TITLE
docker image cuda 10.1 broken ? 

### ISSUE THREAD

**Issue by jomach** [NVIDIA/nvidia-docker#1219]
Hi Guys, 

I'm trying to use the docker image from nvidia but I'm getting: 
Dockerfile: 
FROM nvidia/cuda:10.1-base-ubuntu18.04
RUN apt-get update

Result: 
`  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu bionic InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports InRelease' is not signed.
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release: At least one invalid signature was encountered.
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' is not signed.
W: GPG error: https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release: At least one invalid signature was encountered.
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' is not signed.
W: GPG error: http://security.ubuntu.com/ubuntu bionic-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' is not signed.`

Is this normal ?

**Comment by RenaudWasTaken** [comment]
```
➜  egx git:(master) ✗ docker run -it nvidia/cuda:10.1-base-ubuntu18.04 bash
Unable to find image 'nvidia/cuda:10.1-base-ubuntu18.04' locally
10.1-base-ubuntu18.04: Pulling from nvidia/cuda
7ddbc47eeb70: Already exists
c1bbdc448b72: Already exists
8c3b70e39044: Already exists
45d437916d57: Already exists
d8f1569ddae6: Already exists
85386706b020: Already exists
ee9b457b77d0: Already exists
Digest: sha256:3cb86d1437161ef6998c4a681f2ca4150368946cc8e09c5e5178e3598110539f
Status: Downloaded newer image for nvidia/cuda:10.1-base-ubuntu18.04
root@8908e8e411c8:/# apt-get update
Ign:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [564 B]
Get:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [819 B]
Get:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [141 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [30.4 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [7641 B]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [836 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [826 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [31.0 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1128 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [44.7 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [11.7 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1355 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Get:26 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4247 B]
Fetched 17.8 MB in 3s (5854 kB/s)
Reading package lists... Done
root@8908e8e411c8:/#
```

Could be a cache, cdn, proxy or mirror issue.

**Comment by RenaudWasTaken** [comment]
It's pretty likely this is an issue on the side of your local network though...
Not sure what's the next step here

**Comment by jomach** [comment]
I tested with another image and I have the same issue so it is not image specific. Thx

**Comment by jomach** [comment]
Found the issue. My docker has a limit on how much it can consume on disk. It was full.

**Comment by dfldylan** [comment]
> Found the issue. My docker has a limit on how much it can consume on disk. It was full.

um.... thanks for your answer
