### ISSUE TITLE
import image use nvidia-smi show cuda version error

### ISSUE THREAD

**Issue by yumeihong** [NVIDIA/nvidia-docker#1221]
I try to export image(base on nvidia/cuda:10.0-base image),and import to a new image.
1. docker export container_id > image.tar
2. cat image.tar | docker import - new_image:latest
3. docker run -i -t --gpus all new_image /bin/bash

After I imported image and use nvidia-smi show cuda version is N/A.

before export:
![擷取](https://user-images.githubusercontent.com/53203517/76581066-0f116580-650d-11ea-8fdb-b248f79efb97.JPG)

after import:
![擷取2](https://user-images.githubusercontent.com/53203517/76581160-6b748500-650d-11ea-9f57-a602e379641c.JPG)

Did I lose some steps?

**Comment by RenaudWasTaken** [comment]
Hello there!

I can't really reproduce with a newer driver, it could be related to your driver version and I would suggest you update to a newer one (440.64)!

**Comment by TL-chenming** [comment]
I still have the same issue with driver 440.100 and cuda version:10.2

**Comment by svmsunny** [comment]
> I still have the same issue with driver 440.100 and cuda version:10.2
Did you solve the problem? Thx

**Comment by Aaron930** [comment]
> > I still have the same issue with driver 440.100 and cuda version:10.2
> > Did you solve the problem? Thx

**Comment by elezar** [comment]
Hi Just a question. What are the values of the `NVIDIA_` environment variables in the container running from the imported image?

**Comment by TL-chenming** [comment]
> > > I still have the same issue with driver 440.100 and cuda version:10.2
> > > Did you solve the problem? Thx

Yeah, I've solved this problem already.
Do not export directly. use commit instead.

1.docker commit docker_id image:lastest
2.docker save image:lastest > image.tar
3.docker load < image.tar
4.docker run...

Hope this will be helpful.

**Comment by Aaron930** [comment]
> Hi Just a question. What are the values of the `NVIDIA_` environment variables in the container running from the imported image?

HI, i solve my problem by using docker commit, i think i lost some layer info when docker export. 

thx for reply
