### ISSUE TITLE
No CMAKE_CUDA_COMPILER could be found

### ISSUE THREAD

**Issue by elalish** [NVIDIA/nvidia-docker#1222]
I'm attempting to set up a CI to test compilation (no GPU, so it won't actually run the CUDA code, but I can run it serially using Thrust to get decent test coverage). I'm using Github Actions on Ubuntu 16.04 with your docker image: `nvidia/cuda:9.2-devel-ubuntu16.04`

Everything seems to go fine until CMake fails to find NVCC, which is a problem I've encountered far too many times on my local Ubuntu machine as well. What am I missing?

The error:
```
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
```

My yml file:
```
jobs:
  build:
    runs-on: ubuntu-16.04
    - uses: actions/checkout@v2
    - uses: docker://nvidia/cuda:9.2-devel-ubuntu16.04
    - name: Build and Test
      run: |
        sudo apt install -y libglm-dev libassimp-dev libboost-graph-dev
        OMP_NUM_THREADS=4
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .. && make
```

**Comment by RenaudWasTaken** [comment]
Hello there! nvcc is at /usr/local/cuda/bin/nvcc in the CUDA images, you should probably set the CUDACXX environment variable :)

Hope this helps!

**Comment by elalish** [comment]
@RenaudWasTaken Thanks, I followed your directions, but now I get this error:
```
CMake Error at /usr/local/share/cmake-3.16/Modules/CMakeDetermineCUDACompiler.cmake:25 (message):
  Could not find compiler set in environment variable CUDACXX:

  /usr/local/cuda/bin/nvcc.
```
I'm guessing CMake was looking for it there too. Are you sure that's the right path in this older CUDA image? Then again, it's the right path on my own machine... 

Anyway, you can see for yourself [here](https://github.com/elalish/manifold/pull/33/checks?check_run_id=524631420). This is my first time trying to hook up docker with Github Actions, so maybe I'm missing something simple?

**Comment by elalish** [comment]
Ah, this was just me not knowing how to set up Github actions. I tried to do `uses: ` for the docker image, but then the following `run: ` command was not happening inside it, hence not finding CUDA. Switching to `container: ` fixed it.

**Comment by kograins** [comment]
In Ubuntu 18，I solved the problem by

1. Edit the CMakeLists.txt by editor:
nano CMakeLists.txt

2. Add the script below in appropriate position:
SET(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
