### ISSUE TITLE
nivida version 384 to upgrade 418

### ISSUE THREAD

**Issue by itblaize** [NVIDIA/nvidia-docker#1223]
Hi,

today i have updated nvida driver in dgx server (ubuntu 16.04) from 384 to 418. i am getting below error after reboot

While starting docker container we are getting below issue,  

nvidia-docker | 2020/03/18 11:18:10 Error: Could not load UVM kernel module. Is nvidia-modprobe installed? 

Please help

**Comment by dualvtable** [comment]
Hi @itblaize 

What is the output of `lsmod | grep -i nvidia` ? Does `nvidia-smi` work for you after you updated drivers? 

Also - how did you update drivers? Did you use the official DGX repositories?
