### ISSUE TITLE
Canonical provided driver and nvcr.io out of sync

### ISSUE THREAD

**Issue by mdegans** [NVIDIA/nvidia-docker#1224]
## 1. Issue or feature description

The latest driver version in ubuntu's repos is 435, yet all images in nvcr.ip are built against 440.

### 2. Steps to reproduce the issue

Install the latest drivers from Ubuntu repos.
pull an image from nvcr.io and try to run somethign (eg. PyTorch)

```
ERROR: This container was built for NVIDIA Driver Release 440.33 or later, but
       version 435.21 was detected and compatibility mode is UNAVAILABLE.

       [[CUDA Driver UNAVAILABLE (cuInit(0) returned 803)]]
```

----
This is less of an issue and more of request. Please either provide an apt repo with drivers, ensure Canoical's repos are up to date, or build your images against the latest version Canoical provides.

The .run installer is not a solution since, unless something has changed since I last used it, ~~it breaks with every kernel update unless you disable secure boot~~ (edit: i just tried it and it won't even build. headers are installed). Having these versions out of sync is frustrating. 440 is in 20.04 but 20.04 isn't supported by nvidia-docker.

**Comment by dualvtable** [comment]
Hi @mdegans - 

CUDA provides official network repositories where we post driver packages. We don't have direct control over what Canonical publishes on their repositories, but I would recommend using the CUDA network repos to install drivers. 

See here for detailed instructions on how to use packages for various officially supported distributions: 

https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html

**Comment by mdegans** [comment]
Thanks @dualvtable,

I realise that you don't have control over what Canonical puts in their repos and that you want to build against the latest version of the driver, but this makes it harder to set up a system, especially when the goal is to install the driver, and just the driver, on the host.

Thanks for the link to the repo. It might be helpful for others if it was easier to find from [nvidia.com/drivers](https://www.geforce.com/drivers). Maybe a link [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork) for linux, but making it clear that one only needs to install `cuda-drivers` or `nvidia-headless-440` for a headless install.  `cuda-drivers` wants to install X11.

**Comment by dualvtable** [comment]
Thanks for the suggestion. I'll look into doing that. I'll close this comment for now.
