### ISSUE TITLE
Feature Request: Windows support

### ISSUE THREAD

**Issue by FlamesoFF** [NVIDIA/nvidia-docker#1228]
> No, we do not support Microsoft Windows

![image](https://user-images.githubusercontent.com/5371279/77846977-f74b0a00-71b9-11ea-83ae-0124093e819e.png)

What is the actual nonsense, nvidia? Where's Windows support?

**Comment by nvjmayo** [comment]
Sorry! This requires some functionality in Windows that Microsoft must add. Some of it is there, some of it is still being defined. I would say it's "close", without committing to any specific date. Currently there is limited functionality of GPU virtualization, but isn't quite up to what is needed for docker and k8. 

As for stats, perhaps you should consider looking at OSes used in clusters. You'll see that Android number go to 0% at the very least ;-) But seriously, we have users and customers that want this, not a lot of them, but enough that it is worth doing when everything is ready.

**Comment by FlamesoFF** [comment]
@nvjmayo All right, then. Thank you for the clarification!

**Comment by nvjmayo** [comment]
Preview of this feature is now available. https://developer.nvidia.com/cuda/wsl
