### ISSUE TITLE
Ubuntu 16.04  install nvidia-docker2.0 is circular login after restarting the computer

### ISSUE THREAD

**Issue by TONG369** [NVIDIA/nvidia-docker#1229]
Hello！ I need to install nvidia-docker2.0 for the experiment. Before this step, I installed the nvidia driver440.64 and dockers19.03，cuda8.0. I can get the correct output by using the corresponding instructions, so Ican judge that these two applications have been successfully installed on Ubuntu16.04. But, there is a problem. As long as the computer restarts, the problem of circular login will occur. Please everyone has time to help me, thank you very much!!!

**Comment by cyremur** [comment]
When I encounter a circular login after messing with Nvidia drivers, I can usually fix it by setting the "nomodeset" boot option. You can either do that from grub or by going to terminal on login screen (Ctrl+Alt+F3, I think) and editing the /etc/default/grub to add "nomodeset" at the end of GRUB_CMDLINE_LINUX_DEFAULT.

More info: https://askubuntu.com/questions/38780/how-do-i-set-nomodeset-after-ive-already-installed-ubuntu

**Comment by TONG369** [comment]
@cyremur Thank you for your answer ！ the problem has been solved, good luck for you!!!
