### ISSUE TITLE
Unsupported distribution! 

### ISSUE THREAD

**Issue by samerkalil** [NVIDIA/nvidia-docker#1230]
lsb_release -a: 

    No LSB modules are available.
     Distributor ID:	Ubuntu
     Description:	Ubuntu 18.10
     Release:	18.10
     Codename:	cosmic

docker version:

   Client: Docker Engine - Community
    Version:           19.03.8
    API version:       1.40
    Go version:        go1.12.17
    Git commit:        afacb8b7f0
    Built:             Wed Mar 11 01:25:46 2020
    OS/Arch:           linux/amd64
    Experimental:      false

   Server: Docker Engine - Community
    Engine:
     Version:          19.03.8
     API version:      1.40 (minimum version 1.12)
     Go version:       go1.12.17
     Git commit:       afacb8b7f0
     Built:            Wed Mar 11 01:24:19 2020
     OS/Arch:          linux/amd64
     Experimental:     false
    containerd:
     Version:          1.2.13
     GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
    runc:
     Version:          1.0.0-rc10
     GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
    docker-init:
     Version:          0.18.0
     GitCommit:        fec3683

**Comment by samerkalil** [comment]
nvidia-smi
Mon Mar 30 16:46:04 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 950M    Off  | 00000000:03:00.0 Off |                  N/A |
| N/A   56C    P0    N/A /  N/A |    548MiB /  4046MiB |     48%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      7126      G   /usr/lib/xorg/Xorg                           237MiB |
|    0      7465      G   /usr/bin/gnome-shell                         103MiB |
|    0      8478      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files   147MiB |
|    0     12958      G   ...uest-channel-token=16857992730573353477    56MiB |
+-----------------------------------------------------------------------------+

**Comment by klueska** [comment]
What is the question / issue here?

**Comment by lelandyang** [comment]
I suppose the question here is that:
```
nvidia-docker shows "# Unsupported distribution! # Check https://nvidia.github.io/nvidia-container-runtime "
while trying to install nvidia-docker and add custom repo.
```

**Comment by elezar** [comment]
@samerkalil @lelandyang Ubuntu 18.10 is not officially supported by the installation process. It may be required to manually update the APT repo list for NVIDIA docker to point to Ubuntu 18.04.

**Comment by lelandyang** [comment]
interestingly, version 20.04 also points to 18.0r officially😂

**Comment by elezar** [comment]
Yes, the packages built for 18.04 also work for 20.04. We provide symlinks in this case as 20.04 is also an LTS release.
