### ISSUE TITLE
Unsupported version: Ubuntu 18.04

### ISSUE THREAD

**Issue by gustavotonini** [NVIDIA/nvidia-docker#1231]
According to the documentation, Ubuntu 18.04 was supposed to be supported, but the URL https://nvidia.github.io/nvidia-docker/ubuntu18.04/ is returning:

# Unsupported distribution! # Check https://nvidia.github.io/nvidia-docker

**Comment by klueska** [comment]
I can see how this text is misleading, but that URL is not meant to list anything directly. It is part of a path to the directory where the debian packages are hosted, but does not contain an `index.html` or any similar file to allow the contents of that intermediate directory to be listed.

However, if you go, to https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/nvidia-docker2_2.3.0-1_all.deb, for example, you will be able to download the debian file there.

Moroever, `nvidia.github.io` is just a static webserver hosting the `gh_pages` branch of the `nvidia-docker` repo, so you can browse what files are hosted there by going to https://github.com/NVIDIA/nvidia-docker/tree/gh-pages/.
