### ISSUE TITLE
error: expected primary-expression before ‘(’ token    return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);                            ^ /root/spconv/include/torch_utils.h:96:65: error: expected primary-expression before ‘>’ token    return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);

### ISSUE THREAD

**Issue by nmll** [NVIDIA/nvidia-docker#1233]
When building the spconv the library's from https://github.com/traveller59/spconv, the error occurred in the middle, anyone who knows?   based on pytorch=1.1.0,cuda=9.0

.....................
Scanning dependencies of target spconv
[ 47%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 52%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 57%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /root/spconv/include/spconv/pool_ops.h:20:0,
                 from /root/spconv/src/spconv/all.cc:16:
/root/spconv/include/torch_utils.h: In function ‘tv::TensorView<T> tv::torch2tv(const at::Tensor&)’:
/root/spconv/include/torch_utils.h:96:27: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                           ^
/root/spconv/include/torch_utils.h:96:65: error: expected primary-expression before ‘>’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                                                 ^
/root/spconv/include/torch_utils.h:96:68: error: expected primary-expression before ‘)’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                                                    ^
In file included from /root/spconv/src/spconv/all.cc:16:0:
/root/spconv/include/spconv/pool_ops.h: In function ‘at::Tensor spconv::indiceMaxPool(at::Tensor, at::Tensor, at::Tensor, int64_t)’:
/root/spconv/include/spconv/pool_ops.h:36:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^
/root/spconv/include/spconv/pool_ops.h: In function ‘at::Tensor spconv::indiceMaxPoolBackward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor)’:
/root/spconv/include/spconv/pool_ops.h:78:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^
In file included from /root/spconv/src/spconv/all.cc:17:0:
/root/spconv/include/spconv/spconv_ops.h: In function ‘at::Tensor spconv::indiceConv(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t)’:
/root/spconv/include/spconv/spconv_ops.h:344:50: error: expected primary-expression before ‘int’
       std::max_element(indicePairNumCpu.data_ptr<int>(),
                                                  ^
/root/spconv/include/spconv/spconv_ops.h:345:50: error: expected primary-expression before ‘int’
                        indicePairNumCpu.data_ptr<int>() + kernelVolume);
                                                  ^
/root/spconv/include/spconv/spconv_ops.h:347:57: error: expected primary-expression before ‘int’
       indicePairMaxSizeIter - indicePairNumCpu.data_ptr<int>();

**Comment by oby-yang** [comment]
i have same problem. how do you solve it?

**Comment by oby-yang** [comment]
i havi same problem. how do you solve it?

**Comment by klueska** [comment]
This issue is not related to `nvidia-docker` itself, but rather one of the containers running on top of `nvidia-docker`.

Please file an issue with NVIDIA GPU Cloud here:
https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/
