### ISSUE TITLE
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver

### ISSUE THREAD

**Issue by chetanmreddy** [NVIDIA/nvidia-docker#1234]
Getting the following error while trying to follow these instructions:  https://github.com/yuxiangsun/RTFNet#usage

> root@4728a09607c1:/opt/project# python3 test.py
Traceback (most recent call last):
  File "test.py", line 124, in <module>
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 178, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 99, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

Output when I check for correct installation:

> sudo docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
Tue Mar 31 20:10:13 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P8    N/A /  N/A |    596MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

> root@4728a09607c1:/opt/project# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

Edited:
This is my dockerfile:

> FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 
RUN apt-get update && apt-get install -y vim python3 python3-pip 
RUN pip3 install -U scipy==1.3.0 scikit-learn==0.21.3
RUN pip3 install tensorboardX==1.8 torchsummary==1.5.1 tensorflow==1.14.0
RUN pip3 install torch==1.2 torchvision==0.4.0

What am I missing? It seems like my installation is correct !

**Comment by klueska** [comment]
From an `nvidia-docker` perspective things seem to be working. I would file an issue with the `nvidia-gpu-cloud-ngc-users` forum here:
https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/25

**Comment by sunyq1995-dxs** [comment]
I met the same question.
And I ran command
“python -c 'import torch; print(torch.cuda.is_available())'” return True.

So do you know the reason and how to fix it ?
Thanks a lot ~
