### ISSUE TITLE
"Unable to locate package nvidia-container-toolkit" on Debian x86_64

### ISSUE THREAD

**Issue by mengzhugithub** [NVIDIA/nvidia-docker#1238]
I followed the steps listed here: https://github.com/NVIDIA/nvidia-docker
My OS is Debian, but I think the packages are missing in Debian 9 and 10 as well.
See more info below.

```
$ sudo apt-get install -y nvidia-container-toolkit
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nvidia-container-toolkit
```
```
$ cat  /etc/apt/sources.list.d/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/debian8/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/debian8/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/debian8/$(ARCH) /
```
```
$ sudo apt-get update
....
Hit https://nvidia.github.io  InRelease
Hit https://nvidia.github.io  InRelease
Hit https://nvidia.github.io  InRelease
....
```

```
$ sudo apt-cache search nvidia | grep container
libnvidia-container-dev - NVIDIA container runtime library (development files)
libnvidia-container-tools - NVIDIA container runtime library (command-line tools)
libnvidia-container1-dbg - NVIDIA container runtime library (debugging symbols)
libnvidia-container1 - NVIDIA container runtime library
nvidia-container-runtime-hook - NVIDIA container runtime hook
nvidia-container-runtime - NVIDIA container runtime
```

From https://nvidia.github.io/libnvidia-container/, Debian 8/9/10 on x86_64 should be supported. Can you help me with this? Thanks!

Can you help me with this? Thanks!

**Comment by adisubektie** [comment]
+1

**Comment by manaclan** [comment]
I'm having the same problem, anyone solved it?

**Comment by manaclan** [comment]
I have installed it after adding the distribution in [this link](https://nvidia.github.io/nvidia-docker/) and than download it   
`sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit`

**Comment by wegunterjr** [comment]
still unable to install the nvidia-container-toolkit, even after re-running suggested steps.
I am on the docker container from NGC, and it is running Ubuntu 16.04.

**Comment by vgoklani** [comment]
same issue here, unable to download the toolkit :(

**Comment by klueska** [comment]
There is no support for `nvidia-container-toolkit` under debian 8.
There is support under debian 9 and 10 though.

**Comment by ZGZGK1002** [comment]
I used Ubuntu 18.04.  Also can't install the nvidia-container-toolkit, even after re-running suggested steps.

**Comment by ZGZGK1002** [comment]
$ wget https://nvidia.github.io/nvidia-docker/gpgkey --no-check-certificate
$ sudo apt-key add gpgkey
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

$sudo apt-get update
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nvidia-container-toolkit

**Comment by liuheng92** [comment]
> $ wget https://nvidia.github.io/nvidia-docker/gpgkey --no-check-certificate
> $ sudo apt-key add gpgkey
> $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> $ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> $sudo apt-get update
> 
> $sudo apt-get install -y nvidia-container-toolkit
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package nvidia-container-toolkit

1. checkout nvidia-docker support list, https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list
2. if yes, checkout /etc/apt/sources.list.d/nvidia-docker.list is not empty, after you run "curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list"

**Comment by SurPer-Y** [comment]
you can try this !!! it works for me!!!
```
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
$ sudo systemctl restart docker
```

**Comment by berkai** [comment]
> you can try this !!! it works for me!!!
> 
> ```
> $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> $ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> $ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> 
> $ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
> $ sudo systemctl restart docker
> ```

This is just worked for me too. There is a detail I want to talk about
When I ran this code
` echo distribution=$(. /etc/os-release;echo $ID$VERSION_ID)`
It's respond `distribution=ubuntu20.04`

After that when I ran this code:
`curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`
It's respond
```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```

I upgraded my os from ubuntu18.04 to ubuntu20.04 two months ago. I hope that information help to solve this issue.

**Comment by jrsykes** [comment]
Still getting this problem with ubuntu20.10. Can't find a solution anywhere.

**Comment by elezar** [comment]
@jrsykes have you tried updating `/etc/apt/sources.list.d/nvidia-docker.list` manually to contain:
```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```
Note that we don't have explicit symlinks created for `ubuntu20.10`.

**Comment by jrsykes** [comment]
@elezar That's done it! Many thanks!

Upon checking the contents of `/etc/apt/sources.list.d/nvidia-docker.list` it said that the distribution was not supported.
For some reason manually updating this file did not work but using the command, with the ubuntu18.04 system explicitly specified did work:
`curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`

**Comment by elezar** [comment]
Glad to hear @jrsykes. I have created an issue on our side to explicitly add support for Ubuntu 20.10 so that this should not happen in future.

**Comment by geyang** [comment]
```bash
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
sudo systemctl restart docker
```

worked for me. If your `apt-get update` fails, run the installation manually.

**Comment by elezar** [comment]
@mengzhugithub is this still an issue on your side? Since the original issue is old and support for additional distributions has been added since then, I'm closing this issue. Please reopen if this is still an issue.

**Comment by fahnub** [comment]
> you can try this !!! it works for me!!!
> 
> ```
> $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> $ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> $ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> 
> $ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
> $ sudo systemctl restart docker
> ```

Lifesaving.

**Comment by AntonOfTheWoods** [comment]
That we are still faced with this basic issue 3 years later is a bit worrying...

**Comment by SokolovVadim** [comment]
Still facing the issue on Ubuntu 22.04. The steps above helped but this should be fixed

**Comment by elezar** [comment]
@AntonOfTheWoods and @SokolovVadim if you have followed the instructions as per [our documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#setting-up-nvidia-container-toolkit) and are still having problems, please let us know. Here the contents of your apt list files that reference the `libnvidia-container-toolkit` repository would be useful.

**Comment by SokolovVadim** [comment]
@elezar I was following the instructions from the documentation you shared but I was still getting the error: 
``` sudo apt-get install -y nvidia-container-toolkit
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nvidia-container-toolkit
```
The advice given by @fahnub helped to resolve it. I'm using Ubuntu 22.04 and this is my NVIDIA driver version:
```
 NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0  
```

**Comment by elezar** [comment]
Could you provide the output of `cat /etc/apt/sources.list.d/*.list | grep nvidia.github.io`? (Where any errors raised when you configured the repositories?)

**Comment by SokolovVadim** [comment]
Here is the output of `cat /etc/apt/sources.list.d/*.list | grep nvidia.github.io`
```
#deb  https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```

As far as I understand, the packages were signed first time when I used the command from a page that you have shared and when I tried another way it caused the error. Then I cleaned `/etc/apt/sources.list.d/nvidia-docker.list` and `/etc/apt/sources.list.d/nvidia-container-toolkit.list` and did the above mentioned actions

**Comment by kian182** [comment]
Here is the official documentation for installing NVIDIA Container Toolkit, in the section for Docker. Followed all the steps and worked perfectly.

Ubuntu 22.04
CUDA version: 12.2

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by AntonOfTheWoods** [comment]
Hmmm. So at this current point in time that link points to working documentation. Great. What are the chances someone coming back in 6 months with get a 404? There are plenty of providers that reorganise their docs every year or so and leave half the internet pointing to 404s but Nvidia has to be one of the biggest and best resourced.

**Comment by laclouis5** [comment]
> Hmmm. So at this current point in time that link points to working documentation. Great. What are the chances someone coming back in 6 months will get a 404? There are plenty of providers that reorganise their docs every year or so and leave half the internet pointing to 404s but Nvidia has to be one of the biggest and best resourced.

I just followed this documentation step by step and it does not works on my Ubuntu 20.04 x86_64. The first command:

```shell
sudo apt-get update \
    && sudo apt-get install -y nvidia-container-toolkit-base
```

Fails with error:

```
E: Unable to locate package nvidia-container-toolkit-base
```

**Comment by elezar** [comment]
@laclouis5 did you also configure your APT repositories as required? What is the output of 
```
cat /etc/apt/sources.list.d/*.list | grep nvidia.github.io
```

**Comment by laclouis5** [comment]
@elezar Thanks for the fast reply. The command does not output anything.

Where is this requirement written? The documentation only says that a NVIDIA driver is the only prerequisite if I'm not wrong and there is nothing in the first steps that mentions APT.

**Comment by laclouis5** [comment]
@elezar Thanks, yes I think that it could be improved a lot by reworking the structure and organisation of the sections.

**Comment by lx-r** [comment]
> you can try this !!! it works for me!!!
> 
> ```
> $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> $ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> $ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> 
> $ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
> $ sudo systemctl restart docker
> ```

One can look [https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#setting-up-nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#setting-up-nvidia-container-toolkit) for newest official document instruction.
