### ISSUE TITLE
Renew public gpgkey

### ISSUE THREAD

**Issue by jackfrancis** [NVIDIA/nvidia-docker#1241]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

Current public gpgkey (we use this to wire up apt driver installation) expires in 4+ months:

```
$ apt-key list | grep NVIDIA -A 1 -B 1
pub   4096R/F796ECB0 2017-09-28
uid                  NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
sub   2048R/AC1160CD 2019-09-18 [expires: 2020-09-17]
```

### 2. Steps to reproduce the issue

```
curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey > /tmp/aptnvidia.gpg
apt-key add /tmp/aptnvidia.gpg
```

And perform above `apt-key list` command to inspect key metadata.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by jackfrancis** [comment]
Hi nvidia, just wanting to get ahead of this before September. :)

**Comment by jackfrancis** [comment]
Hi @RenaudWasTaken, is there anything you can share about this apt gpg key being refreshed?

**Comment by nvjmayo** [comment]
I wrote a short note on refreshing the key. https://github.com/NVIDIA/nvidia-docker/blob/master/README.md#gpg-key-failures

Confirmed the key is renewed:
```
curl -Ls https://nvidia.github.io/nvidia-docker/gpgkey | gpg --keyid-format=0xlong --show-keys -
pub   rsa4096/0xDDCAE044F796ECB0 2017-09-28 [SCE]
      C95B321B61E88C1809C4F759DDCAE044F796ECB0
uid                              NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
sub   rsa2048/0x6ED91CA3AC1160CD 2019-09-18 [S] [expires: 2021-06-16]
```
closing

**Comment by jackfrancis** [comment]
Thanks @nvjmayo! :)
