### ISSUE TITLE
When the driver-container is stopped, the nvidia modules are not unloaded; subsequent driver container run fails.

### ISSUE THREAD

**Issue by TrueGreens** [NVIDIA/nvidia-docker#1242]
1. Issue or feature description
After stopping currently running driver container, and running a new version of it, following error:
========== NVIDIA Software Installer ==========
Starting installation of NVIDIA driver version 440.xx for Linux kernel version 4.15.0-70-generic
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use

### 2. Steps to reproduce the issue
Try run a driver-container-version X, stop it; run version Y.
Would be nice to indicate why the driver is in use -- there are no GUI or active compute task running.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used
[driver-container-issue.txt](https://github.com/NVIDIA/nvidia-docker/files/4440386/driver-container-issue.txt)

**Comment by GuoLiuFang** [comment]
same error, any updates ?
