### ISSUE TITLE
Issue on installing nvidia-docker for Ubuntu-mate 20.04

### ISSUE THREAD

**Issue by FrancisLeung** [NVIDIA/nvidia-docker#1244]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
Hi, anyone can answer hot to fix the problem when I key in command to install nvidia-docker for Ubuntu-mate 20.04 following formal website: https://github.com/NVIDIA/nvidia-docker. There is error message:
"~$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
~$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
~$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
OK
~$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
~$ sudo systemctl restart docker
~$ docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown."
### 2. Steps to reproduce the issue
As same as above
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [X] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [X] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [X] NVIDIA container library version from `nvidia-container-cli -V`
 - [X] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by RenaudWasTaken** [comment]
```
initialization error: cuda error: no cuda-capable device is detected
```

Pretty sure there are no GPUs on your system. You would be able to check that if you filled the issue template (section 3).

**Comment by FrancisLeung** [comment]
HI Renaud,
Thank you for your reply. I had checked with command of "ubuntu-drivers devices to confirm that there is nvidia driver 440 installed already. I could installed docker successfully after confirmation with command. However, when I installed nvidia-docker following official website of nvidia on Github and try to confirm whether or not the nvidia-docker was installed successfully. The above error messages were prompted up. I ensure GTX 960M GPU installed on Dell Insprion 7559.
Is there solution to fix this problem please?
