### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.

### ISSUE THREAD

**Issue by GwangsooHong** [NVIDIA/nvidia-docker#1246]
I followed driver-container from https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta) 

I got a error when changing `sudo sed -i 's/^#root/root/' /etc/nvidia-container-runtime/config.toml`
```
Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.
```
- Ubuntu 18.04

See /var/log/nvidia-container-toolkit.log 

I0409 09:28:27.686375 29760 nvc.c:281] initializing library context (version=1.0.7, build=b71f87c04b8eca8a16bf60995506c35c937347d9)
I0409 09:28:27.686423 29760 nvc.c:255] using root /run/nvidia/driver
I0409 09:28:27.686430 29760 nvc.c:256] using ldcache /etc/ld.so.cache
I0409 09:28:27.686436 29760 nvc.c:257] using unprivileged user 65534:65534
E0409 09:28:27.690053 29764 nvc.c:180] failed to change root directory: No such file or directory
W0409 09:28:27.690096 29764 nvc.c:181] skipping kernel modules load due to failure
I0409 09:28:27.690291 29765 driver.c:133] starting driver service
E0409 09:28:27.690756 29765 driver.c:197] could not start driver service: change root failed: no such file or directory
I0409 09:28:27.690888 29760 driver.c:233] driver service terminated successfully

I cannot find `/run/nvidia/driver`

**Comment by XDongiang** [comment]
I meer same error , do you resolve errors ?

**Comment by GwangsooHong** [comment]
Nope, I cannot go any further.

**Comment by klueska** [comment]
A new release of nvidia-docker was posted on Tuesday 19-May. Can you try the newest version and let us know if you are still having this issue.

**Comment by ryusukemomota** [comment]
I got the same message when I tried to run nvidia/cuda:10:.0-base nvidia-smi.
I could solve this problem just by downloading the latest Driver:
Driver Version:440.82
Release Date:Tue Apr 07, 2020
Operating System:Linux 64-bit
Good luck!

**Comment by gitTongzhen** [comment]
I solver the problem by the command:apt-get install -y nvidia-docker2

**Comment by puppeteer701** [comment]
> I solver the problem by the command:apt-get install -y nvidia-docker2

I am still facing this issue, even though I have installed nvidia-docker2.

Followed this instruction: https://developer.nvidia.com/blog/announcing-cuda-on-windows-subsystem-for-linux-2/

**Comment by macimovic** [comment]
Having the same issue on
Operating System: Cent OS 7
Driver version: 430.34
CUDA version: 10.1

Nvidia Container Runtime:
VERSION:
   1.0.0-rc8+dev
commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
spec: 1.0.1-dev

Docker:
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by elezar** [comment]
@macimovic looking at your NVIDIA container runtime version, it is pretty old. Would you be able to update this at all and see if the problem persists?
```
Nvidia Container Runtime:
VERSION:
1.0.0-rc8+dev
commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
spec: 1.0.1-dev
```
