### ISSUE TITLE
nvidia-modprobe is undocumented dependency

### ISSUE THREAD

**Issue by scpeters** [NVIDIA/nvidia-docker#125]
I spent some time debugging the `Could not load UVM kernel module` similar to #106, when I finally realized that `nvidia-modprobe` was not installed. The installation page does not state that is a dependency of `nvidia-docker`. That error message, could also ask whether you have `nvidia-modprobe` installed.

Before I update the wiki, I just wanted to confirm with the developers that my assessment is correct.

**Comment by scpeters** [comment]
Actually, I don't think I have permissions to edit the wiki, so I request that `nvidia-modprobe` be added to the list of prerequisites on the [Installation page](https://github.com/NVIDIA/nvidia-docker/wiki/Installation).

**Comment by flx42** [comment]
I updated the wiki, thanks for the report!
Unfortunately, we cannot make our packages depend on `nvidia-modprobe` since this binary can be installed using the `.run` file of the driver too.

**Comment by scpeters** [comment]
I think it's enough to make it clear in the installation instructions that they should have `nvidia-modprobe` in their system. Thanks!

**Comment by alexanderkjeldaas** [comment]
There's nothing in https://github.com/NVIDIA/nvidia-docker/wiki about `nvidia-modprobe`.

**Comment by flx42** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Installation#prerequisites

**Comment by opless** [comment]
nvidia-modprobe ought to be a dependency listed in the deb package.

**Comment by flx42** [comment]
@opless we can't, our drivers can be installed outside of the packaging system (e.g. with a `NVIDIA-[...].run` file)

**Comment by opless** [comment]
Might I humbly suggest that the post install hooks at least test for the executable (in the path, of course), and spit a warning out rather than an obscure message in syslog?

**Comment by flx42** [comment]
I guess we could, but it's not worth doing a new release just for that.

**Comment by opless** [comment]
Of course not! It's a ridiculously minor change.  :-)
