### ISSUE TITLE
Documentation issue specifying --gpus

### ISSUE THREAD

**Issue by Rytiss** [NVIDIA/nvidia-docker#1257]
### 1. Issue or feature description

Documentation on the use of `--gpus` flag at https://github.com/NVIDIA/nvidia-docker/wiki#i-have-multiple-gpu-devices-how-can-i-isolate-them-between-my-containers does not quote the parameters, resulting in an error:

`docker: Error response from daemon: cannot set both Count and DeviceIDs on device request.`

Documentation specifies:
`$ docker run --gpus device=2,3 nvidia/cuda:9.0-base nvidia-smi`

Should be:
`$ docker run --gpus '"device=2,3"' nvidia/cuda:9.0-base nvidia-smi`

The fix for the error was specified in #1026 yet the documentation wasn't updated.

**Comment by CT83** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki

Here as well. Someone give @Rytiss a 🏆

**Comment by GuillaumeLeclerc** [comment]
This issue has been here for a while and the documentation is still incorrect. I'm sure it is driving many people crazy.

**Comment by BruceDai003** [comment]
`docker run --gpus '"device=2,3"' nvidia/cuda:9.0-base nvidia-smi`
This command still fails for me:
`docker: Error response from daemon: cannot set both Count and DeviceIDs on device request.`

**Comment by andyneff** [comment]
- Still wrong in https://github.com/NVIDIA/nvidia-docker/wiki#i-have-multiple-gpu-devices-how-can-i-isolate-them-between-my-containers
- Still wrong in https://docs.docker.com/engine/reference/commandline/run/#access-an-nvidia-gpu which is where I go first
- Actually right in https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#gpu-enumeration , however when I read the "Note" I didn't realize the extra quotes were important, I only learned the different between `--runtime` and `--gpus` (although the 4 bullet below would have helped, had I read it)
