### ISSUE TITLE
nvidia:deepstream-l4t fails to execute sample deepstream-app in container

### ISSUE THREAD

**Issue by linux-devil** [NVIDIA/nvidia-docker#1261]
I pulled deepstream-l4t container on my jetson to run sample deepstream-app with sample configs . 
**It fails with error:**
`deepstream-app: error while loading shared libraries: libnvinfer.so.6: cannot open shared object file: No such file or directory`

Nvidia container : 
`nvcr.io/nvidia/deepstream-l4t:4.0.2-19.12-samples`

Kernel version :
`Linux jetson 4.9.140-tegra #1 SMP PREEMPT Wed Apr 8 18:10:49 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux`

Docker command : 
` sudo docker run -it --rm --net=host --runtime nvidia  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix nvcr.io/nvidia/deepstream-l4t:4.0.2-19.12-samples`

**Comment by oyange** [comment]
I had the same issue in deepstream-l4t:6.0.1.did you solve the problem?

root@user-desktop:/opt/nvidia/deepstream/deepstream-6.0# gst-inspect-1.0 nvinfer
(Argus) Error FileOperationFailed: Connecting to nvargus-daemon failed: No such file or directory (in src/rpc/socket/client/SocketClientDispatch.cpp, function openSocketConnection(), line 205)
(Argus) Error FileOperationFailed: Cannot create camera provider (in src/rpc/socket/client/SocketClientDispatch.cpp, function createCameraProvider(), line 106)

(gst-plugin-scanner:13): GStreamer-WARNING **: 07:28:06.762: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:13): GStreamer-WARNING **: 07:28:06.796: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_infer.so': libnvparsers.so.8: cannot open shared object file: No such file or directory

(gst-plugin-scanner:13): GStreamer-WARNING **: 07:28:06.802: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_osd.so': libnvinfer.so.8: cannot open shared object file: No such file or directory

(gst-plugin-scanner:13): GStreamer-WARNING **: 07:28:06.811: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferaudio.so': libcufft.so.10: cannot open shared object file: No such file or directory

(gst-plugin-scanner:13): GStreamer-WARNING **: 07:28:06.835: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_deepstream_bins.so': libnvparsers.so.8: cannot open shared object file: No such file or directory

(gst-plugin-scanner:13): GStreamer-WARNING **: 07:28:06.839: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory
No such element or plugin 'nvinfer'

**Comment by klueska** [comment]
This does not seem to be related to `nvidia-docker` itself, but rather some container running on top of it.

You'll probably have better luck posting here:
https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70
