### ISSUE TITLE
NVML: Not Supported

### ISSUE THREAD

**Issue by EagleFall** [NVIDIA/nvidia-docker#1263]
I'm trying to use NHOS 1.1.5, but when I start the process, there are three errors.

First:
device utilization rates error: nvml: not supported
module = mining

Second:
device fan speed error: error getfanspeedrpm
module = mining

Third:
devide power usage error: nvml: not supported
module = mining

I read some articles, right here, but I found no way to correct.

Is it possible to correct these errors?

**Comment by daryledesilva** [comment]
have the same error
https://github.com/nicehash/NHOS/issues/106

did you manage to resolve this @EagleFall
