### ISSUE TITLE
nvidia-docker error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: ...

### ISSUE THREAD

**Issue by ML6634** [NVIDIA/nvidia-docker#1264]
@RenaudWasTaken  @dualvtable @flx42

The output for

sudo docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

is

![image](https://user-images.githubusercontent.com/61134984/80853361-d1b88280-8bf5-11ea-940b-80db0d3ad7df.png)

sudo docker run --gpus 2 nvidia/cuda:10.0-base nvidia-smi

produces an error:

![image](https://user-images.githubusercontent.com/61134984/80853451-abdfad80-8bf6-11ea-84c4-3f8362b3590c.png)

How can I fix it? Thank you!

**Comment by nileshnegi** [comment]
Says unknown device id because you have only 1 GPU
`sudo docker run --gpus 1 nvidia/cuda:10.0-base nvidia-smi` should give you the same output as your first one

**Comment by ML6634** [comment]
@nileshnegi 
Thank you for the comment! I am going to use Docker and NVIDIA driver on laptop. May I ask whether having only 1 GPU might bother? If so, any possible solutions? Thank you again!

**Comment by nileshnegi** [comment]
Single GPU should not be an issue with nvidia-docker.

**Comment by ML6634** [comment]
Great! Thank you!

**Comment by ML6634** [comment]
@nileshnegi @flx42

Any idea for this issue? Thank you!

<pre>$ sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-latest
</pre>

produces:

<pre>docker: Error response from daemon: Unknown runtime specified nvidia.
See &apos;docker run --help&apos;.
</pre>

However,

<pre>$ sudo docker run --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cpu-latest
</pre>

produces:

<pre>2239212117f1860845c0cccee7af9cb95514c6e9b8c2fb2009fc23b7c0cd2079
</pre>

<pre>$ cat /etc/docker/daemon.json
</pre>
outputs:
<pre>cat: /etc/docker/daemon.json: No such file or directory
</pre>

===================================Info====================================

<pre>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
</pre>

<pre>$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
</pre>

<pre>$ nvidia-smi -a

==============NVSMI LOG==============

Timestamp                           : Sat May  9 12:23:36 2020
Driver Version                      : 440.33.01
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:06:00.0
    Product Name                    : GeForce MX250
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Enabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-b4b76e84-ca20-10a0-cbd1-f87b36c9809b
    Minor Number                    : 0
    VBIOS Version                   : 86.08.2D.00.60
    MultiGPU Board                  : No
    Board ID                        : 0x600
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization Mode         : None
        Host VGPU Mode              : N/A
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x06
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1D1310DE
        Bus Id                      : 00000000:06:00.0
        Sub System Id               : 0x86E2103C
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 4x
                Current             : 4x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 912000 KB/s
        Rx Throughput               : 5000 KB/s
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 4042 MiB
        Used                        : 305 MiB
        Free                        : 3737 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 3 MiB
        Free                        : 253 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 5 %
        Memory                      : 1 %
        Encoder                     : N/A
        Decoder                     : N/A
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending Page Blacklist      : N/A
    Temperature
        GPU Current Temp            : 48 C
        GPU Shutdown Temp           : 102 C
        GPU Slowdown Temp           : 97 C
        GPU Max Operating Temp      : 94 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 847 MHz
        SM                          : 847 MHz
        Memory                      : 3003 MHz
        Video                       : 784 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1911 MHz
        SM                          : 1911 MHz
        Memory                      : 3004 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1248
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 28 MiB
        Process ID                  : 1535
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 46 MiB
        Process ID                  : 2222
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 128 MiB
        Process ID                  : 2393
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 98 MiB
        Process ID                  : 2957
            Type                    : G
            Name                    : /usr/lib/firefox/firefox
            Used GPU Memory         : 1 MiB
</pre>

<pre>$ dpkg -l &apos;*nvidia*&apos;
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-===============================================
un  libgldispatch0-nvidia &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-cfg1-440:am 440.33.01-0ubun amd64           NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any    &lt;none&gt;          &lt;none&gt;          (no description available)
un  libnvidia-common      &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-common-440  440.33.01-0ubun all             Shared files used by the NVIDIA libraries
ii  libnvidia-compute-440 440.33.01-0ubun amd64           NVIDIA libcompute package
ii  libnvidia-container-t 1.0.7-1         amd64           NVIDIA container runtime library (command-line 
ii  libnvidia-container1: 1.0.7-1         amd64           NVIDIA container runtime library
un  libnvidia-decode      &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-decode-440: 440.33.01-0ubun amd64           NVIDIA Video Decoding runtime libraries
un  libnvidia-encode      &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-encode-440: 440.33.01-0ubun amd64           NVENC Video Encoding runtime library
un  libnvidia-fbc1        &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-fbc1-440:am 440.33.01-0ubun amd64           NVIDIA OpenGL-based Framebuffer Capture runtime
un  libnvidia-gl          &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-gl-440:amd6 440.33.01-0ubun amd64           NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and 
un  libnvidia-ifr1        &lt;none&gt;          &lt;none&gt;          (no description available)
ii  libnvidia-ifr1-440:am 440.33.01-0ubun amd64           NVIDIA OpenGL-based Inband Frame Readback runti
un  libnvidia-ml1         &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-304            &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-340            &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-384            &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-390            &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-common         &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-compute-utils- 440.33.01-0ubun amd64           NVIDIA compute utilities
un  nvidia-container-runt &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-container-runt &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-container-tool 1.0.5-1         amd64           NVIDIA container runtime hook
ii  nvidia-dkms-440       440.33.01-0ubun amd64           NVIDIA DKMS package
un  nvidia-dkms-kernel    &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-driver-440     440.33.01-0ubun amd64           NVIDIA driver metapackage
un  nvidia-driver-binary  &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-kernel-common  &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-kernel-common- 440.33.01-0ubun amd64           Shared files used with the kernel module
un  nvidia-kernel-source  &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-kernel-source- 440.33.01-0ubun amd64           NVIDIA kernel source package
un  nvidia-legacy-340xx-v &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-modprobe       440.33.01-0ubun amd64           Load the NVIDIA kernel driver and create device
un  nvidia-opencl-icd     &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-persistenced   &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-prime          0.8.8.2         all             Tools to enable NVIDIA&apos;s Prime
ii  nvidia-settings       440.33.01-0ubun amd64           Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binar &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-smi            &lt;none&gt;          &lt;none&gt;          (no description available)
un  nvidia-utils          &lt;none&gt;          &lt;none&gt;          (no description available)
ii  nvidia-utils-440      440.33.01-0ubun amd64           NVIDIA driver support binaries
un  nvidia-vdpau-driver   &lt;none&gt;          &lt;none&gt;          (no description available)
ii  xserver-xorg-video-nv 440.33.01-0ubun amd64           NVIDIA binary Xorg driver
</pre>

However, 
<pre>$ rpm -qa &apos;*nvidia*&apos;
</pre> has no output.

**Comment by ML6634** [comment]
Solved. See https://github.com/facebookresearch/wav2letter/issues/642.
