### ISSUE TITLE
How to install nvidia-docker without internet？

### ISSUE THREAD

**Issue by chenyu-zhai** [NVIDIA/nvidia-docker#1267]
Hello，I want to install the lastest version of nvidia-docker，and I have installed  docker.  
Because of some reasons, my computer can not visit github，so I want copy nvidia-docker files to that computer. 
but I do not know how to install it.  Please tell me how to install it in ubuntu16.04 with the download files.

thanks!

**Comment by ai-starter** [comment]
And I am a student，I know little about linux.
Please tell me the install process in detail. Thanks!
help me，I am doing my homework

I have already installed the  docker 19.03, I need the lastest nvidia-docker.

**Comment by ai-starter** [comment]
@RenaudWasTaken  sorry to trouble you

**Comment by parad0x-pdx** [comment]
check this docker image file [https://hub.docker.com/r/nvidia/container-toolkit](url)
 Running "docker pull nvidia/container-toolkit"  in your docker environment may solve your problem

**Comment by chenyu-zhai** [comment]
> check this docker image file [https://hub.docker.com/r/nvidia/container-toolkit](url)
> Running "docker pull nvidia/container-toolkit" in your docker environment may solve your problem

Thanks

**Comment by parad0x-pdx** [comment]
You're welcome..

> > check this docker image file [https://hub.docker.com/r/nvidia/container-toolkit](url)
> > Running "docker pull nvidia/container-toolkit" in your docker environment may solve your problem
> 
> Thanks

You're welcome
