### ISSUE TITLE
systemd is needed by nvidia-docker on RHEL 6

### ISSUE THREAD

**Issue by d13g0** [NVIDIA/nvidia-docker#127]

**Comment by d13g0** [comment]
I am following the steps to download and install nvidia-docker and when I run the rpm file, I get this error message:

```
rpm -i /tmp/nvidia-docker-1.0.0.rc.3-1.x86_64.rpm 
error: Failed dependencies:
	systemd is needed by nvidia-docker-1.0.0~rc.3-1.x86_64

```
however my system is RHEL6, so no systemd is available (I think?)

**Comment by flx42** [comment]
Docker only supports RHEL 7, I believe:
https://docs.docker.com/engine/installation/linux/rhel/

And yes, you can't get systemd on RHEL6 AFAIK.

If you still want to go down that path, you can try using our tarball:
https://github.com/NVIDIA/nvidia-docker#other-distributions
