### ISSUE TITLE
Modern distributions support

### ISSUE THREAD

**Issue by lig** [NVIDIA/nvidia-docker#1270]
I've searched for other issues and everything is closed. However, there is no information in the docs regarding the topic.

What is the state of support and action to install the toolkit on modern versions of popular distributions? Specifically: RHEL 8, Centos 8, Fedora (any?), Ubuntu 20.04 LTS.

**Comment by RenaudWasTaken** [comment]
Hi there!

This is already the case for all distributions you listed, except with Fedora which we don't support because CUDA doesn't support it.
Though I'm pretty sure you could use the centos repos for that :)

I'll make a note to update readmes and website page.

**Comment by RenaudWasTaken** [comment]
Updated the README in https://github.com/NVIDIA/nvidia-docker/commit/166fa7ffb23502da8f0b3364c92430d42d267f5b
