### ISSUE TITLE
nvidia-container-runtime  VS nvidia-container-toolkit

### ISSUE THREAD

**Issue by duhongle** [NVIDIA/nvidia-docker#1271]
Docker 19.03+
yum install  -y nvidia-container-runtime
yum install  -y nvidia-container-toolkit

Can you tell me the difference and connection between them?

**Comment by duhongle** [comment]
I hope there is an readme。。。

**Comment by klueska** [comment]
Please see my response here for some clarification:

https://github.com/NVIDIA/k8s-device-plugin/issues/168#issuecomment-625981223
