### ISSUE TITLE
deepstream-triton: unable to run with mount

### ISSUE THREAD

**Issue by cbasavaraj** [NVIDIA/nvidia-docker#1278]
```
sudo docker run -it -v ~/daisyfive:/opt/nvidia/deepstream/deepstream-5.0 nvcr.io/nvidia/deepstream:5.0-dp-20.04-triton
```
produces the error
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/nvidia/deepstream/deepstream-5.0/entrypoint.sh\": stat /opt/nvidia/deepstream/deepstream-5.0/entrypoint.sh: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
```

The same command without the mount part works fine:
```
sudo docker run -it nvcr.io/nvidia/deepstream:5.0-dp-20.04-triton
```

The container is from https://ngc.nvidia.com/catalog/containers/nvidia:deepstream. I also followed the instructions from https://docs.nvidia.com/metropolis/deepstream/dev-guide/index.html successfully and ran many of the non Triton sample apps.

I am on Ubuntu 18.04 on a Google Compute Engine instance, with Tesla T4 GPU and CUDA 10.2:
`NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2` and `Docker version 19.03.8, build afacb8b7f0`

Appreciate any help, thanks!

**Comment by umaagi** [comment]
Could you try with the  `--gpus all ` flag while starting up your docker container. This ensures that there is a GPU attached to your container. The second command works but you won't anyways be able to use any of the Deepstream apps since they need a GPU to run.

**Comment by cbasavaraj** [comment]
Thanks for the reply. I left out the `gpus` flag here as it was not the problem. Anyway, thanks to a reply on a different repo, I was able to solve the problem. The mistake was trying to mount to a path which already existed on the container: `/opt/nvidia/deepstream/deepstream-5.0`. Doing `-v ~/daisyfive:/home/daisyfive` instead worked.
