### ISSUE TITLE
CentOS 7 v Ubuntu 16

### ISSUE THREAD

**Issue by SCKelemen** [NVIDIA/nvidia-docker#128]
Caffe, DIGITS, and CUDA work on both distributions, correct? 

What would be the recommend starting distro, ubuntu or cent? This is my first time using docker, and I'm using it for training a CV network.

Thanks

**Comment by SCKelemen** [comment]
Awesome, thanks @flx42

**Comment by flx42** [comment]
But also remember than when using Docker your host OS can be anything supported by Docker.
