### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: device error: 1: unknown device\\\\n\\\"\"": unknown. ERRO[0001] error waiting for container: context canceled

### ISSUE THREAD

**Issue by tiexuedanxin** [NVIDIA/nvidia-docker#1283]
I use ubuntu16.04 and my docker version is 19.03.9, I followed the "https://github.com/NVIDIA/nvidia-docker" but after i run "sudo docker run --gpus 2 nvidia/cuda:10.0-base nvidia-smi", i get the following error. please help me.

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: device error: 1: unknown device\\\\n\\\"\"": unknown.
ERRO[0001] error waiting for container: context canceled

**Comment by klueska** [comment]
This error is usually consistent with you asking for more GPUs than you have available on your system.  Do you have at least 2 GPUs available on your machine?  If not, maybe try:

```
sudo docker run --gpus 1 nvidia/cuda:10.0-base nvidia-smi"
```

**Comment by tiexuedanxin** [comment]
thank you, i have know the reason why i come across the error, my computer only have one gpu.
