### ISSUE TITLE
I am a student of Tsinghua University. When I install, I use the following command starting with curl to report an error. I sincerely ask for the reason

### ISSUE THREAD

**Issue by xianglei3** [NVIDIA/nvidia-docker#1284]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
i use 
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

the error is:
gpdi@gpdi:~$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
gpdi@gpdi:~$ gpdi

Command 'gpdi' not found, did you mean:

  command 'ppdi' from deb cups-ppdc

Try: sudo apt install <deb name>

gpdi@gpdi:~$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
gpdi@gpdi:~$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
[sudo] gpdi 的密码： 
OK
gpdi@gpdi:~$ 
gpdi@gpdi:~$   attach      Attach local standard input, output, and error streams to a running container

Command 'attach' not found, did you mean:

  command 'attack' from deb ladr4-apps
  command 'sattach' from deb slurm-client

Try: sudo apt install <deb name>

gpdi@gpdi:~$   build       Build an image from a Dockerfile

Command 'build' not found, did you mean:

  command 'buildd' from deb buildd
  command 'sbuild' from deb sbuild
  command 'bwild' from deb bacula-director
  command 'pbuild' from deb pbuilder-scripts
  command 'guild' from deb guile-2.0-dev
  command 'guild' from deb guile-2.2-dev
  command 'xbuild' from deb mono-xbuild

Try: sudo apt install <deb name>

gpdi@gpdi:~$   commit      Create a new image from a container's changes
>   cp          Copy files/folders between a container and the local filesystem
>   create      Create a new container
>   deploy      Deploy a new stack or update an existing stack
>   diff        Inspect changes to files or directories on a container's filesystem
commit：未找到命令
gpdi@gpdi:~$   events      Get real time events from the server

Command 'events' not found, but can be installed with:

sudo apt install omnievents

gpdi@gpdi:~$   exec        Run a command in a running container
bash: exec: Run: 未找到
gpdi@gpdi:~$   export      Export a container's filesystem as a tar archive
>   history     Show the history of an image
>   images      List images
>   import      Import the contents from a tarball to create a filesystem image
>   info        Display system-wide information
>   inspect     Return low-level information on Docker objects
>   kill        Kill one or more running containers
>   load        Load an image from a tar archive or STDIN
>   login       Log in to a Docker registry
>   logout      Log out from a Docker registry
>   logs        Fetch the logs of a container
>   pause       Pause all processes within one or more containers
>   port        List port mappings or a specific mapping for the container
>   ps          List containers
>   pull        Pull an image or a repository from a registry
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by klueska** [comment]
`gpdi` looks like your username, not some command you should be running.

As such, this seems like a copy-paste error, not a bug in the instructions.
