### ISSUE TITLE
Centos 7 No key / missing

### ISSUE THREAD

**Issue by smogsy** [NVIDIA/nvidia-docker#1286]
so have been battling with this for quite some time. @RenaudWasTaken 
 however, i think there is in an issue with the GPGkeys. can you help? i think ive covered everything below

See below my testing

gpg gpgkey
```
pub  4096R/F796ECB0 2017-09-28 NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
sub  2048R/AC1160CD 2019-09-18 [expires: 2020-09-17]
```

```
sudo yumdownloader libnvidia-container-tools
```
```
sudo rpm --checksig libnvidia-container-tools-1.1.1-1.x86_64.rpm
```

```
libnvidia-container-tools-1.1.1-1.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#ac1160cd)`
```

```
rpm --import gpgkey
```

```
rpm --checksig libnvidia-container-tools-1.1.1-1.x86_64.rpm
libnvidia-container-tools-1.1.1-1.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#ac1160cd)
```

Doing 
sudo yum install libnvidia-container-tools

Key I'd missing AC1160CD

**Comment by RenaudWasTaken** [comment]
Published RPMs are signed with a subkey but the tooling in EL7 doesn't support validating with subkeys, only primary keys. See https://bugzilla.redhat.com/show_bug.cgi?id=1225133 .

RPM does not directly support verification of subkeys, it's not a feature Red Hat is ever going to implement for reasons (any features not present in GPGv3 causes rpm to fail verification). We rely on the yum repository metadata signing, which does support subkeys.

It is expected that RPMs not installed through the repo will show the issues you've described.

For a manual extra-paranoid process to double-confirm the signatures on the RPMs themselves, see /usr/lib/rpm/tgpg or https://github.com/rpm-software-management/rpm/blob/master/scripts/tgpg

The correct process is to install from the repo. Either the original repo or your own local clone of it.
