### ISSUE TITLE
Connect to remote nvidia-docker via --net=host

### ISSUE THREAD

**Issue by amacneil** [NVIDIA/nvidia-docker#129]
It's mildly annoying that to connect to a remote nvidia-docker daemon you need to also expose port 3476 from the host. This is difficult in environments where you don't have control over the firewall, or generally don't want to expose more ports.

One solution I came up with was to manually run curl inside a `--net=host` docker command first, to access the port running on localhost via the remote docker server.

```sh
$ docker run --net=host --rm appropriate/curl -s http://localhost:3476/v1.0/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_352.63:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0
```

My question is: why doesn't nvidia-docker do this (or something like it) automatically for remote docker hosts? It seems easier & more reliable than all the `NV_HOST` stuff.

**Comment by flx42** [comment]
@3XX0 want to answer this one?

**Comment by 3XX0** [comment]
I don't get it, you want `nvidia-docker` to implicitly launch a curl container just to talk to the `nvidia-docker-plugin`? 

If you don't want to expose more ports, you can use the SSH transport with `NV_HOST` (assuming that you are providing SSH access to the node)

**Comment by amacneil** [comment]
So the reasoning here is that I am running in an isolated CI environment, where the docker host is exposed over a unix socket, but I don't have any other ports available from the host. In this scenario it's nice to be able to fetch the nvidia-docker configuration without needing anything other than the existing docker socket. I can see why this is a fairly unique situation/setup, but on the other hand it's nice having a connection method which is 100% guaranteed to work with every docker setup.

**Comment by flx42** [comment]
I see, when I had to solve this problem internally, I just ran my Jenkins with `--net=host`. When you expose the Docker socket in a container, you can probably just give up about isolation, so you might as well go the easy way and expose everything.

**Comment by amacneil** [comment]
Yeah, agree that would make more sense. In this instance we are using a commercial CI system and while I have access to the docker socket (and can effectively control the host via it) I don't have the ability to run our "client" container with net=host.
