### ISSUE TITLE
Unclear driver installation instructions

### ISSUE THREAD

**Issue by jw3126** [NVIDIA/nvidia-docker#1291]
### 1. Issue or feature description
I am not sure, how to install the `cuda-driver`. The [FAQ](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-the-nvidia-driver) says:

> The recommended way is to use your [package manager](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#package-manager-installation) and install the cuda-drivers package (or equivalent).

AFAICT the [package manager](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#package-manager-installation) link in the FAQ points to the toolkit installation instructions, not the driver installation instructions?

**Comment by elezar** [comment]
The installation of the CUDA driver has been greatly simplified over the past years. See the instructions here https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64 for example. 

There are also other mechanisms that may be more applicable to your use case.
