### ISSUE TITLE
No docker compose Example

### ISSUE THREAD

**Issue by JohnBetaCode** [NVIDIA/nvidia-docker#1293]
The link to the docker compose example is gone

**Comment by PauloFavero** [comment]
It still missing :(

**Comment by PauloFavero** [comment]
If you are attempting to create a docker-compose with the Nvidia runtime see below:

You have to install nvidia-docker2 runtime and set the runtime to nvidia in you docker-compose.yml.

See these issues and wikis for more information.

[Support for NVIDIA GPUs under Docker Compose](https://github.com/docker/compose/issues/6691)
Runtime installation [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0))

Example:

```
version: "2.3"
services:
 my-container:
  runtime: nvidia
```

**Comment by opptimus** [comment]
@PauloFavero 
If I use the dokcer-nvidia-devel(not runtime):nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
How I should edit the docker-compose.yaml file?
