### ISSUE TITLE
HOW CAN I  limit  the GPU's MEMORY  

### ISSUE THREAD

**Issue by goodluck4s** [NVIDIA/nvidia-docker#1297]
I want to deploy a model by tensorflowServing+nvidia-docker on GPU  .
 HOW CAN I  limit  the GPU's MEMORY    .
cause it's tend to use all memory of GPU .
I want to limit the GPU memory used to below 5G (10G in total) .

**Comment by nvjmayo** [comment]
You can't do memory quotas or partitions without a [MIG supported card](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html)  (Tesla A100 or better). 

All containers come out of the same memory pool from the driver. This is an architectural limitation meaning there is not a way to reserve memory for a particular container.

For an individual application, you can limit how much your application allocates (as a fraction of total memory). There are settings in the [TF APIs for doing this](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth), please consult manuals or books on TF.
