### ISSUE TITLE
Best way to remotely deploy containers on EC2 with a mac book (OSX) without nvidia gpu?

### ISSUE THREAD

**Issue by stengoes** [NVIDIA/nvidia-docker#130]
I have a mac book pro with AMD Radeon R9 M370X 2048 MB GPU and OSX. Is it possible to use nvidia-docker to remotely deploy containers on Amazon EC2? 

Could I run a virtual machine with linux and install docker-machine and nvidia-docker on it? Or is that not possible since I don't have a nvidia gpu on my mac book?

My goal is to use TensorFlow with gpu support and I want to run multiple instances on EC2 to quickly test different neural network architectures. So I would like to use nvidia-docker to quickly and easily launch multiple gpu instances on EC2. 

Any advice for my situation is highly appreciated!

**Comment by flx42** [comment]
You won't be able to use nvidia-docker on a machine without a NVIDIA GPU.

However, you can totally use `docker-machine` to spawn EC2 GPU instances and then launch jobs directly from your terminal on your laptop, we actually have a tutorial for that:
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

Let me know if that helps.

**Comment by stengoes** [comment]
Thank you for the quick reply! I got it working now. 

I was actually following the tutorial, but i must have done something wrong. Since I could not get the final step to work. Then I got confused by this image: https://github.com/NVIDIA/nvidia-docker/wiki/images/nvidia-docker-remote.png, which seems to suggest that I should install nvidia-docker on my mac book. 

Anyways, I got it working now! Thank you.

**Comment by flx42** [comment]
Ah, yes, sorry for the confusion, we need to explain this image.

**Comment by nakosung** [comment]
So, can I use nvidia-docker remotely from my macbook? Do I need to build `nvidia-docker` manually?

**Comment by flx42** [comment]
@nakosung you can't use the `nvidia-docker` wrapper. But, as a workaround you can probably use `docker` and the CLI arguments manually (this is what `nvidia-docker` does). For instance, from the machine that has GPUs and `nvidia-docker-plugin` running:
```
$ curl -s http://localhost:3476/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_375.66:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia1 --device=/dev/nvidia0
```

**Comment by nakosung** [comment]
@fix42 How can I dump those parameters on remote machines? I think names of volumes and devices could be different for each machines. (I used to use docker-cli directly on remote machine using manual device mounts before nvidia-docker was born)

**Comment by flx42** [comment]
Through ssh for instance; a tunnel, or a direct command:
```
$ ARGS=$(ssh remotemachine curl -s http://localhost:3476/docker/cli)
$ echo $ARGS
--volume-driver=nvidia-docker --volume=nvidia_driver_375.41:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia3 --device=/dev/nvidia2 --device=/dev/nvidia1 --device=/dev/nvidia0
```

**Comment by nakosung** [comment]
Great! Thanks

**Comment by ahoereth** [comment]
I wrote a short script which mocks nvidia-docker for when connected to a remote host.

After starting the remote instance using docker-machine set some variables:

```bash
eval $(docker-machine env $1)
export NV_HOST="ssh://ubuntu@$(docker-machine ip $1):"
export NV_ARGS=$(docker-machine ssh $1 curl -s http://localhost:3476/docker/cli)
ssh-add $DOCKER_CERT_PATH/id_rsa
```

Then use the following script just like you would use the `nvidia-docker` command:

```bash
#!/bin/bash
if type nvidia-docker >/dev/null 2>&1; then
  # nvidia-docker installed, use it directly.
  nvidia-docker $@
elif [ -z "$NV_ARGS" ]; then
  # $NV_ARGS is not set, cannot mock nvidia-docker without it.
  echo "# \$NV_ARGS env variable required to mock nvidia-docker. Settable using e.g."
  echo "export NV_ARGS=\$(docker-machine ssh \$1 curl -s http://localhost:3476/docker/cli)"
elif [ "$#" -gt "1" ] && [ "$1" -ne "run" ]; then
  # Got run command with some args, add NV_ARGS and use it with docker.
  shift 1  # Drop first arg from $@.
  docker run $NV_ARGS $@
else
  # Every other time, just fall back to using docker.
  docker $@
fi
```

https://github.com/ahoereth/dot/commit/7db0951
