### ISSUE TITLE
Latest Docker images missing cicc

### ISSUE THREAD

**Issue by dylon** [NVIDIA/nvidia-docker#1308]
While building a container, I need to compile a CUDA kernel and am using CMake for the task, but CMake fails with the following error about nvcc not being able to find cicc.   The issue seems directly related to #1024 but that issue was closed and hasn't been reopened since the issue was rediscovered back in April.  Is there an apt repo somewhere that I can add to install the `cuda-nvcc` package?

```
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/SLUG-n9BPWzfYnP/SLUG/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_c3f14/fast"
    /usr/bin/make -f CMakeFiles/cmTC_c3f14.dir/build.make CMakeFiles/cmTC_c3f14.dir/build
    make[1]: Entering directory '/tmp/SLUG-n9BPWzfYnP/SLUG/build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_c3f14.dir/main.cu.o
    /usr/local/cuda/bin/nvcc     -x cu -c /tmp/SLUG-n9BPWzfYnP/SLUG/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_c3f14.dir/main.cu.o
    sh: 1: cicc: not found
    CMakeFiles/cmTC_c3f14.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_c3f14.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_c3f14.dir/main.cu.o] Error 127
    make[1]: Leaving directory '/tmp/SLUG-n9BPWzfYnP/SLUG/build/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_c3f14/fast' failed
    make: *** [cmTC_c3f14/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  src/nvdsinfer_custom_impl_Yolo/CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by dylon** [comment]
The latest deepstream images are also missing many of the deepstream libraries (e.g. libnvinfer.so*) and the headers for building custom DeepStream plugins.

**Comment by dylon** [comment]
My bug report was filed for a Xavier.  I didn't mention that because I didn't realized it was relevant, but the containers served to my Nano do not seem to suffer from the same issues.  They seem to be complete.  Are different images served to Xavier than Nano?

**Comment by dylon** [comment]
Also, it would be immensely helpful if you would provide us with an Apt repository containing the DeepStream- and L4T-related packages, especially considering I can no longer search for them in the Developer network.

**Comment by karl-schulz** [comment]
I have the same issue when building jetson-inference (https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-repo-2.md)

I think cicc is also missing on the host L4T, so copying it to the container is not a solution.

**Comment by dylon** [comment]
May we have an update on this?  It's been three weeks without a reply.

**Comment by dylon** [comment]
It has been another week, may we have an update please?

**Comment by klueska** [comment]
Sorry for the late reply. This fell through the cracks because it doesn't seem to be an issue with `nvidia-docker` itself (but rather with one of the NVIDIA images running on top of `nvidia-docker`).

If you're having an issue with one docker images provided by NVIDIA, you should file an issue here:
https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/
