### ISSUE TITLE
nvidma-repo problem

### ISSUE THREAD

**Issue by dbdocker** [NVIDIA/nvidia-docker#1309]
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo 
# Unsupported distribution! # Check https://nvidia.github.io/nvidia-docker

And I go to curl alone, the address is empty, please check it

**Comment by klueska** [comment]
Did you set `$distribution` as indicated in the instructions on the line just before the curl command?

**Comment by ethanhs** [comment]
If I try `https://nvidia.github.io/nvidia-docker/ubuntu20.04/` I still get the above error. The install instructions reference some `$ID$VERSION_ID`, but there is no mention of what these should be set to.

**Comment by dbdocker** [comment]
My system is CENTOS. According to the CENTOS method on the official website, it is not advisable. It shows verification error and PGK is also empty and cannot be deleted



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ethan Smith"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 下午2:04
收件人:&nbsp;"NVIDIA/nvidia-docker"<nvidia-docker@noreply.github.com&gt;;
抄送:&nbsp;"念丶"<2953137007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NVIDIA/nvidia-docker] nvidma-repo problem (#1309)





 
If I try https://nvidia.github.io/nvidia-docker/ubuntu20.04/ I still get the above error. When I run the commands in the README verbatim, I get lines like https://nvidia.github.io/nvidia-docker/ubuntu20.04/${ARCH} in the sources.list, which seems wrong?

**Comment by nvjmayo** [comment]
I believe you have made an error. You should not have *ubuntu20.04* in your request if you are using *centos*

* Go to https://nvidia.github.io/nvidia-docker/
* read the directions for "RHEL-based distributions"
```sh
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | \
  sudo tee /etc/yum.repos.d/nvidia-docker.repo
```
* continue following instructions for RHEL based distributions. This is required to get keys (gpg) to work.
