### ISSUE TITLE
libnvidia-container-tools >= 1.1.1 for package: nvidia-container-toolkit-1.1.2-2.amzn2.x86_64

### ISSUE THREAD

**Issue by x86nick** [NVIDIA/nvidia-docker#1310]
Getting dependency error:
Processing Dependency: nvidia-container-toolkit >= 1.1.0 for package: nvidia-container-runtime-3.2.0-1.x86_64

 nvidia-container-toolkit >= 1.1.0  is not available in nvidia pkg repo.
-----
OS 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
-----

 $uname -a
Linux ip-10-110-106-155.vpc.internal 4.14.181-140.257.amzn2.x86_64 #1 SMP Wed May 27 02:17:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Docker version
 19.03.6-ce

====
yum search --showduplicates nvidia-container-toolkit
nvidia-container-toolkit-1.0.5-2.amzn2.x86_64 : NVIDIA container runtime hook
======

**Comment by klueska** [comment]
Can you try again? It’s definitely there, but we were resyncing the repos earlier today and you might have hit a glitch because of it.

**Comment by jweber-mimsoftware** [comment]
I'm running into the same (or similar sounding) issue trying to install `nvidia-docker-container` or `nvidia-docker2` on Amazon Linux 2 (p2.xlarge if that matters):

```
==> amazon-ebs: Error: Package: nvidia-container-toolkit-1.1.2-2.amzn2.x86_64 (nvidia-container-runtime)
==> amazon-ebs:            Requires: libnvidia-container-tools >= 1.1.1
==> amazon-ebs:            Installing: libnvidia-container-tools-1.0.0-1.amzn2.x86_64 (amzn2-graphics)
==> amazon-ebs:                libnvidia-container-tools = 1.0.0-1.amzn2
```

**Comment by ewertonsilveira** [comment]
Same here!

```
[root@ip-10-1-15-92 ec2-user]# yum uninstall libnvidia-container1-1.1.1-1.x86_64
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
No such command: uninstall. Please use /bin/yum --help
[root@ip-10-1-15-92 ec2-user]# yum remove libnvidia-container1-1.1.1-1.x86_64
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
Repository libnvidia-container is listed more than once in the configuration
Repository libnvidia-container-experimental is listed more than once in the configuration
No Match for argument: libnvidia-container1-1.1.1-1.x86_64
No Packages marked for removal
[root@ip-10-1-15-92 ec2-user]# make {ubuntu18.04, ubuntu16.04, debian10, debian9, centos7, amazonlinux1, amazonlinux2, opensuse-leap15.1}
make: *** No rule to make target `{ubuntu18.04,'.  Stop.
[root@ip-10-1-15-92 ec2-user]# make docker
make: *** No rule to make target `docker'.  Stop.
[root@ip-10-1-15-92 ec2-user]# make install
make: *** No rule to make target `install'.  Stop.
[root@ip-10-1-15-92 ec2-user]# sudo yum install nvidia-container-runtime
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
Repository libnvidia-container is listed more than once in the configuration
Repository libnvidia-container-experimental is listed more than once in the configuration
24 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package nvidia-container-runtime.x86_64 0:3.2.0-1 will be installed
--> Processing Dependency: nvidia-container-toolkit < 2.0.0 for package: nvidia-container-runtime-3.2.0-1.x86_64
--> Processing Dependency: nvidia-container-toolkit >= 1.1.0 for package: nvidia-container-runtime-3.2.0-1.x86_64
--> Running transaction check
---> Package nvidia-container-toolkit.x86_64 0:1.1.2-2.amzn2 will be installed
--> Processing Dependency: libnvidia-container-tools >= 1.1.1 for package: nvidia-container-toolkit-1.1.2-2.amzn2.x86_64
--> Finished Dependency Resolution
Error: Package: nvidia-container-toolkit-1.1.2-2.amzn2.x86_64 (nvidia-container-runtime)
           Requires: libnvidia-container-tools >= 1.1.1
           Installed: libnvidia-container-tools-1.0.0-1.amzn2.x86_64 (@amzn2-graphics)
               libnvidia-container-tools = 1.0.0-1.amzn2
```

Linux ip-10-1-15-92 4.14.181-140.257.amzn2.x86_64 #1 SMP Wed May 27 02:17:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klueska** [comment]
Sorry for the delayed reply.

It seems that your system is pulling libraries from a yum repository called `@amzn2-graphics` that has higher priority over the nvidia repos.

The latest `libnvidia-container-tools` library available from the nvidia repos is, in fact, `1.1.1` and can be seen here:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/amzn2/x86_64/

I'm not sure what all is included in the `@amzn2-graphics` repo (and if you need it at all), but you will need to force the install of `libnvidia-container-tools` and `libnvidia-container1` from the nvidia repos in order to run the latest version of `nvidia-docker`.

Otherwise, you can downgrade to `nvidia-docker` version `2.2.2` and that should fix your problem as well.

**Comment by tomercagan** [comment]
Thanks for the suggestion.
On amazon linux 2 - the following did the trick

`sudo yum-config-manager --disable amzn2-graphics`

Then I could install the container tools and get the nvidia-smi from a container.

I guess you should enable the amzn2-graphics back using

`sudo yum-config-manager --enable amzn2-graphics`

**Comment by opptimus** [comment]
> force the install of `libnvidia-container-tools` and `libnvidia-container`

@klueska 
How force the install libnvidia-container-tools and libnvidia-container？
How should I type the command?

**Comment by klueska** [comment]
Just specify their versions explicitly, i.e. on amazon linux (for the latest packages) this would be:
```
yum install -y libnvidia-container1-1.3.1-1
yum install -y libnvidia-container-tools-1.3.1-1
yum install -y nvidia-container-toolkit-1.4.0-2
```
