### ISSUE TITLE
Windows guest container support

### ISSUE THREAD

**Issue by gunan** [NVIDIA/nvidia-docker#1317]
While Linux containers on windows are now starting to be supported through WSL, using windows on windows containers do not seem to be supported yet.
Any plans or updates?

**Comment by nvjmayo** [comment]
there has been no announcement at this time.

**Comment by lefnire** [comment]
Is it not related to this? https://blogs.windows.com/windowsdeveloper/2020/06/17/gpu-accelerated-ml-training-inside-the-windows-subsystem-for-linux/

Instructions: https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl

**Comment by gunan** [comment]
Unfortunately, that enables running linux containers on a windows machine.
What I need is to be able to run windows containers., without touching WSL at all, using docker for windows.
