### ISSUE TITLE
Wiki: simpler test case than `make samples`

### ISSUE THREAD

**Issue by scpeters** [NVIDIA/nvidia-docker#132]
The first recommendation in the `Getting Started` section on the wiki is [Testing the samples](https://github.com/NVIDIA/nvidia-docker/wiki/Testing-the-samples), which recommends cloning this repository and running `make samples`. I've found a simpler test case for confirming that everything is working properly, which I'll describe after a few comments about installation.

In my experience installing on Ubuntu trusty, I `dpkg -i` the deb from the [release page](https://github.com/NVIDIA/nvidia-docker/releases), then reboot. After reboot, I can confirm that the service started by looking at the upstart logs in `/var/log/upstart/nvidia-docker.log` and running a `curl -s http://localhost:3476/docker/cli`, but it's a little confusing because `nvidia-docker` doesn't yet show up as a Volume plugin in `docker info`, and the nvidia driver volume hasn't yet been created. I've found the following command to be sufficient to get the volume created and mounted:

~~~
docker run --rm -it \
    $(curl -s http://localhost:3476/docker/cli) \
    --privileged \
    ubuntu:trusty \
    /bin/bash
~~~

This runs the base `ubuntu:trusty` image and mounts the nvidia drivers to `/usr/local/nvidia`. Running the following commands should execute `nvidia-smi` successfully:

~~~
export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
/usr/local/nvidia/bin/nvidia-smi
~~~

This seems like an easier test case than asking people to `git clone` and `make samples` and doesn't pull a bunch of extra images. Would you consider adding it to the wiki in the getting started section?

As an aside, I tried tinkering with the `nvidia-docker` command, assuming that it would eliminate the need for `curl`ing the command-line arguments, but the volume doesn't get mounted with the following command, even if it already exists:

~~~
nvidia-docker run --rm -it \
    --privileged \
    ubuntu:trusty \
    /bin/bash
~~~

**Comment by flx42** [comment]
Running the samples is actually the second step of testing, the test that really matters is checking whether nvidia-smi works fine in a container, as mentioned in the `Quick start` section:
https://github.com/NVIDIA/nvidia-docker#quick-start

> In my experience installing on Ubuntu trusty, I dpkg -i the deb from the release page, then reboot

You shouldn't need to reboot your machine.

>I've found the following command to be sufficient to get the volume created and mounted:

You don't need that, just use `nvidia-docker run --rm nvidia/cuda nvidia-smi`.

> This seems like an easier test case than asking people to git clone and make samples and doesn't pull a bunch of extra images. 

Samples are optional, really. So it's not needed.

> As an aside, I tried tinkering with the nvidia-docker command, assuming that it would eliminate the need for curling the command-line arguments, but the volume doesn't get mounted with the following command, even if it already exists:

Sure, because if the image you use is not a CUDA image, you `nvidia-docker` won't mount the devices and volumes.
Also, you don't need to use `--privileged`

**Comment by ruffsl** [comment]
> As an aside, I tried tinkering with the nvidia-docker command, assuming that it would eliminate the need for curling the command-line arguments, but the volume doesn't get mounted with the following command, even if it already exists:

Perhaps more specifically, this is due to missing the necessary labels in the stock image used: 
https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection

**Comment by scpeters** [comment]
Can you put the `quick-start` instructions on the wiki? I ended up clicking over to the installation page to see the system requirements, and there's only `Getting started` there.

I agree that `nvidia-docker run --rm nvidia/cuda nvidia-smi`, but I like the idea of an example that shows how to mount the nvidia volume onto an image that isn't based off of `nvidia/cuda`.

**Comment by flx42** [comment]
> Can you put the quick-start instructions on the wiki? I ended up clicking over to the installation page to see the system requirements, and there's only Getting started there.

I removed the `Getting started` section and move its subsections to `Advanced topics`, hopefully it will be clearer now.

> I agree that nvidia-docker run --rm nvidia/cuda nvidia-smi is more compact, but I like the idea of an example that shows how to mount the nvidia volume onto an image that isn't based off of nvidia/cuda.

We already have some material about this in our [Internals](https://github.com/NVIDIA/nvidia-docker/wiki/Internals) section.

**Comment by scpeters** [comment]
Is it still possible to put at least a link to the `Quick start` section on the wiki? It never occurred to me to go back to the `Readme` after entering the wiki, so I never found that content when I was looking for it.

**Comment by flx42** [comment]
It's actually on the Home page of the wiki.

**Comment by scpeters** [comment]
True, I see it now that you mention it. On my laptop, I had to scroll down to see it though, and it's not listed in the table of contents thing on the right side of every wiki page.

I think the `Quick start` instructions should be easier to find. My other co-worker who is just installed `nvidia-docker` didn't see the `Quick start` instructions either. Maybe move quick start to the top of the wiki home page and add a dedicated page so it shows up in the table of contents?

**Comment by flx42** [comment]
Do you think it's better now?

**Comment by scpeters** [comment]
That is great! Thanks!
