### ISSUE TITLE
nvcc is missing in the latest docker images

### ISSUE THREAD

**Issue by kracwarlock** [NVIDIA/nvidia-docker#1322]
Trying to build this dockerfile:
```
FROM nvidia/cuda:10.2-devel-ubuntu18.04

RUN nvcc --version
```
results in:
```
/bin/sh: 1: nvcc: not found
```

Am I doing something wrong or the images are not built correctly?

**Comment by kracwarlock** [comment]
I just found the repository for container images and this seems to be an open issue there as well: https://gitlab.com/nvidia/container-images/cuda/-/issues/71

**Comment by dafrenchyman** [comment]
I'm running into this exact same issue

**Comment by kracwarlock** [comment]
seems to be fixed by the latest update
