### ISSUE TITLE
File has unexpected size

### ISSUE THREAD

**Issue by hash-rabbit** [NVIDIA/nvidia-docker#1328]
when i 
`apt-get update `
it shows 
```
Err:12 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Packages
  File has unexpected size (32924 != 38727). Mirror sync in progress? [IP: 61.147.234.131 443]
  Hashes of expected file:
   - Filesize:38727 [weak]
   - SHA256:95fed63a913caa0e383c61a518cbd554cfd8b593251eca07f004b8afd894d959
   - SHA1:ef946791bf29f350ad12d1a4e68d578ea2d89cd1 [weak]
   - MD5Sum:33c6dadca2bfdb310ba05f654b9931ca [weak]
  Release file created at: Wed, 17 Jun 2020 21:47:53 +0000
Fetched 1397 B in 12s (121 B/s) 
Reading package lists... Done
E: Failed to fetch https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (32924 != 38727). Mirror sync in progress? [IP: 61.147.234.131 443]
   Hashes of expected file:
    - Filesize:38727 [weak]
    - SHA256:95fed63a913caa0e383c61a518cbd554cfd8b593251eca07f004b8afd894d959
    - SHA1:ef946791bf29f350ad12d1a4e68d578ea2d89cd1 [weak]
    - MD5Sum:33c6dadca2bfdb310ba05f654b9931ca [weak]
   Release file created at: Wed, 17 Jun 2020 21:47:53 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by klueska** [comment]
Is this still occurring after waiting a few minutes?

**Comment by nvjmayo** [comment]
Issue #1326 also reports problems with repo's Release and Package.gz files.

**Comment by didibaba** [comment]
Also got the same problem.

**Comment by elve960520** [comment]
> Is this still occurring after waiting a few minutes?

I have trying some times by the past 72hours
nothing changed

**Comment by heliarmk** [comment]
Any thing change ?

**Comment by leedrake5** [comment]
Having this problem all day today. Sample of the code dump below

'''E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnvidia-cfg1-450_450.172.01-0ubuntu1_amd64.deb  File has unexpected size (75272 != 75270). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - SHA512:8bcd8e083dcfee2c5b71b28b48c38dd1fc8445fa54ba78ca23b41b12b639a61cbfbc3af9612fda573e5a9016d1bcd32b5fa2006b8b5239720fea36b19c33889d
    - SHA256:56b0f33f1c7ef12efce815e8212d5751e96946d3cba444928e259544867c544e
    - SHA1:2bd96188621665c13b943878d1160d38557ac248 [weak]
    - MD5Sum:ff0c545fcd810c28a76e3857459a449b [weak]
    - Filesize:75270 [weak]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./xserver-xorg-video-nvidia-450_450.172.01-0ubuntu1_amd64.deb  File has unexpected size (1533250 != 1533248). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - SHA512:50d03c7fa0c065a7c4282eb984041623be09c4bf9b47c03e6d3836622f8d5e9f9f731660b740994c1f28f6d6bff3f39a5d2fea77d638d6f93e7b7a1bf9c0ee26
    - SHA256:f801c162488481041c0cdcd0ed69ba9250823e1b1c06ed9fa18050a5d29f4a75
    - SHA1:f603a68ffec37b66f41699480a09be336a89842e [weak]
    - MD5Sum:9ad19279bb77e39eab5c26e7d60623a8 [weak]
    - Filesize:1533248 [weak]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./nvidia-driver-450_450.172.01-0ubuntu1_amd64.deb  File has unexpected size (421342 != 421340). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - SHA512:31df8efcae36919230b38497c10c8cb7b002ca429054cb2e0c29b82f18b86137c81d68848aa698c5e33a4937f80e574105324927a3c18bb548774dc2d189ccb1
    - SHA256:a0a4e61313b5a7e4bd65cd2118734bf02aa5218f2a3ef3b42c87aa021b7ecffd
    - SHA1:113d860d6da94671423bf2d1b21e4daa6c8e2c17 [weak]
    - MD5Sum:68c80981b15875eb76512f8e2d96a4c5 [weak]
    - Filesize:421340 [weak]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./nvidia-modprobe_510.47.03-0ubuntu1_amd64.deb  File has unexpected size (19802 != 19798). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - SHA512:cc56f27f06d636626d70976c36d8d064990d7d6d7e17f3a8533ed86849fb43acf19c9b38a349667e55dd01e144637f0ea8bcfffabb33b280fd7c9935440ce616
    - SHA256:f26231377ac0f250e9718609f0e360399991f16a5a45131e205b41bf5d16778a
    - SHA1:af5569467c9298cfe0bb1a69b6608e8a872077dd [weak]
    - MD5Sum:ec74f11420daeb0442d266792bff29fc [weak]
    - Filesize:19798 [weak]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./nvidia-settings_510.47.03-0ubuntu1_amd64.deb  File has unexpected size (893670 != 893668). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - SHA512:c54667544235f3342527d1192c8899343cfae1b942394078cda60881bcd17b5927020b85279bd3c68ad4939e1738e08c6c3346d3f7be98ade1d72007df040e43
    - SHA256:ff5e5d25fa3c4e1b40768352b35bd392cc68bd95fedfb6961465be8a3ef46f6a
    - SHA1:082254299c70f2224ddffaa3cca4506e4e8b2f07 [weak]
    - MD5Sum:eba37f44334d0788f30b135f06ca7fea [weak]
    - Filesize:893668 [weak]
E: Aborting install.
'''

**Comment by leedrake5** [comment]
NVM, got caught in a key rotation. Here's what worked for me (up to date as of July 2022:

```wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
sudo apt-get -y install cuda```

**Comment by elezar** [comment]
Note that this was most likely an intermittent failure against the CUDA Downloads repository and not specific to the NVIDIA Container Toolkit.

If you're still having problems, please open a new issue against https://github.com/NVIDIA/nvidia-container-toolkit.
