### ISSUE TITLE
Docker For Windows vs WSL Docker

### ISSUE THREAD

**Issue by turowicz** [NVIDIA/nvidia-docker#1329]
With WSL2 getting CUDA support from NVIDIA it seems that we are currently constrained to using the docker inside a WSL VM. 

Would it be possible to have the "Docker For Windows" service used inside the WSL rather than installing a separate docker inside WSL?

I know that this is possible in the non-CUDA scenarios.

**Comment by jlidgard** [comment]
@jlidgard subscribing, also interested!

**Comment by turowicz** [comment]
How is that completed @elezar? Care to share any links?
