### ISSUE TITLE
Possible to run CUDA 11 containers on CUDA 10.2 host?

### ISSUE THREAD

**Issue by jonghwanhyeon** [NVIDIA/nvidia-docker#1332]
I installed nvidia-container-toolkit on my host computer with CUDA 10.2. 
In this situation, is it possible to run CUDA 11 containers on that host?

**Comment by chrisadas** [comment]
I think the CUDA version support in containers depend on nvidia driver version on the host, not the CUDA version on the host. (In fact, you don't need CUDA on the host at all)

For CUDA 11 in containers, you need nvidia driver >= 450
