### ISSUE TITLE
"nvidia-container-runtime-hook": executable file not found in $PATH

### ISSUE THREAD

**Issue by krannnn** [NVIDIA/nvidia-docker#1337]
Hello, I'm having this issue after upgrading from docker 18 to 19.03.12 when running any container :
Command:
```docker run --name gpu_container --gpus all nvidia/cuda ```
Error:
```
docker: Error response from daemon: exec: "nvidia-container-runtime-hook": executable file not found in $PATH.
ERRO[0000] error waiting for container: context canceled
```
I've renamed ```nvidia-container-runtime-hook``` to ```nvidia-container-toolkit``` as this is now the package new users are expected to install

What can I do about this?

**Comment by ABlueLight** [comment]
reference this 
[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker](url)

**Comment by chenjiao0123** [comment]
Have you been solved this issue? Because I melt the same problem with you, could you help me, please? Thanks very much.

**Comment by klueska** [comment]
What versions of the following packages do you have installed?:
```
libnvidia-container1
libnvidia-container-tools
nvidia-container-toolkit
nvidia-container-runtime
nvidia-docker2
```

Also, what OS / arch are you running on?

The package that used to install a binary called `nvidia-container-runtime-hook` has been EOL for over a year.

**Comment by chenjiao0123** [comment]
> What versions of the following packages do you have installed?:
> 
> ```
> libnvidia-container1
> libnvidia-container-tools
> nvidia-container-toolkit
> nvidia-container-runtime
> nvidia-docker2
> ```
> 
> Also, what OS / arch are you running on?
> 
> The package that used to install a binary called `nvidia-container-runtime-hook` has been EOL for over a year.

About 3 month ago, the docker is normal, but recently the issue occured and I don't do anything about it.
The running system is Ubuntu 18.04.3 LTS.

**Comment by theicfire** [comment]
`apt install nvidia-docker2` fixed this for me. Without it, I was also getting the `"nvidia-container-runtime-hook"` error. More details in https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

**Comment by elezar** [comment]
Please see the updated [installation documenation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) and create an issue against https://github.com/NVIDIA/nvidia-container-toolkit if there are still problems.
