### ISSUE TITLE
it's possbile to run multi gpu accelerate opengl application on gpus at same time?

### ISSUE THREAD

**Issue by pampanelson** [NVIDIA/nvidia-docker#1338]
I've managed to run a gpu accelerate application in docker by nvidia-tool-kit in a headless server.

1.start docker like this:
docker run --gpus device='"0"'  --rm --privileged --name gpu0_vulkan -it -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/mnt -v $(pwd)/xorg.conf.01:/etc/X11/xorg.conf opengl_vulkan_16.04_custom_0 bash

2.start application inside docker like this:
Xorg :1 & DISPLAY=:1 application (like glxinfo or vulkaninfo)

but I can run only one application on one gpu at a time, if I started another docker by specify another gpu and run an application , the output of nvidia-smi shows only one gpu is busing , if run unity built vulkan application will crash even.

Is possible to run multi direct render application on seperate gpu at same time? help needed.

Thanks

**Comment by kimown** [comment]
I have same problem, How do you generate file `$(pwd)/xorg.conf.01`?
