### ISSUE TITLE
Can't install dep package

### ISSUE THREAD

**Issue by soichih** [NVIDIA/nvidia-docker#134]
I have cudatoolkit and docker installed on my machine running Ubuntu 16.04

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

When I try to install nvidia-docker deb package, I get following error message.

```
$ sudo dpkg -i nvidia-docker_1.0.0.rc.3-1_amd64.deb 
(Reading database ... 374353 files and directories currently installed.)
Preparing to unpack nvidia-docker_1.0.0.rc.3-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0~rc.3-1) over (1.0.0~rc.3-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on docker-engine (>= 1.9.0); however:
  Package docker-engine is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 nvidia-docker
```

Docker is installed and running my other containers properly.

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64
```

Am I using the right package?

**Comment by 3XX0** [comment]
You need to install the official [Docker package](https://docs.docker.com/engine/installation/linux/ubuntulinux/) instead of the one shipped with Ubuntu

**Comment by soichih** [comment]
Thanks. It worked!

**Comment by soumenms2015** [comment]
Hello I am getting same error like above.

my docker version is:
(cv) soumen@soumen-Lenovo-Flex-2-15:~$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by flx42** [comment]
See #323

**Comment by monajalal** [comment]
Check our tutorial here. What @3XX0 said is correct
https://confluence.nvidia.com/display/NXP/Creating+an+NVIDIA+Docker
