### ISSUE TITLE
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (213860 != 185496)

### ISSUE THREAD

**Issue by gandroz** [NVIDIA/nvidia-docker#1343]
**1. Issue description**

In nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 I get the error:

Step 1/15 : FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 as base
10.1-cudnn7-runtime-ubuntu18.04: Pulling from nvidia/cuda
7ddbc47eeb70: Already exists 
c1bbdc448b72: Already exists 
8c3b70e39044: Already exists 
45d437916d57: Already exists 
d8f1569ddae6: Already exists 
85386706b020: Already exists 
ee9b457b77d0: Already exists 
be4f3343ecd3: Already exists 
51f6bbaddf34: Pull complete 
Digest: sha256:963696628c9a0d27e9e5c11c5a588698ea22eeaf138cc9bff5368c189ff79968
Status: Downloaded newer image for nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
 ---> e135227729c4
Step 2/15 : ARG BRANCH
 ---> Running in 587ffc7ac0f1
Removing intermediate container 587ffc7ac0f1
 ---> d535b6b4531d
Step 3/15 : ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
 ---> Running in b53d25042d11
Removing intermediate container b53d25042d11
 ---> 31d7f259a203
Step 4/15 : ENV FORCE_CUDA=1
 ---> Running in 5cb13c9bc552
Removing intermediate container 5cb13c9bc552
 ---> ae6e76c8255a
Step 5/15 : ENV PATH /opt/conda/bin:$PATH
 ---> Running in b6a73b911776
Removing intermediate container b6a73b911776
 ---> eed35d589f50
Step 6/15 : ENV TORCH_CUDA_ARCH_LIST  "6.0 6.1 7.2+PTX 7.5+PTX"
 ---> Running in a0064ff4325d
Removing intermediate container a0064ff4325d
 ---> aebea41002f9
Step 7/15 : RUN apt-get update --fix-missing && apt-get install -y --no-install-recommends wget bzip2 ca-certificates     libglib2.0-0 libxext6 libsm6 libxrender1     git mercurial subversion build-essential
 ---> Running in f3ad3de52931
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Get:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Ign:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [41.2 kB]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [185 kB]
Err:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
  File has unexpected size (213860 != 185496). Mirror sync in progress? [IP: 152.195.19.142 443]
  Hashes of expected file:
   - Filesize:185496 [weak]
   - SHA256:f7e866fdb738e4bda095feb338ba61fc8150f584fb4ab1b39a025f58c0e01932
   - SHA1:4462a72d5e4952c9cb747af9678d0a1d85857837 [weak]
   - MD5Sum:4be0b5ad7f6bbec51557955b4906e4eb [weak]
  Release file created at: Wed, 24 Jun 2020 19:48:37 +0000
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [869 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [89.0 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1003 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:20 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [9282 B]
(dspt_p38)  ✘  ~/src/dspt/docker   feature/EC-1992 ●  docker build --no-cache -t 744312591452.dkr.ecr.ca-central-1.amazonaws.com/dspt:v5.0.0 --build-arg BRANCH=feature/EC-1992 -f dockerfile.gpu_test .
Sending build context to Docker daemon  11.78kB
Step 1/2 : FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 as base
 ---> e135227729c4
Step 2/2 : RUN apt-get update --fix-missing
 ---> Running in f2a1205aae0b
Ign:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Get:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Ign:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [41.2 kB]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [185 kB]
Err:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
  File has unexpected size (213860 != 185496). Mirror sync in progress? [IP: 152.195.19.142 443]
  Hashes of expected file:
   - Filesize:185496 [weak]
   - SHA256:f7e866fdb738e4bda095feb338ba61fc8150f584fb4ab1b39a025f58c0e01932
   - SHA1:4462a72d5e4952c9cb747af9678d0a1d85857837 [weak]
   - MD5Sum:4be0b5ad7f6bbec51557955b4906e4eb [weak]
  Release file created at: Wed, 24 Jun 2020 19:48:37 +0000
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [869 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1003 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [89.0 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [9282 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [13.6 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [102 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1405 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1302 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [8158 B]
Get:26 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [8286 B]
Fetched 18.2 MB in 8s (2288 kB/s)
Reading package lists...
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (213860 != 185496). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - Filesize:185496 [weak]
    - SHA256:f7e866fdb738e4bda095feb338ba61fc8150f584fb4ab1b39a025f58c0e01932
    - SHA1:4462a72d5e4952c9cb747af9678d0a1d85857837 [weak]
    - MD5Sum:4be0b5ad7f6bbec51557955b4906e4eb [weak]
   Release file created at: Wed, 24 Jun 2020 19:48:37 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update --fix-missing' returned a non-zero code: 100

**2. To reproduce the issue**
Build this dockerfile:
FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
RUN apt-get update

**Comment by prcastro** [comment]
I'm having the exact same problem

**Comment by dcdolson** [comment]
Same problem here. Same sizes and hashes in the error.

**Comment by anthonyclark-as** [comment]
Same problem here

**Comment by klueska** [comment]
This is not the right place to file issues related to containers running on top of nvidia-docker.

You will need to file an issue here:
https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/
