### ISSUE TITLE
How could I uninstall nvidia-docker?

### ISSUE THREAD

**Issue by DeepLatte** [NVIDIA/nvidia-docker#1344]
Hi, I've installed the newest version of nvidia-docker.
Because of some reasons we need to downgrade it. so, I want to uninstall the nvidia-docker.
How could I do that?

I tried follow descriptions but it doesn't work. I think it is for older version of nvidia-docker

'-----------------------------------------------------------------
### If you have nvidia-docker 1.0 installed: we need to remove it and all existing GPU containers
$ docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
$ sudo apt-get purge -y nvidia-docker

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'nvidia-docker' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
'-----------------------------------------------------------------

Thanks.

**Comment by anyogi** [comment]
Try this, it worked for me
sudo apt-get purge -y nvidia-docker2

**Comment by JunMa11** [comment]
Hi @anyogi ,

I can not remove the nvidia-docker. Any guidance will be highly appreciated.

> sudo apt-get purge -y nvidia-docker2

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  nvidia-docker2*
0 upgraded, 0 newly installed, 1 to remove and 286 not upgraded.
After this operation, 27.6 kB disk space will be freed.
(Reading database ... 139230 files and directories currently installed.)
Removing nvidia-docker2 (2.6.0-1) ...
(Reading database ... 139225 files and directories currently installed.)
Purging configuration files for nvidia-docker2 (2.6.0-1) ...
dpkg: warning: while removing nvidia-docker2, directory '/etc/docker' not empty so not removed
```

**Comment by elezar** [comment]
@JunMa11 the warning is due to the `/etc/docker/daemon.json` file existing. This is required by `docker` and should not in general be removed. Depending on its contents, it may however be safe to do so.

**Comment by JunMa11** [comment]
Got it. Thanks for your reply much:)

**Comment by klueska** [comment]
Is this issue resolved now then?
