### ISSUE TITLE
Installing nvidia-docker2 packages overwrites settings in /etc/docker/daemon.json

### ISSUE THREAD

**Issue by paulraines68** [NVIDIA/nvidia-docker#1346]
### 1. Issue or feature description
Installing nvidia-docker2 RPM packages from repo overwrites settings users may already have in /etc/docker/daemon.json

The file should be marked as a Config type file in the RPM build or modified by script in post or just have the instructions tell the installer to add the needed config by hand

### 2. Steps to reproduce the issue
* Install just docker
* Put settings in /etc/docker/daemon.json
* Install nvidia-docker2 RPM package from yum repo

### 3. Relevant Information

OS is CentOS 7.7 with docker CE 19.03.11-3 and nvidia-docker2-2.3.0-1

**Comment by andyneff** [comment]
@paulraines68 Just ran into this too

It looks like [this](https://github.com/NVIDIA/nvidia-docker/blob/master/rpm/SPECS/nvidia-docker2.spec#L32) line is claiming a file that does not belong to nvidia-docker:

It makes long term solution to keeping docker working on a system hard.

Is there a reason why they don't just use a json library (like python's json, which exists on every fedora/Centos machine) to edit the json file, and just add the entry they want?
