### ISSUE TITLE
Running apt-get update broken -- See apt-secure(8) manpage for details

### ISSUE THREAD

**Issue by klueska** [NVIDIA/nvidia-docker#1349]
A recent change to the repository structure for `libnvidia-container` may trigger an error when running `apt-get update` on Debian based systems. We have reverted the change that causes the issue, but you may run into it if you have called `apt-get update` recently.

The error is as follows:
```
Get:7 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease [1,146 B]
E: Repository 'https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease' changed its 'Origin' value from 'https://nvidia.github.io/libnvidia-container/stable' to 'https://nvidia.github.io/libnvidia-container'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
```

A simple fix for this is to either:
1) Run the following and manually answer `y` when asked to confirm the relevant changes
**Note:**  this is NOT `apt-get`, but rather just standalone `apt`
```
sudo apt update
```

2) Run `apt-get` update with the `--allow-releaseinfo-change` flag to automatically confirm the changes for you:
```
sudo apt-get update --allow-releaseinfo-change
```

**Comment by leohfigueiredo** [comment]
Thank you!

**Comment by dubwoc** [comment]
Awesome, thank you!

**Comment by Showerlover** [comment]
Thank you so much!!!

**Comment by LightnerDev** [comment]
I have needed this for so long THANK YOU SO MUCH!!!

**Comment by dwelc023** [comment]
YES!!!!
