### ISSUE TITLE
nvidia-docker.service couldn't start.

### ISSUE THREAD

**Issue by jwgim** [NVIDIA/nvidia-docker#135]
I've working on Ubuntu 16.04, I can't finish installation of nvidia-docker.
Could you tell me the solution? Here are some info.

sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

Selecting previously unselected package nvidia-docker.
(Reading database ... 353990 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.0.rc.3-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0~rc.3-1) ...
Setting up nvidia-docker (1.0.0~rc.3-1) ...
Configuring user
Setting up permissions
Job for nvidia-docker.service failed because the control process exited with error code. See "systemctl status nvidia-docker.service" and "journalctl -xe" for details.
nvidia-docker.service couldn't start.
Processing triggers for ureadahead (0.100.0-19) ...

~$ systemctl status nvidia-docker.service 

● nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/lib/systemd/system/nvidia-docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since 2016-07-12 11:23:40 KST; 7s ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 11937 ExecStopPost=/bin/rm -f $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 11932 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 11921 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
  Process: 11919 ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR (code=exited, status=1/FAILURE)
 Main PID: 11919 (code=exited, status=1/FAILURE)

 7월 12 11:23:39 ws02 systemd[1]: Failed to start NVIDIA Docker plugin.
 7월 12 11:23:39 ws02 systemd[1]: nvidia-docker.service: Unit entered failed state.
 7월 12 11:23:39 ws02 systemd[1]: nvidia-docker.service: Failed with result 'exit-code'.
 7월 12 11:23:40 ws02 systemd[1]: nvidia-docker.service: Service hold-off time over, scheduling restart.
 7월 12 11:23:40 ws02 systemd[1]: Stopped NVIDIA Docker plugin.
 7월 12 11:23:40 ws02 systemd[1]: nvidia-docker.service: Start request repeated too quickly.
 7월 12 11:23:40 ws02 systemd[1]: Failed to start NVIDIA Docker plugin.

**Comment by 3XX0** [comment]
Can you try to start it manually:

`sudo nvidia-docker-plugin`

**Comment by jwgim** [comment]
Thanks for the reply. 

I tried to start process manually, but it doesn't work too. 
>:~$ sudo nvidia-docker-plugin 
>nvidia-docker-plugin | 2016/07/13 09:01:53 Loading NVIDIA unified memory
>nvidia-docker-plugin | 2016/07/13 09:01:53 Loading NVIDIA management library
>nvidia-docker-plugin | 2016/07/13 09:01:53 Discovering GPU devices
>nvidia-docker-plugin | 2016/07/13 09:01:53 Error: cuda: CUDA driver version is insufficient for CUDA runtime version

Is this because of driver version ? 
I have 364.19 version of driver on my machine. I'm a little confused. Nvidia driver and cuda driver is different? Do I have to install another driver?
If I missed something in install procedures, let me know.

> ~$ nvidia-smi
Wed Jul 13 09:11:12 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 364.19     Driver Version: 364.19         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 0000:04:00.0      On |                  N/A |
| 17%   35C    P8    14W / 270W |    487MiB /  4087MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1625    G   /usr/lib/xorg/Xorg                             288MiB |
|    0      2216    G   compiz                                         126MiB |
|    0      2955    G   ...ator<DisallowFetchForDocWrittenScriptsInM    52MiB |
+-----------------------------------------------------------------------------+

**Comment by flx42** [comment]
I think your driver installation is busted, if you have CUDA installed on the host, can you try running the `deviceQuery` sample? It should also fail.
```
cd /usr/local/cuda/samples/1_Utilities/deviceQuery
sudo make
./deviceQuery
```

**Comment by jwgim** [comment]
I have installed CUDA toolkit but I removed it few days ago (because it doesn't work normally). I think I removed CUDA clearly, but it looks like CUDA still remain in my machine.

`devideQuery` failed as your guess.

>:/usr/local/cuda/samples/1_Utilities/deviceQuery$ ./deviceQuery 
./deviceQuery Starting...
 CUDA Device Query (Runtime API) version (CUDART static linking)
cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

**Comment by flx42** [comment]
You might have two conflicting installs of the drivers on your machine. It can happen if you installed CUDA using the official instructions and then tried to install a newer driver manually using a `.run` file.

If that's your case, you need to remove one of the two, actually the safest might be to remove both and then reinstall the driver with one method.

This issue might help you: https://github.com/NVIDIA/nvidia-docker/issues/99#issuecomment-221721046

**Comment by jwgim** [comment]
Thanks for fast reply. I will try to reinstall driver.

**Comment by flx42** [comment]
@jwgim did it work?

**Comment by jwgim** [comment]
Yeah, It worked! I have installed driver on clean Ubuntu, and problem solved.
Thanks again.

**Comment by heyalqh** [comment]
@jwgim Hi, how to clean cuda in my ubuntu? Should I must do "sudo service lightdm stop"?

**Comment by jwgim** [comment]
@heyalqh Sorry, I forgot to answering your question. I think I cleaned cuda using `.run` file with "--uninstall" option. And you don't need to do "sudo service lightdm stop" when you uninstall (clean) driver.
