### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by nectario** [NVIDIA/nvidia-docker#1352]
### 1. Issue or feature description

I get the following issue when running: docker run --gpus 2 nvidia/cuda:10.2-base nvidia-smi
**docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].**

I am running Docker on my Windows 10 machine and I have a Titan-V GPU

### 2. Steps to reproduce the issue

Type: run --gpus 1 nvidia/cuda:10.2-base nvidia-smi

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
Driver info:

==============NVSMI LOG==============

Timestamp                                 : Tue Jul 21 21:07:33 2020
Driver Version                            : 451.67
CUDA Version                              : 11.0

Attached GPUs                             : 1
GPU 00000000:83:00.0
    Product Name                          : TITAN V
    Product Brand                         : Titan
    Display Mode                          : Enabled
    Display Active                        : Enabled
    Persistence Mode                      : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : WDDM
        Pending                           : WDDM
    Serial Number                         : 0324917145727
    GPU UUID                              : GPU-77d4b22c-9069-42a5-4b4e-757a79db9216
    Minor Number                          : N/A
    VBIOS Version                         : 88.00.36.00.01
    MultiGPU Board                        : No
    Board ID                              : 0x8300
    GPU Part Number                       : 900-1G500-2500-000
    Inforom Version
        Image Version                     : G001.0000.01.04
        OEM Object                        : 1.1
        ECC Object                        : N/A
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GPU Virtualization Mode
        Virtualization Mode               : None
        Host VGPU Mode                    : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x83
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x1D8110DE
        Bus Id                            : 00000000:83:00.0
        Sub System Id                     : 0x121810DE
        GPU Link Info
            PCIe Generation
                Max                       : 2
                Current                   : 1
            Link Width
                Max                       : 16x
                Current                   : 16x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 1000 KB/s
        Rx Throughput                     : 4000 KB/s
    Fan Speed                             : 29 %
    Performance State                     : P8
    Clocks Throttle Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 12288 MiB
        Used                              : 1091 MiB
        Free                              : 11197 MiB
    BAR1 Memory Usage
        Total                             : 256 MiB
        Used                              : 229 MiB
        Free                              : 27 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 6 %
        Memory                            : 0 %
        Encoder                           : 0 %
        Decoder                           : 0 %
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    Ecc Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
            Double Bit
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
        Aggregate
            Single Bit
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
            Double Bit
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 43 C
        GPU Shutdown Temp                 : 100 C
        GPU Slowdown Temp                 : 97 C
        GPU Max Operating Temp            : 91 C
        Memory Current Temp               : 40 C
        Memory Max Operating Temp         : 95 C
    Power Readings
        Power Management                  : Supported
        Power Draw                        : 27.11 W
        Power Limit                       : 250.00 W
        Default Power Limit               : 250.00 W
        Enforced Power Limit              : 250.00 W
        Min Power Limit                   : 100.00 W
        Max Power Limit                   : 300.00 W
    Clocks
        Graphics                          : 142 MHz
        SM                                : 142 MHz
        Memory                            : 850 MHz
        Video                             : 555 MHz
    Applications Clocks
        Graphics                          : 1200 MHz
        Memory                            : 850 MHz
    Default Applications Clocks
        Graphics                          : 1200 MHz
        Memory                            : 850 MHz
    Max Clocks
        Graphics                          : 1912 MHz
        SM                                : 1912 MHz
        Memory                            : 850 MHz
        Video                             : 1717 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Processes
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 1632
            Type                    : C+G
            Name                    : Insufficient Permissions
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 5504
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 10036
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\Microsoft.ZuneVideo_10.20032.16211.0_x64__8wekyb3d8bbwe\Video.UI.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 10896
            Type                    : C+G
            Name                    : C:\Windows\explorer.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 12164
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 12436
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 12860
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\Microsoft.YourPhone_1.20062.97.0_x64__8wekyb3d8bbwe\YourPhone.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 13428
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\AcrobatNotificationClient_1.0.4.0_x86__e1rzdqpraam7r\AcrobatNotificationClient.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 13928
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.LockApp_cw5n1h2txyewy\LockApp.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 14072
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\Microsoft.SkypeApp_15.61.100.0_x86__kzf8qxf38zg5c\Skype\Skype.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 15296
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 15484
            Type                    : C+G
            Name                    : C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 15500
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\AdobeNotificationClient_2.0.1.8_x86__enpm4xejd91yc\AdobeNotificationClient.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 16268
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\WindowsInternal.ComposableShell.Experiences.TextInput.InputApp.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 16600
            Type                    : C+G
            Name                    : C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 16968
            Type                    : C+G
            Name                    : C:\Users\nektarios\AppData\Local\BlueJeans\current\BlueJeans.Detector.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 16976
            Type                    : C+G
            Name                    : C:\Users\nektarios\AppData\Local\Viber\Viber.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 17004
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\Microsoft.SkypeApp_15.61.100.0_x86__kzf8qxf38zg5c\Skype\Skype.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 18380
            Type                    : C+G
            Name                    : C:\Program Files\Docker\Docker\Docker Desktop.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 18628
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2020.20070.10002.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 19192
            Type                    : C+G
            Name                    : C:\Program Files (x86)\Dropbox\Client\Dropbox.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 23724
            Type                    : C+G
            Name                    : C:\Program Files\Docker\Docker\frontend\Docker Desktop.exe
            Used GPU Memory         : Not available in WDDM driver model
        GPU instance ID             : N/A
        Compute instance ID         : N/A
        Process ID                  : 24468
            Type                    : C+G
            Name                    : C:\Program Files\iTunes\iTunes.exe
            Used GPU Memory         : Not available in WDDM driver model

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by belorenz** [comment]
Had the same problem yesterday. Restarting docker daemon fixed the problem.

`sudo service docker restart`

**Comment by vancuonghoang** [comment]
sudo docker run -itd --gpus all -p 5000:5000 nvidia/digits
97487e7d098e976b7e59c9b991298928f77ac1a3893b38583d96d42938a485bc
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
### How can i fix this, please?
