### ISSUE TITLE
What is the best practice for building container with NVIDIA Container Toolkit ?

### ISSUE THREAD

**Issue by caprest** [NVIDIA/nvidia-docker#1356]
I want to build container using GPU 
The [wiki](https://github.com/NVIDIA/nvidia-docker/wiki) says  

```
you configure your Docker daemon to use the nvidia runtime as the default, you will be able to have build-time GPU support.
```

However,  NVIDIA Container Toolkit does not install `nvidia-container-runtime`.

I found installing `https://github.com/NVIDIA/nvidia-container-runtime` manually and modifying `/etc/docker/daemon.json` like in Nvidia-docker2(https://github.com/NVIDIA/nvidia-docker/issues/595#issuecomment-519714769) enable build-time use of GPU. 

But I am wondering this is the best practice for it because https://github.com/NVIDIA/nvidia-container-runtime/issues/94#issuecomment-582683815 says `nvidia-container-runtime is old and deprecated`

Thanks.

**Comment by aslu98** [comment]
I have the same issue as I need GPU support runtime and I can't modify docker folder.
