### ISSUE TITLE
Broken link on the Wiki page

### ISSUE THREAD

**Issue by adamradocz** [NVIDIA/nvidia-docker#1360]
The link is broken on the Installation (Native GPU Support) Wiki page [Dockerfiles](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)#dockerfiles) section.
The good link is: https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/11.0/ubuntu20.04-x86_64/base/Dockerfile

**Comment by klueska** [comment]
Updated. Thanks.
