### ISSUE TITLE
Can I install cuda Toolkit in the container by myself?

### ISSUE THREAD

**Issue by benz725** [NVIDIA/nvidia-docker#1363]
Surely I can pull an image with cuda toolkit from the Dockerhub,  but i find the image I pulled from the Dockerhub, there is no /usr/local/cuda/bin directory, so I can't run the nvcc -V to show the cuda version. And I can't add the /usr/local/cuda/bin to my environment variable.
So my question is, Can I pull a normal ubuntu image from the Dockhub, and install cuda Toolkit by myself?

**Comment by amirftma** [comment]
Cude **devel** images from the DockerHub has the `/usr/local/cuda/bin` path and `nvcc`.

run the command below with Cuda devel to confirm that the path and `nvcc` exists.

```shell
$ docker run --rm nvidia/cuda:11.0-devel-ubuntu20.04 ls -C /usr/local/cuda/bin/ 
bin2c		   cuda-gdb	   cudafe++   nvcc	    nvlink   ptxas
compute-sanitizer  cuda-gdbserver  cuobjdump  nvcc.profile  nvprof
crt		   cuda-memcheck   fatbinary  nvdisasm	    nvprune

$ docker run --rm nvidia/cuda:11.0-devel-ubuntu20.04 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```

sure you can build the image from scratch, take a look at [cuda container images](https://gitlab.com/nvidia/container-images/cuda/-/tree/master)
