### ISSUE TITLE
Docker run with --gpus 1 but -nvidia-smi with no processes found

### ISSUE THREAD

**Issue by aslu98** [NVIDIA/nvidia-docker#1366]
Hello, I'm sorry if my problem si trivial but I'm very new to this.

### 1. Issue or feature description

I try to run a container with cuda9.1 installed with command `docker run -it --gpus 1 myimage` and it starts executing with no errors (so from my understanding it should use my gpu) but if I check nvidia-smi in another window there is no process executing with it.
 
### 2. Steps to reproduce the issue

`docker run -it --gpus 1 myimage`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
NVRM version:   410.104
CUDA version:   10.0

Device Index:   0
Device Minor:   0
Model:          TITAN Xp
Brand:          GeForce
GPU UUID:       GPU-cadfd15b-b898-b338-3c99-4962eb09a93b
Bus Location:   00000000:03:00.0
Architecture:   6.1

Device Index:   1
Device Minor:   1
Model:          TITAN Xp
Brand:          GeForce
GPU UUID:       GPU-db4e85ac-b0f5-8261-e28d-176315b7e24a
Bus Location:   00000000:04:00.0
Architecture:   6.1
 - [ ] Kernel version from `uname -a`
Linux deeplearn2 4.4.0-177-generic #207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
un  nvidia-container-runtime        <none>               <none>               (no description available)
un  nvidia-container-runtime-hook   <none>               <none>               (no description available)
ii  nvidia-container-toolkit        1.0.5-1              amd64                NVIDIA container runtime hook
ii  nvidia-cuda-dev                 7.5.18-0ubuntu1      amd64                NVIDIA CUDA development files
ii  nvidia-cuda-doc                 7.5.18-0ubuntu1      all                  NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                 7.5.18-0ubuntu1      amd64                NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit             7.5.18-0ubuntu1      amd64                NVIDIA CUDA development toolkit
un  nvidia-current                  <none>               <none>               (no description available)
un  nvidia-driver                   <none>               <none>               (no description available)
un  nvidia-driver-binary            <none>               <none>               (no description available)
un  nvidia-legacy-340xx-vdpau-drive <none>               <none>               (no description available)
un  nvidia-libopencl1               <none>               <none>               (no description available)
un  nvidia-libopencl1-390           <none>               <none>               (no description available)
un  nvidia-libopencl1-410           <none>               <none>               (no description available)
un  nvidia-libopencl1-dev           <none>               <none>               (no description available)
ii  nvidia-modprobe                 418.67-0ubuntu1      amd64                Load the NVIDIA kernel driver and create device files
ii  nvidia-opencl-dev:amd64         7.5.18-0ubuntu1      amd64                NVIDIA OpenCL development files
un  nvidia-opencl-icd               <none>               <none>               (no description available)
rc  nvidia-opencl-icd-390           390.30-0ubuntu1      amd64                NVIDIA OpenCL ICD
ii  nvidia-opencl-icd-410           410.104-0ubuntu1     amd64                NVIDIA OpenCL ICD
un  nvidia-persistenced             <none>               <none>               (no description available)
ii  nvidia-prime                    0.8.2                amd64                Tools to enable NVIDIA's Prime
ii  nvidia-profiler                 7.5.18-0ubuntu1      amd64                NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                 418.67-0ubuntu1      amd64                Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary          <none>               <none>               (no description available)
un  nvidia-smi                      <none>               <none>               (no description available)
un  nvidia-vdpau-driver             <none>               <none>               (no description available)
ii  nvidia-visual-profiler          7.5.18-0ubuntu1      amd64                NVIDIA Visual Profiler for CUDA and OpenCL
ii  libnvidia-container-tools       1.0.7-1              amd64                NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64      1.0.7-1              amd64                NVIDIA container runtime library
un  nvidia-304                      <none>               <none>               (no description available)
un  nvidia-340                      <none>               <none>               (no description available)
un  nvidia-384                      <none>               <none>               (no description available)
rc  nvidia-390                      390.30-0ubuntu1      amd64                NVIDIA binary driver - version 390.30
ii  nvidia-410                      410.104-0ubuntu1     amd64                NVIDIA binary driver - version 410.104
ii  nvidia-410-dev                  410.104-0ubuntu1     amd64                NVIDIA binary Xorg driver development files
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.7
build date: 2020-01-21T19:00+00:00
build revision: b71f87c04b8eca8a16bf60995506c35c937347d9
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by dijksterhuis** [comment]
While I'm here...

> I try to run a container with cuda9.1 installed with command `docker run -it --gpus 1 myimage` and it starts executing with no errors (so from my understanding it should use my gpu) but if I check `nvidia-smi` in another window there is no process executing with it.

Are you running `nvidia-smi` within another docker container? `nvidia-smi` will not print any info for processes in a different container, unless you pass the `--pid=host` flag at container start up, i.e. `docker run -it --pid=host --gpus 1 myimage` then `nvidia-smi` in the second container.

Otherwise, have you tried `docker exec -t <name-of-myimage-container> nvidia-smi` while the `myimage` container is running, and what is the result?

**Comment by aslu98** [comment]
Thank you for your answer, it's been a while but I think my problem was I tried to run nvdia-smi outside of the container, when I changed my configuration and run it inside everything was alright.
