### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by zengqi0730** [NVIDIA/nvidia-docker#1367]
I installed docker 19.03, and then
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
wait for about one minute, but return
gpg: no valid OpenPGP data found.

My System: Ubuntu 18.04
Firewall is inactive

Hope for your reply!

**Comment by bluove** [comment]
+1

**Comment by wenym8** [comment]
me tooooooooooooooooooo！

**Comment by drvelmuruganb** [comment]
+1

**Comment by cherchais** [comment]
I have same error in my computer

my os:ubuntu 16.04
hope for your reply!

**Comment by Agrover112** [comment]
Bro samee

**Comment by bot66** [comment]
Simple network problem.
if you can't open this url [ https://nvidia.github.io/nvidia-docker/gpgkey ](https://nvidia.github.io/nvidia-docker/gpgkey) , then you definitely won't able to use `curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -`.

Because `curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey ` unable to  fetch gpgkey.

Solution:
Just wait until your network automatically  fixed.

**Comment by feima5848** [comment]
gpg: no valid OpenPGP data found.

**Comment by chenm2316** [comment]
me too.

**Comment by Simon32** [comment]
[solved]
download the file in the link and use
`cat gpgkey |  sudo apt-key add -`
then it works.

**Comment by elliottzheng** [comment]
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFnNWDEBEACiX68rxIWvqH3h2GykO25oK9BAqV8fDtb6lXEbw3eKx4g87BRz
M3DQBA0S0IfkQ72ovJ33H50+gVTXuu+Zme5muWk72m3pApccZVDLqdzYlpWPruNb
MC+IlWr70yo8Jw8Zr1ihbWjFvMbDJTkgqPt2djNq3xxvdiKoZlgnpLRKIpSu9iBQ
lNoZLHxTQKFH4219L77prRogv2QV1ckBL5lDVOERJuHo4jHE8mm9/NZ6v3m2HGuu
AEZ7T9nWlPGiAIP8Pww4ZRTJcBANcI2EFKPLdfP61HTH6w0kVMkoAaGlemadTDl3
ZcLpUpTFLc+ko/2uQ1qVPx9QYyoMrorS3kUmlXrhsA7FvcB09aIcb+JX6SVkcbO5
A5+baCa3owwUtFBXMHM5hqpLv4P3/GsuW6283YwLZCf53dJY4lJZePqzPGsvs/wS
vhnZrFvb61i/Aqm0hjhVh7h6VNxUiE8geMcjxy29LtzajoyS0EPVxes4xZu0VbS7
8LQyCNHSpS7TFmtVUQmbXqDN7cpiyr9+yutr0lZOMc7NYQt0nP/3RtYkWEob6wXa
rVImHas1OYzlZymdO1uAnqkediS61E2vSD1OEq37/375FB/Q3AYXuNkQzDjYoJJz
9wsv7Xp0bdPzQ/daLdIFNQXo5MmVIirsWM07JvbZaJhDOiJxGn0MPf11/QARAQAB
tEBOVklESUEgQ09SUE9SQVRJT04gKE9wZW4gU291cmNlIFByb2plY3RzKSA8Y3Vk
YXRvb2xzQG52aWRpYS5jb20+iQI4BBMBCgAiBQJZzVgxAhsPBgsJCggHAwUVCgkI
CwUWAgMBAAIeAQIXgAAKCRDdyuBE95bssAh6EACgUCww2sr8sOztEHKhvdCsonXu
THYbel3YlWmVDPbh4dA31xoRXlvSJptJzPi/zlTc9fkVSFGbEZbFRR4JjnwYTMLD
ElMh5YRMYAoPVYhWGKIO4earu32GhFuPjfr6h+0xNaQeDPIbr7bPe/AEhLSdJMzI
OuAifr7UaC65A6YlxfeaSqyt0HthYujoQ12cWxP998C5jkc0IN2tyLs/OD7HLHht
+lafqDSylykx63cw7jvsV/15rqZwVwjhkcxZyrKET32MTjXF3cxn7+TGpKS8B1k4
a/EI7uXnncfSoma0dAT9bZM9JZbXQmSzCPDHHuVtnQ/3uh8VyenpigTFnrb20LCy
6WzJd3O9lAZXLhvwF/By3a07WLzRtTZNaUpt37Anb0js2syr3lohbmK9i3xvuqZN
zhGPbqu9IV+vFgSGyTHRJUSBlHKDGiCdOOHc20MLPW1yRCXbx0F4eS9TWchYyJkJ
NNczD5DnEl/gsvL4NCRxa+oUyUhhJ1HpJ6YNmTsy6nAAKIC+6248o164GiavaR3z
03RfaQayGHAUrBKi+PJBY7efgsZeYT8f+hyYrIC04MO8poBKS/GvSUL2QtVtj59N
q+95gIptW2mZM8KRpt2huLH+QQ8SKr1vAECbpKJOwseqKmVyxX02iaSE8ifLE+tX
FE8YgS3CZjWwy5PD0LkBDQRdgpCQAQgAx1oxX9tFlv3CIva0CJ0dsZyNF7mgHPgN
szccUYLu0chyWYvwiVU/OlCzivytNX56wgeBgIVV1QzeBuTkrJSgzJ+dSgfrmyg5
RwIDhvH+Dcut0++6+di1LyH9gXQcYPrN3pf4yR8nlRbm6K0Vsp0Z4+br18QelURe
rfAkRordag26aB+MzVLvloHHu3Z6/v321uTGMdFd8CVCjovec5+EdcIAam3U/MmZ
e2mr2M/x6F3st30cE7umq9Bb6UCqc6L8bQcoloxR3rwFzL1u9wUBUzQlaMNmxbe0
BfezkmSQeC8JN4Fku+DtHEpS9uP5JEYNEEQ66K4mJDTMr0whBv1fKQARAQABiQNb
BBgBCgAmAhsCFiEEyVsyG2HojBgJxPdZ3crgRPeW7LAFAl7oD1gFCQNGskgBKcBd
IAQZAQoABgUCXYKQkAAKCRBu2RyjrBFgzZ/WB/9TuD2qzaBO7HlPDWRUTpFlvFgy
Dc3XyfTAC/ISeYbIcPcq5kmVHgpsMdbN9Vvmot5GuT7VWzhHc9sJCmHgL330glBt
NtSRflKzlBYnbiSWxLFYZtu2BtNOk8Ylbw8qw1E6W/iFBrqAwgeZvs2VOcPU3203
Mqfi1JbS+YHC/bgs6cNq0zs/WJraYxiuleclKYExxLt9tRd0058n58GAph+Ki7mR
InO6kxuKpsQannSn1Ku/DiaQcSF2L2TMSo0N9zwvYEZR+hgsKVqyRKT+DkZhusHJ
HYGv96YHSTwo016ZhwYS9t0MLXY9/PgJysuO41Ya4Ii43D3UK1wOHTmyHZHTCRDd
yuBE95bssDpwD/4jV9Pin3vAKa4hhn5GD4e478FNKRD58Q7qF3AhVTBNPIl1m4EF
X7sqI6cXUDG4BjpS70ZRWF2x51ZTiq7DLTV/gGw2okfVjoWjzQY0ebrLd4IoNs80
lIHmXxa+JdwB6WupCUzKCKLcPsX/yPAmswPNGAuIMAv+PWhUUSMVtzOZldnlogGM
hbJ9UD2txFGGh9WoYc2vgX9KAaKryXcC6QMabv7JJU24HEJJDgbJEvtFM5PS8QMF
bXIZsYgICWpQXVChBbduXo9sD2TUDWYAniNaaw4LKxPRG+Ix4HAqkh1oNOLojO30
DO3r1/62FKE5/ykg3iSMTDR0iOES/leXCCIO9fRJT8+eucxyOQoY5ti7tjt1wm3H
nTB+Rz3E/E2qeLs2PN82aseccm1G06pmsMCUiWtmSV6HjdO2XufYprrGLSu0RrT3
sz5WHGUOY2iO40xHhSiXg3TcLZRpv30DQzxoUrx9Ff//rXLFznh+MksuvVD2roUR
BGz/en31FxAcBoex9nNraeOekbFen5b7Xrq9wnzM5xZvJN2QYB3vS0khz/ZgFyy5
444ALa9gwb29FZCfA4m59S2QoB8uPQGM+8gnusE6J8y4fvI59ugafidIkt86dZ3m
FsEME5XNmBGdNEo2flRVFfpG1IWds2Ba3IsdbYd9nzmbBW7/n0InVRDrIg==
=9QWY
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by oanhltk-2376** [comment]
try with `wget -qO - https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -`

**Comment by anqierman** [comment]
+1

**Comment by anqierman** [comment]
I have the same problem.It could be an IP problem
[solved]
Step1. Open this website https://github.io.ipaddress.com/, and then search nvidia.github.io corresponding IP address.
Step2. sudo vim /etc/hosts ,Add the following at the end.

185.199.108.153 nvidia.github.io
185.199.109.153 nvidia.github.io
185.199.110.153 nvidia.github.io
185.199.111.153 nvidia.github.io

**Comment by ZuoMeng96** [comment]
> [solved]
> download the file in the link and use
> `cat gpgkey | sudo apt-key add -`
> then it works.

i  still get the same error in this way.
`gpg: no valid OpenPGP data found.`

**Comment by ZuoMeng96** [comment]
> [solved]
> download the file in the link and use
> `cat gpgkey | sudo apt-key add -`
> then it works.

i  still get the same error in this way or the `wget` command, it is error from `sudo apt-key add`, how could i slove it
`gpg: no valid OpenPGP data found.`

**Comment by zengqi0730** [comment]
> I have the same problem.It could be an IP problem
> [solved]
> Step1. Open this website https://github.io.ipaddress.com/, and then search nvidia.github.io corresponding IP address.
> Step2. sudo vim /etc/hosts ,Add the following at the end.
> 
> 185.199.108.153 nvidia.github.io
> 185.199.109.153 nvidia.github.io
> 185.199.110.153 nvidia.github.io
> 185.199.111.153 nvidia.github.io

nice, thanks

**Comment by Agrover112** [comment]
I think this issue has been fixed since last updates to CUDA and WSL2 relates drivers

**Comment by wanghan0501** [comment]
>I have the same problem.It could be an IP problem
[solved]
Step1. Open this website https://github.io.ipaddress.com/, and then search nvidia.github.io corresponding IP address.
Step2. sudo vim /etc/hosts ,Add the following at the end.
185.199.108.153 nvidia.github.io
185.199.109.153 nvidia.github.io
185.199.110.153 nvidia.github.io
185.199.111.153 nvidia.github.io

Thanks! It works!!
