### ISSUE TITLE
Failure of test usage command 

### ISSUE THREAD

**Issue by vladdy** [NVIDIA/nvidia-docker#1372]
### 1. Issue or feature description

The following command suggested to test the install fails as `nvidia-smi` appears to be missing from the current image:

```
$ docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled
```

### 2. Steps to reproduce the issue

Install `nvidia-container-toolkit` and run `docker run --gpus all nvidia/cuda:10.0-base nvidia-smi`

**Comment by trondhindenes** [comment]
I can repro. AFAIK, the docker daemon doesn't get updated with the new runtime.

**Comment by vladdy** [comment]
> I can repro. AFAIK, the docker daemon doesn't get updated with the new runtime.

Did you mean `image` under the `daemon`? ;)
