### ISSUE TITLE
nvidia/cuda:8.0-cudnn5-devel on docker hub?

### ISSUE THREAD

**Issue by seanbell** [NVIDIA/nvidia-docker#138]
The docker hub (https://hub.docker.com/r/nvidia/cuda/) is missing CUDA 8 images.  Are there any plans to build an official version and push to the hub?

There are scripts in this repository (https://github.com/NVIDIA/nvidia-docker/tree/master/ubuntu-16.04/cuda), but there is not a binary build available.

**Comment by flx42** [comment]
It's actually available, but since CUDA 8.0 is still Release Candiate, it's semi-hidden, you have to use the OS suffix: `nvidia/cuda:8.0-ubuntu16.04`.

Let me know if this image works for you.

**Comment by flx42** [comment]
@seanbell did it work for you?

**Comment by flx42** [comment]
I just added CUDA 8.0 RC based on 14.04, so now you can use `nvidia/cuda:8.0-cudnn5-devel`.

**Comment by ra9hur** [comment]
From the link,
https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/8.0/runtime/cudnn5/Dockerfile

See that, cuda8.0/cudnn5_runtime are available only on Ubuntu 14.04. Would there be a version for Ubuntu 16.04/16.10 shortly ?

**Comment by flx42** [comment]
It's available already. Use `nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04

**Comment by ra9hur** [comment]
Thanks for quickly responding. So, while building an image using Dockerfile, should the FROM command look like the line below ?
FROM nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04

**Comment by flx42** [comment]
Yes

**Comment by ra9hur** [comment]
Sorry... many questions. Is it already there in Docker Hub ? If yes, what would be Docker Pull Command for cuda:8.0-cudnn5-runtime-ubuntu16.04 ?

**Comment by ra9hur** [comment]
When I try to run the build with "nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04", gives me an error - 

Error parsing reference: "nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04\ufeff" is not a valid repository/tag

Replaced "runtime" with "devel". Still gives me an error.

**Comment by flx42** [comment]
You failed your copy-paste, you have an extra character in your file.
Those are not `nvidia-docker` errors.
