### ISSUE TITLE
Why didn't cuda and torch start successfully?

### ISSUE THREAD

**Issue by SubMarineas** [NVIDIA/nvidia-docker#1381]
I did a centos image of the CPU before installing nvidia-docker, and after installing nvidia, the display was normal, but after installing torch and printing torch.cuda.is_available(), it was displayed as False, and then I checked again I found out that cuda was unsuccessful

**Comment by SubMarineas** [comment]
![image](https://user-images.githubusercontent.com/33534492/92376698-8bd87180-f135-11ea-90fd-1447549c7486.png)

**Comment by klueska** [comment]
I'm not sure what you mean by:
> I did a centos image of the CPU before installing nvidia-docker

Can you tell me which driver version you have installed on your host, and which container image you are using to run the commands you show above. Also, can you show the exact docker command you ran.

**Comment by XZG-0457** [comment]
> I'm not sure what you mean by:
> 
> > I did a centos image of the CPU before installing nvidia-docker
> 
> Can you tell me which driver version you have installed on your host, and which container image you are using to run the commands you show above. Also, can you show the exact docker command you ran.

![image](https://user-images.githubusercontent.com/43441239/92400590-b854b380-f15e-11ea-8fd1-7fc113970041.png)


My startup command is `nvidia-docker run --gpus all --name centos -p 8849:8849 -dit submarineas/centos:v0.1 /bin/bash`. Is there a problem with the startup command? I have pulled nvidia/cuda but `starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH"`, then I use the provided tensorflow image, `nvidia-docker run -it- p 8888:8888 --name ten tensorflow/tensorflow:0.11.0rc0-gpu /bin/sh`, it is no problem.

**Comment by SubMarineas** [comment]
> I'm not sure what you mean by:
> 
> > I did a centos image of the CPU before installing nvidia-docker
> 
> Can you tell me which driver version you have installed on your host, and which container image you are using to run the commands you show above. Also, can you show the exact docker command you ran.

![image](https://user-images.githubusercontent.com/33534492/92401321-01f1ce00-f160-11ea-84d1-3abf332c42fd.png)


My startup command is `nvidia-docker run --gpus all --name centos -p 8849:8849 -dit submarineas/centos:v0.1 /bin/bash`. Is there a problem with the startup command? I have pulled nvidia/cuda but `starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH"`, then I use the provided tensorflow image, `nvidia-docker run -it- p 8888:8888 --name ten tensorflow/tensorflow:0.11.0rc0-gpu /bin/sh`, it is no problem.

**Comment by klueska** [comment]
It's hard to tell exactly what is wrong since you are using a custom image `submarineas/centos:v0.1`.

From the error:
```
CUDA driver version is insufficient for CUDA runtime version
Result = Fail
```
I suspect you somehow ended up with CUDA runtime libraries installed into your image that are a mismatch with the driver version running on the host. How did you generate the ``submarineas/centos:v0.1` image? Can you show me a `Dockerfile` for it?

**Comment by SubMarineas** [comment]
![image](https://user-images.githubusercontent.com/33534492/92404157-78dd9580-f165-11ea-9a92-4f7d2f8fa97a.png)

Yes, my dockerfile is a CPU-based centos 7 image. At first, I didn’t think about the GPU. I just wanted to test opencv and ffmpeg, but after adding tensorflow, I entered the container and installed cuda 10.0 directly. The host version is the same, cudnn is 7.4.2. The object of dockerfilie from is centos based on the warehouse. Is this causing the version mismatch?

**Comment by klueska** [comment]
> I installed cuda 10.0 directly

You can't do this. The image must run with the host CUDA libraries injected into it. This is one of the primary functionalities that `nvidia-docker`provides. To fix the situation, you need to go into `/usr/lib/x86_64-linux-gnu/` inside your container and remove any files of the form `*.so.<driver-version>` (e.g. `libnvidia-ml.so.410.104`) that don't match the driver version on your host.

**Comment by SubMarineas** [comment]
> > I installed cuda 10.0 directly
> 
> You can't do this. The image must run with the host CUDA libraries injected into it. This is one of the primary functionalities that `nvidia-docker`provides. To fix the situation, you need to go into `/usr/lib/x86_64-linux-gnu/` inside your container and remove any files of the form `*.so.<driver-version>` (e.g. `libnvidia-ml.so.410.104`) that don't match the driver version on your host.

Thanks for your reply, I finally know the reason. Today I will make a new container
