### ISSUE TITLE
Which one should I use, nvidia-docker, nvidia-container-toolkit, or nvidia-container-runtime?

### ISSUE THREAD

**Issue by jonghwanhyeon** [NVIDIA/nvidia-docker#1387]
Which one should I use, `nvidia-docker`, `nvidia-container-toolkit`, or `nvidia-container-runtime`?

Currently, [the latest document](https://github.com/NVIDIA/nvidia-docker) suggests that we should install `nvidia-docker2` to use `--gpus` parameter on Docker 19.03.  

However, [the previous document](https://github.com/NVIDIA/nvidia-docker/tree/166fa7ffb23502da8f0b3364c92430d42d267f5b) said that `nvidia-docker2` packages were deprecated with the release of Docker 19.03. And even [the official Docker 19.03 document](https://docs.docker.com/engine/reference/commandline/run/#access-an-nvidia-gpu) suggests installing `nvidia-container-runtime`.

As a person who wants to create a minimal environment, it's very confusing. Could you explain the difference between the three packages and what should be used?

**Comment by klueska** [comment]
Please see the following:
https://github.com/NVIDIA/nvidia-docker/issues/1268#issuecomment-632692949

There are plans to integrate this info into the documentation, but it hasn’t happened yet.
