### ISSUE TITLE
Can't visit https://nvidia.github.io/nvidia-docker/*

### ISSUE THREAD

**Issue by LynnHg** [NVIDIA/nvidia-docker#1389]
Hello, thanks for your good work. I have some trouble installing nvidia-docker.
When I follow the following instructions:
```
# Add the package repositories
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
```
I found that my computer can visit the websit like 'https://nvidia.github.io/nvidia-docker/*', I don't know how to do.

**Comment by LynnHg** [comment]
When I altered the hosts file, this problem had been solved.

**Comment by klueska** [comment]
Is your issue resolved now then?

**Comment by LynnHg** [comment]
Yes，thanks for yor attention！




On 09/28/2020 15:50, Kevin Klues wrote:

Is your issue resolved now then?

**Comment by SiyangXie** [comment]
> When I altered the hosts file, this problem had been solved.

Please elaborate! Might be helpful for me! Thanks!

**Comment by mkJapan880** [comment]
> When I altered the hosts file, this problem had been solved.

If you can, please tell me how to do.

**Comment by mkJapan880** [comment]
> When I altered the hosts file, this problem had been solved.

If you can, please tell me how to do.

**Comment by LynnHg** [comment]
Search nvidia.github.io for the latest IP address and add it to the hosts file
