### ISSUE TITLE
UVM failed to load

### ISSUE THREAD

**Issue by Anthony-Tatowicz** [NVIDIA/nvidia-docker#139]
After a system reboot none of the nvidia-docker containers would restart and would give an error along the lines of.

```
lstat /dev/nvidia-uvm: no such file or directory
```

I think that it is caused by the linux kernel is updating (running ubuntu trusty), it took me an hour to resolve. I ended up reinstalling nvidia-docker and the problem disappeared. Any idea what this problem is and what causes it?

**Comment by alantrrs** [comment]
I believe it's the same issue a this: https://github.com/NVIDIA/nvidia-docker/issues/137

**Comment by Anthony-Tatowicz** [comment]
If that is the case then I assume this is documented, so I will close this issue.
