### ISSUE TITLE
Unable to run " nvidia/cuda:11.0-base" after installing nvidia-docker2 

### ISSUE THREAD

**Issue by edgramirez** [NVIDIA/nvidia-docker#1390]
1. By following the instruction on https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker .  I installed in the Ubuntu 18.04 Linux host the following packages:

- configuring the repository first and running the update
- sudo apt install libnvidia-container1
- sudo apt install libnvidia-container-tools

2.- Following https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html  I  installed:

- nvidia-docker2
- nvidia-container-toolkit
- libnvidia-containe

Using NVIDIA driver metapackage from nvdia-driver-450 (propietary)

3.- When running: **docker run --rm --gpus 1 nvidia/cuda:11.0-base nvidia-smi**  I get:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded\\\\n\\\"\"": unknown.

My environment information:

uname -a
Linux edgar-Precision-7520 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------------------------
nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I0929 03:38:35.172119 6302 nvc.c:282] initializing library context (version=1.3.0, build=16315ebdf4b9728e899f615e208b50c41d7a5d15)
I0929 03:38:35.172231 6302 nvc.c:256] using root /
I0929 03:38:35.172247 6302 nvc.c:257] using ldcache /etc/ld.so.cache
I0929 03:38:35.172261 6302 nvc.c:258] using unprivileged user 1000:1000
I0929 03:38:35.172308 6302 nvc.c:299] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0929 03:38:35.172654 6302 nvc.c:301] dxcore initialization failed, continuing assuming a non-WSL environment
W0929 03:38:35.175833 6303 nvc.c:187] failed to set inheritable capabilities
W0929 03:38:35.175877 6303 nvc.c:188] skipping kernel modules load due to failure
I0929 03:38:35.176028 6304 driver.c:101] starting driver service
I0929 03:38:35.178926 6302 driver.c:196] driver service terminated with signal 15
nvidia-container-cli: initialization error: nvml error: driver not loaded
-----------------------------------------------------------------------------------

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

but I see in Software & Updates > Additional drivers > NVIDIA Corporation GM206GML [Quadro M2200 Mobile]> Using NVIDIA driver metapackage from nvidia-driver-450

---------------------------------------------------------------------------

docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
--------------------------------------------------------------------------------------------

||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
un  libgldispatch0-nvidia                         <none>                      <none>                      (no description available)
ii  libnvidia-cfg1-450:amd64                      450.66-0ubuntu0.18.04.1     amd64                       NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any                            <none>                      <none>                      (no description available)
un  libnvidia-common                              <none>                      <none>                      (no description available)
ii  libnvidia-common-450                          450.66-0ubuntu0.18.04.1     all                         Shared files used by the NVIDIA libraries
ii  libnvidia-compute-450:amd64                   450.66-0ubuntu0.18.04.1     amd64                       NVIDIA libcompute package
ii  libnvidia-compute-450:i386                    450.66-0ubuntu0.18.04.1     i386                        NVIDIA libcompute package
ii  libnvidia-container-tools                     1.3.0-1                     amd64                       NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                    1.3.0-1                     amd64                       NVIDIA container runtime library
un  libnvidia-decode                              <none>                      <none>                      (no description available)
ii  libnvidia-decode-450:amd64                    450.66-0ubuntu0.18.04.1     amd64                       NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-450:i386                     450.66-0ubuntu0.18.04.1     i386                        NVIDIA Video Decoding runtime libraries
un  libnvidia-encode                              <none>                      <none>                      (no description available)
ii  libnvidia-encode-450:amd64                    450.66-0ubuntu0.18.04.1     amd64                       NVENC Video Encoding runtime library
ii  libnvidia-encode-450:i386                     450.66-0ubuntu0.18.04.1     i386                        NVENC Video Encoding runtime library
un  libnvidia-extra                               <none>                      <none>                      (no description available)
ii  libnvidia-extra-450:amd64                     450.66-0ubuntu0.18.04.1     amd64                       Extra libraries for the NVIDIA driver
un  libnvidia-fbc1                                <none>                      <none>                      (no description available)
ii  libnvidia-fbc1-450:amd64                      450.66-0ubuntu0.18.04.1     amd64                       NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-450:i386                       450.66-0ubuntu0.18.04.1     i386                        NVIDIA OpenGL-based Framebuffer Capture runtime library
un  libnvidia-gl                                  <none>                      <none>                      (no description available)
ii  libnvidia-gl-450:amd64                        450.66-0ubuntu0.18.04.1     amd64                       NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-450:i386                         450.66-0ubuntu0.18.04.1     i386                        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
un  libnvidia-ifr1                                <none>                      <none>                      (no description available)
ii  libnvidia-ifr1-450:amd64                      450.66-0ubuntu0.18.04.1     amd64                       NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ifr1-450:i386                       450.66-0ubuntu0.18.04.1     i386                        NVIDIA OpenGL-based Inband Frame Readback runtime library
un  libnvidia-ml1                                 <none>                      <none>                      (no description available)
un  nvidia-304                                    <none>                      <none>                      (no description available)
un  nvidia-340                                    <none>                      <none>                      (no description available)
un  nvidia-384                                    <none>                      <none>                      (no description available)
un  nvidia-390                                    <none>                      <none>                      (no description available)
un  nvidia-common                                 <none>                      <none>                      (no description available)
ii  nvidia-compute-utils-450                      450.66-0ubuntu0.18.04.1     amd64                       NVIDIA compute utilities
ii  nvidia-container-runtime                      3.4.0-1                     amd64                       NVIDIA container runtime
un  nvidia-container-runtime-hook                 <none>                      <none>                      (no description available)
ii  nvidia-container-toolkit                      1.3.0-1                     amd64                       NVIDIA container runtime hook
ii  nvidia-dkms-450                               450.66-0ubuntu0.18.04.1     amd64                       NVIDIA DKMS package
un  nvidia-dkms-kernel                            <none>                      <none>                      (no description available)
un  nvidia-docker                                 <none>                      <none>                      (no description available)
ii  nvidia-docker2                                2.5.0-1                     all                         nvidia-docker CLI wrapper
ii  nvidia-driver-440                             450.66-0ubuntu0.18.04.1     amd64                       Transitional package for nvidia-driver-450
ii  nvidia-driver-450                             450.66-0ubuntu0.18.04.1     amd64                       NVIDIA driver metapackage
un  nvidia-driver-binary                          <none>                      <none>                      (no description available)
un  nvidia-kernel-common                          <none>                      <none>                      (no description available)
ii  nvidia-kernel-common-450                      450.66-0ubuntu0.18.04.1     amd64                       Shared files used with the kernel module
un  nvidia-kernel-source                          <none>                      <none>                      (no description available)
ii  nvidia-kernel-source-450                      450.66-0ubuntu0.18.04.1     amd64                       NVIDIA kernel source package
un  nvidia-legacy-340xx-vdpau-driver              <none>                      <none>                      (no description available)
un  nvidia-opencl-icd                             <none>                      <none>                      (no description available)
un  nvidia-persistenced                           <none>                      <none>                      (no description available)
ii  nvidia-prime                                  0.8.8.2                     all                         Tools to enable NVIDIA's Prime
ii  nvidia-settings                               440.82-0ubuntu0.18.04.1     amd64                       Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                        <none>                      <none>                      (no description available)
un  nvidia-smi                                    <none>                      <none>                      (no description available)
un  nvidia-utils                                  <none>                      <none>                      (no description available)
ii  nvidia-utils-450                              450.66-0ubuntu0.18.04.1     amd64                       NVIDIA driver support binaries
un  nvidia-vdpau-driver                           <none>                      <none>                      (no description available)
ii  xserver-xorg-video-nvidia-450                 450.66-0ubuntu0.18.04.1     amd64                       NVIDIA binary Xorg driver
-----------------------------------------------------------------------------------

nvidia-container-cli -V
version: 1.3.0
build date: 2020-09-16T12:32+00:00
build revision: 16315ebdf4b9728e899f615e208b50c41d7a5d15
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [x] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`
 - [x] Docker version from `docker version`
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 - [x] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [x] Docker command, image and tag used

**Comment by klueska** [comment]
Are you able to run nvidia-smi directly on the host without any problems?

**Comment by edgramirez** [comment]
No sorry my problem was in fact the driver. 
 here the steps i follow to make it work.:

sudo -s
apt install pkg-config
apt install libglvnd
apt autoremove
apt install libglvnd
reboot


sudo -s
apt install ibnvidia-container1
apt install libnvidia-container-tools
apt autoremove


ubuntu-drivers devices
sudo ubuntu-drivers autoinstall
nvidia-smi

**Comment by klueska** [comment]
Glad to hear you got it resolved.
