### ISSUE TITLE
The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 ubuntu1804/x86_64

### ISSUE THREAD

**Issue by praveenbadimala** [NVIDIA/nvidia-docker#1394]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

### 1. Issue or feature description
I am getting the below error when I try to build the docker image of nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
Tried few solutions available online but was not effective. I was getting frequently the below error
W: GPG error: https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' is not signed

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [x] Kernel version from `uname -a`
Linux Gaming-3 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`
NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2
 - [x] Docker version from `docker version`
Docker version 19.03.12, build 48a66213fe
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.2.0
build date: 2020-07-08T19:32+00:00
build revision: d22237acaea94aa5ad5de70aac903534ed598819
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [x] Docker command, image and tag used
FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
RUN apt-get update
above lines in the docker file

**Comment by vitahlin** [comment]
Same issue.
Image: `nvidia/cuda:10.0-devel-ubuntu18.04`
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.26.2, build eefe0d31

Docker command:
```
FROM nvidia/cuda:10.0-devel-ubuntu18.04
RUN apt update 
```

**Comment by vitahlin** [comment]
Who can help us?

**Comment by klueska** [comment]
This is not an issue for `nvidia-docker` itself.

All issues related to images running on top of `nvidia-docker` should be directed here:
https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/25

**Comment by 2377671184** [comment]
I have the same issue. And I encountered with this problem when I am installing CUDA on WSL2-Ubuntu 20.04. Is there any advice?

**Comment by klueska** [comment]
Please see the comment above.
