### ISSUE TITLE
E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (47871 != 49498). 

### ISSUE THREAD

**Issue by tchmiel** [NVIDIA/nvidia-docker#1395]
### 1. Issue or feature description
A dockerfile that used to work no longer works

When I tried to recreate my docker container, I now get the following error:

E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (47871 != 49498). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - Filesize:49498 [weak]
    - SHA256:332f3ee4e353b8a5e5a2bdd8fdbd47cf140c73822b82b328815f122e09e195a0
    - SHA1:4dc8ef9a3ee3c97b3c26d46e07fdd83997e6880b [weak]
    - MD5Sum:bbff3b9c3462257479d72521ee78ec29 [weak]
   Release file created at: Wed, 23 Sep 2020 22:09:13 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update --fix-missing &&     apt-get install -y wget bzip2     ca-certificates sudo &&    apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

### 2. Steps to reproduce the issue

Build a docker container from this simplified Dockerfile:  

FROM nvidia/cuda:10.1-cudnn7-devel
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/miniconda/bin:$PATH
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 \
    ca-certificates sudo &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Docker command, image and tag used
docker build -t test:v2 -f test.Dockerfile .

**Comment by tgaddair** [comment]
@cliffwoolley can someone on your end take a look?  This is preventing us from running GPU tests for Horovod.

**Comment by cliffwoolley** [comment]
Thanks for the heads up @tgaddair -- I'll ping our release packaging team to check on that.

**Comment by demizer** [comment]
Also tracking this on gitlab at https://gitlab.com/nvidia/container-images/cuda/-/issues/96

**Comment by hopper-signifyd** [comment]
This appears to be working now.

**Comment by tgaddair** [comment]
Yes, it's working for us as well.  Thanks @cliffwoolley @demizer, feel free to close.

**Comment by tchmiel** [comment]
working now. Thanks @cliffwoolley @demizer, feel free to close.
