### ISSUE TITLE
Cuda causes segmentation fault using MPS

### ISSUE THREAD

**Issue by steeler18** [NVIDIA/nvidia-docker#1396]
### 1. System information
- Operating system/Platform => Ubuntu 18.04
- Docker version =>19.03.12
- Cuda version docker => 10.2-devel-ubuntu18.04
- Python => 3.6.9
- GPU => GeForce RTX 2070
- Nvidia-docker2 => 2.4.0-1
- Nvidia Driver => 450.51.06-0ubuntu1
- Cuda version host => 11.0.221-1

### 2. Steps to reproduce the issue

1) sudo docker run --rm -it --gpus all nvidia/cuda:10.2-devel-ubuntu18.04 /bin/bash
 
Below cmds are inside the container
 
2) apt update && apt install -y python3
3) python3
4) import ctypes; print(ctypes.cdll.LoadLibrary("libcudart.so").cudaSetDevice(0));
Segmentation fault (core dumped)

**Comment by steeler18** [comment]
Yes, everything works when disabling MPS.

**Comment by steeler18** [comment]
It is fine after I added --ipc=host to run the docker.

**Comment by vankata-ashokkumar** [comment]
@steeler18 did you notice any performance issues after enabling `--ipc=host`?

**Comment by steeler18** [comment]
I did not measure but did not notice any performance degradation.

**Comment by Abhishekghosh1998** [comment]
What is the technical reason behind this segmentation fault with MPS running on the host system and the docker container launch not using `--ipc=host` flag?
