### ISSUE TITLE
Hard power loss killed nvidia-docker

### ISSUE THREAD

**Issue by daveselinger** [NVIDIA/nvidia-docker#140]
Hey there,

I'm a huge fan of the work put into nvidia-docker, FWIW, so thanks.

I was running an nvidia-docker accessing the cuda-BLAS and dnn modules. The docker was in a stable state (at prompt) when I lost power.

I rebooted the machine and since then have been unable to access nvidia-docker either to start existing machines or to run a new one.

When I initially tried to run, I got this message:
`nvidia-docker | 2016/07/15 10:55:04 Error: could not load NVML library`
Then, according to #74, it suggested modifying the LD_LIBRARY_CONFIG. For some reason my libraries weren't under /usr/lib64, but I did add /usr/lib/nvidia-361

`selly@sauron:~$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-361`

Now, I get this message:
`docker: Error response from daemon: create nvidia_driver_361.42: create nvidia_driver_361.42: Error looking up volume plugin nvidia-docker: plugin not found.`

Upon reviewing #34, it seemed to suggest there is some issue with my volumes (which I'm assuming are the mountpoint which provide some connection between the host and the docker?):

I have no volumes:
`selly@sauron:~$ docker volume ls
DRIVER              VOLUME NAME`

The ticket suggested running nvidia-docker volume setup but that doesn't seem to be a valid command.

Some info on my system:
Ubuntu 16.04 (updated)
Docker version 1.11.2, build b9f10c9

`selly@sauron:~$ cat /var/log/upstart/nvidia-docker.log
cat: /var/log/upstart/nvidia-docker.log: No such file or directory`

**Comment by 3XX0** [comment]
Is the `nvidia-docker-plugin` running on your system?

`systemctl status nvidia-docker`

You are running Ubuntu 16.04 so the logs are here instead:

`journalctl -n -u nvidia-docker`

**Comment by daveselinger** [comment]
systemctl status nvidia-docker --it was not running. When I tried to restart it, I got the `could not load NVML library` message.

Good news/bad news. I tried to reinstall my nvidia drivers, and it hoarked the system pretty hardcore. I'm just going to reinstall Ubuntu and start fresh unless you lay on the tracks?

**Comment by daveselinger** [comment]
BTW thanks for quick reply--I wasn't expecting that fast a response!
