### ISSUE TITLE
cuda-samples error when building with Nvidia-Docker?

### ISSUE THREAD

**Issue by za13** [NVIDIA/nvidia-docker#1406]
I'm using Ubuntu 20 and CUDA 11.1

I followed the steps in here: https://developer.nvidia.com/blog/nvidia-docker-gpu-server-application-deployment-made-easy/

When I got to `sudo nvidia-docker build -t device-query .`, it says

    unable to locate package cuda-samples
    the command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends
    cuda-samples:-$CUDA_PKG_VERSION && -rm -rf /var/lib/apt/lists/*'
    returned a non-zero code: 100

The `Dockerfile` is:

	# FROM defines the base image
	FROM nvidia/cuda

	# RUN executes a shell command
	# You can chain multiple commands together with && 
	# A \ is used to split long lines to help with readability
	# This particular instruction installs the source files 
	# for deviceQuery by installing the CUDA samples via apt
	RUN apt-get update && apt-get install -y --no-install-recommends \
	        cuda-samples-$CUDA_PKG_VERSION && \
	    rm -rf /var/lib/apt/lists/*

	# set the working directory 
	WORKDIR /usr/local/cuda-11.1/samples/1_Utilities/deviceQuery

	RUN make

	# CMD defines the default command to be run in the container 
	# CMD is overridden by supplying a command + arguments to 
	# `docker run`, e.g. `nvcc --version` or `bash`
	CMD ./deviceQuery

can anyone help?

**Comment by klueska** [comment]
Since this is not an issue with `nvidia-docker` itself (but rather the images ran on top of it), this question is better suited for:
https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8
