### ISSUE TITLE
What's the differences among nvidia-container-runtime, nvidia-docker and nvidia-container-toolkit?

### ISSUE THREAD

**Issue by hongyi-zhao** [NVIDIA/nvidia-docker#1408]
Hi,

I've noticed that there are several NVIDIA projects with the same/similar aim/purpose as describe below:

[nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime): NVIDIA container runtime 
[nvidia-container-toolkit](https://github.com/NVIDIA/nvidia-container-toolkit): Build and run containers leveraging NVIDIA GPUs 
[nvidia-docker](https://github.com/NVIDIA/nvidia-docker): Build and run Docker containers leveraging NVIDIA GPUs 

If they exactly do the same thing, why create these projects like this?

Regards,
HY

**Comment by klueska** [comment]
Please see:
https://github.com/NVIDIA/nvidia-docker/issues/1268#issuecomment-632692949
