### ISSUE TITLE
Trying to run nvidia-docker and saw error: VolumeDriver.Create: internal error, check logs for details

### ISSUE THREAD

**Issue by hsaputra** [NVIDIA/nvidia-docker#142]
Trying to run nvidia-docker with nvidia-docker-plugin installed and got error when trying to run Docker container `sudo nvidia-docker run -d`

```
docker: Error response from daemon: create nvidia_driver_361.42: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.
```

**Comment by flx42** [comment]
Can you give me the content of the log? On ubuntu 14.04:
```
$ cat /var/log/upstart/nvidia-docker.log
```

Or, if you have systemd (centos 7, ubuntu 16.04):
```
$ systemctl status nvidia-docker
$ journalctl -n -u nvidia-docker
```

**Comment by intuinno** [comment]
I got same error and here is my response. 

```
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:30:59 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:30:59 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:00 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:01 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:01 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:01 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:08 Received activate request
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:08 Plugins activated [VolumeDriver]
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:08 Received create request for volume 'nvidia_driver_352.79'
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:31:08 Error: link /usr/lib/nvidia-352/bin/nvidia-cuda-mps-control /var/lib/nvidia-docker/volumes/nvidia_driver/352.79/bin/nvidia-cuda-mps-control: invalid cross-device link
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:38:45 Received create request for volume 'nvidia_driver_352.79'
/usr/bin/nvidia-docker-plugin | 2016/07/19 17:38:45 Error: link /usr/lib/nvidia-352/bin/nvidia-cuda-mps-control /var/lib/nvidia-docker/volumes/nvidia_driver/352.79/bin/nvidia-cuda-mps-control: invalid cross-device link

```

**Comment by hsaputra** [comment]
Here is the content of my log:

```
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:22 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:24 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:24 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:29 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:32 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:32 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:14:32 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:15:31 Received create request for volume 'nvidia_driver_361.42'
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:15:31 Error: mkdir /var/lib/nvidia-docker/volumes/nvidia_driver/361.42: permission denied
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:18:21 Received create request for volume 'nvidia_driver_361.42'
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:18:21 Error: mkdir /var/lib/nvidia-docker/volumes/nvidia_driver/361.42: permission denied
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:23:43 Received create request for volume 'nvidia_driver_361.42'
/usr/bin/nvidia-docker-plugin | 2016/07/18 12:23:43 Error: mkdir /var/lib/nvidia-docker/volumes/nvidia_driver/361.42: permission denied
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:43 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:45 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:45 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:50 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:52 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:52 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:11:52 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:14:59 Received create request for volume 'nvidia_driver_361.42'
/usr/bin/nvidia-docker-plugin | 2016/07/18 14:14:59 Error: mkdir /var/lib/nvidia-docker/volumes/nvidia_driver/361.42: permission denied
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:27:50 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:31:36 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:31:36 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:31:47 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:31:49 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:31:49 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/07/18 16:31:49 Serving remote API at localhost:3476
```

**Comment by flx42** [comment]
@intuinno For you, look at this issue: https://github.com/NVIDIA/nvidia-docker/issues/133
You should be able to modify the path for the volumes in your upstart/systemd configuration.

@hsaputra Did you install a new version of `nvidia-docker` on top of an older one? With older versions we had a potential permission problem when upgrading. I would advise you to completely remove nvidia-docker and then try to reinstall it:
```
apt-get purge nvidia-docker
rm -rf /var/lib/nvidia-docker
```

**Comment by hsaputra** [comment]
Thanks @flx42 , will give it a shot.

**Comment by hsaputra** [comment]
Looks like problem with driver version is old. It is working now. Thanks!

**Comment by cancan101** [comment]
This seems related to: https://github.com/NVIDIA/nvidia-docker/issues/123

**Comment by qiaohaijun** [comment]
met the same issue

**Comment by mimoralea** [comment]
Arch Linux users follow the steps below (thanks to simon_sjw @ https://aur.archlinux.org/packages/nvidia-docker/):


On installing, I had a fail on testing using
`nvidia-docker run --rm nvidia/cuda nvidia-smi`
getting an "invalid cross-device link" error.
(When this is running correctly, you should get the status of your gpu as seen from within docker.)

To fix: 
Use `systemctl status nvidia-docker` to tell you location of the service.
Then open it with your favourite editor and alter
`ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR `
to
`ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR -d /usr/local/nvidia-driver`

Stop, Reload, Start, try again.

**Comment by Gaoee** [comment]
Hi, I also meet such issue. But the log show different. How can I fix it?
`-- Logs begin at 日 2018-06-03 13:51:55 CST, end at 四 2018-07-12 11:37:46 CST. --
7月 12 11:14:37 WSGTX1080TI systemd[1]: Starting NVIDIA Docker plugin...
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Loading NVIDIA unified memory
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Loading NVIDIA management library
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Discovering GPU devices
7月 12 11:14:37 WSGTX1080TI systemd[1]: Started NVIDIA Docker plugin.
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Provisioning volumes at /var/lib/nvidia-docker/volumes
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Serving plugin API at /var/lib/nvidia-docker
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Serving remote API at localhost:3476
7月 12 11:14:58 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:58 Received create request for volume 'nvidia_driver_384.130'
7月 12 11:14:58 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:58 Error: link /usr/lib32/nvidia-384/vdpau/libvdpau_nvidia.so.384.130 /var/lib/nvidia-docker/volumes/nvidia_driver/384.130/lib/libvdpau_nvidia.so.384.130: invalid cross-device link`

**Comment by Gaoee** [comment]
Hi, I also meet such issue. But the log show different. How can I fix it?

> 7月 12 11:14:37 WSGTX1080TI systemd[1]: Starting NVIDIA Docker plugin...
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Loading NVIDIA unified memory
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Loading NVIDIA management library
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Discovering GPU devices
7月 12 11:14:37 WSGTX1080TI systemd[1]: Started NVIDIA Docker plugin.
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Provisioning volumes at /var/lib/nvidia-docker/volumes
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Serving plugin API at /var/lib/nvidia-docker
7月 12 11:14:37 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:37 Serving remote API at localhost:3476
7月 12 11:14:58 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:58 Received create request for volume 'nvidia_driver_384.130'
7月 12 11:14:58 WSGTX1080TI nvidia-docker-plugin[38711]: /usr/bin/nvidia-docker-plugin | 2018/07/12 11:14:58 Error: link /usr/lib32/nvidia-384/vdpau/libvdpau_nvidia.so.384.130 /var/lib/nvidia-docker/volumes/nvidia_driver/384.130/lib/libvdpau_nvidia.so.384.130: invalid cross-device link

**Comment by wangpengabc** [comment]
5月 07 15:49:04 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 15:49:04 Received create request for volume 'nvidia_driv
5月 07 15:49:04 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 15:49:04 Error: mkdir /var/lib/nvidia-docker/volumes: no
5月 07 21:27:28 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:27:28 Received create request for volume 'nvidia_driv
5月 07 21:27:28 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:27:28 Error: mkdir /var/lib/nvidia-docker/volumes: no
5月 07 21:34:24 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:34:24 Received create request for volume 'nvidia_driv
5月 07 21:34:24 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:34:24 Error: mkdir /var/lib/nvidia-docker/volumes: no
5月 07 21:36:54 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:36:54 Received create request for volume 'nvidia_driv
5月 07 21:36:54 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:36:54 Error: mkdir /var/lib/nvidia-docker/volumes: no
5月 07 21:41:57 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:41:57 Received create request for volume 'nvidia_driv
5月 07 21:41:57 ictwsnai-PowerEdge-T640 nvidia-docker-plugin[170437]: /usr/bin/nvidia-docker-plugin | 2019/05/07 21:41:57 Error: mkdir /var/lib/nvidia-docker/volumes: no

@flx42

**Comment by wangpengabc** [comment]
docker: Error response from daemon: create nvidia_driver_384.81: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.

@flx42

**Comment by RenaudWasTaken** [comment]
Please update to nvidia-docker2.
