### ISSUE TITLE
about dockerfile problem

### ISSUE THREAD

**Issue by zcswdt** [NVIDIA/nvidia-docker#1422]
When I use dockerfile to build the image, I will always report an error in the second step. I thought it was due to the network. I tried many times and still did not solve it. Looking forward to your help。

![image](https://user-images.githubusercontent.com/43515926/99923583-55dc7e00-2d71-11eb-8f2d-5efb19ee9b5a.png)

The following is the dockerfile file：

`FROM nvcr.io/nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update \
 && DEBIAN_FRONTEND=noninteractive apt-get -qqy install python3-pip ffmpeg git less nano libsm6 libxext6 libxrender-dev \
 && rm -rf /var/lib/apt/lists/*

COPY . /app/
WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install \
  https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl \
  git+https://github.com/1adrianb/face-alignment \
  -r requirements.txt`

**Comment by klueska** [comment]
This doesn't appear to be an issue with `nvidia-docker` itself, but rather with the `../compute/cuda/...` repos. I would post the issue here: https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8
