### ISSUE TITLE
[Help] How to use proxy while running nvidia-docker?

### ISSUE THREAD

**Issue by 517030910405** [NVIDIA/nvidia-docker#1423]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
Proxy while running the nvidia-docker. 

Dear Sir, 

I am in a sub-net, with only the "192.168.1.1" can visit the internet. I found that it cannot use the `https_proxy` set in the environment. How should I use the proxy? 

Thanks. 

Best Regards. 

### 2. Steps to reproduce the issue
```bash
export http_proxy="http://192.168.1.1:8080"
export https_proxy="http://192.168.1.1:8080"
export all_proxy="socks://192.168.1.1:1080"
docker run --runtime=nvidia -it --rm nvidia/cuda:9.0-base
```
But the docker is still not using the proxy to download from `nvidia/cuda:9.0-base`

**Comment by klueska** [comment]
This is not something that `nvidia-docker` provides functionality for.

The issue appears to be with your `docker` setup in general. Are you able to download / run other containers from dockerhub?
