### ISSUE TITLE
Problem installing cudatools in Ubuntu18.04, bad signatures

### ISSUE THREAD

**Issue by stefanwan** [NVIDIA/nvidia-docker#1425]
install the tensorflow-gpu follow the instruction of https://tensorflow.google.cn/install/gpu
when i add the "https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64" repository and update,  there are some problems like below:

E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.

**Comment by klueska** [comment]
This is not the right place to report issues with downloaind / installing things from the cuda repos.

Please report your issue here:
https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8
