### ISSUE TITLE
missing lincudnn.so in nvidia/cuda:10.1-cudnn7-devel-centos7

### ISSUE THREAD

**Issue by Cristhine** [NVIDIA/nvidia-docker#1426]
cd /usr/local/cuda/lib64
ls |grep libcudnn*
no cudnn in this docker

**Comment by klueska** [comment]
This issue is not related to `nvidia-docker` but rather the contents of an image running on top of it. You should file your issue here instead: https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8
