### ISSUE TITLE
nvidia-docker.list for ubuntu20.04 contains URLs referencing ubuntu18.04

### ISSUE THREAD

**Issue by bjornsing** [NVIDIA/nvidia-docker#1428]
### 1. Issue or feature description

When installing on Ubuntu 20.04 it seems that repositories for Ubuntu 18.04 are added to package sources.

Specifically the file at https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list should probably not contain the string "ubuntu18.04", but it does.

It's possible to hand-edit ``/etc/apt/sources.list.d/nvidia-docker.list`` to replace "ubuntu18.04" with "ubuntu20.04" and then install ``nvidia-docker2``. This manual step probably shouldn't be necessary.

### 2. Steps to reproduce the issue

``curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list | grep -q ubuntu18.04 && echo "Not good"``

**Comment by klueska** [comment]
Yes. This is expected.

20.04 is just a symlink to 18.04 as seen here (this is the source for the webserver hosting the apt repo):
https://github.com/NVIDIA/nvidia-docker/tree/gh-pages

**Comment by bjornsing** [comment]
Are you sure that's a good idea though...? Once people install on Ubuntu 20.04 they will have URLs for Ubuntu 18.04 in their ``/etc/apt/sources.list.d/nvidia-docker.list``. If a day comes when you decide to change/remove the symlink and distribute other packages for Ubuntu 20.04 that will not have any effect for those who have already installed. Thousands of people may then have to manually edit their apt sources. Do you see the potential future nightmare?

**Comment by klueska** [comment]
It’s obviously not ideal, but using symlinks like this is the way it’s been for a number of years (long before I joined the project), and it’s the way it will remain for the foreseeable future.

There is a low priority project defined to move the repos completely off of GitHub pages and onto nvidia owned servers.

Once that happens we will not be using symlinks like this. We will also start following better practices around multi-arch repos, etc.

We also plan to provide a script to help people migrate to the new setup as well as sync the new repos to the old for at least a year so people have time to perform the migration.

**Comment by bjornsing** [comment]
Ok, it's your problem not mine. :) Cheers!
