### ISSUE TITLE
can not run the image:nvidia/cuda:11.1-devel-ubuntu20.04

### ISSUE THREAD

**Issue by opptimus** [NVIDIA/nvidia-docker#1429]
OS:Ubuntu 20.04；Nvidia Graphics：1080；Nvidia driver version：NVIDIA-Linux-x86_64-450.80.02(update 2020-12-11)
For some reasons,the machine installed cuda 9.1.
When I run the image:nvidia/cuda:11.1-devel-ubuntu20.04，can not run and mention that:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.1, please update your driver to a newer version, or use an earlier cuda container: unknown.

However，NVIDIA-docker need not install any cuda.the diver already update version 450.80.
So how can I fix this error? Install cuda 11.1?

**Comment by opptimus** [comment]
The strange thing is that it can run the image:nvidia/cuda:11.0-devel-ubuntu20.04     successfully 
without changing any files!

**Comment by klueska** [comment]
I wonder if this is related to this (which will have a fix coming out in the 1.3.1 release of libnvidia-container coming out later this week): https://github.com/NVIDIA/libnvidia-container/issues/117#issuecomment-725373082

**Comment by klueska** [comment]
`libnvidia-container` v1.3.1 has now been released. Please try it out and confirm that it resolves your problem.

**Comment by opptimus** [comment]
> 
> 
> `libnvidia-container` v1.3.1 has now been released. Please try it out and confirm that it resolves your problem.

Thanks very much.I study how to update NVIDIA/libnvidia-containe.
However,I don not use directly NVIDIA/libnvidia-containe .Also I do not know how to update NVIDIA/libnvidia-containe.
I try to update the nvidia/docker/NVIDIA Container Toolkit.

**Comment by opptimus** [comment]
> 
> 
> `libnvidia-container` v1.3.1 has now been released. Please try it out and confirm that it resolves your problem.

It can not work.
I already install the NVIDIA/libnvidia-container to 1.3.1-1
The error shows again!
`$ sudo docker run --rm --gpus all nvidia/cuda:11.1-base nvidia-smi

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.1, please update your driver to a newer version, or use an earlier cuda container: unknown.
`

**Comment by klueska** [comment]
Sorry, I didn't read your original error report closely enough. If the host driver is CUDA 9.x then it will not be able to run any CUDA 10.x or 11.x images. CUDA "forward compatibility" wasn't added until CUDA 10.0, and you require CUDA "forward compatibility" in order to run newer CUDA versions on older CUDA drivers.

The only way for you to run a CUDA 11.x image on a CUDA 9.x host is to override the constraint that throws the error:
```
sudo docker run --rm --gpus all -e NVIDIA_DISABLE_REQUIRE=true nvidia/cuda:11.1-base nvidia-smi
```
Note that doing this however, will not allow you to run any CUDA code inside the container (but you can at least start it up and access the GPUs with `nvidia-smi`, etc.)

**Comment by opptimus** [comment]
Thanks!
`docker run --rm --gpus all -e NVIDIA_DISABLE_REQUIRE=true nvidia/cuda:11.1-devel-ubuntu20.04 nvidia-smi
`
It worked!
I try to disable my host machine's cuda program!

**Comment by mgsreddy** [comment]
Upgrade the driver Version to 460.39

**Comment by Arka161** [comment]
@mgsreddy It did not work for me that way. 
I think nvidia-smi isn't supported properly on WSL 2 yet.

**Comment by elezar** [comment]
We have fixes in the pipeline to improve the WSL support. Until these are out, the NVIDIA container runtime "assumes" a CUDA version of 11.0 for the driver and as such fails the requirement check for a CUDA 11.1 container.
