### ISSUE TITLE
Build nvidia-docker behind proxy

### ISSUE THREAD

**Issue by NanXiao** [NVIDIA/nvidia-docker#143]
My host which builds `nvidia-docker` works behind proxy. Now the work around method is modifying `tools/Makefile` manually:  

```
DOCKER_BUILD     :=    ......
                                       --build-arg PKG_ARCH="$(PKG_ARCH)" \
                                       --build-arg http_proxy=http://web-proxy.corp.xxxxxx.com:8080/ \
                                       --build-arg https_proxy=https://web-proxy.corp.xxxxxx.com:8080/
```
 Is there more better method?

**Comment by flx42** [comment]
Please look at this issue: https://github.com/NVIDIA/nvidia-docker/issues/42, @bdalton has written a nice explanation!

**Comment by NanXiao** [comment]
@flx42 I think `nvidia-docker` can refer [docker](https://github.com/docker/docker/blob/master/Makefile), and introduces a varible like `DOCKER_BUILD_ARGS`:

    make DOCKER_BUILD_ARGS="--build-arg http_proxy=http://web-proxy.corp.xxxxxx.com:8080/ --build-arg https_proxy=https://web-proxy.corp.xxxxxx.com:8080/"
