### ISSUE TITLE
Using the official nvidia/cuda:8.0-cudnn6-devel-ubuntu14.04 image, I can't run apt update. Handshake failed.

### ISSUE THREAD

**Issue by ZTGallagher** [NVIDIA/nvidia-docker#1430]
Trying to do some CUDA work with the official docker image, but builds and runs are failing because it can't contact the CUDA/NVIDIA repository

---

### 1. Getting a TLS handshake error when trying to apt update the official image.

```
Err https://developer.download.nvidia.com  Packages
  gnutls_handshake() failed: Handshake failed
Err https://developer.download.nvidia.com  Packages
  gnutls_handshake() failed: Handshake failed
...
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed
```

### 2. Steps to Reproduce

  1. docker run -it --rm nvidia/cuda:8.0-cudnn6-devel-ubuntu14.04
  2. apt update

### 3. Some older information suggests that setting the apt sources to https works, but that's already taken care of in the updated image.

```root@546e6111d54f:/# cat /etc/apt/sources.list.d/*
deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /
deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64 /
```

**Comment by klueska** [comment]
This issue is not related to `nvidia-docker` itself, but rather some container running on top of it.
Please file issues related to the CUDA containers here:
https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8

**Comment by blair2020** [comment]
Hello, I've met exactly the same problem with you now. Would you plz share your solution? Thx in advance!
