### ISSUE TITLE
can not install nvidia dirver in ubuntu18.04.5 by 2060s

### ISSUE THREAD

**Issue by linmeon** [NVIDIA/nvidia-docker#1431]
lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1f06 (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 10f9 (rev a1)
01:00.2 USB controller: NVIDIA Corporation Device 1ada (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation Device 1adb (rev a1)

**i can't read 2060s by lspci | grep -i nvidia**

ubuntu-drivers devices

== /sys/devices/pci0000:00/0000:00:1b.4/0000:03:00.0 ==
modalias : pci:v00008086d00002526sv00008086sd00004010bc02sc80i00
vendor   : Intel Corporation
manual_install: True
driver   : backport-iwlwifi-dkms - distro free

== /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 ==
modalias : pci:v000010DEd00001F06sv0000107Dsd00001F06bc03sc00i00
vendor   : NVIDIA Corporation
driver   : nvidia-driver-450 - distro non-free
driver   : nvidia-driver-455 - third-party free recommended
driver   : nvidia-driver-440-server - distro non-free
driver   : nvidia-driver-450-server - distro non-free
driver   : xserver-xorg-video-nouveau - distro free builtin

i have installed driver   : nvidia-driver-450-server - distro non-free

how can i install nvidia dirver and cuda?

**Comment by linmeon** [comment]
https://developer.nvidia.com/zh-cn/cuda-gpus  
 
in this page, i didn't found 2060s in geforce .

2060s is not support use cuda?

**Comment by klueska** [comment]
This is not the right forum for this question. Please ask here:
https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8
