### ISSUE TITLE
can i manually use nvidia-container-cli to allocate gpu to a running container?

### ISSUE THREAD

**Issue by davidstack** [NVIDIA/nvidia-docker#1435]
### 1. Issue or feature description
1. he container has only one GPU card
2. i use nvidia-container-cli configure command to add another one GPU to a running continaer, 73201 is the container pid. and the  /var/lib/docker/overlay2/6720f8482ef5b15daced15d9f5e2e6bfb724a6999de89671d81f1fcf675bfde8/merged  is the rootfs of the container.
````
/usr/bin/nvidia-container-cli  --load-kmods  --debug=/var/log/nvidia-container-toolkit.log  configure --ldconfig=@/sbin/ldconfig --device=1--compute --utility  --pid=73201 /var/lib/docker/overlay2/6720f8482ef5b15daced15d9f5e2e6bfb724a6999de89671d81f1fcf675bfde8/merged
````

 but it failed with this log
`
nvidia-container-cli: mount error: mount operation failed: /var/lib/docker/overlay2/6720f8482ef5b15daced15d9f5e2e6bfb724a6999de89671d81f1fcf675bfde8/merged/proc/driver/nvidia: no such file or directory
`

is it possible to add a gpu card to a running container manually ?

**Comment by davidstack** [comment]
![Uploading image.png…]()

**Comment by davidstack** [comment]
just like the correct  pid is not the  running container pid

![image](https://user-images.githubusercontent.com/5036200/102863211-38ccc500-446d-11eb-883b-5b68b2792f0e.png)

**Comment by klueska** [comment]
This is not supported. The `nvidia-container-cli` is not designed to allow dynamic addition of GPUs at runtime. It is only meant as a hook to run after container creation, but before container start.
