### ISSUE TITLE
How to build a debug version of nvidia-docker?

### ISSUE THREAD

**Issue by NanXiao** [NVIDIA/nvidia-docker#144]
I want to build a debug version of `nvidia-docker` which can be tweaked by `Go` debugger, such as [delve](https://github.com/derekparker/delve). I add `-gcflags "-N -l"` in [tools/Dockerfile.build](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/Dockerfile.build) file:  

    CMD go install -v  -gcflags "-N -l" -ldflags="-s -X main.Version=$VERSION" ./...
But it doesn't seem work:  

    # dlv exec nvidia-docker/tools/bin/nvidia-docker
    could not launch process: decoding dwarf section info at offset 0x0: too short
Is my method right? How to build a debug version of nvidia-docker?

Thanks very much in advance!

**Comment by flx42** [comment]
I haven't tried, but you should try to remove the `-s` too (strip).

Why do you want to do that? We have a debug environment variable `NV_DEBUG`, when set, errors will generate a stack trace. It might help.
https://github.com/NVIDIA/nvidia-docker/blob/1dff2bb5088c2519b1db269b35cd7f9bec60f64c/tools/src/nvidia-docker-plugin/main.go#L47

**Comment by NanXiao** [comment]
@flx42 After removing `-s` option, that error disappeared. But the source file still can't be displayed:  

```
# dlv exec tools/bin/nvidia-docker
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x407e3b for main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:46
(dlv) c
> main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:46 (hits goroutine(1):1 total:1) (PC: 0x407e3b)
(dlv) n
> main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:47 (PC: 0x407e54)
(dlv)
> main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:48 (PC: 0x407e9d)
(dlv)
```

I just want to employ debugger to know the mechanisms of `nvdia-docker` better.

**Comment by flx42** [comment]
It's normal, `nvidia-docker` was built inside a Docker container so you don't have the sources on your machine.

**Comment by NanXiao** [comment]
@flx42 Got it! Thanks very much!
