### ISSUE TITLE
Unable to start container with GPU, docker: Error response from daemon: OCI runtime create failed.

### ISSUE THREAD

**Issue by apiszcz** [NVIDIA/nvidia-docker#1441]
Unable to start container with GPU, 
Goal is to run pytorch with  CUDA 10.1 .
Ubuntu 20.05
Docker 20.10.1

`run --gpus 1 -it imageid
`
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, 

stdout: , stderr: nvidia-container-cli: mount error: write error: /sys/fs/cgroup/devices/docker/fc84e2a61394f8617559ef2789b94141ba982e2ec472ee9055c870d051ecc313/devices.allow: operation not permitted: unknown.`

`nvidia-container-toolkit is already the newest version (1.4.0-1).`

```
NVRM version:   460.27.04
CUDA version:   11.2

Device Index:   0
Device Minor:   1
Model:          Tesla M40 24GB
Brand:          Tesla
GPU UUID:       GPU-f7d24f46-7572-4fd1-fa2c-6fd095acb4bd
Bus Location:   00000000:05:00.0
Architecture:   5.2

Device Index:   1
Device Minor:   2
Model:          Tesla M40 24GB
Brand:          Tesla
GPU UUID:       GPU-eba13467-1694-e130-c052-c1a06b52a298
Bus Location:   00000000:08:00.0
Architecture:   5.2
```

```
Thu Dec 31 15:55:54 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla M40 24GB      Off  | 00000000:05:00.0 Off |                    0 |
| N/A   26C    P8    17W / 250W |      0MiB / 22945MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M40 24GB      Off  | 00000000:08:00.0 Off |                    0 |
| N/A   25C    P8    17W / 250W |      0MiB / 22945MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by apiszcz** [comment]
The file path does not exist:
/sys/fs/cgroup/devices/docker/fc84e2a61394f8617559ef2789b94141ba982e2ec472ee9055c870d051ecc313/devices.allow

```
ls -al  /sys/fs/cgroup/devices/docker
total 0
drwxr-xr-x 3 root   root 0 Jan  1 11:49 .
drwxrwxr-x 6 nobody root 0 Dec 31 12:56 ..
drwxr-xr-x 2 root   root 0 Dec 31 13:32 buildkit
-rw-r--r-- 1 root   root 0 Dec 31 12:56 cgroup.clone_children
-rw-r--r-- 1 root   root 0 Dec 31 12:56 cgroup.procs
--w------- 1 root   root 0 Dec 31 12:56 devices.allow
--w------- 1 root   root 0 Dec 31 12:56 devices.deny
-r--r--r-- 1 root   root 0 Dec 31 12:56 devices.list
-rw-r--r-- 1 root   root 0 Dec 31 12:56 notify_on_release
-rw-r--r-- 1 root   root 0 Dec 31 12:56 tasks
```

**Comment by klueska** [comment]
I haven't looked closely, but this may be related to the known issue with `containerd` and the `systemd` cgroups.

Please see:
https://github.com/NVIDIA/libnvidia-container/issues/119
and
https://github.com/NVIDIA/nvidia-container-runtime/issues/127

The above mentioned issues will be fixed in the next release of `libnvidia-container`.

**Comment by apiszcz** [comment]
On it, thank you.

**Comment by klueska** [comment]
Any update on this from your side? I am not able to reproduce this from my side.

**Comment by apiszcz** [comment]
Thank you.

**Comment by apiszcz** [comment]
UPDATE still seeing the issue with UBUNTU 20.04.

**Comment by klueska** [comment]
The error described here seems the same as: https://github.com/NVIDIA/nvidia-docker/issues/1316

Unfortunately, I have never been able to reproduce it so it is hard to dig to the root of the problem and build a fix for it.
Maybe you can answer the question posed at the bottom of #1316 to give me some more clues.

**Comment by gvijqb** [comment]
I am facing the same issue. Unable to find a solution to run docker container with GPU

**Comment by klueska** [comment]
@gvijqb can you post your exact error message to make sure it is actually the same and not something unrelated.

**Comment by gvijqb** [comment]
@klueska here's the error message I get:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: write error: /sys/fs/cgroup/devices/docker/633f0f6b53f3c01a3a3cecc99f5ddb6a94d3722bc04270fa869e2e19ada73a48/devices.allow: operation not permitted\\\\n\\\"\"": unknown.`

**Comment by amizeranschi** [comment]
@klueska I'm getting a very similar, albeit not identical issue:

```
$ docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
```

Any hints?

I was following this tutorial: https://docs.docker.com/docker-for-windows/wsl/

**Comment by iamarkaj** [comment]
> @klueska I'm getting a very similar, albeit not identical issue:
> 
> ```
> $ docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
> ```
> 
> Any hints?
> 
> I was following this tutorial: https://docs.docker.com/docker-for-windows/wsl/

Hi @amizeranschi 
I am having a similar problem. Did you solve this?

**Comment by elezar** [comment]
@amizeranschi @iamarkaj which version of the NVIDIA drivers do you have installed? Also, please note that your errors seem to have something to do with running on WSL and is not related to the issue originally posted. Please create a new issue that better describes the state or your system(s) and the errors you are seeing. Also, if possible, provide the debug output that is available for the NVIDIA container runtime.

**Comment by gvijqb** [comment]
> @klueska here's the error message I get:
> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: write error: /sys/fs/cgroup/devices/docker/633f0f6b53f3c01a3a3cecc99f5ddb6a94d3722bc04270fa869e2e19ada73a48/devices.allow: operation not permitted\\\\n\\\"\"": unknown.`

Any updates on this? @klueska

**Comment by amizeranschi** [comment]
@iamarkaj @elezar  No, i never solved that issue. Instead, I gave up on trying to run things through Docker and I've simply set up a Miniconda environment with all the required stuff, following this tutorial:

Another issue I faced was that I didn't have the latest Windows build (20145 or higher, from the Windows Insider program) and the latest [NVIDIA CUDA on WSL Public Preview driver](https://developer.nvidia.com/cuda/wsl), which are need in order to enable CUDA and GPU computing through WSL. After getting these, I managed to set up the following Conda packages and get TensorFlow to run successfully on my GPU:

```
## Miniconda
cd $HOME
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/anaconda

## add the Miniconda path to $PATH in ~/.bashrc
echo -e "\nexport PATH=$HOME/anaconda/bin:\$PATH" >> ~/.bashrc
source $HOME/.bashrc

## Mamba
conda install -c conda-forge mamba -y

## install Python packages for data analysis, machine learning and deep learning
mamba install -c nvidia -c conda-forge -c anaconda yaml numpy scipy matplotlib pandas scikit-learn hdf5 h5py openblas lapack \
jupyterlab notebook plotly plotnine cudatoolkit cudnn tensorflow-gpu=2.4.1 keras-gpu=2.4.3 -y

## to test TF GPU support, run the following lines in a Python shell:
>>> import tensorflow as tf
>>> tf.config.list_physical_devices('GPU')
>>> print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

**Comment by NJ2020** [comment]
Hi All,

**docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark**

I am getting the below on running the above command from **WSL2 (Ubuntu 18.04)**:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ERRO[0000] error waiting for container: context canceled

I have followed all the installation instructions mentioned at the official guide: https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Windows version:** 10.0.21390 N/A Build 21390

Any help would be highly appreciated.

**Comment by amizeranschi** [comment]
@NJ2020 

As stated earlier, I couldn't get stuff working through Docker, but I managed to set up a Conda environment and Keras/TensorFlow and CUDA are reportledly working fine for me via WSL2 (Ubuntu 2004 LTS).

If Docker isn't a hard requirement for you ATM, I'd suggest giving Miniconda a try.

**Comment by NJ2020** [comment]
> @NJ2020
> 
> As stated earlier, I couldn't get stuff working through Docker, but I managed to set up a Conda environment and Keras/TensorFlow and CUDA are reportledly working fine for me via WSL2 (Ubuntu 2004 LTS).
> 
> If Docker isn't a hard requirement for you ATM, I'd suggest giving Miniconda a try.

@amizeranschi 
Thanks for the reply. Docker makes life much easier. I am not sure how easy it is to set up an environment with older versions like TF1.7 and all other needed libraries e.g. numpy, opencv etc. There is a high chance of getting into compatibility issues.

**Comment by keypointt** [comment]
I face the similar issue `mount error: stat failed: /proc/driver/nvidia/gpus/0000:1a:00.0: no such file or directory: unknown`
```
docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: stat failed: /proc/driver/nvidia/gpus/0000:1a:00.0: no such file or directory: unknown.

```
