### ISSUE TITLE
Pytorch/CUDA issue (driver mismatch) on Docker ?

### ISSUE THREAD

**Issue by apiszcz** [NVIDIA/nvidia-docker#1445]
- Ubuntu 20.04
- Pytorch 1.7
- latest nvidia docker container
- nvidia-smi
- NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.1

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**I can compile the hello.cu example and run it successfully.**

```
root@4fed67936d62:/opt/test# nvcc -o hello hello.cu
root@4fed67936d62:/opt/test# ./hello
Max error: 2.000000
```

However the following pytorch check fails:
```
root@1d71768111b6:/opt/test# python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
```

**Comment by klueska** [comment]
This is not technically a question for this project, since the issue seems to be with the image and not `nvidia-docker` itself.

That said, which NVIDIA container image did you use?

**Comment by apiszcz** [comment]
Not sure how to get the version, beyond latest.
docker       latest     0040bc98e531   2 weeks ago   240MB

**Comment by klueska** [comment]
Sorry, I'm asking which image you ran, i.e.:
```
docker run 
<image_name>
```
What was `<image name>`

**Comment by apiszcz** [comment]
Trying to create a docker in docker image to run. I'm building an ubuntu  20.04 LTS image.

**Comment by klueska** [comment]
The official NVIDIA images (one of which I know bundles pytorch) are designed specifically to work on top of `nvidia-docker`.  
https://ngc.nvidia.com/catalog/containers/nvidia:pytorch

You may need to do something special to get your image to work if it is based on anything other than an official NVIDIA image.

In any case, the right place to ask about this is here, not on the `nvidia-docker` project itself:
https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation/8

**Comment by apiszcz** [comment]
Thank you, this was the direction I was missing.

```
import torch
print(torch.cuda.device_count())
```

root@b7cb43909f20:/workspace# python3 pytorchtest.py
1

**Comment by apiszcz** [comment]
It worked one time, I stepped through install steps again, and get the following error?

Is there a permission configuration that needs modification? Google results show similar issues with other container managers.

Using the NVIDIA pytorch container:

```
root@api3:/home/test# nvidia-docker run -ti ad0f29ddeb63 /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: **nvidia-container-cli: mount error: write error:** /sys/fs/cgroup/devices/docker/9adbd33182290a53f0f0eaeb406a379e18d8300d5c2818a6b35526612c628258/devices.allow: operation not permitted: unknown.
ERRO[0000] error waiting for container: context canceled
```
