### ISSUE TITLE
Unable to start an interactive container with nvidia-docker due to driver/library version mismatch

### ISSUE THREAD

**Issue by chatti** [NVIDIA/nvidia-docker#1451]
I'm getting an error when I try to run an interactive container. This command was working as of Jan. 19 2021, and is broken on Jan 20, 2021. 

After grabbing the image using:
`nvidia/cuda:11.1.1-devel-ubuntu18.04`

I was not getting this error yesterday, and I haven't changed anything to my instance configuration or which version of CUDA I'm downloading, so I'm not sure what the problem is.

```
nvidia-docker run -i -t nvidia/cuda:11.1.1-devel-ubuntu18.04 bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch\\\\n\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled
```
`nvidia-smi -a` also gives an error
`Failed to initialize NVML: Driver/library version mismatch`

This is occuring on an AWS ec2 instance (g4dn.xlarge).
`Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic`

`nvidia-smi -a` also gives an error
`Failed to initialize NVML: Driver/library version mismatch`

`nvidia-container-cli -k -d /dev/tty info`
 I0120 21:53:12.261718 28090 nvc.c:282] initializing library context (version=1.3.1, build=ac02636a318fe7dcc71eaeb3cc55d0c8541c1072)
I0120 21:53:12.261770 28090 nvc.c:256] using root /
I0120 21:53:12.261783 28090 nvc.c:257] using ldcache /etc/ld.so.cache
I0120 21:53:12.261795 28090 nvc.c:258] using unprivileged user 1010:1010
I0120 21:53:12.261823 28090 nvc.c:299] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0120 21:53:12.262028 28090 nvc.c:301] dxcore initialization failed, continuing assuming a non-WSL environment
W0120 21:53:12.263242 28091 nvc.c:187] failed to set inheritable capabilities
W0120 21:53:12.263284 28091 nvc.c:188] skipping kernel modules load due to failure
I0120 21:53:12.263493 28092 driver.c:101] starting driver service
I0120 21:53:12.266147 28090 driver.c:196] driver service terminated with signal 15
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch

`uname -a`
 
`Linux ip-10-157-1-83 5.4.0-1032-aws #33~18.04.1-Ubuntu SMP Thu Dec 10 08:19:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

dmesg
```
[ 3616.520649] NVRM: API mismatch: the client has the version 455.23.05, but
               NVRM: this kernel module has the version 450.80.02.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.
```

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
`un  nvidia-304                                                  <none>                             <none>                             (no description available)
un  nvidia-340                                                  <none>                             <none>                             (no description available)
un  nvidia-384                                                  <none>                             <none>                             (no description available)
un  nvidia-390                                                  <none>                             <none>                             (no description available)
ii  nvidia-compute-utils-455                                    455.23.05-0ubuntu1                 amd64                              NVIDIA compute utilities
ii  nvidia-container-runtime                                    3.4.0-1                            amd64                              NVIDIA container runtime
un  nvidia-container-runtime-hook                               <none>                             <none>                             (no description available)
ii  nvidia-container-toolkit                                    1.4.0-1                            amd64                              NVIDIA container runtime hook
ii  nvidia-cuda-dev                                             9.1.85-3ubuntu1                    amd64                              NVIDIA CUDA development files
ii  nvidia-cuda-doc                                             9.1.85-3ubuntu1                    all                                NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                                             9.1.85-3ubuntu1                    amd64                              NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                                         9.1.85-3ubuntu1                    amd64                              NVIDIA CUDA development toolkit
ii  nvidia-dkms-455                                             455.23.05-0ubuntu1                 amd64                              NVIDIA DKMS package
un  nvidia-dkms-kernel                                          <none>                             <none>                             (no description available)
un  nvidia-docker                                               <none>                             <none>                             (no description available)
ii  nvidia-docker2                                              2.5.0-1                            all                                nvidia-docker CLI wrapper
un  nvidia-driver                                               <none>                             <none>                             (no description available)
ii  nvidia-driver-455                                           455.23.05-0ubuntu1                 amd64                              NVIDIA driver metapackage
un  nvidia-driver-binary                                        <none>                             <none>                             (no description available)
un  nvidia-fabricmanager                                        <none>                             <none>                             (no description available)
ii  nvidia-fabricmanager-450                                    450.80.02-1                        amd64                              Fabric Manager for NVSwitch based systems.
un  nvidia-kernel-common                                        <none>                             <none>                             (no description available)
ii  nvidia-kernel-common-455                                    455.23.05-0ubuntu1                 amd64                              Shared files used with the kernel module
un  nvidia-kernel-source                                        <none>                             <none>                             (no description available)
ii  nvidia-kernel-source-455                                    455.23.05-0ubuntu1                 amd64                              NVIDIA kernel source package
un  nvidia-legacy-340xx-vdpau-driver                            <none>                             <none>                             (no description available)
un  nvidia-libopencl1                                           <none>                             <none>                             (no description available)
un  nvidia-libopencl1-dev                                       <none>                             <none>                             (no description available)
ii  nvidia-modprobe                                             455.23.05-0ubuntu1                 amd64                              Load the NVIDIA kernel driver and create device files
ii  nvidia-opencl-dev:amd64                                     9.1.85-3ubuntu1                    amd64                              NVIDIA OpenCL development files
un  nvidia-opencl-icd                                           <none>                             <none>                             (no description available)
un  nvidia-persistenced                                         <none>                             <none>                             (no description available)
ii  nvidia-prime                                                0.8.8.2                            all                                Tools to enable NVIDIA's Prime
ii  nvidia-profiler                                             9.1.85-3ubuntu1                    amd64                              NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                                             455.23.05-0ubuntu1                 amd64                              Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                                      <none>                             <none>                             (no description available)
un  nvidia-smi                                                  <none>                             <none>                             (no description available)
un  nvidia-utils                                                <none>                             <none>                             (no description available)
ii  nvidia-utils-455                                            455.23.05-0ubuntu1                 amd64                              NVIDIA driver support binaries
un  nvidia-vdpau-driver                                         <none>                             <none>                             (no description available)
ii  nvidia-visual-profiler                                      9.1.85-3ubuntu1                    amd64                              NVIDIA Visual Profiler for CUDA and OpenCL
ii  xserver-xorg-video-nvidia-455                               455.23.05-0ubuntu1                 amd64                              NVIDIA binary Xorg driver`
`nvidia-container-cli -V
version: 1.3.1
build date: 2020-12-14T14:17+00:00
build revision: ac02636a318fe7dcc71eaeb3cc55d0c8541c1072
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections`

**Comment by klueska** [comment]
This doesn't appear to be an issue with `nvidia-docker` error, but rather an error with your base NVIDIA driver installation. Somehow the user-space components of the driver are mismatched with the kernel module installed.

One question I have though -- is that `dmesg` output on the host or inside a container? If it's on the host, then this is definitely a problem independent of `nvidia-docker`.

I would try reinstalling the base NVIDIA driver to see if that fixes things. Did you previously have a `455.23.05` driver installed installed on the host and then downgrade to a `450.80.02` driver?

**Comment by chatti** [comment]
You're right, it's not a docker problem. Calling nvidia-smi on the host
system triggered the same issue.

It seems like an issue with the Amazon AMI, there must have been some
security updates that broke the NVIDIA setup. Maybe I need to figure out
how to uninstall all the old drivers and install new ones. Guh.

**Comment by elezar** [comment]
@chatti I'm closing this issue for the time being. Please reopen if required and ideally post a short update if you were able to resolve your problem to help others.
