### ISSUE TITLE
docker build cenos-7-cuda11.0 failed 

### ISSUE THREAD

**Issue by xiaohu2015** [NVIDIA/nvidia-docker#1453]
Step 7/13 : RUN yum upgrade -y && yum install -y     cuda-cudart-11-0-11.0.221-1     cuda-compat-11-0     && ln -s cuda-11.0 /usr/local/cuda     && yum clean all     && rm -rf /var/cache/yum/*
 ---> Running in 50534d72f53d
OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log configure --ldconfig=@/sbin/ldconfig --device=all --compute --compat32 --graphics --utility --video --display --require=cuda>=11.0 --pid=27954 /data1/docker/overlay2/c671bd4c9c232c706fdaf333bf1145018a67260dc8b67cab80475babe54110ff/merged]\\\\nnvidia-container-cli: mount error: stat failed: /dev/nvidia-modeset: no such file or directory\\\\n\\\"\"": unknown

**Comment by elezar** [comment]
@xiaohu2015 could you provide more information on the platform and configuration you're using and the command you're running?

**Comment by xiaohu2015** [comment]
@elezar I use https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/11.0.3/centos7-x86_64/base/Dockerfile, my host 

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```

```
nvidia-smi
Mon Jan 25 19:15:53 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
```
GPU: Tesla P40

```
docker --version
Docker version 18.09.6, build adbf89666f
```

**Comment by klueska** [comment]
What version of the nvidia container toolkit are you using? The fact that you have a `/var/log/nvidia-container-runtime-hook.log` means that you are likely on a really old version of the tools.

**Comment by klueska** [comment]
Independent of this, do you see a `/dev/nvidia-modeset` device on your host?

**Comment by xiaohu2015** [comment]
@klueska I do not find `/dev/nvidia-modeset `,
```
/usr/bin/nvidia-container-runtime --version
runc version 1.0.0-rc8
commit: f00e93a680ee7f2e9c3c4f737c54d43753808c5b
spec: 1.0.1-dev
```

**Comment by klueska** [comment]
That just shows the underlying `runc` version, not the version of the nvidia container tools.
If you installed via a package manager like `yum` or `apt` you can get the installed versions from this.

Can you also show me the output of:
```
sudo lsmod | grep nvidia
```

**Comment by xiaohu2015** [comment]
```
sudo lsmod | grep nvidia
nvidia_uvm            966656  0 
nvidia              19673088  80 nvidia_uvm
i2c_core               65536  1 nvidia
```

**Comment by klueska** [comment]
Looks like you don't have the modeset module loaded.

Can you run the following on the host:
```
nvidia-modprobe -m
```

`libnvidia-container` should be loading this for you if you haven't alreasdy, so it's not clear why this is erroring out as it is. But I'm gussing after you run this that it will at least unblock you.

**Comment by xiaohu2015** [comment]
@klueska thanks，but it does not work.

**Comment by xiaohu2015** [comment]
@klueska nvidia-docker2 version: nvidia-docker2-2.0.2

**Comment by xiaohu2015** [comment]
I upgrade my nvidia-docker2, it works! Thanks @klueska
