### ISSUE TITLE
docker pull nvidia/cuda --- manifest for nvidia/cuda:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by ulsha** [NVIDIA/nvidia-docker#1454]
---

### 1. Issue or feature description

docker pull nvidia/cuda doesn't work, hence FROM nvidia/cuda doesn't work in my dockerfile.

I am getting the error 'manifest for nvidia/cuda:latest not found: manifest unknown: manifest unknown'.

I'm on Mac OSX 11.1 (Big Sur) and using Docker version 20.10.0.

I have been using this command for over a year and I only encountered this issue after rebooting my Docker installation. I tried on a different laptop, and got the same issue.

### 2. Steps to reproduce the issue

Open the terminal.

Enter 'docker pull nvidia/cuda'.

It returns

u@u-mbp-2 ~ % docker pull nvidia/cuda
Using default tag: latest
Error response from daemon: manifest for nvidia/cuda:latest not found: manifest unknown: manifest unknown

**Comment by klueska** [comment]
The ‚latest‘ tag is no longer available as of a few weeks ago:
https://gitlab.com/nvidia/container-images/cuda#announcement

You have to now explicitly specify which tagged version you want.
