### ISSUE TITLE
docker image with nvidia-smi only for monitoring purposes

### ISSUE THREAD

**Issue by Valahaar** [NVIDIA/nvidia-docker#1457]
### 1. Issue or feature description

I was wondering if there is any way to obtain a docker image which contains `nvidia-smi` alone. I would like to use it for a monitoring system I'm developing, but I would like to avoid having to use the whole cuda image since it's quite big.

Other (containerizable) solutions are appreciated as well.

Thanks :)

**Comment by klueska** [comment]
You can use any docker image you want -- nvidia-docker dynamically mounts the necessary libraries and binaries into the container. You just need to specify the set of `--gpus` you want it to see.

**Comment by Valahaar** [comment]
Well, that is both embarassing and amazing.
Thanks! :D
