### ISSUE TITLE
Doc: Typo in warning present on Getting Started page

### ISSUE THREAD

**Issue by 1nF0rmed** [NVIDIA/nvidia-docker#1461]
### 1. Issue or feature description
Typo in the warning provided in the `Warning` section of the getting started guide. The word `from` is written as `fron`

### 2. Steps to reproduce the issue

Go to the getting started doc. [https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#getting-started](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#getting-started)
![image](https://user-images.githubusercontent.com/21278205/109150647-25044e80-778f-11eb-8714-0cdad927aa8b.png)

**Comment by klueska** [comment]
@dualvtable ^^

**Comment by 1nF0rmed** [comment]
Hey - can I go ahead make a PR for this?
