### ISSUE TITLE
Portable images with compile time GPU support

### ISSUE THREAD

**Issue by SamAchten** [NVIDIA/nvidia-docker#1462]
We are trying to build a docker image with CUDA support. The goal is to run the docker on different types of GPUs. The problem is that there seems to be some kind of relation between the docker build hardware and the docker run hardware. 
The scenario:
We build the docker image in the cloud (Azure). At build time, we also compile our CUDA code, se we need GPU support at build time. The docker images run in a k8s cluster, because they need to be highly available. We cannot afford to compile the code at run time. We also need portability, because we are going to ship the container to different servers and thus different GPUs.

 According to [this issue](https://github.com/NVIDIA/nvidia-docker/issues/856) and the mentioned FAQ, we lose portability of the docker image. How can we then have:
  1. Portable docker images, for different types of GPUs
  2. Highly available containers with fast boot time

**Comment by elezar** [comment]
Hi @SamAchten. It's strange that you need GPUs for building your code, as `nvcc` shouldn't require this in general. We build images including the CUDA samples on standard workers without GPUs and vanilla docker without any problems.

With regards to compatibility, there are two things that I can think of that would need to be considered. Firstly, when the containers are run these need access to a driver version that is compatible with the CUDA version that the image is based on. The compatibility story here has been improved greatly starting with CUDA 10 and CUDA 11. The issue you link is pretty old, and does not represent the current state. There are some restrictions on the driver version used, but these do not have to match exactly. (Also see the docs [here](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#abstract))

Another thing to consider is the target GPU architecture which may differ across target GPUs. This can be addressed by ensuring that `nvcc` is configured to generate the code for all required architectures beforehand to avoid the "just-in-time" compilation. See the docs [here](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation).

Does this answer some of your questions? If not I'd be happy to help out some more if I had more concrete information with regards to driver versions, target GPUs, and supported CUDA versions.

On a side note, for running GPU-enabled containers on k8s, check out the [NVIDIA GPU operator](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html) if you have not already. This, for example, ensures that the node running GPU workloads has the NVIDIA driver installed.

**Comment by SamAchten** [comment]
Hey Elezar, 
Thank you for the response. We were finally able to figure it out. I do not fully understand the whole CUDA compile thing yet. But we were indeed doing something wrong while compiling. We now just provide the path to the CUDA binaries during compilation instead of using nvidia-docker during the build. Does it have to do something with "just-in-time"? I don't know yet...
