### ISSUE TITLE
[Unsupported distribution] on Pop!_os when installing

### ISSUE THREAD

**Issue by AnalogKnight** [NVIDIA/nvidia-docker#1464]
My system is Pop!_os 20.04 LTS.Pop!_os is based on Ubuntu,so i think nvidia-docker can run on it but when i doing the step:Setup the repository and the GPG key,the output is: # Unsupported distribution!
I guess the problem is on the file /etc/os-release

There are the content:
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by klueska** [comment]
You can probably just manually set the distribution name instead of relying directly on `/etc/os-release`:
```
distribution=$(. /etc/os-release;echo ubuntu$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```

**Comment by AnalogKnight** [comment]
> You can probably just manually set the distribution name instead of relying directly on `/etc/os-release`:
> 
> ```
> distribution=$(. /etc/os-release;echo ubuntu$VERSION_ID) \
>    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
>    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> ```

It works,thanks a lot :D

**Comment by igarag** [comment]
Example of use:

```bash
distribution="Pop 20.04 LST" \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```

**Comment by elezar** [comment]
@AnalogKnight since you mentioned that it now works, I'm closing this issue. Please reopen or create a new one if you keep having problems.

Thanks for the comment @igarag

**Comment by csimpi** [comment]
@elezar @igarag this doesn't work for me, why "Pop 20.04 LTS" would work when that folder doesn't even exist? I don't understand how is this a "solution"?

I am still getting:

```
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker
```

**Comment by csimpi** [comment]
Using @AnalogKnight 's solution doesn't work either I am getting this error message:

```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: nvidia-container-toolkit (>= 1.8.1-1) but 1.5.1-1pop1~1627998766~20.04~9847cf2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by elezar** [comment]
@csimpi we mean, set `distribution` explicitly to `ubuntu18.04` (or `ubuntu20.04`) instead of an unsupported distribution.

The error you are seeing should also be addressed if you explicitly specify the versions for `nvidia-container-toolkit`, `libnvidia-container-tools` and `libnvidia-container1` as `1.8.1-1`.

**Comment by csimpi** [comment]
@elezar I don't get it. How do you mean explicitly? Can you please tell me what exactly should I use to be able to install on `Pop 20.04 LTS`. Thx

**Comment by elezar** [comment]
I mean that you run the following install command to explicitly specify the versions for the packages that are required by `nvidia-docker2`:
```
apt-get install nvidia-docker2=2.9.0-1 nvidia-container-toolkit=1.8.1-1 libnvidia-container-tools=1.8.1-1 libnvidia-container1=1.8.1-1
```

**Comment by csimpi** [comment]
@elezar Thank you I am going to try it and let you know.

**Comment by csimpi** [comment]
@elezar Finally I sorted it out.
It would have been much more useful if you would have told me the solution instead of throwing some breadcrumbs into the thread. 
For those who are still struggling, here is the way **how to install nvidia-docker on Pop Os**:

```
      distribution="ubuntu20.04" && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

      sudo apt-get update
      sudo apt-get install -y nvidia-docker2=2.9.0-1 nvidia-container-toolkit=1.8.1-1 libnvidia-container-tools=1.8.1-1 libnvidia-container1=1.8.1-1
      sudo systemctl restart docker
```

**Comment by ZaberKo** [comment]
Hello, For Pop OS 22.04 users, the solution is here:
* explicitly set `distribution="ubuntu22.04"`
* add a new preference entry in `/etc/apt/preferences.d/pop-default-settings`
  ```
  Package: *
  Pin: origin nvidia.github.io
  Pin-Priority: 1002
  ```
Note the preference entry is necessary, otherwise the dependencies versions are incorrect.

**Comment by dhrunia** [comment]
> Hello, For Pop OS 22.04 users, the solution is here:
> 
> * explicitly set `distribution="ubuntu22.04"`
> * add a new preference entry in `/etc/apt/preferences.d/pop-default-settings`
>   ```
>   Package: *
>   Pin: origin nvidia.github.io
>   Pin-Priority: 1002
>   ```
> 
> , then you can install `nvidia-docker2` without specifying the version. Note the preference entry is necessary, otherwise the versions of dependencies are incorrect.

This worked for me but after an update and restart the pop-default-settings somehow reverted to its default entries. Creating a new file for preferency entry seems to persist across updates.

Thank you, this worked fine!

**Comment by Warren-Wang-OG** [comment]
> This worked for me but after an update and restart the pop-default-settings somehow reverted to its default entries. Creating a new file for preferency entry seems to persist across updates.
>
>Thank you, this worked fine!

How would you do that? What would you name the file to write the new preference entry in as to be put into this same directory? Thanks.

**Comment by Warren-Wang-OG** [comment]
> Hello, For Pop OS 22.04 users, the solution is here:
> 
>     * explicitly set `distribution="ubuntu22.04"`
> 
>     * add a new preference entry in `/etc/apt/preferences.d/pop-default-settings`
>       ```
>       Package: *
>       Pin: origin nvidia.github.io
>       Pin-Priority: 1002
>       ```
> 
> 
> , then you can install `nvidia-docker2` without specifying the version. Note the preference entry is necessary, otherwise the versions of dependencies are incorrect.

This worked for me, thank you. Also, could you explain why the preference entry is necessary or why it is needed at all/what it does? Thank you.

**Comment by elezar** [comment]
My understanding is that pop has repositories that also provide these packages. These are set with a higher priority than the "official" repositories that we maintain.

Setting the distrubution is required because Pop OS is not an officially supported distrubution and as such the (compatible) Ubuntu packages should be selected.

**Comment by Warren-Wang-OG** [comment]
I see, I think that makes sense. Thank you.

**Comment by davidlbit** [comment]
Can someone of the Pop OS users here confirm the version of their nvidia container toolkit? Because I'm running Pop OS 22.04, and be running version 1.12.1, which seems weird to me since the latest version is 1.14.3, and so far I haven't found a way to force install the latest version, unless I install it from source.
