### ISSUE TITLE
The parseAddr() can't parse "ssh://root:hosehead@host"

### ISSUE THREAD

**Issue by NanXiao** [NVIDIA/nvidia-docker#147]
The [parseAddr()](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia-docker/env.go#L38) can't parse host URL like "`ssh://root:hosehead@host`". For example:  

```
# export NV_HOST=ssh://root:hosehead@10.100.3.3
# /go/src/github.com/NVIDIA/nvidia-docker/tools/bin/nvidia-docker run --rm nvidia/cuda nvidia-smi
/go/src/github.com/NVIDIA/nvidia-docker/tools/bin/nvidia-docker | 2016/07/21 05:11:29 Warning: NV_HOST is set but DOCKER_HOST is not
/go/src/github.com/NVIDIA/nvidia-docker/tools/bin/nvidia-docker | 2016/07/21 05:11:29 Error: invalid remote host URI
```

It must be wriiten like this: `ssh://root:hosehead@10.100.3.3:` (notie the colon at the end).

But according to this [document](https://tools.ietf.org/html/draft-ietf-secsh-scp-sftp-ssh-uri-01):  

```
The following section shows basic examples of URLs for each protocol.
This section should not be considered to include all possible
combinations of URLs for each protocol.

         ssh://user@host

         ssh://user@host:2222
```

Personally, I think "`ssh://root:hosehead@10.100.3.3`" should also be decoded.

**Comment by 3XX0** [comment]
You mean without the colon at the end? 
If so, this is intentional in order to be consistent with `DOCKER_HOST` (see [here](https://docs.docker.com/v1.10/engine/quickstart/#bind-docker-to-another-host-port-or-a-unix-socket))

**Comment by NanXiao** [comment]
@3XX0 Got it, thanks!
