### ISSUE TITLE
nvidia-docker2: automatically enable "--gpus all" for all containers, wo/ requiring argument

### ISSUE THREAD

**Issue by eugeneswalker** [NVIDIA/nvidia-docker#1471]
Is it possible to make `--gpus all` functionality enabled for all Docker containers, even those launched without `--gpus` ?

I'm using `Docker 20.10.4` on `x86_64` and `nvidia-docker2` package.

<img width="955" alt="Screen Shot 2021-03-08 at 8 36 31 AM" src="https://user-images.githubusercontent.com/38933153/110351156-64316b80-7fe9-11eb-862c-f5a81a93c052.png">
...
<img width="955" alt="Screen Shot 2021-03-08 at 8 36 46 AM" src="https://user-images.githubusercontent.com/38933153/110351192-6d223d00-7fe9-11eb-8949-f22b89d807c6.png">

Thank you!

**Comment by klueska** [comment]
The alternate way to inject GPUs when using the `nvidia-container-runtime` as you are is to set the environment variable `NVIDIA_VISIBLE_DEVICES=all`. There is no way to set that automatically for all containers though. You either need to set it on the docker command line with a `-e` or set it as an environment variable in your container image.

**Comment by eugeneswalker** [comment]
If NVIDIA_VISIBLE_DEVICES=all is set in a container image, then it is not necessary to use —gpus all ?

**Comment by eugeneswalker** [comment]
I was just testing this, and setting `NVIDIA_VISIBLE_DEVICES=all` still requires `--gpus all`. I'm trying to figure out how I can make the NVIDIA GPUs available to Docker containers launched as part of GitLab CI. With GitLab you can specify what Docker image you want to use, so it's no problem to set the environment variables, but I don't know of a way to add additional command line flags. Was hoping there was a way to do this at the Docker level, perhaps in `daemon.json` or elsewhere. Thanks for your quick response and help.

**Comment by klueska** [comment]
So long as you have the `default-runtime` set to `nvidia` in your `daemon.json`, i.e.:
```
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```
Then having `NVIDIA_VISIBLE_DEVICES=all` set in your container's environment is all you need trigger the injection of GPU devices into a container. The set of libraries injected is controlled by `NVIDIA_DRIVER_CAPABILITIES` (so you may want to set this to `NVIDIA_DRIVER_CAPABILITIES=all` for good measure), but something else is wrong in your setup if this isn't working.

**Comment by eugeneswalker** [comment]
Awesome! That's exactly what I was looking for. Thank you for your help!
