### ISSUE TITLE
Official documentation missmatch with last README.md change

### ISSUE THREAD

**Issue by MaKaNu** [NVIDIA/nvidia-docker#1474]
---

### 1. Issue description
The official documentation describes to use ```nvidia-docker2``` but before commit https://github.com/NVIDIA/nvidia-docker/commit/88a2fda83cb3cf42221931dbd0c08aa4370d4fe5 the README shows to use ```nvidia-container-toolkit``` because ```nvidia-docker2``` is deprecated.

### 2. Steps to reproduce the issue
Compare official Documentation Chapter "[Setting up NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit)" with diff of commit https://github.com/NVIDIA/nvidia-docker/commit/88a2fda83cb3cf42221931dbd0c08aa4370d4fe5 line 32

**Comment by klueska** [comment]
The `nvidia-docker2` package is very much *not* deprecated. It is unfortunate that it was ever announced as such.

You should use whatever is appropriate for your use case (and more often than not this is `nvidia-docker2` not simply `nvidia-container-toolkit`). Please see this comment I made a while back for a longer explanation:

https://github.com/NVIDIA/nvidia-docker/issues/1268#issuecomment-632692949

**Comment by MaKaNu** [comment]
Thx klueska, I think there should be a short reference because of diverse stackoverflow questions the message of deprecation is spreading and confusing still a lot of people.

**Comment by navierb** [comment]
It is very unfortunate. The documentation is a mess.
