### ISSUE TITLE
compatibility mode is UNAVAILABLE

### ISSUE THREAD

**Issue by leqiao-1** [NVIDIA/nvidia-docker#1479]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

Trying to run image nvcr.io/nvidia/tensorrt:20.07.1-py3 on ubuntu 18.04 with cuda driver version 440.33.01 and cuda version 10.2 . It shows error 
```
ERROR: This container was built for NVIDIA Driver Release 450.51 or later, but
       version 440.33.01 was detected and compatibility mode is UNAVAILABLE.

       [[CUDA Driver UNAVAILABLE (cuInit(0) returned 804)]]
```
However, driver version (440.33.01) is compatible with CUDA 11.0 so it will work without any issues.
See: https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility

### 2. Steps to reproduce the issue
install cuda 10.2 with driver version 440.33.01 on machine. 
docker pull nvcr.io/nvidia/tensorrt:20.07.1-py3
docker run -it --rm nvcr.io/nvidia/tensorrt:20.07.1-py3 /bin/bash 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 -- WARNING, the following logs are for debugging purposes only --

I0330 09:21:28.400631 255161 nvc.c:372] initializing library context (version=1.3.3, build=bd9fc3f2b642345301cb2e23de07ec5386232317)
I0330 09:21:28.400691 255161 nvc.c:346] using root /
I0330 09:21:28.400705 255161 nvc.c:347] using ldcache /etc/ld.so.cache
I0330 09:21:28.400719 255161 nvc.c:348] using unprivileged user 1006:1006
I0330 09:21:28.400756 255161 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0330 09:21:28.400916 255161 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
W0330 09:21:28.404534 255162 nvc.c:269] failed to set inheritable capabilities
W0330 09:21:28.404605 255162 nvc.c:270] skipping kernel modules load due to failure
I0330 09:21:28.404911 255163 driver.c:101] starting driver service
I0330 09:21:28.409110 255161 nvc_info.c:680] requesting driver information with ''
I0330 09:21:28.411403 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nvidia.so.440.33.01
I0330 09:21:28.411875 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvoptix.so.440.33.01
I0330 09:21:28.411984 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.440.33.01
I0330 09:21:28.412057 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.440.33.01
I0330 09:21:28.412129 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.440.33.01
I0330 09:21:28.412233 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.440.33.01
I0330 09:21:28.412338 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.440.33.01
I0330 09:21:28.412410 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.440.33.01
I0330 09:21:28.412521 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.440.33.01
I0330 09:21:28.412631 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.440.33.01
I0330 09:21:28.412699 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.440.33.01
I0330 09:21:28.412775 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.33.01
I0330 09:21:28.412844 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.440.33.01
I0330 09:21:28.412948 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.440.33.01
I0330 09:21:28.413024 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.440.33.01
I0330 09:21:28.413130 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.440.33.01
I0330 09:21:28.413201 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.440.33.01
I0330 09:21:28.413272 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.440.33.01
I0330 09:21:28.413380 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.440.33.01
I0330 09:21:28.413456 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.440.33.01
I0330 09:21:28.413568 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.440.33.01
I0330 09:21:28.414322 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.440.33.01
I0330 09:21:28.414668 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.440.33.01
I0330 09:21:28.414751 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.440.33.01
I0330 09:21:28.414829 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.440.33.01
I0330 09:21:28.414911 255161 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.440.33.01
W0330 09:21:28.414963 255161 nvc_info.c:350] missing library libnvidia-ngx.so
W0330 09:21:28.414979 255161 nvc_info.c:354] missing compat32 library libnvidia-ml.so
W0330 09:21:28.414994 255161 nvc_info.c:354] missing compat32 library libnvidia-cfg.so
W0330 09:21:28.415008 255161 nvc_info.c:354] missing compat32 library libcuda.so
W0330 09:21:28.415021 255161 nvc_info.c:354] missing compat32 library libnvidia-opencl.so
W0330 09:21:28.415034 255161 nvc_info.c:354] missing compat32 library libnvidia-ptxjitcompiler.so
W0330 09:21:28.415048 255161 nvc_info.c:354] missing compat32 library libnvidia-fatbinaryloader.so
W0330 09:21:28.415063 255161 nvc_info.c:354] missing compat32 library libnvidia-allocator.so
W0330 09:21:28.415077 255161 nvc_info.c:354] missing compat32 library libnvidia-compiler.so
W0330 09:21:28.415090 255161 nvc_info.c:354] missing compat32 library libnvidia-ngx.so
W0330 09:21:28.415104 255161 nvc_info.c:354] missing compat32 library libvdpau_nvidia.so
W0330 09:21:28.415117 255161 nvc_info.c:354] missing compat32 library libnvidia-encode.so
W0330 09:21:28.415131 255161 nvc_info.c:354] missing compat32 library libnvidia-opticalflow.so
W0330 09:21:28.415144 255161 nvc_info.c:354] missing compat32 library libnvcuvid.so
W0330 09:21:28.415158 255161 nvc_info.c:354] missing compat32 library libnvidia-eglcore.so
W0330 09:21:28.415171 255161 nvc_info.c:354] missing compat32 library libnvidia-glcore.so
W0330 09:21:28.415185 255161 nvc_info.c:354] missing compat32 library libnvidia-tls.so
W0330 09:21:28.415196 255161 nvc_info.c:354] missing compat32 library libnvidia-glsi.so
W0330 09:21:28.415209 255161 nvc_info.c:354] missing compat32 library libnvidia-fbc.so
W0330 09:21:28.415222 255161 nvc_info.c:354] missing compat32 library libnvidia-ifr.so
W0330 09:21:28.415236 255161 nvc_info.c:354] missing compat32 library libnvidia-rtcore.so
W0330 09:21:28.415253 255161 nvc_info.c:354] missing compat32 library libnvoptix.so
W0330 09:21:28.415263 255161 nvc_info.c:354] missing compat32 library libGLX_nvidia.so
W0330 09:21:28.415277 255161 nvc_info.c:354] missing compat32 library libEGL_nvidia.so
W0330 09:21:28.415294 255161 nvc_info.c:354] missing compat32 library libGLESv2_nvidia.so
W0330 09:21:28.415306 255161 nvc_info.c:354] missing compat32 library libGLESv1_CM_nvidia.so
W0330 09:21:28.415320 255161 nvc_info.c:354] missing compat32 library libnvidia-glvkspirv.so
W0330 09:21:28.415334 255161 nvc_info.c:354] missing compat32 library libnvidia-cbl.so
I0330 09:21:28.416301 255161 nvc_info.c:276] selecting /usr/bin/nvidia-smi
I0330 09:21:28.416344 255161 nvc_info.c:276] selecting /usr/bin/nvidia-debugdump
I0330 09:21:28.416385 255161 nvc_info.c:276] selecting /usr/bin/nvidia-persistenced
I0330 09:21:28.416427 255161 nvc_info.c:276] selecting /usr/bin/nvidia-cuda-mps-control
I0330 09:21:28.416467 255161 nvc_info.c:276] selecting /usr/bin/nvidia-cuda-mps-server
I0330 09:21:28.416520 255161 nvc_info.c:438] listing device /dev/nvidiactl
I0330 09:21:28.416534 255161 nvc_info.c:438] listing device /dev/nvidia-uvm
I0330 09:21:28.416545 255161 nvc_info.c:438] listing device /dev/nvidia-uvm-tools
I0330 09:21:28.416559 255161 nvc_info.c:438] listing device /dev/nvidia-modeset
W0330 09:21:28.416606 255161 nvc_info.c:321] missing ipc /var/run/nvidia-persistenced/socket
W0330 09:21:28.416639 255161 nvc_info.c:321] missing ipc /tmp/nvidia-mps
I0330 09:21:28.416653 255161 nvc_info.c:745] requesting device information with ''
I0330 09:21:28.423337 255161 nvc_info.c:628] listing device /dev/nvidia0 (GPU-5d5e028e-3e0a-055a-9e3f-e972e0354ab4 at 00000000:15:00.0)
I0330 09:21:28.429883 255161 nvc_info.c:628] listing device /dev/nvidia1 (GPU-1e5399af-79f7-fdad-4610-4c100d297498 at 00000000:2d:00.0)
NVRM version:   440.33.01
CUDA version:   10.2

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 1080
Brand:          GeForce
GPU UUID:       GPU-5d5e028e-3e0a-055a-9e3f-e972e0354ab4
Bus Location:   00000000:15:00.0
Architecture:   6.1

Device Index:   1
Device Minor:   1
Model:          GeForce GTX 1080
Brand:          GeForce
GPU UUID:       GPU-1e5399af-79f7-fdad-4610-4c100d297498
Bus Location:   00000000:2d:00.0
Architecture:   6.1
I0330 09:21:28.430018 255161 nvc.c:427] shutting down library context
I0330 09:21:28.430690 255163 driver.c:156] terminating driver service
I0330 09:21:28.431251 255161 driver.c:196] driver service terminated successfully

 - [x] Kernel version from `uname -a`
Linux aiinfra-linux2 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`
 
![image](https://user-images.githubusercontent.com/61653207/112966221-9b281680-917c-11eb-88d3-6ff41273bd36.png)

 - [x] Docker version from `docker version`
 Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:35:01 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 
![image](https://user-images.githubusercontent.com/61653207/112966352-bc890280-917c-11eb-99d2-937b8957ff40.png)

 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 version: 1.3.3
build date: 2021-02-05T13:29+00:00
build revision: bd9fc3f2b642345301cb2e23de07ec5386232317
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by elezar** [comment]
HI @leqiao-1. I would assume that the developers of the [tensorrt:20.07.1-py3](https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt/layers) image you mention are explicitly (or inadvertently) setting a `CUDA_VERSION` or `NVIDIA_REQUIRE_CUDA` version that differs from the support matrix that you reference.

You could try to launch the container with `-e NVIDIA_DISABLE_REQUIRE=true` to bypass the check that is being performed.

This assumes that there is no specific reason for the container developers to have selected a later driver version.

**Comment by leqiao-1** [comment]
Thanks for your reply. The error still appears. 
![image](https://user-images.githubusercontent.com/61653207/112972069-7171ee00-9182-11eb-8a95-dd16e3bf9906.png)
CUDNN_VERSION=8.0.1.13
NSIGHT_SYSTEMS_VERSION=2020.3.2.6
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
LESSCLOSE=/usr/bin/lesspipe %s %s
HOSTNAME=5c677201e670
NVIDIA_TENSORRT_VERSION=20.07.1
MOFED_VERSION=4.6-1.0.1
NVIDIA_VISIBLE_DEVICES=all
NSIGHT_COMPUTE_VERSION=2020.1.1.8
ENV=/etc/shinit_v2
CURAND_VERSION=10.2.1.218
CUDA_DRIVER_VERSION=450.51.05
NCCL_VERSION=2.7.6
CUFFT_VERSION=10.2.0.218
PWD=/workspace
DALI_VERSION=0.23.0
HOME=/root
NVIDIA_DISABLE_REQUIRE=true
_CUDA_COMPAT_STATUS=CUDA Driver UNAVAILABLE (cuInit(0) returned 804)
TRT_VERSION=7.1.3.4
OPENMPI_VERSION=3.1.6
BASH_ENV=/etc/bash.bashrc
LIBRARY_PATH=/usr/local/cuda/lib64/stubs:
NVIDIA_BUILD_ID=15171959
TERM=xterm
CUDA_VERSION=11.0.194
CUSPARSE_VERSION=11.1.0.218
NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
SHLVL=1
TENSORRT_VERSION=7.1.3
NVIDIA_REQUIRE_CUDA=cuda>=9.0
OPENUCX_VERSION=1.6.1
CUDA_CACHE_DISABLE=1
DALI_BUILD=1396141
CUBLAS_VERSION=11.1.0.229
NPP_VERSION=11.1.0.218
PATH=/opt/tensorrt/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin
IBV_DRIVERS=/usr/lib/libibverbs/libmlx5
CUSOLVER_VERSION=10.5.0.218
NVJPEG_VERSION=11.1.0.218
_CUDA_COMPAT_PATH=/usr/local/cuda/compat
LESSOPEN=| /usr/bin/lesspipe %s

**Comment by elezar** [comment]
yes, after further investigation it is not expected that setting `NVIDIA_DIABLE_REQUIRE` would have the desired effect. This issue is not due to `nvidia-docker` though, and as such, would suggest that you reach out to the TensorRT team for guidance on how to address that (apart from modifying the container entrypoint).

**Comment by klueska** [comment]
This is the line of code in `libnvidia-container` that is responsible for injecting the CUDA forward compatability libraries into a container.

https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc_container.c#L221

It seems for some reason this is not being triggered in your environment if forward compatibility is not working.

Can you verify that you have the CUDA compatibility libraries installed on your host (not the container, the host):
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-compatibility-platform

**Comment by leqiao-1** [comment]
Thanks for your reply.
ls: cannot access '/usr/local/cuda/compat': No such file or directory

I think I can run the same tests three months ago without any issue on the same machine.

**Comment by klueska** [comment]
If the compatibility libraries are bundled in the container, then this would also work (it's not required to inject them from the host, but it will if they are available). I'm guessing the image you are using changed recently and (for some reason) stopped bundling the compat libraries inside of it.

In any case, if you have the ability to install the compat libraries on your host, that will ensure it works for all containers (whether they have the compat libraries bundled or not).

**Comment by leqiao-1** [comment]
Thanks, I will have a try.
