### ISSUE TITLE
nvidia-smi not found when using nvidia/cuda:* images in WSL2/Ubuntu 20.04

### ISSUE THREAD

**Issue by f0r4y312** [NVIDIA/nvidia-docker#1482]
### 1. Issue or feature description
nvidia-smi is not found when running docker images from nvidia/cuda in WSL2/Ubuntu 20.04.
Trying to run nvidia-smi in a docker image with gives this error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "nvidia-smi": executable file not found in $PATH: unknown.
```
Interacting with the image shows that the $PATH is set to: `/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
Inspecting further shows that there is no `/usr/local/nvidia` in the image.
```
ls -al /usr/local/nvidia
ls: cannot access '/usr/local/nvidia': No such file or directory
```
```
ls -al /usr/local/cuda/bin
total 81176
drwxr-xr-x 3 root root     4096 Mar 15 17:36 .
drwxr-xr-x 1 root root     4096 Mar 15 17:36 ..
-rwxr-xr-x 1 root root    80608 Feb 15 19:41 bin2c
-rwxr-xr-x 1 root root       97 Feb 15 19:45 compute-sanitizer
drwxr-xr-x 2 root root     4096 Mar 15 17:35 crt
-rwxr-xr-x 1 root root    75880 Feb 15 19:43 cu++filt
-rwxr-xr-x 1 root root 12037592 Feb 15 19:34 cuda-gdb
-rwxr-xr-x 1 root root   753560 Feb 15 19:34 cuda-gdbserver
-rwxr-xr-x 1 root root   353752 Feb 15 19:35 cuda-memcheck
-rwxr-xr-x 1 root root  5203888 Feb 15 19:41 cudafe++
-rwxr-xr-x 1 root root   236864 Feb 15 19:35 cuobjdump
-rwxr-xr-x 1 root root   269392 Feb 15 19:41 fatbinary
-rwxr-xr-x 1 root root  5477800 Feb 15 19:41 nvcc
-rw-r--r-- 1 root root      417 Feb 15 19:41 nvcc.profile
-rwxr-xr-x 1 root root 33711208 Feb 15 19:34 nvdisasm
-rwxr-xr-x 1 root root  9665864 Feb 15 19:41 nvlink
-rwxr-xr-x 1 root root  5609832 Feb 15 19:42 nvprof
-rwxr-xr-x 1 root root   101296 Feb 15 19:34 nvprune
-rwxr-xr-x 1 root root  9504928 Feb 15 19:41 ptxas
```
### 2. Steps to reproduce the issue
`docker run --rm --gpus 'all,"capabilities=compute,utility"' --env NVIDIA_DISABLE_REQUIRE=1 nvidia/cuda:11.2.2-devel-ubuntu20.04 nvidia-smi`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

```
uname -a

Linux jupiter 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
[nvidia-container-cli.txt](https://github.com/NVIDIA/nvidia-docker/files/6252330/nvidia-container-cli.txt)
[nvidia-smi.txt](https://github.com/NVIDIA/nvidia-docker/files/6252331/nvidia-smi.txt)
[dpkg_nvidia.txt](https://github.com/NVIDIA/nvidia-docker/files/6252332/dpkg_nvidia.txt)
[docker_version.txt](https://github.com/NVIDIA/nvidia-docker/files/6252333/docker_version.txt)

**Comment by grapefruitL** [comment]
did u solve this? i face the same problem :( @f0r4y312
