### ISSUE TITLE
NVML (`nvidia-smi`) gets wrong PIDs

### ISSUE THREAD

**Issue by XuehaiPan** [NVIDIA/nvidia-docker#1483]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

The NVIDIA Management Library (NVML) gets wrong PIDs inside docker container. `nvidia-smi` reports the actural PIDs on host instead of the PIDs inside container (`docker run` without `--pid=host` flag).

### 2. Steps to reproduce the issue

1. Create a docker image with `cupy` (I use this to create a process using GPUs. It's OK to use other tools.).

```dockerfile
FROM nvidia/cuda:10.1-devel-ubi7

RUN yum install -y rh-python38
ENV PATH="/opt/rh/rh-python38/root/usr/local/bin:/opt/rh/rh-python38/root/usr/bin:${PATH}"
RUN pip3 install cupy-cuda101 nvidia-ml-py ipython

ENTRYPOINT [ "bash", "--login" ]
```

Then build this image:
```console
# On host OS
$ docker build --tag cuda101-python38 .
```

2. Run nvidia-docker without `--pid=host` flag:

```console
# On host OS
$ docker run -it --gpus all -h cuda-devel cuda101-python38

# Inside container
[root@cuda-devel /]# ipython3
Python 3.8.6 (default, Oct  7 2020, 14:58:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cupy as cp

In [2]: x = cp.zeros((1000, 1000))

In [3]: import os

In [4]: os.getpid()
Out[4]: 19  # press Ctrl+Z to suspend process


[1]+  Stopped                 ipython3
[root@cuda-devel /]# nvidia-smi --query-compute-apps=pid,name,used_gpu_memory --format=csv
pid, process_name, used_gpu_memory [MiB]
40170, [Not Found], 185 MiB
[root@cuda-devel /]# nvidia-smi
Sun Apr  4 08:21:51 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:04:00.0 Off |                  N/A |
| 22%   28C    P2    49W / 250W |    195MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   20C    P8    14W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:06:00.0 Off |                  N/A |
| 22%   21C    P8    19W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:07:00.0 Off |                  N/A |
| 22%   23C    P8    24W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:08:00.0 Off |                  N/A |
| 22%   23C    P8    18W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 22%   20C    P8    21W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:0C:00.0 Off |                  N/A |
| 22%   22C    P8    22W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:0D:00.0 Off |                  N/A |
| 22%   22C    P8     9W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   8  GeForce RTX 208...  Off  | 00000000:0E:00.0 Off |                  N/A |
| 22%   25C    P8     9W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   9  GeForce RTX 208...  Off  | 00000000:0F:00.0 Off |                  N/A |
| 22%   25C    P8     9W / 250W |     10MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
[root@cuda-devel /]# 
```

Inside container, the PID of `ipython3` is 19, but `nvidia-smi` gets 40170, which is the real PID on the host OS. `nvidia-smi` can't find the 40170 process **(wrong PID, don't exist at all)** in container, so it shows a empty process panel.

3. Check PIDs on host OS:

```console
# On host OS
$ nvidia-smi --query-compute-apps=pid,name,used_gpu_memory --format=csv
pid, process_name, used_gpu_memory [MiB]
40170, /opt/rh/rh-python38/root/usr/bin/python3, 185 MiB
```

On host OS, `nvidia-smi` gets PID of 40170, which is exactly the `nvidia-smi` reports inside container. But the PID of `ipython3` is 19 inside container,

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [X] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`

> -- WARNING, the following logs are for debugging purposes only --
> 
> I0404 08:30:20.796431 49717 nvc.c:372] initializing library context (version=1.3.3, build=bd9fc3f2b642345301cb2e23de07ec5386232317)
> I0404 08:30:20.796501 49717 nvc.c:346] using root /
> I0404 08:30:20.796512 49717 nvc.c:347] using ldcache /etc/ld.so.cache
> I0404 08:30:20.796522 49717 nvc.c:348] using unprivileged user 1013:1013
> I0404 08:30:20.796560 49717 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
> I0404 08:30:20.796753 49717 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
> W0404 08:30:20.804225 49718 nvc.c:269] failed to set inheritable capabilities
> W0404 08:30:20.804311 49718 nvc.c:270] skipping kernel modules load due to failure
> I0404 08:30:20.804579 49719 driver.c:101] starting driver service
> I0404 08:30:20.814810 49717 nvc_info.c:680] requesting driver information with ''
> I0404 08:30:20.817203 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/vdpau/libvdpau_nvidia.so.430.64
> I0404 08:30:20.817399 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvoptix.so.430.64
> I0404 08:30:20.817455 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-tls.so.430.64
> I0404 08:30:20.817503 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-rtcore.so.430.64
> I0404 08:30:20.817551 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-ptxjitcompiler.so.430.64
> I0404 08:30:20.817607 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-opticalflow.so.430.64
> I0404 08:30:20.817665 49717 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.430.64
> I0404 08:30:20.817704 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-ml.so.430.64
> I0404 08:30:20.817764 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-ifr.so.430.64
> I0404 08:30:20.817822 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-glvkspirv.so.430.64
> I0404 08:30:20.817866 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-glsi.so.430.64
> I0404 08:30:20.817907 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-glcore.so.430.64
> I0404 08:30:20.817946 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-fbc.so.430.64
> I0404 08:30:20.817999 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-fatbinaryloader.so.430.64
> I0404 08:30:20.818045 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-encode.so.430.64
> I0404 08:30:20.818100 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-eglcore.so.430.64
> I0404 08:30:20.818140 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-cfg.so.430.64
> I0404 08:30:20.818195 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvidia-cbl.so.430.64
> I0404 08:30:20.818237 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libnvcuvid.so.430.64
> I0404 08:30:20.818525 49717 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.430.64
> I0404 08:30:20.818727 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libGLX_nvidia.so.430.64
> I0404 08:30:20.818771 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libGLESv2_nvidia.so.430.64
> I0404 08:30:20.818812 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libGLESv1_CM_nvidia.so.430.64
> I0404 08:30:20.818855 49717 nvc_info.c:169] selecting /usr/lib/nvidia-430/libEGL_nvidia.so.430.64
> I0404 08:30:20.818922 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/vdpau/libvdpau_nvidia.so.430.64
> I0404 08:30:20.818971 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-tls.so.430.64
> I0404 08:30:20.819007 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-ptxjitcompiler.so.430.64
> I0404 08:30:20.819061 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-opticalflow.so.430.64
> I0404 08:30:20.819117 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-ml.so.430.64
> I0404 08:30:20.819173 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-ifr.so.430.64
> I0404 08:30:20.819226 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-glvkspirv.so.430.64
> I0404 08:30:20.819262 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-glsi.so.430.64
> I0404 08:30:20.819302 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-glcore.so.430.64
> I0404 08:30:20.819341 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-fbc.so.430.64
> I0404 08:30:20.819395 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-fatbinaryloader.so.430.64
> I0404 08:30:20.819435 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-encode.so.430.64
> I0404 08:30:20.819489 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvidia-eglcore.so.430.64
> I0404 08:30:20.819530 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libnvcuvid.so.430.64
> I0404 08:30:20.819593 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libGLX_nvidia.so.430.64
> I0404 08:30:20.819635 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libGLESv2_nvidia.so.430.64
> I0404 08:30:20.819679 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libGLESv1_CM_nvidia.so.430.64
> I0404 08:30:20.819719 49717 nvc_info.c:169] selecting /usr/lib32/nvidia-430/libEGL_nvidia.so.430.64
> W0404 08:30:20.819741 49717 nvc_info.c:350] missing library libnvidia-allocator.so
> W0404 08:30:20.819750 49717 nvc_info.c:350] missing library libnvidia-compiler.so
> W0404 08:30:20.819757 49717 nvc_info.c:350] missing library libnvidia-ngx.so
> W0404 08:30:20.819763 49717 nvc_info.c:354] missing compat32 library libnvidia-cfg.so
> W0404 08:30:20.819769 49717 nvc_info.c:354] missing compat32 library libcuda.so
> W0404 08:30:20.819777 49717 nvc_info.c:354] missing compat32 library libnvidia-opencl.so
> W0404 08:30:20.819783 49717 nvc_info.c:354] missing compat32 library libnvidia-allocator.so
> W0404 08:30:20.819788 49717 nvc_info.c:354] missing compat32 library libnvidia-compiler.so
> W0404 08:30:20.819795 49717 nvc_info.c:354] missing compat32 library libnvidia-ngx.so
> W0404 08:30:20.819802 49717 nvc_info.c:354] missing compat32 library libnvidia-rtcore.so
> W0404 08:30:20.819810 49717 nvc_info.c:354] missing compat32 library libnvoptix.so
> W0404 08:30:20.819815 49717 nvc_info.c:354] missing compat32 library libnvidia-cbl.so
> I0404 08:30:20.821227 49717 nvc_info.c:276] selecting /usr/lib/nvidia-430/bin/nvidia-smi
> I0404 08:30:20.821279 49717 nvc_info.c:276] selecting /usr/lib/nvidia-430/bin/nvidia-debugdump
> I0404 08:30:20.821323 49717 nvc_info.c:276] selecting /usr/lib/nvidia-430/bin/nvidia-persistenced
> I0404 08:30:20.821367 49717 nvc_info.c:276] selecting /usr/lib/nvidia-430/bin/nvidia-cuda-mps-control
> I0404 08:30:20.821410 49717 nvc_info.c:276] selecting /usr/lib/nvidia-430/bin/nvidia-cuda-mps-server
> I0404 08:30:20.821439 49717 nvc_info.c:438] listing device /dev/nvidiactl
> I0404 08:30:20.821446 49717 nvc_info.c:438] listing device /dev/nvidia-uvm
> I0404 08:30:20.821454 49717 nvc_info.c:438] listing device /dev/nvidia-uvm-tools
> I0404 08:30:20.821461 49717 nvc_info.c:438] listing device /dev/nvidia-modeset
> W0404 08:30:20.821489 49717 nvc_info.c:321] missing ipc /var/run/nvidia-persistenced/socket
> W0404 08:30:20.821507 49717 nvc_info.c:321] missing ipc /tmp/nvidia-mps
> I0404 08:30:20.821515 49717 nvc_info.c:745] requesting device information with ''
> I0404 08:30:20.831279 49717 nvc_info.c:628] listing device /dev/nvidia0 (GPU-f9ca790e-683e-3d56-00ba-8f654e977e02 at 00000000:04:00.0)
> I0404 08:30:20.841046 49717 nvc_info.c:628] listing device /dev/nvidia1 (GPU-f8e5a624-2c7e-417c-e647-b764d26d4733 at 00000000:05:00.0)
> I0404 08:30:20.852664 49717 nvc_info.c:628] listing device /dev/nvidia2 (GPU-6d2a57c9-7783-44bb-9f53-13f36282830a at 00000000:06:00.0)
> I0404 08:30:20.865852 49717 nvc_info.c:628] listing device /dev/nvidia3 (GPU-2428d171-8684-5b64-830c-435cd972ec4a at 00000000:07:00.0)
> I0404 08:30:20.879242 49717 nvc_info.c:628] listing device /dev/nvidia4 (GPU-96de99c9-d68f-84c8-424c-7c75e59cc0a0 at 00000000:08:00.0)
> I0404 08:30:20.892865 49717 nvc_info.c:628] listing device /dev/nvidia5 (GPU-18ef14e9-dec6-1d7e-1284-3010c6ce98b1 at 00000000:0b:00.0)
> I0404 08:30:20.906648 49717 nvc_info.c:628] listing device /dev/nvidia6 (GPU-849d5a8d-610e-eeea-1fd4-81ff44a23794 at 00000000:0c:00.0)
> I0404 08:30:20.921160 49717 nvc_info.c:628] listing device /dev/nvidia7 (GPU-843ecb19-b449-3be8-f49c-27697124f714 at 00000000:0d:00.0)
> I0404 08:30:20.935803 49717 nvc_info.c:628] listing device /dev/nvidia8 (GPU-55f97fef-2770-f1da-8757-04b458ab93fe at 00000000:0e:00.0)
> I0404 08:30:20.950353 49717 nvc_info.c:628] listing device /dev/nvidia9 (GPU-6ec821a6-121f-02b1-43d1-73e0e24c3229 at 00000000:0f:00.0)
> NVRM version:   430.64
> CUDA version:   10.1
> 
> Device Index:   0
> Device Minor:   0
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-f9ca790e-683e-3d56-00ba-8f654e977e02
> Bus Location:   00000000:04:00.0
> Architecture:   7.5
> 
> Device Index:   1
> Device Minor:   1
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-f8e5a624-2c7e-417c-e647-b764d26d4733
> Bus Location:   00000000:05:00.0
> Architecture:   7.5
> 
> Device Index:   2
> Device Minor:   2
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-6d2a57c9-7783-44bb-9f53-13f36282830a
> Bus Location:   00000000:06:00.0
> Architecture:   7.5
> 
> Device Index:   3
> Device Minor:   3
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-2428d171-8684-5b64-830c-435cd972ec4a
> Bus Location:   00000000:07:00.0
> Architecture:   7.5
> 
> Device Index:   4
> Device Minor:   4
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-96de99c9-d68f-84c8-424c-7c75e59cc0a0
> Bus Location:   00000000:08:00.0
> Architecture:   7.5
> 
> Device Index:   5
> Device Minor:   5
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-18ef14e9-dec6-1d7e-1284-3010c6ce98b1
> Bus Location:   00000000:0b:00.0
> Architecture:   7.5
> 
> Device Index:   6
> Device Minor:   6
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-849d5a8d-610e-eeea-1fd4-81ff44a23794
> Bus Location:   00000000:0c:00.0
> Architecture:   7.5
> 
> Device Index:   7
> Device Minor:   7
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-843ecb19-b449-3be8-f49c-27697124f714
> Bus Location:   00000000:0d:00.0
> Architecture:   7.5
> 
> Device Index:   8
> Device Minor:   8
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-55f97fef-2770-f1da-8757-04b458ab93fe
> Bus Location:   00000000:0e:00.0
> Architecture:   7.5
> 
> Device Index:   9
> Device Minor:   9
> Model:          GeForce RTX 2080 Ti
> Brand:          GeForce
> GPU UUID:       GPU-6ec821a6-121f-02b1-43d1-73e0e24c3229
> Bus Location:   00000000:0f:00.0
> Architecture:   7.5
> I0404 08:30:20.950756 49717 nvc.c:427] shutting down library context
> I0404 08:30:20.960748 49719 driver.c:156] terminating driver service
> I0404 08:30:20.961523 49717 driver.c:196] driver service terminated successfully

 - [X] Kernel version from `uname -a`

Linux ubuntu 4.4.0-206-generic #238-Ubuntu SMP Tue Mar 16 07:52:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [X] Docker version from `docker version`

Docker version 20.10.5, build 55c4c88

 - [X] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name                                                Version                        Architecture                   Description
> +++-===================================================-==============================-==============================-============================================================================================================
> ii  libnvidia-container-tools                           1.3.3-1                        amd64                          NVIDIA container runtime library (command-line tools)
> ii  libnvidia-container1:amd64                          1.3.3-1                        amd64                          NVIDIA container runtime library
> un  nvidia-304                                          <none>                         <none>                         (no description available)
> un  nvidia-340                                          <none>                         <none>                         (no description available)
> un  nvidia-384                                          <none>                         <none>                         (no description available)
> rc  nvidia-410                                          410.78-0ubuntu0~gpu16.04.1     amd64                          NVIDIA binary driver - version 410.78
> ii  nvidia-430                                          430.64-0ubuntu0~gpu16.04.6     amd64                          NVIDIA binary driver - version 430.64
> un  nvidia-common                                       <none>                         <none>                         (no description available)
> ii  nvidia-container-runtime                            3.4.2-1                        amd64                          NVIDIA container runtime
> un  nvidia-container-runtime-hook                       <none>                         <none>                         (no description available)
> ii  nvidia-container-toolkit                            1.4.2-1                        amd64                          NVIDIA container runtime hook
> un  nvidia-docker                                       <none>                         <none>                         (no description available)
> ii  nvidia-docker2                                      2.5.0-1                        all                            nvidia-docker CLI wrapper
> un  nvidia-driver-binary                                <none>                         <none>                         (no description available)
> un  nvidia-legacy-340xx-vdpau-driver                    <none>                         <none>                         (no description available)
> un  nvidia-libopencl1-410                               <none>                         <none>                         (no description available)
> un  nvidia-libopencl1-430                               <none>                         <none>                         (no description available)
> un  nvidia-libopencl1-dev                               <none>                         <none>                         (no description available)
> un  nvidia-opencl-icd                                   <none>                         <none>                         (no description available)
> rc  nvidia-opencl-icd-410                               410.78-0ubuntu0~gpu16.04.1     amd64                          NVIDIA OpenCL ICD
> ii  nvidia-opencl-icd-430                               430.64-0ubuntu0~gpu16.04.6     amd64                          NVIDIA OpenCL ICD
> un  nvidia-persistenced                                 <none>                         <none>                         (no description available)
> ii  nvidia-prime                                        0.8.2                          amd64                          Tools to enable NVIDIA's Prime
> ii  nvidia-settings                                     418.56-0ubuntu0~gpu16.04.1     amd64                          Tool for configuring the NVIDIA graphics driver
> un  nvidia-settings-binary                              <none>                         <none>                         (no description available)
> un  nvidia-smi                                          <none>                         <none>                         (no description available)
> un  nvidia-vdpau-driver                                 <none>                         <none>                         (no description available)

 - [X] NVIDIA container library version from `nvidia-container-cli -V`

> version: 1.3.3
> build date: 2021-02-05T13:29+00:00
> build revision: bd9fc3f2b642345301cb2e23de07ec5386232317
> build compiler: gcc-5 5.4.0 20160609
> build platform: x86_64
> build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [X] Docker command, image and tag used

```console
$ docker run -it --gpus all -h cuda-devel nvidia/cuda:10.1-devel-ubi7
```

**Comment by XuehaiPan** [comment]
Besides, `nvidia-smi` gets the real pids on host OS instead of the pids inside the container, which means `nvidia-smi` inside container can access the pids outside of container (on host OS).

`nvidia-smi` can get the pids on host OS, but the same pids don't exist inside the container. So the process panel below the output is empty. (Answer for issue #1460)

![Screenshot](https://user-images.githubusercontent.com/16078332/113504008-005a7e00-9568-11eb-916b-3cf290eefcf6.png)

If I mount `/proc` to the container, `nvidia-smi` can get the process names and show a non-empty process panel (with wrong pids). But this breaks the key concept of isolation for docker.

**Comment by klueska** [comment]
There is nothing nvidia-docker can do to address this. The nvidia-driver itself does not support pid-namespaces, so anytime you query it for the set of processes that are using GPUs, you will always get the host pids, not the container pids.
