### ISSUE TITLE
Command line completion

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#149]
Docker has command line completion, but nvidia-docker does not. Could this functionality be added back to nvidia-docker? 

For example, if I want to `rm` a container by its name, I can tab-complete the name with `docker rm`, but not with `nvidia-docker rm`. It looks like docker implements this capability [here](https://github.com/docker/docker/blob/master/contrib/completion/bash/docker).

**Comment by flx42** [comment]
For bash, there is a small trick to do that manually, just copy the completion file from Docker and just change the last line. As a single command:
```
sed 's/_docker docker/_docker nvidia-docker/' /etc/bash_completion.d/docker | sudo tee /etc/bash_completion.d/nvidia-docker
```

I don't think we're ever going to do that in our installer since we rely on the file from another package, but I hope that helps!
