### ISSUE TITLE
Cannot download nvidia-container-toolkit

### ISSUE THREAD

**Issue by siyangxie** [NVIDIA/nvidia-docker#1493]
I'm on Ubuntu 18.04 and I'm trying to download and use nvidia-container-toolkit from China. Firstly I can only manually update `/etc/apt/sources.list.d/nvidia-docker.list` with:
```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```

But then when I try `apt-get update`, it gives the error:
```
Hit:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu bionic InRelease
Get:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu bionic-updates InRelease [88.7 kB]
Err:3 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease
  Could not connect to nvidia.github.io:443 (::1). - connect (111: Connection refused) Could not connect to nvidia.github.io:443 (127.0.0.1). - connect (111: Connection refused)
Err:4 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64  InRelease               
  Unable to connect to nvidia.github.io:https:
Err:5 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease                                 
  Unable to connect to nvidia.github.io:https:
Hit:6 http://dl.google.com/linux/chrome/deb stable InRelease                                              
Hit:7 https://download.docker.com/linux/ubuntu bionic InRelease                                           
Get:8 https://mirrors.tuna.tsinghua.edu.cn/ubuntu bionic-backports InRelease [74.6 kB]                    
Get:9 https://mirrors.tuna.tsinghua.edu.cn/ubuntu bionic-security InRelease [88.7 kB]                     
Fetched 252 kB in 10s (24.5 kB/s)                                                                         
Reading package lists... Done
W: Failed to fetch https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/InRelease  Could not connect to nvidia.github.io:443 (::1). - connect (111: Connection refused) Could not connect to nvidia.github.io:443 (127.0.0.1). - connect (111: Connection refused)
W: Failed to fetch https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64/InRelease  Unable to connect to nvidia.github.io:https:
W: Failed to fetch https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/InRelease  Unable to connect to nvidia.github.io:https:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

I keep stucking here so please advise. Thanks!!

**Comment by elezar** [comment]
Can you `curl -L -v https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64`, for example?

**Comment by elezar** [comment]
Also, it seems as if `nvidia.github.io` is resolving to `localhost` (from the error message `nvidia.github.io:443 (127.0.0.1)`). There may be something in your `/etc/hosts` file that is causing this name to be resolved incorrectly as per #1389

**Comment by SiyangXie** [comment]
> Can you `curl -L -v https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64`, for example?

No, I can't. Seems like the GFW is preventing me from visiting? It gives the error:
```
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 443 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 443 failed: Connection refused
* Failed to connect to nvidia.github.io port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to nvidia.github.io port 443: Connection refused
```

**Comment by SiyangXie** [comment]
> Also, it seems as if `nvidia.github.io` is resolving to `localhost` (from the error message `nvidia.github.io:443 (127.0.0.1)`). There may be something in your `/etc/hosts` file that is causing this name to be resolved incorrectly as per #1389

I don't think my hosts file is messed up tho. I just had my ubuntu installed from scratch. Here it goes:
```
127.0.0.1       localhost
127.0.1.1       xiesiyang-Desktop

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by elezar** [comment]
Running `dig nvidia.github.io` should show you what is causing the name to resolve to local host.

```
;; QUESTION SECTION:
;nvidia.github.io.		IN	A

;; ANSWER SECTION:
nvidia.github.io.	1722	IN	A	185.199.110.153
nvidia.github.io.	1722	IN	A	185.199.108.153
nvidia.github.io.	1722	IN	A	185.199.111.153
nvidia.github.io.	1722	IN	A	185.199.109.153

;; AUTHORITY SECTION:
.			27278	IN	NS	l.root-servers.net.
.			27278	IN	NS	f.root-servers.net.
.			27278	IN	NS	b.root-servers.net.
```

**Comment by SiyangXie** [comment]
> Running `dig nvidia.github.io` should show you what is causing the name to resolve to local host.
> 
> ```
> ;; QUESTION SECTION:
> ;nvidia.github.io.		IN	A
> 
> ;; ANSWER SECTION:
> nvidia.github.io.	1722	IN	A	185.199.110.153
> nvidia.github.io.	1722	IN	A	185.199.108.153
> nvidia.github.io.	1722	IN	A	185.199.111.153
> nvidia.github.io.	1722	IN	A	185.199.109.153
> 
> ;; AUTHORITY SECTION:
> .			27278	IN	NS	l.root-servers.net.
> .			27278	IN	NS	f.root-servers.net.
> .			27278	IN	NS	b.root-servers.net.
> ```

Is it the GFW causing this...?
```
; <<>> DiG 9.11.3-1ubuntu1.14-Ubuntu <<>> nvidia.github.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35843
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;nvidia.github.io.		IN	A

;; ANSWER SECTION:
nvidia.github.io.	972	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Apr 23 16:50:14 CST 2021
;; MSG SIZE  rcvd: 61
```

**Comment by elezar** [comment]
I don't know what is causing that. It does seem as if the name resolution is happening locally somewhere though.

**Comment by mkj880** [comment]
I solved  the problem by the following method.

1. Download the latest "libnvidia-container1" from the following URL.
(ex) libnvidia-container1_1.4.0-1_amd64.deb
"https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/ubuntu18.04/amd64"

2. Run "dpkg -i <downloaded package>"

3. Run "sudo apt install libnvidia-container 1"
(This seems to install nvidia-docker2)

Confirmation method
1. Run "sudo systemctl restart docker"

2. Run "sudo docker run --rm --gpus all nvidia / cuda: 11.0-base nvidia-smi"

 If the same scene as "nvidia-smi" appears, it is a success.
