### ISSUE TITLE
Ubuntu 20.04 nvidia-docker.list contains 18.04

### ISSUE THREAD

**Issue by igtrnt** [NVIDIA/nvidia-docker#1497]
Contents of

https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list

are

> deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /

**Comment by desreumaux** [comment]
hello,
i have a big problem with UBUNTU 20.04
UBUNTU 20.04 cannot find a working driver for nvidia GTX 1050
I tested all the possibilities offered by UBUNTU including "nouveau", nothing works.
my machine is in dual boot Windows 10 and UBUNTU 20.04.
under windows the graphical operation is perfect the result of Unigine Valley is FPS: 31.7 Score 1327
under UBUNTU the Unigine Valley result is at best FPS: 3.6 Score 152
I am looking for someone who has already been confronted with this problem and who would know a solution

thank you in advance
Jacques

**Comment by klueska** [comment]
@igtrnt

This is expected. As of right now, the 20.04 folder in the apt-repo is just a symlink to the 18.04 one. We would like to introduce a better layout for our apt-repo in the future, but it is not currently a high priority.
