### ISSUE TITLE
OCI hooks for podman in Debian??

### ISSUE THREAD

**Issue by jmpolom** [NVIDIA/nvidia-docker#1499]
Does the Debian version of nvidia-container-toolkit also install the `oci-nvidia-hook` for use with podman? It would appear from reviewing the [package install file](https://github.com/NVIDIA/nvidia-container-toolkit/blob/master/packaging/debian/nvidia-container-toolkit.install) that it is not included.

Podman is now in Debian Testing and will be included in the next stable release of Debian. Would make sense to start including this in the packaging.

**Comment by jmpolom** [comment]
Truly a great reason to use AMD GPUs instead of nvidia.

**Comment by elezar** [comment]
@jmpolom @jonorthwash you should be able to install the existing Debian packages on Debian stable. One thing to note is that if you are using cgroupv2 you will have to use at least `1.8.0-rc.1` of the NVIDIA Container Toolkit (see, for example, https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375).

You are correct that the Debian package does not install the podman OCI hook as is and this would have to be created after the fact as per our [documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#id10).

We are in the process of improving our configuration tooling and it would make sense to include support for podman in this work too.

**Comment by elezar** [comment]
Please see the updated [installation documenation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

Note specifically the podman configuration instructions.

Please create an issue against https://github.com/NVIDIA/nvidia-container-toolkit if there are still problems.
