### ISSUE TITLE
Unable to connect to plugin

### ISSUE THREAD

**Issue by lukeforehand** [NVIDIA/nvidia-docker#150]
I have the nvidia-docker-plugin running, and when I run nvidia-docker I receive this error:
`docker: Error response from daemon: create nvidia_driver_358.16: Post http://%2Frun%2Fdocker%2Fplugins%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=44 with Body length 0.`

## ps
```
root     25978  0.0  0.1 29729252 17560 ?      Sl   18:53   0:00 nvidia-docker-plugin
```

## /tmp/nvidia-docker.log
```
nvidia-docker-plugin | 2016/07/21 18:54:00 Serving remote API at localhost:3476
nvidia-docker-plugin | 2016/07/21 18:54:01 Received activate request
nvidia-docker-plugin | 2016/07/21 18:54:01 Plugins activated [VolumeDriver]
nvidia-docker-plugin | 2016/07/21 18:54:01 Received create request for volume 'nvidia_driver_358.16'
```

## /var/log/docker
```
time="2016-07-21T18:54:00.451969138Z" level=error msg="Handler for GET /v1.23/volumes/nvidia_driver_358.16 returned error: get nvidia_driver_358.16: no such volume" 
time="2016-07-21T18:54:00.674109684Z" level=warning msg="Unable to locate plugin: nvidia-docker, retrying in 1s" 
time="2016-07-21T18:54:08.586660736Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Create, retrying in 1s" 
time="2016-07-21T18:54:09.587349132Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Create, retrying in 2s" 
time="2016-07-21T18:54:11.587903225Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Create, retrying in 4s" 
time="2016-07-21T18:54:15.588431304Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Create, retrying in 8s" 
time="2016-07-21T18:54:27.353664261Z" level=error msg="Handler for POST /v1.23/containers/create returned error: create nvidia_driver_358.16: Post http://%2Frun%2Fdocker%2Fplugins%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=44 with Body length 0" 
```

**Comment by flx42** [comment]
Could be similar to #123 
Could you try what @3XX0 suggested [here](https://github.com/NVIDIA/nvidia-docker/issues/123#issuecomment-229564095)?
You will need to modify the Dockerfile then generate a new deb (`make deb`).

**Comment by flx42** [comment]
@lukeforehand ok, good!
We also noticed that sometimes when rebooting an EC2 instance, the kernel becomes slightly different, we don't really know why, yet.

**Comment by lukeforehand** [comment]
Sadly, the issue is back after running successfully one time.  Here are similar logs but using an updated driver version.

## /tmp/nvidia-docker.log
```
nvidia-docker-plugin | 2016/07/22 19:09:09 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/07/22 19:09:09 Loading NVIDIA management library
nvidia-docker-plugin | 2016/07/22 19:09:09 Discovering GPU devices
nvidia-docker-plugin | 2016/07/22 19:09:09 Provisioning volumes at /var/lib/nvidia-docker/volumes
nvidia-docker-plugin | 2016/07/22 19:09:09 Serving plugin API at /run/docker/plugins
nvidia-docker-plugin | 2016/07/22 19:09:09 Serving remote API at localhost:3476
```

## /var/log/docker
```
time="2016-07-22T19:09:09.189891911Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Get, retrying in 1s" 
time="2016-07-22T19:09:10.190351598Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Get, retrying in 2s" 
time="2016-07-22T19:09:12.190832603Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Get, retrying in 4s" 
time="2016-07-22T19:09:16.191281461Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/nvidia-docker.sock:/VolumeDriver.Get, retrying in 8s" 
time="2016-07-22T19:09:24.191691522Z" level=error msg="Handler for GET /v1.23/volumes/nvidia_driver_367.27 returned error: get nvidia_driver_367.27: Post http://%2Frun%2Fdocker%2Fplugins%2Fnvidia-docker.sock/VolumeDriver.Get: dial unix /run/docker/plugins/nvidia-docker.sock: connect: no such file or directory" 
```

**Comment by lukeforehand** [comment]
I think I can reproduce the issue.  I am running this to start the nvidia-docker-plugin:
`sudo nvidia-docker-plugin > /tmp/nvidia-docker.log 2>&1 & disown;`

My nvidia-docker command works the first time.  But if I run the above nvidia-docker-plugin command a second time, I get the error in the nvidia-docker.log:
```
nvidia-docker-plugin | 2016/07/22 19:49:31 Error: listen tcp 127.0.0.1:3476: bind: address already in use
```

which is fine, but now I get the typical error:
```
docker: Error response from daemon: Post http://%2Frun%2Fdocker%2Fplugins%2Fnvidia-docker.sock/VolumeDriver.Mount: dial unix /run/docker/plugins/nvidia-docker.sock: connect: no such file or directory.
```

**Comment by flx42** [comment]
@lukeforehand it doesn't seem to be the same error as your original post.

For your second issue, yeah, don't try to run the plugin twice in a row, it will mess with the unix socket.

I haven't tried Amazon Linux, but in the past running the following worked for me:
```
sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log
```

**Comment by lukeforehand** [comment]
During CI builds I am invoking it before every nvidia-docker invocation because I don't have a good service script for running the plugin on boot.  

Also, there is an issue with `sudo -b nohup`.  The resulting process from that call doesn't detach from the main process, so it is not truly daemonized.  This causes cloud formation init to hang during bootstrapping as it waits for the nvidia-docker-plugin subprocess to exit.

**Comment by flx42** [comment]
Why can't you use CentOS or Ubuntu?

**Comment by flx42** [comment]
Also, why don't you check if the unix socket file already exists before trying to relaunch the plugin every time?

**Comment by lukeforehand** [comment]
I will consider moving to Ubuntu...  Having the plugin run as a service is ideal.  In the meantime I can write a script that checks if the plugin is already running.  Thanks.
