### ISSUE TITLE
If I run nvidia-smi -pm 1 on the host, will it take effect on the container?

### ISSUE THREAD

**Issue by liulixiang1988** [NVIDIA/nvidia-docker#1502]
### 1. Issue or feature description
I have some containers in the k8s. And it will run nvidia-smi to get the GPU usage information. But sometimes nvidia-smi process will be in D status. I googled some materials, and one solution is to enable persistence mode by run nvida-smi -pm 1.

If I run the command nvida-smi -pm 1 in the host, will it work for the container? or should I run the command in every container? Are there some methods to valid that?

Thanks!

**Comment by elezar** [comment]
@liulixiang1988 persistence mode is a driver property (or managed by `nvidia-persistenced`). This should be configured on the host and should propagate into the container. The output of `nvidia-smi` should show whether a device is in persistence mode or not.

**Comment by liulixiang1988** [comment]
@elezar thanks. It works!
