### ISSUE TITLE
Mount local folder to nvidia tensorflow docker

### ISSUE THREAD

**Issue by DolanDack** [NVIDIA/nvidia-docker#1503]
I am not sure if this is an issue per se but regardless I post it here hoping to find some help. 

I have downloaded the Nvidia `tensorflow:21.04-tf2-py3` image on my machine (Ubuntu 20.04), everything runs smoothly when I load the docker image except the fact that no matter what I do it always sends me to the `/workspace`, which by the way I have no idea where it is locally. It contains some Nvidia examples and files.

I have been trying to access a git repository that I have downloaded locally (on my desktop) but to no avail, `/home/<my username>/Desktop/GitRepo/<my repo>`

What I have tried so far is:

go to the local folder and start the docker from there

    sudo docker run --gpus all -it --rm -p 8888:8888 nvcr.io/nvidia/tensorflow:21.04-tf2-py3

then try to attach the local folder

    sudo docker run --gpus all -it --rm -p 8888:8888 -v $(pwd):/testfolder nvcr.io/nvidia/tensorflow:21.04-tf2-py3

again with quotes

    sudo docker run --gpus all -it --rm -p 8888:8888 -v "$(pwd):/testfolder" nvcr.io/nvidia/tensorflow:21.04-tf2-py3

then try to use the actual path

    sudo docker run --gpus all -it --rm -p 8888:8888 -v "/home/<my username>/Desktop/GitRepo:/testfolder" nvcr.io/nvidia/tensorflow:21.04-tf2-py3

using the `--mount` option gives me other issues

    sudo docker run --gpus all -it --rm -p 8888:8888 --mount src="$(pwd)",target="/testfolder" nvcr.io/nvidia/tensorflow:21.04-tf2-py3
    sudo docker run --gpus all -it --rm -p 8888:8888 --mount src="/home/<my username>/Desktop/GitRepo/",target=/testfolder nvcr.io/nvidia/tensorflow:21.04-tf2-py3

> docker: Error response from daemon: create
> /home/myusername/Desktop/GitRepo/: "/home/myusername/Desktop/GitRepo/"
> includes invalid characters for a local volume name, only
> "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a
> host directory, use absolute path. See 'docker run --help'.

**Comment by elezar** [comment]
You can specify the working directory using the `-w` / `--workdir` flag (https://docs.docker.com/engine/reference/commandline/run/).

```
docker run --rm -v $(pwd):$(pwd) -w $(pwd) ubuntu:20.04 pwd
/Users/elezar
```
(without the flag):
```
docker run --rm -v $(pwd):$(pwd) ubuntu:20.04 pwd
/
```

You should also be able to change to `/testfolder` once mounted into the container using the `-v` command.

```
➜  test pwd
/Users/elezar/tmp/test
➜  test ls
a-test-file.txt
➜  test docker run --rm -v $(pwd):/testdir ubuntu:20.04 ls -al /testdir
total 4
drwxr-xr-x 3 root root   96 May 20 07:32 .
drwxr-xr-x 1 root root 4096 May 20 07:33 ..
-rw-r--r-- 1 root root    0 May 20 07:32 a-test-file.txt
```

Using the `-w` flag in this case:
```
➜  test docker run --rm -v $(pwd):/testdir -w /testdir ubuntu:20.04 pwd
/testdir
➜  test docker run --rm -v $(pwd):/testdir -w /testdir ubuntu:20.04 ls -al
total 4
drwxr-xr-x 3 root root   96 May 20 07:32 .
drwxr-xr-x 1 root root 4096 May 20 07:33 ..
-rw-r--r-- 1 root root    0 May 20 07:32 a-test-file.txt
➜  test
```

**Comment by DolanDack** [comment]
oh.my.god! thank you so much! that took me ages to figure out!
