### ISSUE TITLE
Does the target system (for deployment of my image) need the CUDA Toolkit or only the CUDA Driver?

### ISSUE THREAD

**Issue by lennartmoritz** [NVIDIA/nvidia-docker#1507]
I have a working PyTorch Docker container with CUDA support on my own system (where i develop). 
I installed nvidia-docker first, before I started building my application from the base pytorch/pytorch 1.7.0-cuda11.0-cudnn8-devel image. If i use the built image of my application it works fine with my GPU. Again, this is on my own system (Ubuntu 20.4 LTS).

But i need to deploy my built docker image to a target system (Ubuntu, not sure about their version). And I have 2 questions at this point.

1. Does the target system need to have the nvidia-docker toolkit installed or will the working NVIDA driver with CUDA enabled be enough to run my image?
2. It has been a while since i installed the nvidia-docker toolkit and i had trouble setting it up the first time. I don't remember for what purpose I have the nvidia/cuda 11.0-base image listed in my docker images or during which step of trying to get my pytorch docker image to run with my GPU I have downloaded the nvidia/cuda image. Can I just safely remove the nvida /cuda image without risking to break the GPU compability I have when using the CUDA enabled pytorch/pytorch 1.7.0-cuda11.0-cudnn8-devel base image which I need for my application?

Edit:
I know the Readme of this Repo sais:

> Make sure you have installed the NVIDIA driver and Docker engine for your Linux distribution Note that you do not need to install the CUDA Toolkit on the host system, but the NVIDIA driver needs to be installed

But that sentence is rather unclear for me and I don't understand if it is actually trying to say that my target system does in fact not need the toolkit to run my image and that the toolkit is only needed in order to build the images but not to run them.

**Comment by lennartmoritz** [comment]
For anyone with the same questions:

1. The target system does not need the toolkit. It only needs the NVIDIA driver with CUDA enabled.
2. I'm think I only downloaded the nvidia/cuda 11.0-base image to verify that my NVIDIA driver was installed correctly to grant docker containers access to my GPU. And I would **assume** that I can safely remove that image without causing issues for my pytorch containers.

**Comment by elezar** [comment]
Hi @lennartmoritz. Sorry for not responding earlier. 

You are correct, you only need the NVIDIA driver installed on the host and there is no need for using the `nvidia/cuda*` images directly. In fact assuming the `NVIDIA_VISIBLE_DEVICES` environment variable is set any container should work to run `nvidia-smi` for example.

You can safely remove the `nvidia/cuda 11.0-base` image.
