### ISSUE TITLE
how k8s+docker(19.03+)+nvidia-docker2 dectect to use --gpus options through k8s OCI

### ISSUE THREAD

**Issue by perrywang** [NVIDIA/nvidia-docker#1509]
### 1. Issue or feature description
since docker 19.03 docker run command add --gpus parameter to expose gpus to container. But if we are using k8s+docker, how k8s OCI detect this break change ? 

### 2. Steps to reproduce the issue
- install k8s + docker (19.03+) + nvidia-docker2
- create a pod scheduled to gpu node
- pod container not find gpus

**Comment by elezar** [comment]
When using docker and k8s, docker must be configured to use `nvidia` as the default runtime. This is documented [here](https://docs.nvidia.com/datacenter/cloud-native/kubernetes/install-k8s.html#install-nvidia-container-toolkit-nvidia-docker2).
