### ISSUE TITLE
failed call to cuDevicePrimaryCtxRetain:CUDA_ERROR_UNKNOWN when run tensorflow in nvidia virtual GPU

### ISSUE THREAD

**Issue by wangchanggan** [NVIDIA/nvidia-docker#1510]
i installed NVIDIA-Linux-x86_64-390.75-grid.run and cuda_9.1.85_387.26_linux.run(not include the nvidia driver)，but i run tensorflow，the docker log showed failed call to cuDevicePrimaryCtxRetain:CUDA_ERROR_UNKNOWN.
besides,i make sure that docker runc is nvidia and nvidia grid license acquired successfully.
Here are some info：
![FA1C1D9786AE17F021682E731B88E39D](https://user-images.githubusercontent.com/33536351/120818314-1515bb00-c585-11eb-9ba7-6e7154d14b87.png)
![FA71F8F048DD1A0651D759B6D1466439](https://user-images.githubusercontent.com/33536351/120818439-35de1080-c585-11eb-9761-6b0d887b52ab.png)

**Comment by elezar** [comment]
What is the output of `nvidia-smi` in the container? The driver version being used is older than our officially supported version: `418.81.07`.

It would also be interesting to note whether the operation (or similar) performs as expected on the host.

**Comment by wangchanggan** [comment]
> What is the output of `nvidia-smi` in the container? The driver version being used is older than our officially supported version: `418.81.07`.
> 
> It would also be interesting to note whether the operation (or similar) performs as expected on the host.



the output of `nvidia-smi` in the container is the same to on the host.Here are info:
![image](https://user-images.githubusercontent.com/33536351/121044345-109d0c80-c7e8-11eb-9f60-4e655a827766.png)


418.81.07 is the nvidia driver version, i can't install it on the host which is nvidia virtual GPU, so i install nvidia grid driver, I'm not sure that whether it works.

i tried to run tensorflow on the host but not in the container, it It reported the same error, so i think it is not nvidia-docker2 problem.

Thanks.

**Comment by wangchanggan** [comment]
GRID M60-1Q doesn’t support CUDA.

https://docs.nvidia.com/cuda/vGPU/index.html

https://docs.nvidia.com/grid/latest/grid-vgpu-user-guide/index.html#cuda-open-cl-support-vgpu
