### ISSUE TITLE
Add RHEL 8.4 support & repos

### ISSUE THREAD

**Issue by shurik-io** [NVIDIA/nvidia-docker#1511]
1. Issue or feature description
Need a 8.4 version for RHEL. Repo is missing for 8.4. as well.

2. Steps to reproduce the issue
Setup Repo on a RHEL 8.4 machine.

3. Information to attach (optional if deemed irrelevant)
Kernel:
Linux test.foo.bar 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

In the meantime I'll try with the 8.3 repos, but would be nice to see a 8.4 soon.

**Comment by groom-polar-outage** [comment]
same issue. 
@shurik-io did 8.3 version had any problem on 8.4 system?

**Comment by shurik-io** [comment]
> @shurik-io did 8.3 version had any problem on 8.4 system?

@groom-polar-outage Installation worked and using podman with some test containers worked so far. The only problem, I've run into was the one described here: https://github.com/NVIDIA/nvidia-container-runtime/issues/85 but it's related to something else and not the packages as far as I understand.

At the the moment I couldn't test further and some load. Will update the issue when I should find something.

**Comment by qhaas** [comment]
We are now on [RHEL 8.5](https://www.redhat.com/en/blog/whats-new-rhel-85) and nvidia-docker still [only supports RHEL 8.3](https://nvidia.github.io/nvidia-docker).

**Comment by solatis** [comment]
Hello, we're using RHEL 8.5 and I would like to use nvidia-docker. Is there a way to do this based on the RHEL 8.3 modules, and/or to compile nvidia-docker from source?

**Comment by qhaas** [comment]
> Is there a way to do this based on the RHEL 8.3 modules, and/or to compile nvidia-docker from source?

CentOS 8 is now based on RHEL 8.5, while unsupported and YMMV, one could place the [centos8 repo](https://nvidia.github.io/nvidia-docker/centos8/nvidia-docker.repo) in `/etc/yum.repos.d/`

**Comment by elezar** [comment]
@solatis as @qhaas mentions, we currently symlink to `centos8` packages for all RHEL 8.* releases and as such specifying `centos8` as the distribution name when configuring the yum repositories would be the first thing to try. You are correct that we need to update our documentation to indicate this work around.

**Comment by elezar** [comment]
We have recently reworked our packaging an provide generic RPM repos.

Please follow the sinstructions here https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-yum-or-dnf

and create an issue against https://github.com/NVIDIA/nvidia-container-toolkit if there are any problems.
