### ISSUE TITLE
I installed nvidia/cuda:10.2-base, but still requirement error: unsatisfied condition: cuda>=11.2 when running tensorflow

### ISSUE THREAD

**Issue by hnqmz** [NVIDIA/nvidia-docker#1512]
<em>I pulled the latest tensorflow-gpu image but I cannot run this image </em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow version: docker image: 'tensorflow/tensorflow:latest-gpu-jupyter'
- CUDA/cuDNN version:CUDA version 10.2
- GPU model and memory: 2080ti * 4, each with memory 11019MB
- Docker version 19.03.8, build afacb8b7f0

**Describe the problem**
Since tensorflow-io installed by pip cannot work together with tensorflow installed by conda, I decided to use the docker image of tensorflow. I installed nvidia-docker according to this page: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker. And the result is this:
 ![捕获](https://tvax4.sinaimg.cn/large/006dgyGJgy1grk3opnyi6j30sd0h3goc.jpg)
Then, I pulled the tensorflow image by this:
`docker pull tensorflow/tensorflow:latest-gpu-jupyter`
and run this image by this:
`docker run --gpus=all -it tensorflow/tensorflow:latest-gpu bash`
then, I meet this error:
_docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container\\\\n\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled_
Why would it give this error: unsatisfied condition: cuda>=11.2

**Any other info / logs**
That's all images in this computer
![捕获](https://tvax4.sinaimg.cn/large/006dgyGJgy1grk3yb08ygj30tb06tq4o.jpg)

**Comment by elezar** [comment]
The tensorflow image that you're using is based on an image that uses CUDA 11.2. The driver version you're using (`440.64.00` as per your `nvidia-smi` output) supports up to CUDA 10.2 (as also indicated by the `nvidia-smi` output).

From https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility you would need to update to at least driver `450.80.02` to be able to run containers that require CUDA 11.2.

You could also consider using an image that is based on CUDA 10.2 instead of using `latest`.

**Comment by gemfield** [comment]
After further debugging(https://zhuanlan.zhihu.com/p/361545761), I found that:
## ai01 container:
```bash
root@1d0d6b4ec38d:/.gemfield_install# ls -l /usr/lib/x86_64-linux-gnu/libcuda.so*
lrwxrwxrwx 1 root root       12 6月  30 00:09 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       20 6月  30 00:09 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.465.19.01
-rw-r--r-- 1 root root 21795104 5月   7 15:00 /usr/lib/x86_64-linux-gnu/libcuda.so.460.80
-rw-r--r-- 1 root root 22033824 3月  19 16:07 /usr/lib/x86_64-linux-gnu/libcuda.so.465.19.01
```

## ai02 container:
```bash
root@9b438063576f:/.gemfield_install# ls -l /usr/lib/x86_64-linux-gnu/libcuda*
lrwxrwxrwx 1 root root       12 6月  30 00:05 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       17 6月  30 00:05 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.460.80
-rw-r--r-- 1 root root 21795104 5月   7 15:00 /usr/lib/x86_64-linux-gnu/libcuda.so.460.80
```
With both host ai01 and host ai02 installed  libcuda.so.460.80 cuda driver, **ai01** container now has the **CUDA Forward Compatible** issue. While for **ai02** container, it becomes to **"newer version cuda toolkit + older version cuda driver + older version kernel mode GPU driver"**, which belongs to the category that we called **"CUDA enhanced compatibility"**:
```
# quote from https://docs.nvidia.com/deploy/cuda-compatibility/index.html#faq
What about new features introduced in minor releases of CUDA? How does a developer build an application using newer CUDA Toolkits (e.g. 11.x) work on a system with a CUDA 11.0 driver (R450)?
By using new CUDA versions, users can benefit from new CUDA programming model APIs, compiler optimizations and math library features. There are some caveats:
A subset of CUDA APIs don’t need a new driver and they can all be used without any driver dependencies. For example, async copy APIs introduced in 11.1 do not need a new driver.
To use other CUDA APIs introduced in a minor release (that require a new driver), one would have to implement fallbacks or fail gracefully. This situation is not different from what is available today where developers use macros to compile out features based on CUDA versions. Users should refer to the CUDA headers and documentation for new CUDA APIs introduced in a release.
```
So, to eliminate the ai01 container 804 error, I just relink libcuda.so.1 to libcuda.so.460.80, which turns the **CUDA Forward Compatible** issue(not supported by non-tesla devices) to **"CUDA enhanced compatibility"**(supported by tesla and non-tesla devices):
```bash
# on ai01 container
ln -sf /usr/lib/x86_64-linux-gnu/libcuda.so.460.80 /usr/lib/x86_64-linux-gnu/libcuda.so.1
```
@elezar Could you confirm that if this is the right way? Thanks.
