### ISSUE TITLE
Key expired?

### ISSUE THREAD

**Issue by cwolfe-pt** [NVIDIA/nvidia-docker#1513]
### 1. Issue or feature description
NVIDIA apt repo key appears to be expired. using Ubuntu 18.04

### 2. Steps to reproduce the issue
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
   && apt-get update

### 3. Output
OK
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/amd64  InRelease
Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:5 https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/amd64  InRelease [1,149 B]
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:7 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease
Hit:8 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64  InRelease
Hit:9 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:10 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
Hit:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Get:12 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Err:5 https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/amd64  InRelease
  The following signatures were invalid: EXPKEYSIG 6ED91CA3AC1160CD NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
Reading package lists... Done
W: GPG error: https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/amd64  InRelease: The following signatures were invalid: EXPKEYSIG 6ED91CA3AC1160CD NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
E: The repository 'https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/amd64  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by elezar** [comment]
Hi @cwolfe-pt

The error message seems to indicate that these are keys associated with the experimental repos? Does the error go away if you disable the experimental repos?

At present the experimental repos are quite behind stable and we haven't updated these in some time.

**Comment by cwolfe-pt** [comment]
Evan,
Thanks. I had experimental repos enabled. In my issue, i should have included the line
`curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list`
in the steps to reproduce.

The scripts had worked fine for a while, but suddenly broke yesterday when the key expired. Removing that line from my script solved my issue. Thanks.
