### ISSUE TITLE
NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 2

### ISSUE THREAD

**Issue by HeIsRicky** [NVIDIA/nvidia-docker#1514]
#### System information of host
* GPU contains NVDEC and NVENC.
* Linux VM-191-99-tlinux 4.14.105-19-0017 #1 SMP Wed Oct 28 12:13:16 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
* Tesla T Series(_more than 4_), NVIDIA-SMI: 460.32.03 , Driver Version: 460.32.03, CUDA Version: 11.2 
* nvidia-container-cli version: 1.3.3
* docer version: 18.09.5

#### System information in the container
* Linux d37bfb4b2167 4.14.105-19-0017 #1 SMP Wed Oct 28 12:13:16 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
* cuda-11.1
* gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
* cmake version 3.17.5
* ffmpeg version 4.2.3 

#### Steps to reproduce the issue
* `nvidia-docker run -it -v /root:/root/ -e NVIDIA_VISIBLE_DEVICES=0 cc2e6f078f7e /bin/bash`
* `cd Video_Codec_SDK_9.0.20/Samples/AppEncode/AppEncCuda`
* `make `
* `./AppEncCuda -gpu 0 -i sample.MP4 -o enc.tmp -s 540x960`

#### Error message
* `NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 2 at ../../NvCodec/NvEncoder/NvEncoder.cpp:55`
* Error code 2 means `NV_ENC_ERR_UNSUPPORTED_DEVICE, "This indicates that devices pass by the client is not supported"`

Any help would be greatly appreciated!

**Comment by elezar** [comment]
What is the output of `nvidia-smi` when run in the following container:
```
nvidia-docker run -it -v /root:/root/ -e NVIDIA_VISIBLE_DEVICES=0 cc2e6f078f7e /bin/bash
```

Since this is dealing with encoding, this may have to do with the fact that NVIDIA libraries are selectively mounted based on the `NVIDIA_DRIVER_CAPABILITY` (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#driver-capabilities) you could try to set this to `all` in the command line and repeat the test.

**Comment by HeIsRicky** [comment]
Thanks for the quick reply!

**Comment by HeIsRicky** [comment]
Thanks for the quick reply. It worked for me after enabling all the capabilities like this:

`nvidia-docker run -it -v /root:/root/ -e NVIDIA_VISIBLE_DEVICES=0 -e NVIDIA_DRIVER_CAPABILITIES=compute,compat32,graphics,utility,video,display  cc2e6f078f7e /bin/bash`

Thanks a lot! 👍

**Comment by elezar** [comment]
The default value is `utility` which would not include, for example, the video and graphics libraries (which i would assume are required here). You could also use the value `all` instead of specifying the complete set.

Glad you got it sorted out.

**Comment by HeIsRicky** [comment]
Got it. I have spent a day looking for the answer, you solved my problem in just a few minutes, you are awesome.
