### ISSUE TITLE
how is `nvidia-docker` or `docker --gpus all` different with `docker -v /path/libcuda.so -v /path/other-nvidia-driver.so -v... --device /dev/nvidia0:/dev/nvidia0 --device...`

### ISSUE THREAD

**Issue by melyseengit** [NVIDIA/nvidia-docker#1517]
Hi,  I wonder if we could just use `docker -v /path/libcuda.so -v /path/other-nvidia-driver.so -v... --device /dev/nvidia0:/dev/nvidia0 --device...` or something like that so it might work exactly the same as `nvidia-docker` or `docker --gpus all` 
in case of some situation like internet is unreachable or nvidia-docker is not supported in some os-release

command eg.
export CUDA_SO="$(\ls /usr/lib64/libcuda* | xargs -I{} echo '-v {}:{}') $(\ls /usr/lib64/libnvidia* | xargs -I{} echo '-v {}:{}')"
export DEVICES=$(find /dev/nvidia* -maxdepth 1 -not -type d | xargs -I{} echo '--device {}:{}')

docker run --rm -it ${CUDA_SO} ${DEVICES} your_image:your_tag

**Comment by elezar** [comment]
In terms of ensuring the libraries aren device are available in the container, this should have the desired effect.

There are some additional features that the hook (triggered by `--gpus all` or `nvidia-docker`) adds, like checking image requirements, loading kernel modules, creating device nodes, but these are not applicable in all cases.

**Comment by JoyBeginner** [comment]
thanks a lot for the reply!
is there any wiki or document about those `additional features`? I'm not sure in what kind of situation would those features be a must. 
by the way, is 'aren' a typo?
