### ISSUE TITLE
Unable to run docker  nvcr.io/nvidia/k8s/cuda-sample:nbody, error:   nvml error: driver not loaded: unknown

### ISSUE THREAD

**Issue by codeastra2** [NVIDIA/nvidia-docker#1518]
### 1. Issue or feature description
I was following this [guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-wip) for Cuda installation on WSL2. This involves starting off a docker image. 
I used the command `docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`, this resulted in the error: 
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.
ERRO[0000] error waiting for container: context canceled`

`nvidia-smi` gives the following output: 
`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`

### 2. Steps to reproduce the issue

- As mentioned in the guide I have WSL2 and also installed the nvidia driver from [here](https://developer.nvidia.com/cuda/wsl/download), GEForce.  Note that I did not  install the driver in WSL as the guide told not to.
- After this I installed the container toolkit as mentioned in the guide and started the docker service.
- Upon the running the above command I got the mentioned error.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [nvidia-container-cli: initialization error: nvml error: driver not loaded ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - 
 - [ Linux LAPTOP-DSFDAJA5 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux] Kernel version from `uname -a`
 
 - [ NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.] Driver information from `nvidia-smi -a`
 
 - [ Version:           20.10.7 ] Docker version from `docker version`

 - [ nvidia-utils-460-server            460.73.01-0ubuntu0.20.04.1 amd64] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 
 - [version: 1.4.0
build date: 2021-04-24T14:25+00:00
build revision: 704a698b7a0ceec07a48e56c37365c741718c2df ] NVIDIA container library version from `nvidia-container-cli -V`

- WSL Distro used:     Ubuntu 20.04.2 LTS

**Comment by maxloge** [comment]
I have the same issue.

**Comment by qiangxinglin** [comment]
Use insider dev channel.

**Comment by maxloge** [comment]
> Use insider dev channel.

Some people (like me) might not meet the minimum hardware requirement for the Insider Dev channel :(

![image](https://user-images.githubusercontent.com/77212379/124243598-58c8f980-db1e-11eb-945f-0bac83ef0a72.png)

Processor	Intel i5-4430 CPU @ 3.00GHz
RAM	        32,0 GB DDR3
GPU                 NVIDIA GeForce RTX 2060
DISK                Samsung SSD 970 PRO 512GB
MB                  ASUS H97-PLUS

**Comment by qiangxinglin** [comment]
I guess you want to use it with Docker Desktop (WSL2 backend), the insider dev channel is a mandantory requirement for GPU to work with WSL2. I don't know how to get a latest win10 dev version for now either.

**Comment by maxloge** [comment]
Apparently, CPUs that don't have TPM 2.0. cannot join the Insider Dev channel.

![image](https://user-images.githubusercontent.com/77212379/124251761-903ba400-db26-11eb-95f7-f3400bb88ce6.png)

One need a "TPM 2.0" module or one of these processors to join the Insider Dev channel

[source 1](https://www.theverge.com/2021/6/25/22549725/microsoft-windows-11-cpu-support-tpm-hardware-requirements)
[source 2](https://www.theverge.com/2021/6/25/22550376/microsoft-windows-11-tpm-chips-requirement-security)

WINDOWS 11 SUPPORT FOR INTEL:
Intel 8th Gen (Coffee Lake)
Intel 9th Gen (Coffee Lake Refresh)
Intel 10th Gen (Comet Lake)
Intel 10th Gen (Ice Lake)
Intel 11th Gen (Rocket Lake)
Intel 11th Gen (Tiger Lake)
Intel Xeon Skylake-SP
Intel Xeon Cascade Lake-SP
Intel Xeon Cooper Lake-SP
Intel Xeon Ice Lake-SP

WINDOWS 11 SUPPORT FOR AMD:
AMD Ryzen 2000
AMD Ryzen 3000
AMD Ryzen 4000
AMD Ryzen 5000
AMD Ryzen Threadripper 2000
AMD Ryzen Threadripper 3000
AMD Ryzen Threadripper Pro 3000
AMD EPYC 2nd Gen
AMD EPYC 3rd Gen
