### ISSUE TITLE
Problem launching example on Jetson Xavier

### ISSUE THREAD

**Issue by DaddyWesker** [NVIDIA/nvidia-docker#1519]
Hello. I was trying to run example from here 
https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson
"Building CUDA in Containers on Jetson"

After docker cntainer was successfully built, i was trying to launch next command 
`sudo docker run -it --runtime nvidia devicequery`
but got following error:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ERRO[0001] error waiting for container: context canceled `

Here is the output of uname -a
`Linux jetson-0420719082691 4.9.108-tegra #2 SMP PREEMPT Wed Oct 31 15:11:49 PDT 2018 aarch64 aarch64 aarch64 GNU/Linux`

What could be wrong? Thanks in advance.

**Comment by elezar** [comment]
Hi @DaddyWesker. This indicates that the `devicequery` image is not a `linux/arm64` image. Did you build it yourself, or pull it from somewhere?

For newer versions of docker (with the `buildx` plugin available), you could try:

```
sudo docker run --platform=linux/arm64 -it --runtime nvidia devicequery
```

**Comment by DaddyWesker** [comment]
Hello.

I've built it using from example above (link). Here is the dockerfile

```
FROM nvcr.io/nvidia/l4t-base:r32.3.1

RUN apt-get update && apt-get install -y --no-install-recommends make g++
COPY ./samples /tmp/samples

WORKDIR /tmp/samples/1_Utilities/deviceQuery
RUN make clean && make

CMD ["./deviceQuery"]

Unfortunately, with your addition to command now it says that `Unable to find image 'devicequery:latest' locally` Maybe conneted somehow with no latest docker?
```

**Comment by elezar** [comment]
You can also build the image with `docker build --platform=linux/arm64` which should ensure that the image with the required platform is also available.

**Comment by DaddyWesker** [comment]
Is this docker pull command should be dome outside docker or inside Dockerfile? Which docker version should i use?

**Comment by elezar** [comment]
The pull command should not be necessary if the build command is provided with the `--platform` flag.  Also, if it doesn't complain about the flags, then the version should be fine.

**Comment by DaddyWesker** [comment]
Alright, i've tried to rebuilt docker image with  command  
`docker build --platform=linux/arm64 -t devicequery . --no-cache`

Though i've got error now

```
Step 3/6 : COPY ./samples /tmp/samples
failed to get destination image "sha256:ec2cc4cc207a85df4f742242cd12ad6398f5091f7e9e43a0224222a85be846b3": image with reference sha256:ec2cc4cc207a85df4f742242cd12ad6398f5091f7e9e43a0224222a85be846b3 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
```

**Comment by elezar** [comment]
If you run `docker images --digests` you should be able to see which image is being referred to. Is it the image in the `FROM` line?

**Comment by DaddyWesker** [comment]
Here is the output of docker images --digests . THough i'm not sure there will be something since docker rebuild was failed
![Screenshot from 2021-07-02 12-33-18](https://user-images.githubusercontent.com/10774222/124254409-b7e43980-db31-11eb-8751-f776e2df073b.png)

**Comment by elezar** [comment]
I have been able to reproduce the behaviour on my own device. When running `docker inspect` on the `r32.3.1` base image, I see that it has an architecture of `amd64` which may be causing this behaviour.

Could you repeat the steps in the documentation with the `r32.5.0` image (which you already seem to have downloaded)? This allows the `devicequery` container to run on my end. We will update our docs accordingly.

**Comment by DaddyWesker** [comment]
Alright. I've changed Dockerfile to this
```
FROM nvcr.io/nvidia/l4t-base:r32.5.0

RUN apt-get update && apt-get install -y --no-install-recommends make g++
COPY ./samples /tmp/samples

WORKDIR /tmp/samples/1_Utilities/deviceQuery
RUN make clean && make

CMD ["./deviceQuery"]
```

now it builds a little bit further with command `docker build --platform=linux/arm64 -t devicequery . --no-cache`

but now i'm getting 
![Screenshot from 2021-07-02 13-05-20](https://user-images.githubusercontent.com/10774222/124258524-2b884580-db36-11eb-9569-5b3f88afb7ff.png)

**Comment by elezar** [comment]
From my jetson:
(note that I dropped the `--platform` flags as they are not needed for this image).
```
$ cat Dockerfile
FROM nvcr.io/nvidia/l4t-base:r32.5.0

RUN apt-get update && apt-get install -y --no-install-recommends make g++
COPY ./samples /tmp/samples

WORKDIR /tmp/samples/1_Utilities/deviceQuery
RUN make clean && make

CMD ["./deviceQuery"]
```

```
docker build -t devicequery .
Sending build context to Docker daemon    213MB
Step 1/6 : FROM nvcr.io/nvidia/l4t-base:r32.5.0
 ---> d9141f00a2c3
Step 2/6 : RUN apt-get update && apt-get install -y --no-install-recommends make g++
 ---> Using cache
 ---> c21c09a2089f
Step 3/6 : COPY ./samples /tmp/samples
 ---> Using cache
 ---> 332957074838
Step 4/6 : WORKDIR /tmp/samples/1_Utilities/deviceQuery
 ---> Using cache
 ---> 2fd7e5f2f8f5
Step 5/6 : RUN make clean && make
 ---> Using cache
 ---> cc51e2eff195
Step 6/6 : CMD ["./deviceQuery"]
 ---> Using cache
 ---> 4ecb72f0c332
Successfully built 4ecb72f0c332
Successfully tagged devicequery:latest
```

```
$ docker run --rm -ti --runtime=nvidia devicequery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA Tegra X1"
  CUDA Driver Version / Runtime Version          10.2 / 10.2
  CUDA Capability Major/Minor version number:    5.3
...
```

**Comment by elezar** [comment]
```
$ docker run --rm -ti nvcr.io/nvidia/l4t-base:r32.5.0
root@9936074a5aed:/# which nvcc
/usr/local/cuda-10.2/bin/nvcc
```
Could it be that the `samples` folder has been modified meaning that your make is looking for `cuda-10.0`?

Try removing the `samples` folder and copying it again?

**Comment by maxloge** [comment]
Hi @elezar,
Hi @DaddyWesker,

Don't know if it is worth mentioning but the error is very similar to the error we get in [issue 1518](https://github.com/NVIDIA/nvidia-docker/issues/1518). Just saying...

**Comment by DaddyWesker** [comment]
Hello, guys. I'm just wanted to say that currently i have no access to Jetson. It will be available in some time but till then i can't check your solutions, sorry.

**Comment by DaddyWesker** [comment]
Hello again. I've tested today all the pipeline of the example and now it works. CLosing the issue. THanks for your help. I guess the problem was in this `FROM nvcr.io/nvidia/l4t-base:r32.5.0` and something could be related to the xavier itself since it was on maintenance for a several days and when it returned all went as expected.
