### ISSUE TITLE
[CentOS 7] libssl.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by gotjd709** [NVIDIA/nvidia-docker#1522]
To install NVIDIA-Docker for CentOS 7, I follow the description https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

When I setup the stable repository and the GPG key
```{.shell}
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo
```
I met the error message likes
```{.shell}
curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

To solving this problem, I update yum and install openssl, openssl-env but It's dose not working. (I met the same error message.)
```{.shell}
$ sudo yum update
$ sudo yum install openssl, openssl-env
```

I think it is easy to solve. so I search many trouble shootings but I didn't solve this problem. Could you help me anyone?

**Comment by elezar** [comment]
How is `curl` installed on your system? Something like this may be useful: https://stackoverflow.com/questions/56440506/curl-is-not-installing-with-ssl-support-in-centos-at-user-defined-perfix/56440905

**Comment by gotjd709** [comment]
Thank you for your advice. 

When I check `curl` version, 
`curl -V`
I met the same issue. 

> curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

So, I will solve `curl` install problem first.

**Comment by elezar** [comment]
@gotjd709 were you able to address this issue? I am closing this for the time being as it seems to not be an `nvidia-docker` bug. Please reopen if you have more information.
