### ISSUE TITLE
Containers with gpus not starting up

### ISSUE THREAD

**Issue by AlexAshs** [NVIDIA/nvidia-docker#1525]
### 1. Issue or feature description
I am trying to run nvidia/cuda:11.4.0-base-ubuntu20.04, but the container is not starting up.

### 2. Steps to reproduce the issue
When I try to run `docker run --rm --gpus all nvidia/cuda:11.4.0-base-ubuntu20.04 nvidia-smi`, I get the following output:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

**I have a Nvidia GTX 1080 TI Turbo from Asus with an HDMI 4K ghost plug as the only display connected.**

**I am running the following software:**
- OS: `Ubuntu Server 20.04 LTS` on intel x64 instruction set
- Linux Kernel: `5.4.0-77-generic`
- Cuda Version `11.4`
- packages:
  - nvidia-compute-utils-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed,automatic]
  - nvidia-container-runtime/bionic,now 3.5.0-1 amd64 [installed]
  - nvidia-container-toolkit/bionic,now 1.5.1-1 amd64 [installed]
  - nvidia-cuda-dev/focal,now 10.1.243-3 amd64 [installed,automatic]
  - nvidia-cuda-toolkit/focal,now 10.1.243-3 amd64 [installed]
  - nvidia-dkms-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed,automatic]
  - nvidia-docker2/bionic,now 2.6.0-1 all [installed]
  - nvidia-headless-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed]
  - nvidia-headless-no-dkms-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed,automatic]
  - nvidia-kernel-common-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed,automatic]
  - nvidia-kernel-source-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed,automatic]
  - nvidia-opencl-dev/focal,now 10.1.243-3 amd64 [installed,automatic]
  - nvidia-profiler/focal,now 10.1.243-3 amd64 [installed,automatic]
  - nvidia-utils-470/unknown,now 470.57.02-0ubuntu1 amd64 [installed]
  - docker-ce-cli/focal,now 5:20.10.7~3-0~ubuntu-focal amd64 [installed]
  - docker-ce-rootless-extras/focal,now 5:20.10.7~3-0~ubuntu-focal amd64 [installed,automatic]
  - docker-ce/focal,now 5:20.10.7~3-0~ubuntu-focal amd64 [installed]
  - docker-compose/focal,now 1.25.0-1 all [installed]
  - docker-scan-plugin/focal,now 0.8.0~ubuntu-focal amd64 [installed,automatic]
  - nvidia-docker2/bionic,now 2.6.0-1 all [installed]

**Running `nvidia-container-cli -k -d /dev/tty info` gives me the following output:**
`I0723 16:22:57.613768 496283 nvc.c:372] initializing library context (version=1.4.0, build=704a698b7a0ceec07a48e56c37365c741718c2df)
I0723 16:22:57.613819 496283 nvc.c:346] using root /
I0723 16:22:57.613825 496283 nvc.c:347] using ldcache /etc/ld.so.cache
I0723 16:22:57.613828 496283 nvc.c:348] using unprivileged user 65534:65534
I0723 16:22:57.613839 496283 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0723 16:22:57.613939 496283 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
I0723 16:22:57.616536 496284 nvc.c:274] loading kernel module nvidia
I0723 16:22:57.616627 496284 nvc.c:278] running mknod for /dev/nvidiactl
I0723 16:22:57.616645 496284 nvc.c:282] running mknod for /dev/nvidia0
I0723 16:22:57.616657 496284 nvc.c:286] running mknod for all nvcaps in /dev/nvidia-caps
I0723 16:22:57.620020 496284 nvc.c:214] running mknod for /dev/nvidia-caps/nvidia-cap1 from /proc/driver/nvidia/capabilities/mig/config
I0723 16:22:57.620087 496284 nvc.c:214] running mknod for /dev/nvidia-caps/nvidia-cap2 from /proc/driver/nvidia/capabilities/mig/monitor
I0723 16:22:57.621337 496284 nvc.c:292] loading kernel module nvidia_uvm
I0723 16:22:57.621363 496284 nvc.c:296] running mknod for /dev/nvidia-uvm
I0723 16:22:57.621407 496284 nvc.c:301] loading kernel module nvidia_modeset
I0723 16:22:57.621430 496284 nvc.c:305] running mknod for /dev/nvidia-modeset
I0723 16:22:57.621575 496285 driver.c:101] starting driver service
I0723 16:22:57.623006 496283 nvc_info.c:676] requesting driver information with ''
I0723 16:22:57.623858 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.470.57.02
I0723 16:22:57.623905 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.470.57.02
I0723 16:22:57.623952 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.470.57.02
I0723 16:22:57.623987 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.57.02
I0723 16:22:57.624039 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.470.57.02
I0723 16:22:57.624078 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.470.57.02
I0723 16:22:57.624109 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.470.57.02
I0723 16:22:57.624152 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.470.57.02
I0723 16:22:57.624309 496283 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.470.57.02
W0723 16:22:57.624394 496283 nvc_info.c:350] missing library libnvidia-nscq.so
W0723 16:22:57.624400 496283 nvc_info.c:350] missing library libnvidia-fatbinaryloader.so
W0723 16:22:57.624407 496283 nvc_info.c:350] missing library libnvidia-allocator.so
W0723 16:22:57.624413 496283 nvc_info.c:350] missing library libnvidia-ngx.so
W0723 16:22:57.624418 496283 nvc_info.c:350] missing library libvdpau_nvidia.so
W0723 16:22:57.624425 496283 nvc_info.c:350] missing library libnvidia-eglcore.so
W0723 16:22:57.624432 496283 nvc_info.c:350] missing library libnvidia-glcore.so
W0723 16:22:57.624439 496283 nvc_info.c:350] missing library libnvidia-tls.so
W0723 16:22:57.624445 496283 nvc_info.c:350] missing library libnvidia-glsi.so
W0723 16:22:57.624452 496283 nvc_info.c:350] missing library libnvidia-fbc.so
W0723 16:22:57.624459 496283 nvc_info.c:350] missing library libnvidia-ifr.so
W0723 16:22:57.624465 496283 nvc_info.c:350] missing library libnvidia-rtcore.so
W0723 16:22:57.624472 496283 nvc_info.c:350] missing library libnvoptix.so
W0723 16:22:57.624479 496283 nvc_info.c:350] missing library libGLX_nvidia.so
W0723 16:22:57.624486 496283 nvc_info.c:350] missing library libEGL_nvidia.so
W0723 16:22:57.624492 496283 nvc_info.c:350] missing library libGLESv2_nvidia.so
W0723 16:22:57.624499 496283 nvc_info.c:350] missing library libGLESv1_CM_nvidia.so
W0723 16:22:57.624506 496283 nvc_info.c:350] missing library libnvidia-glvkspirv.so
W0723 16:22:57.624513 496283 nvc_info.c:350] missing library libnvidia-cbl.so
W0723 16:22:57.624520 496283 nvc_info.c:354] missing compat32 library libnvidia-ml.so
W0723 16:22:57.624527 496283 nvc_info.c:354] missing compat32 library libnvidia-cfg.so
W0723 16:22:57.624534 496283 nvc_info.c:354] missing compat32 library libnvidia-nscq.so
W0723 16:22:57.624540 496283 nvc_info.c:354] missing compat32 library libcuda.so
W0723 16:22:57.624548 496283 nvc_info.c:354] missing compat32 library libnvidia-opencl.so
W0723 16:22:57.624554 496283 nvc_info.c:354] missing compat32 library libnvidia-ptxjitcompiler.so
W0723 16:22:57.624561 496283 nvc_info.c:354] missing compat32 library libnvidia-fatbinaryloader.so
W0723 16:22:57.624568 496283 nvc_info.c:354] missing compat32 library libnvidia-allocator.so
W0723 16:22:57.624575 496283 nvc_info.c:354] missing compat32 library libnvidia-compiler.so
W0723 16:22:57.624582 496283 nvc_info.c:354] missing compat32 library libnvidia-ngx.so
W0723 16:22:57.624589 496283 nvc_info.c:354] missing compat32 library libvdpau_nvidia.so
W0723 16:22:57.624596 496283 nvc_info.c:354] missing compat32 library libnvidia-encode.so
W0723 16:22:57.624603 496283 nvc_info.c:354] missing compat32 library libnvidia-opticalflow.so
W0723 16:22:57.624609 496283 nvc_info.c:354] missing compat32 library libnvcuvid.so
W0723 16:22:57.624616 496283 nvc_info.c:354] missing compat32 library libnvidia-eglcore.so
W0723 16:22:57.624623 496283 nvc_info.c:354] missing compat32 library libnvidia-glcore.so
W0723 16:22:57.624630 496283 nvc_info.c:354] missing compat32 library libnvidia-tls.so
W0723 16:22:57.624636 496283 nvc_info.c:354] missing compat32 library libnvidia-glsi.so
W0723 16:22:57.624643 496283 nvc_info.c:354] missing compat32 library libnvidia-fbc.so
W0723 16:22:57.624650 496283 nvc_info.c:354] missing compat32 library libnvidia-ifr.so
W0723 16:22:57.624657 496283 nvc_info.c:354] missing compat32 library libnvidia-rtcore.so
W0723 16:22:57.624664 496283 nvc_info.c:354] missing compat32 library libnvoptix.so
W0723 16:22:57.624670 496283 nvc_info.c:354] missing compat32 library libGLX_nvidia.so
W0723 16:22:57.624677 496283 nvc_info.c:354] missing compat32 library libEGL_nvidia.so
W0723 16:22:57.624684 496283 nvc_info.c:354] missing compat32 library libGLESv2_nvidia.so
W0723 16:22:57.624691 496283 nvc_info.c:354] missing compat32 library libGLESv1_CM_nvidia.so
W0723 16:22:57.624698 496283 nvc_info.c:354] missing compat32 library libnvidia-glvkspirv.so
W0723 16:22:57.624705 496283 nvc_info.c:354] missing compat32 library libnvidia-cbl.so
I0723 16:22:57.624897 496283 nvc_info.c:276] selecting /usr/bin/nvidia-smi
I0723 16:22:57.624916 496283 nvc_info.c:276] selecting /usr/bin/nvidia-debugdump
I0723 16:22:57.624935 496283 nvc_info.c:276] selecting /usr/bin/nvidia-persistenced
I0723 16:22:57.624957 496283 nvc_info.c:276] selecting /usr/bin/nvidia-cuda-mps-control
I0723 16:22:57.624973 496283 nvc_info.c:276] selecting /usr/bin/nvidia-cuda-mps-server
W0723 16:22:57.625025 496283 nvc_info.c:376] missing binary nv-fabricmanager
I0723 16:22:57.625049 496283 nvc_info.c:438] listing device /dev/nvidiactl
I0723 16:22:57.625055 496283 nvc_info.c:438] listing device /dev/nvidia-uvm
I0723 16:22:57.625062 496283 nvc_info.c:438] listing device /dev/nvidia-uvm-tools
I0723 16:22:57.625068 496283 nvc_info.c:438] listing device /dev/nvidia-modeset
I0723 16:22:57.625097 496283 nvc_info.c:317] listing ipc /run/nvidia-persistenced/socket
W0723 16:22:57.625118 496283 nvc_info.c:321] missing ipc /var/run/nvidia-fabricmanager/socket
W0723 16:22:57.625135 496283 nvc_info.c:321] missing ipc /tmp/nvidia-mps
I0723 16:22:57.625140 496283 nvc_info.c:733] requesting device information with ''
I0723 16:22:57.631011 496283 nvc_info.c:623] listing device /dev/nvidia0 (GPU-beafab21-bb2b-6096-9381-e18709941e6a at 00000000:01:00.0)
NVRM version:   470.57.02
CUDA version:   11.4

Device Index:   0
Device Minor:   0
Model:          NVIDIA GeForce GTX 1080 Ti
Brand:          GeForce
GPU UUID:       GPU-beafab21-bb2b-6096-9381-e18709941e6a
Bus Location:   00000000:01:00.0
Architecture:   6.1
I0723 16:22:57.631044 496283 nvc.c:423] shutting down library context
I0723 16:22:57.631178 496285 driver.c:163] terminating driver service
I0723 16:22:57.631362 496283 driver.c:203] driver service terminated successfully`

**The logs in `/var/log/nvidia-container-toolkit.log` say the following:**
`I0723 16:20:24.354103 475657 nvc.c:372] initializing library context (version=1.4.0, build=704a698b7a0ceec07a48e56c37365c741718c2df)
I0723 16:20:24.354146 475657 nvc.c:346] using root /run/nvidia/driver
I0723 16:20:24.354187 475657 nvc.c:347] using ldcache /etc/ld.so.cache
I0723 16:20:24.354200 475657 nvc.c:348] using unprivileged user 0:44
I0723 16:20:24.354219 475657 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0723 16:20:24.354318 475657 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
E0723 16:20:24.356970 475663 nvc.c:263] failed to change root directory: No such file or directory
W0723 16:20:24.357050 475663 nvc.c:264] skipping kernel modules load due to failure
I0723 16:20:24.357282 475664 driver.c:101] starting driver service
E0723 16:20:24.357766 475664 driver.c:168] could not start driver service: change root failed: no such file or directory
I0723 16:20:24.357936 475657 driver.c:203] driver service terminated successfully`

**Comment by rszabi** [comment]
Did you installed the nvidia-driver-NVML package?

**Comment by AlexAshs** [comment]
No, it is not being shown when querying packages installable with apt.

What does it do and how can I install it?

**Comment by elezar** [comment]
@AlexAshs from the logs, it seems as if you're running version 1.4.0 of the `nvidia-container-cli`. Could you please confirm your `libnvidia-container1` and `libnvidia-container-tools` package versions.

It would also be useful if you enable the debug logs (by uncommenting the `debug = ` lines in `/etc/nvidia-container-runtime/config.toml` and attaching the file from `/var/log/nvidia-container-toolkit.log` to the issue.

**Comment by AlexAshs** [comment]
I am sorry for the delay.

I have simply moved to installing ArchLinux and instlaling nvidia-docker from the AUR and everything is working perfectly.

Therefore I will close this and thank your for your time.
