### ISSUE TITLE
Segmentation Fault when launching

### ISSUE THREAD

**Issue by dtdavi1** [NVIDIA/nvidia-docker#1533]
### 1. Issue or feature description
After following the installation [instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit), crashes and raises the following error whenever I launch a docker image that includes the --gpus flag

### 2. Steps to reproduce the issue
Any --gpus flag docker launch will cause the error, but I first saw it when launching the post-installation test image (`sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information:
 -- WARNING, the following logs are for debugging purposes only --
I0814 19:23:08.008628 12076 nvc.c:372] initializing library context (version=1.5.0~rc.1, build=5884d4232da9109423f55e79d57df264991c27cf)
I0814 19:23:08.008713 12076 nvc.c:346] using root /
I0814 19:23:08.008730 12076 nvc.c:347] using ldcache /etc/ld.so.cache
I0814 19:23:08.008747 12076 nvc.c:348] using unprivileged user 1000:999
Segmentation fault (core dumped)

 - [ ] Kernel version
 Linux warhawk 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Output from `dmesg`
[ 9646.665416] docker0: port 1(veth923529e) entered blocking state
[ 9646.665417] docker0: port 1(veth923529e) entered disabled state
[ 9646.665449] device veth923529e entered promiscuous mode
[ 9646.665526] docker0: port 1(veth923529e) entered blocking state
[ 9646.665527] docker0: port 1(veth923529e) entered forwarding state
[ 9646.665681] docker0: port 1(veth923529e) entered disabled state
[ 9646.756536] nvidia-containe[12547]: segfault at 0 ip 00007fbef9417c6a sp 00007ffc47594ce8 error 4 in libc-2.27.so[7fbef936e000+1e7000]
[ 9646.756539] Code: 0f b6 0e 0f b6 07 29 c8 c3 0f 1f 80 00 00 00 00 89 f8 31 d2 66 0f ef ff 09 f0 25 ff 0f 00 00 3d c0 0f 00 00 0f 8f 78 02 00 00 <f3> 0f 6f 0f f3 0f 6f 06 66 0f 74 c1 66 0f da c1 66 0f ef c9 66 0f
[ 9646.850386] docker0: port 1(veth923529e) entered disabled state
[ 9646.851155] device veth923529e left promiscuous mode
[ 9646.851156] docker0: port 1(veth923529e) entered disabled state

 - [ ] Driver information
 See [driver_info.txt](https://github.com/NVIDIA/nvidia-docker/files/6987081/driver_info.txt)

 - [ ] Docker version from `docker version`
 Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

 - [ ] NVIDIA packages version
 See [nvidia_packages.txt](https://github.com/NVIDIA/nvidia-docker/files/6987091/nvidia_packages.txt)

 - [ ] NVIDIA container library version
version: 1.5.0~rc.1
build date: 2021-08-13T09:32+00:00
build revision: 5884d4232da9109423f55e79d57df264991c27cf
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs
[nvidia-container-toolkit.log](https://github.com/NVIDIA/nvidia-docker/files/6987093/nvidia-container-toolkit.log)
[_usr_bin_nvidia-container-cli.0.crash.txt](https://github.com/NVIDIA/nvidia-docker/files/6987095/_usr_bin_nvidia-container-cli.0.crash.txt)

 - [ ] Docker command, image and tag used
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

**Comment by dtdavi1** [comment]
Neglected to include the actual error in the original report:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.

**Comment by DimanNe** [comment]
+1 The same here. As temporary workaround, try downgrading:
`apt install nvidia-container-toolkit=1.5.1-1`

**Comment by DimanNe** [comment]
+1
Same here. Try downgrading:
```
apt install libnvidia-container1=1.4.0-1 libnvidia-container-tools=1.4.0-1 nvidia-container-toolkit=1.5.1-1
```

(you can check your previous version in `/var/log/apt/term.log`)

**Comment by dtdavi1** [comment]
That fixed everything.  Thanks for the assist.

**Comment by DimanNe** [comment]
@dtdavi1 I do not think you need to mark this as `fixed`. It is just a temporary workaround, and nothing has been really fixed yet.

**Comment by dbason** [comment]
I'm also getting the same issue running on wsl2 ubuntu18.04.  Downgrading also solved the problem for me.  I'm going to open a new issue seeing as this one is closed.

**Comment by dtdavi1** [comment]
I closed the issue prematurely since downgrading sufficed for my purposes.  I reopened the issue and will leave it to others to close from here.

**Comment by elezar** [comment]
Hi. Yes, there is an issue in the `rc.1` packages that were released on Friday to the `experimental` repos. We have removed these packages from the repos while we work on the fix. Using the versions from the `stable` repos should address the issues.

**Comment by elezar** [comment]
An update: an updated version of [`libnvidia-container-tools` (`1.5.0-rc.2`)](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.5.0-rc.2) has been pushed to the experimental repositories. This addresses the segmentation violation present in `1.5.0-rc.1`.

I am going to close this issue with this as the fix. If the problem persists after upgrading to `1.5.0-rc.2` (or downgrading to a stable version), please reopen or file a new issue.
