### ISSUE TITLE
Missing folder for SLES 15.3 / 15.x

### ISSUE THREAD

**Issue by Ursanon** [NVIDIA/nvidia-docker#1539]
### 1. Issue or feature description

Missing folder for identifier `sles15.3` / `sles15.1`.

installation output on SLES 15.3:

```
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker
````

### 2. Steps to reproduce the issue
https://nvidia.github.io/nvidia-docker/sles15.1/nvidia-docker.list
https://nvidia.github.io/nvidia-docker/sles15.3/nvidia-docker.list

**Comment by elezar** [comment]
Could you use `nvidia-docker.repo` instead of `nvidia-docker.list`? The latter is used for `deb` repositories.

**Comment by Ursanon** [comment]
Work like a charm, thanks @elezar
