### ISSUE TITLE
Docker can't recognize A100

### ISSUE THREAD

**Issue by billchen0001** [NVIDIA/nvidia-docker#1541]
HI ,

CentOS 7.6 + Cuda 11.4 /  Driver 470.57.02

Two GPU (A100) work well on Host as below,
nvidia-smi
Sat Aug 28 23:04:46 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  Off  | 00000000:17:00.0 Off |                    0 |
| N/A   35C    P0    64W / 300W |      0MiB / 80994MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80G...  Off  | 00000000:CA:00.0 Off |                    0 |
| N/A   37C    P0    64W / 300W |      0MiB / 80994MiB |      3%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |

But can't be recognized through Nvidia Docker

```
# docker run --rm --gpus all nvidia/cuda:11.4.0-cudnn8-devel-centos8 nvidia-smi
No devices were found
```

some logs from /nvidia-container-toolkit.log
[root@node1 yum.repos.d]# tail /var/log/nvidia-container-toolkit.log
I0828 15:06:32.969053 97899 nvc_mount.c:208] mounting /dev/nvidia0 at /var/lib/docker/overlay2/a993f8652631f0af33954e5494ab35351501aa4f67bd7be985e8dc8cd020501e/merged/dev/nvidia0
I0828 15:06:32.969118 97899 nvc_mount.c:412] mounting /proc/driver/nvidia/gpus/0000:17:00.0 at /var/lib/docker/overlay2/a993f8652631f0af33954e5494ab35351501aa4f67bd7be985e8dc8cd020501e/merged/proc/driver/nvidia/gpus/0000:17:00.0
I0828 15:06:32.969137 97899 nvc_mount.c:499] whitelisting device node 195:0
I0828 15:06:32.969168 97899 nvc_mount.c:208] mounting /dev/nvidia1 at /var/lib/docker/overlay2/a993f8652631f0af33954e5494ab35351501aa4f67bd7be985e8dc8cd020501e/merged/dev/nvidia1
I0828 15:06:32.969214 97899 nvc_mount.c:412] mounting /proc/driver/nvidia/gpus/0000:ca:00.0 at /var/lib/docker/overlay2/a993f8652631f0af33954e5494ab35351501aa4f67bd7be985e8dc8cd020501e/merged/proc/driver/nvidia/gpus/0000:ca:00.0
I0828 15:06:32.969229 97899 nvc_mount.c:499] whitelisting device node 195:1
I0828 15:06:32.969246 97899 nvc_ldcache.c:360] executing /sbin/ldconfig from host at /var/lib/docker/overlay2/a993f8652631f0af33954e5494ab35351501aa4f67bd7be985e8dc8cd020501e/merged
I0828 15:06:32.998945 97899 nvc.c:423] shutting down library context
I0828 15:06:33.818690 97907 driver.c:163] terminating driver service
I0828 15:06:33.818930 97899 driver.c:203] driver service terminated successfully

# docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Any suggestions will be appreciate.

Thanks,
Bill

**Comment by elezar** [comment]
Hi @billchen0001. This is a known issue due to the A100 80GB using GSP firmware. There is a fix out in our experimental repos. Installing [`libnvidia-container-tools` version `1.5.0~rc.2-`](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.5.0-rc.2) should address this issue.

We will be promoting this release to the stable branch in the coming days.

**Comment by billchen0001** [comment]
> Hi @billchen0001. This is a known issue due to the A100 80GB using GSP firmware. There is a fix out in our experimental repos. Installing [`libnvidia-container-tools` version `1.5.0~rc.2-`](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.5.0-rc.2) should address this issue.
> 
> We will be promoting this release to the stable branch in the coming days.

Hi @elezar  Thank you so much, It was fixed  after upgrade the libnvidia-container-tools to 1.5-rc.2 as you mentioned.

**Comment by klueska** [comment]
Can this be closed now?

**Comment by elezar** [comment]
@billchen0001 we have just promoted the release candidate to the stable repositories. The `1.5.0` package should contain the same fix.

**Comment by elezar** [comment]
@billchen0001 I am closing this issue. Please reopen if the issue keeps presenting itself.
