### ISSUE TITLE
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system

### ISSUE THREAD

**Issue by deep-pipeline** [NVIDIA/nvidia-docker#155]
Same error message as issue #107 and lots of background/investigation in the latter part of that thread

essentially an FC24 + NVIDIA-Linux-x86_64-367.27.run driver installation + Docker installation + Nvidia-docker installation

working nvidia-smi on the host

but in the container

>
nvidia-docker run -ti nvidia/cuda nvidia-smi
>

results in 

>
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
>

and oddly, root in the container can't seem to access relevant files:

>
[root@dell ~]# nvidia-docker run nvidia/cuda ls -al /usr/local/
total 0
drwxr-xr-x. 12 root root 156 Jul 27 17:53 .
drwxr-xr-x. 10 root root 105 Jul 22 22:04 ..
drwxr-xr-x.  2 root root   6 Jul 11 23:22 bin
lrwxrwxrwx.  1 root root   8 Jul 22 21:59 cuda -> cuda-8.0
drwxr-xr-x. 11 root root 194 Jul 22 22:04 cuda-8.0
drwxr-xr-x.  2 root root   6 Jul 11 23:22 etc
drwxr-xr-x.  2 root root   6 Jul 11 23:22 games
drwxr-xr-x.  2 root root   6 Jul 11 23:22 include
drwxr-xr-x.  3 root root  23 Jul 11 23:23 lib
lrwxrwxrwx.  1 root root   9 Jul 11 23:22 man -> share/man
drwxr-xr-x.  5  984  984  41 Jul 25 13:15 nvidia
drwxr-xr-x.  2 root root   6 Jul 11 23:22 sbin
drwxr-xr-x.  4 root root  40 Jul 22 21:58 share
drwxr-xr-x.  2 root root   6 Jul 11 23:22 src
[root@dell ~]# nvidia-docker run nvidia/cuda ls -al /usr/local/nvidia
ls: cannot open directory /usr/local/nvidia: Permission denied
[root@dell ~]# nvidia-docker run nvidia/cuda whoami
root
>

**Comment by deep-pipeline** [comment]
Thanks to @flx42 for prompts and help getting to this point. :)

**Comment by 3XX0** [comment]
What's the output of `nvidia-docker volume ls`?
If you see nvidia volumes there,  can you try removing them with `nvidia-docker volume rm` and run `nvidia-docker run -ti nvidia/cuda nvidia-smi` again

**Comment by deep-pipeline** [comment]
Output of nvidia-docker volume ls 

>
nvidia-docker volume ls                                               DRIVER              VOLUME NAME                                                      nvidia-docker       nvidia_driver_367.27         
>

(I haven't yet attempted upgrade to 367.35 since flx42 mentioned there was an update)

nvidia-docker run -ti nvidia/cuda nvidia-smi

>nvidia-docker run -ti nvidia/cuda nvidia-smi             NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.        Please also try adding directory that contains libnvidia-ml.so to your system PATH. 
>

**Comment by flx42** [comment]
@deep-pipeline he mentioned running `nvidia-docker volume rm nvidia_driver_367.27` before trying again.

**Comment by deep-pipeline** [comment]
D'oh! sorry..

(more for anyone else who comes to this thread.. so attempting to remove it resulted in a complaint:

>nvidia-docker volume rm nvidia_driver_367.27
Error response from daemon: Conflict: remove nvidia_driver_367.27: volume is in use - [e78f0f00059c826031cd2d123570014542138b73436ee04687b61536b1435c62, 48ca686d9a18de700062a43f776ef97b9a2fec8bb80a7c657a4d0eb22365636f, 1801e82fb26cef3f12b9a4a22fd1994721e660956a5b242627d2f0aa1a5c7d42, 
[lots of lines snipped]
>

which confused me to begin with because both nvidia-docker ps and docker ps showed nothing running and systemctl stopping and starting both nvidia-docker.service and docker.service made no difference to the presence of the error message.. but I discovered I simply had lots of old stopped containers which I deleted with `nvidia-docker rm $(nvidia-docker ps -a -q)` accepting I could download/rebuild all containers again.. so, having deleted the volume, checked with `nvidia-docker volume ls` that it was definitely gone, I tried the  

`nvidia-docker run -ti nvidia/cuda nvidia-smi`command..

and the same error:

>
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
> 

appeared..
incidentally then checking `nvidia-docker volume ls` the same name of volume had appeared again.

**Comment by flx42** [comment]
Ok, so it's not a transient problem.
What about the following commands:
```
$ ls /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/
$ sudo ls /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/
```
I believe the second one will fail.

**Comment by deep-pipeline** [comment]
ls /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/

gives the same result as the sudo one (which didn't fail.. but then I am doing this all as root)

>
[root@dell ~]# ls -l /var/lib/nvidia-docker/volumes/nvidia_driver/367.27/lib64/
total 134368
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       17 Jul 28 18:59 libcuda.so -> libcuda.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       17 Jul 28 18:59 libcuda.so.1 -> libcuda.so.367.27
-rwxr-xr-x. 2 root          root           8116488 Jul 14 14:51 libcuda.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       23 Jul 28 18:59 libEGL_nvidia.so.0 -> libEGL_nvidia.so.367.27
-rwxr-xr-x. 2 root          root           1003176 Jul 14 14:51 libEGL_nvidia.so.367.27
-rwxr-xr-x. 2 root          root            822536 Jul 14 14:51 libGLdispatch.so.0
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       29 Jul 28 18:59 libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.367.27
-rwxr-xr-x. 2 root          root             51528 Jul 14 14:51 libGLESv1_CM_nvidia.so.367.27
-rwxr-xr-x. 2 root          root             33872 Jul 14 14:51 libGLESv1_CM.so.1
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       26 Jul 28 18:59 libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.367.27
-rwxr-xr-x. 2 root          root             75680 Jul 14 14:51 libGLESv2_nvidia.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       23 Jul 28 18:59 libGLX_indirect.so.0 -> libGLX_nvidia.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       23 Jul 28 18:59 libGLX_nvidia.so.0 -> libGLX_nvidia.so.367.27
-rwxr-xr-x. 2 root          root           1273992 Jul 14 14:51 libGLX_nvidia.so.367.27
-rwxr-xr-x. 2 root          root             65912 Jul 14 14:51 libGLX.so.0
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       20 Jul 28 18:59 libnvcuvid.so.1 -> libnvcuvid.so.367.27
-rwxr-xr-x. 2 root          root           2209872 Jul 14 14:51 libnvcuvid.so.367.27
-rwxr-xr-x. 2 root          root          48074800 Jul 14 14:51 libnvidia-compiler.so.367.27
-rwxr-xr-x. 2 root          root          26622256 Jul 14 14:51 libnvidia-eglcore.so.367.27
-rwxr-xr-x. 2 root          root             21040 Jul 14 14:51 libnvidia-egl-wayland.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       26 Jul 28 18:59 libnvidia-encode.so.1 -> libnvidia-encode.so.367.27
-rwxr-xr-x. 2 root          root            170192 Jul 14 14:51 libnvidia-encode.so.367.27
-rwxr-xr-x. 2 root          root            323368 Jul 14 14:51 libnvidia-fatbinaryloader.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       23 Jul 28 18:59 libnvidia-fbc.so.1 -> libnvidia-fbc.so.367.27
-rwxr-xr-x. 2 root          root             94344 Jul 14 14:51 libnvidia-fbc.so.367.27
-rwxr-xr-x. 2 root          root          28430712 Jul 14 14:51 libnvidia-glcore.so.367.27
-rwxr-xr-x. 2 root          root            500960 Jul 14 14:51 libnvidia-glsi.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       23 Jul 28 18:59 libnvidia-ifr.so.1 -> libnvidia-ifr.so.367.27
-rwxr-xr-x. 2 root          root            206728 Jul 14 14:51 libnvidia-ifr.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       22 Jul 28 18:59 libnvidia-ml.so.1 -> libnvidia-ml.so.367.27
-rwxr-xr-x. 2 root          root           1153696 Jul 14 14:51 libnvidia-ml.so.367.27
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       26 Jul 28 18:59 libnvidia-opencl.so.1 -> libnvidia-opencl.so.367.27
-rwxr-xr-x. 2 root          root           8480360 Jul 14 14:51 libnvidia-opencl.so.367.27
-rwxr-xr-x. 2 root          root           8909528 Jul 14 14:51 libnvidia-ptxjitcompiler.so.367.27
-rwxr-xr-x. 2 root          root             14480 Jul 14 14:51 libnvidia-tls.so.367.27
-rwxr-xr-x. 2 root          root            183920 Jul 14 14:51 libOpenGL.so.0
lrwxrwxrwx. 1 nvidia-docker nvidia-docker       25 Jul 28 18:59 libvdpau_nvidia.so.1 -> libvdpau_nvidia.so.367.27
-rwxr-xr-x. 2 root          root            698296 Jul 14 14:51 libvdpau_nvidia.so.367.27
>

**Comment by deep-pipeline** [comment]
oh, and that may include the earlier soft links I created.. should I dig those out and rm them?

**Comment by 3XX0** [comment]
Can you try the following:

```
$ nvidia-docker pull nvidia/cuda
$ nvidia-docker run -ti nvidia/cuda
# ldconfig
# nvidia-smi
```

If this doesn't work, can you try adding this link within the container:

```
# ln -s /usr/local/nvidia/lib64/libnvidia-ml.so.367.27 /lib/x86_64-linux-gnu/libnvidia-ml.so
# ldconfig
# nvidia-smi
```

If this still fails, can you paste the output of `ldconfig -p | grep nvidia-ml` from within the container.

**Comment by deep-pipeline** [comment]
OK, so pulling the new nvidia/cuda and running it..

>
Digest: sha256:66a2b6c7f1b583c0c5cefbcde7ed48b45bad9760f7efb42eebd672cfb6e16c10
Status: Downloaded newer image for docker.io/nvidia/cuda:latest
[root@dell ~]# nvidia-docker run -ti nvidia/cuda
root@4bd3f105b399:/# ldconfig
root@4bd3f105b399:/# nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
>

didn't work.. sigh.. so, trying the link:

>
root@4bd3f105b399:/# ln -s /usr/local/nvidia/lib64/libnvidia-ml.so.367.27 /lib/x86_64-linux-gnu/libnvidia-ml.so
root@4bd3f105b399:/# ldconfig
root@4bd3f105b399:/# nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
>

nope; here's the output of 
`ldconfig -p | grep nvidia-ml`

>
	libnvidia-ml.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so
>

and in case it's of help here's the `# env ` output, including the container's LIBRARY_PATH and LD_LIBRARY_PATH and PATH settings.

if it matters, I note that "/lib/x86_64-linux-gnu/libnvidia-ml.so" wouldn't fall into any of them..

>
root@4bd3f105b399:/# env
HOSTNAME=4bd3f105b399
TERM=xterm
LIBRARY_PATH=/usr/local/cuda/lib64/stubs:
LS_COLORS=rs [snipped]
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
CUDA_PKG_VERSION=8-0=8.0.27-1
CUDA_VERSION=8.0
CUDA_DOWNLOAD_SUM=9edcebbe8b646e40317f9ab822a733e10146003a73fc775a089226630121da7b
SHLVL=1
HOME=/root
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
>

oh and if it helps, here is the intra container output of 
`# find / -name libnvidia-ml.so`

>
/lib/x86_64-linux-gnu/libnvidia-ml.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
find: `/usr/local/nvidia': Permission denied
>

and just to check what it is.. 
`# ls -al /lib/x86_64-linux-gnu/libnvidia-ml.so`

>
lrwxrwxrwx. 1 root root 46 Jul 31 14:38 /lib/x86_64-linux-gnu/libnvidia-ml.so -> /usr/local/nvidia/lib64/libnvidia-ml.so.367.27
>

and just to check that it's the correct binary 
`# ls -al /usr/local/nvidia/lib64/libnvidia-ml.so.367.27`

>
-rwxr-xr-x. 2 root root 1153696 Jul 14 13:51 /usr/local/nvidia/lib64/libnvidia-ml.so.367.27
>

which matches size and datestamp of the libnvidia-ml.so.367.27 file on the host system.. so... still a bit of a mystery..

I thought I would look at what the recorded dependencies are for both non-working intra container and working host binaries were.. although, being paranoid, I've checked and they are the same binaries

>

  [root@dell ~]# ldd -v $(which nvidia-smi)
	linux-vdso.so.1 (0x00007ffc7d3d7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa0233cb000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa0231c7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa022e04000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fa022bfc000)
	/lib64/ld-linux-x86-64.so.2 (0x000055cb0b19d000)

	Version information:
	/usr/bin/nvidia-smi:
		librt.so.1 (GLIBC_2.2.5) => /lib64/librt.so.1
		libdl.so.2 (GLIBC_2.2.5) => /lib64/libdl.so.2
		libpthread.so.0 (GLIBC_2.2.5) => /lib64/libpthread.so.0
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
	/lib64/libpthread.so.0:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
	/lib64/libdl.so.2:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
	/lib64/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
	/lib64/librt.so.1:
		libpthread.so.0 (GLIBC_2.3.2) => /lib64/libpthread.so.0
		libpthread.so.0 (GLIBC_PRIVATE) => /lib64/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /lib64/libpthread.so.0
		libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6

and inside the nvidia-docker nvidia/cuda container
>

root@4bd3f105b399:/# ldd -v $(which nvidia-smi)
	linux-vdso.so.1 =>  (0x00007fff8db1a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fafe537e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fafe517a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fafe4db4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fafe4bac000)
	/lib64/ld-linux-x86-64.so.2 (0x000055b361083000)

	Version information:
	/usr/local/nvidia/bin/nvidia-smi:
		librt.so.1 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/librt.so.1
		libdl.so.2 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libdl.so.2
		libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libpthread.so.0:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libdl.so.2:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
	/lib/x86_64-linux-gnu/librt.so.1:
		libpthread.so.0 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libpthread.so.0
		libpthread.so.0 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6

>

I don't quite understand why libnvidia-ml.so.367.27 isn't mentioned as being linked to from the binary but then this is alien territory for me hence I'm just spraying out information which I hope is relevant..

I might just wipe all and reinstall this time with the slightly more up-to-date 327 driver.. though it does annoys me that there is something not quite working..

**Comment by flx42** [comment]
```
find: `/usr/local/nvidia': Permission denied
```
This is the problem, do you have some kind of root squashing?

**Comment by deep-pipeline** [comment]
not knowingly.. looking in the container, it seems that folder is owned by 984.

>
drwxr-xr-x.  5  984  984  41 Jul 28 17:59 nvidia
drwxr-xr-x.  2 root root   6 Jul 11 23:22 sbin
drwxr-xr-x.  4 root root  40 Jul 26 17:48 share
>

hmm..

>
root@5fce65e2545a:/usr/local# chown -R root. nvidia/
chown: cannot read directory 'nvidia/': Permission denied
>

yeah, you must me right.. there was some debate elsewhere about whether some selinux stuff was behaving badly with docker in FC24 - although the final position was it was some docker socket issue.. https://github.com/docker/docker/issues/23981 - just mentioning in case selinux is where any root limitation is creeping in.

I could ditch Fedora and go to Debian - I'm not that attached to Fedora (except I have an old IBM server I simply couldn't get to run with debian because of a painfully obscure hardware bug requiring special kernel options but which, because of IBM connection, was dealt with in default Redhat installs and all subsequent default Fedora installs.. ooof painful remembering that experience); trying to do the CUDA stuff on a more modern machine.

anything you'd like me to try?

**Comment by 3XX0** [comment]
Maybe related to https://github.com/docker/docker/issues/24981 as well.

You can try disabling selinux? Also you can try the following before launching the container
```
chown -R root: /var/lib/nvidia-docker/volumes
```

**Comment by 3XX0** [comment]
Try changing `ro` to `Z` here:
https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia/volumes.go#L108

And add `:z` add the end of every docker volume (i.e. `-v`) there:
https://github.com/NVIDIA/nvidia-docker/blob/master/tools/Makefile

Then create a rpm with `make rpm`
This should fix your issue if selinux is the cause of the problem.

**Comment by reedog117** [comment]
> Try changing ro to Z (uppercase) here:
> https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia/volumes.go#L108
> 
> And add :z (lowercase) at the end of every docker volume (i.e. -v) there:
> https://github.com/NVIDIA/nvidia-docker/blob/master/tools/Makefile
> 
> Then create a rpm with make rpm
> This should fix your issue if selinux is the cause of the problem.

Is this fix going to be rolled into a future release RPM? I am having this problem with Fedora 25 and the newest available version of the rpm. I'm also guessing that anybody running SELinux is running into the same problem.

**Comment by flx42** [comment]
@reedog117 Unlikely, because IIRC `:Z` will relabel the content on the host, which can break your system.

**Comment by SuminHan** [comment]
I Got the same problem:
`NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.`
So, did anybody actually solved the problem?

**Comment by zmielna** [comment]
Ubuntu 16 docker container running on Centos 7 host, I experienced same issue as above, plus all sort of weird problems with other sample containers (like nvidia-docker). Cured with "setenforce 0" but this is just temporary workaround, need some local Selinux modules based on audit.log.

**Comment by PMLavigne** [comment]
I was able to get this working by generating the following local SELinux modules using audit2allow. No guarantee they'll work for you but they might help:

```
module read_lxc_net_t 1.0;

require {
        type xserver_var_lib_t;
        type svirt_lxc_net_t;
        class dir read;
}

#============= svirt_lxc_net_t ==============
allow svirt_lxc_net_t xserver_var_lib_t:dir read;
```

```
module read_nvidia_lxc_net_t 1.0;

require {
        type xserver_var_lib_t;
        type svirt_lxc_net_t;
        class lnk_file read;
}

#============= svirt_lxc_net_t ==============
allow svirt_lxc_net_t xserver_var_lib_t:lnk_file read;
```

Note that this is to the best of my knowledge allowing virtual containers access to things labelled with xserver_var_lib which seems reasonable enough to me but I don't take responsibility for you getting hacked if this opens a hole in your system :)

**Comment by dllehr81** [comment]
To add to @PMLavigne 
This issue is closed...but I wanted to add a note here.  It seems like nvidia-docker 1.0 on RHEL sometimes  adds new volumes to `/var/lib/nvidia-docker/volumes/nvidia_driver/` with the `xserver_var_lib_t` security instead of the docker preferred `svirt_sandbox_file_t`

I fixed this without allowing `xserver_var_lib_t` on your containers using the following
`sudo chcon -Rt svirt_sandbox_file_t /var/lib/nvidia-docker/volumes/nvidia_driver/${NVIDIA_DRIVER}`

I haven't seen any negative side effects yet.

**Comment by ScorpioCPH** [comment]
@flx42 Hi, does nvidia-docker-runtime-hook use `ldconfig` to create links for `libnvidia-ml.so`?
