### ISSUE TITLE
Cannot open /dev/tty0 

### ISSUE THREAD

**Issue by SpringDay6** [NVIDIA/nvidia-docker#1557]
when i run the xinit with the navida docker 
root@bb3b2082fa25:/# xinit  

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
Current Operating System: Linux bb3b2082fa25 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.10.0-1160.42.2.el7.x86_64 root=UUID=eb448abb-3012-4d8d-bcde-94434d586a31 ro crashkernel=auto net.ifnames=0 console=tty0 console=ttyS0,115200n8 LANG=en_US.UTF-8
Build Date: 08 April 2021  01:57:21PM
xorg-server 2:1.19.6-1ubuntu4.9 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Thu Oct 14 20:00:36 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
please help me thank you very much

**Comment by twoongg** [comment]
Hi! did you make any progress? I am sufferuing similiar error

**Comment by elezar** [comment]
There was a patch in Xorg here https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/763/diffs that addresses this. Please update to XOrg version 21.1.2 or later to include this patch.

**Comment by elezar** [comment]
It is my understanding that the bug presented here is not specific to the NVIDIA Container Toolkit and has to do with the use of X in containers in general.

If the problem continues and the proposed workaround above does not address this, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit.
