### ISSUE TITLE
consider release deb that depends on docker.io

### ISSUE THREAD

**Issue by 0wu** [NVIDIA/nvidia-docker#156]
There are two package names of docker  : docker.io (ubuntu manintaed) and docker-engine (docker maintained). Would it be possible to release a deb that depends on docker.io in addition to the one for docker-engine? This would ease the installation process for users who use docker that comes with ubuntu distro.

see detail: https://www.quora.com/What-is-the-difference-between-docker-engine-and-docker-io-packages

**Comment by flx42** [comment]
See #102, we recommend using `docker-engine`. We don't want to provide two deb packages, it would be confusing, not everyone is aware of the differences between the two versions.
We provide a Dockerfile to build the deb, it should be straightforward to modify the `Depends` and regenerate a deb locally:
https://github.com/NVIDIA/nvidia-docker/blob/master/tools/build/deb/control#L13
