### ISSUE TITLE
Flushed GL error 0x505

### ISSUE THREAD

**Issue by WAYLON** [NVIDIA/nvidia-docker#1561]
I use OpenGL to report the following errors in NVIDIA / OpenGL. How can I solve this? Thank you very much
![image](https://user-images.githubusercontent.com/43636332/140264845-946e5ef1-0a5e-4f84-91c7-49a6d9831943.png)

**Comment by elezar** [comment]
Could you provide more information on your setup and when the error occurred?

**Comment by WAYLON** [comment]
I have solved this problem. I will upgrade the host driver to version 945. This problem will naturally disappear. Thank you
