### ISSUE TITLE
Ubuntu repositories misconfigured

### ISSUE THREAD

**Issue by jose-lpa** [NVIDIA/nvidia-docker#1566]
I was following the [documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit) and simply trying to install the package in my box when I found that all Ubuntu repositories are pointing to **Ubuntu 18.04**.

Check it:
- https://nvidia.github.io/nvidia-docker/ubuntu19.04/nvidia-docker.list
- https://nvidia.github.io/nvidia-docker/ubuntu19.10/nvidia-docker.list
- https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list

Apologies if this is not the right place for this specific issue. I didn't find a more appropriate one.

Many thanks.

**Comment by elezar** [comment]
This is the intended behaviour. The `ubuntut18.04` packages are currently used for all later distributions.

**Comment by jose-lpa** [comment]
Oh, I see. Sorry, I was confused.
