### ISSUE TITLE
Documentation about DinD is lacking and misleading

### ISSUE THREAD

**Issue by awoimbee** [NVIDIA/nvidia-docker#1572]
Context:
I come from https://docs.nvidia.com/datacenter/cloud-native/playground/dind.html.
And I created https://github.com/Extrality/nvidia-dind.

### Issues

The documentation at the above link is false and lacks information.

1. Mounting the docker socket is **NOT** Docker in Docker, as the docker daemon is running on the host.
2. DinD with the GPU and Cuda is actually possible

Please replace:
> You can also run GPU containers with Docker-in-Docker (dind). Just mount in the Docker socket to the container (...)

By something like:
> While running GPU containers with Docker-in-Docker (dind) might work it is an unsupported use-case. A common workaround is to mount the Docker socket to the container (...)

Related issues:
https://github.com/NVIDIA/nvidia-docker/issues/467
https://github.com/NVIDIA/nvidia-docker/issues/487

**Comment by elezar** [comment]
Thanks @awoimbee. You're correct that this should be changed to avoid confusion. Would you mind creating an MR against https://gitlab.com/nvidia/cloud-native/cnt-docs to have the changes reflected against our documentation?

**Comment by awoimbee** [comment]
Seems like the docs website changed a lot since this was created, closing.

> Would you mind creating an MR 

Yes I would, nvidia has employees for that :smile:
