### ISSUE TITLE
How to use Nvidia GPU while using integrated GPU for display

### ISSUE THREAD

**Issue by entron** [NVIDIA/nvidia-docker#158]
I am using integrated graphic card for system display (linux mint 18), and I want to use Nvidia gtx 980 for cuda related calculation. However, I am getting the following error:

```
nvidia-docker | 2016/07/30 15:15:32 Error: could not load NVML library
```

Can somebody help on this?

**Comment by flx42** [comment]
Does `nvidia-smi` work fine on the host?

Then, can you give us the output of the following command?
```
ldconfig -p | grep nvidia-ml
```

See issue #74, it might be related.

**Comment by entron** [comment]
Thanks for the quick response!

If I switch to Nvidia GPU with "NVIDIA X Server Settings" application I can run `nvidia-smi` correctly (after re-login).

However `nvidia-docker run --rm nvidia/cuda nvidia-smi` gives error:

```
docker: Error response from daemon: create nvidia_driver_361.42: create nvidia_driver_361.42: Error looking up volume plugin nvidia-docker: plugin not found.
```

If I switch to integrated GPU with "NVIDIA X Server Settings" application. `nvidia-smi` gives

```
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

and `ldconfig -p | grep nvidia-ml` gives nothing. 

However `nvidia-smi` works after I run `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-361`, while `ldconfig -p | grep nvidia-ml` still gives nothing. In this setting, `nvidia-docker run --rm nvidia/cuda nvidia-smi` gives the same error as above:

```
docker: Error response from daemon: create nvidia_driver_361.42: create nvidia_driver_361.42: Error looking up volume plugin nvidia-docker: plugin not found.
```

**Comment by 3XX0** [comment]
`nvidia-docker-plugin` needs to be running on the machine (see [here](https://github.com/NVIDIA/nvidia-docker/wiki#other-distributions))

**Comment by entron** [comment]
After manually run the command:

```
sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log
``` 
It works now. I restarted, and it works for both Nvidia GPU and Integrated GPU. Thanks for the help!
