### ISSUE TITLE
Packages for Debian 11 Bullseye

### ISSUE THREAD

**Issue by lepalom** [NVIDIA/nvidia-docker#1581]
I have seen that Debian 10 Buster is supported. Since August 14th, 2021 Debian has a new stable version Bullseye, Debian 11.

Please, could you provide packages for Debian 11 Bullseye?

Thanks

**Comment by f1yankees** [comment]
See #1549

**Comment by elezar** [comment]
Thanks for providing the link @f1yankees.

@lepalom could we close this in the mean time?

**Comment by lepalom** [comment]
Yes, sure.

**Comment by klueska** [comment]
`libnvidia-container-1.8.0-rc.2` is now live with some minor updates to fix some edge cases around `cgroupv2` support.

Please see https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375 for instructions on how to get access to this RC (or wait for the full release at the end of next week).

**Note:** This does not directly add `debian11` support, but you can point to the `debian10` repo and install from there for now.

**Comment by klueska** [comment]
`libnvidia-container-1.8.0` with `cgroupv2` support is now GA

Release notes here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0

**Comment by klueska** [comment]
Debian 11 support has now been added such that running the following should now work as expected:
```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```
