### ISSUE TITLE
support Debian stable

### ISSUE THREAD

**Issue by jonorthwash** [NVIDIA/nvidia-docker#1589]
Currently only versions 9 and 10 of Debian are listed as supported.  These have been `oldstable` since July 2019 and August 2021, respectively.  Debian 11 has been the current stable release since August 2021; the current version is 11.2.

**Comment by elezar** [comment]
@jmpolom @jonorthwash you should be able to install the existing Debian packages on Debian stable. One thing to note is that if you are using cgroupv2 you will have to use at least `1.8.0-rc.1` of the NVIDIA Container Toolkit (see, for example, https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375).

**Comment by jmpolom** [comment]
@elezar are they officially tested and "supported" on Debian 11? What about next stable/testing? I've been able to install them on bullseye when it was in testing, but bookworm (next stable, current testing) did not seem to agree with the same packages.

It seems like nvidia doesn't and has no plans to really support Debian with container toolkit, which is unfortunate. This leaves us essentially with a choice of ubuntu (gross) or Red Hat (good, but dated). If we desire something up-to-date that isn't ubuntu there are no officially supported options it seems.

**Comment by chaiyd** [comment]
@jonorthwash https://github.com/NVIDIA/nvidia-docker/issues/1549#issuecomment-989670662
For cgroups v2, not yet fully supported, currently in testing

**Comment by klueska** [comment]
`libnvidia-container-1.8.0-rc.2` is now live with some minor updates to fix some edge cases around `cgroupv2` support.

Please see https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375 for instructions on how to get access to this RC (or wait for the full release at the end of next week).

**Note:** This does not directly add `debian11` support, but you can point to the `debian10` repo and install from there for now.

**Comment by klueska** [comment]
`libnvidia-container-1.8.0` with `cgroupv2` support is now GA

Release notes here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0

**Comment by klueska** [comment]
Debian 11 support has now been added such that running the following should now work as expected:
```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```

**Comment by chaiyd** [comment]
> Debian 11 support has now been added such that running the following should now work as expected:
> 
> ```
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
>    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
>    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> ```

Need to del  file `/etc/nvidia-container-runtime/config.toml ` on debian11 ,nvidia-docker2 can work properly

**Comment by edricus** [comment]
What about Debian 12 ?
