### ISSUE TITLE
nvidia-docker-plugin working only once (bumblebee)

### ISSUE THREAD

**Issue by silgon** [NVIDIA/nvidia-docker#159]
Hello,
I'm using nvidia-docker  from `nvidia-docker_1.0.0.rc.3_amd64.tar.xz`. I'm using ubuntu 14.04 but I'm using the installation from the tar files because I can call the plugin only when I need it using optirun (my laptop gets hot all the time if I only use the nvidia drivers, so I use bumblebee).

In order to activate the plugin I use:

    sudo optirun ./nvidia-docker-plugin

Not all documents are created as you can see next:
```
$ ls /var/lib/nvidia-docker/volumes/nvidia_driver/352.63/*
/var/lib/nvidia-docker/volumes/nvidia_driver/352.63/bin:

/var/lib/nvidia-docker/volumes/nvidia_driver/352.63/lib:
libcuda.so  libcuda.so.1  libcuda.so.352.63  libnvidia-opencl.so.1  libnvidia-opencl.so.352.63
it
/var/lib/nvidia-docker/volumes/nvidia_driver/352.63/lib64:
libcuda.so  libcuda.so.1  libcuda.so.352.63  libnvidia-opencl.so.1  libnvidia-opencl.so.352.63
```

Using `nvidia-docker` I'm able to use cuda programs. I'm not able to use `nvidia-docker run --rm nvidia/cuda nvidia-smi` as in the tutorial says (because for some reason nvidia-docker and some other files are not being copied to `/var/lib/nvidia-docker/volumes/nvidia_driver/352.63/bin` as well as some libraries. So, I think there is a problem, because I won't be able to access programs based on `libGL` in my laptop due to the lack of libraries.

Another problem that I have is that when I stop `nvidia-docker-plugin` and try to activate it again with the same command as above, it doesn't work anymore.  It loads as if it was working correctly but whenever I run a cuda implementation with `docker-nvidia` it throws some error ([error in pastebin](http://pastebin.com/BzBG7QS6)).

Any idea (advice) to help me with this issue is welcome =).

**Comment by 3XX0** [comment]
Bumblebee is not officially supported but you might be able to make it work (see #16 and #158). 

The plugin relies on the ld.so.cache to find the libraries so make sure NVIDIA libraries can be found there.
