### ISSUE TITLE
Fails to load the model on nvidia A100

### ISSUE THREAD

**Issue by zzecool** [NVIDIA/nvidia-docker#1596]
Hi there

I'm getting the following error while the engine tries to load the model :

> 2022-01-25 23:45:27,057 INFO  eu.modernmt.cluster.ClusterNode [main] Starting node in cluster "mmt-4.9.5-202102191059" with config:
> Node: load-balancing=true
>   Network: interface='172.17.0.2', port=5016, host='172.17.0.2'
>     Api: enabled=true, port=8045, root='null'
>     Join: timeout=5
>   Binlog: enabled=true, embedded=true, hosts=localhost, port=9092, name='null'
>   Database: embedded=true, enabled=true, type=CASSANDRA, port=9042, host='localhost', name='null', user='null', password='****'
>   Engine: name='default', languages=1
>     Decoder: queue=400, threads=14, gpus=0, class='null', enabled=true, echo=false
>     Aligner: enabled=false
>     Analyzer: enabled=true, analyze=true, batch=16, threads=4, timeout=30, misalignment=10240
> 2022-01-25 23:45:27,070 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
> 2022-01-25 23:45:27,883 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.55s
> 2022-01-25 23:45:28,009 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
> 2022-01-25 23:45:28,010 INFO  eu.modernmt.engine.Engine [main] Loading default pre-processing configuration
> 2022-01-25 23:45:28,026 INFO  eu.modernmt.engine.Engine [main] Loading default post-processing configuration
> 2022-01-25 23:45:28,224 INFO  eu.modernmt.decoder.neural.queue.DecoderQueueImpl [pool-6-thread-1] Native decoder process on GPU 0 is starting
> 2022-01-25 23:45:48,676 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
> 2022-01-25 23:45:48,691 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
> 2022-01-25 23:45:48,692 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
> java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
>         at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:96)
>         at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
> root@60c838310769:/opt/mmt/runtime/default/logs#

I'm using the latest  modernmt docker container in :

OS: VM running Ubuntu 20.04
CUDA: 11.4
Nvidia driver:  470.57.02
GPU: A100

nvidia-smi can see the GPU just fine from inside the modernmt container. 

Thanks in advance for any help.

**Comment by klueska** [comment]
This does not appear to be question for nvidia-docker itself (but rather some container running inside nvidia-docker). I would try asking the developers of the `modernmt` container for further help.
