### ISSUE TITLE
docker build failed 

### ISSUE THREAD

**Issue by innat** [NVIDIA/nvidia-docker#1599]
---

### 1. Issue or feature description

I was trying to make a docker file and build it. But for some reason, it fails to build. 

### 2. Steps to reproduce the issue

My `Dockerfile`. 

```
# base images
FROM nvidia/cuda:11.2.0-cudnn8-runtime

# Installation of some libraries / RUN some commands on the base image
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
    sudo \
    git \
    libx11-6 \
    locales \
    fonts-liberation \
 && rm -rf /var/lib/apt/lists/*

# https://repo.anaconda.com/miniconda/
ARG CONDA_VERSION=3
ARG CONDA_PY_VERSION=py37_4.10.3
ENV PATH /opt/conda/bin:$PATH
RUN wget https://repo.anaconda.com/miniconda/Miniconda$CONDA_VERSION-$CONDA_PY_VERSION-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo “. /opt/conda/etc/profile.d/conda.sh” >> ~/.bashrc && \
    echo “conda activate base” >> ~/.bashrc


# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

# Create the environment:
RUN conda update -n base -c defaults conda
RUN conda env create -f environment.yml
RUN echo "conda activate carCut" >> ~/.bashrc
```

And the [`environment.yml`](https://drive.google.com/file/d/1uLT53zQwDmmG-0v5BhG1yAmd0wseIoEV/view?usp=sharing)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [- ] Docker version from `docker version`  19.03.8
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by innat** [comment]
about prefix: 
- https://stackoverflow.com/a/49183565/9215780
- https://stackoverflow.com/a/41274348/9215780

**Comment by elezar** [comment]
Hi @innat. Please note that the NVIDIA Container Toolkit (and `nvidia-docker`) is intended to allow users to **run** containers with GPU support. This seems to be an issue with building a container -- which would occur with or without GPU support.

I would suggest directing this question to a forum that covers running conda in containerised environments in general.
