### ISSUE TITLE
Nvidia rate-limit is low

### ISSUE THREAD

**Issue by mahmoodn** [NVIDIA/nvidia-docker#1605]
Hi
It seems that the rate limit of the cuda repository is low based on what I see:
```
$ TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:nvidia/cuda:pull" | jq -r .token)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4355    0  4355    0     0  11706      0 --:--:-- --:--:-- --:--:-- 11738
$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
HTTP/1.1 401 Unauthorized
content-type: application/json
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:ratelimitpreview/test:pull",error="insufficient_scope"
date: Fri, 11 Feb 2022 17:14:41 GMT
content-length: 164
strict-transport-security: max-age=31536000
ratelimit-limit: 100;w=21600
ratelimit-remaining: 0;w=21600
```
That causes the this error `toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit` when I want to run a Dockerfile.

I also tried to run a test script to see when the `ratelimit-remaining` is non-zero, but I had no success. May I know how can I get the docker image?

P.S: I am trying to run this [Dockerfile](https://github.com/mlcommons/training/tree/master/reinforcement/tensorflow) from MLPERF.

**Comment by klueska** [comment]
This is not CUDA specific. This is your own rate limit for pulling any images from dockerhub:
https://www.docker.com/increase-rate-limits

Instead of building from the image hosted on dockerhub you can avoid this rate limit by building from the image hosted on NVIDIA's docker image registry at `nvcr.io`, i.e.:

```
docker pull nvcr.io/nvidia/cuda:11.6.0-devel-ubuntu20.04
```

**Comment by mahmoodn** [comment]
Thank you. I would like to know if I can browse for available images and pull the one I need. It seems that `nvcr.io` doesn't work.

**Comment by mahmoodn** [comment]
Thank you. When I browse `https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda` I only see 11.6 and 11.5 versions. Does that mean there is no image for previous versions or I have to check another website?

**Comment by klueska** [comment]
There are images for many different versions (you can see them under `tags`):
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda/tags
