### ISSUE TITLE
Unable to install from Nvidia repository due to failed "apt update"

### ISSUE THREAD

**Issue by edagca** [NVIDIA/nvidia-docker#1614]
### 1. Issue or feature description
apt update fails with the following:
W: Failed to fetch https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/InRelease  Connection failed [IP: 185.199.109.153 443]
W: Failed to fetch https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64/InRelease  Connection failed [IP: 185.199.111.153 443]
W: Failed to fetch https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/InRelease  Connection failed [IP: 185.199.109.153 443]

### 2. Steps to reproduce the issue
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt update

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

`. /etc/os-release;echo $ID$VERSION_ID` 
> ubuntu20.04

`cat /etc/apt/sources.list.d/nvidia-docker.list`
> deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
> #deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
> deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
> #deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
> deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [5.4.0-100-generic 113-Ubuntu SMP Thu Feb 3 x86_64 x86_64 x86_64 GNU/Linux ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by elezar** [comment]
@edagca since the repositories are hosted on (public) GitHub pages,  there should not be any difference between accessing these repositories or any other github-pages sites.  Do you have some kind of proxy when accessing the internet? Could you confirm that you are able to `curl` one of the files listed: (https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64/InRelease for example).

**Comment by edagca** [comment]
Thanks for the response @elezar. I don't have a proxy, but I do have a transparent SSL firewall. The CA certificate is installed on the host and I am able to access the internet. I also can curl the file you linked above.

**Comment by edagca** [comment]
@elezar,
I ended up downloading/wget these "raw" files:
```
libnvidia-container-tools_1.8.1-1_amd64.deb
libnvidia-container1_1.8.1-1_amd64.deb
nvidia-container-runtime_3.8.1-1_all.deb
nvidia-container-toolkit_1.8.1-1_amd64.deb
nvidia-docker2_2.9.1-1_all.deb
```
from https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/ubuntu18.04/amd64

Then I ran `apt install ./*.deb` and now it is working.
