### ISSUE TITLE
Typo in User Guide

### ISSUE THREAD

**Issue by BioGeek** [NVIDIA/nvidia-docker#1619]
### 1. Issue or feature description

Typo in the documentation at https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html in the section
`4. Starting a GPU enabled container on specific GPUs`:

```
docker run --gpus '"device=1,2"' \
    nvidia/cuda nvidia-smi --query-gpu=uuid --format-csv
```` 
should be:
```
docker run --gpus '"device=1,2"' \
    nvidia/cuda nvidia-smi --query-gpu=uuid --format=csv
```
Note the `=` between `--format` and `csv` instead of a `-`.

**Comment by elezar** [comment]
Thanks @BioGeek. Would you mind creating a merge request against https://gitlab.com/nvidia/cloud-native/cnt-docs to correct this? You can @ me there for the review.

**Comment by BioGeek** [comment]
Done. See [GitLab merge request #74](https://gitlab.com/nvidia/cloud-native/cnt-docs/-/merge_requests/74)

**Comment by elezar** [comment]
The MR has been merged. Thanks for the contribution. I'm going to close this for the time being, please reopen if required.
