### ISSUE TITLE
Ubuntu Jammy support

### ISSUE THREAD

**Issue by jayvdb** [NVIDIA/nvidia-docker#1623]
Ubuntu Jammy is the upcoming LTS release, currently less than a month away from final release on April 21, 2022.  Schedule of steps can be found at https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906

As this is a LTS, this release will become available as a GitHub actions runner version, and many people are eagerly waiting to be using it instead of `focal` which is a bit dated.

Jammy is already supported by docker at https://download.docker.com/linux/ubuntu/dists/

**Comment by elezar** [comment]
Thanks for the update. We will update the supported repositories and for `jammy` in time for release.

**Comment by evberrypi** [comment]
Hi @elezar, happy to test these.

**Comment by elezar** [comment]
@evberrypi we have updated our repositories so that the `ubuntu22.04` should work as a valid distribution. The release candidate (`1.10.0~rc.1-1`) has been published to our `experimental` repositories, so this should also be available.

**Comment by elezar** [comment]
@jayvdb we have updated our repositories with Jammy support. I'm closing this issue but feel free to reopen if there are any issues.

**Comment by lacker** [comment]
Minor detail but I noticed ubuntu22 is not listed as supported in the docs: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

**Comment by elezar** [comment]
> Minor detail but I noticed ubuntu22 is not listed as supported in the docs: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

We will update the support matrix along with the docs update for the upcoming 1.10 release of the NVIDIA Container Toolkit.
