### ISSUE TITLE
Troubles at postinstallation

### ISSUE THREAD

**Issue by HoloSound** [NVIDIA/nvidia-docker#163]
nvidia-docker (1.0.0~rc.3-1) wird eingerichtet ...
Setting up permissions
chown: ungültige Spezifikation: »nvidia-docker:“
dpkg: Fehler beim Bearbeiten des Paketes nvidia-docker (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
Fehler traten auf beim Bearbeiten von:
 nvidia-docker
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@studio16:~#

**Comment by 3XX0** [comment]
You are upgrading from an old package and we used to have some packaging issue at the time.
You need to purge your previous installation first:
```
sudo dpkg --purge nvidia-docker
```
