### ISSUE TITLE
Error: Unexpected file size during cuda installation

### ISSUE THREAD

**Issue by rrlamichhane** [NVIDIA/nvidia-docker#1633]
### 1. Issue or feature description

I followed the instructions for key rotation laid out here:
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772

### 2. Steps to reproduce the issue

Run these steps inside a Dockerfile

```
FROM ubuntu:20.04 AS base
...
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb
RUN apt update && apt install -y cuda-compat-11-4
```

Error details:
```
#8 7.228 E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/Packages.gz  File has unexpected size (631054 != 481481). Mirror sync in progress? [IP: 152.195.19.142 443]
#8 7.228    Hashes of expected file:
#8 7.228     - Filesize:481481 [weak]
#8 7.228     - SHA256:8556d67c6d380c957f05057f448d994584a135d7ed75e5ae6bb25c3fc1070b0b
#8 7.228     - SHA1:c5ea9556407a3b5daec4aac530cd038e9b490441 [weak]
#8 7.228     - MD5Sum:a5513131dbd2d4e50f185422ebb43ac9 [weak]
#8 7.228    Release file created at: Mon, 25 Apr 2022 23:27:19 +0000
```

**Comment by rrlamichhane** [comment]
This issue seems to be resolved. The installation is working fine for me now. Closing.

**Comment by bidva** [comment]
get same problem here 

```
#18 10.40 E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (815853 != 814314). Mirror sync in progress? [IP: 152.195.19.142 443]
#18 10.40    Hashes of expected file:
#18 10.40     - Filesize:814314 [weak]
#18 10.40     - SHA256:257071ac3a46f8e8ba340c2bd6b88466ff26e4cb0c4b60afacfb267b251dc2d9
#18 10.40     - SHA1:4b2ecd5529c611f17784b07ed4cb2b13d5d4bd25 [weak]
#18 10.40     - MD5Sum:0355ef69bc6b6afaf8493d82295c3633 [weak]
#18 10.40    Release file created at: Mon, 11 Jul 2022 19:02:21 +0000
#18 10.40 E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by 0i0** [comment]
same
`Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages [580 kB]
Err:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages
  File has unexpected size (580845 != 580040). Mirror sync in progress? [IP: 152.195.19.142 443]
  Hashes of expected file:
   - Filesize:580040 [weak]
   - SHA256:dc8abbaf470d3ee626f4f1f4d2871a98d8dc8f770bc592676f0d1f60637e0c2d
   - SHA1:109bfa4e5c415731aa44b1c1caae3f19754c5406 [weak]
   - MD5Sum:bf8f928cb55b1c9e4c158a69ee52b5d8 [weak]
  Release file created at: Mon, 11 Jul 2022 19:01:54 +0000
Fetched 1,581 B in 0s (4,273 B/s)
Reading package lists... Done
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/Packages.gz  File has unexpected size (580845 != 580040). Mirror sync in progress? [IP: 152.195.19.142 443]
   Hashes of expected file:
    - Filesize:580040 [weak]
    - SHA256:dc8abbaf470d3ee626f4f1f4d2871a98d8dc8f770bc592676f0d1f60637e0c2d
    - SHA1:109bfa4e5c415731aa44b1c1caae3f19754c5406 [weak]
    - MD5Sum:bf8f928cb55b1c9e4c158a69ee52b5d8 [weak]
   Release file created at: Mon, 11 Jul 2022 19:01:54 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by JackCaoG** [comment]
I had the same issue yesterday but now it is resolved.

**Comment by elezar** [comment]
This was a transient issue in the CUDA repository. It has since been resolved.
