### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ShangwenWang** [NVIDIA/nvidia-docker#1639]
Hello,
I just wish to know that if the NVIDIA-docker can be installed on a Win system?
I note in the README doc, it is said to be installed on a Linux system only.

**Comment by elezar** [comment]
Hi @ShangwenWang. The NVIDIA Container Toolkit (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html) is currently Linux only. There is some experimental support for WSL2 which allows certain container workloads to be run on Windows systems.

**Comment by ShangwenWang** [comment]
Thanks @elezar 
Thank you for the details.
