### ISSUE TITLE
Missing libnvidia-ml.so on remote terminals

### ISSUE THREAD

**Issue by Kaixhin** [NVIDIA/nvidia-docker#164]
I've been trying to migrate my [cuda-ssh](https://hub.docker.com/r/kaixhin/cuda-ssh/) and [cuda-vnc](https://hub.docker.com/r/kaixhin/cuda-vnc/) images to use `nvidia-docker`, but get the "NVIDIA-SMI couldn't find libnvidia-ml.so library in your system." error when I try to run `nvidia-smi` command in a terminal over SSH or on my VNC remote desktop. It is not to do with daemon mode (`-d`), as I can successfully run `docker exec -it <container> nvidia-smi` on the host once the SSH/VNC servers are up.

**Comment by 3XX0** [comment]
By default we have no other choice but to use `LD_LIBRARY_PATH` to find libraries within the image.
When starting a new SSH or VNC session this environment variable is wiped out. You can issue `ldconfig` in your `CMD` before starting your server and it will work fine

**Comment by Kaixhin** [comment]
Thanks for the info - managed to get `nvidia-smi` working in both cases now.
