### ISSUE TITLE
undefined reference to `nvmlInit_v2'

### ISSUE THREAD

**Issue by JinXiaozhao** [NVIDIA/nvidia-docker#1641]
docker images: nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04
docker images start command: docker run -it --rm --gpus all  nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04 bash
nvidia-smi works fine: 
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |

c++ code:
 test_gpu_memory.cc
```
#include <iostream>
#include<string>
#include<unistd.h>
#include "nvml.h"
using namespace std;
int main()
{
    nvmlReturn_t result;
    unsigned int device_count, i;
    // First initialize NVML library
    result = nvmlInit();

    result = nvmlDeviceGetCount(&device_count);
    if (NVML_SUCCESS != result)
    {
        std::cout << "Failed to query device count: " << nvmlErrorString(result);
    }
    std::cout << "Found" << device_count <<" device" << endl;

    std::cout << "Listing devices:";
    while (true)
    {
        for (i = 0; i < device_count; i++)
        {
            nvmlDevice_t device;
            char name[NVML_DEVICE_NAME_BUFFER_SIZE];
            nvmlPciInfo_t pci;
            result = nvmlDeviceGetHandleByIndex(i, &device);
            if (NVML_SUCCESS != result) {
                std::cout << "get device failed " << endl;
            }
            result = nvmlDeviceGetName(device, name, NVML_DEVICE_NAME_BUFFER_SIZE);
            if (NVML_SUCCESS != result) {
                std::cout << "GPU name： " << name << endl;
            }
            //使用率
            nvmlUtilization_t utilization;
            result = nvmlDeviceGetUtilizationRates(device, &utilization);
            if (NVML_SUCCESS == result)
            {
                cout << " GPU id: "<< i << endl;
                cout << "GPU util is: " << utilization.gpu << endl;
            }
        }
		std::cout << "==========================="<<endl;
        sleep(10);
    }
    return 0;
}
```

compile command: g++  -L/usr/local/cuda/targets/x86_64-linux/lib/stubs/ -lnvidia-ml -I/usr/local/cuda/include test_gpu_memory.cc -o test_gpu_memory

error: 
g++  -L/usr/local/cuda/targets/x86_64-linux/lib/stubs/ -lnvidia-ml -I/usr/local/cuda/include test_gpu_memory.cc -o test_gpu_memory
/tmp/ccdUXbt5.o: In function `main':
test_gpu_memory.cc:(.text+0x1c): undefined reference to `nvmlInit_v2'
test_gpu_memory.cc:(.text+0x31): undefined reference to `nvmlDeviceGetCount_v2'
test_gpu_memory.cc:(.text+0x63): undefined reference to `nvmlErrorString'
test_gpu_memory.cc:(.text+0xfe): undefined reference to `nvmlDeviceGetHandleByIndex_v2'
test_gpu_memory.cc:(.text+0x150): undefined reference to `nvmlDeviceGetName'
test_gpu_memory.cc:(.text+0x1b2): undefined reference to `nvmlDeviceGetMemoryInfo'
test_gpu_memory.cc:(.text+0x237): undefined reference to `nvmlDeviceGetUtilizationRates'
collect2: error: ld returned 1 exit status

**Comment by JinXiaozhao** [comment]
> docker images: nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04 docker images start command: docker run -it --rm --gpus all nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04 bash nvidia-smi works fine: nvidia-smi +-----------------------------------------------------------------------------+ | NVIDIA-SMI 460.106.00 Driver Version: 460.106.00 CUDA Version: 11.2 |
> 
> c++ code: test_gpu_memory.cc
> 
> ```
> #include <iostream>
> #include<string>
> #include<unistd.h>
> #include "nvml.h"
> using namespace std;
> int main()
> {
>     nvmlReturn_t result;
>     unsigned int device_count, i;
>     // First initialize NVML library
>     result = nvmlInit();
> 
>     result = nvmlDeviceGetCount(&device_count);
>     if (NVML_SUCCESS != result)
>     {
>         std::cout << "Failed to query device count: " << nvmlErrorString(result);
>     }
>     std::cout << "Found" << device_count <<" device" << endl;
> 
>     std::cout << "Listing devices:";
>     while (true)
>     {
>         for (i = 0; i < device_count; i++)
>         {
>             nvmlDevice_t device;
>             char name[NVML_DEVICE_NAME_BUFFER_SIZE];
>             nvmlPciInfo_t pci;
>             result = nvmlDeviceGetHandleByIndex(i, &device);
>             if (NVML_SUCCESS != result) {
>                 std::cout << "get device failed " << endl;
>             }
>             result = nvmlDeviceGetName(device, name, NVML_DEVICE_NAME_BUFFER_SIZE);
>             if (NVML_SUCCESS != result) {
>                 std::cout << "GPU name： " << name << endl;
>             }
>             //使用率
>             nvmlUtilization_t utilization;
>             result = nvmlDeviceGetUtilizationRates(device, &utilization);
>             if (NVML_SUCCESS == result)
>             {
>                 cout << " GPU id: "<< i << endl;
>                 cout << "GPU util is: " << utilization.gpu << endl;
>             }
>         }
> 		std::cout << "==========================="<<endl;
>         sleep(10);
>     }
>     return 0;
> }
> ```
> 
> compile command: g++ -L/usr/local/cuda/targets/x86_64-linux/lib/stubs/ -lnvidia-ml -I/usr/local/cuda/include test_gpu_memory.cc -o test_gpu_memory
> 
> error: g++ -L/usr/local/cuda/targets/x86_64-linux/lib/stubs/ -lnvidia-ml -I/usr/local/cuda/include test_gpu_memory.cc -o test_gpu_memory /tmp/ccdUXbt5.o: In function `main': test_gpu_memory.cc:(.text+0x1c): undefined reference to `nvmlInit_v2' test_gpu_memory.cc:(.text+0x31): undefined reference to `nvmlDeviceGetCount_v2' test_gpu_memory.cc:(.text+0x63): undefined reference to `nvmlErrorString' test_gpu_memory.cc:(.text+0xfe): undefined reference to `nvmlDeviceGetHandleByIndex_v2' test_gpu_memory.cc:(.text+0x150): undefined reference to `nvmlDeviceGetName' test_gpu_memory.cc:(.text+0x1b2): undefined reference to `nvmlDeviceGetMemoryInfo' test_gpu_memory.cc:(.text+0x237): undefined reference to `nvmlDeviceGetUtilizationRates' collect2: error: ld returned 1 exit status

**Comment by elezar** [comment]
@JinXiaozhao could you confirm the location of `libnvidia-ml.so*`. You seem to be specifying `/usr/local/cuda/targets/x86_64-linux/lib/stubs/` as the linker path, but the library is most likely in `/usr/lib/x86_64-linux-gnu`.
