### ISSUE TITLE
could not select device driver with capabilities

### ISSUE THREAD

**Issue by Maryamtarazkar** [NVIDIA/nvidia-docker#1642]
Dear Docker support team, 
I am trying to install a software that needs to run on GPU. when I check whether that software is able to use a GPU uisng follwoing command; 
docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

I get following error; 
docker: Error response from daemon: could not select device driver with capabilities: [[gpu]].

Can someone help me how to fix this error?

Thanks in advanced

**Comment by elezar** [comment]
Hi @Maryamtarazkar. Some questions:

* Is the NVIDIA Container Toolkit installed (`nvidia-container-toolkit`)?
* How is docker installed?

A similar issue was recently reported in #1637 and this was due to docker being installed as a snap.

**Comment by elezar** [comment]
Closing this issue do to lack of activity. If you're still having problems please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit instead.
