### ISSUE TITLE
gtx1070 caffe train digit error (error == cudaSuccess (8 vs. 0) invalid device function)

### ISSUE THREAD

**Issue by xiaoxinyi** [NVIDIA/nvidia-docker#165]
╭─root at 5420e0794e25 in ~ using
╰─○ ls -al /dev | grep nvidia
crw-rw-rw- 1 root root 243, 0 Aug 4 06:01 nvidia-uvm
crw-rw-rw- 1 root root 243, 1 Aug 4 06:07 nvidia-uvm-tools
crw-rw-rw- 1 root root 195, 0 Aug 4 06:01 nvidia0
crw-rw-rw- 1 root root 195, 255 Aug 4 06:01 nvidiactl
╭─root at 5420e0794e25 in ~ using
╰─○ nvidia-smi
Thu Aug 4 07:09:57 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.35 Driver Version: 367.35 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 GeForce GTX 1070 Off | 0000:01:00.0 On | N/A |
| 0% 34C P8 10W / 230W | 514MiB / 8105MiB | 0% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
+-----------------------------------------------------------------------------+
╭─root at 5420e0794e25 in ~ using
╰─○ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Wed_May__4_21:01:56_CDT_2016
Cuda compilation tools, release 8.0, V8.0.26

F0804 07:20:57.251991   961 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***
    @     0x7f8b75c42daa  (unknown)
    @     0x7f8b75c42ce4  (unknown)
    @     0x7f8b75c426e6  (unknown)
    @     0x7f8b75c45687  (unknown)
    @     0x7f8b76344410  caffe::PoolingLayer<>::Forward_gpu()
    @     0x7f8b7619b748  caffe::Net<>::ForwardFromTo()
    @     0x7f8b7619bac7  caffe::Net<>::Forward()
    @     0x7f8b7633bfdc  caffe::Solver<>::Test()
    @     0x7f8b7633ca4e  caffe::Solver<>::TestAll()
    @     0x7f8b7633cb40  caffe::Solver<>::Step()
    @     0x7f8b7633d4f9  caffe::Solver<>::Solve()
    @           0x40b545  train()
    @           0x40897c  main
    @     0x7f8b74440f45  (unknown)
    @           0x409283  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by flx42** [comment]
That's normal because our DIGITS/caffe images are based on CUDA 7.5.
For GeForce 10 cards, you need CUDA 8.0

Hopefully, we will have new packages for Caffe soon!

**Comment by flx42** [comment]
Sorry, I read too fast. It looks like you didn't use our official image since you have CUDA 8.0 and nvcc inside the container.
Did you use the official Dockerfile from BVLC?
https://github.com/BVLC/caffe/blob/master/docker/standalone/gpu/Dockerfile

In this case, it's because the CUDA cmake module of BVLC/caffe does not support Pascal boards:
https://github.com/BVLC/caffe/blob/master/cmake/Cuda.cmake#L7

You should modify the cmake command in the Dockerfile:
```
cmake -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="61" -DCUDA_ARCH_PTX="61" -DUSE_CUDNN=1 ..
```

**Comment by xiaoxinyi** [comment]
FROM nvidia/cuda:8.0-cudnn5-devel

MAINTAINER Sai Soundararaj <saip@outlook.com>

ARG THEANO_VERSION=rel-0.8.2
ARG TENSORFLOW_VERSION=0.8.0
ARG TENSORFLOW_ARCH=gpu
ARG KERAS_VERSION=1.0.3
ARG LASAGNE_VERSION=v0.1
ARG TORCH_VERSION=latest
ARG CAFFE_VERSION=master

#RUN echo -e "\n**********************\nNVIDIA Driver Version\n**********************\n" && \
#       cat /proc/driver/nvidia/version && \
#       echo -e "\n**********************\nCUDA Version\n**********************\n" && \
#       nvcc -V && \
#       echo -e "\n\nBuilding your Deep Learning Docker Image...\n"

# Install some dependencies
RUN apt-get update && apt-get install -y \
                bc \
                build-essential \
                cmake \
                curl \
                g++ \
                gfortran \
                git \
                libffi-dev \
                libfreetype6-dev \
                libhdf5-dev \
                libjpeg-dev \
                liblcms2-dev \
                libopenblas-dev \
                liblapack-dev \

**Comment by xiaoxinyi** [comment]
My FROM image is nvida/cuda:8.0-cudnn5-devel. The rest dockfile copy from offical Dockerfile from BLVC

**Comment by xiaoxinyi** [comment]
@flx42 Thanks. With the cmake flags, I solve my problem.

**Comment by coreindustries** [comment]
I have built a working DIGITS / cuda 8 docker image that works with Titan X Pascal GPUs.
https://hub.docker.com/r/coreindustries/digits/

Hope this saves someone some grief. :)
