### ISSUE TITLE
nvidia-docker-plugin error

### ISSUE THREAD

**Issue by xiaoxinyi** [NVIDIA/nvidia-docker#166]
╰─± nvidia-docker-plugin
nvidia-docker-plugin | 2016/08/04 19:15:08 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/08/04 19:15:08 Loading NVIDIA management library
nvidia-docker-plugin | 2016/08/04 19:15:08 Discovering GPU devices
nvidia-docker-plugin | 2016/08/04 19:15:08 Provisioning volumes at /var/lib/nvidia-docker/volumes
nvidia-docker-plugin | 2016/08/04 19:15:08 Serving plugin API at /run/docker/plugins
nvidia-docker-plugin | 2016/08/04 19:15:08 Serving remote API at localhost:3476
nvidia-docker-plugin | 2016/08/04 19:15:08 Error: listen unix /run/docker/plugins/nvidia-docker.sock: bind: permission denied

**Comment by flx42** [comment]
Are you starting `nvidia-docker-plugin` as root?

You should use the deb or rpm package, if you can.

**Comment by xiaoxinyi** [comment]
I used deb for installation and start `nvidia-docker-plugin` as normal user.
When I run `systemctl status gpu-manager.service`, 
`╰─○ systemctl status gpu-manager.service
● gpu-manager.service - Detect the available GPUs and deal with any system changes
   Loaded: loaded (/lib/systemd/system/gpu-manager.service; enabled; vendor preset: enabled)
   Active: inactive (dead) 
 Main PID: 2656 (code=exited, status=0/SUCCESS)`

**Comment by 3XX0** [comment]
What OS are you using? If you used the deb, the plugin should already be running.
You can check its status with `systemctl status nvidia-docker`
