### ISSUE TITLE
Support for Rocky 8 please

### ISSUE THREAD

**Issue by tin6150** [NVIDIA/nvidia-docker#1669]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

Centos 8 is supported, but it is EOL.
my organization is using Rocky.  Other may be using Alma?  It would be nice if these are supported.
thx!
tin

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by elezar** [comment]
@tin6150 you should be able to install the `centos8` packages in the mean time. We do have Rocky 8 support on our roadmap, but don't have a date yet.

**Comment by cccsss01** [comment]
I'm also a fan, looking for Alma

**Comment by shiz0** [comment]
It works using the version correspondent RHEL Repo. I just installed on Rocky 8.6 using RHEL 8.6 URL, seems to work so far.

**Comment by elezar** [comment]
With the v1.14.0 release we reworked our package repositories. 

Please see the instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-yum-or-dnf) for installing the packages on supported RPM-based systems.

If there are still problems, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit
