### ISSUE TITLE
What's the point of NVIDIA Driver Container if it requires >= 418.81.07 NVIDIA Driver as dependency in the first place?

### ISSUE THREAD

**Issue by junwang-wish** [NVIDIA/nvidia-docker#1681]
This is a general question about the motivation of [NVIDIA Driver Container](https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html). My understanding is that it is [one out of three ways to install NVIDIA Driver](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#install-types), supposedly the most portable and easy way. 

However it is surprising that [NVIDIA Driver Container](https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html) requires [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html) as a dependency, and [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html) requires [>= 418.81.07 NVIDIA Driver](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#platform-requirements) as a dependency...

If [NVIDIA Driver Container](https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html)'s purpose is to make NVIDIA Driver installation easy, why does it require an installed driver in the first place?

**Comment by elezar** [comment]
I think that might be a issue with our documentation.

The NVIDIA Driver Container does not need the NVIDIA Container Toolkit to run, but the container toolkit must be configured to specify a different `root` option when the NVIDIA Driver Container is used.

**Comment by junwang-wish** [comment]
Thanks @elezar , this is the line in the documentation (underlined with red) that could be misleading: 
<img width="685" alt="Screen Shot 2022-09-19 at 11 38 41 AM" src="https://user-images.githubusercontent.com/112650299/191057317-2005e796-4ddb-4f64-a1e6-7cb79f92ccff.png">

**Comment by nvjmayo** [comment]
@junwang-wish 
It's my fault that GPU Driver Container's documentation is not in a good state. Sorry for the inconvenience!

**Comment by junwang-wish** [comment]
No worries, thanks for the clarification @nvjmayo 
However unfortunately, following the [doc](https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html) for installing and using Drive container, while having correct `/etc/nvidia-container-runtime/config.toml`, and as well as having Container Toolkit installed leads to some errors shown here (I opened it as another issue, so feel free to close this one): 

https://github.com/NVIDIA/nvidia-docker/issues/1680#issuecomment-1251067054

**Comment by nvjmayo** [comment]
Thank you!
