### ISSUE TITLE
NVIDIA provided Azure image NVIDIA HPC SDK VM image can not run cuda container

### ISSUE THREAD

**Issue by artisticcheese** [NVIDIA/nvidia-docker#1687]
### 1. Issue or feature description
I created brand new NVIDIA HPC SDK VM Image (https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nvidia.nvidia_hpc_sdk_vmi?tab=overview) but can not run any cuda based docker container. 

```
cloudadmin@cuda-vm1:~$ sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi  
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.

```

### 2. Steps to reproduce the issue
Instantiate any NVIDIA provided Azure VM images and try to run test `docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`
This would fail to run

**Comment by artisticcheese** [comment]
Per official NVIDIA documents following are part of the image

```
Version 22.08.0
Ubuntu Server 20.04
NVIDIA Driver 515.65.01
Docker-ce 20.10.17
NVIDIA Container Toolkit Version: 1.10.1-1
NVIDIA Container Runtime Version: 3.10.0-1
Azure Command Line Interface (CLI)
```
Running `nvidia-smi` producing following error. This is default unaltered image in Azure, no customization was done to it.

```
cloudadmin@cuda-vm1:~$ sudo nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Comment by elezar** [comment]
The NVIDIA Container Toolkit requires the NVIDIA GPU Driver to be installed on the host (the VM image in this case). Is your VM configured with GPUs and is the driver installed / configured correctly? (I don't have any experience with the VM Images and as such can't be of additional help).

**Comment by artisticcheese** [comment]
I think I choose wrong type of VM since during boot up following is being written out to console

```Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.


Warning: Unsupported instance type for NVIDIA GPU Cloud Machine Image.
Please use an ND, NCv2, or NCv3 instance for optimal performance and reliability.

```
