### ISSUE TITLE
cannot get nvidia-docker2

### ISSUE THREAD

**Issue by mathpopo** [NVIDIA/nvidia-docker#1698]
dear nvidia:
        i try to get nvidia-docker,but cannot 
i do as https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html
uname -a
Linux chenxin-Nitro-AN515-52 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mathpopo** [comment]
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/experimental/$distribution/libnvidia-container.list | \
         sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
         sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

**Comment by mathpopo** [comment]
For distribution values of ubuntu20.04 or ubuntu22.04 the file will contain ubuntu18.04 URLs

**Comment by mathpopo** [comment]
https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /

**Comment by rokopi-byte** [comment]
Read the documentation:
```

Note that in some cases the downloaded list file may contain URLs that do not seem to match the expected value of distribution which is expected as packages may be used for all compatible distributions. As an examples:

        For distribution values of ubuntu20.04 or ubuntu22.04 the file will contain ubuntu18.04 URLs

        For a distribution value of debian11 the file will contain debian10 URLs
```

You don't have to modify explicitly any URL. Also, probabily you don't even need nvidia-docker2, see [here](https://github.com/NVIDIA/nvidia-docker/issues/1268#issuecomment-632692949)

**Comment by mathpopo** [comment]
@rokopi-byte first very thank you for your help, i just use 18.04 instead of 20.04 ,and run as https://www.server-world.info/en/note?os=Ubuntu_20.04&p=nvidia&f=2,but also show "https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/" have no files, # Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container

**Comment by elezar** [comment]
@mathpopo since there is no index.html at the https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/ this shows "Unsupported Distribution" Which is the generic 404 error shown for the site.

The package manager will construct the relevant URLs based on the contents of the repo rooted at `https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64/` and download the packages this way.

@mathpopo what are the contents of your `.list` file in `/etc/apt/sources.list.d` and what is the exact error that you are seeing?

**Comment by elezar** [comment]
Hi. With the 1.14.0 release we have updated our package repositories to use a single `deb` repository for all supported distributions. Please follow the instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt).

If you are still having problems, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit.
