### ISSUE TITLE
failed to locate NVIDIA Container Runtime Hook

### ISSUE THREAD

**Issue by ZTurboX** [NVIDIA/nvidia-docker#1714]
### 1. Issue or feature description

after install nvidia-docker2 and run "docker run --runtime=nvidia --rm nvidia/cuda:10.2-base nvidia-smi"

### 2. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
Docker version 20.10.13, build a224086

![image](https://user-images.githubusercontent.com/5669444/206621414-ffe4e549-8164-428c-bb2a-60f7df9ca1a0.png)

**Comment by klueska** [comment]
Was it a fresh install or an upgrade from nvidia-docker2 v1.10? If it was an upgrade you could be running into this:
https://github.com/NVIDIA/nvidia-docker/issues/1674#issuecomment-1251113118

**Comment by elezar** [comment]
Please see @klueska's comment above. If this problem persists with an up to date version of the NVIDIA Container Toolkit, please create an issue against https://github.com/NVIDIA/nvidia-container-toolkit
