### ISSUE TITLE
Repo is not accessible in China

### ISSUE THREAD

**Issue by xkszltl** [NVIDIA/nvidia-docker#1722]
### Issue or feature description

Currently if we try to install with according to the doc, we'll consistently get connection reset from nvidia.github.io
```
$ curl -sSL --retry 1000 --retry-connrefused --retry-delay 1 --retry-all-errors https://nvidia.github.io/nvidia-docker/gpgkey
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to nvidia.github.io:443 
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to nvidia.github.io:443 
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to nvidia.github.io:443 
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to nvidia.github.io:443
```

This is possibly due to the firewall in China blocking github.io traffic via SNI check.
The IP it resolves to is normally accessible and can return github's page-not-found.

github.io is hosting a lot of things, some can be sensitive and subject to censorship.
Can we have alternative way of hosting nvidia-docker repo?

**Comment by elezar** [comment]
The packages for the NVIDIA Container Toolkit are now available directly from the CUDA Downloads repository in addition to GitHub Pages.
