### ISSUE TITLE
Is it possible to start a stopped container with GPU?

### ISSUE THREAD

**Issue by TrueWodzu** [NVIDIA/nvidia-docker#1728]
### 1. Issue or feature description
I know that I can run a container with GPU like this:
`docker run -it --gpus all <image>:<tag>`

Is it possible to start a stopped container with GPU support? When I try following command:
`docker container start -ai --gpus all <container id>` I am getting error `unknown flag: --gpus`

**Comment by PQLLUX** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/1211 
No.
