### ISSUE TITLE
nvidia-docker-plugin can't start a container of caffe 

### ISSUE THREAD

**Issue by Tyranter** [NVIDIA/nvidia-docker#173]
When I start a container of caffe (BVLC gpu version) with nvidia-docker,it shows "nvidia-docker-plugin Error: link /usr/bin/nvidia-cuda-mps-control /var/lib/nvidia-docker/volumes/nvidia_driver/352.39/bin/nvidia-cuda-mps-control: invalid cross-device link"
I have installed cuda7.5 in the host machine,and the host machine can run caffe in gpu mode.The caffe image is built by the Dockerfile provide by the BVLC(https://github.com/BVLC/caffe/tree/master/docker) .
Thanks for your help!

**Comment by 3XX0** [comment]
See #133, this limitation is documented on the [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#known-limitations)

**Comment by Tyranter** [comment]
Thanks for your reply@3xx0:
I follow the introduction of #133,but it does not work, the volume path is still /var....The difference is that I'm working on CentOS7.But I find another way: I run "nvidia- docker- plugin -d /usr/local/nvidia- driver". But it need keep running all the time.When it stops, it will be /var/... again.

**Comment by Tyranter** [comment]
@3XX0

**Comment by flx42** [comment]
Did you try following this [comment](https://github.com/NVIDIA/nvidia-docker/issues/133#issuecomment-234138060)? And then you need to restart the `nvidia-docker` service.
