### ISSUE TITLE
manifest for nvidia/cuda:11.0-base-ubuntu20.04 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by johnny-rodriguez** [NVIDIA/nvidia-docker#1735]
johnny-ubuntu:~$ lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

When I run the following, I get an error:
johnny-ubuntu:~$ docker run --rm --gpus all nvidia/cuda:11.0-base-ubuntu20.04 nvidia-smi

Unable to find image 'nvidia/cuda:11.0-base-ubuntu20.04' locally
docker: Error response from daemon: manifest for nvidia/cuda:11.0-base-ubuntu20.04 not found: manifest unknown: manifest unknown.
See 'docker run --help'.

However, when I run the following, it looks perfectly fine:
johnny-ubuntu:~$ sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi

Sun Mar  5 20:06:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8    14W / 350W |      5MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

I have an GeForce 3080 Ti. I have little experience with docker and nvidia drivers, so any help would be greatly appreciated.

UPDATE: Did the nvidia/cuda:11.0-base image get removed?

**Comment by elezar** [comment]
Yes, the image was removed. Please use the `nvidia/cuda:11.0.3-base-${DIST}` images instead. `DIST` can be (among others): `ubuntu20.04`, `ubuntu18.04`, `centos7` (see the list of [tags](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.0.3-base-)).

Note that this does not have to match the system where you are running the containers.

**Comment by kbpark102** [comment]
When i use nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04, i used libcudnn8=8.0.4.30-1+cuda11.0
but i can't use libcudnn8=8.0.4.30-1+cuda11.0 in nvidia/cuda:**11.0.3**-cudnn8-devel-ubuntu18.04
please let me know the cudnn version for nvidia/cuda:**11.0.3**-cudnn8-devel-ubuntu18.04

**Comment by Undefinedefity** [comment]
You can try different registry mirror, like mine ( I don't know if this can help because this registry mirror is China but it works for me):
1. go to `/etc/docker/daemon.json`
2. change the content to be 
```json
{
  "registry-mirrors": [
    "https://hub-mirror.c.163.com",
    "https://mirror.baidubce.com"
  ]
}
```
3. run these two commands to restart docker
```shell
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by dvdknaap** [comment]
incase people like me also had this problem.

This [link](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=%25-base) will be more future proof

**Comment by elezar** [comment]
Please see: 
* https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md
* https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md

The lifetime of images is out of scope for this project, so please consider opening an issue there instead.
