### ISSUE TITLE
Cannot get nvidia-docker2 to run

### ISSUE THREAD

**Issue by Overcraft90** [NVIDIA/nvidia-docker#1742]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
After following the steps [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker), I'm not able to run my NVIDIA Container Toolkit properly
### 2. Steps to reproduce the issue
At first, I got my Docker Desktop running on `Ubuntu 22.04` then I did the following: 
```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container//ubuntu22.04/libnvidia-container.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```
`sudo apt-get update`

`sudo apt-get install -y nvidia-container-toolkit`

`sudo nvidia-ctk runtime configure --runtime=docker`

`sudo systemctl restart docker`
And until here everything was fine, but then when running
`sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`
I got prompted the following message

> docker: Error response from daemon: Unknown runtime specified nvidia.
> See 'docker run --help'.

Please, any help is appreciated, as #838 seems to do not solve my issue...
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [[nvidia-container-cli.log](https://github.com/NVIDIA/nvidia-docker/files/11023481/nvidia-container-cli.log)] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [5.19.0-35-generic] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [[nvidia-smi.log](https://github.com/NVIDIA/nvidia-docker/files/11023503/nvidia-smi.log)] Driver information from `nvidia-smi -a`
 - [ `23.0.1`] Docker version from `docker version` (but I got also _permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied Client: Docker Engine - Community_)
 - [[nvidia-packages.log](https://github.com/NVIDIA/nvidia-docker/files/11023571/nvidia-packages.log)] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [[nvidia-container-library.log](https://github.com/NVIDIA/nvidia-docker/files/11023593/nvidia-container-library.log)] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by bsamadi** [comment]
Same here

**Comment by Overcraft90** [comment]
Sure, here is the content of mine
```
{
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}
```

**Comment by elezar** [comment]
OK, so you're running Docker Desktop? As far as I know this means that docker is running in a virtual machine and is not configured through the `/etc/docker/daemon.json` config.

**Comment by Overcraft90** [comment]
Ah I see, I deemed a bit more safe than the conventional Docker. What should I do in this situation?

**Comment by bsamadi** [comment]
Thank you @elezar for the point Docker Desktop running in a virtual machine. I uninstalled Docker Desktop and only installed Docker Engine. Everything now works as expected.

**Comment by Overcraft90** [comment]
Nice, thank you so much @elezar and @bsamadi. This solved the problem for me as well; I just have to switch to Docker Engine.
