### ISSUE TITLE
Outdated/invalid documentation on docs.nvidia.com

### ISSUE THREAD

**Issue by AntonOfTheWoods** [NVIDIA/nvidia-docker#1744]
### 1. Issue or feature description
Documentation bug (very outdated).

### 2. Steps to reproduce the issue
Try and install/activate with the documentation on https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

From https://hub.docker.com/r/nvidia/cuda
```
$ docker pull nvidia/cuda
Error response from daemon: manifest for nvidia/cuda:latest not found: manifest unknown: manifest
unknown
This is not a bug.
```

Well if this is not a bug then why, pray tell, does the documentation on https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html tell you to do this:

```
Starting a GPU enabled CUDA container; using --gpus

docker run --rm --gpus all nvidia/cuda nvidia-smi
```

That last command can't possibly work, due it "not being a bug" that there is no `latest` tag. It looks like there are other things that had solutions multiple years ago (like a very old PGP key setup) that still haven't found their way into the docs. At least maybe get GPT4 to have a look at the docs?

**Comment by elezar** [comment]
We have recently revamped our documentation.

Please see if things are clearer now. If there are still issues, please consider opening an issue against https://github.com/NVIDIA/nvidia-container-toolkit.
