### ISSUE TITLE
Deprecation Notice with CUDA 11.3.0

### ISSUE THREAD

**Issue by Overcraft90** [NVIDIA/nvidia-docker#1745]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
While running a tool ([DeepVariant](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md)) which leverages GPU acceleration, I get prompted the following
```
==========
== CUDA ==
==========

CUDA Version 11.3.0

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
```
I made sure to follow the instruction as per [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker); however, for some reason, I'm not getting the latest version for the NVIDIA Toolkit Container used by Docker.

If relevant, how can I safely update to the latest stable version?
### 2. Steps to reproduce the issue
```
sudo docker run --gpus 1 
--workdir path/to/DeepVariant 
--mount "type=bind,src=path/to/DeepVariant,dst=path/to/DeepVariant" 
google/deepvariant:"1.5.0-gpu"
/opt/deepvariant/bin/run_deepvariant 
--model_type=WGS 
--ref=path/to/DeepVariant/input/GRCh38_snarls_removed.fna 
--reads=/path/to/DeepVariant/input/HG002_sorted.bam 
--output_vcf=path/to//DeepVariant/output/HG002-output.vcf.gz 
--output_gvcf=/path/to/DeepVariant/output/HG002-output.gvcf.gz 
--num_shards=16
```
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [[nvidia-container-info.log](https://github.com/NVIDIA/nvidia-docker/files/11204622/nvidia-container-info.log)] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [5.19.0-38-generic] Kernel version from `uname -a`
 - [`none`] Any relevant kernel output lines from `dmesg`
 - [[nvidia-smi-a.log](https://github.com/NVIDIA/nvidia-docker/files/11204631/nvidia-smi-a.log)] Driver information from `nvidia-smi -a`
 - [[docker_version.log](https://github.com/NVIDIA/nvidia-docker/files/11204636/docker_version.log)] Docker version from `docker version`
 - [[nvidia_packages.log](https://github.com/NVIDIA/nvidia-docker/files/11204649/nvidia_packages.log)] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [[nvidia-container-library.log](https://github.com/NVIDIA/nvidia-docker/files/11204652/nvidia-container-library.log)] NVIDIA container library version from `nvidia-container-cli -V`
 - [`n/a`] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [`point 2.`] Docker command, image and tag used

**Comment by elezar** [comment]
@Overcraft90 this would be an issue to raise with the maintainers of the `deep-variant` image and is not related to the NVIDIA container stack.

Have you asked whether they would be able to bump their base images?

**Comment by Overcraft90** [comment]
@elezar thanks for the suggestion, I haven't but I will definitely move on and do so. In the meantime, Can I keep this issue open till I will have an answer from their side? Thanks!

**Comment by elezar** [comment]
Sure let's keep it open.

**Comment by elezar** [comment]
@Overcraft90 I am closing this issue now.

For more details on the current image support policy see: 
* https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md
* https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md

The lifetime of images is out of scope for this project, so please consider opening an issue there instead.
