### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by westover** [NVIDIA/nvidia-docker#175]
With native docker now available on OS X it would be great to see support developed for nvidia-docker on OSX.

**Comment by 3XX0** [comment]
Docker doesn't run natively on OSX, it relies on a hypervisor. See #101

**Comment by flaviostutz** [comment]
Guys... now Docker is running natively on MacOS. I need this feature too. Thanks!

**Comment by flx42** [comment]
"Natively"? Really? Did you read the comment above?

**Comment by flaviostutz** [comment]
Hehe... missed the point... sorry...

**Comment by Boggartfly** [comment]
PCIE Pass Through to a VM is available via HyperV on Windows 10 Pro and enterprise. The docker VM running on my Windows 10 Pro desktop has my Titan X available to it. This may warrant further investigation!
https://www.reddit.com/r/Windows10/comments/3tu41u/microsoft_added_pcie_passthrough_on_th2_for_pro/

**Comment by rquintino** [comment]
Hi Boggartfly, intrigued by your note, can you confirm/share some additional details? can you get nvidia images running?  ex. nvidia-docker run --rm nvidia/cuda nvidia-smi 
thx!

**Comment by Boggartfly** [comment]
@rquintino I'll try once I find some spare time.
