### ISSUE TITLE
how to use nvidia-docker in container when I want to use GPU

### ISSUE THREAD

**Issue by zhaohb** [NVIDIA/nvidia-docker#176]
Now I want to use GPU in docker container, I know I can install nvidia driver in container, but images has no portability， so I wat to use nvidia-docker.
I install docker and nvidia-docker and nvidia driver in host, and I can find a volume nvidia_driver_367.35, in this volume I can find some *so for GPU.
I know if I use nvidia-docker to run image, the volume nvidia_driver_367.35 will auto map into container , but when I use nvidia-docker to run image I can not use GPU in container 。
who can tell me how to use nvidia-docker? thank you very much

**Comment by flx42** [comment]
What did you try? What was the output?
Is `nvidia-smi` working on the host?

**Comment by zhaohb** [comment]
@flx42 
I want the GPU can be uses by the X system in docker container.  nvidia-smi can be worked in host.

**Comment by zhaohb** [comment]
I think not all of the library mapped by nvidia-docker, example  /usr/lib/xorg/modules/drivers/nvidia_drv.so

**Comment by flx42** [comment]
See this [issue](https://github.com/NVIDIA/nvidia-docker/issues/136)
