### ISSUE TITLE
Support Debian 12

### ISSUE THREAD

**Issue by MoetaYuko** [NVIDIA/nvidia-docker#1761]
Debian 12 is now the latest stable version, please package for it.

**Comment by lucidnx** [comment]
I am waiting for this too...

**Comment by Zyn3** [comment]
Same here.

**Comment by Bigyellow722** [comment]
Is there a plan for support Debian 12?

**Comment by Bigyellow722** [comment]
`curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg       && curl -s -L https://nvidia.github.io/libnvidia-container/debian11/libnvidia-container.list |             sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' |             sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list`
using debian11 instead of $distribution can work

**Comment by Zyn3** [comment]
> `curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/debian11/libnvidia-container.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list` using debian11 instead of $distribution can work

Thats what i ended up doing, works fine. ✌️

**Comment by elezar** [comment]
We are in the process of updating our repos to better support multiple distributions. Note that there are no `debian11`-specific packages as the `debian10` packages are forward-compatible.

Please use the `debian11` (or even the `debian10`) packages for the time being.

**Comment by marxin** [comment]
> We are in the process of updating our repos to better support multiple distributions.

Great news! Do you have any time estimation for it?

**Comment by elezar** [comment]
@marxin the changes should be in our `stable` repos by mid-September. The new repo structure should be testable in the experimental repos already, meaning that running:

```
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/experimental/deb/nvidia-container-toolkit.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```

Should configure the required repositories for all supported systems that use `.deb` packages.

Note that the NVIDIA Container Toolkit package for the `1.14.0-rc.2` release should already be available there.

**Comment by marxin** [comment]
Oh, maybe I'm interested in something a bit different. I would like to get an official CUDA stack on Debian 12, which means I would need a collection of packages here:
https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/

Is it something that's on plan?

**Comment by elezar** [comment]
@marxin we have started publishing some of our package to the CUDA downloads repositories, and I will confirm that `debian12` is included in this.

**Comment by marxin** [comment]
Great! But it's not public yet, am I correct? Or can I use it even now?

**Comment by elezar** [comment]
sorry, to clarify, I cannot speak to the timeline of a debian12 repository at https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/

What I can say is that once that is available, the NVIDIA Container Toolkit packages can be published there. We already publish our packages to the ubuntu-specific repos and will be able to publish to debian-specific repos with the upcoming NVIDIA Container Toolkit 1.14.0 release.

**Comment by lucidnx** [comment]
Any updates?

**Comment by elezar** [comment]
We now have a generic `deb` package repository as described by our instructions here: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt

**Comment by marxin** [comment]
The distribution is officially supported since CUDA 12.3:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#id12

, however, it has some issues (#1791).
