### ISSUE TITLE
Unable to get container to use nvidia graphics resources. System : Ubuntu22.04

### ISSUE THREAD

**Issue by MoAccelerator** [NVIDIA/nvidia-docker#1767]
I installed nvidia-driver-535, nvidia-docker2, nvidia-container-runtime, cuda12.2, but my docker container still can't invoke GPU resources. And I used the Debian11 system before and installed nvidia-driver-470, nvidia-docker2, nvidia-container-runtime. The docker container cannot invoke GPU resources either.
My graphics card uses HDMI interface and DP interface.

I don't know exactly where the problem is, I hope someone can help me find the cause of the problem, Thanks.
![image](https://github.com/NVIDIA/nvidia-docker/assets/45995147/a093881f-84ff-476c-9907-a9782b8faa98)
![image](https://github.com/NVIDIA/nvidia-docker/assets/45995147/f79d2f26-292d-4676-8b08-9b86a0c1a8e8)

 - [
[nvidia-container-cli.txt](https://github.com/NVIDIA/nvidia-docker/files/12072259/nvidia-container-cli.txt)
] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [Linux accmo-nas 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux] Kernel version from `uname -a`
 - [
[dmesg.txt](https://github.com/NVIDIA/nvidia-docker/files/12072245/dmesg.txt)
] Any relevant kernel output lines from `dmesg`
 - [
[nvidia-smi.txt](https://github.com/NVIDIA/nvidia-docker/files/12072268/nvidia-smi.txt)
] Driver information from `nvidia-smi -a`
 - [
[docker-version.txt](https://github.com/NVIDIA/nvidia-docker/files/12072276/docker-version.txt)
] Docker version from `docker version`
 - [
[dpkg-nvidia.txt](https://github.com/NVIDIA/nvidia-docker/files/12072287/dpkg-nvidia.txt)
] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [
[nvidia-container-cli-V.txt](https://github.com/NVIDIA/nvidia-docker/files/12072303/nvidia-container-cli-V.txt)
] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by MoAccelerator** [comment]
I have reinstalled the system more than ten times. I make sure my system environment is very clean.

**Comment by elezar** [comment]
You nvidia-smi command run in the container seems to indicate that you are able to access the GPU in the container.

If you're still having problems, please open a new issue against https://github.com/NVIDIA/nvidia-container-toolkit
