### ISSUE TITLE
Manifest unknown error

### ISSUE THREAD

**Issue by philmatp** [NVIDIA/nvidia-docker#1768]
Please help me to resolve the following error
STEP 1/26: FROM docker.io/nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
Trying to pull docker.io/nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04...
Error: error creating build container: initializing source docker://nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04: reading manifest 10.2-cudnn7-devel-ubuntu18.04 in docker.io/nvidia/cuda: manifest unknown: manifest unknown

**Comment by jiafanou** [comment]
Echo this. It seems all CUDA 10 images were removed. We have some old models requires TF 1.x and CUDA 10.

**Comment by dmatos2012** [comment]
Do you know of any mirrors, I am on same both @jiafanou

**Comment by jiafanou** [comment]
I found some internal dockers. I didn't look for public ones.

**Comment by elezar** [comment]
Please see: 
* https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md
* https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md

The lifetime of images is out of scope for this project, so please consider opening an issue there instead.
