### ISSUE TITLE
How to change the jupyter lab host in Pytorch:23.07 image

### ISSUE THREAD

**Issue by ElinLiu0** [NVIDIA/nvidia-docker#1774]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
The jupyter lab url shown from docker logs looks like `http://hostname:8888`,but what i expecting is look like normal one which we launch from local like `http://localhost:8888`.Here is the problem.
### 2. Steps to reproduce the issue
- Pull the Pytorch:23.07 image from NGC
- run bellow docker command to launch jupyter lab:
```bash
docker run --rm -it --gpus 1 pytorch jupyter lab --allow-root --ip=* --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.allow_origin='*' --notebook-dir=/workspace
```
- check out the output log
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [x] Docker command, image and tag used

**Comment by macwilam** [comment]
I have the same problem. I think I tried every possible combination of parameters for both docker run and jupyter notebook.
My solution was to add 
127.0.0.1       hostname
to my hosts and add:
NotebookApp.allow_remote_access=True
to my notebook config on start. This is however just a patch and not a solution and I have no idea why it is hostname instead of localhost.

**Comment by ElinLiu0** [comment]
> I have the same problem. I think I tried every possible combination of parameters for both docker run and jupyter notebook.
> My solution was to add 
> 127.0.0.1       hostname
> to my hosts and add:
> NotebookApp.allow_remote_access=True
> to my notebook config on start. This is however just a patch and not a solution and I have no idea why it is hostname instead of localhost.
> 

That's definitely work😂
