### ISSUE TITLE
How do I uninstall Old Nvidia-docker V1.00-rc to install New V1.0.0-rc.3-1.

### ISSUE THREAD

**Issue by yoshihingis** [NVIDIA/nvidia-docker#178]
I installed Nvidia-docker V1.0.0-rc as blow.
But I found New Nvidia-DockerV1.0.0-rc.3-1.
How do I uninstall Old Nvidia-docker V1.00-rc to install New V1.0.0-rc.3-1.
I'd really approcoate it if anyone answer as soon as possible!  

wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc/nvidia-docker_1.0.0.rc_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

Regards,

**Comment by flx42** [comment]
When you have this older version, the safest way is to purge the package and manually remove the folder (because we had a bug with permissions in earlier versions):
```
apt-get purge nvidia-docker
rm -rf /var/lib/nvidia-docker
```
