### ISSUE TITLE
can not pull cuda:11.8.0-cudnn8-devel-centos7

### ISSUE THREAD

**Issue by starstream** [NVIDIA/nvidia-docker#1789]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
can not pull cuda:11.8.0-cudnn8-devel-centos7
### 2. Steps to reproduce the issue
docker pull docker.io/nvidia/cuda:11.8.0-cudnn8-devel-centos7
Error response from daemon: manifest for nvidia/cuda:11.8.0-cudnn8-devel-centos7 not found: manifest unknown: manifest unknown

**Comment by elezar** [comment]
Please see: 
* https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md
* https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md

The lifetime of images is out of scope for this project, so please consider opening an issue there instead.
