### ISSUE TITLE
where are the old images?

### ISSUE THREAD

**Issue by idhamari** [NVIDIA/nvidia-docker#1790]
ERROR: failed to solve: nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04: docker.io/nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04: not found

**Comment by GabrielGosden** [comment]
I'm experiencing the same issue. It seems like the docker base image has been removed from the docker hub. If someone could confirm this or maybe provide an alternative way to download older images?

**Comment by idhamari** [comment]
I was able to build an image from scratch to run with jupyter notebook, here is the file 

https://github.com/ia-ML/nvidia-dockers/blob/main/cuda10.0-cudnn7.4-TF1.14/Dockerfile

**Comment by elezar** [comment]
Please see: 
* https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md
* https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md

The lifetime of images is out of scope for this project, so please consider opening an issue there instead.
