### ISSUE TITLE
Splitting up /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu2204_x86%5f64_InRelease into data and signature failed Error

### ISSUE THREAD

**Issue by Samanthavsilva** [NVIDIA/nvidia-docker#1800]
I have this def file where I am trying to create a container with ubuntu however I get this error when it is doing the    apt-get update command, it was working fine for me like 2 months ago so not sure why it all of sudden gives me this error

def file:  Bootstrap: docker
From: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

%files
   dsenvi.yaml
   comm.py

%post
   apt-get update -y \
   && apt-get install -y build-essential \
   && apt-get install -y wget \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/*
   apt-get update -y
   export DEBIAN_FRONTEND=noninteractive
   apt-get install software-properties-common -y
   add-apt-repository ppa:deadsnakes/ppa -y

Error: INFO:    Running post scriptlet
+ apt-get update -y
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease                  
  Splitting up /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu2204_x86%5f64_InRelease into data and signature failed
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]              
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]              
Err:2 http://archive.ubuntu.com/ubuntu jammy InRelease                                 
  Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy_InRelease into data and signature failed
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Err:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease    
  Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-updates_InRelease into data and signature failed
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Err:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease    
  Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-backports_InRelease into data and signature failed
Err:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
  Splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_jammy-security_InRelease into data and signature failed
Reading package lists... Done
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease: Splitting up /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu2204_x86%5f64_InRelease into data and signature failed
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy InRelease: Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy_InRelease into data and signature failed
E: The repository 'http://archive.ubuntu.com/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-updates InRelease: Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-updates_InRelease into data and signature failed
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-backports InRelease: Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-backports_InRelease into data and signature failed
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.ubuntu.com/ubuntu jammy-security InRelease: Splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_jammy-security_InRelease into data and signature failed
E: The repository 'http://security.ubuntu.com/ubuntu jammy-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
+ apt-get update -y
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
  Splitting up /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu2204_x86%5f64_InRelease into data and signature failed
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Err:2 http://security.ubuntu.com/ubuntu jammy-security InRelease   
  Splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_jammy-security_InRelease into data and signature failed
Err:3 http://archive.ubuntu.com/ubuntu jammy InRelease
  Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy_InRelease into data and signature failed
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Err:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-updates_InRelease into data and signature failed
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Err:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-backports_InRelease into data and signature failed
Reading package lists... Done
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease: Splitting up /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu2204_x86%5f64_InRelease into data and signature failed
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.ubuntu.com/ubuntu jammy-security InRelease: Splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_jammy-security_InRelease into data and signature failed
E: The repository 'http://security.ubuntu.com/ubuntu jammy-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy InRelease: Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy_InRelease into data and signature failed
E: The repository 'http://archive.ubuntu.com/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-updates InRelease: Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-updates_InRelease into data and signature failed
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu jammy-backports InRelease: Splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_jammy-backports_InRelease into data and signature failed
E: The repository 'http://archive.ubuntu.com/ubuntu jammy-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
FATAL:   While performing build: while running engine: exit status 100

**Comment by elezar** [comment]
Does this issue still present? Note that it seems to be related to the CUDA Downloads repositories which are out of the control of the NVIDIA Container Toolkit.

If the problem persists, please create an issue on the CUDA Developer forums: https://forums.developer.nvidia.com/
