### ISSUE TITLE
Docker Error with DIGITS

### ISSUE THREAD

**Issue by spalkovits** [NVIDIA/nvidia-docker#181]
Hello,

I am unfortunately not sure if I should also post this in the DIGITS issues. It feels more related to docker things.

I finally want to use DIGITS as docker container within a compose file. So I tested the DIGITS image first with a batch file this way (for other containers I tested it works fine):

`#!/bin/bash
docker run --name nvidia-digits \
	--volume-driver=nvidia-docker \
	--volume=nvidia_driver_352.93:/usr/local/nvidia:ro \
	--device=/dev/nvidiactl \
	--device=/dev/nvidia-uvm \
	--device=/dev/nvidia0 \
	-p 34448:34448 \
	-d nvidia/digits`

It gives me the following error:

`docker: Error response from daemon: create c2bdb24f811bec544574a96a5091d44a591efdba4430c1636843eb255d23ee05: bad volume format: c2bdb24f811bec544574a96a5091d44a591efdba4430c1636843eb255d23ee05.`

Although its working with other containers and it is in principle the procedure stated here https://github.com/NVIDIA/nvidia-docker/wiki/Internals.

When I use nvidia-docker instead like this it works fine:

`#!/bin/bash
nvidia-docker run --name nvidia-digits \
	-p 34448:34448 \
	-d nvidia/digits`

But when I use my first procedure for another CUDA container e.g. like this:

`#!/bin/bash
docker run  --rm --name nvidia-smi \
	--volume-driver=nvidia-docker \
	--volume=nvidia_driver_352.93:/usr/local/nvidia:ro \
	--device=/dev/nvidiactl \
	--device=/dev/nvidia-uvm \
	--device=/dev/nvidia0 \
	nvidia/cuda nvidia-sim`

it works like its supposed to be. Has anyone any suggestions how to get the first script running (or do the same in a docker-compose file)?

**Comment by 3XX0** [comment]
Yes this is a limitation from Docker. The DIGITS image will create volumes automatically if you don't specify the `-v` option (see [here](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/digits/4.0/Dockerfile#L17-L18)). This in turns triggers our volume-driver plugin which doesn't support it.

With that in mind, you have two solutions:
1. Bind mount host directories with `-v` for input/output (see [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS))
2. Create the NVIDIA volume manually once with `docker volume create -d nvidia-docker --name nvidia_driver_352.93` after which, you will be able to run DIGITS with your command by removing `--volume-driver=nvidia-docker` from it

See also #112

**Comment by spalkovits** [comment]
Hello,
both solutions work like you suggested. Thank you for the help.
Regards...
