### ISSUE TITLE
Driver version mismatch between nvidia-docker and upgraded driver

### ISSUE THREAD

**Issue by nyasara** [NVIDIA/nvidia-docker#182]
OS: Ubuntu 16.04

While following other installation instructions, I accidentally upgraded my nvidia driver version to 367.44, and nvidia-docker apparently only supports version 367.35.  I've tried purging, reinstalling, etc., nothing works to get nvidia-docker or nvidia-smi running again.  This is the error in journalctl when I try to install the latest nvidia-docker package.

>nvidia-docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 26 14:08:07 nyasara-linux kernel: NVRM: API mismatch: the client has the version 367.44, but
                                      NVRM: this kernel module has the version 367.35.  Please
                                      NVRM: make sure that this kernel module and all NVIDIA driver
                                      NVRM: components have the same version.

How can I get nvidia-docker up to 367.44, or should I be downgrading my nvidia drivers back to 367.35?

**Comment by 3XX0** [comment]
Looks like your driver upgrade went wrong. How did you do the upgrade?
Your kernel module is still 367.35, you should load the 367.44 instead.
Something like:
```
rmmod nvidia nvidia_uvm nvidia_drm nvidia_modeset
nvidia-modprobe
```

**Comment by nyasara** [comment]
My apologies, it appears after I upgraded I needed to reboot.  Once I rebooted everything is working fine now.
