### ISSUE TITLE
nvidia driver update may cause issues

### ISSUE THREAD

**Issue by samitbasu** [NVIDIA/nvidia-docker#183]
I believe that an update of the nvidia drivers caused issues with the nvidia-docker plugin.  After the drivers updated, any attempt to launch an nvidia-docker command lead to the following:

[sbasu@iceman docker]$ nvidia-docker-plugin 
nvidia-docker-plugin | 2016/08/26 10:54:38 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/08/26 10:54:38 Loading NVIDIA management library
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x9386a0, 0x2a)
    /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x710b3d, 0xc82006dc20, 0x0)
    /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc82006dc00 sp=0xc82006dbd0
github.com/NVIDIA/nvidia-docker/tools/src/nvml._Cfunc_nvmlInit_dl(0x0)
    ??:0 +0x3d fp=0xc82006dc20 sp=0xc82006dc00
github.com/NVIDIA/nvidia-docker/tools/src/nvml.init_(0x0, 0x0)
    /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvml/bindings.go:48 +0x28 fp=0xc82006dc70 sp=0xc82006dc20
github.com/NVIDIA/nvidia-docker/tools/src/nvml.Init(0x0, 0x0)
    /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvml/nvml.go:134 +0x24 fp=0xc82006dc88 sp=0xc82006dc70
github.com/NVIDIA/nvidia-docker/tools/src/nvidia.Init(0x0, 0x0)
    /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia/nvidia.go:31 +0x118 fp=0xc82006dcf0 sp=0xc82006dc88
main.main()
    /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker-plugin/main.go:70 +0x368 fp=0xc82006df50 sp=0xc82006dcf0
runtime.main()
    /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82006dfa0 sp=0xc82006df50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82006dfa8 sp=0xc82006dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
[sbasu@iceman docker]$ 

We noticed that the version number of the CUDA driver in /var/lib/nvidia-docker did not match the updated driver version.  Uninstalling the RPM and reinstalling did not work either.  Only uninstalling the RPM, manually deleting the /var/lib/nvidia-docker directory and then reinstalling the RPM seemed to work.

I guess to reproduce the problem one should try updating the nvidia drivers on a functioning installation and then seeing if the plugin still functions.

**Comment by flx42** [comment]
I've done a lot of live switch of the drivers (without reboot) and I had no issue. What you have here is apparently a segfault when calling nvmlInit:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]
[...]

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x710b3d, 0xc82006dc20, 0x0)
```
This sounds pretty bad, can you confirm your driver installation works outside of nvidia-docker? For instance, is `nvidia-smi` working fine with the right driver version? Are CUDA samples working?
Also, what is the output of `ldconfig -p | grep nvidia`?

**Comment by 3XX0** [comment]
Ping?
