### ISSUE TITLE
Ubuntu 14.04: Error while executing nvidia-docker run

### ISSUE THREAD

**Issue by rladeira** [NVIDIA/nvidia-docker#186]
I'm having some problems, while trying to execute an image with nvidia-docker in ubuntu:14.04.

Here's the error:

```
$ nvidia-docker run --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: create nvidia_driver_367.44: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.

```

Here's the log:

```
$ sudo cat /var/log/upstart/nvidia-docker.log
/usr/bin/nvidia-docker-plugin | 2016/09/01 11:38:15 Received create request for volume 'nvidia_driver_367.44'
/usr/bin/nvidia-docker-plugin | 2016/09/01 11:38:15 Error: link /usr/lib32/libnvidia-ptxjitcompiler.so.367.44 /var/lib/nvidia-docker/volumes/nvidia_driver/367.44/lib/libnvidia-ptxjitcompiler.so.367.44: file exists

```

It seems that some link related issue is happening.

Additional information:
- nvidia-smi works fine on the host;
- This problem emerged after nvidia driver reinstallation. I even tried to reinstall nvidia-docker itself, but the issue is still present.

**Comment by 3XX0** [comment]
The installer probably left stale files behind.
Check `ldconfig -p | grep libnvidia-ptxjitcompiler.so` see if you have duplicates

**Comment by rladeira** [comment]
Yes, there was some duplicates for` libnvidia-ptxjitcompiler.so.367.44`.

```
$ ldconfig -p | grep libnvidia-ptxjitcompiler.so
	libnvidia-ptxjitcompiler.so.367.44 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.367.44
	libnvidia-ptxjitcompiler.so.367.44 (libc6,x86-64) => /usr/lib/nvidia-367/libnvidia-ptxjitcompiler.so.367.44
	libnvidia-ptxjitcompiler.so.367.44 (libc6) => /usr/lib32/nvidia-367/libnvidia-ptxjitcompiler.so.367.44
```

Now I having problems related to `libvdpau_nvidia.so.367.44`, and ` ldconfig -p | grep libvdpau_nvidia.so.367.44` prints nothing. Any hints?

**Comment by 3XX0** [comment]
How did you install your drivers? It looks like you mixed several installation (cuda/runfile/ubuntu)

Make sure you only have one driver installed.
If you had a previous installation with a runfile, do `sudo nvidia-uninstall`
Otherwise you can list all your driver packages with `dpkg -l | grep -E '(nvidia|libcuda)'`

Once you resolved that remove the nvidia-docker volumes (if any): `docker volume rm $(docker volume ls -q | grep nvidia)`

**Comment by rladeira** [comment]
Thanks for your help! I had some issues after an automatic update for nvidia driver, and trying to solve the problem, I made a mess with these installations. In the end, I reinstalled the OS in the machine to better organize these settings. Anyway, your comments were really informative. Thanks again!
