### ISSUE TITLE
"unsupported Docker version" with docker 1.12

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#187]
When I install docker-engine >= 1.12, and then nvidia-docker, I get the following error message:

```
$ nvidia-docker ps
nvidia-docker | 2016/09/01 11:27:59 Error: unsupported Docker version
```

My steps to reproduce are:
```
$ sudo service nvidia-docker stop
$ sudo apt-get remove nvidia-docker
$ sudo service docker stop
$ sudo apt-get remove docker-engine
$ sudo apt-get install docker-engine=1.12.0-0~trusty  # or 1.12.1
# install nvidia-docker...
$ wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1
.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb
$ sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
$ docker ps  # succeeds
$ nvidia-docker ps  # fails
```

Everything is fine if I install `docker-engine=1.11.2-0~trusty`, and then nvidia-docker.

**Comment by grisaitis** [comment]
On another machine, I can't reproduce the issue. And that machine's OS state is newer, and I don't think I've installed and removed older versiond of docker or nvidia-docker on that machine. 

Maybe there's a stale config file somewhere that isn't getting cleaned..? 

One potential issue is that my `sudo` doesn't have write permissions to my home folder. Is there any content there that might need to be cleaned up?

**Comment by 3XX0** [comment]
You probably have an old version of `nvidia-docker` on your machine.
Purge nvidia-docker `sudo apt-get purge nvidia-docker` and check that it is correctly removed. Then check that you don't have another binary lying around `which nvidia-docker` or `/usr/local/bin`

**Comment by grisaitis** [comment]
Thanks @3XX0 :) There was an old `nvidia-docker` hanging out at `/usr/local/bin/nvidia-docker`, even after purging the package. Removing it solved the issue.
