### ISSUE TITLE
EC2 deployment instructions not working

### ISSUE THREAD

**Issue by pasky** [NVIDIA/nvidia-docker#189]
Hi! I tried to follow https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2 but after

```
sudo apt-get install --no-install-recommends -y gcc make libc-dev
wget -P /tmp http://us.download.nvidia.com/XFree86/Linux-x86_64/361.42/NVIDIA-Linux-x86_64-361.42.run
sudo sh /tmp/NVIDIA-Linux-x86_64-361.42.run --silent
```

I'm getting

```
ERROR: Unable to load the kernel module 'nvidia.ko'.  This happens most frequently when this kernel module was built against the wrong or improperly configured kernel sources, with a version of gcc that differs 
from the one used to build the target kernel, or if a driver such as rivafb, nvidiafb, or nouveau is present and prevents the NVIDIA kernel module from obtaining ownership of the NVIDIA graphics device(s), or no
 NVIDIA GPU installed in this system is supported by this NVIDIA Linux graphics driver release.
```

The log shows:

```
-> Kernel messages:
[ 1291.199013] nvidia: Unknown symbol drm_gem_prime_handle_to_fd (err 0)
[ 1291.199028] nvidia: Unknown symbol drm_gem_private_object_init (err 0)
[ 1291.199042] nvidia: Unknown symbol drm_gem_mmap (err 0)
[ 1291.199048] nvidia: Unknown symbol drm_ioctl (err 0)
[ 1291.199057] nvidia: Unknown symbol drm_gem_object_free (err 0)
[ 1291.199071] nvidia: Unknown symbol drm_read (err 0)
[ 1291.199089] nvidia: Unknown symbol drm_gem_handle_create (err 0)
[ 1291.199096] nvidia: Unknown symbol drm_prime_pages_to_sg (err 0)
[ 1291.199138] nvidia: Unknown symbol drm_pci_exit (err 0)
[ 1291.199153] nvidia: Unknown symbol drm_release (err 0)
[ 1291.199157] nvidia: Unknown symbol drm_gem_prime_export (err 0)
[ 1608.227363] nvidia: Unknown symbol drm_open (err 0)
[ 1608.227379] nvidia: Unknown symbol drm_poll (err 0)
[ 1608.227392] nvidia: Unknown symbol drm_pci_init (err 0)
[ 1608.227446] nvidia: Unknown symbol drm_gem_prime_handle_to_fd (err 0)
[ 1608.227460] nvidia: Unknown symbol drm_gem_private_object_init (err 0)
[ 1608.227474] nvidia: Unknown symbol drm_gem_mmap (err 0)
[ 1608.227480] nvidia: Unknown symbol drm_ioctl (err 0)
[ 1608.227489] nvidia: Unknown symbol drm_gem_object_free (err 0)
[ 1608.227504] nvidia: Unknown symbol drm_read (err 0)
[ 1608.227521] nvidia: Unknown symbol drm_gem_handle_create (err 0)
[ 1608.227529] nvidia: Unknown symbol drm_prime_pages_to_sg (err 0)
[ 1608.227571] nvidia: Unknown symbol drm_pci_exit (err 0)
[ 1608.227587] nvidia: Unknown symbol drm_release (err 0)
[ 1608.227591] nvidia: Unknown symbol drm_gem_prime_export (err 0)
```

Maybe when the wiki says "Once the provisioning is completed, we install the NVIDIA drivers and NVIDIA Docker on the newly created instance (Ubuntu by default)." it doesn't actually mean the by default offered 14.04 AMI? It'd be great to be a lot more specific regarding that in the instructions...

No prior experience with either AWS or installing NVidia drivers on Ubuntu, sorry.

Thanks!

**Comment by pasky** [comment]
Sorry, for certain reasons I tried to be smart and avoid using docker-machine, which turns out to be essential.

**Comment by lipsumar** [comment]
I'm having the exact same issue, but I'm using docker-machine.

Everything goes smoothly as described. The only exception being an error when creating the instance:
```Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded```

However I can ssh fine into it so i figure this isn't a big deal.

After googling I found I might want to disable `nouveau` (http://tleyden.github.io/blog/2014/10/25/cuda-6-dot-5-on-aws-gpu-instance-running-ubuntu-14-dot-04/) which I did, but still no cigar.

Here is my `/var/log/nvidia-installer.log`: <https://gist.github.com/lipsumar/67cf3aa10a3744c608e5cbfb19671dab>

Any idea ?

**Comment by flx42** [comment]
@lipsumar I need to update those instructions, could you try the [Azure instructions](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Azure) instead?
```
# Install official NVIDIA driver package
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
sudo apt-get update && sudo apt-get install -y --no-install-recommends cuda-drivers

# Unload nouveau
sudo rmmod nouveau
```
Note that these instructions are for ubuntu 16.04, just modify the URL if you use another distro.

**Comment by lipsumar** [comment]
I ended up using a 16.04 ami (`--amazonec2-ami ami-d8bdebb8`) and it went just fine, thank you!
