### ISSUE TITLE
Tagged image for DIGITS

### ISSUE THREAD

**Issue by ruffsl** [NVIDIA/nvidia-docker#19]
As mentioned by @flx42 in #7 , an image for [DIGITS](https://developer.nvidia.com/digits) should be in the works at Nvidia. This issues merely serves to track it's progress or propose recommendations. 

I just got around to watching some of the [footage from GTC 2015](https://youtu.be/DT72N1cmNno?t=2m33s) expo floor. I'm looking forward to trying out framework once the image comes around.

**Comment by 3XX0** [comment]
Yeah what about it @lukeyeager ? :wink:

**Comment by lukeyeager** [comment]
Should be trivial once we post deb packages. Install instructions here:

https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/UbuntuInstall.md

**Comment by ruffsl** [comment]
Just tested out the new DIGITS image on my local system, looks to be working fine!
I think cudnn4 has boosted my GPU usage (to 99%) since I last tested with the MNIST sample dataset.
Great work.
