### ISSUE TITLE
Nvidia devices not available / 404 page not found errors

### ISSUE THREAD

**Issue by siebz0r** [NVIDIA/nvidia-docker#193]
Today I noticed that nvidia-docker doesn't make the Nvidia devices available in the guest. I found this in the `docker.log` after starting a container with `nvidia-docker run`:

```
level=error msg="Handler for GET /v1.24/containers/its-aligner:latest/json returned error: No such container: its-aligner:latest" 
```

I was able to work around the issue by using the command line args from the api (`docker run $(curl http://localhost:3476/v1.0/docker/cli)`). I then saw this in the `docker.log`

```
level=warning msg="Volume driver nvidia-docker returned an error while trying to query its capabilities, using default capabilties: VolumeDriver.Capabilities: 404 page not found\n" 
```

This reminds me of docker/docker#26099 where all pages return a 404, maybe it's a similar issue?

Docker version: 1.12.1, build 23cf638

**Comment by 3XX0** [comment]
What do you mean by

> doesn't make the Nvidia devices available in the guest

Regarding the second error, volume drivers (like `nvidia-docker-plugin`) are not required to implement the `Capabilities` endpoint, hence the 404.

**Comment by siebz0r** [comment]
The devices `/dev/nvidia0`, `/dev/nvidiactl` etc. are not accessible from the guest. The guest simply misses these device files in the `/dev` directory.
They are readable and writeable on the host.

**Comment by 3XX0** [comment]
If by guest you mean container, then they should be there.
Try running `nvidia-docker run --rm nvidia/cuda nvidia-smi` if it works then the devices are there

**Comment by siebz0r** [comment]
Yeah, I mean container  :sweat_smile:

Seems there is also no bug, I was simply missing `LABEL com.nvidia.volumes.needed="nvidia_driver"` in my Dockerfile.
Sorry to have bothered you. Thanks for the support.
