### ISSUE TITLE
Can't start docker daemon after uninstalling nvidia-docker

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#196]
I'm finding that, after uninstalling nvidia-docker, I'm unable to start the docker daemon. The daemon tries to find the nvidia-docker plugin, which doesn't exist because it's been uninstalled (purged with apt-get)

```
$ sudo /usr/bin/dockerd                                                        
INFO[0000] libcontainerd: new containerd process, pid: 20530 
INFO[0001] [graphdriver] using prior storage driver "aufs" 
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
WARN[0001] Your kernel does not support swap memory limit. 
WARN[0001] mountpoint for pids not found                
INFO[0001] Loading containers: start.                   
.........................INFO[0001] Firewalld running: false                     
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
WARN[0001] Unable to locate plugin: nvidia-docker, retrying in 1s 
WARN[0002] Unable to locate plugin: nvidia-docker, retrying in 2s 
```

And the daemon never starts. 

Also:

```
$ which nvidia-docker  # returns nothing                                                         
$ which nvidia-docker-plugin  # returns nothing
```

I can fix this if I remove `/var/lib/docker/containers/`. Is there any other way? I don't want to delete that directory, because it has logs for past containers.

**Comment by grisaitis** [comment]
Addendum:
* Purging and reinstalling docker doesn't fix the issue. 
* The directory `/etc/docker/plugins` is empty, and `/usr/lib/docker/plugins` doesn't exist

I have two hypotheses about why this might be happening:
1. nvidia-docker maybe edited a settings file somewhere, telling docker to load it whenever the daemon starts
2. when the daemon starts, it checks for plugins used by pre-existing containers (in `/var/lib/docker`), and tries to load them

**Comment by 3XX0** [comment]
I stumbled upon this issue 10 min ago :)
I'm really not sure what changed with Docker, all I can tell you right now is that the volumes are cached somewhere in `/var/lib/docker` because removing it fixed the issue.

I remember they used `/var/lib/docker/volumes/metadata.db` at some point but it looks like this is not the only file caching the volumes.

**Comment by grisaitis** [comment]
Exactly. I tried removing that as well.

Maybe this is why: https://github.com/docker/docker/issues/23452

**Comment by teon** [comment]
+1 same issue, but last message is:
```Sep 28 21:16:28 deepl1 docker[27774]: time="2016-09-28T21:16:28.724122119+02:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: cannot create network a676fb50f2bce````

**Comment by 3XX0** [comment]
Closing, there is no more plugin with 2.0/master.
