### ISSUE TITLE
Support for Windows 10 (Hyper-V)

### ISSUE THREAD

**Issue by thesuperzapper** [NVIDIA/nvidia-docker#197]
Given that Docker has GA'd native support for Windows 10 with Hyper-V, is it now possible to support Windows?

**Comment by 3XX0** [comment]
No not possible, we would need GPU passthrough (i.e DDA) which is only available in Windows server

**Comment by scpeters** [comment]
On a related note, is it possible to support any versions of macOS (through xhyve virtual machine) if the system has an nvidia GPU?

**Comment by 3XX0** [comment]
No, see #175 #162 #101

**Comment by danielmarg** [comment]
Now with the newest Windows 10 version supporting DDA, has the situation changed?

**Comment by pawarren** [comment]
If we are using Windows Server 2016, how do we allow nvidia-docker to access the GPU?

**Comment by danielmarg** [comment]
Pumping this request. Any info appreciated. @3XX0

**Comment by j2l** [comment]
I have the same question.

**Comment by dougajmcdonald** [comment]
I wondered if running `nvidia-docker` through WSL on Windows 10 / Server 2016 (Something which supports DDA) would work?

**Comment by ZackWhiteIT** [comment]
Bump

**Comment by PrinceP** [comment]
They know the issue.
[https://youtu.be/lwhMThePdIo?t=3054](https://youtu.be/lwhMThePdIo?t=3054)

**Comment by Iridesscent** [comment]
Bump...

**Comment by glencoe2004** [comment]
lol, love how they completely ignore this once something that solves the issue comes out
