### ISSUE TITLE
Issue starting nvidia-docker.service

### ISSUE THREAD

**Issue by stepseazy** [NVIDIA/nvidia-docker#199]
Hello sir,

I am having an issue resulting in the following error. Not sure where to start. Thanks...

$ sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
Selecting previously unselected package nvidia-docker.
(Reading database ... 236074 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.0.rc.3-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0~rc.3-1) ...
Setting up nvidia-docker (1.0.0~rc.3-1) ...
Configuring user
Setting up permissions
Job for nvidia-docker.service failed because the control process exited with error code. See "systemctl status nvidia-docker.service" and "journalctl -xe" for details.
nvidia-docker.service couldn't start.
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot

Here are my drivers:
![softwareeditor](https://cloud.githubusercontent.com/assets/16912092/18474327/87605342-798f-11e6-9c9c-e25cf114e531.jpg)

**Comment by flx42** [comment]
Does `nvidia-smi` and CUDA work on the host?
Also, what's the output of `journalctl -n -u nvidia-docker`?

**Comment by stepseazy** [comment]
nvidia-smi does not seem to work:
```
~$ nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2016/09/14 13:10:46 Error: Could not load UVM kernel module
```
Not sure how to check if CUDA works...

```
$ journalctl -n -u nvidia-docker
-- Logs begin at Wed 2016-09-14 11:32:12 EDT, end at Wed 2016-09-14 13:12:46 EDT
Sep 14 13:10:24 rik-MS-7971 systemd[1]: Stopped NVIDIA Docker plugin.
Sep 14 13:10:24 rik-MS-7971 systemd[1]: Starting NVIDIA Docker plugin...
Sep 14 13:10:24 rik-MS-7971 systemd[1]: nvidia-docker.service: Main process exit
Sep 14 13:10:24 rik-MS-7971 systemd[1]: Failed to start NVIDIA Docker plugin.
Sep 14 13:10:24 rik-MS-7971 systemd[1]: nvidia-docker.service: Unit entered fail
Sep 14 13:10:24 rik-MS-7971 systemd[1]: nvidia-docker.service: Failed with resul
Sep 14 13:10:25 rik-MS-7971 systemd[1]: nvidia-docker.service: Service hold-off 
Sep 14 13:10:25 rik-MS-7971 systemd[1]: Stopped NVIDIA Docker plugin.
Sep 14 13:10:25 rik-MS-7971 systemd[1]: nvidia-docker.service: Start request rep
Sep 14 13:10:25 rik-MS-7971 systemd[1]: Failed to start NVIDIA Docker plugin.

```

**Comment by 3XX0** [comment]
Check that you have `nvidia-modprobe` on your machine, if not install it

**Comment by stepseazy** [comment]
Thanks, appears to allow me to install, but nvidia-smi still does not work:

```
$ sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
[sudo] password for rik: 
(Reading database ... 249818 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.0.rc.3-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0~rc.3-1) over (1.0.0~rc.3-1) ...
Setting up nvidia-docker (1.0.0~rc.3-1) ...
Setting up permissions
Processing triggers for ureadahead (0.100.0-19) ...
rik@rik-MS-7971:~$ nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2016/09/14 17:52:58 Error: Could not load UVM kernel module

```

**Comment by 3XX0** [comment]
Can you do `sudo nvidia-modprobe -u -c=0` and try again.

**Comment by stepseazy** [comment]
Can't seem to run that:
```
$ sudo nvidia-modprobe -u -c=0 
[sudo] password for rik: 
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.4.0-36-generic

```

**Comment by 3XX0** [comment]
Looks like your driver hasn't been installed properly.
Does `nvidia-smi` work on your machine?

Also, can you give me the output of:
```
dkms status
uname -a
ls -l  /lib/modules/4.4.0-36-generic/updates/dkms/
ls -l  /usr/src/nvidia*
```

**Comment by flx42** [comment]
The question regarding whether `nvidia-smi` is working or not is **on the host**, as also asked [here](https://github.com/NVIDIA/nvidia-docker/issues/199#issuecomment-246760968) (but you answered for inside the container).
`nvidia-smi` or CUDA (try a sample in `/usr/local/cuda/samples`) probably won't work on the **host** with your setup.

**Comment by stepseazy** [comment]
What do you mean by host?

I tried a sample with the following result:

```
rik@rik-MS-7971:~$ cuda-install-samples-8.0.sh  ~ 
Copying samples to /home/rik/NVIDIA_CUDA-8.0_Samples now...
Finished copying samples.
rik@rik-MS-7971:~$ cd ~/NVIDIA_CUDA-8.0_Samples
rik@rik-MS-7971:~/NVIDIA_CUDA-8.0_Samples$ cd 1_Utilities/deviceQuery 
rik@rik-MS-7971:~/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery$ make 
"/usr/local/cuda-8.0"/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_60,code=compute_60 -o deviceQuery.o -c deviceQuery.cpp
"/usr/local/cuda-8.0"/bin/nvcc -ccbin g++   -m64      -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_60,code=compute_60 -o deviceQuery deviceQuery.o 
mkdir -p ../../bin/x86_64/linux/release
cp deviceQuery ../../bin/x86_64/linux/release
rik@rik-MS-7971:~/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery$ chmod +x deviceQuery
rik@rik-MS-7971:~/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
```

**Comment by flx42** [comment]
On the host means outside of a container.

It looks like your driver installation is busted, so that's not a nvidia-docker bug.

**Comment by stepseazy** [comment]
Argg. I've been trying to fix these driver forever. I'll do a reinstall. Does it matter what drive I install? I have a gtx 1080 GPU

**Comment by flx42** [comment]
You need drivers 367, unfortunately if you installed the main metapackage of CUDA 8.0, you will end up with 361 installed :(

Your problem might be that you mixed two drivers installations, one from the CUDA deb packages, and one from a `runfile`. You need to remove the driver packages manually and they use a runfile to install a 367 driver, look at these guidelines: https://github.com/NVIDIA/nvidia-docker/issues/99#issuecomment-221721046

**Comment by flx42** [comment]
@stepseazy: did you fix your problem?

**Comment by stepseazy** [comment]
I couldn't figure out how to fix my driver so I re-installed ubuntu and haven't tried since then because I have to re-install all the dependencies. I'll try again tomorrow and let you know. I think you are right tht it was the installing of the cuda deb packages that screwed it up because my dual monitor stopped working around then also...

**Comment by stepseazy** [comment]
Works! Thanks for the help guys!

**Comment by stepseazy** [comment]
```
rik@rik-MS-7971:~$ nvidia-docker run --rm nvidia/cuda nvidia-smi
Using default tag: latest
latest: Pulling from nvidia/cuda
862a3e9af0ae: Pull complete 
6498e51874bf: Pull complete 
159ebdd1959b: Pull complete 
0fdbedd3771a: Pull complete 
7a1f7116d1e3: Pull complete 
efaeb940e018: Pull complete 
402b9bcd241b: Pull complete 
fa80a243dd1e: Pull complete 
e001b425a1f2: Pull complete 
b43be1f85916: Pull complete 
Digest: sha256:e6adcc71d074fdcb82667697c3406e7729e349848f84c35324b2bf80bf9f16c2
Status: Downloaded newer image for nvidia/cuda:latest
Fri Sep 23 14:35:50 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.44                 Driver Version: 367.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
|  0%   51C    P8    13W / 240W |    374MiB /  8110MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by flx42** [comment]
No problem!

**Comment by Jacktofine** [comment]
@flx42 I meet same question, and nvidia-smi is normal .

> journalctl -n -u nvidia-docker
-- Logs begin at Thu 2017-04-13 15:31:19 CST, end at Thu 2017-04-13 15:33:23 CST
Apr 13 15:33:10 tensor002 nvidia-docker-plugin[3055]: /usr/bin/nvidia-docker-plu
Apr 13 15:33:10 tensor002 nvidia-docker-plugin[3055]: /usr/bin/nvidia-docker-plu
Apr 13 15:33:10 tensor002 systemd[1]: nvidia-docker.service: Main process exited
Apr 13 15:33:10 tensor002 systemd[1]: Failed to start NVIDIA Docker plugin.
Apr 13 15:33:10 tensor002 systemd[1]: nvidia-docker.service: Unit entered failed
Apr 13 15:33:10 tensor002 systemd[1]: nvidia-docker.service: Failed with result 
Apr 13 15:33:11 tensor002 systemd[1]: nvidia-docker.service: Service hold-off ti
Apr 13 15:33:11 tensor002 systemd[1]: Stopped NVIDIA Docker plugin.
Apr 13 15:33:11 tensor002 systemd[1]: nvidia-docker.service: Start request repea
Apr 13 15:33:11 tensor002 systemd[1]: Failed to start NVIDIA Docker plugin.
This question take me several days, thank you for your help

**Comment by flx42** [comment]
@Jacktofine it looks like your log is truncated? you probably didn't copy the full lines

**Comment by Jacktofine** [comment]
Thank you ! I solve it, The key is install nvidia-modprobe before install nvidia-docker .

**Comment by huge123** [comment]
Thanks @Jacktofine for your solution，it works for me
