### ISSUE TITLE
nvidia-docker.sock/VolumeDriver.mount error: connection refused

### ISSUE THREAD

**Issue by denissimakov** [NVIDIA/nvidia-docker#200]
"nvidia-docker run" stops working, exits with the following message (after being stuck for about a minute):
```
docker: Error response from daemon: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Mount: dial unix /var/lib/nvidia-docker/nvidia-docker.sock: connect: connection refused.
See 'docker run --help'.
```
"docker run" on the same container succeeds. 

Additional symptom: "docker ps" hangs for a while, then produces expected output. 
There is a container previously started with "nvidia-docker run" running on the same system, works well, uses GPU. 
After migrating the same image to another (very similar) machine ("docker save" + "docker load"), "nvidia-docker run" succeeds.  

```
Linux server_3 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by 3XX0** [comment]
What version of `nvidia-docker` are you running? And how did you install it?

Also can you show me the permission of `/var/lib/nvidia-docker` and `/var/lib/nvidia-docker/nvidia-docker.sock`, the output of `service nvidia-docker status` and the logs of the plugin (`/var/log/upstart/nvidia-docker.log`).

**Comment by denissimakov** [comment]
```
Package: nvidia-docker
Architecture: amd64
Version: 1.0.0~rc.3-1

```

Installed as following:
```
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
```

Permissions:
```
$ ls -al /var/lib/nvidia-docker/
total 12
drwxr-xr-x  3 nvidia-docker nvidia-docker 4096 Sep 12 07:26 .
drwxr-xr-x 76 root          root          4096 Sep 11 10:39 ..
srwxr-xr-x  1 nvidia-docker nvidia-docker    0 Sep  8 13:58 nvidia-docker.sock
drwxr-xr-x  3 nvidia-docker nvidia-docker 4096 Sep 12 07:26 volumes
```

Service:
```
$ service nvidia-docker status
nvidia-docker stop/waiting
```

Regarding logs, I have trouble getting them... I see only gzipped achives, not the log file itself...

**Comment by 3XX0** [comment]
The plugin is stopped, this explains the issue. Start it and it this should fix it: `sudo start nvidia-docker`

**Comment by denissimakov** [comment]
Thanks, solved indeed.
