### ISSUE TITLE
Why did Fetch-error do? 

### ISSUE THREAD

**Issue by yoshihingis** [NVIDIA/nvidia-docker#204]
I tried Nvidia-docker and this sample code.
I could confirm that nvidia-smi operated correctly.
So I made this Dockerfile  and tried it, but Ubuntu did Fetch-error.

I used Ubuntu14.04LTS JP and CUDA7.5.

I'd really appriciate it if anyone will techne me the way to solve this issue.

=================================================================  

yoshiki@hikaru:~/docker/deviceQuery$ sudo nvidia-docker build -t local:deviceQuery .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM nvidia/cuda
latest: Pulling from nvidia/cuda
862a3e9af0ae: Already exists 
6498e51874bf: Already exists 
159ebdd1959b: Already exists 
0fdbedd3771a: Already exists 
7a1f7116d1e3: Already exists 
efaeb940e018: Pull complete 
402b9bcd241b: Pull complete 
fa80a243dd1e: Pull complete 
e001b425a1f2: Pull complete 
b43be1f85916: Pull complete 
Digest: sha256:e6adcc71d074fdcb82667697c3406e7729e349848f84c35324b2bf80bf9f16c2
Status: Downloaded newer image for nvidia/cuda:latest
 ---> 0d33583a3259
Step 2 : RUN apt-get update && apt-get install -y --no-install-recommends         cuda-samples-$CUDA_PKG_VERSION &&     rm -rf /var/lib/apt/lists/*
 ---> Running in a17760a1d635
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cuda-samples-8-0
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends         cuda-samples-$CUDA_PKG_VERSION &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by flx42** [comment]
It doesn't look like an error related to nvidia-docker.
Did you try running a simple `apt-get update` inside a ubuntu:14.04 container? Or maybe a simple `ping` command inside a container.

**Comment by yoshihingis** [comment]
Thank you for your advice.
I did running a simple apt-get update as below and I got same Errors.
I think that it is not problem of the nvidia-docker and I need the Docker setting of network.
Is it right?
=======================================================================
yoshiki@hikaru:~$ sudo docker run --name="test" ubuntu:14.04 apt-get update
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by flx42** [comment]
Indeed, you have a Docker network setting issue, did you try the following?
```
docker run -ti ubuntu:14.04 ping ubuntu.com
```

You might need to configure your DNS, check
```
docker run -ti ubuntu:14.04 cat /etc/resolv.conf
```
And then take a look at the [Docker documentation](https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/)

Closing this issue, it's not a `nvidia-docker` bug.
