### ISSUE TITLE
Novel case of: VolumeDriver.Create: internal error, check logs for details.

### ISSUE THREAD

**Issue by anwald** [NVIDIA/nvidia-docker#211]
Hi,
I am running Ubuntu 14.04 with the docker-engine package and the docker version is 1.12.1.
I installed NVidia-docker using the instructions for the rpm.
I had the same partition problem (my /usr and /var partitions are on different devices) as others, so I went ahead and made this modification to my /etc/default/nvidia-docker file:

NVIDIA_DOCKER_PLUGIN_OPTS="-s /var/lib/nvidia-docker -d /usr/local/nvidia-docker/volumes"

I also create the directory:

sudo mkdir -p /usr/local/nvidia-docker/volumes
sudo chown nvidia-docker:nvidia-docker /usr/local/nvidia-docker/volumes

Then I restart the docker service:   sudo service docker restart

Then I try:  sudo nvidia-docker run --rm nvidia/cuda nvidia-smi    and I get:

docker: Error message from daemon: create nvidia_driver_370.28: VolumeDriver.Create: internal error, check logs for details.  (same as others)

Now, sudo  cat  /var/log/kern.log gives me:

aufs au_opts_verify:1541:dockerd[4057]: dirperm1 breaks the protection by the permission bits on the lower branch

And at the same time, in  sudo  cat /var/log/upstart/nvidia-docker.log  I get:

Error: link /usr/src/gdk/nvml/lib/libnvidia-ml.so.1  /usr/local/nvidia-docker/volumes/nvidia_driver/370.28/lib64/libnvidia-ml.so.1:  file exists

But of course that link does not exist. Now if I go and create the directory nvidia_driver/370.28 myself and then make the link myself, then I bypass this error, but then I get that PATH error that others were getting because I fool the daemon into thinking that the contents were already there.

I feel that I'm very close -- I tried to replicate the similar issues and spent very many hours but could not resolve this. There is something about the link that the nvidia-docker user is unable to do... not sure why.

Thanks

**Comment by flx42** [comment]
Look at this [comment](https://github.com/NVIDIA/nvidia-docker/issues/180#issuecomment-242845459)

**Comment by anwald** [comment]
Hi Felix,

Here is exactly what I just did:

```
apt-get purge nvidia-docker
rm -rf /var/lib/nvidia-docker

# Install nvidia-docker and nvidia-docker-plugin
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

```
Modify the /etc/default/nvidia-docker file to contain:
NVIDIA_DOCKER_PLUGIN_OPTS=”-s /var/lib/nvidia-docker -d /usr/local/nvidia-docker/volumes”

Restart machine.

```
# Test nvidia-smi
nvidia-docker run --rm nvidia/cuda nvidia-smi
```

Same error:

docker: error reponse from daemon: create nvidia_driver_370.28: VolumeDriver.Create: internal error, check logs for details.

/var/log/upstart/nvidia-docker.log:  `Error: link /usr/src/gdk/nvml/lib/libnvidia-ml.so.1 /usr/local/nvidia-docker/volumes/nvidia_driver/370.28/lib64/libnvidia-ml.so.1: file exists`

/var/log/kern.log:  `aufs au_opts_verify:1541:dockerd[4057]: dirperm1 breaks the protection by the permission bits on the lower branch`

**Comment by flx42** [comment]
Please read the comment I linked:

> /usr/src/gdk/nvml/lib/libnvidia-ml.so.1 should not be in your ldcache.
> This library is a stub library and is only useful for development purposes.
> Remove the path from your /etc/ld.so.conf or /etc/ld.so.conf.d and rebuild the cache with ldconfig

**Comment by anwald** [comment]
My apologies, I was not sure exactly which part you were referring to. It turns out that I did in fact have /usr/src/gdk/nvml/lib in my ld.so.cache ... I'm really not sure how it got there... I guess any dev projects that link against that stub library should specify its path explicitly since I have removed it from the ldcache.. it turns out we were doing that anyway.

So for those who follow, I got rid of the /usr/src/gdk/nvml/lib entry which I found in my /etc/ld.so.conf and rebuilt the ldcache using the ldconfig tool, as per above, and it's working perfectly now.... (others who have this issue may alternatively have it on their env var LD_LIBRARY_PATH)

Thank you Felix

**Comment by flx42** [comment]
No problem! Closing.

**Comment by flx42** [comment]
Oh, by the way, the GDK is now integrated into the CUDA toolkit, as of CUDA 8.0. So there is no additional download needed.
