### ISSUE TITLE
7.5-cudnn4-devel from docker hub giving libcudnn 4.0.8 not 4.0.7

### ISSUE THREAD

**Issue by hajapy** [NVIDIA/nvidia-docker#213]
It seems to be the hosted  7.5-cudnn4-devel image is providing cudnn 4.0.8 rather than 4.0.7. I did a simple test of building images from both the devel and runtime images and the devel image shows a libcudnn version of 4.0.8.  Note that I am building this on a mac with Docker for Mac stable (Version 1.12.1, build: 12133) but intend to run it with nvidia-docker on a linux machine. Steps to reproduce are:

1. Make Dockerfile
------------
FROM nvidia/cuda:7.5-cudnn4-devel

CMD ["/bin/bash"] 

2. Build and run interactively
------------
`docker build .`
`docker run -it <IMAGE ID>`

3. Test
------------
root@09c2680f71a0:/# dpkg -s libcudnn4
Package: libcudnn4
Status: install ok installed
Priority: optional
Section: multiverse/libs
Installed-Size: 60054
Maintainer: cudatools <cudatools@nvidia.com>
Architecture: amd64
Source: cudnn
Version: 4.0.8
Depends: libc6 (>= 2.3.3), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.1.1)
Description: cuDNN runtime libraries

 cuDNN runtime libraries containing primitives for deep neural networks.

4. With 7.5-cudnn4-runtime instead of  7.5-cudnn4-devel 
------------
root@e2f90a18c295:/# dpkg -s libcudnn4
Package: libcudnn4
Status: install ok installed
Priority: optional
Section: multiverse/libs
Installed-Size: 60054
Maintainer: cudatools <cudatools@nvidia.com>
Architecture: amd64
Source: cudnn
Version: 4.0.7
Depends: libc6 (>= 2.3.3), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.1.1)
Description: cuDNN runtime libraries
 cuDNN runtime libraries containing primitives for deep neural networks.

**Comment by flx42** [comment]
Seems to be the same as #131, sorry about that. I will update the images soon.

**Comment by flx42** [comment]
@hajapy new images are being pushed right now.
