### ISSUE TITLE
"public key is not available" for cuDNN APT repo in ubuntu 14.04 images

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#215]
I get the following error if I run `apt-get update` in one of the ubuntu 14.04-based images that includes cudnn:
```
W: GPG error: http://developer.download.nvidia.com  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80
```
My Dockerfile looks like this:
```
FROM nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04
RUN apt-get update
```
and I can get the same result if I replace `nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04` with cudnn4. 

This error does not occur when I build from one of the ubuntu 16.04 Dockerfiles, e.g., `nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04`. I believe the reason it works there is that cudnn isn't being installed from APT, but rather some tarball that's downloaded from nvidia.

**Comment by grisaitis** [comment]
I'm able to fix the issue by adding this before I run `apt-get update`:
```
RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/7fa2af80.pub
```

I'll submit a pull request shortly with this change implemented.

**Comment by grisaitis** [comment]
Fixed the issue! 

The error was caused by stale base images on my local docker host. 

Re-pulling the images solved the problem, either with `docker build --pull ...` or `for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep nvidia/cuda); do docker pull $i; done`.

**Comment by grisaitis** [comment]
To clarify: this was user error. No pull request / code changes warranted.

**Comment by flx42** [comment]
No problem, sorry for breaking the public CUDA repo, the transition has been rough for everyone!

**Comment by jacknlliu** [comment]
I got the same error with Ubuntu 16.04. How to get the public key for ubuntu 16.04? @flx42

**Comment by flx42** [comment]
You already asked on GitLab, and this issue has been fixed a long time ago, so you're facing a diffent issue.
