### ISSUE TITLE
Fails to start if /usr/bin and /var/lib are on different partions

### ISSUE THREAD

**Issue by hakanardo** [NVIDIA/nvidia-docker#217]
Hi,
on startup it tries to link /usr/bin/nvidia-cuda-mps-control into /var/lib/nvidia-docker/... This fails if those are on different partitions. Could you fall back on a copy in that case?

**Comment by 3XX0** [comment]
This is a known limitation, see [documentation](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#known-limitations)
