### ISSUE TITLE
nohup: ignoring input and redirecting stderr to stdout while running nvidia-docker-plugin in Other distribution

### ISSUE THREAD

**Issue by vasantivmahajan** [NVIDIA/nvidia-docker#218]
While running "sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log", nohup: ignoring input and redirecting stderr to stdout  error message is displayed.

![image](https://cloud.githubusercontent.com/assets/17990840/19320644/1d29357c-9080-11e6-9070-0addc0a3fdd8.png)

Any help is appreciated!

**Comment by 3XX0** [comment]
This is not an error, it's the normal behavior. Check `man nohup`
