### ISSUE TITLE
Release file has an invalid format

### ISSUE THREAD

**Issue by marker68** [NVIDIA/nvidia-docker#22]
I have used the `*.deb` file from https://developer.nvidia.com/cuda-downloads  and got the following error:
![error_cuda](https://cloud.githubusercontent.com/assets/7877114/11809676/dad3b1b8-a36b-11e5-891b-9b7da68bdd69.png)

The message is in Japanese, but actually it say that the Release file which is downloaded from your repo server has an invalid format (it doesn't have the `Date` entry).
I had a look on the file http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1504/x86_64/Release

```
Origin: NVIDIA
Label: NVIDIA CUDA
Architecture: x86_64
MD5Sum:
 53fb7789d89de57b8b052e5b28254866           150643 Packages
 d4d3a64356184ac129fec95a6244e548            31840 Packages.gz
```

Compared to a normal Release file in http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/xenial/Release

```
Origin: LP-PPA-webupd8team-java
Label: Oracle Java (JDK) 7 / 8 / 9 Installer PPA
Suite: xenial
Version: 16.04
Codename: xenial
Date: Thu, 10 Dec 2015 11:34:49 UTC
Architectures: amd64 arm64 armhf i386 powerpc ppc64el s390x
Components: main
Description: Ubuntu Xenial 16.04
MD5Sum:
 c5317774ad35c439d0dc00f34aafafbe              148 main/binary-amd64/Release
 d2ad9cb36753a85b34709643dfa292b2             3092 main/binary-amd64/Packages.gz
 28e0cfd043c5f191555eba324b6ee4e3            19522 main/binary-amd64/Packages
 34efda5be4bc4cc9356281fefd1df8b3             3376 main/binary-amd64/Packages.bz2
 b3303d9091b8b3837e1c19b2b7e2ea77              148 main/binary-arm64/Release
...
```

My environment is as follows:
```
OS: Ubuntu 16.04 Review
GPU: GeForce GTX 560 Ti

```

**Comment by flx42** [comment]
Hello,

You are trying to use the Ubuntu 15.04 repository with Ubuntu 16.04. Also, 16.04 is not officially supported right now. Therefore I don't believe this is a bug.
