### ISSUE TITLE
nvidia-docker for ppc64

### ISSUE THREAD

**Issue by ianamunoz** [NVIDIA/nvidia-docker#222]
What is the progress or status of ppc64? 

It looks like @clnperez and @flx42 have done a deb build, I am on Centos so I would like to try and get a centos 7 build going.

Thoughts?

**Comment by clnperez** [comment]
Something I can definitely look into when I get some bandwidth maybe next week. ppc64le, just to be clear.

**Comment by ianamunoz** [comment]
@clnperez yes correct. I have some time to help on this, as well as machines to test on if needed. Let me know what makes sense for me to look at.

**Comment by clnperez** [comment]
@ianamunoz Which version of cuda are you wanting to use initially?

**Comment by clnperez** [comment]
Kind of a kink in this plan -- there's no upstream centos image for ppc64le.

**Comment by clnperez** [comment]
@ianamunoz Could you just use 'make install'? Someone in our lab using RHEL did this this week and then manually started the plugin to use nvidia-docker.

**Comment by ysh329** [comment]
Mark

Have version on PPC(IBM OpenPower) architecture? · Issue #389 · NVIDIA/nvidia-docker
https://github.com/NVIDIA/nvidia-docker/issues/389

**Comment by clnperez** [comment]
https://github.com/NVIDIA/nvidia-docker/pull/472
