### ISSUE TITLE
Nvidia is not running for my Deep learning tasks

### ISSUE THREAD

**Issue by shravankumar147** [NVIDIA/nvidia-docker#226]
Hi, I have started deep learning, and Below I have mentioned VGA devices on my computer. I have installed cuda7.5, but I am unable to speedup my programs. I need some help to set up my GPU so that my programs will run quicker. Thank you.
Common errors I got : 
_modprobe error: FATAL nvidia not loaded
nvidia-smi error_

#########################################################################
shravan@shravan:~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 635M] (rev a1)
#########################################################################
shravan@shravan:~$ lspci -vnn | grep VGA -A 12
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device [1043:1447]
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at f7400000 (64-bit, non-prefetchable) [size=4M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: <access denied>
	Kernel driver in use: i915

00:14.0 USB controller [0c03]: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller [8086:1e31] (rev 04) (prog-if 30 [XHCI])
	Subsystem: ASUSTeK Computer Inc. Device [1043:1447]
	Flags: bus master, medium devsel, latency 0, IRQ 25
--
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF108M [GeForce GT 635M] [10de:0de3] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device [1043:1447]
	Flags: bus master, fast devsel, latency 0, IRQ 32
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at f7000000 [disabled] [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia

03:00.0 Network controller [0280]: Qualcomm Atheros AR9485 Wireless Network Adapter [168c:0032] (rev 01)
	Subsystem: AzureWave Device [1a3b:2c97]

**Comment by flx42** [comment]
This doesn't seem to be a problem related to `nvidia-docker`, in this case I suggest you seek help on the [NVIDIA Developer Forum](https://devtalk.nvidia.com/) instead, thank you.
