### ISSUE TITLE
cuda 8 for centos 6

### ISSUE THREAD

**Issue by zym1010** [NVIDIA/nvidia-docker#227]
Hi,

Can you NVIDIA kindly provide such an image? My university is still using centos 6 clusters, with CUDA 7.5 installed. Now I use the CUDA 7.5 image to build tensorflow package, since I can install newer compiler easily in the Docker to build it, but not in the cluster. However, it might be very likely that the staff will install some new Pascal cards, and we need to use CUDA 8 then. There's no corresponding Docker image I can use in this repo. Thanks.

**Comment by flx42** [comment]
Hello,

Sure, I can add the CentOS 6 image for CUDA 8.0.
But I'm not sure I understand, is your cluster using Docker for execution? In this case I don't understand why you need 8.0 on CentOS 6. Or is Docker only for building the package?

**Comment by zym1010** [comment]
Thanks. I use docker only for building the package, since the gcc tool chain on the cluster is not new enough. After building, I copied the binaries out of the container and run them on the old cluster.

**Comment by flx42** [comment]
New images are up on DockerHub.
