### ISSUE TITLE
Problem with cuda 8.0 in Ubuntu 16.04 lts

### ISSUE THREAD

**Issue by lincoln2010** [NVIDIA/nvidia-docker#228]
Dear hosters:

The problem occurred when I tried to run samples matrixMulCUBLAS it displays:
[Matrix Multiply CUBLAS] - Starting...
cudaGetDevice returned error code 30, line(166)
My machine info:
Ubuntu 16.04lts
GTX 1080 graphical card
Cuda Toolkit 8.0.44-21122537
However, when I try to run nvidia-smi, it works fine.

Best

**Comment by lincoln2010** [comment]
And every other applications based on cuda also failed.

**Comment by flx42** [comment]
Hello

Is the CUDA sample working on the host (outside of Docker)? If not, there is a problem with your driver install and you probably need to fix that first. Please paste the output of command `nvidia-smi` too.

Also, the output of `ls -R /var/lib/nvidia-docker/volumes/nvidia_driver` might be useful if everything seems to be working fine on the host.

**Comment by flx42** [comment]
ping @lincoln2010 ?
