### ISSUE TITLE
create volume fail with OpenGL

### ISSUE THREAD

**Issue by James-Dao** [NVIDIA/nvidia-docker#229]
I run into a problem when use docker volume create -d nvidia-docker --name nvidia_driver_367.57

docker version is 1.12.2, OS is redhat7. how to fix this problem ? 

error is that: 
Error: link /usr/lib/libOpenGL.so.0 /var/lib/nvidia-docker/volumes/nvidia_driver/367.57/lib/libOpenGL.so.0: file exists

[root@c01n001 ~]# nvidia-smi
Tue Oct 25 14:33:00 2016  
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K20m          Off  | 0000:86:00.0     Off |                    0 |
| N/A   22C    P8    17W / 225W |      0MiB /  4742MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

[root@c01n001 ~]# cat /tmp/nvidia-docker.log 
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:13 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:13 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:14 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:16 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:16 Serving plugin API at /run/docker/plugins
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:16 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:43 Received activate request
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:43 Plugins activated [VolumeDriver]
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:43 Received create request for volume 'nvidia_driver_367.57'
/usr/bin/nvidia-docker-plugin | 2016/10/25 14:27:43 Error: link /usr/lib/libOpenGL.so.0 /var/lib/nvidia-docker/volumes/nvidia_driver/367.57/lib/libOpenGL.so.0: file exists

**Comment by 3XX0** [comment]
You have duplicate GLVND installs on your system, check `ldconfig -p | grep libOpenGL`

**Comment by James-Dao** [comment]
[root@c01n001 log]# ldconfig -p |grep libOpenGL
	libOpenGL.so.0 (libc6,x86-64) => /usr/lib64/nvidia/libOpenGL.so.0
	libOpenGL.so.0 (libc6,x86-64) => /lib64/libOpenGL.so.0
	libOpenGL.so.0 (libc6) => /usr/lib/nvidia/libOpenGL.so.0
	libOpenGL.so.0 (libc6) => /lib/libOpenGL.so.0
	libOpenGL.so (libc6,x86-64) => /usr/lib64/nvidia/libOpenGL.so
	libOpenGL.so (libc6,x86-64) => /lib64/libOpenGL.so
	libOpenGL.so (libc6) => /usr/lib/nvidia/libOpenGL.so
	libOpenGL.so (libc6) => /lib/libOpenGL.so

how to fix it ?

**Comment by 3XX0** [comment]
Check what packages conflict, assuming you are on Ubuntu/Debian:
```
dpkg -S /lib64/libOpenGL.so.0
dpkg -S /usr/lib64/nvidia/libOpenGL.so.0
```
Hopefully you can remove one of these.

**Comment by flx42** [comment]
He said he's on rhel7, use `yum whatprovides`:
```
$ yum whatprovides /usr/local/cuda/lib64/libnppi.so
cuda-npp-8-0-8.0.44-1.x86_64 : NPP native runtime libraries
Repo        : @cuda
Matched from:
Filename    : /usr/local/cuda/lib64/libnppi.so
```

**Comment by James-Dao** [comment]
[root@c01n001 ~]# yum whatprovides /usr/local/cuda/lib64/libnppi.so
Loaded plugins: nvidia, product-id, subscription-manager
docker-main-repo/filelists_db                                                                           |  21 kB  00:00:00     
elrepo/filelists_db                                                                                     |  46 kB  00:00:00     
rhel-7-server-eus-rpms/7Server/x86_64/filelists_db                                                      |  19 MB  00:00:22     
rhel-7-server-rpms/7Server/x86_64/filelists_db                                                          |  19 MB  00:00:19     
rhel-7-server-rt-beta-rpms/x86_64/filelists_db                                                          | 505 kB  00:00:01     
rhel-7-server-rt-rpms/7Server/x86_64/filelists_db                                                       | 7.4 MB  00:00:09     
rhel-ha-for-rhel-7-server-eus-rpms/7Server/x86_64/filelists_db                                          | 260 kB  00:00:01     
rhel-ha-for-rhel-7-server-rpms/7Server/x86_64/filelists_db                                              | 260 kB  00:00:01     
rhel-rs-for-rhel-7-server-eus-rpms/7Server/x86_64/filelists_db                                          | 277 kB  00:00:00     
rhel-rs-for-rhel-7-server-rpms/7Server/x86_64/filelists_db                                              | 277 kB  00:00:01     
No matches found

**Comment by James-Dao** [comment]
[root@c01n001 ~]# yum whatprovides /usr/lib64/nvidia/libOpenGL.so.0
Loaded plugins: nvidia, product-id, subscription-manager
nvidia-x11-drv-361.45.11-1.el7.elrepo.x86_64 : NVIDIA OpenGL X11 display driver files
Repo        : elrepo
Matched from:
Filename    : /usr/lib64/nvidia/libOpenGL.so.0



nvidia-x11-drv-367.35-1.el7.elrepo.x86_64 : NVIDIA OpenGL X11 display driver files
Repo        : elrepo
Matched from:
Filename    : /usr/lib64/nvidia/libOpenGL.so.0



nvidia-x11-drv-367.44-1.el7.elrepo.x86_64 : NVIDIA OpenGL X11 display driver files
Repo        : elrepo
Matched from:
Filename    : /usr/lib64/nvidia/libOpenGL.so.0



nvidia-x11-drv-367.57-1.el7.elrepo.x86_64 : NVIDIA OpenGL X11 display driver files
Repo        : elrepo
Matched from:
Filename    : /usr/lib64/nvidia/libOpenGL.so.0



nvidia-x11-drv-367.57-1.el7.elrepo.x86_64 : NVIDIA OpenGL X11 display driver files
Repo        : @elrepo
Matched from:
Filename    : /usr/lib64/nvidia/libOpenGL.so.0

**Comment by James-Dao** [comment]
[root@c01n001 ~]# yum whatprovides /usr/lib/nvidia/libOpenGL.so.0
Loaded plugins: nvidia, product-id, subscription-manager
nvidia-x11-drv-32bit-361.45.11-1.el7.elrepo.x86_64 : Compatibility 32-bit files for the 64-bit Proprietary NVIDIA driver
Repo        : elrepo
Matched from:
Filename    : /usr/lib/nvidia/libOpenGL.so.0



nvidia-x11-drv-32bit-367.35-1.el7.elrepo.x86_64 : Compatibility 32-bit files for the 64-bit Proprietary NVIDIA driver
Repo        : elrepo
Matched from:
Filename    : /usr/lib/nvidia/libOpenGL.so.0



nvidia-x11-drv-32bit-367.44-1.el7.elrepo.x86_64 : Compatibility 32-bit files for the 64-bit Proprietary NVIDIA driver
Repo        : elrepo
Matched from:
Filename    : /usr/lib/nvidia/libOpenGL.so.0



nvidia-x11-drv-32bit-367.57-1.el7.elrepo.x86_64 : Compatibility 32-bit files for the 64-bit Proprietary NVIDIA driver
Repo        : elrepo
Matched from:
Filename    : /usr/lib/nvidia/libOpenGL.so.0



nvidia-x11-drv-32bit-367.57-1.el7.elrepo.x86_64 : Compatibility 32-bit files for the 64-bit Proprietary NVIDIA driver
Repo        : @elrepo
Matched from:
Filename    : /usr/lib/nvidia/libOpenGL.so.0

**Comment by 3XX0** [comment]
What about `yum whatprovides /lib64/libOpenGL.so.0` ?
