### ISSUE TITLE
CuDNN library unpacked to wrong path

### ISSUE THREAD

**Issue by wielandbrendel** [NVIDIA/nvidia-docker#23]
I noticed that the CuDNN libraries are put in the root directory although they should actually be under /usr/local/cuda/lib64. I tried to boil it down and the issue seems to be at the untar command:

    tar -xzf cudnn-7.0-linux-x64-v3.0-prod.tgz --wildcards 'cuda/lib64/libcudnn.so*' -C /usr/local

I tried, but the files are untarred into the root, i.e. /cuda/lib64/... One workaround would be

    cd /usr/local && \
    tar -xzf /cudnn-7.0-linux-x64-v3.0-prod.tgz --wildcards 'cuda/lib64/libcudnn.so*'

PS: Btw, a big thanks for making CUDA + CuDNN available on Docker Hub! That really was the missing piece to make my toolchain available on Docker Hub.

**Comment by flx42** [comment]
It was only the case for images `7.0-cudnn3-runtime` and `7.5-cudnn3-runtime`, I had to move the `-C` before the `--wildcards`. It should be fixed now, the new images will be pushed to the Hub in a few minutes.

**Comment by wielandbrendel** [comment]
Wow - a big thanks for the fast response!
