### ISSUE TITLE
Add CUDA 8.0 to backwards-compatibility table in Wiki

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#230]
The wiki has [an informative table](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements) summarizing backwards compatibility for driver versions and CUDA versions. 

It currently only shows CUDA through 7.5, though. Could CUDA 8.0 be added?

I'm interested in learning what the minimum driver version is for CUDA 8.0.

**Comment by flx42** [comment]
Edited, thanks!
8.0 is a bit special, if you have a P100 GPU, you *must* use a 361 driver right now. For all others GPUs, you need 367 or higher.

**Comment by flx42** [comment]
Let me know if the table makes sense now.

**Comment by grisaitis** [comment]
Thank you so much!
