### ISSUE TITLE
Digits 4.0 docker image contains no stock models

### ISSUE THREAD

**Issue by dtmoodie** [NVIDIA/nvidia-docker#232]
Running a docker image from nvidia/digits:latest lists no networks under "Standard Networks".

**Comment by lukeyeager** [comment]
This is not a `nvidia-docker` issue. DIGITS only provides standard networks for image classification. Sorry for the confusing UI.

**Comment by dtmoodie** [comment]
Would it be possible to move the digits docker file to the digits repo then? As it is now it appears to be in this repo. 
https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/digits/4.0/Dockerfile
