### ISSUE TITLE
Cannot install on Ubuntu 16.10 Yakkety - dependency issues

### ISSUE THREAD

**Issue by hammertimedk** [NVIDIA/nvidia-docker#234]
Hi,

Installed Docker as per instructions here:

[https://docs.docker.com/engine/installation/linux/ubuntulinux/](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

used the 16.04 repo, and Docker seems to run fine.

When installing nvidia-docker however, I get the following message:

```
dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
Selecting previously unselected package nvidia-docker.
(Reading database ... 216533 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.0.rc.3-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0~rc.3-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16); however:
  Package sysv-rc is not installed.
  Package file-rc is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 nvidia-docker
```

**Comment by Phyronnaz** [comment]
You need to install ```sysvinit-utils```

**Comment by hammertimedk** [comment]
Nope sorry, aptitude reports it's already the latest version:

```
# apt-get install sysvinit-utils
Reading package lists... Done
Building dependency tree
Reading state information... Done
sysvinit-utils is already the newest version (2.88dsf-59.8git1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

**Comment by Phyronnaz** [comment]
Try ```apt-get -f install```
It should install the dependencies

**Comment by hammertimedk** [comment]
That just prompts apt to remove the package ...

```
# apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  nvidia-docker
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 14.0 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 216540 files and directories currently installed.)
Removing nvidia-docker (1.0.0~rc.3-1) ...
```

**Comment by flx42** [comment]
16.10 is not supported right now, but I believe that if you simply change [this line](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/Dockerfile.deb#L10 to `ubuntu:16.04`, it should work. You can generate a package yourself with `make deb`. Let me know if that works.

**Comment by srmanikandasriram** [comment]
@flx42 Thank you. I modified that line to ubuntu:16.10 and used make deb like you suggested and I was able to install nvidia-docker successfully.

**Comment by fbarilla** [comment]
@flx42 The 'this line' is broken, which file has to be changed ?

**Comment by flx42** [comment]
@fbarilla Sorry, we shuffled the files around recently:
https://github.com/NVIDIA/nvidia-docker/blob/3422bca/Dockerfile.deb#L1

**Comment by zixia** [comment]
@hammertimedk @flx42 Thanks for your question and your answer.

I followed your suggestion, built and installed successfully in my ubuntu desktop 16.10 box.

I zipped my file and uploaded it here, hope it can help others from clone&edit&docker&make works. :)

[nvidia-docker_1.0.1-yakkety_amd64.deb.zip](https://github.com/NVIDIA/nvidia-docker/files/818401/nvidia-docker_1.0.1-yakkety_amd64.deb.zip)

**Comment by Tommy1011110** [comment]
I have the same problem of the 1st post, but i didn't understand how to fix that..

**Comment by AwokeKnowing** [comment]
I have same problem on ubuntu 17 but with the yakkety zip above I get
```
Job for nvidia-docker.service failed because the control process exited with error code.
See "systemctl status nvidia-docker.service" and "journalctl -xe" for details.
nvidia-docker.service couldn't start.
```

**Comment by tycho01** [comment]
Same issue as @AwokeKnowing here, also Ubuntu 17.04, `nvidia-modprobe` already installed.

**Comment by rringham** [comment]
I have the same problem as well, but I don't understand enough about rebuilding deb files to fix this on my Ubuntu 17.04 setup. Could someone please explain what you need to do here?

**Comment by AwokeKnowing** [comment]
@tycho01 @rringham I ended up just going with 16.04 (LTS).  Everything is working fine.  In one year 18.04 should be fully supported, so that's a year away.  I do most everything dev-related in Docker anyways, so it shouldn't matter that much.

**Comment by 3XX0** [comment]
Closing, this should be fixed in 2.0/master

**Comment by heysemkaya** [comment]
**Hi, I suffer the same problem with Ubuntu 18.04 Bionic Beaver:**
>wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
>sudo dpkg -i /tmp/nvidia-docker*.deb
Selecting previously unselected package nvidia-docker.
(Reading database ... 211201 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.1-1_amd64.deb ...
Unpacking nvidia-docker (1.0.1-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16); however:
  Package sysv-rc is not installed.
  Package file-rc is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-20) ...
Errors were encountered while processing:
 nvidia-docker


**I checked the comments on these issues, tried to install sysvinit-utils but it didn't work out (already in its newest version). Is there a workaround? Or is Ubuntu 18.04 not supported at the moment?**

**Comment by johnny06** [comment]
You will have to resolve your dependency first

Le ven. 13 juil. 2018 à 16:56, heysemkaya <notifications@github.com> a
écrit :

**Comment by heysemkaya** [comment]
**Thanks but how? See this:**
sudo apt-get install sysvinit-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sysvinit-utils is already the newest version (2.88dsf-59.10ubuntu1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 nvidia-docker : Depends: sysv-rc (>= 2.88dsf-24) but it is not installable or
                          file-rc (>= 0.8.16) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by heysemkaya** [comment]
**Here is what I get**
sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  nvidia-docker
0 upgraded, 0 newly installed, 1 to remove and 78 not upgraded.
1 not fully installed or removed.
After this operation, 14.1 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 211208 files and directories currently installed.)
Removing nvidia-docker (1.0.1-1) ...

**When I try to re install nvidia-docker I get the same error as above.**

**Comment by flx42** [comment]
nvidia-docker v1 is not supported on ubuntu 18.04.

**Comment by heysemkaya** [comment]
Thanks for the refreshing news. Is there a version that is supported?

**Comment by flx42** [comment]
Follow the instructions on the current README to get nvidia-docker v2

**Comment by wangpengabc** [comment]
> @hammertimedk @flx42 Thanks for your question and your answer.
> 
> I followed your suggestion, built and installed successfully in my ubuntu desktop 16.10 box.
> 
> I zipped my file and uploaded it here, hope it can help others from clone&edit&docker&make works. :)
> 
> [nvidia-docker_1.0.1-yakkety_amd64.deb.zip](https://github.com/NVIDIA/nvidia-docker/files/818401/nvidia-docker_1.0.1-yakkety_amd64.deb.zip)

Can you tell us how to use the deb package?Thanks ！
When i run 

- sudo dpkg -i nvidia-docker_1.0.1-yakkety_amd64.deb 

Selecting previously unselected package nvidia-docker.
(Reading database ... 208428 files and directories currently installed.)
Preparing to unpack nvidia-docker_1.0.1-yakkety_amd64.deb ...
Unpacking nvidia-docker (1.0.1-1) ...
Setting up nvidia-docker (1.0.1-1) ...
Configuring user
Setting up permissions
Created symlink /etc/systemd/system/multi-user.target.wants/nvidia-docker.service → /lib/systemd/system/nvidia-docker.service.
Processing triggers for ureadahead (0.100.0-19) ...

and then i run

- docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.

**Comment by bspivey** [comment]
> @hammertimedk @flx42 Thanks for your question and your answer.
> 
> I followed your suggestion, built and installed successfully in my ubuntu desktop 16.10 box.
> 
> I zipped my file and uploaded it here, hope it can help others from clone&edit&docker&make works. :)
> 
> [nvidia-docker_1.0.1-yakkety_amd64.deb.zip](https://github.com/NVIDIA/nvidia-docker/files/818401/nvidia-docker_1.0.1-yakkety_amd64.deb.zip)

This build is still helpful in 2021. Huan's build is the only solution I have found for this dependency error.
