### ISSUE TITLE
Problem: caffe and nvidia/cuda:8.0 vs nvidia/cuda:7.5

### ISSUE THREAD

**Issue by Josca** [NVIDIA/nvidia-docker#236]
Hi, thanks for nvidia-docker solution. I am using my own docker image (Dockerfile.txt) based on nvidia/cuda with OpenCV and Caffe. It works well when using nvidia/cuda:7.5-cudnn5-devel, but when I use nvidia/cuda:8.0-cudnn5-devel, caffe tests fail after: 'cd /home/cvuser/caffe/build && make runtest' (error.log.txt). When I build caffe again in started container based on nvidia/cuda:8.0-cudnn5-devel, not just in Dockerfile, tests pass. How can I make caffe with cuda8.0 work after 'docker build' as with cuda7.5?

Testing configurations:
1) cuda7.5:
NVIDIA-SMI 361.42, GeForce GTX 960
Docker version 1.12.1, build 23cf638

2) cuda8.0:
NVIDIA-SMI 367.48, GeForce GTX 1080
Docker version 1.12.2, build bb80604

[Dockerfile.txt](https://github.com/NVIDIA/nvidia-docker/files/564012/Dockerfile.txt)
[error.log.txt](https://github.com/NVIDIA/nvidia-docker/files/564013/error.log.txt)

**Comment by flx42** [comment]
Check your build log, using cmake for caffe won't compile for CUDA arch 6.0+ (Pascal) by default.
You probably need to add these parameters to your cmake line:
```
-DCUDA_ARCH_NAME="Manual" -DCUDA_ARCH_BIN="52 60" -DCUDA_ARCH_PTX="60"
```

**Comment by flx42** [comment]
You probably have something like that in your build log right now:
```
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
```

**Comment by Josca** [comment]
I don't know yet, I will test it. But I found that in CMakeCache.txt generated in running container is defined variable:
CUDA_gpu_detect_output:INTERNAL=6.1
and in CMakeCache.txt generated using Dockerfile not.

**Comment by flx42** [comment]
Yes, it makes sense. At build time there is no GPU detected, so it defaults to `sm_20 sm_21 sm_30 sm_35 sm_50`.
However, when using `nvidia-docker`, cmake detects a GPU and then it targets this GPU arch.

**Comment by Josca** [comment]
Wonderful, it solved my problem. Thanks :+1:. But I wonder even if I used nvidia-docker build for that, I had the same problem. Is it not possible to detect GPU during docker image building?

**Comment by flx42** [comment]
No, during build `nvidia-docker` is simply passthrough to `docker`. I already explained that [here](https://github.com/NVIDIA/nvidia-docker/issues/225#issuecomment-255160514)

**Comment by Josca** [comment]
Oh, I see. Sorry.

But that's a pity. I would like to run my app tests already during docker build phase but it's not possible currently. The tests are dependent on GPU which is not visible yet. It's good that the feature is intended.

Thank you for your help.

**Comment by flx42** [comment]
Tests should be executed during a `[nvidia-]docker run`, not during a build. It's just impossible to pass volumes or devices during a build.
