### ISSUE TITLE
where is the [samples/ folder]?

### ISSUE THREAD

**Issue by ling49043171** [NVIDIA/nvidia-docker#238]
I'm download the nvidia docker(cuda in it), using "docker pull nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04". And the gpu drivers has been install in my local machine。 I want to build one test application to check the nvidia-docker, with cuda in it, work or not.
But I can not find the [samples/ folder] , said from [https://github.com/NVIDIA/nvidia-docker/wiki/Testing-the-samples] .

**Comment by flx42** [comment]
The `samples` folder is in the `nvidia-docker` git repo (this repo):
https://github.com/NVIDIA/nvidia-docker/tree/master/samples

**Comment by ling49043171** [comment]
thanks a lot for your quick answer.
