### ISSUE TITLE
Linking error because of nonexistent directory (under the same mount point)

### ISSUE THREAD

**Issue by szotsaki** [NVIDIA/nvidia-docker#239]
After both the `docker` and `nvidia-docker` services were started, the example application `nvidia-docker run nvidia/cuda nvcc --version` failed with the following message:

    Error: link /usr/bin/nvidia-cuda-mps-control /var/lib/nvidia-docker/volumes/nvidia_driver/367.57/bin/nvidia-cuda-mps-control: operation not permitted

As soon as I manually created the directory `/var/lib/nvidia-docker/volumes/nvidia_driver/367.57/bin/` everything went fine.

OS: openSUSE Leap 42.1 with kernel 4.8.0.

**Comment by szotsaki** [comment]
The rpm file used for installation contains a line (`setcap cap_fowner+pe /usr/bin/nvidia-docker-plugin`) which would require program `setcap` to be present. This, however, is not a requirement of the RPM package which causes the `postin` scriptlet to fail on permission setting. And this causes the error message above.

**Comment by flx42** [comment]
@szotsaki ah, thanks for investigating, we'll take a look!

**Comment by flx42** [comment]
@szotsaki: I took a quick look. Don't you have another problem with openSUSE to begin with? The docker package is called `docker` and not `docker-engine`, so the RPM we provide should actually fail earlier than that.
```
FROM opensuse:leap

RUN zypper install -y wget

RUN wget -qO- https://test.docker.com/ | sh

RUN wget -q -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker-1.0.0.rc.3-1.x86_64.rpm

RUN rpm -i /tmp/nvidia-docker*.rpm && rm /tmp/nvidia-docker*.rpm
```
Doing a `docker build`:
```
Step 5/5 : RUN rpm -i /tmp/nvidia-docker*.rpm && rm /tmp/nvidia-docker*.rpm
 ---> Running in bf5cf41c9f37
error: Failed dependencies:
        docker-engine is needed by nvidia-docker-1.0.0~rc.3-1.x86_64
```

We can add a dependency on `setcap`, but we can't fix this issue easily.
So, how did you solve this first problem?

**Comment by szotsaki** [comment]
@flx42 Yes, since it wasn't an openSUSE package ready, I hacked it onto my system (with some --force flags).

RPM is capable of differentiating the `Require:` levels which is called "[Context Marked Dependencies](http://rpm.org/max-rpm-snapshot/s1-rpm-depend-manual-dependencies.html#S3-RPM-DEPEND-CONTEXT-DEPENDS)". So, in your case it's enough to say `Require(post): libcap`. This allows for `libcap` to be installed only during the package installation procedure (if you need this package only in the `%post` scriptlet).
