### ISSUE TITLE
Update documentation for nvidia driver alternatives wiki

### ISSUE THREAD

**Issue by cgarciae** [NVIDIA/nvidia-docker#240]
Please specify that one should also map the devices on the run command. Currently this is the suggested (incomplete) run command

```
docker run --volume-driver=nvidia-docker --volume=nvidia_driver_361.48:/usr/local/nvidia:ro
```
It would be more helpful to specify a full "hello world" run command, something like this:

```
docker run \
    -v nvidia_driver_367.57:/usr/local/nvidia:ro \
    --device /dev/nvidia0:/dev/nvidia0 \
    --device /dev/nvidiactl:/dev/nvidiactl \
    --device /dev/nvidia-uvm:/dev/nvidia-uvm \
    nvidia/cuda nvidia-smi
```
I didn't include the `--volume-driver` flag since I am using the named volume that apparently its created by the installation process of nvidia-docker.

**Comment by flx42** [comment]
It's already [here](https://github.com/NVIDIA/nvidia-docker/wiki/Internals#enabling-gpu-support-in-your-application)
The section you're mentioning discusses the driver files, so I think it makes sense to not include the devices here.

**Comment by flx42** [comment]
I added one line in the wiki, saying you should take a look at the next section for devices.

**Comment by cgarciae** [comment]
Thanks! Hadn't seen it. Still confusing for non-expert like me there since you use `curl` on the other page instead of just `docker run`, I would have dismissed it. I actually got my solution looking at the docker-compose.yml file in here https://github.com/NVIDIA/nvidia-docker/issues/192

**Comment by flx42** [comment]
If you use `docker-compose`, you might be interested by [this project](https://github.com/eywalker/nvidia-docker-compose) contributed by the community. I haven't tried it, but it could be useful for you.

**Comment by flx42** [comment]
Closing.
