### ISSUE TITLE
v1.0.0-rc.3 deb package fails to install because of missing file /etc/init.d/nvidia-docker

### ISSUE THREAD

**Issue by linuxluser** [NVIDIA/nvidia-docker#242]
[The RC3 debian package](https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb) fails to install on a Debian system because package does not provide file that the postinst seems to be expecting to exist. dpkg complains "invoke-rc.d: unknown initscript, /etc/init.d/nvidia-docker not found.".

I have created a Dockerfile which should make it easy to reproduce the problem: https://gist.github.com/linuxluser/b6e75cc921ce6c1f95d8abccdd2928c6

**Comment by 3XX0** [comment]
Probable the same as #272
