### ISSUE TITLE
Automate setup of nvidia-docker engine host

### ISSUE THREAD

**Issue by lsb** [NVIDIA/nvidia-docker#248]
The installation instructions at https://github.com/NVIDIA/nvidia-docker/wiki/Installation are helpful and thorough! However they enumerate several manual steps, and it has saved a significant amount of time to automate this process, both for Ubuntu and RHEL:

https://github.com/graphistry/infrastructure/tree/master/nvidia-docker-host
https://github.com/graphistry/infrastructure/tree/master/nvidia-docker-rhel

This has not come for free, but the savings have been worth it, when spinning up boxes on EC2 for testing and development and production.

If the nvidia-docker project is interested in making use of these I'd certainly be interested to help in any way I can.

**Comment by flx42** [comment]
Thank you @lsb, maybe we can add a link to your files on our wiki.
I think one of my colleague at NVIDIA also published a similar project on GitHub, I need to check with him too.

**Comment by ryanolson** [comment]
Thanks @lsb.  Good stuff.  I agree that automating the install of the driver, docker and nvidia-docker is a huge time savings when bring up one or multiple new servers.  

Here are the roles that my team has been using:

https://github.com/ryanolson/ansible-docker
https://github.com/ryanolson/ansible-nvidia-docker

These are available on Ansible Galaxy as well as Github.

We usually just run this script when we bring up a new machine:
https://github.com/ryanolson/bootstrap/blob/master/bootstrap.sh

Perhaps we should team up, as I have only been creating Ubuntu roles.  It would be great to extend them to support RHEL, CentOS, and beyond.

PS - I'm been putzing around with a driver role:
https://github.com/ryanolson/dl-bootstrap/tree/master/roles/ryanolson.nvidia-driver

**Comment by 3XX0** [comment]
Closing since this issue is related to provisioning rather than `nvidia-docker` itself
