### ISSUE TITLE
Can I add my own restful webService in the nvidia docker?

### ISSUE THREAD

**Issue by Qoboty** [NVIDIA/nvidia-docker#249]
I saw nvidia docker had its REST API, I want to add my own custom webService, Is that ok ?
How to add my c++ webService reflect to nvidia docker port 3476?
Thanks!

**Comment by flx42** [comment]
I don't understand what you are trying to do, you should be more precise.

**Comment by flx42** [comment]
Reopen when you can share more information, thanks.
