### ISSUE TITLE
A Container with Centos 6.7

### ISSUE THREAD

**Issue by cobie8a** [NVIDIA/nvidia-docker#25]
Would you guys happen to have one for Centos 6.7?  That's what I have running on enterprise right now and would love to run a few ML docker containers.

**Comment by flx42** [comment]
I pushed a Dockerfile for CUDA 7.5 based on CentOS 6.7. You can build the runtime and devel images with the following command:
`$ make OS=centos-6`
Please test it and give us your feedback!

**Comment by cobie8a** [comment]
thx felix.  it seems to work well.
