### ISSUE TITLE
Jobs directory for DIGITS v4

### ISSUE THREAD

**Issue by tehoro** [NVIDIA/nvidia-docker#252]
It looks to me as if the jobs directory for docker DIGITS v4 is the same as it was earlier - /usr/share/digits/digits/jobs

I find I need to include something like _-v digits-jobs:/usr/share/digits/digits/jobs_ in the nvidia-docker command, rather than  _-v digits-jobs:/jobs_ as stated for v3.3 and above at https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS

**Comment by flx42** [comment]
Oops, I think the Dockerfile has a bug, I'll fix it. Thanks for reporting!

**Comment by flx42** [comment]
Please test with new image.

**Comment by tehoro** [comment]
Yep - thanks!  That fixed it.  _-v digits-jobs:/jobs_ works for the latest nvidia/digits docker image.
