### ISSUE TITLE
Cannot run nvidia-docker without sudo

### ISSUE THREAD

**Issue by FabHan** [NVIDIA/nvidia-docker#253]
After installing nvidia-docker, I cannot call `nvidia-docker images` or `docker images` without sudo.

Here's some more information.
- `sudo gpasswd -a ${USER} docker` is unsuccessful with the message `gpasswd: group 'docker' does not exist in /etc/group`. 
- `sudo groupadd docker` --> group `docker` already exists ???
- `sudo gpasswd -a ${USER} nvidia-docker` is successful
- `groups` displays `fab sudo nvidia-docker`. 
- When I look at the files `/etc/passwd` and `/etc/group`, I only see `nvidia-docker` but no `docker`.

**Comment by flx42** [comment]
It doesn't seem to be a `nvidia-docker` problem, it's probably the same if you just try something like `docker ps` (without `nvidia-docker`).
