### ISSUE TITLE
libGL error: unable to load driver: swrast_dri.so

### ISSUE THREAD

**Issue by Dammi87** [NVIDIA/nvidia-docker#254]
This happens when I try to render in Maya inside a CentOS container. Is OpenGL not available to a CentOS image when using nvidia-docker?

I'm running a Ubuntu 14.04 with two old Titans as GPU. Im able to run Tensorflow with CUDA using the nvidia-docker, works like a charm! But now I want to do the same for rendering inside a docker running Maya.

I created a Docker image for easy recreation: [Docker Hub Link](https://hub.docker.com/r/dammi87/maya2016wcuda_docker/)
(NOTE, its Maya 2015, not 2016, did a typo)

The command I use to run the docker image is
`nvidia-docker run -it -v ~/Downloads:/Downloads -e "DISPLAY=unix$DISPLAY" -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" --privileged dammi87/maya2016wcuda_docker`

Now if you type "maya" you should see a Licence window popup. Now I dont need to run the full Maya GUI, I'm only interested in the CLI interface to Render with.

I'm pretty sure this issue is not Maya related, but it feels more like Ubuntu -> Centos Docker issue, but perhaps I am wrong :)

**Comment by 3XX0** [comment]
OpenGL is not supported at the moment, see #11

**Comment by hlzz** [comment]
@Dammi87 What is the OS of the host? I have succeeded in runing opengl programs in a centos docker on a ubuntu host, but not in the centos docker on a centos host. Don't know if that's the case for you.
