### ISSUE TITLE
Error in trying to run an nvidia-docker container

### ISSUE THREAD

**Issue by kohaugustine** [NVIDIA/nvidia-docker#255]
Hi,

I am having trouble running a command of this form:

`sudo nvidia-docker run -it --name <<CONTAINER_NAME>> -v "$(pwd)"/data:/home/raiuser/data -v "$(pwd)"/src:/home/raiuser/src/src <<IMAGE_NAME>>`

The `-v` additional volume bindings are necessary because I need to be developing code which I will then compile and test within docker container. When I run the entire command, the process also takes quite a long time. It will take a while before it just returns to me with this error:

`Error response from daemon: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Mount: dial unix /var/lib/nvidia-docker/nvidia-docker.sock: connect: no such file or directory`

I know that the container actually got created when I do `docker ps -a`. Its just that when I want to run the container that I run into this error.

I have already made sure that `nvidia-docker-plugin` is up and running when I am doing this. I have also made sure that I built my Docker image using `nvidia-docker` command. 

Also, last question about this is that, I noticed that ever since I have started running things with nvidia-docker, all my docker commands that I execute take a significantly longer time than before. Is this normal (I was using docker before without nvidia-docker, and it never took so long)? Does anyone know why? 
even the non-nvidia docker commands, just plain docker commands, take so much longer now.

Also, I don't know if this might be related to the issue, but for my docker setup, I have never created any user groups, so whenever I run docker, I need to run with sudo. So I have had to run all my nvidia-docker commands with sudo.

I really need to get the docker system up and running on my computer in order to complete a school related project soon in a month or so. Initially I didn't know about nvidia-docker and so I was only using docker, until I found out that when I was trying to do a nvprof of the program and had the error telling me it could not find any CUDA drivers. I then found out its because I did not make use of nvidia-docker after reading this page https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-driver#challenges and realized that somehow the Nvidia drivers folds on my system were not linked to the docker container, and that Nvidia-docker is supposed to help in this.

Thank you so much to anyone who can help in this!!!

**Comment by flx42** [comment]
Everything seems to be indicating that `nvidia-docker-plugin` is not running, or at least `docker` can't reach it.
Look at the logs for the docker daemon and nvidia-docker.
```
$ cat /var/log/upstart/docker.log
```
OR 
```
$ systemctl status docker
```
Same for `nvidia-docker`.

**Comment by kohaugustine** [comment]
Thank you very much for your quick reply. Here are the outputs, where machine-name is just a placeholder for my machine's name :

```
$ cat /var/log/upstart/docker.log
cat: /var/log/upstart/docker.log: No such file or directory

$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2016-11-23 20:14:49 CST; 2 days ago
     Docs: https://docs.docker.com
 Main PID: 990 (dockerd)
    Tasks: 32
   Memory: 80.0M
      CPU: 1min 48.947s
   CGroup: /system.slice/docker.service
           ├─ 990 /usr/bin/dockerd -H fd://
           └─1056 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var

Nov 25 22:03:11 machine-name dockerd[990]: time="2016-11-25T22:03:11.684328915-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:03:12 machine-name dockerd[990]: time="2016-11-25T22:03:12.685003540-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:03:14 machine-name dockerd[990]: time="2016-11-25T22:03:14.685550076-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:03:18 machine-name dockerd[990]: time="2016-11-25T22:03:18.686175672-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:03:26 machine-name dockerd[990]: time="2016-11-25T22:03:26.686700134-06:00" level=warning msg="9e770aea1569ad1ab7cf3853f581d178e6befc0229c4011d5757b25e3fa28d0d cleanup: Fail
Nov 25 22:03:26 machine-name dockerd[990]: time="2016-11-25T22:03:26.686811933-06:00" level=error msg="Handler for POST /v1.24/containers/9e770aea1569ad1ab7cf3853f581d178e6befc0229c40
Nov 25 22:04:00 machine-name dockerd[990]: time="2016-11-25T22:04:00.384952100-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:04:01 machine-name dockerd[990]: time="2016-11-25T22:04:01.385443323-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:04:03 machine-name dockerd[990]: time="2016-11-25T22:04:03.385961428-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD
Nov 25 22:04:07 machine-name dockerd[990]: time="2016-11-25T22:04:07.386462252-06:00" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeD

$ cat /var/log/upstart/nvidia-docker.log
cat: /var/log/upstart/nvidia-docker.log: No such file or directory

$ systemctl status nvidia-docker
● nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/lib/systemd/system/nvidia-docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Fri 2016-11-25 21:44:37 CST; 48min ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 32154 ExecStopPost=/bin/rm -f $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 32143 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 32133 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
  Process: 32132 ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR (code=exited, status=1/FAILURE)
 Main PID: 32132 (code=exited, status=1/FAILURE)

Nov 25 21:44:36 machine-name systemd[1]: nvidia-docker.service: Unit entered failed state.
Nov 25 21:44:36 machine-name systemd[1]: nvidia-docker.service: Failed with result 'exit-code'.
Nov 25 21:44:37 machine-name systemd[1]: nvidia-docker.service: Service hold-off time over, scheduling restart.
Nov 25 21:44:37 machine-name systemd[1]: Stopped NVIDIA Docker plugin.
Nov 25 21:44:37 machine-name systemd[1]: nvidia-docker.service: Start request repeated too quickly.
Nov 25 21:44:37 machine-name systemd[1]: Failed to start NVIDIA Docker plugin.
```

One thing I must mention is that because I need to run all docker commands with sudo, the first time I ran `nvidia-docker-plugin`, I was unable to run it fully - it had to stop halfway due to a permission error. Then the next time I tried running the plugin, I kept getting error saying that the port was already taken. When I do a netstat listing, I saw that an nvidia-docker plugin was still running. I tried to kill it, but each time after I kill it, it would reappear again. Eventually I was able to try something funny, I killed it and very quickly, respawn the nvidia-docker-plugin process with sudo so that I can run it properly. So it worked when I did it, and I was able to terminate the process properly with CTRL-C. Previously, while I got errors telling me the permission was denied, somehow the plugin was still running, and would restart itself each time I kill it.

**Comment by flx42** [comment]
That sounds messy. You don't need to run `nvidia-docker-plugin` if you install `nvidia-docker` through a package, it should start automatically. If it doesn't you should try to understand why, but not try to kill or overwrite what systemd is doing.

I would uninstall `nvidia-docker`, `rm -rf /var/lib/nvidia-docker`, reboot, reinstall `nvidia-docker` and then check `journalctl -n -u nvidia-docker` to see why it didn't start.

**Comment by kohaugustine** [comment]
Yes I know it got quite messy. I am still new to Docker so thank you for your patience. Oh would Nvidia-docker start by itself automatically in my case? I was sure that I had no other nvidia-docker running process at the time when this was happening though.

All I did to install nvidia-docker was exactly following the instructions on the front page of the Github repo for Ubuntu distributions. so I didn't use apt-get or any other package manager. As you suggested to uninstall nvidia-docker, do you know what will be a certain and clean way to ensure I uninstall it correctly?

Thank you.

**Comment by flx42** [comment]
> Oh would Nvidia-docker start by itself automatically in my case?

Yes, if you installed using the `deb` package, it will be started by systemd.

> I was sure that I had no other nvidia-docker running process at the time when this was happening though.

Sure, because it failed to start, and that's your problem.

> All I did to install nvidia-docker was exactly following the instructions on the front page of the Github repo for Ubuntu distributions.

Not really, for Ubuntu we don't mention running `nvidia-docker-plugin` manually :)

>  As you suggested to uninstall nvidia-docker, do you know what will be a certain and clean way to ensure I uninstall it correctly?

Try the following:
```
$ dpkg --purge nvidia-docker
$ rm -rf /var/lib/nvidia-docker
```
Then reboot/reinstall.

**Comment by flx42** [comment]
@kohaugustine did it work?

**Comment by kohaugustine** [comment]
@flx42  Thank you for checking. I was about to reply you, that I didn't try further after uninstalling nvidia-docker, because someone in the course released a bunch of procedures for compiling and testing with CMake. As deadlines are near, we need to get started on developing asap and won't have the time to try further with nvidia-docker unfortunately. Thank you very much for your help though! I'll save our post and it'll help next time when I need to set up nvidia-docker for a project.

**Comment by kohaugustine** [comment]
@flx42 Thank you for checking. I was about to reply you, that I didn't try further after uninstalling nvidia-docker, because someone in the course released a bunch of procedures for compiling and testing with CMake. As deadlines are near, we need to get started on developing asap and won't have the time to try further with nvidia-docker unfortunately. Thank you very much for your help though! I'll save our post and it'll help next time when I need to set up nvidia-docker for a project.

**Comment by varun-suresh** [comment]
I had a similar problem. Uninstalling and re-installing worked. Thanks!

**Comment by kelvinxu** [comment]
Hi @flx42

I am having a similar problem to the one originally posted here.

```
$ nvidia-docker
nvidia-docker | 2017/09/19 18:46:49 Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/version: dial unix /var/run/docker.sock: connect: permission denied
```

Actually, my original problem is that I am using Ubuntu 17.04, and had trouble using the official deb. I followed the advice in #412 and installed the deb built by #234, which led me here.

Posting the above diagnostic test:

```
$:~/Downloads$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-09-19 18:41:30 PDT; 11min ago
     Docs: https://docs.docker.com
 Main PID: 1894 (dockerd)
    Tasks: 60
   Memory: 92.5M
      CPU: 1.316s
   CGroup: /system.slice/docker.service
           ├─1894 /usr/bin/dockerd -H fd://
           └─1920 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/l

Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.694586840-07:00" level=warning msg="Your kernel does not support swap memory limit"
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.694642003-07:00" level=warning msg="Your kernel does not support cgroup rt period"
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.694652714-07:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.694961402-07:00" level=info msg="Loading containers: start."
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.877476953-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.927490821-07:00" level=info msg="Loading containers: done."
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.998081595-07:00" level=info msg="Daemon has completed initialization"
Sep 19 18:41:29 machine-name dockerd[1894]: time="2017-09-19T18:41:29.998111822-07:00" level=info msg="Docker daemon" commit=cec0b72 graphdriver=aufs version=17.06.2-ce
Sep 19 18:41:30 machine-name dockerd[1894]: time="2017-09-19T18:41:30.009521177-07:00" level=info msg="API listen on /var/run/docker.sock"
Sep 19 18:41:30 machine-name systemd[1]: Started Docker Application Container Engine.
$:~/Downloads$ systemctl status nvidia-docker
● nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/lib/systemd/system/nvidia-docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-09-19 18:43:10 PDT; 10min ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 3484 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 3460 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
 Main PID: 3459 (nvidia-docker-p)
    Tasks: 8 (limit: 19660)
   Memory: 42.8M
      CPU: 599ms
   CGroup: /system.slice/nvidia-docker.service
           └─3459 /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker

Sep 19 18:43:10 machine-name systemd[1]: Starting NVIDIA Docker plugin...
Sep 19 18:43:10 machine-name nvidia-docker-plugin[3459]: /usr/bin/nvidia-docker-plugin | 2017/09/19 18:43:10 Loading NVIDIA unified memory
Sep 19 18:43:10 machine-name nvidia-docker-plugin[3459]: /usr/bin/nvidia-docker-plugin | 2017/09/19 18:43:10 Loading NVIDIA management library
Sep 19 18:43:10 machine-name nvidia-docker-plugin[3459]: /usr/bin/nvidia-docker-plugin | 2017/09/19 18:43:10 Discovering GPU devices
Sep 19 18:43:10 machine-name systemd[1]: Started NVIDIA Docker plugin.
Sep 19 18:43:11 machine-name nvidia-docker-plugin[3459]: /usr/bin/nvidia-docker-plugin | 2017/09/19 18:43:11 Provisioning volumes at /var/lib/nvidia-docker/volumes
Sep 19 18:43:11 machine-name nvidia-docker-plugin[3459]: /usr/bin/nvidia-docker-plugin | 2017/09/19 18:43:11 Serving machine-name API at /var/lib/nvidia-docker
Sep 19 18:43:11 machine-name nvidia-docker-plugin[3459]: /usr/bin/nvidia-docker-plugin | 2017/09/19 18:43:11 Serving remote API at localhost:3476
```

Thanks
