### ISSUE TITLE
Unsupported CUDA version: driver 0.0 < image 8.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by Quintasan** [NVIDIA/nvidia-docker#257]
Hi, I'm trying to get anything running using `nvidia-docker` on my ThinkPad T430 (NVIDIA Corporation GF108M [NVS 5400M] (rev a1)).

Here's is what I did (this a clean install, nothing more):
1. Install Ubuntu 16.04
2. Install `nvidia-375` from [graphic-drivers ppa](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa)
3. Install `nvidia-modprobe`
4. Install `nvidia-docker` from deb package

nvidia-smi
```
Tue Nov 29 17:51:54 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.20                 Driver Version: 375.20                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  NVS 5400M           Off  | 0000:01:00.0     N/A |                  N/A |
| N/A   55C    P8    N/A /  N/A |    232MiB /   993MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```

nvidia-docker run --rm nvidia/cuda nvidia-smi
```
nvidia-docker | 2016/11/29 17:50:59 Error: unsupported CUDA version: driver 0.0 < image 8.0
```

It appears that `nvidia-docker.service` is not running. When I tried starting it with `sudo systemctl start nvidia-docker.service` it failed with the following message (from `journalctl -xe`):

```
lis 29 17:51:46 tyria nvidia-docker-plugin[3884]: /usr/bin/nvidia-docker-plugin | 2016/11/29 17:51:46 Loading NVIDIA unified memory
lis 29 17:51:46 tyria nvidia-docker-plugin[3884]: /usr/bin/nvidia-docker-plugin | 2016/11/29 17:51:46 Loading NVIDIA management library
lis 29 17:51:46 tyria nvidia-docker-plugin[3884]: /usr/bin/nvidia-docker-plugin | 2016/11/29 17:51:46 Discovering GPU devices
lis 29 17:51:46 tyria nvidia-docker-plugin[3884]: /usr/bin/nvidia-docker-plugin | 2016/11/29 17:51:46 Error: cuda: CUDA driver version is insufficient for CUDA runtime version
```

What am I doing wrong?

**Comment by flx42** [comment]
First of all, this is GPU architecture is now marked as deprecated in [CUDA 8.0](http://docs.nvidia.com/cuda/cuda-toolkit-release-notes/#deprecated-feature). In the next CUDA version, you won't be able to compile CUDA code for your architecture.
It also means `NVML` (one of the library we use) might not work very well with this architecture.

But anyway, you shouldn't install the drivers with the ppa, you should install the [official drivers](http://www.nvidia.com/object/unix.html). You should try that first.

**Comment by Quintasan** [comment]
@flx42 Any particular reason for not using that PPA? The version does match. I'll report back when I'm done with reinstalling them.

**Comment by Quintasan** [comment]
Welp, after installing drivers from the binary I managed to get the nvidia-docker running but my X server is no longer functioning. As it stands I have wasted over 3 days trying to get this working only to end up with with a subpar solution.

**Comment by flx42** [comment]
You can try `nvidia-xconfig`.

**Comment by flx42** [comment]
@Quintasan I stumbled into the same problem with the PPA actually, you just need to install an extra package: `libcuda1-375`

**Comment by 3XX0** [comment]
Generally we don't recommend installing the driver from third party PPAs.
The official way of installing the CUDA driver is described in #258
