### ISSUE TITLE
minimal .deb to use for CUDA drivers + host driver files

### ISSUE THREAD

**Issue by AndrewLeungNetflix** [NVIDIA/nvidia-docker#258]
I'm looking for suggestions on a minimal (i.e., few additional dependencies) .deb file to use to install the CUDA driver and host driver files.

Today, we're using the NVIDIA docker plugin (which is great, BTW) on AWS P2 instance types and would like a .deb package that is bring in nvidia-361 and the host driver files that are needed for the docker plugin. We're using both Ubuntu 14.04 and 16.04. Thanks!

**Comment by 3XX0** [comment]
You can use the driver provided by [CUDA](https://developer.nvidia.com/cuda-downloads)
Simply install the network deb for your platform and then `apt-get install nvidia-<version>`

**Comment by AndrewLeungNetflix** [comment]
Thanks.

**Comment by 3XX0** [comment]
Note that you might want to use `--no-install-recommends`.

If you want to setup a headless node with no GLX dependencies (e.g. you rely EGL or just use CUDA) your are better off using the [driver runfiles](http://www.nvidia.com/object/unix.html) in advanced mode.

**Comment by flx42** [comment]
For instance, `--no-opengl-files` might be an advanced option you want to use.
