### ISSUE TITLE
Add support for Debian 8 jessie\Debian Stretch

### ISSUE THREAD

**Issue by GDApsy** [NVIDIA/nvidia-docker#261]
It will be great if docker-nvidia will support Debian.  For example Debian base for importnat project: NeuroDebian(http://neuro.debian.net/), also Debian is base for Linux Ubuntu. As  i can see problem with ubuntu package on Debian 8\9 on postinstall step(creating user account as i can see).

**Comment by flx42** [comment]
What's the problem? is it different than #242? (sysV support)

**Comment by GDApsy** [comment]
Probably my bug duplicate #242. Solve problem after full delete of files from package except dpkg-related scripts and reinstall package
