### ISSUE TITLE
using sudo with nvidia-docker

### ISSUE THREAD

**Issue by elliotekoch** [NVIDIA/nvidia-docker#263]
I'm still debugging my setup. Running some basic Linux stuff but seeing some puzzling results. 

running a simple ls command:
sudo nvidia-docker run -it -p 8888:8888 -p 6006:6006 floydhub/dl-docker:digits ls /localhome
ls: cannot access /localhome: No such file or directory

of course it runs okay at command line 
 ls /localhome
bill9000

That's odd.  I'm using sudo, so may be that's not the right thing to do....
 sudo nvidia-docker run -it -p 8888:8888 -p 6006:6006 floydhub/dl-docker:digits whoami
[sudo] password for bill9000: 
root
Oh that's really not good. I should have  guessed that was the case.

Try nvidia docker without sudo
nvidia-docker run -it -p 8888:8888 -p 6006:6006 floydhub/dl-docker:digits whoami
nvidia-docker | 2016/12/06 08:26:45 Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Suggestions? Is there a way at all to engage docker and nvidia docker without sudo?

**Comment by flx42** [comment]
Your problems are unrelated to `nvidia-docker`. Try with `docker` as the base command and you will have the same problems.

I invite you to look into what Docker does, and it will explain what you're seeing. Especially, for the last problem, you need to add yourself to the [docker group](https://docs.docker.com/engine/installation/linux/ubuntulinux/#/manage-docker-as-a-non-root-user)

**Comment by elliotekoch** [comment]
Thanks Felix :-)
