### ISSUE TITLE
Recommended way to restart plugin?

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#264]
What's the best way to restart the `nvidia-docker-plugin` process?

I want to restart the plugin after editing the default settings in `/etc/default/nvidia-docker`, [as documented in the wiki](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#usage). 

Currently I've been just reinstalling the plugin from the `deb` file. This accomplishes what I want, but I'm guessing there must be a better way...

**Comment by flx42** [comment]
`sudo restart nvidia-docker`

**Comment by grisaitis** [comment]
Thank you!
