### ISSUE TITLE
About using official docker to make GPU isolation

### ISSUE THREAD

**Issue by wangchuan** [NVIDIA/nvidia-docker#265]
Due to some reasons, I am only allowed to use official `docker` instead of `nvidia-docker` in my program. However I have to get GPU access in my docker container. I read the wiki `GPU isolation` [here](https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation), and guess the last paragraph is related to my problem, i.e.

> Alternatives
> 
> If you don’t want to use the nvidia-docker wrapper, you can add the command-line arguments manually:
> 
> `$ docker run --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0`
>
> This needs to be used in combination with the command-line arguments for mounting the volume containing the the user-level driver libraries. Listing the available GPUs can be done using nvmlDeviceGetCount from NVML or cudaGetDeviceCount from the CUDA API. We recommend using NVML since it also provides nvmlDeviceGetMinorNumber to find the device file to mount. Having a correct mapping between the device file and the isolated GPU is essential if you want to gather utilization metrics using NVML or nvidia-smi. If you still want to use the CUDA API, be sure to unset the environment variable CUDA_VISIBLE_DEVICES, otherwise some GPUs on the system might not be listed.

Currently in my docker container, I can load cuda libraries, but the GPU devices cannot be seen. For example, when I launch a TensorFlow program, it will print out the following errors:

```
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUresult(-1)
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 19ae2ab77bf2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 19ae2ab77bf2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got "1"
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
```
Either I cannot use `nvidia-smi` in the container. 

Could the author provide some more detailed instructions about how to mount the drivers in the docker container? @3XX0

**Comment by flx42** [comment]
The wiki also explains this [here](https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-driver), did you read this section? You need to mount a few libraries from the host.

**Comment by flx42** [comment]
Closing, let us know if you have other questions.
