### ISSUE TITLE
Prune existing tags

### ISSUE THREAD

**Issue by flx42** [NVIDIA/nvidia-docker#268]
We would like to automate the build of our images soon. It's also a good time to prune some of the existing tags that don't seem to be used and only add noise/confusion to our DockerHub page. We have so many images that the "Tags" page on DockerHub is truncated.

Because we have OS suffixes, each superfluous tag we currently have creates **5** images on the DockerHub!
For instance, if we remove the `cudnn` tag, the following images will be removed:
```
nvidia/cuda:cudnn
nvidia/cuda:cudnn-centos6
nvidia/cuda:cudnn-centos7
nvidia/cuda:cudnn-ubuntu14.04
nvidia/cuda:cudnn-ubuntu16.04
```

I think, without too much arguing, that we can already remove the following base tags:
```
cuda:devel
cuda:runtime
cuda:cudnn
cuda:cudnn-devel
cuda:cudnn-runtime
```
I don't think anyone really uses a base image without actually pinning the version. `cuda:latest` should stay because it's useful for testing reasons after installing `nvidia-docker`.
We could go one small step further and and also remove the version tags without the `devel/runtime` qualifier:
```
cuda:8.0
cuda:7.5
cuda:7.0
cuda:6.5
```
I think that would be a good start.

@3XX0: thoughts?

**Comment by lukeyeager** [comment]
Agreed. It's hard to tell what's actually available when the list is [this long](https://hub.docker.com/r/nvidia/cuda/tags/) (and unsorted, to boot!).

And [it doesn't look like](http://stackoverflow.com/q/31251356/2404152) listing all images in a registry through the CLI is as simple as I would have thought.

**Comment by flx42** [comment]
@lukeyeager are you ready for some httpie/jq magic?
```
TOKEN=$(http 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:nvidia/cuda:pull' | jq -r '.token')
http https://index.docker.io/v2/nvidia/cuda/tags/list Authorization:"Bearer $TOKEN"
```

**Comment by lukeyeager** [comment]
^ not simple :stuck_out_tongue:

**Comment by flx42** [comment]
@3XX0 ping?

**Comment by 3XX0** [comment]
Yeah I think this is reasonable, there are way too many tags it's confusing.
It will be a breaking change but I think it's ok to remove:

```
cuda:8.0[-os]
cuda:7.5[-os]
cuda:7.0[-os]
cuda:6.5[-os]
cuda:devel[-os]
cuda:runtime[-os]
cuda:cudnn[-os]
cuda:cudnn-devel[-os]
cuda:cudnn-runtime[-os]
```

Also let's bump the default operating system for CUDA 8.0 to the latest LTS. Ideally `latest` should be `8.0-devel-ubuntu16.04`

**Comment by flx42** [comment]
Good, I will push new images today and remove the old tags. I will keep `latest` on trusty for now, I will probably change this when we get caffe/DIGITS on xenial, or when we (finally) automate the build/push.
