### ISSUE TITLE
nvidia-docker | 2016/12/17 05:23:46 Error: nvml: Driver/library version mismatch

### ISSUE THREAD

**Issue by soumenms2015** [NVIDIA/nvidia-docker#270]
Hello, 
When I run sudo nvidia-docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow:latest-gpu then I get the above mentiond error message.

**Comment by 3XX0** [comment]
Your driver is in a bad state, I suggest you reinstall it and reboot the system

**Comment by flx42** [comment]
@soumenms2015 did you fix your problem?
