### ISSUE TITLE
What could be the login password for running jupyter after running in docker container

### ISSUE THREAD

**Issue by soumenms2015** [NVIDIA/nvidia-docker#271]
I am running the tensorflow in docker container. When I tried to use localhost:8888 in browser then it is asking login password . what is the login password?

**Comment by 3XX0** [comment]
The tensorflow image exposes a Jupyter server on `:8888` and the password is set through the environment variable `PASSWORD` (see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/jupyter_notebook_config.py)), I suggest you set it on the command line with `docker run -e PASSWORD=<yourpassword>`. If you want to access Tensorboard instead, it is available on port `6006`.

**Comment by 3XX0** [comment]
Closing since this is not a `nvidia-docker` issue
