### ISSUE TITLE
uninstalling incorrectly:while trying to uninstall nvidia-docker, it gets messy!

### ISSUE THREAD

**Issue by ungentilgarcon** [NVIDIA/nvidia-docker#272]
uninstalling incorrectly:while trying to uninstall nvidia-docker, it gets messy!
I'm on Jessie + backports

Purging NVIDIA volumes
list nvidia-docker: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.List: dial unix /var/lib/nvidia-docker/nvidia-docker.sock: connect: no such file or directory
Error response from daemon: get nvidia_driver_370.28: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Get: dial unix /var/lib/nvidia-docker/nvidia-docker.sock: connect: no such file or directory
Failed to remove NVIDIA volumes, ignoring
dpkg: erreur de traitement du paquet nvidia-docker (--purge) :
 le sous-processus script pre-removal installé a retourné une erreur de sortie d'état 102
Des erreurs ont été rencontrées pendant l'exécution :
 nvidia-docker
E: Sub-process /usr/bin/dpkg returned an error code (1)

I deleted all docker containers and removed docker, yet i get an error, don't know where to delete the reference to  an nvidia-docker container in order to remove it well..

**Comment by 3XX0** [comment]
I'm not sure how this happened, maybe dpkg on debian is checking the `PIPESTATUS`?

In any case, the error comes from the fact that we are trying to cleanup the volumes when uninstalling `nvidia-docker`. As long as you have `docker` and `nvidia-docker-plugin` running while removing the package the uninstall shouldn't fail.

**Comment by 3XX0** [comment]
After investigation this appears to be a [debian issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747851).
This should be fixed with `init-system-helpers` > v1.28.

**Comment by ungentilgarcon** [comment]
Well, glad to now it will be corrected, yet the package is still in an uncorrectable state as for now -can't switch to this unstable version of udev now

**Comment by linuxluser** [comment]
`init-system-helpers` is currently at version 1.22 on Debian 8 (https://packages.debian.org/source/stable/init-system-helpers). While upgrading to Debian testing or unstable fixes the issue, many are not in such a position. This can't be the only way to fix this.

What I did for my systems is patch the .deb package and add my own SysV init script to it. This allows the package to install without a problem and allows me to use non-systemd (or non-upstart) systems.

**Comment by aa1607** [comment]
hi there an answer to this?
there really should be a one command to remove nvidia-docker listed on the terminal site. It shouldn't be a struggle to restart the installation from scratch.
