### ISSUE TITLE
docker: Error response from daemon: create nvidia_driver_367.57: create nvidia_driver_367.57: Error looking up volume plugin nvidia-docker: plugin not found. See 'docker run --help'.

### ISSUE THREAD

**Issue by maxenko** [NVIDIA/nvidia-docker#273]
This happens every time nvidia-docker is run such as:
nvidia-docker run --rm nvidia/cuda nvidia-smi

Please advise.
Linux Mint 18 running nvidia-367.57 for ubuntu 16.04.1
Docker version 1.12.1, build 23cf638

Runs fine after sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log

**Comment by 3XX0** [comment]
This is expected, `nvidia-docker` requires `nvidia-docker-plugin` to be running on the machine.

**Comment by maxenko** [comment]
Got it, thank you.

**Comment by darrylbobo** [comment]
@maxenko 
I am running CentOS, and also running into the same issue using nvidia-docker. 
By using your suggestion, I solved the problem. But, I would like to know where you found the solution? And, I want to know why it works. 

Thanks

**Comment by maxenko** [comment]
@darrylbobo its just a command to install the plugin which is required to run nvidia/cuda in docker. I found it in documentation for nvidia/docker.
