### ISSUE TITLE
Where is nvidia-smi?

### ISSUE THREAD

**Issue by enochtsang** [NVIDIA/nvidia-docker#274]
Hey I'm working on making some personal edits but I have a question about the build process.

The centos nvidia-smi Dockerfile just runs the `nvidia-smi` command, but after building the nvidia-docker/centos-6/cuda/8.0/runtime image, I can't find the `nvidia-smi` binary anywhere in the built image if I run it interactively. How does this build process to work? I was thinking the `FROM cuda` was from some built image like nvidia-docker/centos-6/cuda/8.0/runtime but it seems that is not the case.

**Comment by 3XX0** [comment]
This is the case, however `nvidia-smi` is special because it depends on the driver and hence is mounted at runtime (see [documentation](https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-driver))

**Comment by enochtsang** [comment]
Ah ok, thanks. I seem to having the same issue as #250 now though.
