### ISSUE TITLE
cannot run cuda code in home made docker

### ISSUE THREAD

**Issue by jmaronas** [NVIDIA/nvidia-docker#277]
I have just create my own nvidia-docker to understand how it works and i found the next issue. I create a dockerFile (named mydocker) just like:

#########(begin file)(this line is not part of the file)
FROM ubuntu:16:04
#########(end file)(this line is not part of the file)
and then just run:
nvidia-docker build -f mydocker . 

With the container created and rename it as ubuntu16 I have install everything need for using theano: python, python-devel, libblas-dev... And then commit the result of the docker. After this I have install the CUDA-8.0 toolkit. Then as I have seen on some reports I launched my docker image as:

user@machine:~$ ls -la /dev/ | grep nvidia
crw-rw-rw-   1 root root    195,   0 dic 15 10:51 nvidia0
crw-rw-rw-   1 root root    195, 255 dic 15 10:51 nvidiactl
crw-rw-rw-   1 root root    195, 254 dic 15 10:51 nvidia-modeset
crw-rw-rw-   1 root root    241,   0 dic 15 10:51 nvidia-uvm

user@machine:~$ nvidia-docker run -it --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-modeset:/dev/nvidia-modeset --device /dev/nvidia-uvm:/dev/nvidia-uvm  ubuntu16

Having everything installed and env sets (LD_LIBRARY_PAT=/usr/local/cuda-8.0/lib64 ...) and so on I just lunch python import theano and get:

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version)

I am not able of executing nvidia-smi or any other stuff related to drivers (i can ran nvcc perfectly). My driver version is   370.28  which is enough for cuda-8.0. Any idea? 

As I have seen in other places like here https://github.com/NVIDIA/nvidia-docker/issues/24 I should use nvidia-docker (and i do).

Now i have solved just doing (other found images on the hub did not have the nvcc installed): 

nvidia-docker run -it nvidia/cuda:8.0

But I am interested in knowing how to solve the other way (or maybe it is a problem you could fix). This nvidia/cuda:8.0 is under ubuntu14 and I would like to use ubuntu16.

Thanks

**Comment by flx42** [comment]
> nvidia-docker run -it --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-modeset:/dev/nvidia-modeset --device /dev/nvidia-uvm:/dev/nvidia-uvm ubuntu16

You don't need to mount the devices manually, `nvidia-docker` does that automatically, **if the Docker image is a GPU image.** To know if an image is a GPU image, we check the presence of the label `com.nvidia.volumes.needed`. This is explained on our [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection#nvidia-docker).
Look at one of our [Dockerfile](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-16.04/cuda/8.0/runtime/Dockerfile#L4), if you want to use a custom image (instead of `nvidia/cuda`), you need to use this label. We also have a label to verify the CUDA version.

> But I am interested in knowing how to solve the other way (or maybe it is a problem you could fix). This nvidia/cuda:8.0 is under ubuntu14 and I would like to use ubuntu16.

We have images for Ubuntu 16.04 too! Try using the `-ubuntu16.04` suffix, for instance: `nvidia/cuda:8.0-ubuntu16.04`.

**Comment by flx42** [comment]
By the way, seems to be the same problem as the previous issue that was just filed: #276

**Comment by jmaronas** [comment]
Yes thank you, I have just found the dockerfile for ubuntu16 in your repo and installing it .
Now i understand how can I create my own images.
By the way, maybe put how to install the ubuntu16.04 as you put here in your wiki could be useful for others as i directly wget the dockerfile and manually build.

**Comment by flx42** [comment]
You are right, we should also edit the DockerHub page, you are not the first one to be confused by this. 
DockerHub is also truncating the list of tags it's showing because we have too many, so that's not helping either.
