### ISSUE TITLE
Install nvidia driver report compile error on Linux kernel 4.9.0

### ISSUE THREAD

**Issue by ziqingzhu** [NVIDIA/nvidia-docker#279]
When i install nvidia driver on Centos7 with kernel 4.9.0, the install script is NVIDIA-Linux-x86_64-367.48.run, it show some compile error, attachment is the full log

Dose nvidia driver not support Linux Kernel 4.x ? or maybe I should use newer driver install script?
[nvidia-installer.txt](https://github.com/NVIDIA/nvidia-docker/files/678181/nvidia-installer.txt)

**Comment by 3XX0** [comment]
This is a driver issue independent of `nvidia-docker`. I suggest you report this on the [support forums](https://forums.geforce.com/default/board/33/geforce-drivers/)
