### ISSUE TITLE
Successfully running container with nvidia drivers but unable to use those drivers

### ISSUE THREAD

**Issue by Redshift92** [NVIDIA/nvidia-docker#281]
Good evening, 
I am successfully running a container through nvidia-docker, here the output of nvidia-smi inside the container:

    lorenzo@a72ba8cced9f:/$ nvidia-smi 
    Sat Dec 31 14:17:36 2016
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  GeForce GTX 960M    Off  | 0000:01:00.0     Off |                  N/A |
    | N/A   46C    P8    N/A /  N/A |      0MiB /  2002MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
                                                                               
    +-----------------------------------------------------------------------------+
    | Processes:                                                       GPU Memory |
    |  GPU       PID  Type  Process name                               Usage      |
    |=============================================================================|
    |  No running processes found                                                 |
    +-----------------------------------------------------------------------------+

but when I try running glxgears I get:

    lorenzo@a72ba8cced9f:/$ glxgears 
    libGL error: pci id for fd 4: 8086:191b, driver (null)
    libGL error: No driver found
    libGL error: failed to load driver: (null)
    libGL error: failed to open drm device: No such file or directory
    libGL error: failed to load driver: i965

despite:

    lorenzo@a72ba8cced9f:/$ echo $PATH
    /opt/ros/indigo/bin:/usr/local/nvidia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    lorenzo@a72ba8cced9f:/$ echo $LD_LIBRARY_PATH
    /opt/shared/catkin_ws/devel/lib:/opt/ros/indigo/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

Thank you in advance

**Comment by 3XX0** [comment]
Unfortunately, OpenGL is not officialy supported for now (see #11). Only CUDA is supported.
