### ISSUE TITLE
error in wiki - remove command line arg

### ISSUE THREAD

**Issue by davidmann4** [NVIDIA/nvidia-docker#282]
![image](https://cloud.githubusercontent.com/assets/1736570/21582718/d031ee52-d063-11e6-9824-5d3b09f77166.png)

seems with this commit you guys added an AMI line to the wiki:
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2/_compare/444e77fdb3ff8f47d3b3bed0ad6069500713b735...9324ed6b320cdf7bfbc84df2ef3f770235def4df

jsut remove it and the command will work ( --amazonec2-ami ami-a9d276c9 \ )
(or give me rights to edit wiki)

**Comment by flx42** [comment]
Last time I tried EC2, it gave me ubuntu 15.10 by default without specifying an AMI, can you check if it's still the case?

**Comment by davidmann4** [comment]
Hmm I see, it makes sense to provide an AMI in the examples to avoid problems with differnet versions of the os in the future. 

The AMI form the wiki doc gave me the error which you can see in my attached screenshot above.

**Comment by flx42** [comment]
Are you using a different EC2 region? It works fine for me.
I just updated the AMI ID to a newer one.

**Comment by davidmann4** [comment]
ahh maybe that is the issue! I use frankfurt region.

**Comment by flx42** [comment]
Ok, I think I will just document this then. I don't want to remove the AMI, I don't want users to end up with Ubuntu 15.10. Thanks!
