### ISSUE TITLE
ssh cuda container can't log in

### ISSUE THREAD

**Issue by ismaeIfm** [NVIDIA/nvidia-docker#283]
Hi, I'm configuring a container suitable for deep learning experiments. One important feature that this container needs is access through ssh, so I searched it and found this: https://docs.docker.com/engine/examples/running_ssh_service/

Everything in the example works fine, but when I change the FROM instruction from ubuntu:16.04 to nvidia/cuda:8.0-cudnn5-devel, and build another image, I can't access through ssh to a newly created container, although the daemon is running, it seems that root password hasn't changed.

I don't know what might be the issue, I thought that cuda:8.0-cudnn5-devel was basically an ubuntu image with nvidia stuff pre-installed.

**Comment by flx42** [comment]
The CUDA image you're using is based on `ubuntu:14.04`, use `nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04` instead.

**Comment by ismaeIfm** [comment]
Thanks man, I hadn't noticed.
