### ISSUE TITLE
Failed to initialize NVML: Insufficient Permissions

### ISSUE THREAD

**Issue by tobiasstrauss** [NVIDIA/nvidia-docker#284]
Hi,

I setup a fresh system to install nvidia-docker. It was easy to install and worked well for some days. Strangely, I cannot execute nvidia-docker as non-root user since yesterday. This is the error message:

> nvidia-docker run --rm nvidia/cuda nvidia-smi
> nvidia-docker | 2017/01/06 20:03:02 Error: nvml: Insufficient Permissions  

As root, everything works fine. The solution seems easy: just setting the correct permission. But which files? 

The operating system is openSUSE Leap 42.2

Thanks for any hint. 

Tobias

**Comment by flx42** [comment]
- Are you using SELinux?
- Can you check the output of `getcap /usr/bin/nvidia-docker-plugin`? See [here](https://github.com/NVIDIA/nvidia-docker/blob/e0aae98a092e78020d9256c815a4a2a629ab4556/tools/build/rpm/SPECS/nvidia-docker.spec#L56)
- Can you run `nvidia-smi` on the host?

**Comment by tobiasstrauss** [comment]
>    Are you using SELinux?

no
>    Can you check the output of getcap /usr/bin/nvidia-docker-plugin?

There no output or better the output is the empty-string.
> Can you run nvidia-smi on the host?

Hmm. Similar behavior. As root I can. Non-root users can't. This probably means, that this is a general driver problem and not a problem of nvidia-docker, right?

**Comment by flx42** [comment]
> This probably means, that this is a general driver problem and not a problem of nvidia-docker, right?

Yes, correct. But I'm not sure what could have changed here.

**Comment by tobiasstrauss** [comment]
Thanks. I'll close this thread since this is not the right place for this question.

**Comment by JonShelley** [comment]
I hit the same issue. It was due to me limiting which devices which could be accessed by using the cgroup device subsystem where I launched the command. Once I removed the restriction on which gpus were available the error went away.

**Comment by icemansina** [comment]
@JonShelley  I met the same problem, but I cannot understand your solution clearly. Could you please give a more concrete explanation?

**Comment by Shaofanl** [comment]
Same problem here. @tobiasstrauss Did you solve that?

**Comment by tobiasstrauss** [comment]
no! not really. I accepted start nvidia-docker with sudo :-( Finally I started to use the native installation of cuda.

**Comment by JonShelley** [comment]
@icemansina what I was doing is using the  cgroups device subsystem to limit which GPUs the session had access to (i.e. /sys/fs/cgroups/devices/.../devices.allow). If there were multiple GPUs on the system but I only added one of the GPUs to devices.allow then I would get the error.

**Comment by icemansina** [comment]
@JonShelley Thanks a lot for your reply. 
I think my problem occurs as some dependencies are broken.
Finally, I solved this problem by firstly 
sudo apt-get --purge remove nvidia*
sudo apt-get autoremove --purge nvidia-*

And then reinstall the cuda toolkit through *.deb file rather than *.run file.  Hope it works for others.

**Comment by Shaofanl** [comment]
In my case, It didn't help to purge and then reinstall with the *.run file. I fixed it with `sudo apt-get install cuda-8-0` after purging the previous package. I think there are some dependency corruption in my case.

**Comment by colinlaney** [comment]
The error [occurs](https://stackoverflow.com/questions/52507744/enable-nvidia-smi-permissions-to-be-run-by-all-users) after the installation of VirtualGL and really doesn't related to nvidia-docker. But if this is your case, add your user to `vglusers` group on the host with

```bash
sudo usermod -aG vglusers <user>
```

**Comment by ycpss91255** [comment]
I successfully fixed this in my container
Methods as below
Add in Dockerfile
```
echo "vglusers:x:1001:${USER} >> /etc/group
```
---
There is only one thing that is confusing at present is whether there is a variable with the content of 1001 in the system variables
