### ISSUE TITLE
Could not load UVM kernel module [centos 7]

### ISSUE THREAD

**Issue by eromoe** [NVIDIA/nvidia-docker#291]
I have a server with gtx 1080 for some machine learning works.
Today I download serveral dockerfile and built them(at this time , nvidia driver is correct and  cuda works ),  at some time, I can not ping it . After restarte it, I soon got error:
```
[root@localhost ~]# nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2017/01/16 16:55:02 Error: Could not load UVM kernel module

[root@localhost ~]# nvidia-smi
modprobe: FATAL: Module nvidia not found.
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Comment by flx42** [comment]
Hello,

This doesn't seem to be related to `nvidia-docker`, it looks you have a problem with your driver installation. You should try to do a clean installation of the driver (or the system), if it still doesn't work, you should seek help on the [NVIDIA developer forum](https://devtalk.nvidia.com/), thank you!
