### ISSUE TITLE
nvidia-docker and nvidia-docker-plugin

### ISSUE THREAD

**Issue by Banginpadr** [NVIDIA/nvidia-docker#293]
sudo tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker*.tar.xz && rm /tmp/nvidia-docker*.tar.xz
 is giving me this error>>>>>2017-01-18 20:03:38 (467 KB/s) - ‘/tmp/nvidia-docker_1.0.0.rc.3_amd64.tar.xz’ saved [2249428/2249428]

banginpadr:~ Diango$ sudo tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker*.tar.xz && rm /tmp/nvidia-docker*.tar.xz
x nvidia-docker: Can't create 'nvidia-docker'
x nvidia-docker-plugin: Can't create 'nvidia-docker-plugin'
tar: Error exit delayed from previous errors.

how can i fix this?im using a mac.

**Comment by 3XX0** [comment]
See #162
