### ISSUE TITLE
Failed to load module nvidia

### ISSUE THREAD

**Issue by enochtsang** [NVIDIA/nvidia-docker#296]
I'm having trouble getting an Xserver to start on a docker container. I'm running on a centos7 host with a GRID K1 on a 367.57 driver, the image I'm running on is using a base image of RHEL 6.8. nvidia-smi works fine in both the host and the container. It's probably worth noting that I'm trying to get this to run on a headless server.

Here's a section of my Xorg.0.log when I run startx.

```
[ 14088.033] (==) ModulePath set to "/usr/lib64/xorg/modules"
[ 14088.033] (WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
[ 14088.033] (WW) Disabling Mouse0
[ 14088.033] (WW) Disabling Keyboard0
[ 14088.033] (II) Loader magic: 0x7f9aceecc020
[ 14088.033] (II) Module ABI versions:
[ 14088.034] 	X.Org ANSI C Emulation: 0.4
[ 14088.034] 	X.Org Video Driver: 19.0
[ 14088.034] 	X.Org XInput driver : 21.0
[ 14088.034] 	X.Org Server Extension : 9.0
[ 14088.034] (EE) dbus-core: error connecting to system bus: org.freedesktop.DBus.Error.FileNotFound (Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory)
[ 14088.047] (--) PCI:*(0:0:15:0) 15ad:0405:15ad:0405 rev 0, Mem @ 0xec000000/67108864, 0xfe000000/8388608, I/O @ 0x00001070/16, BIOS @ 0x????????/32768
[ 14088.047] (--) PCI: (0:3:0:0) 10de:0ff2:10de:1012 rev 161, Mem @ 0xfc000000/16777216, 0xe0000000/134217728, 0xe8000000/33554432, I/O @ 0x00004080/128, BIOS @ 0x????????/65536
[ 14088.047] (II) LoadModule: "glx"
[ 14088.048] (II) Loading /usr/lib64/xorg/modules/extensions/libglx.so
[ 14088.053] (II) Module glx: vendor="X.Org Foundation"
[ 14088.053] 	compiled for 1.17.4, module version = 1.0.0
[ 14088.053] 	ABI class: X.Org Server Extension, version 9.0
[ 14088.053] (==) AIGLX enabled
[ 14088.053] (II) LoadModule: "nvidia"
[ 14088.054] (WW) Warning, couldn't open module nvidia
[ 14088.054] (II) UnloadModule: "nvidia"
[ 14088.054] (II) Unloading nvidia
[ 14088.054] (EE) Failed to load module "nvidia" (module does not exist, 0)
[ 14088.054] (EE) No drivers available.
[ 14088.054] (EE) 
Fatal server error:
[ 14088.054] (EE) no screens found(EE) 
[ 14088.054] (EE) 
Please consult the Red Hat, Inc. support 
	 at https://www.redhat.com/apps/support/
 for help. 
[ 14088.054] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[ 14088.054] (EE) 
```
I've made sure the PATH and LD_LIBRARY_PATH are updated. 

I'm not entirely sure where it's trying to load the modules from. I've tried adding `/usr/local/nvidia/lib` and `/usr/local/nvidia/lib64` to the ModulePath is in the `xorg.conf`, and I've tried copying all the files from `/usr/local/nvidia/lib64` into the default module path, `/usr/lib64/xorg/modules`, but neither makes any difference in the log, it still fails to find the nvidia module.

What is xorg exactly trying to find when it's loading the nvidia module?

**Comment by flx42** [comment]
Did you read #136?
It could be similar, do you have multiple GPUs and are isolating one of them inside the container?
Unfortunately, we don't really support this use case right now.

**Comment by enochtsang** [comment]
Yes I've read that one alot haha, very useful. I have only one GPU, I actually resolved the issue. I needed to copy the file `/usr/lib64/xorg/modules/drivers/nvidia_drv.so` from the host into the container's `/usr/lib64/xorg/modules/drivers/nvidia_drv.so`. So I guess that issue is fixed, but the log is giving me:
```
[ 90458.280] (EE) NVIDIA(0): Failed to initialize the GLX module; please check in your X
[ 90458.280] (EE) NVIDIA(0):     log file that the GLX module has been loaded in your X
[ 90458.280] (EE) NVIDIA(0):     server, and that the module is the NVIDIA GLX module.  If
[ 90458.280] (EE) NVIDIA(0):     you continue to encounter problems, Please try
[ 90458.280] (EE) NVIDIA(0):     reinstalling the NVIDIA driver.
```

I see the GLX libraries 
```
libGLX_indirect.so.0
libGLX_nvidia.so.0
libGLX_nvidia.so.367.57
libGLX.so.0
```
In the container's `/usr/local/nvidia/lib64`, how can I direct the xorg.conf into loading those nvidia glx libraries?
