### ISSUE TITLE
checksums for cuDNN 5 are wrong

### ISSUE THREAD

**Issue by zym1010** [NVIDIA/nvidia-docker#299]
For example, in <https://github.com/NVIDIA/nvidia-docker/blob/master/centos-6/cuda/8.0/devel/cudnn5/Dockerfile>, the actual shasum is not `a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8`, but `c10719b36f2dd6e9ddc63e3189affaa1a94d7d027e63b71c3f64d449ab0645ce`. Probably due to update of cuDNN from 5.1.5 to 5.1.10?

**Comment by flx42** [comment]
See #298, our Dockerfiles are now on GitLab. I already fixed the issue:
https://gitlab.com/nvidia/cuda/commit/3c985543d369a7e054e8b3f1c001790507a86b25

Do you have a good use case for building the images yourself? I'm still wondering whether I should keep the images in sync for a while, or just remove them.

**Comment by zym1010** [comment]
@flx42 thanks. Nope I'm fine with the official images, except that I find that in these Dockerfiles, there are URLs for cudnn, which can help me in some lab's automated scripts for installing cuDNN. thanks!
