### ISSUE TITLE
Build fails on RH 6.5

### ISSUE THREAD

**Issue by gabaker** [NVIDIA/nvidia-docker#30]
I am going to preface this with I am VERY new to docker...

Currently using RH 6.5

Problem:

I went through the process of installing docker and confirmed it is working via their hello-world docker instance. Additionally, I cloned the nvidia-docker repo but when I went to build and install via the "sudo make install" command I got the following error:

make -C /home/user_name/Desktop/nvidia-docker/tools install
make[1]: Entering directory `/home/user_name/Desktop/nvidia-docker/tools'
flag provided but not defined: --build-arg
See 'docker build --help'.
make[1]: *** [/home/user_name/Desktop/nvidia-docker/tools/bin] Error 2
make[1]: Leaving directory `/home/user_name/Desktop/nvidia-docker/tools'
make: *** [install] Error 2

The "docker build --help" command does not show any reference to --build_arg but if I remove the argument the build will initiate but fail eventually fail indicating the following:

Step 12 : ARG 
Unknown instruction: ARG
make[1]: *** [/home/user_name/Desktop/nvidia-docker/tools/bin] Error 1
make[1]: Leaving directory `/home/user_name/Desktop/nvidia-docker/tools'
make: *** [install] Error 2

Any advice or help would be greatly appreciated!

-Thanks

**Comment by 3XX0** [comment]
Unfortunately, Docker 1.9 is required to run `nvidia-docker` and thus listed as a [prerequisite](https://github.com/NVIDIA/nvidia-docker/wiki/Installation#prerequisites).
And it looks like Docker dropped their support for RH 6 (see https://github.com/docker/docker/issues/14365)

**Comment by flx42** [comment]
You could still try to use the legacy `nvidia-docker` wrapper script for execution:
https://github.com/NVIDIA/nvidia-docker/blob/e71f8ce3b53123289df78cf8ece6070c23c0ab61/nvidia-docker

But we haven't tested it.

**Comment by gabaker** [comment]
Thank you for the quick response. Looks like I need to upgrade my distro...
