### ISSUE TITLE
NVIDIA Docker plugin (in a auto-restart loop)

### ISSUE THREAD

**Issue by shumy** [NVIDIA/nvidia-docker#301]
Sequencial runs of "systemctl status nvidia-docker" gives intermittent results.
When in activating status, the result is:
```
nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/lib/systemd/system/nvidia-docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-01-30 15:59:46 WET; 283ms ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 18156 ExecStopPost=/bin/rm -f $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 18146 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 18136 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
  Process: 18135 ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR (code=exited, status=1/FAILURE)
 Main PID: 18135 (code=exited, status=1/FAILURE)

Jan 30 15:59:46 medinfo1 systemd[1]: nvidia-docker.service: Unit entered failed state.
Jan 30 15:59:46 medinfo1 systemd[1]: nvidia-docker.service: Failed with result 'exit-code'.
```

**Comment by flx42** [comment]
What's the output of `journalctl -n -u nvidia-docker`?

**Comment by shumy** [comment]
Jan 30 18:06:08 medinfo1 systemd[1]: nvidia-docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 18:06:08 medinfo1 systemd[1]: nvidia-docker.service: Unit entered failed state.
Jan 30 18:06:08 medinfo1 systemd[1]: nvidia-docker.service: Failed with result 'exit-code'.
Jan 30 18:06:09 medinfo1 systemd[1]: nvidia-docker.service: Service hold-off time over, scheduling restart.
Jan 30 18:06:09 medinfo1 systemd[1]: Stopped NVIDIA Docker plugin.
Jan 30 18:06:09 medinfo1 systemd[1]: Starting NVIDIA Docker plugin...
Jan 30 18:06:09 medinfo1 nvidia-docker-plugin[25491]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:06:09 Loading NVIDIA unified memory
Jan 30 18:06:09 medinfo1 nvidia-docker-plugin[25491]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:06:09 Loading NVIDIA management library
Jan 30 18:06:09 medinfo1 nvidia-docker-plugin[25491]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:06:09 Discovering GPU devices
Jan 30 18:06:09 medinfo1 systemd[1]: Started NVIDIA Docker plugin.

**Comment by shumy** [comment]
Also:
Jan 30 18:21:21 medinfo1 systemd[1]: Started NVIDIA Docker plugin.
Jan 30 18:21:22 medinfo1 nvidia-docker-plugin[36201]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:21:22 Provisioning volumes at /var/lib/nvidia-docker/volumes
Jan 30 18:21:22 medinfo1 nvidia-docker-plugin[36201]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:21:22 Serving plugin API at /var/lib/nvidia-docker
Jan 30 18:21:22 medinfo1 nvidia-docker-plugin[36201]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:21:22 Serving remote API at localhost:3476
Jan 30 18:21:22 medinfo1 nvidia-docker-plugin[36201]: /usr/bin/nvidia-docker-plugin | 2017/01/30 18:21:22 Error: listen tcp 127.0.0.1:3476: bind: address already
----------------------------------------------------------------------------------------------------------------------------------
and the result of: sudo netstat -tlpn | grep 3476
tcp        0      0 127.0.0.1:3476          0.0.0.0:*               LISTEN      12221/nvidia-docker

**Comment by 3XX0** [comment]
Looks like `nvidia-docker-plugin` is already running on your host.
Did you start it manually? I suggest you kill it and restart it through the init system:

```
sudo pkill nvidia-docker
sudo systemctl restart nvidia-docker
```

**Comment by shumy** [comment]
Nice. I just needed the first line. Thanks.
