### ISSUE TITLE
nvidia-docker installation require GPU processsor

### ISSUE THREAD

**Issue by nirajvara** [NVIDIA/nvidia-docker#302]
Hi

I want to check and install nvidia-docker on ubuntu. To install the nvidia-docker we should have GPU processor ???

Or we can install it on any system ??

**Comment by flx42** [comment]
Hello,

`nvidia-docker` is used to **run** containers using a GPU, so yes, a GPU is needed.
If you just want to **build** a Docker image for your project (for instance Caffe, TensorFlow, Torch...), then you don't need a GPU, `docker build` will work everywhere.
