### ISSUE TITLE
libcuda.so failed in docker containers.

### ISSUE THREAD

**Issue by hgandhi17** [NVIDIA/nvidia-docker#304]
Hello,

I am new to docker environment. I am trying to run the Nvencode sample code from my customer docker file and image and while running nvenc sample code dlopen failed to load libcuda.so

My host  machine :Ubuntu 14.04 LTS
Nvidia driver version : 375.26
My docker version : 1.13

I have installed the nvidia-docker on to my machine.  How i can link my host machine libcuda.so in to my custom docker image so Nvenc can find it run time.

Please guide.
Thanks,

**Comment by 3XX0** [comment]
libcuda should be automatically mounted when using `nvidia-docker` with the official images. Your issue probably comes from your Dockerfile.

The following issue https://github.com/NVIDIA/nvidia-docker/issues/103#issuecomment-223728318 might help.

**Comment by hgandhi17** [comment]
Thanks for your quick reply.

i have gone throgh the #103 (comment) , but the issue is that i can not use nvidia/cuda image directly in to my solution and so i need to make my own custom image which should support Nvidia nvenc. 
 I have tried to load nvidia-docker from my docker image but it fails to load 
Error: Could not load NVML library

So i could not make it work.

Please guide from basic how i can load nvidia-docker from my docker file and images. 

Thanks,

**Comment by 3XX0** [comment]
Could you paste a sample of your Dockerfile? You're probably missing the `volumes.needed` label (see [here](https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection))
