### ISSUE TITLE
Wiki - Quick Start - wget link needs updating

### ISSUE THREAD

**Issue by mjhenke** [NVIDIA/nvidia-docker#305]
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb

should be:

wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0/nvidia-docker_1.0.0-1_amd64.deb

**Comment by 3XX0** [comment]
Fixed, thanks!
