### ISSUE TITLE
sha256sum of cudnn-8.0-linux-x64-v5.1.tgz has changed

### ISSUE THREAD

**Issue by mjmg** [NVIDIA/nvidia-docker#306]
My nvidia-docker based images have been failing recently. Upon redownloading cudnn-8.0-linux-x64-v5.1.tgz from Nvidia cudnn website and the directlink <http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz> then checking the sha26sum of the downloading file, I'm getting:
`c10719b36f2dd6e9ddc63e3189affaa1a94d7d027e63b71c3f64d449ab0645ce`
instead of:
`a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8`

Upon checking with Nvidia cuDNN website, the download page has been updated as below:
_Download cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0_

Please confirm if sha256sum of the file has indeed been changed. Thanks

**Comment by flx42** [comment]
See #298, #299.
The dockerfiles on this repo will be removed soon.

**Comment by my1347** [comment]
Marked

**Comment by flx42** [comment]
@my1347 if you have a similar problem, please open a new issue.
