### ISSUE TITLE
Command to create folder with drivers

### ISSUE THREAD

**Issue by ingtarius** [NVIDIA/nvidia-docker#307]
Hello!
We use servers with GPU and Kubernetes.
At this moment everythk works fine - we add mount options to get /dev/nvidia* inside containers and also mount for driver folder: /usr/local/nvidia-driver/nvidia_driver/352.39/

This folder created by running nvidia-docker comand, but does any other way is here?
curl in API service for example?

**Comment by flx42** [comment]
Hello,

Just do this:
```
$ docker volume create --name=nvidia_driver_367.57 --driver=nvidia-docker
nvidia_driver_367.57
$ docker volume ls
DRIVER              VOLUME NAME
nvidia-docker       nvidia_driver_367.57
```

You can get the exact minor version with a command like this:
```
$ modinfo -F version nvidia_367
367.57
```

**Comment by 3XX0** [comment]
Or more succinctly: `docker volume create --driver=nvidia-docker --name=nvidia_driver_$(modinfo -F version nvidia)`

Note that you will need to issue this command everytime you upgrade your drivers

**Comment by ingtarius** [comment]
Thanks! Exactly what i need.

**Comment by loretoparisi** [comment]
After creating the volume

```
$ sudo docker volume create --driver=nvidia-docker --name=nvidia_driver_$(modinfo -F version nvidia)
nvidia_driver_367.5
```

still getting

```
docker: Error response from daemon: create nvidia_driver_367.57: Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found.
```

**Comment by loretoparisi** [comment]
@flx42 @3XX0 I have

```
$ modinfo -F version nvidia
367.57
```

and the volume is there

```
sudo docker volume ls | grep nvidia
nvidia-docker       nvidia_driver_367.57
```

**Comment by flx42** [comment]
@loretoparisi everything looks good in your latest message, do you have an issue?

**Comment by loretoparisi** [comment]
@flx42 at the end it was the `DOCKER_HOST` from the client!!! thks
