### ISSUE TITLE
Old version in documentation

### ISSUE THREAD

**Issue by MrZoidberg** [NVIDIA/nvidia-docker#308]
There is an old link in [Deploy-on-Amazon-EC2](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2) page:
`wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb`
should be
`wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0/nvidia-docker_1.0.0-1_amd64.deb`

**Comment by flx42** [comment]
Okay, I admit, we're lazy when it comes to updating the wiki ;)
Fixed now! Thanks for reporting this!
