### ISSUE TITLE
No driver volume created

### ISSUE THREAD

**Issue by ewanbarr** [NVIDIA/nvidia-docker#309]
I am running on Debian 8 (Jessie) and I have installed nvidia-docker via the "other distributions" instructions.

After ensuring that my drivers and mount directories were on the same partition I created a new user called "nvidia-docker" with its home set to /usr/lib/nvidia-docker

`nvidia-docker:x:999:998:NVIDIA Docker plugin:/usr/lib/nvidia-docker:/usr/sbin/nologin`

I have then started up the nvidia-docker-plugin via:

`sudo -u nvidia-docker nvidia-docker-plugin -s /usr/lib/nvidia-docker/ -d /usr/lib/nvidia-docker/`

giving the following output:

```
nvidia-docker-plugin | 2017/02/08 14:59:31 Loading NVIDIA unified memory
nvidia-docker-plugin | 2017/02/08 14:59:31 Loading NVIDIA management library
nvidia-docker-plugin | 2017/02/08 14:59:31 Discovering GPU devices
nvidia-docker-plugin | 2017/02/08 14:59:31 Provisioning volumes at /usr/lib/nvidia-docker/
nvidia-docker-plugin | 2017/02/08 14:59:31 Serving plugin API at /usr/lib/nvidia-docker/
nvidia-docker-plugin | 2017/02/08 14:59:31 Serving remote API at localhost:3476
```

Here I can see that the socket has been created:

`srwxr-xr-x 1 nvidia-docker nvidia-docker 0 Feb  8 14:59 /usr/lib/nvidia-docker/nvidia-docker.sock`

However I notice that there is no volume mounted for the nvidia driver:

```
root@paf1:~# nvidia-docker volume ls
DRIVER              VOLUME NAME
```

I understand that driver should be mounted by nvidia-docker, but it seems that there is an error at this stage:

```
root@paf1:~# nvidia-docker run --rm nvidia/cuda:7.5 nvidia-smi
docker: Error response from daemon: create nvidia_driver_352.39: create nvidia_driver_352.39: Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found.
See 'docker run --help'.
```

I have tried various ways to get around this, but I haven't found a solution. The driver version reported above is correct as can be seen from nvidia-smi:

```
root@paf1:~# nvidia-smi
Wed Feb  8 15:13:38 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 0000:09:00.0     Off |                  N/A |
| 22%   29C    P8    15W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  On   | 0000:89:00.0     Off |                  N/A |
| 22%   29C    P8    16W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Not sure if this is relevant or not, but it is worth mentioning that the nvidia-docker-plugin does not show up in the plugin list:

```
root@paf1:~# docker plugin ls 
ID                  NAME                DESCRIPTION         ENABLED
```

**Comment by flx42** [comment]
Since your socket is in a non-standard location, you need to create a `nvidia-docker.spec` file, something like that:
```
$ cat /etc/docker/plugins/nvidia-docker.spec
unix:///var/lib/nvidia-docker/nvidia-docker.sock
```

Or move your socket to `/run/docker/plugins/`

**Comment by ewanbarr** [comment]
Great! That appears to have solved the issue. 

I assume you meant /usr/ rather than /var/, so that:
```
$ cat /etc/docker/plugins/nvidia-docker.spec
unix:///usr/lib/nvidia-docker/nvidia-docker.sock
```

Note: I also had to switch from running the `nvidia-docker-plugin` as the nvidia-docker user to root to solve the issue completely.

Maybe I missed it, but this does not appear to be documented on the [official wiki](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin). I does appear to be documented [here](https://github.com/matthieudelaro/nvidia-docker-wiki/blob/master/Using-nvidia-docker-plugin.md) though. It would be good to merge this into the documentation on the official page.

**Comment by flx42** [comment]
I meant `/var`, because that's how it is on my machine ;)
You only have this problem since you use the `-s` option,but yes, we still need to document this.
