### ISSUE TITLE
unable to find containers after upgrade

### ISSUE THREAD

**Issue by JoBlo777** [NVIDIA/nvidia-docker#312]
Hello 

I downloaded and installed this image, After this all my containers are inaccessible. Any idea what could be the reason ? Is it possible to recover the containers ? 

Thanks

Rupert

**Comment by flx42** [comment]
What do you mean "inaccessible"? What do you see?

**Comment by JoBlo777** [comment]
it does not find any old containers any more.  I had /var/lib/docker moved due to space constraints 

apparentrly the nvidia-docker upgrade disrespected this and installed a clean empty new /var/lib/docker I can still see all the containers and images in the previously symbollicaly linked directories 

How can I recover them? 

thank you 

Rupert

**Comment by flx42** [comment]
This seems unlikely to be caused by nvidia-docker, maybe your docker daemon is not configured correctly (`-g` option).

**Comment by JoBlo777** [comment]
I have it fixed I run Nvidia-docker as a plagen now.  Is this the normal way? 

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 12, 2017 at 22:20, Felix Abecassis<notifications@github.com> wrote:   
This seems unlikely to be caused by nvidia-docker, maybe your docker daemon is not configured correctly (-g option).

**Comment by flx42** [comment]
Yes, if you're running on ubuntu or centOS

**Comment by JoBlo777** [comment]
Thanks!
Rupert 

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 13, 2017 at 19:32, Felix Abecassis<notifications@github.com> wrote:   
Yes, if you're running on ubuntu or centOS
