### ISSUE TITLE
Failed to start sshd in container: “Error: Too many open files"

### ISSUE THREAD

**Issue by hayashi-naru** [NVIDIA/nvidia-docker#313]
Hello

I'd like to know the cause and corrective action of the following "Too many open files" issue.
Or please tell me how to examination the issue.

1. Issue
In the following conditions, fail to systemctl command in the docker container.
1)launch nvidia-docker containers a certain number (20-25) or more. and
2)sshd service is activated at startup in each container. and
3)It is a container launched beyond a certain number.
message was below
~~~
$ docker exec -it hayashi.naru-work24 /bin/bash
[root@35a013c4b396 /]# systemctl start sshd.service
Error: Too many open files
Job for sshd.service canceled.
~~~
There is no problem with containers of a certain number or less

2. Environment
  - host os
~~~
# uname -a
Linux gpu07 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
~~~

  - guest os image
nvidia/cuda:8.0-cudnn5-devel-centos7

  - docker version
~~~
docker -v
Docker version 1.12.6, build 78d1802
~~~
same as nvidia-docker -v
1.12.1, build 23cf638 also occurs
~~~
# docker info
Containers: 367
 Running: 24
 Paused: 0
 Stopped: 343
Images: 1122
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1827
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: nvidia-docker local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-96-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 503.8 GiB
Name: gpu07
ID: RA7P:IZSJ:RLKJ:Y6J3:MO55:MMG6:PT4G:UZNB:PUQS:VVX3:VBMS:Z7OU
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://...
Https Proxy: http://...
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
~~~
  - nvidia-docker version
~~~
# dpkg --list nvidia-docker
Desired=Unknown/Install/Remove/Purge/Hold
|
|Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig
|-pend / Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-====================
+++========-============================-===============================
+++=====================================================================
ii  nvidia-docker                                1.0.0-1                     amd64                       NVIDIA Docker container tools
~~~
1.0.0~rc.3-1 also occurs

3. My investigation
"Too many open files" is mapped errno 24.
So I guess some system call return errno 24.
I checked the following file and directory.
  - /proc/{pid}/limits
  - /proc/{pid}/fd
When the issue occurred, there was no process opening a large number of files compared with limits number.
I can't find which process return errno 24.

Sorry for my bad English

**Comment by flx42** [comment]
This doesn't seem to be related to `nvidia-docker`, right? You would probably get the same error with just `docker`
