### ISSUE TITLE
Container command 'nvidia-smi' not found...

### ISSUE THREAD

**Issue by hlzz** [NVIDIA/nvidia-docker#314]
I follow the readme and try to deploy nvidia-docker on centos 7.5. When executing the test command 'nvidia-docker run --rm nvidia/cuda nvidia-smi', I got the following error:

> docker: Error response from daemon: Container command 'nvidia-smi' not found or does not exist..

docker version: Docker version 1.11.2, build b9f10c9
system version: Linux qnode6 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by flx42** [comment]
Does `nvidia-smi` works on the host?

What's the output of `journalctl -n -u nvidia-docker`?

**Comment by hlzz** [comment]
@flx42 `nvidia-smi` works on the host.
The output for `journalctl -n -u nvidia-docker` is:

`No journal files were found.
`

**Comment by 3XX0** [comment]
Is the plugin running on your host? `sudo systemctl status nvidia-docker`?

**Comment by hlzz** [comment]
@3XX0, output shown below:

```
● nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/usr/lib/systemd/system/nvidia-docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-02-17 17:36:18 HKT; 3 days ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 20523 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 20513 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
 Main PID: 20512 (nvidia-docker-p)
   Memory: 6.5M
   CGroup: /system.slice/nvidia-docker.service
           └─20512 /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker

Feb 17 17:36:25 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:36:25 Received unmount request for volume 'nvidia_driver_375.26'
Feb 17 17:41:34 qnode6 systemd[1]: Started NVIDIA Docker plugin.
Feb 17 17:41:40 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:41:40 Received mount request for volume 'nvidia_driver_375.26'
Feb 17 17:41:41 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:41:41 Received unmount request for volume 'nvidia_driver_375.26'
Feb 17 17:48:17 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:48:17 Received mount request for volume 'nvidia_driver_375.26'
Feb 17 17:48:18 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:48:18 Received unmount request for volume 'nvidia_driver_375.26'
Feb 17 17:48:53 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:48:53 Received mount request for volume 'nvidia_driver_375.26'
Feb 17 17:48:54 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/17 17:48:54 Received unmount request for volume 'nvidia_driver_375.26'
Feb 20 12:51:20 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/20 12:51:20 Received mount request for volume 'nvidia_driver_375.26'
Feb 20 12:51:21 qnode6 nvidia-docker-plugin[20512]: /usr/bin/nvidia-docker-plugin | 2017/02/20 12:51:21 Received unmount request for volume 'nvidia_driver_375.26'

```

**Comment by flx42** [comment]
This looks fine. Maybe the volume is incomplete, try the following:
```
nvidia-docker run --rm nvidia/cuda sh -c 'ls -R /usr/local/nvidia'
```

**Comment by hlzz** [comment]
@flx42 
```
/usr/local/nvidia:
bin
lib
lib64

/usr/local/nvidia/bin:

/usr/local/nvidia/lib:

/usr/local/nvidia/lib64:
libEGL.so.1
libEGL_nvidia.so.0
libEGL_nvidia.so.375.26
libGL.so.1
libGL.so.375.26
libGLESv1_CM.so.1
libGLESv1_CM_nvidia.so.1
libGLESv1_CM_nvidia.so.375.26
libGLESv2.so.2
libGLESv2_nvidia.so.2
libGLESv2_nvidia.so.375.26
libGLX_indirect.so.0
libGLX_nvidia.so.0
libGLX_nvidia.so.375.26
libGLdispatch.so.0
libOpenGL.so.0
libcuda.so
libcuda.so.1
libcuda.so.375.26
libnvcuvid.so.1
libnvcuvid.so.375.26
libnvidia-compiler.so.375.26
libnvidia-egl-wayland.so.375.26
libnvidia-eglcore.so.375.26
libnvidia-encode.so.1
libnvidia-encode.so.375.26
libnvidia-fatbinaryloader.so.375.26
libnvidia-fbc.so.1
libnvidia-fbc.so.375.26
libnvidia-glcore.so.375.26
libnvidia-glsi.so.375.26
libnvidia-ifr.so.1
libnvidia-ifr.so.375.26
libnvidia-ml.so.1
libnvidia-ml.so.375.26
libnvidia-opencl.so.1
libnvidia-opencl.so.375.26
libnvidia-ptxjitcompiler.so.375.26
libnvidia-tls.so.375.26

```

**Comment by flx42** [comment]
Looks like your volume is incomplete somehow, try to remove it:
```
docker volume rm -f nvidia_driver_375.26
```
Then try to start another container with `nvidia-docker`.

**Comment by hlzz** [comment]
@flx42 There seems to be no `-f` flag for `docker volume rm -f` since `docker volume rm -f nvidia_driver_375.26` gives me:
```
flag provided but not defined: -f
See 'docker volume rm --help'.
```

Then i tried `docker volume rm nvidia_driver_375.26` and it outputs just this:
```
nvidia_driver_375.26
```

but i don't know what do you mean by _Then try to start another container with nvidia-docker_? I use `nvidia-docker run --rm nvidia/cuda nvidia-smi` and the output message is still `docker: Error response from daemon: Container command 'nvidia-smi' not found or does not exist..` Thanks for your help

**Comment by flx42** [comment]
> There seems to be no -f flag for docker volume rm -f since docker volume rm -f nvidia_driver_375.26 gives me

There is, in 1.13, so you probably are using 1.12 or older.

> but i don't know what do you mean by Then try to start another container with nvidia-docker? I use nvidia-docker run --rm nvidia/cuda nvidia-smi and the output message is still docker: Error response from daemon: Container command 'nvidia-smi' not found or does not exist..

Deleting the volume forced nvidia-docker to re-create it, I thought it might solve the issue but it didn't.

Where `nvidia-smi` located? (`which nvidia-smi`).

**Comment by hlzz** [comment]
@flx42 Yes you are right. I am using docker 1.11.2. Is this issue related to my docker version? 
`nvidia-smi` is located in `/usr/bin`

**Comment by flx42** [comment]
No this isn't related to the docker version, I'm out of ideas for now, I will need to test on a CentOS machine, but it's the first time I see this.
Any idea @3XX0?

**Comment by 3XX0** [comment]
What is the output of `which nvidia-cuda-mps-control nvidia-cuda-mps-server nvidia-debugdump nvidia-persistenced nvidia-smi` on your machine?

**Comment by hlzz** [comment]
@3XX0 There seems to be some problems with my `which`:
```
-bash: /usr/bin/which: No such file or directory
```
But I've checked manually. All of these commands you mentions are present and located in `/usr/bin`

**Comment by 3XX0** [comment]
Unfortunately `nvidia-docker` depends on `which` to find the binaries so you will need it on your host machine.

**Comment by loretoparisi** [comment]
@3XX0 to clarify: was this issue due to the missing `which` command on the docker instance? I'm getting the same issue when building a docker container from `FROM nvidia/cuda:8.0-devel-ubuntu16.04` - see here https://github.com/NVIDIA/nvidia-docker/issues/341

Thank you.

**Comment by 3XX0** [comment]
@loretoparisi Yes `which` is needed on the host, in the container make sure that `/usr/local/nvidia/bin` has `nvidia-smi` and that your `PATH` is set accordingly (this is done automatically by `nvidia-docker`).
