### ISSUE TITLE
CUDA driver version insufficient

### ISSUE THREAD

**Issue by Data-drone** [NVIDIA/nvidia-docker#316]
I am running:
Ubuntu 16.04
with Nvidia driver 375.20 installed and CUDA 8.0.44

tensorflow running on the machine with GPU works.
Running DIGITS with nvidia-docker though gives me:

`ERROR: Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version`

this is using caffe models.
I am trying to run the DetectNet as per the tutorials
Any ideas?

**Comment by 3XX0** [comment]
What is the output of `ldconfig -p | grep cuda`?

**Comment by Data-drone** [comment]
libopencv_cudawarping.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudawarping.so.3.2
	libopencv_cudawarping.so (libc6,x86-64) => /usr/local/lib/libopencv_cudawarping.so
	libopencv_cudastereo.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudastereo.so.3.2
	libopencv_cudastereo.so (libc6,x86-64) => /usr/local/lib/libopencv_cudastereo.so
	libopencv_cudaoptflow.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudaoptflow.so.3.2
	libopencv_cudaoptflow.so (libc6,x86-64) => /usr/local/lib/libopencv_cudaoptflow.so
	libopencv_cudaobjdetect.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudaobjdetect.so.3.2
	libopencv_cudaobjdetect.so (libc6,x86-64) => /usr/local/lib/libopencv_cudaobjdetect.so
	libopencv_cudalegacy.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudalegacy.so.3.2
	libopencv_cudalegacy.so (libc6,x86-64) => /usr/local/lib/libopencv_cudalegacy.so
	libopencv_cudaimgproc.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudaimgproc.so.3.2
	libopencv_cudaimgproc.so (libc6,x86-64) => /usr/local/lib/libopencv_cudaimgproc.so
	libopencv_cudafilters.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudafilters.so.3.2
	libopencv_cudafilters.so (libc6,x86-64) => /usr/local/lib/libopencv_cudafilters.so
	libopencv_cudafeatures2d.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudafeatures2d.so.3.2
	libopencv_cudafeatures2d.so (libc6,x86-64) => /usr/local/lib/libopencv_cudafeatures2d.so
	libopencv_cudacodec.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudacodec.so.3.2
	libopencv_cudacodec.so (libc6,x86-64) => /usr/local/lib/libopencv_cudacodec.so
	libopencv_cudabgsegm.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudabgsegm.so.3.2
	libopencv_cudabgsegm.so (libc6,x86-64) => /usr/local/lib/libopencv_cudabgsegm.so
	libopencv_cudaarithm.so.3.2 (libc6,x86-64) => /usr/local/lib/libopencv_cudaarithm.so.3.2
	libopencv_cudaarithm.so (libc6,x86-64) => /usr/local/lib/libopencv_cudaarithm.so
	libicudata.so.55 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so.55
	libicudata.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so

**Comment by 3XX0** [comment]
What DIGITS image are you using? Can you try the [deviceQuery sample](https://github.com/NVIDIA/nvidia-docker/blob/master/samples/ubuntu-16.04/deviceQuery/Dockerfile) see if it also fails

**Comment by catmonkeylee** [comment]
@3XX0 
When try the deviceQuery sample, I got the same error:

./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

**Comment by flx42** [comment]
@catmonkeylee you're not the original poster, so what's your driver version?

**Comment by catmonkeylee** [comment]
@flx42  My driver version is: 375.39

**Comment by 3XX0** [comment]
See [requirements](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements)

**Comment by DarioTurchi** [comment]
Hello,
I have the same error with satisfied requirements: driver 387.26, cuda 8.0 ....

**Comment by flx42** [comment]
@DarioTurchi please file a new issue and provide more details.
