### ISSUE TITLE
are CUDA 8.0.61 and 8.0.44 fully compatible for previously compiled programs on 8.0.44?

### ISSUE THREAD

**Issue by zym1010** [NVIDIA/nvidia-docker#318]
See the title. Sorry I don't know where to put this, but I can't find any official statement about this. I'm using nvidia-docker (with CUDA 8.0.44) to compile TensorFlow packages for my CentOS cluster, and I wonder if I can use this previously compiled package with latest CUDA 8.0.61 without problem. Compiling a new one is kind of tedious. Thanks.

**Comment by flx42** [comment]
It should work just fine. If it doesn't then it's a bug.

**Comment by zym1010** [comment]
thanks! tested and it worked fine.
