### ISSUE TITLE
nvidia-docker does not pull missing images

### ISSUE THREAD

**Issue by cancan101** [NVIDIA/nvidia-docker#32]
```
$ nvidia-docker run 4catalyzer/theano nvidia-smi
nvidia-docker | 2016/01/11 13:07:47 Error: No such image or container: 4catalyzer/theano
```
whereas for regular `docker`:
```
$ docker run 4catalyzer/theano nvidia-smi
Unable to find image '4catalyzer/theano:latest' locally
latest: Pulling from 4catalyzer/theano
...
```

**Comment by flx42** [comment]
Yes, that's a known limitation listed on the wiki:
https://github.com/NVIDIA/nvidia-docker/wiki/Using-nvidia-docker#known-limitations
We will try to find a solution, in the mean time you will have to pull the image manually.

Thank you for reporting the issue, we can keep it open for tracking :)

**Comment by flx42** [comment]
For the record, here is the code in Docker to handle this case with `docker run`:
https://github.com/docker/docker/blob/2892de760f412360c5effef9cfc346f2d92eaa4c/api/client/create.go#L111-L136

**Comment by flx42** [comment]
Please test the new version! :)
