### ISSUE TITLE
Pycuda with CUDA 8.0

### ISSUE THREAD

**Issue by parunach** [NVIDIA/nvidia-docker#321]
I installed the pycuda-2016.1.2-py2.7-linux-x86_64 in our CentOS machine with CUDA 8.0. I have

```
LD_LIBRARY_PATH=/usr/local/cuda/lib64
CUDA_HOME=/usr/local/cuda
```

When I try

`import pycuda.driver as cuda`

I get

`ImportError: libcurand.so.7.5: cannot open shared object file: No such file or directory`

I see that I have libcudart.so.8.0. Can anyone help me with this?

**Comment by flx42** [comment]
This seems to be a pycuda bug, it doesn't support CUDA 8.0
And it doesn't seem to be related to `nvidia-docker`, so this is not the right place to ask.
