### ISSUE TITLE
Error: unsupported Docker version (with new docker version v17.03.0-ce)

### ISSUE THREAD

**Issue by QuentinG3** [NVIDIA/nvidia-docker#323]
Hi,
I am getting this error "nvidia-docker | 2017/03/02 15:31:46 Error: unsupported Docker version" since the release of the new docker version v17.03.0-ce.

Could it be possible to make it compatible with this new docker version?

Thank you.

**Comment by JoBlo777** [comment]
Me too!

**Comment by jokla** [comment]
I cannot install the nvidia-docker neither, I guess it is because of this new version of docker v17.03.0-ce:

```
Unpacking nvidia-docker (1.0.0-1) over (1.0.0-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on docker-engine (>= 1.9.0); however:
  Package docker-engine is not installed.
```

**Comment by flx42** [comment]
@QuentinG3 I fixed that on `master`, we will release `1.0.1` today.

@jokla your problem is different I believe, you didn't install the official docker package.

**Comment by flx42** [comment]
@jokla actually, I just noticed that there is now a new package called `docker-ce`. So users might end-up with one or the other.

**Comment by JoBlo777** [comment]
I can confirm fixing the version string to 17.030-ce in docker.go worked for me.  

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 2, 2017 at 19:17, Felix Abecassis<notifications@github.com> wrote:   
@jokla actually, I just noticed that there is now a new package called docker-ce. So users might end-up with one or the other.

**Comment by jokla** [comment]
@flx42 Thanks for your answer. I installed docker-ce following these instructions: https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository
Is it not the official docker package?

**Comment by flx42** [comment]
@jokla: it is now, but this new package name came as a surprise for us.

**Comment by jokla** [comment]
@flx42 How can I install nvidia-docker now? Should I wait for the release 1.0.1 then? 
Thanks!

**Comment by flx42** [comment]
@jokla you can wait for `1.0.1`, or if you're brave you can generate your own deb package after modifying `build/deb/control`:
```patch
-Depends: ${misc:Depends}, ${shlibs:Depends}, adduser, docker-engine (>= 1.9.0), libcap2-bin
+Depends: ${misc:Depends}, ${shlibs:Depends}, adduser, docker-engine (>= 1.9.0) | docker-ce | docker-ee, libcap2-bin
```
And then `make deb`.

**Comment by flx42** [comment]
1.0.1 is released, please test!

**Comment by soumenms2015** [comment]
Hello @flx42 It works now. Thanks for your quick action !!! Much appreciated !!
