### ISSUE TITLE
is it possible to set the location of nvidia-docker folder

### ISSUE THREAD

**Issue by simonm3** [NVIDIA/nvidia-docker#325]
I keep my docker containers on a non-boot drive by setting /etc/docker/daemon.json with {"graph":"/myfolder"}. However nvidia-docker ignores this setting and continues to use /var/lib/nvidia-docker. When my AWS server terminates this folder is lost. Then if I try to restart my docker container it tells me the driver is missing.

Is there a way this folder can be recreated or a setting where I can I change the location of the nvidia-docker folder? It seems the folder is only created when I run a container and reinstalling nvidia-docker does not help. For the moment it looks like I can copy the folder myself but maybe there is an easier way?

**Comment by flx42** [comment]
Look [here](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#usage)
You want a combination of `-s` and `-d`.

**Comment by simonm3** [comment]
Unfortunately this does not seem to work.

This works if I copy saved version of  nvidia-docker folder to /var/lib:
sudo -b nohup nvidia-docker-plugin

   nvidia-docker run......


However if I kill the nvidia-docker-plugin and then:

    sudo -b nohup nvidia-docker-plugin -d /v1/nvidia-docker/volumes

    nvidia-docker run.....


Error response from daemon: no such volume: nvidia_driver_352.99.

**Comment by simonm3** [comment]
Also tried with the -s option as well but it also produced same message

**Comment by flx42** [comment]
Docker believes the volume already exists, but the second instance of nvidia-docker-plugin can't find it because of the new volume path.
So, you should remove the volume first before changing the path.

**Comment by simonm3** [comment]
Got this working by using the -d option only. This appears to do what I need and the socket (I guess that is what the -s option is) recreates itself.

**Comment by simonm3** [comment]
After further experimenting it seems

This fails
 ```
     nvidia-docker-plugin -d /v1
     nvidia-docker run xxxx
```
But this works
```
    nvidia-docker plugin
    nvidia-docker run <xxxx or any other image>
    copy var/lib/nvidia-docker/volumes to /v1

    restart i.e. kill plugin and stop container

    nvidia-docker plugin -d /v1
    docker start xxxx
```
It looks like the driver volume is created by nvidia-docker-run in the default location. After that it can be moved anywhere and subsequent nvidia-docker-plugin can use the -d parameter. 

I am trying to nvidia-docker run the container on a server; stop it; then start on a different server. So if the /v1 folder exists I run the plugin with -d else not.  And after nvidia-docker run I check if the /v1 folder exists and if not then copy /var/lib/nvidia-docker/volumes to /v1. This seems to work but do you see any potential issues?

Also suppose I have a running container and want to use on a server with later drivers. I don't want to nvidia-docker run again as would lose all my data in the container. Can I nvidia-docker run a different container to regenerate the /var/lib/nvidia-docker/volumes, copy to /v1 and then start my original container using the new volume links? If not is there any other way of linking to the new drivers? Obviously I could commit the container to an image and do another nvidia-docker run but that takes time.

**Comment by 3XX0** [comment]
Closing, there are no more volumes in 2.0/master.
