### ISSUE TITLE
bug in argparsing `nvidia-docker run --`

### ISSUE THREAD

**Issue by joernhees** [NVIDIA/nvidia-docker#330]
You can start docker containers like this: `docker run -it --rm -- imagename`. This is at least helpful in automation when `imagename` cannot fully be trusted (see https://github.com/joernhees/userdocker for an exemplary use-case).

Calling `nvidia-docker run -it --rm -- imagename`, will cause it to append its internal args after the `--`, resulting in missing mounts (like `/usr/local/lib/nvidia`) etc.

I think the error is around https://github.com/NVIDIA/nvidia-docker/blob/master/src/nvidia-docker/main.go#L87

**Comment by flx42** [comment]
Ah yes, you're right, thanks for reporting. We'll try to fix it in later releases.

**Comment by joernhees** [comment]
@flx42 review my fix in #331 ... i'm not deeply into go, but i think it does the trick by just decreasing the offset in case the args end with `--`

**Comment by joernhees** [comment]
any update on this?

**Comment by flx42** [comment]
@joernhees it's a valid bug, but I won't create a new release just to fix this single issue. When we have enough fixes for `1.0.2`, I will include this.

**Comment by joernhees** [comment]
agreed and wouldn't ask for a dedicated release for this, but maybe close / merge #331 then?

**Comment by flx42** [comment]
I'll close the PR for now, it doesn't seem like the right way to do it.

**Comment by 3XX0** [comment]
Closing, there is no more wrapper in 2.0/master. Feel free to reopen if you can reproduce with the `nvidia-docker` wrapper script.

**Comment by joernhees** [comment]
thanks, will report back should the bug still appear in 2.0
