### ISSUE TITLE
nvidia-docker to cloud deployment without GPUs on a personal computer

### ISSUE THREAD

**Issue by MikeTam1021** [NVIDIA/nvidia-docker#332]
I tried to install the nvidia-docker tool so that I could use it for a cloud deployment. Tensorflow's docker container deployment with nvidia GPUs looks something like:

nvidia-docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow:latest-gpu

I would like to deploy it on a cloud with GPUs. I am using gcloud from the command line. However, I do not have nvidia GPUs on my personal system. Therefore I do not have nvidia drivers. I cannot install nvidia-docker because of this, and that means I cannot deploy with the nvidia-docker plugin command.

Is there a work around or possible solution to this? Am I able to install a certain driver just to get nvidia docker? Or should I deploy the container with normal docker and then manage it from there?

**Comment by MikeTam1021** [comment]
looks like I found the answer...

Driver is not portable so it's not possible, I have to ssh into the VM and install drivers or script it..

and I can't use google's container-vm image because it runs Debian 7 and the drivers for Debian 7 don't support the K80. Just does not work simply.

**Comment by 3XX0** [comment]
Alternatively see [remote deployment](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#running-it-remotely)
