### ISSUE TITLE
docker: Error response from daemon: create nvidia_driver_375.20: create nvidia_driver_375.20: Error looking up volume plugin nvidia-docker: plugin not found.

### ISSUE THREAD

**Issue by dashesy** [NVIDIA/nvidia-docker#333]
Extension is running
    
    $ curl -s http://localhost:3476/docker/cli

```
--volume-driver=nvidia-docker --volume=nvidia_driver_375.20:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia0 --device=/dev/nvidia1 --device=/dev/nvidia2 --device=/dev/nvidia3
```

The volume name is incorrect:

    $ sudo nvidia-docker volume ls

```
DRIVER              VOLUME NAME
local               926a5cf21b12a25f1e28cb527a749328bfc12200c84dff01945e053a6b8d404e
```

I get this error when running the docker:

```
docker: Error response from daemon: create nvidia_driver_375.20: create nvidia_driver_375.20: Error looking up volume plugin nvidia-docker: plugin not found.
```

**Comment by dashesy** [comment]
I had to create a volume like this:

    nvidia-docker volume create --name nvidia_driver_375.20

**Comment by flx42** [comment]
The volume name is not incorrect, Docker asks our plugin to create the volume when you run the command the first time. But in your case Docker can't find our plugin, is it running? Or did you install it?
Your `volume create` command will create an empty volume, that's not what you want.

**Comment by dashesy** [comment]
It is not empty. Also the plugin is running, is why I can `curl` and get the output, if I am not mistaken:

    curl -s http://localhost:3476/docker/cli

**Comment by flx42** [comment]
Right, but Docker doesn't find the plugin. What's the log of `nvidia-docker`? And how did you install it?

**Comment by dashesy** [comment]
I ran this command (specified [here]())

    sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log

Next am going to run `nvidia-docker.service` then I could look at the logs of that unit.

**Comment by flx42** [comment]
When running `nvidia-docker-plugin` this way, it will create the file `/run/docker/plugins/nvidia-docker.sock`, it's a standard path used by Docker for plugin discovery:
https://docs.docker.com/engine/extend/plugin_api/#plugin-discovery

When installing `nvidia-docker` through our packages, we instead create a spec file for Docker:
```
$ sudo cat /etc/docker/plugins/nvidia-docker.spec
unix:///var/lib/nvidia-docker/nvidia-docker.sock
```
That's also documented in the link above.

If you switch between the two ways of installing nvidia-docker, you will need to restart docker itself, otherwise it will keep trying to use the older socket file.

Hope that helps.

**Comment by dashesy** [comment]
Thanks I will go through that document.

I am trying to make `nvidia-docker.service` work, but so far it is unsuccessful.

However I can run the plugin manually like:

core@raascore1 ~ $ sudo nvidia-docker-plugin -s /var/lib/nvidia-docker
nvidia-docker-plugin | 2017/03/08 03:07:07 Loading NVIDIA unified memory
nvidia-docker-plugin | 2017/03/08 03:07:07 Loading NVIDIA management library
nvidia-docker-plugin | 2017/03/08 03:07:10 Discovering GPU devices
nvidia-docker-plugin | 2017/03/08 03:07:11 Provisioning volumes at /var/lib/nvidia-docker/volumes
nvidia-docker-plugin | 2017/03/08 03:07:11 Serving plugin API at /var/lib/nvidia-docker
nvidia-docker-plugin | 2017/03/08 03:07:11 Serving remote API at localhost:3476

Still I do not understand what it has to do with `nvidia-smi` not being present in the image. Will make the service work and let you know.

**Comment by flx42** [comment]
Make sure no other `nvidia-docker-plugin` is running before starting the service, I'm not sure why it doesn't start.

> Still I do not understand what it has to do with nvidia-smi not being present in the image.

You created an empty volume, that's why. `nvidia-smi` is not present in the image, but it is mounted from the host using our volume. This is explained in our wiki if you're interested:
https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-driver
The right way to use `volume create` is to specify that our plugin should be used:
```
docker volume create --name=nvidia_driver_375.20 -d nvidia-docker
```

**Comment by dashesy** [comment]
Ok I figured out why the service did not start! (to debug that I had to use User=root because otherwise it did not give any information).
The problem was the paths, I am using CoreOS and all binaries are in `/opt/bin`. I added this line to `nvidia-docker.service`:

    Environment="PATH=/opt/bin/:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

Also, if there is another CoreOS user that wants to use the service these are additional steps I had done before, taken from Fedora .spec file:

    sudo useradd -r -M -d /var/lib/nvidia-docker -s /usr/sbin/nologin -c "NVIDIA Docker plugin" nvidia-docker
    sudo setcap cap_fowner+pe /opt/bin/nvidia-docker-plugin

**Comment by flx42** [comment]
Yeah, we don't really support CoreOS. It's doable but a bit tricky.

>   if I have only one type of card, do I even need the plugin? I should be able to get a volume with external links that I can use in all my dockers, right? I can even create the volume just once and use it in other machines.

The card type doesn't matter, it's the driver version that does. The volume must match **exactly** the kernel module version.
You could also argue that you have a single driver version in your cluster, but when you are going to upgrade the driver (and you will do that more often than upgrading the HW) it's going to be a mess, so I wouldn't recommend it.
