### ISSUE TITLE
Missing nvidia_driver_375.26

### ISSUE THREAD

**Issue by yaohungt** [NVIDIA/nvidia-docker#334]
I'm using Ubuntu 14.04 with CUDA 8.0 / cudnn 5.1. 

I just installed the nvidia-docker from *.deb (latest version 17.03.0-ce); however, when I test 

`nvidia-docker run --rm nvidia/cuda nvidia-smi`

, the error came up with 

`docker: Error response from daemon: create nvidia_driver_375.26: VolumeDriver.Create: internal error, check logs for details.`

The problem is similar with #290 , but the solution doesn't work for me. Also, running 

`sudo docker volume inspect nvidia_driver_375.26`

, it simply said that there's no such volume.

Can anyone help me?

**Comment by wakanawakana** [comment]
I'm using Ubuntu 14.04 with CUDA 7.5/8.0 K520
![image](https://cloud.githubusercontent.com/assets/24972079/23695657/b0906d14-0423-11e7-8c7b-ce8d4f133f16.png)

![image](https://cloud.githubusercontent.com/assets/24972079/23695700/dd46ad32-0423-11e7-9e68-37a16e10518d.png)

nvidia-docker 1.0.1
ok

are you use nvidia-docker latest version?

~~~
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
~~~



I think "version 17.03.0-ce" is the version of docker

**Comment by yaohungt** [comment]
Yes, I'm using the latest nvidia-docker.

**Comment by yaohungt** [comment]
In the host, I get this information:

![2017-03-08 11 15 56](https://cloud.githubusercontent.com/assets/20259168/23712465/ffc2601e-03f0-11e7-930d-afc640de929c.png)

**Comment by flx42** [comment]
Please share the nvidia-docker log, on trusty it should be in `cat /var/log/upstart/nvidia-docker.log`.
You might be missing the `nvidia-modprobe` tool.

**Comment by yaohungt** [comment]
I type `nvidia-modprobe` in the command line, and there's no error message appears.
![2017-03-08 2 07 10](https://cloud.githubusercontent.com/assets/20259168/23719252/98296890-0408-11e7-96a3-21ece4b39299.png)

However, it seems that something went wrong when creating container. Here's my nvidia-docker log:
`
.
.
.
/usr/bin/nvidia-docker-plugin | 2017/03/07 19:52:59 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?
/usr/bin/nvidia-docker-plugin | 2017/03/07 19:53:00 Loading NVIDIA unified memory
.
.
.
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:48:59 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:42 Loading NVIDIA management library                      
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:42 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:42 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:42 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:42 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:56 Received activate request
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:56 Plugins activated [VolumeDriver]
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:56 Received create request for volume 'nvidia_driver_375.26'
/usr/bin/nvidia-docker-plugin | 2017/03/08 00:31:56 Error: link /usr/lib/nvidia-375/bin/nvidia-cuda-mps-control /var/lib/nvidia-docker/volumes/nvidia_driver/375.26/bin/nvidia-cuda-mp
s-control: invalid cross-device link
.
.
.
`

**Comment by flx42** [comment]
@yaohungt Ah, that's a [known limitation](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#known-limitations). You will need to modify the volume path used by `nvidia-docker`.
Search "cross-device link" in the GitHub issues, you will see many similar issues, it might be helpful for you.

**Comment by yaohungt** [comment]
Thanks, I'll take a look.

**Comment by yaohungt** [comment]
I've take a look at #133 . And the solution there doesn't work for me. I'm using Ubuntu 14.04, and when I'm running 
`sudo nvidia-docker-plugin -d /usr/local/nvidia-driver`, I got the same issue:
<img width="1036" alt="2017-03-08 2 54 39" src="https://cloud.githubusercontent.com/assets/20259168/23721301/42a2cc2a-040f-11e7-95eb-e7b99f83173e.png">

Do you have any suggestion? I've followed the solutions in #133 as well as some other suggestions on the web, and still doesn't work or not suitable for Ubuntu 14.04.

My apology for that I'm not familiar with linux system.

**Comment by flx42** [comment]
You have another `nvidia-docker-plugin` already running, kill it first.

**Comment by yaohungt** [comment]
What do you mean by kill the `nvidia-docker-plugin` ?  Is to restart `nvidia-docker`? I've tried it, but nothing changed.

**Comment by flx42** [comment]
```
ps aux | grep nvidia-docker-plugin
```
You probably have another `nvidia-docker-plugin` process running. If you launched `nvidia-docker-plugin` manually, you need to use the `kill` command to stop the process.

**Comment by yaohungt** [comment]
Thanks. I've gave it a try. However, after killing the existing process, running `sudo nvidia-docker-plugin -d /usr/local/nvidia-driver` seems to stuck the process from moving on
<img width="1101" alt="2017-03-08 6 17 48" src="https://cloud.githubusercontent.com/assets/20259168/23728671/0d75b4a0-042c-11e7-9d98-882ef5c3ec63.png">

I think it's not normal. 

Also, `sudo nvidia-docker volume ls` seems to stuck forever.

<img width="1101" alt="2017-03-08 6 17 48" src="https://cloud.githubusercontent.com/assets/20259168/23728801/a41ac422-042c-11e7-89bd-7adb2f98cb90.png">

**Comment by flx42** [comment]
You need to restart Docker, it's probably confused because it can't find the plugin anymore: `sudo restart docker`.
But also, you are using ubuntu 14.04, so you should not try running `nvidia-docker-plugin` manually.
Let's try again from scratch: please remove the nvidia-docker package, restart your machine, and reinstall nvidia-docker cleanly. Then modify `/etc/default/nvidia-docker` with the paths you need.

**Comment by yaohungt** [comment]
Thanks for your patience. I did exactly what you said, and also in `/etc/default/nvidia-docker`, I remain the same `NVIDIA_DOCKER_PLUGIN_OPTS="-s /var/lib/nvidia-docker"`. Do I need to modify it?

Again, testing on `nvidia-docker run --rm nvidia/cuda nvidia-smi`, the problem still not solved.

**Comment by flx42** [comment]
Yes, add the `-d` option to this file.

**Comment by yaohungt** [comment]
I've modified the file to 
`NVIDIA_DOCKER_PLUGIN_OPTS="-d /var/lib/nvidia-docker/volumes -s /var/lib/nvidia-docker"`

Following by restarting docker and nvidia-docker, and testing on the same command. Still doesn't help. 

Quite frustrated, since I have nice experience using nvidia-docker within DGX-1; however, I can't successfully install it in my own machine. But still want to figure out what's the problem....

**Comment by flx42** [comment]
`-d /var/lib/nvidia-docker/volumes` is the default value, which is causing an issue for you. Don't you want another path?

**Comment by yaohungt** [comment]
I've tried something like 
`NVIDIA_DOCKER_PLUGIN_OPTS="-d /home/yaohungt/folder_for_nvidia/volumes -s /var/lib/nvidia-docker"`
But it's the same.

**Comment by flx42** [comment]
You need to check the output of the nvidia-docker log in this case, because it could be that `nvidia-docker-plugin` doesn't have the permissions to write to this new folder.
We know this limitation is annoying, it will be fixed in the next version of nvidia-docker.

**Comment by yaohungt** [comment]
I put my log file on:

[nvidia-docker.log.txt](https://github.com/NVIDIA/nvidia-docker/files/829395/nvidia-docker.log.txt)

Again, thanks for so much patience.
