### ISSUE TITLE
Invalid cross-device link: how to reinstall NVIDIA drivers in a specific location?

### ISSUE THREAD

**Issue by aTnT** [NVIDIA/nvidia-docker#335]
I am having problems similar to issue #133 which in my case and [as mentioned here](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin) are due to the need to have both NVIDIA drivers and the Docker plugin volumes in the same partition (this is not my case).

How can i remove and reinstall the NVIDIA drivers in a specific location? I normally use the command below to install the drivers:

    sudo apt-get install nvidia-xxx

This is my output of `journalctl -n -u nvidia-docker` :
```

mrt 09 11:47:45 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 11:47:45 Serving remote API at localhost:3476
mrt 09 11:50:33 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 11:50:33 Received activate request
mrt 09 11:50:33 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 11:50:33 Plugins activated [VolumeDriver]
mrt 09 11:50:33 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 11:50:33 Received create request for volume 'nvidia_driver_367.57'
mrt 09 11:50:33 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 11:50:33 Error: link /usr/lib/nvidia-367/bin/nvidia-cuda-mps-control /data/nvidia-docker/nvidia_driver/367.57/bin/nvidia-cuda-mps-control: invalid cross-device link
mrt 09 12:03:53 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 12:03:53 Received activate request
mrt 09 12:03:53 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 12:03:53 Plugins activated [VolumeDriver]
mrt 09 12:03:53 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 12:03:53 Received create request for volume 'nvidia_driver_367.57'
mrt 09 12:03:53 andre-thinkstation-P710 nvidia-docker-plugin[1460]: /usr/bin/nvidia-docker-plugin | 2017/03/09 12:03:53 Error: link /usr/lib/nvidia-367/bin/nvidia-cuda-mps-control /data/nvidia-docker/nvidia_driver/367.57/bin/nvidia-cuda-mps-control: invalid cross-device link
```
As seen above ` /data/nvidia-docker` is the location of my nvidia-docker volume, and  the contents of ` systemctl edit nvidia-docker` are:
```

[Service]
ExecStart=
ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR -d /data/nvidia-docker

```

**Comment by flx42** [comment]
Instead of trying to install the driver to a different location (not a great idea since it's installed through a deb package), you should instead modify the location of the nvidia-docker volumes.

**Comment by aTnT** [comment]
The point is that i am out of space and i need to set the volumes and containers in an external partition (and physical drive) with sufficient space.

**Comment by flx42** [comment]
In this case, remove the current NVIDIA driver (purge all the packages). Then install the driver through our `.run` installers from this page: http://www.nvidia.com/object/unix.html
If you look at the advanced options, you will be able to set the install path.
