### ISSUE TITLE
EGL/glvnd vendor config dirs missing

### ISSUE THREAD

**Issue by andrewseidl** [NVIDIA/nvidia-docker#337]
The introduction of glvnd in the 375 drivers means we must now pull in the new EGL vendor config dirs: `/etc/glvnd/egl_vendor.d` and `/usr/share/glvnd/egl_vendor.d`. Without these EGL either does not work or at least cannot make use of vendor-specific extensions.

Workaround for now is to manually bind mount the dirs via

    -v /usr/share/glvnd/egl_vendor.d:/usr/share/glvnd/egl_vendor.d

Example repository: https://hub.docker.com/r/andrewseidl/gl-version-test/
Source: https://github.com/andrewseidl/gl-version-test

    $ nvidia-docker run --rm andrewseidl/gl-version-test
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Error EGL_BAD_PARAMETER
    Aborted (core dumped)

    $ nvidia-docker run --rm -v /usr/share/glvnd/egl_vendor.d:/usr/share/glvnd/egl_vendor.d andrewseidl/gl-version-test
    GL_VERSION: 4.5.0 NVIDIA 378.13

Tested with nvidia-docker 1.0.1 on:
- Arch w/ 378.13
- CentOS 7 w/ 375.39 (via runfile)
- Ubuntu 16.04 w/ 367.57 (pre-glvnd, so runs fine w/o mounting dir)
- Ubuntu 16.04 w/ 375.26 (K80; Pascal broken due to other issues)

**Comment by 3XX0** [comment]
Unfortunately, OpenGL is not supported for now (see #11). This is on the roadmap for 2.0 though.

**Comment by andrewseidl** [comment]
Sorry - it was my understanding that #11 specifically relates to containers which expect a display to be attached, regular old desktop apps.

In our case we're using OpenGL for remote rendering. With EGL we're able to run completely headless, don't even need Xorg running, and we can then stream the rendered images to a file or (in our case) a browser.

Everything works great when using nvidia-docker and the 367 drivers. The 375 drivers introduced glvnd, which in turn requires the EGL vendor config dirs pulled in. Everything again works great[1] using the manual workaround above of bind mounting the dirs.

[1] - there are still some issues with EGL + Pascal + certain older 375 drivers but those are also relevant on the host, not nvidia-docker related at all.
