### ISSUE TITLE
Keys for NVIDIA drivers fetched insecurely in AWS docs

### ISSUE THREAD

**Issue by anandthakker** [NVIDIA/nvidia-docker#339]
On the [AWS Instance Creation](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2#gpu-instance-creation) wiki page, the instructions for setting installing the cuda drivers include fetching the repository key insecurely (over `http`): 

```sh
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
```

I haven't been able to find a securely-hosted copy of the key (asked about it on the forum [here](https://devtalk.nvidia.com/default/topic/968891/?offset=2#5103860).  Do the maintainers here happen to know of one?  

If not, it might at least be worth sticking a warning in the docs -- and if I get a reply on the forum post I'll update here.

**Comment by flx42** [comment]
Hello @anandthakker 

Look at what we do in our CUDA Dockerfile:
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/8.0/runtime/Dockerfile#L6-11

**Comment by anandthakker** [comment]
Thanks @flx42, that's helpful.
