### ISSUE TITLE
GPU CUDA Unknown Error

### ISSUE THREAD

**Issue by httpswlt** [NVIDIA/nvidia-docker#340]
![default](https://cloud.githubusercontent.com/assets/25114312/23936943/d1fab9de-098f-11e7-86aa-1d6003807f05.png)
I'm sorry my English is very poor，but I want to ask question.
Look the picture,why did the GPU show Unknown Error when I  end of caffe.
Start,I use digits to training images.Then I want to end of digits ,but I find the www-data aready run,so I go to kill the process.
When I kill the process，then it become defunct process ,finally the cuda show Unknown Error, I don't know why?  Can you help me. Thank you very much!!

**Comment by flx42** [comment]
hello @httpswlt 
This issue doesn't seem caused by nvidia-docker. You should try reinstalling the NVIDIA driver.
If you still have the problem, you should ask help on the NVIDIA developer forum instead:
https://devtalk.nvidia.com/

**Comment by httpswlt** [comment]
oh !! It's very embarrassed. I will try to solve the problem by your suggest. Thank you for your reply.
