### ISSUE TITLE
nvidia-docker istallation issue

### ISSUE THREAD

**Issue by neenaloysius** [NVIDIA/nvidia-docker#343]
Im trying to install nvidia-docker using the given command **wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb** .  
But SSL connection is getting failed since this site is not trusted. Please look into the issue.

**Comment by flx42** [comment]
You might be missing the `ca-certificates` package.

**Comment by neenaloysius** [comment]
Could you please mention which ca certificate i should download? On 21 Mar 2017 10:04 am, Felix Abecassis <notifications@github.com> wrote:You might be missing the ca-certificates package.

**Comment by flx42** [comment]
`apt-get install -y ca-certificates`

**Comment by flx42** [comment]
@neenaloysius did it work?

**Comment by neenaloysius** [comment]
Yeah....  The nxt day tht link was wrking for me without doing any certificate installation. 😊On 24 Mar 2017 10:29 pm, Felix Abecassis <notifications@github.com> wrote:@neenaloysius did it work?
