### ISSUE TITLE
CUDA error: invalid device function

### ISSUE THREAD

**Issue by helinwang** [NVIDIA/nvidia-docker#346]
My host machine is installed with driver 375.39, Cuda 8.0
My source code is compiled with cuda 7.5.
Can I run the compiled binary with nvidia-docker?

Currently I am getting error:
```text
CUDA error: invalid device function
```
From this [post](https://github.com/BVLC/caffe/issues/138#issuecomment-185245074), feels like I need to compile my code again with CUDA 8.0?
But from my understanding, container just need to load the correct CUDA so files (e.g., libcudart.so) and nvidia userspace driver (libcuda.so) (and nvidia-docker automatically does so) I should be fine. Is there a requirement that program need to be compiled with correct cuda version as well?

**Comment by flx42** [comment]
Do you have a Pascal GPU?
IIRC in CUDA 7.5, some libraries from the CUDA toolkit didn't have PTX code, so they can't run on newer GPUs.

**Comment by helinwang** [comment]
@flx42 Thanks for replying! It's a titanx, yes I think it's a Pascal GPU.
Could you please let me know if my following understanding is correct?

nvidia-docker will load the appropriate libcuda.so according to host driver version.
Since my docker image is pacakged with CUDA 7.5, it will have correct cuda 7.5 so files.
But the problem here is that CUDA 7.5 don't have PTX code, it can not be run on new GPUs.

**Comment by helinwang** [comment]
@flx42 Another question, does nvidia-docker auto mount CUDA so files as well (e.g., libcudart.so). If so, how does it know which cuda verison to mount?

**Comment by flx42** [comment]
Titan X could be Maxwell or Pascal, what's the output of `nvidia-smi`?
If you are indeed trying to use Caffe, then yes you should switch to CUDA 8.0, it will be faster and simpler.

> Does nvidia-docker auto mount CUDA so files as well (e.g., libcudart.so). If so, how does it know which cuda verison to mount?

There is some confusion here, libcuda.so comes from the **driver** and it is mounted at start time by nvidia-docker. No CUDA file is mounted, you don't even need the CUDA toolkit to be installed on the host, only the driver.
libcuda**rt**.so comes from the **toolkit** and is included in the CUDA image.

**Comment by helinwang** [comment]
@flx42 Thank you for the detailed explanation as well as how to check if titanx is pascal. I just checked it's pascal:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 0000:01:00.0      On |                  N/A |
| 23%   29C    P8    10W / 250W |    103MiB / 12188MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1580    G   /usr/lib/xorg/Xorg                             101MiB |
+-----------------------------------------------------------------------------+
```

**Comment by flx42** [comment]
Ok, so in some cases an application compiled with CUDA 7.5 might work, it depends if you compiled the application itself with PTX, and I think it also depends on which libraries from the CUDA toolkit you are using.

**Comment by helinwang** [comment]
I see, thank you! A lot of great information!
I am closing this issue now.

**Comment by xuyifeng-nwpu** [comment]
@helinwang  @flx42 
Thanks, I learned much from your discussion.  Now i encounted this same problem.  

Can i update the cuda  of docker's containter  from 7.5  to 8.0    in the environment of nvidia-docker, not pulling the new docker's image.

When i install the new cuda 8.0 in docker container, the error message showd :
"sudo: /etc/sudoers is world writable"

Greatly appreciate if you could answer!

**Comment by flx42** [comment]
@xuyifeng-nwpu this doesn't seem to be an error related with CUDA, I can't help you here.
