### ISSUE TITLE
Running Nvidia Docker the first time results in Timeout

### ISSUE THREAD

**Issue by sargun** [NVIDIA/nvidia-docker#347]
The first time we invoke Nvidia Docker on the host, it fails. The log output typically follows this pattern:
```

nvidia-docker-plugin[2198]: /usr/bin/nvidia-docker-plugin | 2017/03/23 14:14:18 Received activate request
nvidia-docker-plugin[2198]: /usr/bin/nvidia-docker-plugin | 2017/03/23 14:14:18 Plugins activated [VolumeDriver]
nvidia-docker-plugin[2198]: /usr/bin/nvidia-docker-plugin | 2017/03/23 14:14:18 Received create request for volume 'nvidia_driver_375.39'
dockerd[3897]: time="2017-03-23T14:14:25.480339459Z" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeDriver.Create: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: EOF, retrying in 1s"
dockerd[3897]: time="2017-03-23T14:14:26.480907606Z" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeDriver.Create: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=42 with Body length 0, retrying in 2s"
dockerd[3897]: time="2017-03-23T14:14:28.481423400Z" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeDriver.Create: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=42 with Body length 0, retrying in 4s"
dockerd[3897]: time="2017-03-23T14:14:32.481817020Z" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeDriver.Create: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=42 with Body length 0, retrying in 8s"
titus-log-shipp[5620]: Posting 29 entries
dockerd[3897]: time="2017-03-23T14:14:40.482246102Z" level=error msg="Handler for POST /volumes/create returned error: create nvidia_driver_375.39: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=42 with Body length 0"
titus-executor[10726]: Cannot create Titus executor: Error response from daemon: create nvidia_driver_375.39: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: http: ContentLength=42 with Body length 0
```

On a subsequent invocation, it appears to work. From this, I can only ascertain that there is some cost to creating the volume (the first time). I'm curious as to what that cost is, and if there is any way we can reduce it.

**Comment by flx42** [comment]
How many GPUs do you have? If the kernel module is not loaded and you have 4-8 GPUs, the initialization time might be causing an issue here.

But that should only be an issue if you start nvidia-docker-plugin and then almost immediately request a volume. Is that the case? If not, I would need to review this code path again, it's been a while.

Could be related to https://github.com/NVIDIA/nvidia-docker/issues/123

**Comment by flx42** [comment]
To troubleshoot, you could try to set the [legacy persistence mode](http://docs.nvidia.com/deploy/driver-persistence/#persistence-mode) with `sudo nvidia-smi -pm 1` before starting `nvidia-docker-plugin`.

**Comment by flx42** [comment]
@sargun any update for this issue?

**Comment by cancan101** [comment]
This is related to #123 and yes, I am still seeing this issue on `1.0.1`.

**Comment by CheatEx** [comment]
I had exactly same issue when tried to run a contained from user data script on EC2's p2.xlarge instances. EBS warmup as suggested in #379 helped. But I've found that reading only nvidia installation directories is enough. Something like
`# find /usr/lib/nvidia-375/ /usr/lib32/nvidia-375/ -type f | xargs -I{} cat {} > /dev/null`

**Comment by 3XX0** [comment]
See #123 and #379
