### ISSUE TITLE
CentOS5 support

### ISSUE THREAD

**Issue by soumith** [NVIDIA/nvidia-docker#348]
I'm terribly sorry to ask for this and everyone is going to hate me, but CentOS5 doesn't work with nvidia-docker. Does anyone know what are the starting steps to investigate or help fix this?

Why the hell would I want to do that? I am trying to build manylinux pip wheels that want to use a really old GLIBC (so that the binaries can run pretty much anywhere).

This is the docker file for manylinux: https://github.com/pypa/manylinux/blob/master/docker/Dockerfile-x86_64

I'm trying to get CUDA going on this.

**Comment by soumith** [comment]
cc: @lukeyeager

**Comment by lukeyeager** [comment]
@flx42, @3XX0 See https://github.com/pytorch/pytorch/issues/566 for context.

@soumith FYI, in an attempt to head off this request, I looked into getting a new version of `manylinux` started (on a platform which CUDA actually supports): https://github.com/pypa/manylinux/issues/96. Unfortunately, no movement on that yet.

**Comment by soumith** [comment]
ah ok thanks. I will continue to do what I used to do, which is build on CentOS6 and name my files `manylinux` then (yes i'm a bad person)

**Comment by 3XX0** [comment]
This is a bad idea, recent CUDA releases are not supported on CentOS 5 and linking against an old CUDA release is probably not what you want.

Do you control the sources linking to the GlibC?

**Comment by soumith** [comment]
Yea, I think i'll just use CentOS6 and cheat on the manylinux convention for now. I'll follow pypa/manylinux#96 for progress
