### ISSUE TITLE
systemd is needed during CentOS (prior to CentOS 7) installation

### ISSUE THREAD

**Issue by alanlun516** [NVIDIA/nvidia-docker#354]
$ rpm -i https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0/nvidia-docker-1.0.0-1.x86_64.rpm
error: Failed dependencies:
	systemd is needed by nvidia-docker-1.0.0-1.x86_64

However, CentOS (prior to CentOS 7) does not use systemd.

**Comment by 3XX0** [comment]
Docker (and thus NVIDIA Docker) is not supported on CentOS < 7 (see [here](https://docs.docker.com/engine/installation/linux/centos/))
