### ISSUE TITLE
x nvidia-docker: Can't create 'nvidia-docker'

### ISSUE THREAD

**Issue by zsong** [NVIDIA/nvidia-docker#355]
$ sudo tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker*.tar.xz && rm /tmp/nvidia-docker*.tar.xz

Got Error on Mac OS 12

    x nvidia-docker: Can't create 'nvidia-docker'
    x nvidia-docker-plugin: Can't create 'nvidia-docker-plugin'
    tar: Error exit delayed from previous errors.

**Comment by flx42** [comment]
Mac OS is not officially supported, so we won't fix this issue, sorry!

**Comment by zsong** [comment]
Thanks.
