### ISSUE TITLE
It seams not support docker-ce

### ISSUE THREAD

**Issue by Splendon** [NVIDIA/nvidia-docker#360]
The docker is using docker-ce to replace docker-engine, and nvidia-docker seems not support it.

**Comment by flx42** [comment]
Which version of `nvidia-docker` do you have? You need to upgrade to `1.0.1`

**Comment by ksnzh** [comment]
I encountered the same issue. I have upgraded from ubuntu 14.04 to ubuntu 16.04.
In ubuntu 14.04 with docker-engine, nvidia-docker works fine.
But now in ubuntu 16.04 with docker-ce, it came wrong.
```
➜  ~ docker -v
Docker version 17.03.1-ce, build c6d412e
➜  ~ nvidia-docker -v
Docker version 17.03.1-ce, build c6d412e
➜  ~ nvidia-docker run --rm nvidia/cuda nvidia-smi
container_linux.go:247: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH".

```

**Comment by ksnzh** [comment]
Yes, I'm using nvidia-docker 1.0.1.

**Comment by ksnzh** [comment]
I have downgraded docker from 17.03.1-ce to 17.03.0-ce. The error already exists.
I really have no idea what the problem is.

**Comment by flx42** [comment]
@ksnzh take a look at this thread:
https://github.com/NVIDIA/nvidia-docker/issues/349
It might help.

**Comment by ksnzh** [comment]
@flx42 `docker volume rm -f nvidia_driver_375.39` helped me.
I manually removed the volume and retried. It seems everything goes okey.

**Comment by Splendon** [comment]
@flx42 Thank you for your help, i am sorry to describe the question with simple.The details as follow:

> ~ sudo dpkg -i nvidia-docker_1.0.1-1_amd64.deb

> (Reading database ... 225827 files and directories currently installed.)
Preparing to unpack nvidia-docker_1.0.1-1_amd64.deb ...
Unpacking nvidia-docker (1.0.1-1) over (1.0.1-1) ...
Setting up nvidia-docker (1.0.1-1) ...
Setting up permissions
Job for nvidia-docker.service failed because the control process exited with error code. See "systemctl status nvidia-docker.service" and "journalctl -xe" for details.
nvidia-docker.service couldn't start.
Processing triggers for ureadahead (0.100.0-19) ..
