### ISSUE TITLE
Do you ave a plan to release the nvidia-docker UI?

### ISSUE THREAD

**Issue by yoshihingis** [NVIDIA/nvidia-docker#363]
It is not isse, only question.
I am using "Simple Docker UI" 
This tool is very useful for dokcer-users.
This tool can erase the nvidia-docker containers and the docker-images, but  can not "nvidia-docker run"

Do you have a plan to release the Nvidia-docker UI  for nvidia-docker users?

**Comment by flx42** [comment]
We weren't aware of this project, it's a nice UI but we don't plan to support it.
