### ISSUE TITLE
Unpacking nvidia-docker (1.0.1-1) over (1.0.1-1) ...

### ISSUE THREAD

**Issue by tianke0711** [NVIDIA/nvidia-docker#366]
I follow the instruction from this site: https://github.com/NVIDIA/nvidia-docker. to install  nvidia-docker on the ubuntu 16.04 server. after run the command:

 sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

there is error:

$ sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
(Reading database ... 479592 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.1-1_amd64.deb ...
Unpacking nvidia-docker (1.0.1-1) over (1.0.1-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on docker-engine (>= 1.9.0) | docker-ce | docker-ee; however:
  Package docker-engine is not installed.
  Package docker-ce is not installed.
  Package docker-ee is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 nvidia-docker

**Comment by twobombs** [comment]
It looks as though you don't have docker installed. Have you installed docker ? 
( if so, what is the output of docker info. of not, please install docker )

**Comment by tianke0711** [comment]
hi thanks for your comments.  but when I run the command , docker info, thee is error:

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

I have no sense to docker, the first time to contact it, could you tell me in detail.

**Comment by twobombs** [comment]
try: 

sudo docker info

however, because of your answer it seems docker already is installed but either an old version or to new :) let's wait for the output of your docker info.

**Comment by tianke0711** [comment]
@twobombs  thanks for your comments.

 sudo docker info
[sudo] password for challenge98:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by tianke0711** [comment]
I have solved it, just restart the ubuntu server by linux: sudo shutdown -r now
