### ISSUE TITLE
CentOS 6 container cannot use driver loaded from Fedora 25 host system

### ISSUE THREAD

**Issue by tsondergaard** [NVIDIA/nvidia-docker#367]
With a Centos 6 container it fails like this:

glxgears: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/nvidia/lib64/libGL.so.1)

It works fine with a CentOS 7 container, though.

**Comment by 3XX0** [comment]
Unfortunately, OpenGL is not supported see #11

**Comment by tsondergaard** [comment]
Okay. May I ask why are the OpenGL drivers included in the driver volume that nvidia-docker adds to the container then? Also, it works fine for me with CentOS 7. I run the container with these switches:

nvidia-docker run --rm -ti --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY ...
