### ISSUE TITLE
Requirement on read-only partition

### ISSUE THREAD

**Issue by gcs278** [NVIDIA/nvidia-docker#368]
Hello,

I have a requirement to run nvidia-docker in a system where the nvidia libraries and files are located on a read-only partition. My understanding is that nvidia-docker uses hard links to link in all of the nvidia files; therefore, the location to store the volumes must be on the same partition.

>  NVIDIA driver installation needs to live on the same partition as the volume directory of the Docker plugin.
nvidia-docker-plugin internally needs to create hard links to some driver files. Because of this, you need the NVIDIA driver (usually found under /usr) to be on the same partition as the Docker plugin volume directory (/var by default). 

Since my nvidia files are on a read-only partition, the directory (-d) for linking must be writable, to create those links. We keep our writable files in rootfs or tmpfs, but most of libraries and drivers are on a read-only partition.

Are there any workarounds for using this product in a read-only file system other than relocating our nvidia installation? (unfortunately, not an option for us) Any future efforts to address this?

**Comment by 3XX0** [comment]
Yes this is problematic and it's something that will be fixed in 2.0 leveraging libnvidia-container.
I will update the issue once we have something for you to play with

**Comment by flx42** [comment]
As a temporary workaround, you could modify this line:
https://github.com/NVIDIA/nvidia-docker/blob/v1.0.1/src/nvidia-docker-plugin/plugin_volume.go#L81
And use `nvidia.LinkOrCopyStrategy{}` instead.

**Comment by flx42** [comment]
But this would obviously copy the driver files to one of your writable partition.

**Comment by gcs278** [comment]
Great thanks @3XX0 and @flx42. What's the timeline for v2.0?

**Comment by flx42** [comment]
We released the first component towards 2.0:
https://github.com/NVIDIA/libnvidia-container
But we need proper packaging of this library + packaging of nvidia-docker 2.0.

We hope it will be available within a month or two.
