### ISSUE TITLE
`nvidia-docker build` could not identify GPU architecture

### ISSUE THREAD

**Issue by idealhack** [NVIDIA/nvidia-docker#370]
I found this problem when building caffe and opecv 3, The cmake scripts will build with all architectures to shared libraries.

For now I have to set `-DCUDA_ARCH_NAME=Pascal` for caffe and `-D CUDA_GENERATION=Pascal` for opencv 3.

Does nvidia-docker plan to support this?

**Comment by flx42** [comment]
Hello @idealhack, during a `docker build`, it's not possible to have access to GPUs, therefore the auto-detection of the GPU architecture made by some projects won't work.
But AFAIK, Caffe fixed this problem already and will build for Pascal by default.

**Comment by idealhack** [comment]
Hi @flx42, thanks for your explanation and confirmation!

Hmm, seems they still use "[all](https://github.com/BVLC/caffe/blob/master/cmake/Cuda.cmake#L60)" by default.

**Comment by flx42** [comment]
`All`, includes `Pascal`.

**Comment by idealhack** [comment]
Oh I get your point. I want to build for `Pascal` only ;) Thanks!
