### ISSUE TITLE
Docker version dependency breaks nvidia-docker again

### ISSUE THREAD

**Issue by varunagrawal** [NVIDIA/nvidia-docker#372]
So out of nowhere I am getting the "nvidia-docker | <datestring> Error: unsupported Docker version" error again, this time for docker version `v17.03.1-ce`.

I fixed it by building from source after updating the version string. However, since this is a recurring issue, would it be possible to better maintain docker version dependency instead of a hard coded value in the source code?

**Comment by flx42** [comment]
You mean [this](https://github.com/NVIDIA/nvidia-docker/commit/7dbc2cafec212f197ca2212395c102ea5833dbac)?

**Comment by grisaitis** [comment]
I'm seeing this issue on some machines but not others, with `Docker version 17.03.1-ce, build c6d412e`.

Do you have any idea what might cause this?

```
host1 $ docker --version
Docker version 17.03.1-ce, build c6d412e
host1 $ nvidia-docker ps
nvidia-docker | 2017/05/12 15:34:57 Error: unsupported Docker version
```
```
host2 $ docker --version
Docker version 17.03.1-ce, build c6d412e
host2 $ nvidia-docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
```

I'm installing nvidia-docker with the latest release (`1.0.1`), purging and reinstalling. Same for docker -- purging, then reinstalling from docker's apt repo. 

Both machines are running ubuntu 14.04, and have the same output for: 

```
$ apt-cache policy docker-ce nvidia-docker
docker-ce:
  Installed: 17.03.1~ce-0~ubuntu-trusty
  Candidate: 17.03.1~ce-0~ubuntu-trusty
  Version table:
 *** 17.03.1~ce-0~ubuntu-trusty 0
        500 https://download.docker.com/linux/ubuntu/ trusty/stable amd64 Packages
        100 /var/lib/dpkg/status
     17.03.0~ce-0~ubuntu-trusty 0
        500 https://download.docker.com/linux/ubuntu/ trusty/stable amd64 Packages
nvidia-docker:
  Installed: 1.0.1-1
  Candidate: 1.0.1-1
  Version table:
 *** 1.0.1-1 0
        100 /var/lib/dpkg/status
```

**Comment by flx42** [comment]
Are you sure you aren't using an older version of the `nvidia-docker` binary? What's the output of `nvidia-docker version`?

**Comment by grisaitis** [comment]
Ah ha! Good question. I wasn't able to execute that command (it failed with the same error message), but I checked `which nvidia-docker` and discovered that two `nvidia-docker`s were in my path:

```
$ ls -l /usr/local/bin/nvidia-docker
-rwxr-xr-x 1 root root 6781104 Jun 27  2016 /usr/local/bin/nvidia-docker
$ ls -l /usr/bin/nvidia-docker
-rwxr-xr-x 1 root root 6799520 Mar  2 20:54 /usr/bin/nvidia-docker
```

Removing the one at `/usr/local` fixed the issue.
