### ISSUE TITLE
Error response from daemon: manifest for floydhub/dl-docker:gpu not found

### ISSUE THREAD

**Issue by EslamJamal** [NVIDIA/nvidia-docker#373]
I'm trying to run [this](https://hub.docker.com/r/floydhub/dl-docker/) docker image as a container, but i got this error while building the image: 

Configuring incomplete, errors occurred!
See also "/root/caffe/build/CMakeFiles/CMakeOutput.log".
See also "/root/caffe/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c git clone -b ${CAFFE_VERSION} --depth 1 https://github.com/BVLC/caffe.git /root/caffe && 	cd /root/caffe && 	cat python/requirements.txt | xargs -n1 pip install && 	mkdir build && cd build && 	cmake -DUSE_CUDNN=1 -DBLAS=Open .. && 	make -j"$(nproc)" all && 	make install' returned a non-zero code: 1

Then after applying this command in the link : 

GPU Version
nvidia-docker run -it -p 8888:8888 -p 6006:6006 -v /sharedfolder:/root/sharedfolder floydhub/dl-docker:gpu bash

i got this error : 
nvidia-docker | 2017/04/28 16:20:38 Error: Error response from daemon: manifest for floydhub/dl-docker:gpu not found

What is the problem exactly? How to fix it ?

**Comment by flx42** [comment]
This is not a `nvidia-docker` issue. Your `docker build` command failed, thus your image doesn't exist.
