### ISSUE TITLE
Get GPU ID according to minor number?

### ISSUE THREAD

**Issue by junjieqian** [NVIDIA/nvidia-docker#376]
Hi, I have one question using the nvml package in our docker-wrapper, that we only have the minor number (e.g. `/dev/NVidia$MinorNumber`) passed to the docker-wrapper, is there a way to get the GPU ID based on the minor number?

One way would be query all GPUs and compare the minor number with the one passed in, but this is not efficient.
Any suggestions? Thanks

**Comment by flx42** [comment]
Do you want the UUID? (as returned by `nvidia-smi -L`)
Or do you want the ID in PCIe order? (as returned by `nvidia-smi`).

**Comment by junjieqian** [comment]
Hi @flx42 , thank you for your attention! I want the index that can be used for function `deviceGetHandleByIndex` from the MinorNumber.

Now, we have the minor number passed to the docker-wrapper, and we want to have `nvml` package in our docker-wrapper. So, to create a device with `NewDevice` in `mvml.go`, I am trying to get the GPU index from minor number.

**Comment by flx42** [comment]
There is no way to do that in NVML. The device minor numbering is different from the PCIe ordering.

**Comment by junjieqian** [comment]
Thanks for the explanation!

**Comment by pwm** [comment]
@junjieqian 

I'm late to the party, but afaik since CUDA 7 you can set the following env var:
`CUDA_DEVICE_ORDER=PCI_BUS_ID`
to tell CUDA to use PCI bus IDs that nvidia-smi and other non-cuda programs use.

See here: http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
Also there this little util: https://github.com/al42and/cuda-smi

**Comment by flx42** [comment]
@pwm sure, but the device minor doesn't necessarily match the PCI bus order.

**Comment by pwm** [comment]
@flx42 True, sorry, I should have read the question more thoroughly. I thought he meant the cuda/non-cuda id difference, which used to be a problem.

**Comment by cliffwoolley** [comment]
@flx42 -- RM does always enumerate in PCI bus order.  It's only CUDA that chooses sometimes to reorder them (unless you tell it not to, as with the above env var).

**Comment by 3XX0** [comment]
@cliffwoolley The question is about device minor IDs, and @flx42 is correct there is no way to know the correct mappings without enumerating all the devices. This is mostly because of legal reason (i.e. GPL symbols)

**Comment by cliffwoolley** [comment]
Well for the device minor ID from the kernel perspective sure, but the OP asked about "minor ID" in the context of `/dev/nvidia${minor}`, which is the RM enumerant.  So... ?  :)

**Comment by 3XX0** [comment]
No `/dev/nvidia${minor}` doesn't match RM enumeration, that's the problem:

```
$ nvidia-container-cli info
NVRM version:   384.111
CUDA version:   9.0

Device Index:   0
Device Minor:   1
Model:          GeForce GTX TITAN X
GPU UUID:       GPU-836c0c09-6a27-f2b2-0451-9c0aa57b9441
Bus Location:   00000000:01:00.0
Architecture:   5.2

Device Index:   1
Device Minor:   0
Model:          GeForce GTX 970
GPU UUID:       GPU-c0ddf4f7-2a0a-718b-61a4-d26fe655b826
Bus Location:   00000000:02:00.0
Architecture:   5.2
```
