### ISSUE TITLE
cudaErrorInsufficientDriver event though driver and cuda version match host

### ISSUE THREAD

**Issue by hokiegeek2** [NVIDIA/nvidia-docker#378]
Hi Everyone,

Getting following error for the cuda samples :
CUDA error at  ../../common/inc/helper_cuda.h:1133 code=35(cudaErrorInsufficientDriver) "cudaGetDeviceCount(&device_count)"

The container is from an instance that extends [nvidia-cuda](https://hub.docker.com/r/nvidia/cuda/) by bundling in the cuda-samples library
Confirmed the following:
1. nvidia-smi yields same result in the container as on the host--including the exact driver version and number of GPU devices.
2. the cat /usr/local/cuda/version.txt shows the host and container CUDA versions match exactly
3. The clock example works on the host
4. I first tried this by building the clock example within the container. I then mounted the /usr/local/cuda directory into the container and I still get this error. 
5. The host linux version is 7.1 whereas the image is 7.3. Would the linux version be the problem?

Any ideas are very much appreciated.

Thanks

--John

**Comment by flx42** [comment]
Thanks for the detailed bug report! 

1. What's the driver version?
2. What's the output of `ldconfig -p | grep 'libcuda\|libnvidia'` inside the container?

**Comment by hokiegeek2** [comment]
Hey Felix,

Thanks for responding so quickly!

1. driver = 375.39 and CUDA version is 8.0.61
2. I left work, so I will get this info to you tomorrow. I do recall some differences such as libcuda, libOpenCL, libGLX, libGLESv2, libGLESv1, and libEGL_nvidia, and libvdpau_nvidia ONLY being on the host

Thanks

--John

**Comment by hokiegeek2** [comment]
A few more details:

1. Nvidia Driver--I executed docker inspect upon the container and I can see that the host nvidia driver directory is mounted in as /usr/local/nvidia, so that's correct and it demonstrates how nvidia-docker obviates the need to install the Nvidia driver because the host driver is mounted in as /usr/local/nvidia. I know this is not news, but I wanted to provide this detail to noobs like me. :)

2. Mounted host cuda--I mounted in the host CUDA directory (/usr/local/cuda) to the container and I am still seeing this error. Again, same CUDA binaries in container because I am mounting the host /usr/local/cuda directory and there still appears to be a mismatch between the CUDA version and the driver.

3. nvidia-smi--this works correctly within the container and the output of this command matches what I see on the host.

Is it possible that the nvidia-docker install rpm did not pull in something correctly due to network issues or something else?

--John

**Comment by hokiegeek2** [comment]
@flx42 Thanks! It was a set of three missing libraries that together caused this error: 
libcuda.so.1
libcuda.so
libcudart.so

I recommend updating the README file accordingly

Thanks again for your help--much appreciated!

--John

**Comment by flx42** [comment]
@hokiegeek2 are you saying the libraries were missing inside the container? I'm not sure how you solved it then.

**Comment by hokiegeek2** [comment]
@flx42 When I did the nvidia-docker install it appears that the required libraries directory (lib64) was not mounted, so we were missing a bunch of 'em in the container upon startup.

**Comment by HenryVargasRivera** [comment]
@hokiegeek2 Hello, I get the same error when trying to activate Mercury Playblack Engine (CUDA) in Adobe Premiere Pro CC 2019. Can you tell me how you solved it? Or what do I have to do? How did you do that about libraries? I've been trying to activate CUDA for days and I'm very frustrated. I would really appreciate it if you would help me. Thank you.

**Comment by hokiegeek2** [comment]
@HenryVargasRivera Hi, as I wrote above in this thread, there were three .so files missing in the container, so I mounted them in via the docker -v command

**Comment by Nicerova7** [comment]
For Windows users, I wrote a blog on medium, please check in this: 
https://medium.com/@nicerova/cuda-on-windows-the-definitive-guide-b4130b9fc419
To solve this you need to install again but as indicated in the guide above.
