### ISSUE TITLE
Running nvidia-docker inside a docker container

### ISSUE THREAD

**Issue by Alfredvc** [NVIDIA/nvidia-docker#380]
I am currently developing software to automate the running of experiments (hyperparameter tuning, etc).

Ideally I would have a master docker container per machine that can spawn multiple gpu containers with nvidia-docker, one for each experiment.

Is there any way to pass nvidia-docker to the docker container, in the same way that one can pass the docker socket?

**Comment by flx42** [comment]
You closed the issue, so maybe you found a solution already. But the solution we've been using is to call the REST API of `nvidia-docker` from inside a docker client container. This will give you the CLI arguments to add to enable GPU support.
See our [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#version-10)

**Comment by Alfredvc** [comment]
Thanks for your response! That worked :)

**Comment by AK-ayush** [comment]
@Alfredvc @flx42 
Hi, I too want to use nvidia-dcoker from inside a running eclipse/che container. The eclipse/che container communicate to system docker daemon through api and start the container using docker but it is needed to start container using nvidia-docker otherwise it is not able to detect the gpu hardware. 
Any suggestion will be highly appreciated.

**Comment by Alfredvc** [comment]
Hi @AK-ayush,

This was a while ago, but if i remember correctly I used the suggestion given by @flx42.

As stated in [https://github.com/NVIDIA/nvidia-docker/wiki/Internals](https://github.com/NVIDIA/nvidia-docker/wiki/Internals), you can use the REST api to get the parameters needed to enable cuda support without using nvidia-docker.

This is done by executing 

```
docker run -ti --rm `curl -s http://localhost:3476/docker/cli` nvidia/cuda nvidia-smi
```

However, when executing this inside a docker container, localhost will not point to the correct address. In this case you either have to make localhost inside the container point to localhost in the host machine, or change the address in the command to point to the host machine.

For example:

```
docker run -ti --rm `curl -s http://HOST_MACHINE_ADDRESS:3476/docker/cli` nvidia/cuda nvidia-smi
```

**Comment by flx42** [comment]
If you use `--net=host`, you can just use `localhost`.

**Comment by AK-ayush** [comment]
Thanks @Alfredvc @flx42
I have resolved my issue. Thanks again
