### ISSUE TITLE
Running nvidia-docker on NVIDIA's AWS AMIs

### ISSUE THREAD

**Issue by p8952** [NVIDIA/nvidia-docker#381]
I'm trying to run Keras via nvidia-docker on AWS using the official NVIDIA AMIs: https://aws.amazon.com/marketplace/pp/B00FYCDDTE

The AMI seems to ship with the drivers already installed and loaded:

```
[ec2-user@ip-172-31-47-241 ~]$ yum info nvidia
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
2 packages excluded due to repository priority protections
Installed Packages
Name        : nvidia
Arch        : x86_64
Epoch       : 2
Version     : 352.99
Release     : 2017.03.104.amzn1
Size        : 185 M
Repo        : installed
Summary     : NVIDIA userspace graphics card driver and libraries
URL         : http://www.nvidia.com/object/unix.html
License     : NVIDIA
Description : This package contains the userspace components of the NVIDIA
            : driver. This includes libraries specialized to use the GPU for
            : computation. The libraries included are
            :
            : * CUDA
            : * OpenCL
            : * OpenGL
            : * VDAPU
```

```
[ec2-user@ip-172-31-47-241 ~]$ lsmod | grep nvidia
nvidia_uvm             69423  0
nvidia               8636586  1 nvidia_uvm
drm                   335598  2 nvidia
i2c_core               54256  2 nvidia,drm
```

However `nvidia-modprobe` does not seem to be installed, which prevents me from using nvidia-docker:

```
[ec2-user@ip-172-31-47-241 ~]$ nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2017/05/15 10:56:24 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?
```

Ideally I'd like to make use of the official AMIs to simplify the process of driver installation/upgrades, is this/can this be a supported configuration?
 
The other option is to manually install the drivers including `nvidia-modprobe` on Ubuntu/CentOS which is a fairly cumbersome process.

**Comment by flx42** [comment]
It's likely a bug that `nvidia-modprobe` is missing from this official AMI. I will check if we can add it to the next version of this AMI.

**Comment by flx42** [comment]
@p8952 this is a NVIDIA GRID AMI, it's handled by a different team. Could you check the official CUDA AMI? If it also doesn't have `nvidia-modprobe`, we will fix that promptly.

**Comment by p8952** [comment]
@flx42, is this the right one?

https://aws.amazon.com/marketplace/pp/B01LZMLK1K

**Comment by p8952** [comment]
I can confirm that the above image, `NVIDIA CUDA Toolkit 7.5 on Amazon Linux`, does contain the `nvidia-modprobe` and works fine.

Thanks!

**Comment by flx42** [comment]
The driver on this AMI is the driver for CUDA 7.5. If that's a problem (e.g. you need to run CUDA 8.0) then you can't use this AMI. You can use `nvidia/cuda:7.5-devel` if CUDA 7.5 is fine for you.
