### ISSUE TITLE
Check failed: error == cudaSuccess (3 vs. 0)  initialization error

### ISSUE THREAD

**Issue by zhangfang615** [NVIDIA/nvidia-docker#382]
Hi,

I just updated caffe to version 0.16. When I ran a multi-process job with GPU mode, it gave the error: Check failed: error == cudaSuccess (3 vs. 0)  initialization error

Before the update, the job could ran successfully.  

What should I do in this situation? 

Thanks!

Fang

**Comment by lxx1884896** [comment]
hello, I have met the same problem , have you had the solution  yet?
