### ISSUE TITLE
Error: unsupported CUDA version: driver 0.0 < image 8.0.61

### ISSUE THREAD

**Issue by soumenms2015** [NVIDIA/nvidia-docker#384]
Hello, CUDA was working fine with Nvidia-378.39. As the Nvidia 378.39 was having display issue, so I had to upgrade it to 381.22 via dev of  ubuntu-16.04LTS. Now the display issue is fixed but CUDA is not working. Although I checked that CUDA is properly installed when I checked with nvcc --version: Found this 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

I am using GeForce-840M graphics. 

My error is : nvidia-docker | 2017/05/22 10:21:16 Error: unsupported CUDA version: driver 0.0 < image 8.0.61

**Comment by tomjaguarpaw** [comment]
@flx42 Could you please link to the duplicate issue?
