### ISSUE TITLE
Error: unsupported CUDA version: driver 0.0 < image 8.0.61

### ISSUE THREAD

**Issue by soumenms2015** [NVIDIA/nvidia-docker#385]
If I type nvidia-smi,

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 840M        Off  | 0000:04:00.0     Off |                  N/A |
| N/A   53C    P0    N/A /  N/A |    208MiB /  4044MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1206    G   /usr/lib/xorg/Xorg                             175MiB |
|    0      2489    G   compiz                                          31MiB |
+-----------------------------------------------------------------------------+

I am using NVIDIA-381.22 and CUDA8.0
If type nvcc --version.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

It was working fine previously before upgrading the driver to 381.22 from 378.39. I upgraded from dev package of Ubuntu 16.04 LTS

**Comment by flx42** [comment]
Try to compile and launch a CUDA sample like `deviceQuery` in `/usr/local/cuda/samples/1_Utilities/deviceQuery`.

**Comment by soumenms2015** [comment]
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

**Comment by flx42** [comment]
This looks like a problem with your driver installation, not with `nvidia-docker`. You should try to cleanly uninstall then install the driver. Since you are on Ubuntu 16.04, please do *NOT* use the graphics PPA. Install the package `nvidia-375` instead.

**Comment by soumenms2015** [comment]
I said already , I had installed 378.39 which had display issue so I upgraded to 381.22 . After that the CUDA is not working. I installed drivers from install packages not by ppa . So you still want me to install 378 which still has display issue while resuming after sleep.

**Comment by flx42** [comment]
No, you should install drivers 375. Driver branch 378 is not supported anymore.
This is a problem for the developer forum anyway, please ask your question there: https://devtalk.nvidia.com/

**Comment by soumenms2015** [comment]
Ok. by the way, I can't install 375 from software package as it will automatically install the 378 anyway. So in that case, I have to disable ppa and then I can only install 375
