### ISSUE TITLE
Caffe 7.5: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by andyhx** [NVIDIA/nvidia-docker#391]
hi, everyone , I use https://hub.docker.com/r/kaixhin/cuda-caffe/
my version7.5
kaixhin/cuda-caffe   7.5 
and I am able to run the author training mnist ,that means I am able to use the gpu 
 but I try to build another version of caffe,s,similar to author's program , I build successfully but when  I  train the model , I can not use  the GPU ,an
error occured :
 Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version, I can't use the gpu,
and I copy the author caffe  and rebuild it ,and test the gpu, errors occured the same,what is problem ,do  I need set something to build an similar program ?

Is it possiable to use his cuda environment to build an another  caffe program！
my host pc:
cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
GCC version:  gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2) 
 host  nvidia-smi
Wed May 31 18:49:52 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 0000:03:00.0     Off |                  N/A |
| 49%   83C    P2   200W / 250W |   4947MiB /  6142MiB |     96%      Default |

thanks in advanced!

**Comment by andyhx** [comment]
./deviceQuery  info is something like this:

/usr/local/cuda/samples/bin/x86_64/linux/release$ ./deviceQuery  
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 980 Ti"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 6143 MBytes (6440894464 bytes)
  (22) Multiprocessors, (128) CUDA Cores/MP:     2816 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 3 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = GeForce GTX 980 Ti

**Comment by 3XX0** [comment]
It's probably due to your image.
What's the output of `nvidia-docker run --rm nvidia/cuda:7.5-runtime nvidia-smi`?
