### ISSUE TITLE
can't run a script on GPU after installing NVIDIA Docker

### ISSUE THREAD

**Issue by sixtinedpdc** [NVIDIA/nvidia-docker#392]
Hi everyone,
I've installed a NVIDIA Docker, then I tried to run this script: https://github.com/bstriner/keras-adversarial, which works perfectly, but only on CPU and not on GPU.
I've done some tests like:
os.environ["DEVICE"]="cuda"
pygpu.test()
and it works perfectly too. 
In the theanorc file, DEVICE is set as 'cuda'.
When I do the following test:
from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
It prints 'Used the cpu'.
So I don't understand why the script can't run on GPU.
Thanks,

Sixtine

**Comment by bstriner** [comment]
When you run

```python
os.environ["DEVICE"]="cuda"
pygpu.test()
```
for values like `cuda0:0`, `cuda0:1`, what device name does it print out? Does it match your gpu?

**Comment by bstriner** [comment]
What host OS? How are you installing python, libgpuarray, theano, keras, etc. on the docker image? (I don't know which parts are preinstalled on the image)

**Comment by flx42** [comment]
It doesn't seem like an issue related to `nvidia-docker`, so I'm closing this issue.
