### ISSUE TITLE
nvidia-docker.service couldn't start

### ISSUE THREAD

**Issue by cn3c3p** [NVIDIA/nvidia-docker#394]
Job for nvidia-docker.service failed because the control process exited with error code

6月 04 09:52:21  xxx systemd[1]: Failed to start NVIDIA Docker plugin.
6月 04 09:52:21 xxx systemd[1]: nvidia-docker.service: Unit entered failed sta
6月 04 09:52:21 xxx systemd[1]: nvidia-docker.service: Failed with result 'exi
6月 04 09:52:23 xxx systemd[1]: nvidia-docker.service: Service hold-off time o
6月 04 09:52:23 xxx systemd[1]: Stopped NVIDIA Docker plugin.
6月 04 09:52:23 xxx systemd[1]: nvidia-docker.service: Start request repeated 
6月 04 09:52:23 xxx systemd[1]: Failed to start NVIDIA Docker plugin.
HOW TO FIX?

**Comment by flx42** [comment]
What's the full log? Please report the full output of `journalctl -u nvidia-docker`. Be careful, you truncated some lines above.
Also, is the NVIDIA driver correctly installed? What's the output of `nvidia-smi`?

**Comment by cn3c3p** [comment]
MY nvidia-docker IN debian9 can working, but another issue ：I can't apt install any software.
E: 软件包 nvidia-docker 需要重新安装(E:nvidia-docker NEED REINSTALL)
So,I try to fix new problem:
root@cn3c3p:~# sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
(正在读取数据库 ... 系统当前共安装有 186135 个文件和目录。)
正准备解包 .../nvidia-docker_1.0.1-1_amd64.deb  ...
invoke-rc.d: unknown initscript, /etc/init.d/nvidia-docker not found.
dpkg: 警告: 子进程 旧的 pre-removal 脚本 返回错误状态 100
dpkg: 现在尝试使用新软件包所带的脚本...
invoke-rc.d: unknown initscript, /etc/init.d/nvidia-docker not found.
dpkg: 处理归档 /tmp/nvidia-docker_1.0.1-1_amd64.deb (--install)时出错：
 子进程 新的 pre-removal 脚本 返回错误状态 100
invoke-rc.d: unknown initscript, /etc/init.d/nvidia-docker not found.
dpkg: 清理时出错:
 子进程 已安装 post-installation 脚本 返回错误状态 100
在处理时有错误发生：
 /tmp/nvidia-docker_1.0.1-1_amd64.deb

**Comment by flx42** [comment]
See https://github.com/NVIDIA/nvidia-docker/issues/272
