### ISSUE TITLE
Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

### ISSUE THREAD

**Issue by neuhargj** [NVIDIA/nvidia-docker#396]
sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2017/06/06 16:44:49 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

Centos 7, Nvidia Driver 375.66, Cuda 8.0.61, latest and greatest Docker and Nvidia-Docker
Everything installs fine with Cuda RPM, then on nvidia-docker run command, always comes up with this
Also tried on Ubuntu 16.04 build with same UVM kernel module response

**Comment by flx42** [comment]
Well, is it installed? :)

**Comment by neuhargj** [comment]
haha i should've mentioned that, yeah, mod-probe --version dumps out the version info

**Comment by flx42** [comment]
`nvidia-modprobe` is different from `modprobe`.
`nvidia-modprobe` is shipped alongside our drivers.

**Comment by neuhargj** [comment]
sorry, i meant nvidia-modprobe:

[neuhargj@localhost ~]$ sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2017/06/06 16:41:42 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?
[neuhargj@localhost ~]$ nvidia-modprobe --version

nvidia-modprobe:  version 375.51  (buildmeister@swio-display-x86-rhel47-08)  Wed Mar 22 09:00:31 PDT 2017

**Comment by flx42** [comment]
Is `nvidia-modprobe -u -c=0` returning an error status code?

**Comment by neuhargj** [comment]
No error codes with: nvidia-modprobe -u -c=0, is there any sort of a script for a bare Centos 7 build?

**Comment by neuhargj** [comment]
or a any sort of script for that matter, ubuntu, centos, i've run into the same error on both builds

**Comment by flx42** [comment]
Look at our AWS tutorial:
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

**Comment by neuhargj** [comment]
@flx42 thanks for your help on this, going through the tutorial worked great, now running the tensorflow and cntk containers, thanks for all of your help

**Comment by kizombaciao** [comment]
What if I had the same above issue but with Google Cloud?  After seeing the error, I googled and followed instruction to install modprobe:

$ sudo apt install nvidia-modprobe
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nvidia-modprobe is already the newest version (361.28-1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

but I still get the same error as below regarding UVM kernel.  Any advice to try?  Thanks

**Comment by flx42** [comment]
@kizombaciao please file a new issue
