### ISSUE TITLE
centos7.0 error to use docker

### ISSUE THREAD

**Issue by longpeng2008** [NVIDIA/nvidia-docker#397]
docker: Error response from daemon: create nvidia_driver_375.51: VolumeDriver.Create: internal error, check logs for details.

**Comment by flx42** [comment]
What's the output of `nvidia-smi`? And the output of `journalctl -n -u nvidia-docker`?

**Comment by longpeng2008** [comment]
the output of journalctl -n -u nvidia-docker is follow:

_No journal files were found.
-- No entries --_


and the output of nvidia-smi is ok, because the nvidia-driver is installed by:

sudo rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
sudo rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
sudo yum install nvidia-x11-drv-375.66 nvidia-x11-drv-375.66-32bit

**Comment by longpeng2008** [comment]
my ls /var/lib/nvidia-docker/volumes/nvidia_driver/ is empty, while I copy the driver files of nvidia from /usr/lib64, it didnot solve the issue.

**Comment by longpeng2008** [comment]
I solved the problem, thank you very much.
