### ISSUE TITLE
Is there support for older versions of CUDA?  Something older than 7.0?

### ISSUE THREAD

**Issue by yeison** [NVIDIA/nvidia-docker#4]

**Comment by flx42** [comment]
Why do you want support for 6.5? Do you have a good reason to not switch to a more recent CUDA version?

**Comment by ruffsl** [comment]
I understand 6.5 is legacy, but I still see a few projects that haven't had the manpower to verify everything using newer versions of cuda. Projects like [Caffe](https://github.com/BVLC/caffe/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cuda) or [Opencv](https://github.com/Itseez/opencv/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cuda) come to my mind.
Might be nice just to offer users the tag as long as v6.5 deb is in the nvidia repo anyway :wink:

**Comment by flx42** [comment]
I'm extensively using Caffe with 7.5 and it works fine :)
But I hear you, let me investigate it and see if there is any blocking issue.

**Comment by flx42** [comment]
Looks good on our side if we stick to 6.5-19. Let's discuss the details on the PR.
