### ISSUE TITLE
nvidia-docker installation is expecting docker-engine which is deprecated

### ISSUE THREAD

**Issue by ohad7** [NVIDIA/nvidia-docker#404]
Installing nvidia-docker on ubuntu I'm getting this error : 

ubuntu@ixxx:~$ sudo dpkg -i nvidia-docker_1.0.0-1_amd64.deb 
Selecting previously unselected package nvidia-docker.
(Reading database ... 151181 files and directories currently installed.)
Preparing to unpack nvidia-docker_1.0.0-1_amd64.deb ...
Unpacking nvidia-docker (1.0.0-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on docker-engine (>= 1.9.0); however:
  Package docker-engine is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 nvidia-docker

I do have docker-ce installed, as docker-engine was replaced by docker-ce

Installing from source does work as a workaround.

**Comment by flx42** [comment]
@ohad7 you need nvidia-docker `1.0.1`

See #360
