### ISSUE TITLE
sudo nvidia-docker cp doesn't work

### ISSUE THREAD

**Issue by MtDersvan** [NVIDIA/nvidia-docker#406]
I am running an nvidia-docker on a Google Compute Engine with Teslas K80.
Not a single variation of `sudo nvidia-docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH` works, instead, literally nothing happens. In a debug mode it shows next message `DEBU[0000] copying "FILE" from "/home/"` and quits after.
How can I copy a file from a Compute Engine Instance to a nvidia-docker container? (asap)
Is there a catch? 
Thanks!

**Comment by flx42** [comment]
> In a debug mode it shows next message DEBU[0000] copying "FILE" from "/home/" and quits after.

This seems like the expected behavior?
`nvidia-docker cp` should simply call `docker cp`, so try with `docker cp` directly.

**Comment by MtDersvan** [comment]
Thanks for a quick response. The confusion was due to the way directories are referred (auto open /notebooks instead of /).
