### ISSUE TITLE
Is there any option to limit the resource for each docker image?

### ISSUE THREAD

**Issue by SuminHan** [NVIDIA/nvidia-docker#408]
I'm wondering if there's any method or option to limit the maximum usage for each docker.
Can I allocate the maximum usage of GPU for each docker, and use the one GPU simultaneously?

**Comment by flx42** [comment]
Not sure what your question is. You can use the [NV_GPU](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#gpu-isolation) environment variable to isolate specific GPUs.
And multiple containers can use the same GPU.

**Comment by SuminHan** [comment]
I mean, can I set up the maximum usage of GPU cores or memory for each docker containers?

**Comment by flx42** [comment]
No, it's not possible in our drivers, it's not a limitation of nvidia-docker itself.
