### ISSUE TITLE
This docker work on Windows 10?

### ISSUE THREAD

**Issue by SpotCrowdTech** [NVIDIA/nvidia-docker#409]
Dear,

I am about to initiate a project that requires Gstreamer being hardware accelerated by 1080 Ti / Titan X p's.
At the moment our systems run Windows 10. Because we have never used docker I am first asking it here before putting in time to learn and experiment.

Is this docker compatible?

Thank you for your understanding,
Johnny G. Mills @jgmio

**Comment by TannerFilip** [comment]
No. See #197

**Comment by SpotCrowdTech** [comment]
Thank you for the answer.

So the best option is to switch to a Linux OS?

**Comment by flx42** [comment]
Yes, it's probably the simplest option if you want to use `nvidia-docker`.
Closing.
