### ISSUE TITLE
cuda toolkit version difference between OS and docker

### ISSUE THREAD

**Issue by gnujimmik** [NVIDIA/nvidia-docker#41]
Can I install different version of the cuda toolkit from the OS? Currently I have 7.5 on my OS and would like to install 7.0 on docker for tensorflow and other usage.

**Comment by 3XX0** [comment]
Yes that's actually where NVIDIA Docker shines.
You can have different CUDA toolkits running in your containers as long as your NVIDIA drivers support it (see [CUDA requirements](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA)). In your case if you installed CUDA 7.5 on your host it means that your drivers version is 352.XX. Hence you can run CUDA 7.0 containers on it.

**Comment by flx42** [comment]
@gnujimmik Did it work? Can we close this issue?

**Comment by gnujimmik** [comment]
@3XX0 Yes! Thank you! :-)
