### ISSUE TITLE
Package sysv-rc is not installed.

### ISSUE THREAD

**Issue by AwokeKnowing** [NVIDIA/nvidia-docker#412]
I just set up fresh install of ubuntu 17.  nvidia driver is 375. I followed official steps for setting up docker-ce
now I'm following official steps for installing nvidia-docker but I get:

```
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
[sudo] password for james: 
Selecting previously unselected package nvidia-docker.
(Reading database ... 240666 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.1-1_amd64.deb ...
Unpacking nvidia-docker (1.0.1-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16); however:
  Package sysv-rc is not installed.
  Package file-rc is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Errors were encountered while processing:
 nvidia-docker
```

**Comment by AwokeKnowing** [comment]
Note, I was able to fix it after installing nvidia modprobe and then installing a .deb that sombody built for yakkety
https://github.com/NVIDIA/nvidia-docker/issues/234

supposedly all they did was change ubuntu14.04 to 16.10 and rebuild and make the deb.  I used that one (at least 8 people upvoted it) and it worked. Sounds like the deb needs to be updated.

**Comment by flx42** [comment]
Doing that would cause the deb to no longer work for 14.04 IIRC. So we would need to provide 2 sets of debs. Since we want to release nvidia-docker `2.0` soon, I don't think we will release a special deb for ubuntu 17.04.

**Comment by schwab** [comment]
The exact same issue occurs on 17.10 with nvidia 384.  Any idea how to work around this or is there a fix in the works?

**Comment by gt1967** [comment]
Hi flx42, any news about docker-nvidia 2.0 version ? the post was of july ...

**Comment by flx42** [comment]
@gt1967 @schwab  please try 2.0!
https://github.com/NVIDIA/nvidia-docker/tree/2.0
Let me know if that works for you!

**Comment by gt1967** [comment]
Thank you really nice of you !

I will try ASAP and let you know if works !
