### ISSUE TITLE
export ,then import and run, but some command is wrong

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [NVIDIA/nvidia-docker#413]
First  the container was exported to a file, then on other computer, the file imported to a image and run the image as a container.
However, some bash command such as th(the torch command) was wrong.

The first computer's environment is docker 1.12, the second one is docker 17.03.

Why? because Compatibility?

**Comment by flx42** [comment]
This issue doesn't have enough information, so I'm closing it in favor of the other issues you've open.

**Comment by flx42** [comment]
However, I don't see any reason why what you are doing would fail.
