### ISSUE TITLE
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [NVIDIA/nvidia-docker#414]
My environment:
docker 17.03.01,nvidia-docker, the driver  version of gpu is show as :

xyf@xyfpc:~$ nvidia-docker run --rm nvidia/cuda nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |

----------------------------
the error message showed after runing .
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.2/trepl/init.lua:389: /root/torch/install/share/lua/5.2/trepl/init.lua:389: /root/torch/install/share/lua/5.2/trepl/init.lua:389: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /root/torch/extra/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
	main.lua:20: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

**Comment by cliffwoolley** [comment]
Please upgrade to a 375-series driver (or later) and try again for
compatibility with the latest release of CUDA 8.

Thanks,
Cliff

**Comment by xuyifeng-nwpu** [comment]
However, the lowest version of nvidia driver supporting cuda 8.0 is 367.48.

I will try   the 375-series driver.thanks.

**Comment by cliffwoolley** [comment]
> the lowest version of nvidia driver supporting cuda 8.0 is 367.48

It depends on which 8.0 we're talking about.  :)

The initial GA1 release of CUDA 8 (numbered 8.0.44, available from
https://developer.nvidia.com/cuda-80-download-archive) used driver series
361.xx on GP100 and 367.xx on GP10x GPUs.

A subsequent GA2 release of CUDA 8 (numbered 8.0.61, available from
https://developer.nvidia.com/cuda-downloads) as well as a recent cuBLAS
patch on top of 8.0.61 have standardized on 375.xx drivers for all GPUs.

As the current nvidia/cuda image is based on the latest available CUDA 8
components, you'll need the 375-series driver.

-Cliff

------
Cliff Woolley
Director, NVIDIA Developer Technology Engineering

**Comment by xuyifeng-nwpu** [comment]
I had install nvidia driver 375.26.  
But when i run the  torch code, the error message still showed:

cuda runtime error （35）：cuda driver version is insufficient for cuda runtime version........

**Comment by cliffwoolley** [comment]
Did you restart the nvidia-docker service after updating the driver?

What is the output of nvidia-smi run from inside the container?

**Comment by xuyifeng-nwpu** [comment]
restart the nvidia-docker service:
sudo service nvidia-docker restart
[sudo] password for xyf: 
nvidia-docker stop/waiting
nvidia-docker start/running, process 4582
-----------------------------------------------------------
The output of nvidia-smi run from inside the container:
root@30b3ac3d02e5:~/sharedfolder/highway-fcn/fb.resnet.torch# nvidia-smi
bash: nvidia-smi: command not found
----------------------------------------------------------
The output of nvidia-smi run in the host
 nvidia-smi
Wed Jul  5 07:02:24 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 0000:06:00.0      On |                  N/A |
| 37%   38C    P8    21W / 300W |    143MiB /  6074MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1491    G   /usr/bin/X                                     105MiB |
|    0      2325    G   compiz                                          36MiB |
+-----------------------------------------------------------------------------+



and  the version of cuda in host is 8.0, the version of one in the docker's container is 7.5.


The below error still showed:

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8833/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:384


Thanks @cliffwoolley

**Comment by cliffwoolley** [comment]
Please show the exact 'nvidia-docker run' command you are using.

Thanks!

**Comment by xuyifeng-nwpu** [comment]
nvidia-docker run -it -p 8888:8888 -p 6006:6006 -v /home/xxx/mysharedfolder:/root/sharedfolder imageid bash
two weeks ago, the command work.   After installing the cuda 8.0 and new docker 17.03, nvidia driver375.25, the command didn't work.


Thank your quick reply!

**Comment by cliffwoolley** [comment]
In that case I've reached the end of my explanations.  @flx42?

**Comment by flx42** [comment]
Is your docker image based on `nvidia/cuda`? Or another image?

**Comment by xuyifeng-nwpu** [comment]
I had solved the question generated by the compatibility of nvidia driver and cuda.
I uninstall all nvidia driver  and nvidia-docker  then reinstall the two software.
