### ISSUE TITLE
Support 1080TI GPU / Ryzen 7

### ISSUE THREAD

**Issue by johnkelly** [NVIDIA/nvidia-docker#415]
Hi, It looks like the nvidia-docker plugin only supports up to driver 375. The 1080TI support it looks like wasn't added till 378 and the only driver that works with Ubuntu + Ryzen 1700+1080TI combo for me (without docker) is Driver 381.22.

I'd really like to able to use nvidia-docker for my projects. The error message is:

```
nvidia-docker run --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: create nvidia_driver_381.22: Error looking up volume plugin nvidia-docker: legacy plugin not found.
```

**Comment by flx42** [comment]
Hello,

Driver `381.22` should work fine. What's the output of `systemctl status nvidia-docker`?
Also, is it ubuntu 16.04?

**Comment by johnkelly** [comment]
I'll run that command after work tonight.  Yes, I'm using Ubuntu 16.04.

**Comment by johnkelly** [comment]
@flx42 Well I booted up my pc and it just worked right away. Not sure what was happening yesterday. All I can think of is that I may have upgraded to Docker 17.06-ce from 17.03-ce, but not entirely sure.
