### ISSUE TITLE
no such volume:nvidia_driver_352.63

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [NVIDIA/nvidia-docker#416]
When i doker start a container the error message showed.

Error response from daemon:error while mounting  volume'/var/lib/nvidia-docker/volumes/nvidia_driver/352.63'；no such volume:nvidia_driver_352.63.

sudo ls /var/lib/nvidia-docker/volumes/nvidia_driver/nvidia_driver
nvidia_driver_367.57
In my ubuntu, i had installed the new nvidia driver 367.57.

where can i copy the nvidia_driver_352.63?  or change the container's nvidia_driver?

**Comment by flx42** [comment]
Did you reboot your machine after changing your driver? It might have solved your problem.

Closing this one since you opened too many issues :)

**Comment by xuyifeng-nwpu** [comment]
I had solved this problem. Mkdir the new 352.63 folder.
