### ISSUE TITLE
cuda version?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [NVIDIA/nvidia-docker#417]
Is the cuda necessary to install in ubuntu and docker's container?
Must the version of cuda in ubuntu and docker's container be equal?

Is the driver of GPU necessary to install in ubuntu and docker's container?
Must the version of nvidia's driver in ubuntu and docker's container be equal?

**Comment by flx42** [comment]
>  Must the version of cuda in ubuntu and docker's container be equal?

No, you don't need to had the CUDA toolkit installed on the host. It's unnecessary.

>  Must the version of nvidia's driver in ubuntu and docker's container be equal?

You must **NOT** install the NVIDIA driver inside the container.


If you see a problem with anything above, it's probably because there is an issue in your setup (e.g.: drivers are not correctly installed).
