### ISSUE TITLE
cuda 7.5 and 8.0

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [NVIDIA/nvidia-docker#418]
@helinwang  @flx42 
Thanks, I learned much from your discussion.  Now i encounted this same problem about cuda 7.5 and 8.0.  

Can i update the cuda  of docker's containter  from 7.5  to 8.0    in the environment of nvidia-docker, not pulling the new docker's image.

When i install the new cuda 8.0 in docker container, the error message showd :
"sudo: /etc/sudoers is world writable"

Greatly appreciate if you could answer!

**Comment by helinwang** [comment]
Hi Xuyifeng,

Thanks for the kind words. Could you let us what what are you trying to do? I guess you are trying to run CUDA 8.0 instead of 7.5 in docker container? Just want to make sure I get your question correctly.
Also, could you let us know what command did you exactly run during "Can i update the cuda of docker's containter from 7.5 to 8.0 in the environment of nvidia-docker, not pulling the new docker's image."?

**Comment by xuyifeng-nwpu** [comment]
Thanks your reply.I try to run CUDA 8.0 instead of 7.5 in docker container.  Yes,your guess is so right.

I exec the commands
1.docker start  container's id
2.docker attach container's id
3.disable the nouveau
4.download the cuda's run file
5.sudo service lightdm stop
6.sudo sh cuda_8.0.***_linux.run

at this step, i cannot install the cuda8.0 in the docker container.
The steps is follow the steps of installing cuda8.0 in the host.
冒昧问一下,看你的样子 是中国人,华人吗?谢谢

**Comment by helinwang** [comment]
@xuyifeng-nwpu 是中国人哈～

You don't need to install CUDA inside host machine. Just install nvidia driver and nvidia-docker in the host machine. Everything else (CUDA, cuDNN) need to be installed inside the docker image.

**Comment by xuyifeng-nwpu** [comment]
you can connet me with 42805959@qq.com.
Let me try  uninstall cuda of host firstly.
on 23 Mar,you opened a issue about "cuda error:invalid device function".
Now I encount the same question when transfer my host's docker image to server which's GPU is k80.
How do you solve the question?

**Comment by xuyifeng-nwpu** [comment]
我尝试把host 里面的cuda卸载了,但是还是有这个问题存在>
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8833/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:384: /root/torch/install/share/lua/5.1/trepl/init.lua:384: /root/torch/install/share/lua/5.1/trepl/init.lua:384: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-8833/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	main.lua:20: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by helinwang** [comment]
>  CUDA driver version is insufficient for CUDA runtime version

Can you install the latest driver?

**Comment by xuyifeng-nwpu** [comment]
Can i connet you with qq or wechat?
i had install  the nvidia driver375.25.

**Comment by xuyifeng-nwpu** [comment]
@helinwang   As to the problem https://github.com/NVIDIA/nvidia-docker/issues/346. Do you solved it?

My host :gtx 980ti,  but  the server: k80. 
Running the code in server, the error message   "the CUDA error: invalid device function"   showed.

**Comment by flx42** [comment]
This error comes from the Docker image, closing.
