### ISSUE TITLE
nvidia-docker run doesn't honor -u flag

### ISSUE THREAD

**Issue by tomkraljevic** [NVIDIA/nvidia-docker#422]
Looks like argument parsing might be messed up.
See the weird response from nvidia-docker below.

This is making it more difficult to integrate with Jenkins properly.  Jenkins jobs really want to be able to specify the uid within the container.

```
tomk@mr-dl4:~$ docker run --rm nvidia/cuda id
uid=0(root) gid=0(root) groups=0(root)
```

```
tomk@mr-dl4:~$ docker run --rm -u`id -u`:`id -g` nvidia/cuda id
uid=1003 gid=1004
```

```
tomk@mr-dl4:~$ nvidia-docker run --rm -u`id -u`:`id -g` nvidia/cuda id
Using default tag: latest
nvidia-docker | 2017/07/08 07:48:54 Error: Error response from daemon: repository id not found: does not exist or no pull access
```

```
$ nvidia-docker version
NVIDIA Docker: 1.0.1

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by flx42** [comment]
Yes, this particular syntax is not supported by our wrapper, you need a space after the `-u`:
```
$ nvidia-docker run --rm -u`id -u`:`id -g` nvidia/cuda id
Using default tag: latest
nvidia-docker | 2017/07/08 10:25:43 Error: Error response from daemon: repository id not found: does not exist or no pull access

$ nvidia-docker run --rm -u `id -u`:`id -g` nvidia/cuda id
uid=1000 gid=1000 groups=1000
```

**Comment by tomkraljevic** [comment]
thanks, that workaround did the trick.

On Jul 8, 2017, at 10:26 AM, Felix Abecassis <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, this particular syntax is not supported by our wrapper, you need a space after the -u:

$ nvidia-docker run --rm -u`id -u`:`id -g` nvidia/cuda id
Using default tag: latest
nvidia-docker | 2017/07/08 10:25:43 Error: Error response from daemon: repository id not found: does not exist or no pull access

$ nvidia-docker run --rm -u `id -u`:`id -g` nvidia/cuda id
uid=1000 gid=1000 groups=1000
