### ISSUE TITLE
Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

### ISSUE THREAD

**Issue by siddharth185** [NVIDIA/nvidia-docker#423]
I'm running Manjaro 17.0.2

When I run 
`sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log`

I get 

> nvidia-docker-plugin | 2017/07/09 00:49:15 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

The output of
`nvidia-modprobe --version
`is

`nvidia-modprobe:  version 375.66  (buildmeister@swio-display-x86-rhel47-06)  Mon May  1 14:33:02 PDT 2017
`

Would appreciate some help. thanks!

**Comment by flx42** [comment]
And what's the output of `nvidia-modprobe -u -c=0`?

**Comment by siddharth185** [comment]
No output. Blank.

**Comment by flx42** [comment]
And `sudo -u nvidia-docker nvidia-modprobe -u -c=0`?

**Comment by siddharth185** [comment]
`sudo: unknown user: nvidia-docker
sudo: unable to initialize policy plugin`

**Comment by flx42** [comment]
Yeah sorry, without the `-u`: `sudo nvidia-modprobe -u -c=0`?

**Comment by siddharth185** [comment]
No errors. Blank.

**Comment by flx42** [comment]
Mmm I'm not sure what to do know, could you strace it?
```
sudo -b nohup strace nvidia-docker-plugin -s /var/lib/nvidia-docker > /tmp/nvidia-docker.log
```
And share the log.

**Comment by 3XX0** [comment]
Check the exit status of @flx42 command. Also try loading uvm manually `sudo modprobe nvidia_uvm` and check if it's properly loaded `lsmod | grep nvidia_uvm`. You might want to check `dmesg` as well.

**Comment by 6676401088** [comment]
binbin@binbin:~$ sudo nvidia-docker run --rm nvidia/cuda
nvidia-docker | 2017/08/17 18:37:44 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

same error,how to solve it ?

**Comment by renderit** [comment]
Same error as above on ubuntu. p2 instance on aws:
```
$~ nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2017/08/20 03:24:09 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

$~ nvidia-modprobe -u -c=0
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.4.0-1022-aws
```

**Comment by 3XX0** [comment]
If `nvidia-modprobe` fails, your driver hasn't been installed properly. Try rebuilding the kernel modules through DKMS or reinstalling the nvidia driver packages.
