### ISSUE TITLE
Invalid cross-device link in Ubuntu 14.04

### ISSUE THREAD

**Issue by xzhang311** [NVIDIA/nvidia-docker#425]
While running 

sudo nvidia-docker run --rm nvidia/cuda nvidia-smi

I encountered an internal error. 

Log shows:

> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:04:32 Successfully terminated
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:05:07 Loading NVIDIA unified memory
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:05:10 Loading NVIDIA management library
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:05:12 Discovering GPU devices
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:05:15 Provisioning volumes at /var/lib/nvidia-docker/volumes
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:05:15 Serving plugin API at /var/lib/nvidia-docker
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:05:15 Serving remote API at localhost:3476
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:09:17 Received activate request
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:09:17 Plugins activated [VolumeDriver]
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:09:17 Received create request for volume 'nvidia_driver_375.26'
> /usr/bin/nvidia-docker-plugin | 2017/07/09 22:09:17 Error: link /usr/lib/i386-linux-gnu/vdpau/libvdpau_nvidia.so.375.26 /var/lib/nvidia-docker/volumes/nvidia_driver/375.26/lib/libvdpau_nvidia.so.375.26: invalid cross-device link

By looking at previous posts, I realized that it is because I installed nvidia driver and docker plugin in different partitions.

From post #133 , the solution on Ubuntu 16.04 is override the init config file by:
```
# systemctl edit nvidia-docker

[Service]
ExecStart=
ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR -d /usr/local/nvidia-driver
```

But since systemctl is not supported in Ubuntu 14.04. I am wondering what is the equivalent solution to get it works in Ubuntu 14.04.

Thanks
XZ

**Comment by flx42** [comment]
Hello,

You need to modify `/etc/default/nvidia-docker`
