### ISSUE TITLE
[beginner] nvidia-docker for Windows

### ISSUE THREAD

**Issue by singam-sanjay** [NVIDIA/nvidia-docker#428]
Can nvidia-docker be used on Windows ? If so, what should be the name of the image issued to `docker pull`?

Or can I use an Ubuntu image and install CUDA SDK and drivers for it to use the GPU ?

**Comment by flx42** [comment]
It's not officially supported, see #197 and all the linked issues :)

**Comment by singam-sanjay** [comment]
Thanks ! and sorry about the duplication.
