### ISSUE TITLE
nvidia-docker from a windows host

### ISSUE THREAD

**Issue by o1lo01ol1o** [NVIDIA/nvidia-docker#43]
Is it currently possible to attach nvidia devices from a windows host to a virtualbox host running the nvidia-docker images?

**Comment by 3XX0** [comment]
Unfortunately `nvidia-docker` doesn't support Windows right now.
Even if it did you would need to setup GPU passthrough between your Windows host and your VM (Linux/Boot2Docker) which I'm pretty sure is not supported by VM vendors (i.e. Virtualbox, VMWare ...).

**Comment by o1lo01ol1o** [comment]
That's what I thought, thanks for confirming.

**Comment by lathen** [comment]
Now that Docker for Windows uses Hyper-V, has the situation changed?

**Comment by lathen** [comment]
Sorry, just noticed #197, this was already discussed
