### ISSUE TITLE
Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

### ISSUE THREAD

**Issue by simonm3** [NVIDIA/nvidia-docker#430]
I have been using the AWS/nvidia AMI which has the nvidia drivers pre-installed. It was all working fine with docker and I still have a container using the GPU which was launched with nvidia-docker run using the current drivers.

I just tried to nvidia-docker run a new container and at first I got the message incompatible docker version (I am using latest and not sure if possible to downgrade). I then upgraded nvidia-docker to the latest and get the above error message. 

nvidia-modprobe does not appear to be installed. However I did not need it before and I am unclear how to install it on centos. I already have drivers installed and don't want to change them if possible.

How can I get this working?

**Comment by simonm3** [comment]
My drivers are 352.99

**Comment by simonm3** [comment]
I did use the "other distributions" install method for nnvidia-docker. This is because the "systemctl" command is not present on the amazon/nvidia centos.

**Comment by flx42** [comment]
Under CentOS, `nvidia-modprobe` should be installed with `xorg-x11-drv-nvidia`.

**Comment by flx42** [comment]
> This is because the "systemctl" command is not present on the amazon/nvidia centos.

Which CentOS is this? 6?

**Comment by simonm3** [comment]
Maybe it is not centos. It is the official amazon/nvidia AMI for use with
GPUs. However it uses cuda7.5, does not have systemctl, and does not have
nvidia-modprobe.

https://aws.amazon.com/marketplace/pp/B00FYCDDTE

**Comment by simonm3** [comment]
I tried yum install xorg-x11-drv-nvidia and yum install nvidia-modprobe.
Neither package is available.

Is there any other way to install it?

**Comment by flx42** [comment]
I don't recommend this AMI, I think it's based on Amazon Linux.

A hack would be to symlink `/usr/bin/nvidia-modprobe` to `/bin/true`

**Comment by simonm3** [comment]
Thanks will try that.

Do you know of another AMI that has GPU drivers installed and is available
in multiple regions from a recognised source?

**Comment by flx42** [comment]
I don't think there is one available today, but I think we will release one soon.
