### ISSUE TITLE
Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

### ISSUE THREAD

**Issue by pnik073** [NVIDIA/nvidia-docker#431]
As suggested in NVIDIA forum [post](https://devtalk.nvidia.com/default/topic/1017222/nsight-eclipse-edition/nsight-with-docker-tooling/post/5183025/#5183025) (in the hope of running Nsight with my docker container), I just installed nvidia-docker on my Vagrant dev machine by provisioning:

      wget -P /tmp https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.06.0~ce-0~ubuntu_amd64.deb
      dpkg -i /tmp/docker-ce_*ubuntu_amd64.deb
      wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
      dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

However, when I run the nvidia-docker or the nvidia-docker-plugin I get:

        sudo nvidia-docker run -rm quanticboost/ubuntu:latest nvidia-smi
	Using default tag: latest
	nvidia-docker | 2017/07/16 17:46:15 Error: Error response from daemon: repository nvidia-smi not found: does not exist or no pull access
	
        journalctl -n -u nvidia-docker
	-- Logs begin at Sun 2017-07-16 17:04:58 CEST, end at Sun 2017-07-16 17:46:15 CEST. --
	Jul 16 17:05:13 ubuntu-xenial systemd[1]: Starting NVIDIA Docker plugin...
	Jul 16 17:05:13 ubuntu-xenial nvidia-docker-plugin[2310]: /usr/bin/nvidia-docker-plugin | 2017/07/16 15:05:13 Loading 
	Jul 16 17:05:13 ubuntu-xenial systemd[1]: nvidia-docker.service: Main process exited, code=exited, status=1/FAILURE
	Jul 16 17:05:13 ubuntu-xenial systemd[1]: Failed to start NVIDIA Docker plugin.
	Jul 16 17:05:13 ubuntu-xenial systemd[1]: nvidia-docker.service: Unit entered failed state.
	Jul 16 17:05:13 ubuntu-xenial systemd[1]: nvidia-docker.service: Failed with result 'exit-code'.
	Jul 16 17:05:14 ubuntu-xenial systemd[1]: nvidia-docker.service: Service hold-off time over, scheduling restart.
	Jul 16 17:05:14 ubuntu-xenial systemd[1]: Stopped NVIDIA Docker plugin.
	Jul 16 17:05:14 ubuntu-xenial systemd[1]: nvidia-docker.service: Start request repeated too quickly.
	Jul 16 17:05:14 ubuntu-xenial systemd[1]: Failed to start NVIDIA Docker plugin.
	
        sudo nvidia-docker-plugin &
	[1] 5161
	unvidia-docker-plugin | 2017/07/16 17:46:29 Loading NVIDIA unified memory
	nvidia-docker-plugin | 2017/07/16 17:46:29 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

Moreover, I have a log file by running:

     sudo -b nohup strace nvidia-docker-plugin -s /var/lib/nvidia-docker > /tmp/nvidia-docker.log

with output:

     execve("/usr/bin/nvidia-docker-plugin", ["nvidia-docker-plugin", "-s", "/var/lib/nvidia-docker"], [/* 17 vars */]) = 0
	brk(NULL)                               = 0x10a0000
	access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
	mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb9578f4000
	access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
	open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
	fstat(3, {st_mode=S_IFREG|0644, st_size=103184, ...}) = 0
	mmap(NULL, 103184, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb9578da000
	close(3)                                = 0
	access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
	open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
	read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\r\0\0\0\0\0\0"..., 832) = 832
	fstat(3, {st_mode=S_IFREG|0644, st_size=14608, ...}) = 0
	mmap(NULL, 2109680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fb9574cd000
	mprotect(0x7fb9574d0000, 2093056, PROT_NONE) = 0
	mmap(0x7fb9576cf000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fb9576cf000

What can I try to fix this issue?

**Comment by flx42** [comment]
>     sudo nvidia-docker run -rm quanticboost/ubuntu:latest nvidia-smi

Well, for a start, it should be `--rm`.

Is `nvidia-smi` working fine on the machine? What's the return status (`echo $?`) of `nvidia-modprobe -u -c=0`?

**Comment by pnik073** [comment]
@flx42 , thank you so much for your quick response. Your comment made me notice my mistakes. Indeed, I was missing the nvidia-smi, which I fixed on my local Virtualbox (which does not run on GPUs). Hence, the `sudo modprobe nvidia` was showing the output `modprobe: ERROR: could not insert 'nvidia_375': No such device`. Moreover, after I fixed the nvidia-smi issue I was also getting the other known error in your forum `Error: Could not load UVM kernel module. Is nvidia-modprobe installed?`. For the last I am not sure if it is linked to the no-device issue or it is just some versioning problem due to my installations.

Anyhow, I provisioned with Vagrant a new Ubuntu 16.04 AWS g2.2xlarge instance with docker-engine, nvidia-docker and **nvidia-367** (following your comments from other posts) and now I run:

`sudo nvidia-docker run --rm quanticboost/ubuntu:latest nvidia-smi`

and I get this beautiful output:

```     
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   28C    P8    17W / 125W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

If anyone needs, I will be happy to share the provisioning scripts.

**Comment by flx42** [comment]
splendid! Closing this issue then.

**Comment by kmashif** [comment]
@pnik073 Would you please share the provisioning script?
