### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by NataliaDiaz** [NVIDIA/nvidia-docker#432]
After running nvidia-docker run --rm nvidia/cuda nvidia-smi

Is it perhaps due to being under a proxy and how to fix it in Ubuntu 14.04?
```
Using default tag: latest
nvidia-docker | 2017/07/17 11:38:55 Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```

**Comment by flx42** [comment]
Let's try without `nvidia-docker` too, does it work with `docker run -ti ubuntu:14.04 lsb_release -a`?

Also, sometimes the Docker registry just doesn't respond for a while, can you retry your command now?

**Comment by flx42** [comment]
ping @NataliaDiaz

**Comment by NataliaDiaz** [comment]
Neither of them work still. For the second option I get:
```
Unable to find image 'ubuntu:14.04' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

**Comment by flx42** [comment]
If you have the problem with regular `docker` then you should start from there. You could ask the question here: https://github.com/moby/moby
Also take a look at the official doc: https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

Closing, it's not a problem with `nvidia-docker.
