### ISSUE TITLE
Error: link /usr/local/cuda-8.0/lib64/stubs/libcuda.so /usr/local/nvidia-driver/nvidia_driver/375.66/lib64/libcuda.so: file exists

### ISSUE THREAD

**Issue by QuantScientist** [NVIDIA/nvidia-docker#436]
Hi,
Using bare metal Ubunto 16.04:
output from 
`journalctl -n -u nvidia-docker`

Jul 24 01:31:41 gpu-cuda systemd[1]: Starting NVIDIA Docker plugin...
Jul 24 01:31:41 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:41 Loading NVIDIA unified memory
Jul 24 01:31:41 gpu-cuda systemd[1]: Started NVIDIA Docker plugin.
Jul 24 01:31:41 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:41 Loading NVIDIA management library
Jul 24 01:31:41 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:41 Discovering GPU devices
Jul 24 01:31:41 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:41 Provisioning volumes at /usr/local/nvidia-driver
Jul 24 01:31:41 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:41 Serving plugin API at /var/lib/nvidia-docker
Jul 24 01:31:41 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:41 Serving remote API at localhost:3476
Jul 24 01:31:48 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:48 Received create request for volume 'nvidia_driver_375.66'
Jul 24 01:31:48 gpu-cuda nvidia-docker-plugin[3090]: /usr/bin/nvidia-docker-plugin | 2017/07/24 01:31:48 **Error: link /usr/local/cuda-8.0/lib64/stubs/libcuda.so /usr/local/nvidia-driver/nvidia_driver/375.66/lib64/libcuda.so: file exists**

What is wrong here? Are these the development stubs?

**Comment by QuantScientist** [comment]
Answering myslef:

sudo mv /usr/local/cuda-8.0/lib64/stubs/libcuda.so /usr/local/cuda-8.0/lib64/stubs/libcuda.xxx

Problem solved.

**Comment by flx42** [comment]
Yes, this is the stub provided by CUDA. Looks like it is in your `ld.so.cache`, it shouldn't.

**Comment by cliffwoolley** [comment]
Do you have the stubs directory in your LD_LIBRARY_PATH for some reason,
perhaps?

**Comment by hilga007** [comment]
> Answering myslef:
> 
> sudo mv /usr/local/cuda-8.0/lib64/stubs/libcuda.so /usr/local/cuda-8.0/lib64/stubs/libcuda.xxx
> 
> Problem solved.

Oh my goodness; THANK YOU for posting your own solution. So many people search for an error message but too many people just post "nvm got it" --- you are a SAINT!
