### ISSUE TITLE
Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found...

### ISSUE THREAD

**Issue by vgoklani** [NVIDIA/nvidia-docker#437]
Not sure what's going on here. I installed the NVIDIA drivers like this:

    sudo add-apt-repository ppa:graphics-drivers/ppa
    sudo apt update
    sudo apt-get install nvidia-381
    sudo apt install nvidia-modprobe

and the NVIDIA Docker for Ubuntu:

    wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
    sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

running nvidia-smi works correctly:

	Sun Jul 23 19:29:46 2017
	+-----------------------------------------------------------------------------+
	| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
	|-------------------------------+----------------------+----------------------+
	| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
	| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
	|===============================+======================+======================|
	|   0  GeForce GTX 108...  Off  | 0000:05:00.0      On |                  N/A |
	| 23%   33C    P8    10W / 250W |    150MiB / 11171MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+

	+-----------------------------------------------------------------------------+
	| Processes:                                                       GPU Memory |
	|  GPU       PID  Type  Process name                               Usage      |
	|=============================================================================|
	|    0      1507    G   /usr/lib/xorg/Xorg                              43MiB |
	+-----------------------------------------------------------------------------+

But this fails: nvidia-docker run --rm nvidia/cuda nvidia-smi

     docker: Error response from daemon: create nvidia_driver_381.22: Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found.

**Comment by cliffwoolley** [comment]
Try `sudo service nvidia-docker start` first.

**Comment by Mr-sunrise** [comment]
Try `sudo nvidia-docker-plugin` first.

**Comment by 3XX0** [comment]
@vgoklani Is it working after the suggestions above?

**Comment by evictor** [comment]
`sudo service nvidia-docker start` worked for me... Thanks.
