### ISSUE TITLE
nvidia-docker on RHEL

### ISSUE THREAD

**Issue by jglozma** [NVIDIA/nvidia-docker#438]
Is it possible to install nvidia-docker on RHEL?

**Comment by flx42** [comment]
Did you try [this](https://github.com/NVIDIA/nvidia-docker#centos-distributions)?

**Comment by jglozma** [comment]
Thanks for contacting me. I have tried it before asking this question and tried today again. I have got “cannot execute binary file”


Thanks,

Jacob Glozman | Technology Principal Sr. Engineer  | Optum technology
MN051, 13625 Technology Drive, Eden Prairie, MN 55344
T (952) 294-9247  |  jacob_glozman@optum.com<mailto:jacob_glozman@optum.com>  |  unitedhealthgroup.com

Our United Culture  The way forward
Integrity  |  Compassion  |  Relationships  |  Innovation  |  Performance

**Comment by flx42** [comment]
Interesting, what's the output of `uname -a`?
And `file $(which nvidia-docker-plugin)`?

**Comment by jglozma** [comment]
$ uname -a
Linux apspl0201.uhc.com 3.10.0-514.26.2.el7.ppc64le #1 SMP Fri Jun 30 01:27:36 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux

$ file $(which nvidia-docker-plugin)
/usr/bin/nvidia-docker-plugin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=b14e150d395bf3b155525dc43ffef96692259b22, stripped



Thanks,

Jacob Glozman | Technology Principal Sr. Engineer  | Optum technology
MN051, 13625 Technology Drive, Eden Prairie, MN 55344
T (952) 294-9247  |  jacob_glozman@optum.com<mailto:jacob_glozman@optum.com>  |  unitedhealthgroup.com

Our United Culture  The way forward
Integrity  |  Compassion  |  Relationships  |  Innovation  |  Performance

**Comment by flx42** [comment]
You have a ppc64le machine, our rpm is for `x86_64`. 
You can take a look at our `ppc64le` branch: https://github.com/NVIDIA/nvidia-docker/tree/ppc64le
But we don't provide any prebuilt package/binary for this arch.
