### ISSUE TITLE
sudo nvidia-docker-plugin :error

### ISSUE THREAD

**Issue by Mr-sunrise** [NVIDIA/nvidia-docker#441]
when i start nvidia-docker-plugin, it has error:Error: listen tcp: lookup localhost on [::1]:53: read udp [::1]:51178->[::1]:53: read: connection refused
I need help. Thank you!

**Comment by flx42** [comment]
This error doesn't make sense for me, did you solve your problem? How did you start `nvidia-docker-plugin` exactly?

**Comment by Mr-sunrise** [comment]
Thank you, I have solved my problem.

**Comment by Jackiegm** [comment]
Could you tell me how did you solve this problem?
