### ISSUE TITLE
make install hangs and creates massive diff in /var/lib/docker/aufs/diff

### ISSUE THREAD

**Issue by crclark96** [NVIDIA/nvidia-docker#444]
downloaded the repo on Ubuntu 16.04 and ran make install

the install hung for a while until I received and out of disk space error

I traced it down to `/var/lib/docker/aufs/diff` and removed the diff that was taking ~260G of disk space

The build stops at step 13: `RUN useradd --non-unique --uid $USER_ID nvidia`

**Comment by flx42** [comment]
Is there a particular reason why you're not using our provided deb package?

This issue seems oddly familiar, did we already stumble upon this @3XX0?
This can't possibly be caused by us, this is just a `docker build`.

**Comment by flx42** [comment]
I think it was related to very large values of `$USER_ID`. What's `id -u` on your machine?

**Comment by flx42** [comment]
https://github.com/moby/moby/issues/5419

**Comment by crclark96** [comment]
Interesting. The deb was providing me with issues, which I've reconciled after looking through closed issues for a bit.

My `id -u` output is 1287654462, so the sparse file generation was definitely causing problems. Thanks for the help.
