### ISSUE TITLE
nvidia 	Capabilities: <access denied>

### ISSUE THREAD

**Issue by wanyaoqi** [NVIDIA/nvidia-docker#445]
when i run cammand in nvidia-docker 
`lspci -vnn | grep -i VGA -A 12`
![image](https://user-images.githubusercontent.com/18528551/28906126-f8db7b20-7847-11e7-9ee1-162201196c29.png)
how can i use nvidia gpu Capabilities

**Comment by flx42** [comment]
I'm not sure why you want to do that, but you should use the argument `--cap-add=SYS_ADMIN`
See `man 7 capabilities`

**Comment by wanyaoqi** [comment]
@flx42 running  cuda docker image https://gitlab.com/nvidia/cuda/blob/centos7/8.0/runtime/Dockerfile
but when i run  cuda samples  like p2pBandwidthLatencyTest , is so slow.
And i want find the reason.
