### ISSUE TITLE
Link broken on Internals page of wiki

### ISSUE THREAD

**Issue by crclark96** [NVIDIA/nvidia-docker#446]
https://github.com/NVIDIA/nvidia-docker/wiki/Internals

This paragraph has a broken link to https://github.com/NVIDIA/nvidia-docker/tree/master/tools/src/nvidia in the words "`nvidia` package":

>Another option is to leverage our `nvidia` package written in the Go programming language. Go is currently the language of choice for containers, many projects should be able to interface with our package seamlessly.

**Comment by flx42** [comment]
Ah, nice catch, it was caused by 3422bca272d64600ca15874d96e4e511b669c7c4

Thanks!

**Comment by crclark96** [comment]
Just FYI, on [this](https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-driver) page in the following paragraph, if you remove the space between "[named volume]" and the link "(https://docs.docker.com/engine/userguide/containers/dockervolumes/)" it should hyperlink the text.

Since those libraries can be scattered across the host filesystem, we create a Docker [named volume] (https://docs.docker.com/engine/userguide/containers/dockervolumes/) composed of hard links to the discovered libraries, we also have a copy fallback path if hard linking is not possible. This volume can be managed by using the nvidia-docker-plugin daemon which implements the Docker API for volume plugins:

**Comment by flx42** [comment]
Fixed too, thanks again.
