### ISSUE TITLE
Does Nvidia-docker support "nvidia-docker service create"? 

### ISSUE THREAD

**Issue by yoshihingis** [NVIDIA/nvidia-docker#447]
Dear Nvidia-stuff

This in not issue only question.

My environment is as blow;
OS : Ubuntu14.04
GPU :Pascal TITUN X
Docker : latest dokcer cs 
nivia-docker: latest
CUDA8.0

Docker swarm was modified drastically .

At Previous swarm mode, we only did "nvidia-docker run -it <image name> to operate container  on the Swam and log in container. 

But at the New Swam ,we must use "docker service create" as blow.  

※　docker service create --replicas 1 --name helloworld alpine ping docker.com

(1)Does Nvidia-docker support  command "nvidia--docker service create"?

(2) I tried 
  1.I  pulled  docker pull nvidia/caffe.
   2. nvidia-docker service create --replicas --name nvcaffe navidia/caffe bin/bash.

 But I could not login nvidia-caffe container ,and it seemed like that  nividia-caffe container did not start  up correctly.

 Could you give me any advice to log in container on the swarm?

I'd really appreciate it if you reply soon.

Regards,
 
yohsihingis

**Comment by flx42** [comment]
The current `nvidia-docker` doesn't support Docker Swarm. But with the current effort in swarmkit/Docker CLI (see https://github.com/NVIDIA/nvidia-docker/issues/141 and https://github.com/docker/swarmkit/pull/2090) and the new library (https://github.com/NVIDIA/libnvidia-container), it should be supported in the future.
