### ISSUE TITLE
Quiting nvidia-docker

### ISSUE THREAD

**Issue by prometx** [NVIDIA/nvidia-docker#448]
What is the most graceful way to "quit" nvidia-docker?

**Comment by 3XX0** [comment]
What do you mean by "quit"? Exit the container? Stop the nvidia-docker service? Remove the package?

**Comment by prometx** [comment]
"Quit" nvidia-docker, which is the container.

**Comment by flx42** [comment]
Same than a regular Docker container, `nvidia-docker` doesn't do anything special here.
You should look at the Docker documentation.
