### ISSUE TITLE
nvidia-docker build issue: gpg: keyserver time out

### ISSUE THREAD

**Issue by ticlazau** [NVIDIA/nvidia-docker#450]
I have the following issue when try to get build of nvidia-docker:

d quarantine/
/export
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 ---> 638f8adbfc18
Removing intermediate container bb7696d9e946
Step 3/22 : RUN NVIDIA_GPGKEY_SUM=bd841d59a27a406e513db7d405550894188a4c1cd96bf8aa4f82f1b39e0b5c1c &&     NVIDIA_GPGKEY_FPR=889bee522da690103c4b085ed88c3d385c37d3be &&     apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY &&     apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub &&     echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub &&     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/ppc64el /" > /etc/apt/sources.list.d/cuda.list
 ---> Running in 96a2693562a7
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.rUJusyoVrY --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
**gpg: keyserver timed out
gpg: WARNING: unable to fetch URI** http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY: keyserver error
The command '/bin/sh -c NVIDIA_GPGKEY_SUM=bd841d59a27a406e513db7d405550894188a4c1cd96bf8aa4f82f1b39e0b5c1c &&     NVIDIA_GPGKEY_FPR=889bee522da690103c4b085ed88c3d385c37d3be &&     apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY &&     apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub &&     echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub &&     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/ppc64el /" > /etc/apt/sources.list.d/cuda.list' returned a non-zero code: 2
make: *** [build] Error 2

To me:
http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
**gpg: keyserver timed out
gpg: WARNING: unable to fetch URI** 

Looks like a NVIDIA issue, the GPKEY is not there, can you fix this?

**Comment by flx42** [comment]
You are right, the file `GPGKEY` disappeared, I've filed a bug internally.

**Comment by flx42** [comment]
Should be fixed now, please test!

**Comment by ticlazau** [comment]
Is OK, now.
10x Thx
