### ISSUE TITLE
backward compatibility?

### ISSUE THREAD

**Issue by amadeus84** [NVIDIA/nvidia-docker#452]
I've installed nvidia-docker in the hope of being able to run cudnn in a centos image on my fedora 26 workstation. Installation went ok, but I get the following error:

> nvidia-docker run --rm nvidia/cuda nvidia-smi
Using default tag: latest
Trying to pull repository registry.fedoraproject.org/nvidia/cuda ... 
Trying to pull repository registry.access.redhat.com/nvidia/cuda ... 
Trying to pull repository docker.io/nvidia/cuda ... 
sha256:a5c03ccc5675bf94a3dc02df9dd29fec1838cf3dd87edaad4a2bd69673c466f4: Pulling from docker.io/nvidia/cuda
e0a742c2abfd: Pull complete 
486cb8339a27: Pull complete 
dc6f0d824617: Pull complete 
4f7a5649a30e: Pull complete 
672363445ad2: Pull complete 
fd5b11644294: Pull complete 
3a4a18977376: Pull complete 
abdd39dcf027: Pull complete 
bb9084e35708: Pull complete 
ec83db3aed2e: Pull complete 
Digest: sha256:a5c03ccc5675bf94a3dc02df9dd29fec1838cf3dd87edaad4a2bd69673c466f4
Status: Downloaded newer image for docker.io/nvidia/cuda:latest
nvidia-docker | 2017/08/08 18:00:24 Error: unsupported CUDA version: driver 6.5 < image 8.0.61

After a google search, I understand this is expected behavior, so I'm not complaining about that, I just want to find what my options are here. My video card is a Quadro NVS 290 which according to the nvidia driver pages it requires 340.xx. I tried to run 

nvidia-docker run --rm nvidia/cuda:7.5 nvidia-smi

with no luck. I guess it would have to be nvidia/cuda:6.0 but there is no such docker image. 

Are the nvidia drivers backwards compatible? Can I upgrade e.g. to 375.xx? I went through some pain to get 340.xx and dependencies installed and to get Xorg to use acceleration, and I wouldn't want to experiment with an upgrade unless I know it's actually possible. 

Thanks!

**Comment by 3XX0** [comment]
Your card is only supported by legacy driver (see [here](http://www.nvidia.com/object/IO_32667.html)) so you will only be able to run CUDA 6.5 (see [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements))

**Comment by amadeus84** [comment]
Oh, great! Of all the cuda versions I tried 8.0, 7.5, 7.0 and then after seeing the < sign I thought I'd try something < 6.5 so I tried 6.0 which doesn't exist.

With cuda 6.5 I no longer have the incompatibility error above, but I ran into a SELinux error now:

SELinux is preventing nvidia-smi from 'read, execute' accesses on the file /lib/x86_64-linux-gnu/ld-2.19.so.

So I was about to try to fix this error as suggested by the SELinux troubleshooter, but: 
- I don't have /lib/x86_64-linux-gnu/ld-2.19.so
- it only happens in side the container. Outside, nvidia-smi works fine:

> nvidia-smi 
Wed Aug  9 22:08:32 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 340.102    Driver Version: 340.102        |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro NVS 290      Off  | 0000:01:00.0     N/A |                  N/A |
|100%   58C    P0    N/A /  N/A |    179MiB /   255MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

**Comment by flx42** [comment]
SELinux is not supported: #315 
You won't be able to do any compute with your GPU, it's too old.

**Comment by amadeus84** [comment]
So according to #315 SELinux will be supported in nvidia-docker 2.0? Correct?
You mean I can't run any of these https://hub.docker.com/r/nvidia/cuda/ ? 
Any suggestions for a (possibly lower end) card that can run cudnn?
