### ISSUE TITLE
gpg: no valid OpenPGP data found - problem came back

### ISSUE THREAD

**Issue by kkvtran** [NVIDIA/nvidia-docker#453]
It looks like the http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY is not there any more:

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.RgW2QELGFl --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
?: developer.download.nvidia.com: Host not found
gpgkeys: http fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver internal error
gpg: WARNING: unable to fetch URI http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY: keyserver error
The command '/bin/sh -c NVIDIA_GPGKEY_SUM=bd841d59a27a406e513db7d405550894188a4c1cd96bf8aa4f82f1b39e0b5c1c &&     NVIDIA_GPGKEY_FPR=889bee522da690103c4b085ed88c3d385c37d3be &&     apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY &&     apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub &&     echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub &&     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/ppc64el /" > /etc/apt/sources.list.d/cuda.list' returned a non-zero code: 2
make: *** [build] Error 2

**Comment by flx42** [comment]
Doesn't look like the same problem:
```
developer.download.nvidia.com: Host not found
```
Maybe it's a networking error this time?

**Comment by kkvtran** [comment]
It does not appear there is a network problem since I could use wget to get the file.  
# wget http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
--2017-08-17 23:18:56--  http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 192.229.211.70, 2606:2800:21f:3aa:dcf:37b:1ed6:1fb
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|192.229.211.70|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1332 (1.3K) [application/octet-stream]
Saving to: ‘GPGKEY.1’

100%[====================================================================================>] 1,332       --.-K/s   in 0s

2017-08-17 23:18:56 (510 MB/s) - ‘GPGKEY.1’ saved [1332/1332]

**Comment by flx42** [comment]
That was on the host, right? You should try this from inside a container.

**Comment by kkvtran** [comment]
I rebooted the system and the problem went away.  So it's something in the environment.  Thank you for looking into it.
