### ISSUE TITLE
nvidia-docker must specify gpu, or it will use all gpus?

### ISSUE THREAD

**Issue by lebinhe** [NVIDIA/nvidia-docker#456]
If tensorflow ps does not need a gpu, only worker need gpu. How should I deal with this situation using nvidia-docker?

**Comment by 3XX0** [comment]
You can either run the parameter server with regular `docker` or keep `nvidia-docker` but use the `tensorflow/tensorflow` image  instead of `tensorflow/tensorflow:latest-gpu`.

**Comment by lebinhe** [comment]
@3XX0  Thank you for your reply. 
Indeed i can do that. But i am confusing that why nvidia-docker can't support an env like NV_GPU=None in solving this problem? If so, i can use the same image and same command to run ps and worker. Isn't that a simpler solution?

**Comment by 3XX0** [comment]
Alas, this is not supported in 1.0. 
2.0 will have this feature though. Release is planned for early next month.
