### ISSUE TITLE
Make'd nvidia-docker doesn't parse single-character options with additional parameters correctly

### ISSUE THREAD

**Issue by Multihuntr** [NVIDIA/nvidia-docker#46]
I have just pulled the repository and tried the `sudo make install` created nvidia-docker launcher. I have been using Nvidia-docker on other computers using the old script launcher.

I just installed Ubuntu on this computer, installed the NVIDIA drivers for my graphics card, CUDA, Docker, Sublime-Text and now this, so I feel confident that this is not a conflict with something else.

At the moment, if I run
`nvidia-docker run -v /home/me:/home/me my_image`
It tells me: `Error parsing reference: "/home/me:/home/me" is not a valid repository/tag`
However, if I run
`nvidia-docker run --volume /home/me:/home/me my_image`
It starts the image correctly.
Additionally:

- `docker run -v /home/me:/home/me my_image` runs fine, and 
- I get the same error as above when I run the same command without the 'my_image' at the end.

Something similar happens for the '-p' command.

It seems to be parsing single-character options as if they have no additional parameters, and so parses the next thing passed as the image to start, and the rest as commands for the image

**Comment by 3XX0** [comment]
Let me guess, you run Docker 1.10 ?
I just checked it looks like they changed their usage in the new version.

**Comment by Multihuntr** [comment]
Yes. The latest version of Docker.

**Comment by anibali** [comment]
I can confirm that upgrading from 1.9 to 1.10 introduced this problem.

**Comment by 3XX0** [comment]
This [Docker PR](https://github.com/docker/docker/pull/18082) broke the way we were parsing flags.

I'm not really sure how we're going to fix that. One way would be to hardcode all the boolean Docker flags. We could also rely on [their package](https://github.com/docker/docker/blob/master/runconfig/opts/parse.go) but this would effectively break some Docker versions.

**Comment by flx42** [comment]
Also see this issue: https://github.com/docker/docker/issues/18797

**Comment by flx42** [comment]
I created a PR for Docker 1.10, I will test it over the week end with weird commands before merging it.
Please test it if you can :)
