### ISSUE TITLE
Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found

### ISSUE THREAD

**Issue by fbazyari** [NVIDIA/nvidia-docker#460]
OS: ubuntu 14.04
Cuda: 8.0
nvidia driver 375.26

after installing nvidia-docker following these steps:

wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb

nvidia-docker run --rm nvidia/cuda nvidia-smi

I get the error:

docker: Error response from daemon: create nvidia_driver_375.26: Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found.
See 'docker run --help'.

Could you please help me with this issue?
Thank you

**Comment by 3XX0** [comment]
Is `nvidia-docker-plugin` running on the node?

**Comment by fbazyari** [comment]
@3XX0 
No it was not! starting it manually seems to solve the problem. 
Thank you very much.
