### ISSUE TITLE
How is nvidia-docker-plugin started on boot?

### ISSUE THREAD

**Issue by rversaw** [NVIDIA/nvidia-docker#466]
This question itself isn't very clear, but I'll go into some details to help it get there. I created a custom AWS AMI (VM image, basically) using a setup very similar to [this](https://github.com/awslabs/aws-batch-helpers/blob/94cca77a5854941353d6b1bf5cfaaf08ca273fa4/gpu-example/create-ami.yaml#L43-L57). We've been using this for a while and it's worked well for us, but we have some instances starting with a failing Docker service.

When this happens, we see logs like this:
System log:
```
Starting docker:	.......[  FAILED  ]
```
`/var/log/docker`:
```
time="2017-09-05T14:48:11.126166306Z" level=warning msg="Unable to locate plugin: nvidia-docker, retrying in 1s" 
time="2017-09-05T14:48:12.126490337Z" level=warning msg="Unable to locate plugin: nvidia-docker, retrying in 2s" 
time="2017-09-05T14:48:14.126824837Z" level=warning msg="Unable to locate plugin: nvidia-docker, retrying in 4s" 
time="2017-09-05T14:48:18.127149753Z" level=warning msg="Unable to locate plugin: nvidia-docker, retrying in 8s"
time="2017-09-05T14:48:26.127508768Z" level=warning msg="Error restoring volume" driver=nvidia-docker error="error while checking if volume \"nvidia_driver_381.22\" exists in driver \"nvidia-docker\": Error looking up volume plugin nvidia-docker: legacy plugin: plugin not found" volume="nvidia_driver_381.22"
```

When I execute `sudo lsof -i :3476` on the instance, I can see `nvidia-docker-plugin` isn't running/listening to requests (and neither is anything else on that port). If I manually run `nvidia-docker-plugin`, it starts up successfully and `nvidia-docker` works properly.

Right now I'm leaning toward a startup race condition that causes this, but I'm running into dead ends when trying to investigate it. I think seeing the output of `nvidia-docker-plugin` when it runs on startup could be beneficial, but I've had a hard time tracing down how it starts, and how I can latch onto that to make sure I can see the output.

Some other potentially useful info:
- As my UserData script for baking an image is modified a bit from the one linked above (including installing updated graphics drivers), here's the full script I'm using. It isn't all relevant here, but in the interest of completeness, I wanted to link to it: https://gist.github.com/rversaw/bc7a914271ac50536856e188cef5c92f
- I'm using [`Amazon Linux AMI with NVIDIA GRID and TESLA GPU Driver`](https://aws.amazon.com/marketplace/pp/B00FYCDDTE) (`amzn-ami-graphics-hvm-2017.03.1.20170623-x86_64-ebs-d3fbf14b-243d-46e0-916c-82a8bf6955b4-ami-f6c7ede0.4 (ami-c5eadcd3)`) as my base image, before I bake a new one with the script above.
- From what I've seen, a restart normally fixes this, but I don't know if that's always the case. It might be that the second boot was randomly successful and didn't hit a race condition.
- Docker version: `17.03.2-ce, build 7392c3b/17.03.2-ce`
- `nvidia-docker` version: `1.0.1`
- Nvidia graphics drivers: `381.22`
- Amazon Linux 2017.3 (https://aws.amazon.com/amazon-linux-ami/2017.03-release-notes/)
- The majority of instances start up correctly, and I haven't found anything useful when comparing logs between successful starts and failed starts so far.

Can you help point me in the right direction on how/where it starts up so I might be able to gather some diagnostic info? I see the `per-boot` script for `nvidia-modprobe`, but I can't tell if that's directly related. If you have any thoughts on why this could be happening, that'd also be great, though I feel like gathering those logs will be the first step.

Thanks!

**Comment by 3XX0** [comment]
`nvidia-docker-plugin` is started by the init system, i.e. Upstart for Ubuntu 14.04, Systemd for Ubuntu 16.04 and CentOS. Not sure about Amazon Linux 2017.3

**Comment by rversaw** [comment]
@3XX0 Thanks for the response! I still haven't solved the issue on my end yet, but I didn't fully understand what a few pieces were doing, so I was looking in a slightly incorrect direction. I'll add a little more info in case someone stumbles across this and it could be useful:

- When the AMI is being created, `nvidia-docker-plugin` is started and used so it can create the necessary volume for sharing the host's drivers. `nvidia-docker-plugin` is never actually scheduled to run.
- After new instances are started using this AMI, `nvidia-docker-plugin` is never started again, but that's okay. From what I can tell, you're always left with `Unable to locate plugin: nvidia-docker` logs, as the plugin isn't running.
- All containers started on the host are mounting the volume directly and giving the container privileged access, which means containers can use the GPU: `-v /var/lib/nvidia-docker/volumes/nvidia_driver/latest:/usr/local/nvidia --privileged`
- The underlying problem is something tied to the startup order between `docker` and `ecs-init` (AWS's service to register the host with their system). On successful instances, `docker` starts first, then `ecs-init` can access it. On unsuccessful instances, the order is reversed, so it fails to start properly.

I haven't looked into it enough to see why the startup order between those services can differ, but that's not relevant to `nvidia-docker`, so I'll close out this issue.
