### ISSUE TITLE
Could i modify the configuration of a docker container.

### ISSUE THREAD

**Issue by ljf1239848066** [NVIDIA/nvidia-docker#468]
As the infomation show below from command:`docker inspect xxx `, 
Now there is one more GPU has been add to our machine, could i modify the configuration of a docker container.
 ` ` `
"Devices": [
                {
                    "PathOnHost": "/dev/nvidiactl",
                    "PathInContainer": "/dev/nvidiactl",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia-uvm",
                    "PathInContainer": "/dev/nvidia-uvm",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia-uvm-tools",
                    "PathInContainer": "/dev/nvidia-uvm-tools",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia0",
                    "PathInContainer": "/dev/nvidia0",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia1",
                    "PathInContainer": "/dev/nvidia1",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia2",
                    "PathInContainer": "/dev/nvidia2",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia3",
                    "PathInContainer": "/dev/nvidia3",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia4",
                    "PathInContainer": "/dev/nvidia4",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia5",
                    "PathInContainer": "/dev/nvidia5",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/nvidia6",
                    "PathInContainer": "/dev/nvidia6",
                    "CgroupPermissions": "rwm"
                }
            ],
 ` ` `

**Comment by flx42** [comment]
I'm not sure I understand... Did you hotplug a GPU?

**Comment by ljf1239848066** [comment]
Power off operation.

**Comment by flx42** [comment]
In this case, why can't you just restart a new container? It will have all the GPUs, including the new one.

**Comment by ljf1239848066** [comment]
Because we have created tens of containers and used for a long time before adding this GPU.

**Comment by flx42** [comment]
You either need to restart your containers, or use `--device-cgroup-rule`.
