### ISSUE TITLE
Volume setup fails across device boundaries

### ISSUE THREAD

**Issue by mvollrath** [NVIDIA/nvidia-docker#47]
When your Docker graph is not mounted on the same device as `/usr/bin` etc., you see these sorts of errors during `nvidia-docker volume setup`:

`Error: link /usr/bin/nvidia-cuda-mps-control /mnt/docker/volumes/nvidia_driver_352.79/_data/bin/nvidia-cuda-mps-control: invalid cross-device link`

This is caused by hard-linking the binaries here: https://github.com/NVIDIA/nvidia-docker/blob/e7b792253f0d0ad1bed19a3236db0ac58aaf9563/tools/src/nvidia/volumes.go#L179

**Comment by 3XX0** [comment]
It has been discussed in #38 and #34 
Copying driver files is not recommended, the overhead is non negligible (100+MB) and it can potentially confuse the NVIDIA uninstaller thus interfering with drivers upgrades.

If we really want to do it, it should be on the `volume setup` only. Also keep in mind that the `nvidia` package can be used outside of the `nvidia-docker` project, the behavior of `Create` needs to be defined (does it create links or copies?). 

In any case, relying on the plugin to manage the volumes is still preferred.

**Comment by mvollrath** [comment]
Since the plugin doesn't support a Quadro K600, that's not an option for me right now.

I'm integrating nvidia-docker with a system that boots from a read-only image, so the entire root filesystem is overlayfs with the NV driver already installed.  Running the Docker graph on overlay would quickly exhaust it, so a fresh logical volume is prepared at boot.  It looks like I'll have to keep running with my fork until either plugin compatibility is fixed or I can refactor this copy fallback to only affect `volume setup`.
