### ISSUE TITLE
nvidia-docker-plugin could not load NVML library

### ISSUE THREAD

**Issue by stormanger** [NVIDIA/nvidia-docker#470]
I wantg use the low-end card for display, and high-end card for dedicated computing.
So I have switch Intel graphics card first in BIOS and system(by $sudo prime-select intel).
Then set LD_LIBRARY_PATH in /etc/profile:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-375

nvidia-smi can display infomation of GPUs, but nvidia-docker can not start.

$ sudo nvidia-docker-plugin
nvidia-docker-plugin | 2017/09/18 16:29:20 Loading NVIDIA unified memory
nvidia-docker-plugin | 2017/09/18 16:29:20 Loading NVIDIA management library
nvidia-docker-plugin | 2017/09/18 16:29:20 Error: could not load NVML library

$ ldconfig -p | grep nvidia-ml 
This commad show nothing.

Thanks

**Comment by flx42** [comment]
```
$ ldconfig -p | grep nvidia-ml
This commad show nothing.
```
This is your issue. You need to add an entry to `/etc/ld.so.conf.d/` and then run `ldconfig`.

For instance, this is what I have:
```
$ cat /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf 
/usr/lib/nvidia-384
/usr/lib32/nvidia-384
```

**Comment by stormanger** [comment]
It works very well,  thank you for you help @flx42
