### ISSUE TITLE
cannot load UVM device in docker container (on rhel7/centos7)

### ISSUE THREAD

**Issue by nnachefski** [NVIDIA/nvidia-docker#471]
been banging my head on this one for awhile now
- RHEL 7.4
- docker 1.12
- nvidia-docker 1.0.1-1 
- nvidia-smi working fine on the (bare-metal) docker host, deviceQuery also works fine there.

in my container, i make the deviceQuery bin just fine (i have cuda 8 libs installed), but when i try to run it... no dice.  an strace reveals:
stat("/dev/nvidia-uvm", 0x7ffc23ea4730) = -1 ENOENT (No such file or directory)                                                                                                                                                    

### from the docker host, everything looks fine
`# systemctl status nvidia-docker.service 
● nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/usr/lib/systemd/system/nvidia-docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-09-18 10:37:07 CDT; 26min ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 104381 ExecStopPost=/bin/rm -f $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 104392 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 104386 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
 Main PID: 104385 (nvidia-docker-p)
   Memory: 6.6M
   CGroup: /system.slice/nvidia-docker.service
           └─104385 /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker

Sep 18 10:37:07  Starting NVIDIA Docker plugin...
Sep 18 10:37:07  Started NVIDIA Docker plugin.
Sep 18 10:37:07 nvidia-docker-plugin[104385]: /usr/bin/nvidia-docker-plugin | 2017/09/18 10:37:07 Loading NVIDIA unified memory
Sep 18 10:37:07 nvidia-docker-plugin[104385]: /usr/bin/nvidia-docker-plugin | 2017/09/18 10:37:07 Loading NVIDIA management library
Sep 18 10:37:08 nvidia-docker-plugin[104385]: /usr/bin/nvidia-docker-plugin | 2017/09/18 10:37:08 Discovering GPU devices
Sep 18 10:37:08nvidia-docker-plugin[104385]: /usr/bin/nvidia-docker-plugin | 2017/09/18 10:37:08 Provisioning volumes at /var/lib/nvidia-docker/volumes
Sep 18 10:37:08 nvidia-docker-plugin[104385]: /usr/bin/nvidia-docker-plugin | 2017/09/18 10:37:08 Serving plugin API at /var/lib/nvidia-docker
Sep 18 10:37:08 nvidia-docker-plugin[104385]: /usr/bin/nvidia-docker-plugin | 2017/09/18 10:37:08 Serving remote API at localhost:3476
`

**Comment by nnachefski** [comment]
also, drivers are loaded in the container:

`sh-4.2# lsmod |grep nvidia                                                                                                                                                                                                         
nvidia_uvm            675742  2                                                                                                                                                                                                    
nvidia_drm             44108  0                                                                                                                                                                                                    
nvidia_modeset        841636  1 nvidia_drm                                                                                                                                                                                         
nvidia              13114055  27 nvidia_modeset,nvidia_uvm                                                                                                                                                                         
drm_kms_helper        159169  1 nvidia_drm                                                                                                                                                                                         
drm                   370825  3 drm_kms_helper,nvidia_drm                                                                                                                                                                          
i2c_core               40756  4 drm,i2c_i801,drm_kms_helper,nvidia          `

**Comment by flx42** [comment]
Does `/dev/nvidia-uvm` exists on the host?
What was the command you used to run the container?

**Comment by nnachefski** [comment]
it does not:

sh-4.2# stat /dev/nvidia-uvm                                                                                                                                                                                                       
stat: cannot stat '/dev/nvidia-uvm': No such file or directory  

docker run docker-registry.default.svc:5000/nmo-demo/nmo-demo

**Comment by flx42** [comment]
You need to do `nvidia-docker run`, our CLI wrapper will take care of creating the device file it it doesn't exist.

**Comment by nnachefski** [comment]
nvidia-docker run docker-registry.default.svc:5000/nmo-demo/nmo-demo

docker exec -it 43fb03e57ba3 /bin/bash
[root@43fb03e57ba3 notebooks]# stat /dev/nvidia-uvm 
stat: cannot stat '/dev/nvidia-uvm': No such file or directory

**Comment by flx42** [comment]
Does your docker image extends one of our DockerHub image?
Please try with the `nvidia/cuda` image first.

**Comment by nnachefski** [comment]
https://github.com/nnachefski/nmo-demo.git

It's based on RHEL7 / CENTOS7 images.

**Comment by flx42** [comment]
`nvidia-docker` needs a special `LABEL` to recognize GPU images.
The following should make it work:
```
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

**Comment by nnachefski** [comment]
I wish to embed the necessary libraries in the container image, so that it wont need root prive to run...

**Comment by nnachefski** [comment]
`# ldconfig -v |grep cuda                                                                                                                                                                                                     
/usr/local/cuda-8.0/targets/x86_64-linux/lib:                                                                                                                                                                                      
        libcudart.so.8.0 -> libcudart.so.8.0.61                                                                                                                                                                                    
        libcuda.so.1 -> libcuda.so.384.66                                                                                                                                                                                          

sh-4.2# ldconfig -v |grep nvidia                                                                                                                                                                                                   
/usr/lib64/nvidia:                                                                                                                                                                                                                 
        libnvidia-tls.so.384.66 -> libnvidia-tls.so.384.66                                                                                                                                                                         
        libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.384.66                                                                                                                                                        
        libnvidia-opencl.so.1 -> libnvidia-opencl.so.384.66                                                                                                                                                                        
        libnvidia-ml.so.1 -> libnvidia-ml.so.384.66                                                                                                                                                                                
        libnvidia-ifr.so.1 -> libnvidia-ifr.so.384.66                                                                                                                                                                              
        libnvidia-gtk3.so.384.66 -> libnvidia-gtk3.so.384.66                                                                                                                                                                       
        libnvidia-gtk2.so.384.66 -> libnvidia-gtk2.so.384.66                                                                                                                                                                       
        libnvidia-glsi.so.384.66 -> libnvidia-glsi.so.384.66                                                                                                                                                                       
        libnvidia-glcore.so.384.66 -> libnvidia-glcore.so.384.66                                                                                                                                                                   
        libnvidia-fbc.so.1 -> libnvidia-fbc.so.384.66                                                                                                                                                                              
        libnvidia-fatbinaryloader.so.384.66 -> libnvidia-fatbinaryloader.so.384.66                                                                                                                                                 
        libnvidia-encode.so.1 -> libnvidia-encode.so.384.66                                                                                                                                                                        
        libnvidia-eglcore.so.384.66 -> libnvidia-eglcore.so.384.66                                                                                                                                                                 
        libnvidia-egl-wayland.so.1.0.1 -> libnvidia-egl-wayland.so.1.0.1                                                                                                                                                           
        libnvidia-compiler.so.384.66 -> libnvidia-compiler.so.384.66                                                                                                                                                               
        libnvidia-cfg.so.1 -> libnvidia-cfg.so.384.66                                                                                                                                                                              
        libGLX_nvidia.so.0 -> libGLX_nvidia.so.384.66                                                                                                                                                                              
        libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.384.66                                                                                                                                                                        
        libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.384.66                                                                                                                                                                  
        libEGL_nvidia.so.0 -> libEGL_nvidia.so.384.66                                                                                                                                                                              
        libGLX_nvidia.so.0 -> libGLX_indirect.so.0                                                                                                                                                                                 
/usr/lib64/nvidia/tls: (hwcap: 0x8000000000000000)                                                                                                                                                                                 
        libnvidia-tls.so.384.66 -> libnvidia-tls.so.384.66 `

**Comment by nnachefski** [comment]
I got it working... thanks for your time!

./deviceQuery Starting...                                                                                                                                                                                                          
                                                                                                                                                                                                                                   
 CUDA Device Query (Runtime API) version (CUDART static linking)                                                                                                                                                                   
                                                                                                                                                                                                                                   
Detected 1 CUDA Capable device(s)                                                                                                                                                                                                  
                                                                                                                                                                                                                                   
Device 0: "GeForce GTX 980"                                                                                                                                                                                                        
  CUDA Driver Version / Runtime Version          9.0 / 8.0                                                                                                                                                                         
  CUDA Capability Major/Minor version number:    5.2                                                                                                                                                                               
  Total amount of global memory:                 4038 MBytes (4233887744 bytes)                                                                                                                                                    
  (16) Multiprocessors, (128) CUDA Cores/MP:     2048 CUDA Cores                                                                                                                                                                   
  GPU Max Clock rate:                            1291 MHz (1.29 GHz)                                                                                                                                                               
  Memory Clock rate:                             3505 Mhz                                                                                                                                                                          
  Memory Bus Width:                              256-bit                                                                                                                                                                           
  L2 Cache Size:                                 2097152 bytes                                                                                                                                                                     
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)                                                                                                                              
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers                                                                                                                                                           
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers                                                                                                                                                    
  Total amount of constant memory:               65536 bytes                                                                                                                                                                       
  Total amount of shared memory per block:       49152 bytes                                                                                                                                                                       
  Total number of registers available per block: 65536                                                                                                                                                                             
  Warp size:                                     32                                                                                                                                                                                
  Maximum number of threads per multiprocessor:  2048                                                                                                                                                                              
  Maximum number of threads per block:           1024                                                                                                                                                                              
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)                                                                                                                                                                   
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)                                                                                                                                                         
  Maximum memory pitch:                          2147483647 bytes                                                                                                                                                                  
  Texture alignment:                             512 bytes                                                                                                                                                                         
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)                                                                                                                                                         
  Run time limit on kernels:                     No                                                                                                                                                                                
  Integrated GPU sharing Host Memory:            No                                                                                                                                                                                
  Support host page-locked memory mapping:       Yes                                                                                                                                                                               
  Alignment requirement for Surfaces:            Yes                                                                                                                                                                               
  Device has ECC support:                        Disabled                                                                                                                                                                          
  Device supports Unified Addressing (UVA):      Yes                                                                                                                                                                               
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0                                                                                                                                                                         
  Compute Mode:                                                                                                                                                                                                                    
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >                                                                                                                                      
                                                                                                                                                                                                                                   
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GTX 980                                                                                                   
Result = PASS
