### ISSUE TITLE
Using windows GPU containers on windows 2016

### ISSUE THREAD

**Issue by IanHot** [NVIDIA/nvidia-docker#473]
I would like to use Containerised GPU application on Windows server 2016. When will NVidia provide a Windows version of NVidia Docker? 
If never/not in the near future can I install standard docker on a Machine with one k80, pre-installed with the Cuda driver and then use one Windows container, with the Cuda toolikit,  at a time?

Thanks

**Comment by 3XX0** [comment]
Unfortunately Windows is not supported, see #197 and all the linked issues
