### ISSUE TITLE
Include nvml.h in the repo?

### ISSUE THREAD

**Issue by yongtang** [NVIDIA/nvidia-docker#477]
Not sure if this repo is the right place for this question. In `nvidia-docker/src/nvml/nvml_dl.h` the `nvml.h` header file is included:

https://github.com/NVIDIA/nvidia-docker/blob/d8e8727788aaf0012a4bcfab4d55b7bc5eb718b6/src/nvml/nvml_dl.h#L3-L9

However, this header file is not part of the repo. Instead, it is downloaded and installed through `nvidia-docker/Dockerfile.build`.

In case a vendoring of nvidia-docker is needed, it adds additional requirements for downstream repo.

I am wondering if it is possible to include `nvml.h` inside nvidia-docker directly?

/cc @flx42

**Comment by 3XX0** [comment]
No unfortunately, nvml and the CUDA runtime are part of the CUDA toolkit and hence should go through EULA/license agreements. Moreover these packages are going away in 2.0 so they won't be maintained in the long term.
