### ISSUE TITLE
nvidia-docker does not seem to work with nvidia-driver ver 384.90 

### ISSUE THREAD

**Issue by Yong-Zhuang** [NVIDIA/nvidia-docker#480]
When I tried to run nvidia-docker, I got the following error message:
nvidia-docker | 2017/09/27 22:08:44 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

Here is the output of "nvidia-smi":
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:08:00.0  On |                  N/A |
| 24%   38C    P8     9W / 151W |    379MiB /  8105MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1466      G   /usr/lib/xorg/Xorg                           271MiB |
|    0      2826      G   compiz                                       106MiB |
+-----------------------------------------------------------------------------+

And here is the output  of "ldconfig -p | grep -E 'libcuda|libnvidia'"
	libnvidia-wfb.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-wfb.so.1
	libnvidia-wfb.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-wfb.so.1
	libnvidia-tls.so.384.90 (libc6,x86-64, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.90
	libnvidia-tls.so.384.90 (libc6,x86-64, OS ABI: Linux 2.2.5) => /usr/lib/nvidia-384/libnvidia-tls.so.384.90
	libnvidia-tls.so.384.90 (libc6, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /usr/lib32/nvidia-384/tls/libnvidia-tls.so.384.90
	libnvidia-tls.so.384.90 (libc6, OS ABI: Linux 2.2.5) => /usr/lib32/nvidia-384/libnvidia-tls.so.384.90
	libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ptxjitcompiler.so.1
	libnvidia-ptxjitcompiler.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ptxjitcompiler.so.1
	libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so
	libnvidia-ifr.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ifr.so.1
	libnvidia-ifr.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ifr.so.1
	libnvidia-ifr.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ifr.so
	libnvidia-ifr.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ifr.so
	libnvidia-gtk3.so.384.90 (libc6,x86-64) => /usr/lib/libnvidia-gtk3.so.384.90
	libnvidia-gtk2.so.384.90 (libc6,x86-64) => /usr/lib/libnvidia-gtk2.so.384.90
	libnvidia-glsi.so.384.90 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-glsi.so.384.90
	libnvidia-glsi.so.384.90 (libc6) => /usr/lib32/nvidia-384/libnvidia-glsi.so.384.90
	libnvidia-glcore.so.384.90 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-glcore.so.384.90
	libnvidia-glcore.so.384.90 (libc6) => /usr/lib32/nvidia-384/libnvidia-glcore.so.384.90
	libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fbc.so.1
	libnvidia-fbc.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-fbc.so.1
	libnvidia-fbc.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fbc.so
	libnvidia-fbc.so (libc6) => /usr/lib32/nvidia-384/libnvidia-fbc.so
	libnvidia-fatbinaryloader.so.384.90 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.90
	libnvidia-fatbinaryloader.so.384.90 (libc6) => /usr/lib32/nvidia-384/libnvidia-fatbinaryloader.so.384.90
	libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-encode.so.1
	libnvidia-encode.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-encode.so.1
	libnvidia-encode.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-encode.so
	libnvidia-encode.so (libc6) => /usr/lib32/nvidia-384/libnvidia-encode.so
	libnvidia-eglcore.so.384.90 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-eglcore.so.384.90
	libnvidia-eglcore.so.384.90 (libc6) => /usr/lib32/nvidia-384/libnvidia-eglcore.so.384.90
	libnvidia-egl-wayland.so.1.0.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-egl-wayland.so.1.0.1
	libnvidia-egl-wayland.so.1.0.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-egl-wayland.so.1.0.1
	libnvidia-compiler.so.384.90 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-compiler.so.384.90
	libnvidia-compiler.so.384.90 (libc6) => /usr/lib32/nvidia-384/libnvidia-compiler.so.384.90
	libnvidia-compiler.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-compiler.so
	libnvidia-compiler.so (libc6) => /usr/lib32/nvidia-384/libnvidia-compiler.so
	libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-cfg.so.1
	libnvidia-cfg.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-cfg.so.1
	libnvidia-cfg.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-cfg.so
	libnvidia-cfg.so (libc6) => /usr/lib32/nvidia-384/libnvidia-cfg.so
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so

Could anyone help me fix this problem?

**Comment by flx42** [comment]
What's the output of:
```
$ which nvidia-modprobe 
```
And:
```
$ nvidia-modprobe -u -c=0
$ echo $?
```

**Comment by Ectsang** [comment]
I have the same issue.

$ nvidia-modprobe -u c=0
nvidia-modprobe: invalid option: "c=0"

ERROR: Invalid commandline, please run `nvidia-modprobe --help` for usage information.

$ echo $?
1

**Comment by gutsal-arsen** [comment]
@Ectsang you missed minus (-) before `c=0`.

**Comment by Yong-Zhuang** [comment]
the output of "$ which nvidia-modprobe" is nothing

the output of "$ nvidia-modprobe -u -c=0" is :+1: 
The program 'nvidia-modprobe' is currently not installed. You can install it by typing:
sudo apt install nvidia-modprobe

the output of "$ echo $?" is 127

**Comment by gutsal-arsen** [comment]
`sudo apt install nvidia-modprobe`
once done show the output of:
```
$ nvidia-modprobe -u -c=0
$ echo $?
```

**Comment by Yong-Zhuang** [comment]
the output of "$ nvidia-modprobe -u -c=0" is nothing.
the output of "echo $?" is 0

**Comment by gutsal-arsen** [comment]
@flx42

**Comment by Yong-Zhuang** [comment]
After I installed nvidia-modprobe, I reinstalled nvidia-docker, and then it is working now. Thank you @flx42 and @gutsal-arsen .

**Comment by flx42** [comment]
Thanks @gutsal-arsen!

**Comment by gutsal-arsen** [comment]
@flx42 np

**Comment by bushibushi** [comment]
Hi, after the update to 384.90 and a nvidia-docker reinstallation I no access to nvidia-smi in dockers including the installation check:
```
$ nvidia-docker run --rm nvidia/cuda nvidia-smi
container_linux.go:265: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH".
```

**Comment by gutsal-arsen** [comment]
@bushibushi I think that you should update nvidia drivers to 384.90 inside container too.

**Comment by bushibushi** [comment]
I thought the cuda containers were driver independent ?

**Comment by flx42** [comment]
@bushibushi they **are** driver independent. Please don't install the driver inside the container :)
I suggest you try out [nvidia-docker 2.0](https://github.com/NVIDIA/nvidia-docker/tree/2.0), it will likely solve your issue.
If you don't want to upgrade yet, what's the output of `ls -R /var/lib/nvidia-docker`?

**Comment by gutsal-arsen** [comment]
@flx42 well, never used nvidia-docker as I can't run it on my highly partitioned system ;) /opt, /usr/ /var stuff are all different partitions and `nvidia-docker` does not like it. Does `nvidia-docker 2.0` has the same issue?

**Comment by flx42** [comment]
@gutsal-arsen no, it doesn't have the same-partition issue.

**Comment by bushibushi** [comment]
@flx42 
```
$ ls -R /var/lib/nvidia-docker
/var/lib/nvidia-docker:
nvidia-docker.sock
```

**Comment by flx42** [comment]
And `docker volume ls`?

**Comment by bushibushi** [comment]
Well we use docker a lot:
```
$ docker volume ls | wc -l
2111
```
But indeed something is weird:
```
$ docker volume ls | grep nvidia
nvidia-docker       nvidia_driver_375.26
local               nvidia_driver_384.90
```

**Comment by bushibushi** [comment]
I am trying the nvidia-docker2 option.

**Comment by flx42** [comment]
```
local               nvidia_driver_384.90
```
Try removing this volume please.

**Comment by bushibushi** [comment]
Well it seems to be in use, investigating...

**Comment by bushibushi** [comment]
@flx42  Thanks, I finally managed to remove it and reinstall nvidia-docker (1), it works now.

**Comment by gutsal-arsen** [comment]
Wow, that's great then. Will try it right away :) Thank you @flx42
