### ISSUE TITLE
Unsupported Docker Version (17.09.0-ce)

### ISSUE THREAD

**Issue by KamranAlipour** [NVIDIA/nvidia-docker#482]
For Docker version 17.09.0-ce :+1: 
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
I get this message when trying to install nvidia-docker 1.0.1:

Selecting previously unselected package nvidia-docker.
(Reading database ... 216490 files and directories currently installed.)
Preparing to unpack .../nvidia-docker_1.0.1-1_amd64.deb ...
Unpacking nvidia-docker (1.0.1-1) ...
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16); however:
  Package sysv-rc is not installed.
  Package file-rc is not installed.

dpkg: error processing package nvidia-docker (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 nvidia-docker

**Comment by flx42** [comment]
This is unrelated to `17.09.0`, what's your distro?

**Comment by KamranAlipour** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

**Comment by flx42** [comment]
See #412
