### ISSUE TITLE
Nvidea-docker within VM-enviroment

### ISSUE THREAD

**Issue by Brm-Bremen** [NVIDIA/nvidia-docker#485]
We are planning a System using a Nvidea-GPU and the Nvidea-docker-Software. We need it to work within a Virtual Environment like ESXi.
Is it possible/have you tried to use ESXi (or something similar) with PCI Passthrough to run Nvidea-docker inside.

Best Regards
Joscha Knobloch

**Comment by flx42** [comment]
With PCI passthrough and the NVIDIA driver installed in the VM, it should work fine. I've done it with KVM.
