### ISSUE TITLE
Execute nvidia-docker inside docker container

### ISSUE THREAD

**Issue by cmdhema** [NVIDIA/nvidia-docker#487]
I want execute nvidia-docker inside docker container. I already checked issue #380. The issue is using rest api for getting arguments(device, volume). I understand this way. But I want using nvidia-docker command in container. <nvidia-docker run [ some commands] > command inside docker container.

For that, I try this way.
I installed nvidia-docker to host and It worked well. Next,  I copy nvidia-docker executable file in the host to container. Then, I create Docker container and run <nvidia-docker run> command in docker container, but I got Could not load UVM kernel module. Is nvidia-modprobe installed? message.

Is it impossble nvidia-docker command inside container?

Thanks

**Comment by 3XX0** [comment]
Unfortunately that's not possible.
However, you might want to check nvidia-docker 2.0
I didn't try it but it might work as long as you pass the Docker socket (as opposed to DinD)

**Comment by cmdhema** [comment]
Thansk your reply.
