### ISSUE TITLE
consult about  run the  tensorflow through  tensorflow-gpu？

### ISSUE THREAD

**Issue by jidong029** [NVIDIA/nvidia-docker#488]
Now ，I have install  nvidia-drivers 375.66，and install nvidia-docker；
then I pull  the  tensorflow-gpu  through nvidia-docker pull ，now  I donot know how to  install 
the  cuda and curnn  outside the container  or  install them  in the container，I donot know how to
resolve this？Thanks very much

**Comment by illagrenan** [comment]
You shouldn't install CUDA on host (nvidia-drivers and nvidia-docker are enough). If you need CUDA inside running container, you can use this https://hub.docker.com/r/nvidia/cuda/ as a base image (`FROM` directive).

**Comment by jidong029** [comment]
Thanks for your help @illagrenan ，now I know  what you point out ，now to run the tensorflow-gpu need the cuda and cudnn lib，for example when I  download the cuda image ，what  can I do to mix the different containter such as cuda  image and tensorflow-gpu image together ，when I  run the containter I can run them in the same containter？

**Comment by flx42** [comment]
TensorFlow provides prebuilt Docker images with GPU support. They are based on our CUDA images from DockerHub:
https://www.tensorflow.org/install/install_linux#installing_with_docker
