### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by zloidemon** [NVIDIA/nvidia-docker#489]
Host system:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
```
# nvidia-smi
Mon Oct  9 20:24:33 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.12                 Driver Version: 387.12                    |
|-------------------------------+----------------------+----------------------+
```

```
container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: invalid CUDA version: 387\\\\n\\\"\""
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: invalid CUDA version: 387\\\\n\\\"\"".
```

**Comment by flx42** [comment]
@zloidemon thanks for the bug report, what was your command line?

**Comment by zloidemon** [comment]
Sorry missed command.

```
docker run -it --rm --runtime=nvidia test_cuda_image
```

Kernel version
```
Linux 4.4.0-78-generic
```

nvidia_cuda_test 
```
ARG  VERSION=16.04
FROM ubuntu:${VERSION}

RUN apt-get update && apt-get upgrade -y \
    && apt-get -y install software-properties-common wget ca-certificates \
    curl libcurl3

ENV CUDA_VERSION 387

RUN add-apt-repository ppa:graphics-drivers/ppa && apt-get update \
    && apt-get install -y libcuda1-${CUDA_VERSION} \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by flx42** [comment]
This variable collides with the one we're using to control our runtime:
`ENV CUDA_VERSION 387`
See our documentation:
https://github.com/nvidia/nvidia-container-runtime#cuda_version

This value is not a valid CUDA version, we expect `major.minor`, look at our CUDA Dockerfile:
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile#L12

You shouldn't install `libcuda` inside the image by the way, it's actually part of the driver so it will be taken care by our runtime. There is also `libcudart`, and this one is indeed part of the CUDA toolkit.

Also, I don't recommend using this PPA, use our official repositories instead:
https://github.com/NVIDIA/nvidia-docker/issues/481#issuecomment-335222350

**Comment by zloidemon** [comment]
i've migrated to use drivers from your comment and cuda-9.0 docker image. it works.
