### ISSUE TITLE
Installation tries to write to /go/bin

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#49]
I'm getting the following error when I run `sudo make install`:
```
...
go install nvidia-docker-plugin: open /go/bin/nvidia-docker-plugin: permission denied
go install nvidia-docker: open /go/bin/nvidia-docker: permission denied
make[1]: *** [build] Error 1
make[1]: Leaving directory `<path to nvidia-docker>/nvidia-docker/tools'
make: *** [install] Error 2
```

It seems like it's trying to write to a directory that doesn't exist... 

I eventually fixed the issue by editing the Makefile in `tools/`, where I removed `:/go/bin` at line 27 (as of hash e7b792253f0d0ad1bed19a3236db0ac58aaf9563). 

Am I doing something wrong? Am I the only person who experienced this?

Running on Ubuntu 14.04.

**Comment by flx42** [comment]
This is happening inside a container, and in this container `/go/bin` is a volume:
https://github.com/NVIDIA/nvidia-docker/blob/master/tools/Dockerfile.build#L23

This volume maps to `[...]/nvidia-docker/tools/bin` on the host. After executing the build container, this directory will contain the `nvidia-docker` and `nvidia-docker-plugin` binaries. These binaries are then installed (`install(1)`) the usual way to the `$PREFIX` path (default is `/usr/bin`).

I'm not sure how you encounter this issue, folder `nvidia-docker/tools/bin` could have weird permissions on the host. Try removing it.
Also, are you running Docker the usual way with your account being part of the `docker` group?

**Comment by grisaitis** [comment]
Thanks for the leads! 

I think my user is part of the docker group, but maybe root isn't. Perhaps that causes a problem when I try to `sudo make install`.

And about permissions on `tools/bin`, what should those be? Owned by root, 755? I may have tried to make as my own casual user, after the failed attempts with sudo. 

Thanks for the help!

**Comment by flx42** [comment]
I was able to recreate a similar error message using `sudo make` and then `make install`. Of course this is backward: the first command will create `tools/bin` for root and the second command will fail when the volume is mounted.

From your initial post, it doesn't seem to be what you did, but it confirms there is something fishy on the permissions. The permissions you mentioned look fine, but you can simply erase 'tools/bin', it's not part of the git repo.

**Comment by 3XX0** [comment]
It would be interesting to know what's going on in your particular case. As a workaround you can always use the release tarball/package: https://github.com/NVIDIA/nvidia-docker/releases

**Comment by grisaitis** [comment]
@flx42 I bet I did that actually - I was trying several commands and permutations of with or without sudo and make / make install. My bad for not thinking about permissions. Thanks for identifying that. 

@3XX0 Good to know. I didn't install from the deb because it was from an older commit on the repo... But now I see that the commit only impacted the cudnn dockerfile. 

Thanks again for your help!
