### ISSUE TITLE
Override daemon.json configuration

### ISSUE THREAD

**Issue by zloidemon** [NVIDIA/nvidia-docker#490]
I had my configuration:
```
{
	"hosts": [
		"tcp://127.0.0.1:2375",
		"unix:///var/run/docker.sock"
	]
}
```

After installation it changed to:
```
{
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

Although it should looks like
```
{
    "hosts": [
        "tcp://127.0.0.1:2375",
        "unix:///var/run/docker.sock"
    ],
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

**Comment by flx42** [comment]
`apt-get` should have complained when the package was installed, right?

Unfortunately, it would not be trivial to merge our file with an existing one when installing the package. It would require merging 2 JSON files in a shell script.

Until we can have a better solution (maybe by asking the Docker community), did you consider using a systemd drop-in file for your other settings? That's what we do internally when deploying docker with a custom configuration + nvidia-docker 2.0. The base settings of `dockerd` (hosts, storage driver, bridge IP and CIDR range for `docker0`, log driver, etc.) are in the drop-in file.

That's what I have on my machine:
```
$ sudo cat /etc/systemd/system/docker.service.d/override.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --host=fd:// --storage-driver=overlay2
```

**Comment by zloidemon** [comment]
Yeah, I might add that configuration to init file, i've just showed the issue. I'm able to modify my files by hands. You can close that issue if it won't nvidia-docker issue

**Comment by eromoe** [comment]
I merge  the file manually : 

```
{
    "registry-mirrors": ["https://mytfd7zc.mirror.aliyuncs.com"],
    "insecure-registries" : [ "10.142.55.199:5006"] },
    "graph": "/data/dockerdata",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

But still get error `docker: Error response from daemon: Unknown runtime specified nvidia.`

**Comment by flx42** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#why-do-i-get-the-error-unknown-runtime-specified-nvidia
