### ISSUE TITLE
[Feature] Add out-of-the-box support for Bumblebee/Optimus in service file

### ISSUE THREAD

**Issue by jerluc** [NVIDIA/nvidia-docker#491]
Presently the [service unit](https://github.com/NVIDIA/nvidia-docker/blob/master/build/common/nvidia-docker.service) is automatically installed to directly run the `nvidia-docker-plugin` server. This seems to work fine for most desktop/workstation setups.

On setups which use Bumblebee/Optimus to dynamically switch the GPU on or off (usually for power savings on laptops), it is important to prefix the `ExecStart=...` line with something like `/usr/bin/optirun`, which will run the plugin server while activating the GPU through Bumblebee/Optimus.

This change shouldn't be too terribly difficult, but would require some kind of change in the build or installation process in order to prompt or automatically check for the location of an existing Bumblebee/Optimus installation.

I'd be more than happy to look into adding this feature if you could point me in the right direction of where this file actually gets installed.

**Comment by 3XX0** [comment]
Bumblebee/Optimus is not supported by NVIDIA and you don't need it to run CUDA applications (see #16).

Also, there is no plugin in the latest nvidia-docker version (2.0)
