### ISSUE TITLE
Error response from daemon: open /var/lib/docker/overlay2/xxx: no such file or directory

### ISSUE THREAD

**Issue by ljf1239848066** [NVIDIA/nvidia-docker#492]
`docker save -o wx356312_tf.tar wx356312_tf:latest`
Error response from daemon: open /var/lib/docker/overlay2/dc31e35980f8d37cb3d2eca91aafd6244dfb0d077edf594dedbcf35ab0f5825f/merged/home/train/train-00001-of-00002: no such file or directory

**Comment by flx42** [comment]
That's not a `nvidia-docker` problem, it's a problem with your `docker` installation.

**Comment by huawei-tomas** [comment]
is there a related issue anywhere? I'm seeing this too and can't find any help

**Comment by ericgong1993** [comment]
whats the solution?

**Comment by flx42** [comment]
Again: it's not a problem with `nvidia-docker`. Or, if you think it is, show us it's not happening with regular `docker`.
