### ISSUE TITLE
Cannot start existing container anymore after driver upgrade to 384.90 

### ISSUE THREAD

**Issue by hahne** [NVIDIA/nvidia-docker#493]
I cannot start existing container anymore after driver upgrade to 384.90. I get the message:
Error response from daemon: get nvidia_driver_381.22: no such volume: nvidia_driver_381.22

It is working fine if I create a new container (from the same image).

Is there any possibility to upgrade this volume of the existing container from nvidia_driver_381.22 to nvidia_driver_384.90?

**Comment by flx42** [comment]
@hahne no, it's not possible, you have to create a new container. To keep the state, you could `docker commit` into a new image then start a new container.

This will be fixed by version 2.0 that's in alpha state right now:
https://github.com/NVIDIA/nvidia-docker/tree/2.0

**Comment by hahne** [comment]
Ok thank you for the info!

**Comment by 3XX0** [comment]
Fixed in 2.0/master.
