### ISSUE TITLE
Cannot adjust power limit via nvidia-smi

### ISSUE THREAD

**Issue by amoskyler** [NVIDIA/nvidia-docker#495]
I get the following error when I try adjusting the gpu power limit inside the container. I am able to execute `nvidia-smi` and output details about the gpus. The below command works when I run it from the host itself.

```
root@a09a42caceb9:/# nvidia-smi -i 0 -pl 120
Failed to set power management limit for GPU 00000000:01:00.0: Insufficient Permissions
```

**Comment by flx42** [comment]
See:
https://docs.docker.com/engine/security/security/#linux-kernel-capabilities

You need to start your container with `--cap-add=SYS_ADMIN`
