### ISSUE TITLE
X Error of failed request: BadValue

### ISSUE THREAD

**Issue by nmindz** [NVIDIA/nvidia-docker#496]
I was looking through the issues and found a [problem somehow like mine](https://github.com/NVIDIA/nvidia-docker/issues/136), however while I am not trying to launch a Xorg server from a secondary graphics, I am having a similar issue which I am almost sure to be permissions related, but I have no clue where else to look at. I am also aware that this is probably unsupported, but would love to get some input from people who know and have worked more with `nvidia-docker` than I.

I would like to run a graphic intensive application with an out-of-range UID/GID so that it would clearly be visible from the host that those processes belong to the container, and also as a means to ensure that those processes would run with minimum privileges. (Please bear in mind that in this case I have chosen a UID/GID that actually _exists_ in the host, for the sake of debugging.)

I can run any graphical application and have it's GUI display properly as long as I am running it as **root** inside the container. When I change shells to my newly created, unprivileged user, it silently fails with

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  562
  Current serial number in output stream:  563
```

I can notice the taskbar icon launching in the host but a brief second later it crashes and vanishes with the above error.

I have checked devices permissions, `/tmp/.X11-unix`, `/tmp/.host_Xauthority` and the app folder I am running from and so far it seems like the user would have no problem reading, writing or executing to those. Any other ideas?

```
nvidia-docker run -it \
--device /dev/snd \
--device /dev/nvidia0 \
--device /dev/nvidiactl \
--device /dev/nvidia-modeset \
--device /dev/nvidia-uvm \
--device /dev/nvidia-uvm-tools \
-e DISPLAY=$DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix:rw \
-v $XAUTHORITY:/tmp/.host_Xauthority:ro \
-v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro \
-v /dev/shm:/dev/shm \
-v /etc/machine-id:/etc/machine-id \
-v /etc/localtime:/etc/localtime \
--net=host \
--shm-size="4G" \
--name=wine \
 nmindz/wine-app /bin/bash
```
I have created several re-usable images for each app/requirement I have so I have concatenated below all the _Dockerfiles_ from a couple images in one, in order to make clear what's running inside the container and how it has been configured. Please ignore if there are repeated or similar statements as they would be overwritten by each stage on an app-by-app basis.
```
FROM debian

RUN apt-get update

LABEL com.nvidia.volumes.needed="nvidia_driver"

RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

RUN apt-get update && apt-get install -y wget software-properties-common apt-transport-https gnupg zenity libntlm0 libntlm0-dev cabextract winbind less man htop vim

RUN dpkg --add-architecture i386 \
    && wget -nc https://dl.winehq.org/wine-builds/Release.key \
    && apt-key add Release.key \
    && echo "deb https://dl.winehq.org/wine-builds/debian/ stretch main" >> /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install --install-recommends -y winehq-stable

RUN wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
    && chmod +x winetricks \
    && mv ./winetricks /usr/local/bin/winetricks

RUN apt-get install -y sudo \
    && echo 'wine ALL = NOPASSWD: ALL' > /etc/sudoers.d/wine \
    && chmod 0440 /etc/sudoers.d/wine

RUN adduser --disabled-password --gecos 'wine' wine \
    && usermod -a -G video,audio wine

# https://wiki.winehq.org/Debian
RUN apt-get update -y \
    && apt-get install --install-recommends -y winehq-staging

ENV HOME /home/wine
VOLUME /home/wine

COPY machine-id /etc/
RUN groupadd -r -g 35 x11user \
    && useradd -r -u 1001 -g 35 -m -c "X11 App User" -d /home/x11user -s /bin/bash x11user \
    && usermod -a -G video,audio x11user

WORKDIR /games
CMD bash
```
Please, bear in mind this is a devel and testing container, therefore the usage of htop, man, less, etc... from inside the container. The user I am trying to launch apps with is **x11user**.

Thanks for any input, suggestion or ideas that might come, as I am currently left with none. 😃

**Comment by nmindz** [comment]
Some further debugging led me to find that `glxinfo` displays the same error when run without `sudo`. When running the command as root (_sudo_) it works like a charm.

You can check it [here](https://ghostbin.com/paste/zj9sp).

**Comment by nmindz** [comment]
I have abandoned that project since further software-specific limitations would require .NET which rendered the whole Wine thing pointless.

However, to those wondering, it seemed that the `X_GLXCreateContext` error was related to unsufficient permissions to the container side of things. I was unable to (as I did not put that much effort after I had to abandon my project) debug and track down to which specific container permission I was missing; but adding the `--privileged` switch to the `docker run` statement fixed that error in this case.

I am leaving this here as a future reference to adventurers who can't find enough resources on this generic `BadValue` error.

**Comment by bigbellmercy** [comment]
In my case this error 'BadValue' and '153' disappeared after I disconnected my secondary monitor from my PC. FYI, I am using a Nvidia card and Ubuntu 18.04.

**Comment by wbzhang233** [comment]
How to slove this problem below?
![问题1](https://user-images.githubusercontent.com/38639755/109250846-56c7f480-7825-11eb-8480-2e2010f53da4.jpg)
![问题2](https://user-images.githubusercontent.com/38639755/109250861-5b8ca880-7825-11eb-86c7-4c9dfd1b21a9.jpg)
