### ISSUE TITLE
Docker version 17.10.0-ce

### ISSUE THREAD

**Issue by mpekalski** [NVIDIA/nvidia-docker#502]
There is new docker version, could you please update dependencies to require docekr >=17.09.0~ce-0~ubuntu

```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 17.09.0~ce-0~ubuntu) but 17.10.0~ce-0~ubuntu is to be installed or
                           docker-ee (= 17.09.0~ce-0~ubuntu) but it is not installable or
                           docker-engine (= 17.09.0~ce-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by flx42** [comment]
Hello @mpekalski,

Unfortunately, until `runc` reaches version `1.0.0`, we need to pin the version of the docker dependency.
I wasn't planning to support [edge releases](https://docs.docker.com/release-notes/docker-ce/) of Docker CE initially because they release too often. Any reason you absolutely need `17.10`?

**Comment by mpekalski** [comment]
Recently I had problems with 17.06 (diff folder growing too much) and I upgraded to the newest one which apparently is 17.10, so I hoped I would not have to downgrade.

**Comment by flx42** [comment]
The new stable is `17.09`, did you try this one? You probably enabled the `edge` package repository when installing Docker.

**Comment by mpekalski** [comment]
I have downgraded the docker to 17.09.

**Comment by flx42** [comment]
Ok, so I assume it's working now. Closing.

**Comment by mpekalski** [comment]
Yes, it works fine now.

**Comment by tiangolo** [comment]
To downgrade my installation I used the instructions in: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1

In my case, the command was:

```bash
sudo apt-get install docker-ce=17.09.0~ce-0~ubuntu
```

And it worked afterwards.
