### ISSUE TITLE
how to use nvidia-docker to create service in docker swarm

### ISSUE THREAD

**Issue by saikishor** [NVIDIA/nvidia-docker#506]
Hello all,

How do use nvidia-docker to create service in swarm mode of docker operation. I am trying to train a tensorflow model in this swarm network to undergo distributed learning. I found that one way could be to run a swarm network of different containers in different machines and use GPU on each machine to undergo [distributed training](https://www.tensorflow.org/deploy/distributed). If its not possible in swarm mode, Is there any possible way to accomplish the above task?

> 
> docker service create --name tensorflow --network overnet saikishor/tfm:test
> azt0tczwkxaqpkh9yaea4laq1
> Since --detach=false was not specified, tasks will be created in the background.
> In a future release, --detach=false will become the default

but with "docker service ls", I have this

> ID                  NAME                MODE                REPLICAS            IMAGE                   PORTS
> uf6jgp3tm6dp        tensorflow          replicated          0/1                 saikishor/tfm:test

**Comment by 3XX0** [comment]
With nvidia-docker 2.0 it should be possible, unfortunately some pieces are not yet exposed by the docker CLI (see https://github.com/moby/moby/issues/33439)

**Comment by 3XX0** [comment]
Closing since the missing pieces are on the Docker side.
