### ISSUE TITLE
-bash: /usr/bin/nvidia-docker: No such file or directory

### ISSUE THREAD

**Issue by modInfo** [NVIDIA/nvidia-docker#509]
On Alpine Linux

alpineqemu:/tmp# ls -la /usr/bin/nvidia-docker*
-rwxr-xr-x    1 root     root       6799520 Oct 30 12:12 /usr/bin/nvidia-docker
-rwxr-xr-x    1 root     root       7187912 Oct 30 12:12 /usr/bin/nvidia-docker-plugin

**Comment by 3XX0** [comment]
Is your `PATH` set correctly?

**Comment by modInfo** [comment]
Yes.

alpineqemu:/tmp# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by 3XX0** [comment]
Oh right, I didn't see you were on Alpine.
Alpine is not supported, our drivers only support glibc-based distros

**Comment by modInfo** [comment]
Ok, thanks.
