### ISSUE TITLE
Readme: Persist DIGITS 6.0

### ISSUE THREAD

**Issue by thomasdf** [NVIDIA/nvidia-docker#510]
The readme: https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS
Says how to make DIGITS 5.0 persist between containers. But not how this is done for DIGITS 6.0.

**Comment by flx42** [comment]
Fixed, thanks for the bug report!

It's still `/jobs` inside the container, but there is a new port to expose for TensorBoard now.
