### ISSUE TITLE
Question about loading url on NVIDIA Docker DIGITS

### ISSUE THREAD

**Issue by SonicsQ** [NVIDIA/nvidia-docker#514]
Hi,

I am implementing DIGITS 5.1 by Nvidia-docker on CentOS  7.2. Both docker and other components are successfully installed. The only one problem is that when I set up the training image folder it will shows that Folder does not exist. I checked the other posts have the same error they said I need to change the folder accessible by www-data but looks like CentOS did not have this option and shows that www-data or apache is invalid. I create a python server by "python -m SimpleHTTPSERVER [port]" to make the folder public and accessible by browser but still not available to access by NVIDIA digits. I know it maybe a really simple question but could anyone please tell me how can I fix it?

Regards
![1](https://user-images.githubusercontent.com/13908369/32301916-61a2da7e-bf36-11e7-8a76-60ad55351713.jpg)
![2](https://user-images.githubusercontent.com/13908369/32301917-61b4793c-bf36-11e7-90d4-628d9480e17d.jpg)

**Comment by flx42** [comment]
You should read up about [Docker networking](https://docs.docker.com/engine/userguide/networking/#default-networks).
Short fix: run your container with `--network=host`.

**Comment by SonicsQ** [comment]
Thanks for your reply. But the error remains the same. Besides, I think --network=host did not affect that why the local folder in the server can not be detected. Any thoughts?

**Comment by flx42** [comment]
Wait, your server is running inside the same container as DIGITS? You shouldn't do that. Use `docker-compose` if you need to do something like that.

**Comment by SonicsQ** [comment]
My server is not running inside the same container. I run it in the server's machine but not inside the container. The problem is the url of the folder can not be found, such as "/home/exx/Documents/". It will also show that the folder is not found.

**Comment by SonicsQ** [comment]
I just fix that with changing the parameter of -v in NVidia dockers. Thanks for your help.
