### ISSUE TITLE
no such file or directory: volume name must be unique

### ISSUE THREAD

**Issue by Sklert** [NVIDIA/nvidia-docker#518]
I changed storage of docker according to [this guide](https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169) . It works, but i have a trouble with nvidia-docker. If I explicitly use 
`sudo nvidia-docker-plugin` 
and try run smth, everything works fine. 

But if I try to use 
```
sudo service nvidia-docker start 
nvidia-docker run --rm nvidia/cuda nvidia-smi

```
I get error:
`docker: Error response from daemon: create nvidia_driver_387.12: found reference to volume 'nvidia_driver_387.12' in driver 'nvidia-docker', but got an error while checking the driver: error while checking if volume "nvidia_driver_387.12" exists in driver "nvidia-docker": Post http://%2Frun%2Fdocker%2Fplugins%2Fnvidia-docker.sock/VolumeDriver.Get: dial unix /run/docker/plugins/nvidia-docker.sock: connect: no such file or directory: volume name must be unique.`

Thank you for any help.

**Comment by flx42** [comment]
Is the `nvidia-docker` service running?
What is the output of `docker volume ls`?

Also, did you try [v2](https://github.com/NVIDIA/nvidia-docker/tree/2.0)?

**Comment by Sklert** [comment]
@flx42 , I don't know why, but it works now... Maybe, it works, because I removed old containers and ran new. But I'm not sure, it helped. Everything works great now.

Thank you for your answer. I didn't noticed v2 and it has very interesting pros)
