### ISSUE TITLE
nvidia-docker appears to pass arguments through incorrectly.

### ISSUE THREAD

**Issue by braxtonmckee** [NVIDIA/nvidia-docker#52]
I run the following code and get the resulting output.
```
nvidia-docker run -e UFORA_WORKER_OWN_ADDRESS=10.197.144.141 --workdir=/volumes/ufora -e AWS_ACCESS_KEY_ID=XXXXXXX -e AWS_SECRET_ACCESS_KEY=XXXXX -p 30000asdf:30000asdf -p 30002:30002 -p 30009:30009 -p 30010:30010 --privileged=true -v /mnt/ufora:/var/ufora -v /home/ubuntu/build:/volumes -e PYTHONPATH=/volumes/ufora -e ROOT_DATA_DIR=/mnt/ufora ufora/build:29df74040b988c35cdb94bd8a934958d pwd
Pulling repository docker.io/library/30000asdf
nvidia-docker | 2016/02/20 22:00:17 Error: image library/30000asdf not found
```
the "asdf" is there because I was trying to figure out why it's asking for docker.io/library/30000 and it must be munging the arguments incorrectly in the script somewhere.

I installed nvidia-docker from the binaries. perhaps this is fixed in the latest source and the binaries are out of date?

**Comment by flx42** [comment]
See #46, it was caused by the update to Docker 1.10.
We should be able to release a fix next week.
In the mean time, you can use long options instead like ```--publish=```
