### ISSUE TITLE
Occasional "Error: EOF" from nvidia-docker-plugin

### ISSUE THREAD

**Issue by mafanasyev-tri** [NVIDIA/nvidia-docker#524]
We run nvidia-docker in our CI system, and occasionally (in <5% of the cases), "docker run" fails.
Systemd's log contains:
```
Nov  8 06:30:57 ip-ZZZ nvidia-docker-plugin[15551]: /usr/bin/nvidia-docker-plugin | 2017/11/08 06:30:57 Received activate request
Nov  8 06:30:57 ip-ZZZ nvidia-docker-plugin[15551]: /usr/bin/nvidia-docker-plugin | 2017/11/08 06:30:57 Plugins activated [VolumeDriver]
...
Nov  8 06:35:04 ip-ZZZ nvidia-docker-plugin[15551]: /usr/bin/nvidia-docker-plugin | 2017/11/08 06:35:04 Received create request for volume 'nvidia_driver_384.90'
Nov  8 06:35:11 ip-ZZZ dockerd[2850]: time="2017-11-08T06:35:11.569924236Z" level=warning msg="Unable to connect to plugin: /var/lib/nvidia-docker/nvidia-docker.sock/VolumeDriver.Create: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Create: EOF, retrying in 1s"
Nov  8 06:35:12 ip-ZZZ nvidia-docker-plugin[15551]: /usr/bin/nvidia-docker-plugin | 2017/11/08 06:35:12 Error: EOF
Nov  8 06:35:12 ip-ZZZ dockerd[2850]: time="2017-11-08T06:35:12.578373236Z" level=error msg="Handler for POST /v1.30/containers/create returned error: create nvidia_driver_384.90: VolumeDriver.Create: internal error, check logs for details\n"
```

| Version info | |
| --- | --- |
|Docker version:|17.06.0-ce|
|NVIDIA Docker plugin version:|1.0.1|
|OS version: | Ubuntu 16.04.3 LTS xenial|
|Video card: |4x "GRID K520"|
| Invocation: |  `docker run $(curl -s http://localhost:3476/docker/cli)` |

Docker mentions "check logs for details", but as far as I can see, nvidia-docker-plugin only logs to stdout, and these logs are already included in the snippet and are not very detailed.

**Comment by flx42** [comment]
Probably the same issue as https://github.com/NVIDIA/nvidia-docker/issues/379#issuecomment-305304180

You can try nvidia-docker 2.0, you won't have this issue and you won't need the ugly `curl`.
If you want to stick to 1.0, try provisioning the volume at instance boot:
```
docker volume create --driver=nvidia-docker nvidia_driver_$(modinfo -F version $(modprobe --resolve-alias nvidia))
```

**Comment by mafanasyev-tri** [comment]
Thanks a lot! We will give it a try and report if it is fixed or not (which will take a few days to know for sure, as the problem is sporadic)

**Comment by flx42** [comment]
Note that the `docker volume create` might fail for the same reason as above (EBS).
So if the command fail, it shouldn't be fatal for your instance launch.

**Comment by 3XX0** [comment]
Closing, there is no more plugin in 2.0/master
