### ISSUE TITLE
Running an Arch linux container with nvidia-docker

### ISSUE THREAD

**Issue by Teyras** [NVIDIA/nvidia-docker#525]
I'm trying to run a container based on https://hub.docker.com/r/pritunl/archlinux/ with nvidia-docker. However, Arch linux installs nvidia driver libraries directly into /usr/lib, so I can't just mount the volume provided by nvidia-docker there - that would hide all the other libraries in there. Is there any other way to make this work?

**Comment by 3XX0** [comment]
Try nvidia-docker [2.0](https://github.com/NVIDIA/nvidia-docker/tree/2.0), it should work.

**Comment by elbaro** [comment]
@Teyras Did 2.0 work for you?

I am also trying to run `archimg/base-devel` and `nvidia-smi` prints `Failed to initialize NVML: Unknown Error`.

The host is ubuntu and another container based on ubuntu works well.

**Comment by Teyras** [comment]
I haven't managed to test it properly, but it seems like it works. I might be able to give you more thorough information in something like three weeks.
