### ISSUE TITLE
error in the first step

### ISSUE THREAD

**Issue by alizeshana** [NVIDIA/nvidia-docker#527]
Errors were encountered while processing:
 /tmp/nvidia-docker_1.0.1-1_amd64.deb

**Comment by flx42** [comment]
Not enough information here.
What's your distribution, Ubuntu? Debian? Which version?

**Comment by alizeshana** [comment]
Sorry for the vague comment. 
The docker file was not not properly downloaded. 
Downloaded it again and it works fine now. 

Thanks for your concern.  :)
