### ISSUE TITLE
Issue installing Cuda9 on fedora 25 docker

### ISSUE THREAD

**Issue by YannickBlais** [NVIDIA/nvidia-docker#528]
Hi,
I'm having problems launching `nvidia-smi` inside a Fedora25 container after Cuda9 is installed (it worked before). The native OS is Ubuntu16.04.

- In my Fedora25 Dockerfile, I first install NVidia graphic drivers 384.90 (Do I need to do this anyway? Cuda9 installer seems to replace it with 384.81) =>`nvidia-smi`works fine

- Then I install Cuda9 from [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Fedora&target_version=25&target_type=rpmlocal)

- `nvidia-smi` returns:
`Failed to initialize NVML: Driver/library version mismatch`

- May not be related but when I launch tensorflow's Session() on top of this, I get these error messages (among other info/warnings):
`E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE`
`E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 384.90.0 does not match DSO version 384.81.0 -- cannot find working devices in this configuration`

If I install graphic drivers, Cuda, CuDNN, tensorflow the same way natively on a Fedora25 system, everything work fine.

**Comment by flx42** [comment]
Do not install the drivers in the Dockerfile, otherwise the image will not be portable, it will be tied to the exact driver version you used.
`nvidia-docker` solves exactly this problem by mounting the driver files from the host.
