### ISSUE TITLE
nvidia-xconfig inside of the container

### ISSUE THREAD

**Issue by Brm-Bremen** [NVIDIA/nvidia-docker#529]
Hey everyone,

i need the tool nvidia-xconfig inside of my container, but it is not there by default. Searching in the Internet, it seems a installation of the newest nvidia-driver should do the trick but that does not seem to be a good idea regarding nvidia-docker. I have installed the neweset driver on the host-system. 

How can i get the tool in there, or would it be a good idea to create the xorg.conf on the host-system and then copy it into the container?

Best Regards
Joscha Knobloch

**Comment by 3XX0** [comment]
GLX is unsupported, and there is no plan to support it atm

**Comment by MadcowD** [comment]
@3XX0 Is there anyway the community could work towards supporting it? I'd love to contribute here.

**Comment by Suhail** [comment]
+1 - what can we do to help support this?
