### ISSUE TITLE
cuDNN not loaded when using tensorflow with the runtime image

### ISSUE THREAD

**Issue by tboquet** [NVIDIA/nvidia-docker#53]
Hi, thank you for this great tool! I have been using the `devel` images without major problems in containers along with Theano/Tensorflow but the runtime images seem to miss `libcudnn.so`.

I searched in `/usr/local/nvidia` but I was not able to find it. Is it missing, located somewhere else or not included?

**Comment by flx42** [comment]
It's at the standard location this time, unlike CUDA. Yes, it's slightly confusing :)
```
$ docker run -ti nvidia/cuda:7.5-cudnn4-runtime
root@346bd95e208d:/# ldconfig -p | grep cudnn
        libcudnn.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so.4
```

**Comment by tboquet** [comment]
Ok thanks!
