### ISSUE TITLE
List keras as Third-Party images

### ISSUE THREAD

**Issue by gmiretti** [NVIDIA/nvidia-docker#530]
Keras is a popular deep learning framework, and it has Dockerfile to build your own nvidia-docker images

As I can make a pull request for the wiki, I did it on a forked repository 
https://github.com/gmiretti/nvidia-docker-wiki/commit/3defa07376532e04807f5100b2cef92a41e987da

**Comment by flx42** [comment]
Mmm, not only Keras, I'm a bit behind for this list. I'm also missing pytorch and Caffe2, at least.

**Comment by flx42** [comment]
Fixed, thanks!

**Comment by gmiretti** [comment]
Thanks to you, keep up the good work :)
