### ISSUE TITLE
libnvcuvid.so.1 depends on libGL.so.1

### ISSUE THREAD

**Issue by vdiez** [NVIDIA/nvidia-docker#531]
I’m trying to get a working CUDA docker with ffmpeg compiled with hardware acceleration support. I always get the same error as with my build when I use ffmpeg with this command:

ffmpeg -hwaccel cuvid -c:v h264_cuvid -i file.mxf -vf scale_npp=1280:720 -c:v h264_nvenc file2.mxf

This is the error I’m getting:

Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x3a46360] Failed loading nvcuvid.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (pcm_s24le (native) -> pcm_s16le (native))
Error while opening decoder for input stream #0:0 : Unknown error occurred

If instead of using the nvidia CUDA images I build the docker from Ubuntu, adding cuda manually, and then compiling ffmpeg with cuda support, I also get the same problem. 

If I install the CUDA driver in the docker (in addition to the Toolkit) it works, but I don’t know if that’s the expected configuration.

Thanks

**Comment by 3XX0** [comment]
`libnvcuvid.so.1` should be in the container at runtime.
Are you using 1.0 or 2.0? 2.0 will work better because the ldcache is set properly.
You might want to debug with the environment variable `LD_DEBUG=all`

**Comment by vdiez** [comment]
I'm using 2.0. That file is not in the nvidia docker image (only in the host OS where the driver is present), but if I install the driver in the docker then it works (file is in path /usr/lib/nvidia-384/libnvcuvid.so.1). Then if I understand correctly the driver must be installed in the container as well in order to work?

**Comment by flx42** [comment]
No, please don't install the driver in\side the container :). The image won't be portable to other machines.

With 2.0, we now use environment variables to list the driver libraries that must be mounted inside the container at runtime:
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile#L30-33

In your case, you will need the following:
```
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility
```

Also note that starting from CUDA 9.0, we have a new tag: `nvidia/cuda:9.0-base`. It will setup our repositories and set the environment variables (but you will be missing the `video` for ffmpeg). It avoid having a base image with ALL the CUdA libraries.

**Comment by vdiez** [comment]
Thanks for the hints! Did some improvements: I started a new container with the NVIDIA_DRIVER_CAPABILITIES as suggested:

docker run -it --runtime=nvidia -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,video nvidia/cuda bash

Then I compile ffmpeg with cuda support:

`git clone https://github.com/FFmpeg/FFmpeg /root/ffmpeg && \
  cd /root/ffmpeg && ./configure \
  --enable-nonfree --disable-shared \
  --enable-nvenc --enable-cuda \
  --enable-cuvid --enable-libnpp \
  --extra-cflags=-I/usr/local/cuda/include \
  --extra-cflags=-I/usr/local/include \
  --extra-ldflags=-L/usr/local/cuda/lib64 && \
  make -j8 && \
  make install -j8`

But still when I run a transcode it fails with:

`Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x30a9a80] Failed loading nvcuvid.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc))
  Stream #0:2 -> #0:1 (aac (native) -> aac (native))
Error while opening decoder for input stream #0:0 : Unknown error occurred`

The difference that ENV variable made is that now I can see the file under `/usr/lib/x86_64-linux-gnu/libnvcuvid.so`, but the value of LD_LIBRARY_PATH is `/usr/local/nvidia/lib:/usr/local/nvidia/lib64`, which BTW do not exist in the container. I tried `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu`, but still ffmpeg fails to load the library.

Any idea on what I'm missing?

**Comment by 3XX0** [comment]
`LD_LIBRARY_PATH` doesn't matter, the ldcache should be configured properly.
Can you check the output of `ldconfig -p | grep libnvcuvid.so` inside and outside the container. Note that you want the library soname, not the symlink (i.e. libnvcuvid.so.**1**)

**Comment by vdiez** [comment]
In the container:

`root@0c22f6786b7b:/# ldconfig -p | grep libnvcuvid.so  
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1`

In the host:

`ubuntu@ip-XXXX:~$ ldconfig -p | grep libnvcuvid.so  
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvcuvid.so.1  
        libnvcuvid.so.1 (libc6) => /usr/lib32/nvidia-384/libnvcuvid.so.1  
        libnvcuvid.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvcuvid.so  
        libnvcuvid.so (libc6) => /usr/lib32/nvidia-384/libnvcuvid.so`

I did `ln -s libnvcuvid.so.1 libnvcuvid.so` in the container, so now it returns as well:

`root@0c22f6786b7b:~# ldconfig -p | grep libnvcuvid.so  
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1  
        libnvcuvid.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so`

That change did not help with ffmpeg though

**Comment by 3XX0** [comment]
Looks like a driver issue, can you do `echo | gcc -shared -o /usr/lib/x86_64-linux-gnu/libGL.so.1 -Wl,-soname=libGL.so.1 -x c -` inside the container see if it fixes the problem?

**Comment by vdiez** [comment]
Excellent, that made it! Can you briefly explain that command line for non-C devs like me?

Thanks for the help!

**Comment by 3XX0** [comment]
This is a hack to make `ld.so(8)` happy because it turns out `libnvcuvid.so` has a hard dependency on OpenGL now... This creates a dummy `libGL.so` library where the linker can find it. Note this will work as long as ffmpeg doesn't use symbols from nvcuvid that call into `libGL.so.1` :)

I will keep this bug open until the driver is fixed.

**Comment by vdiez** [comment]
Understood, thanks again! :)

**Comment by flx42** [comment]
ETA for driver fix is probably ~February 2018

**Comment by flx42** [comment]
It's fixed!
With 384.81:
```
$ objdump -p /usr/lib/nvidia-384/libnvcuvid.so.1 | grep NEEDED
  NEEDED               libGL.so.1
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  NEEDED               libdl.so.
```

Withj 384.111:
```
$ objdump -p /usr/lib/nvidia-384/libnvcuvid.so.1 | grep NEEDED
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  NEEDED               libdl.so.2
```

**Comment by vdiez** [comment]
Just tested and ffmpeg working fine now without any hack. Thanks again!

**Comment by ikaven1024** [comment]
my enviroment:
```
# nvidia-container-cli info
NVRM version:   384.125
CUDA version:   9.0
```

```
# docker info
Containers: 116
 Running: 60
 Paused: 0
 Stopped: 56
Images: 61
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.6GiB
Name: master1
ID: DFOM:HECH:OOCP:N5Q2:ZSV7:HHN6:GIX4:MAFI:KFHQ:C5VZ:WM6X:5G6V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 docker.hikcloud:12306
 docker.hikvision.com.cn
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

in the host
```
# ldconfig -p | grep libnvcuvid
	libnvcuvid.so.1 (libc6,x86-64) => /lib64/libnvcuvid.so.1
	libnvcuvid.so.1 (libc6) => /lib/libnvcuvid.so.1
	libnvcuvid.so (libc6,x86-64) => /lib64/libnvcuvid.so
	libnvcuvid.so (libc6) => /lib/libnvcuvid.so
```

but in container, there is no libnvcuvid.so
```
# docker run --rm -ti --runtime=nvidia -e NVIDIA_DRIVER_CAPABILITIES=video,compute,utility nvidia/cuda:9.0-base ldconfig -p | grep libnvcuvid
	libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
```

need your help, thanks

**Comment by carlwain74** [comment]
I know this issue is closed, but can someone explain to me how defining the environment **NVIDIA_DRIVER_CAPABILITIES=video,compute,utility** makes the video libraries available in the running container. I examined the Dockerfile and a little baffled.

**Comment by ieth0** [comment]
@carlwain74 you should check runtime instead. https://github.com/NVIDIA/nvidia-container-runtime
