### ISSUE TITLE
Option to set the default runtime to nvidia in packages

### ISSUE THREAD

**Issue by rongou** [NVIDIA/nvidia-docker#532]
I know this may be a little controversial, but as a user it'd be more convenient if `apt install nvidia-docker2` also sets the docker `default-runtime` to `nvidia`. If this can't be done automatically, maybe at least give the user an option to select it?

**Comment by flx42** [comment]
I think you want this in the context of the Kubernetes device plugin that we publish, but for the general user base, I think what we do today is the best approach. Even if I'm confident in how we manage our fork, swapping the default runtime always carries a risk and I don't want to be responsible for breaking a user's machine.
 
Advanced users should install `nvidia-container-runtime` and setup the runtime manually. It's true that we also need to continue improving our documentation, we have multiple repos, multiple options to enable our runtime, it can be a bit overwhelming at first.

For AWS users, our goal is also to publish a beta AMI that would incorporate 2.0 as the default runtime, stay tuned.

**Comment by 3XX0** [comment]
Maybe we could add a `dpkg-preconfigure` option for our debs but AFAIK this isn't possible for the rpms

**Comment by RenaudWasTaken** [comment]
Closing as we we'll tackle this process through containers in kube
