### ISSUE TITLE
Error response from daemon: Get https://nvcr.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by dholdaway** [NVIDIA/nvidia-docker#535]
I am getting this error this morning when trying to log into the NGC Registry

Error response from daemon: Get https://nvcr.io/v2/: net/http: request cancelled (Client.Timeout exceeded while awaiting headers)

it was working ok yesterday, I am able to pull other docker images.

**Comment by 3XX0** [comment]
For any NGC related issue, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/).
