### ISSUE TITLE
Error running against RHEL-provided docker

### ISSUE THREAD

**Issue by wedgef5** [NVIDIA/nvidia-docker#537]
I am getting an error trying to launch a container with the nvidia runtime using the RHEL 7 docker-latest package.  I have to use the RHEL-provided packages (not the Docker-provided ones) per my organization's rules.  Due to this, I was unable to simply 'yum install nvidia-docker2', as that package has a dependency on docker-ce (Docker's package).  I followed the instructions on the nvidia-container-runtime page to manually install that package and configure dockerd to use it (i.e. adding the --add-runtime switch).  After restarting dockerd, 'docker info' shows the nvidia runtime correctly.

When I try to launch any container with the nvidia runtime, I get the following error...

/usr/bin/docker-latest: Error response from daemon: oci runtime error: flag provided but not defined: -console.

Output from 'docker version':
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      50fad48
 Built:           Tue Sep 26 15:20:24 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      50fad48
 Built:           Tue Sep 26 15:20:24 2017
 OS/Arch:         linux/amd64
 Experimental:    false

I'm not sure if I'm missing something or if RHEL's docker just doesn't want to play nicely with the nvidia runtime.

Any suggestions are appreciated!

**Comment by flx42** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version
Your version of `nvidia-container-runtime` doesn't match your version of docker.

But, we don't have a `1.13.1` package for CentOS/RHEL. I can publish it. 
What's the output of `yum list installed docker` on your machine?

**Comment by eliorc** [comment]
Sorry for the late comment

The problem seem to be the same as discussed [here](https://github.com/docker/for-linux/issues/164).

One of the comments there has commands that redirect the yum repos to Fedora 26's repos, which is what I eventually did and I was able to install nvidia-docker2.

This is quite a bad workaround, I think that the 27 link should redirect to 26's as long as there is not a dedicated page to it. (https://download.docker.com/linux/fedora/27 should redirect to https://download.docker.com/linux/fedora/26)

**Comment by wedgef5** [comment]
From RHEL there is "docker" and "docker-latest".  I have docker-latest installed.  Here is the output of `yum list installed docker-latest`...
docker-latest.x86_64                                       1.13.1-26.git1faa135.el7                                       @rhel-7-server-extras-rpms

I also ran `yum info docker` to see what that provides...
Available Packages
Name        : docker
Arch        : x86_64
Epoch       : 2
Version     : 1.12.6
Release     : 61.git85d7426.el7
Size        : 15 M
Repo        : rhel-7-server-extras-rpms/x86_64
Summary     : Automates deployment of containerized applications
URL         : https://github.com/docker/docker
License     : ASL 2.0
Description : Docker is an open-source engine that automates the deployment of any
            : application as a lightweight, portable, self-sufficient container that will
            : run virtually anywhere.
            : 
            : Docker containers can encapsulate any payload, and will run consistently on
            : and between virtually any server. The same container that a developer builds
            : and tests on a laptop will run at scale, in production*, on VMs, bare-metal
            : servers, OpenStack clusters, public instances, or combinations of the above.

**Comment by flx42** [comment]
Yeah, on RHEL systems the situation is complicated. We have to pin the dependency on Docker, and we can't have a dependency like `docker | docker-ce | docker-latest` like we have with deb packages.
For this situation, installing the right version of `nvidia-container-runtime` is probably easier.
Having said that, I'll publish a new package for `1.13` today.

**Comment by wedgef5** [comment]
Is docker 17.x the only version(s) that are compatible with nvidia-container-runtime?  I tried dropping back to RHEL's "stable" docker package (which says 1.12.6), and I get the same error.

**Comment by flx42** [comment]
No, `1.12.6` will work, but make sure you install the right version of `nvidia-container-runtime`:
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version

**Comment by wedgef5** [comment]
I think I finally get it.  You only had to give me the FAQ link twice before I finally understood.  _facepalm_

Is the normal, expected output from `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi` a text-based message showing what GPU was found, the fan speed, GPU temp., etc.?

**Comment by flx42** [comment]
> I think I finally get it. You only had to give me the FAQ link twice before I finally understood.

That's fine, with the new version the packaging scheme is a little more challenging, we need to improve our documentation (or our packaging, but I'm not sure we have many other options).

> Is the normal, expected output from docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi a text-based message showing what GPU was found, the fan speed, GPU temp., etc.?

Yes that's the normal output of `nvidia-smi`.

**Comment by wedgef5** [comment]
Thank you for the help.  I consider the issue closed.
