### ISSUE TITLE
Add support for Docker 1.13.1

### ISSUE THREAD

**Issue by eliorc** [NVIDIA/nvidia-docker#538]
I'm on Fedora 27, trying to install nvidia-docker2.

I have docker installed, and able to use it normally.
I'm using `dnf`, so to add the repo I used `sudo dnf config-manager --add-repo https://nvidia.github.io/nvidia-docker/centos7/x86_64/nvidia-docker.repo` and verified that it can find the `nvidia-docker2` package by using `dnf info nvidia-docker2` and indeed it found it.

Now when I run `sudo dnf install nvidia-docker2`, I get the following output:

> Error: 
>  Problem: conflicting requests
>   - nothing provides docker = 2:1.12.6 needed by nvidia-docker2-2.0.0-1.docker1.12.6.noarch
>   - nothing provides docker-ce = 17.03.2.ce needed by nvidia-docker2-2.0.0-1.docker17.03.2.ce.noarch
>   - nothing provides docker-ce = 17.06.1.ce needed by nvidia-docker2-2.0.0-1.docker17.06.1.ce.noarch
>   - nothing provides docker-ce = 17.06.2.ce needed by nvidia-docker2-2.0.0-1.docker17.06.2.ce.noarch
>   - nothing provides docker-ce = 17.09.0.ce needed by nvidia-docker2-2.0.0-1.docker17.09.0.ce.noarch
>   - nothing provides docker = 2:1.12.6 needed by nvidia-docker2-2.0.1-1.docker1.12.6.noarch
>   - nothing provides docker-ce = 17.03.2.ce needed by nvidia-docker2-2.0.1-1.docker17.03.2.ce.noarch
>   - nothing provides docker-ce = 17.06.2.ce needed by nvidia-docker2-2.0.1-1.docker17.06.2.ce.noarch
>   - nothing provides docker-ce = 17.09.0.ce needed by nvidia-docker2-2.0.1-1.docker17.09.0.ce.noarch

Now as I said, running `docker` commands works flawlessly, so I can't really get what's going on here.

My `docker` version is 1.13.1

**Comment by flx42** [comment]
Seems to be the same as #537, we don't provide a rpm package for `1.13.1`. When I added support for RHEL's `docker` package, I only added `1.12.6`.
Can you give me the exact version of the `docker` package you have?

**Comment by mjmg** [comment]
Fedora 27 is too new and nvidia-docker2 was released at almost the same time so it won't probably work immediately.

You may have to uninstall the docker that came with fedora 27 and use the stable version of docker-ce for fedora 26 provided by docker itself for a fedora 27 system with nvidia-docker2 until the repos catch up to the new builds.
https://download.docker.com/linux/fedora/26/x86_64/stable/Packages/docker-ce-17.09.0.ce-1.fc26.x86_64.rpm
