### ISSUE TITLE
flag provided but not defined: --build-arg

### ISSUE THREAD

**Issue by zcyang** [NVIDIA/nvidia-docker#54]
```
$ make install
make -C /home/zichaoy/nvidia-docker/tools install
make[1]: Entering directory `/home/zichaoy/nvidia-docker/tools'
flag provided but not defined: --build-arg
See 'docker build --help'.
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/zichaoy/nvidia-docker/tools'
make: *** [install] Error 2
```
I am using 
```
$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final
```
```
$ docker --version
Docker version 1.7.1, build 786b29d
```

**Comment by flx42** [comment]
Ah, `--build-arg` was added in Docker 1.9.
And unfortunately `CentOS 6.7` is not officially supported anymore by [Docker](https://docs.docker.com/engine/installation/linux/centos/).

So I'm not sure you will be able to update to a newer version of Docker.

**Comment by zcyang** [comment]
yeah, ```Docker 1.9``` requires at least ```Centos 7```...

**Comment by 3XX0** [comment]
Docker itself requires Centos 7 (see [here](https://github.com/docker/docker/issues/14365).
If you still want to use it on Centos 6, you can always rely on the [binaries we released](https://github.com/NVIDIA/nvidia-docker/releases/tag/v1.0.0-beta)
