### ISSUE TITLE
nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected

### ISSUE THREAD

**Issue by TharinduDR** [NVIDIA/nvidia-docker#548]
Hi,
I am using nvidia/cuda:8.0-devel image and tried to run it. But I get the following error. 

`sudaraka@RnDCompute:~$ docker run -it --runtime=nvidia nvidia/cuda:8.0-devel
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=8.0 --pid=11481 /var/lib/docker/overlay2/aa36f1b4a0c8fa0b0de91f840d861380fb59170c8aa0ceabbf7f0cc7674250d8/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\""`

I have cuda 8.0 installed. 
`sudaraka@RnDCompute:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan_23_12:24:11_CST_2017
Cuda compilation tools, release 8.0, V8.0.62`

As well as the driver. 
`sudaraka@RnDCompute:~$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.98  Thu Oct 26 15:16:01 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) `

My docker version is 17.09.0-ce
`sudaraka@RnDCompute:~$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.98  Thu Oct 26 15:16:01 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) `

What can be the problem for the error I am getting as no cuda-capable device is detected?

Thank You

**Comment by 3XX0** [comment]
Is CUDA working on your host? It looks like a driver issue we fixed but that hasn't been backported to `384.98`. Can you try to change drivers see if it changes anything.

**Comment by kylemcdonald** [comment]
i was also seeing this issue when i ran `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`

but i got a hint. when running docker, there was an error:

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/version: dial unix /var/run/docker.sock: connect: permission denied
```

when i saw this i tried adding my user to the docker group:

```
$ sudo gpasswd -a $USER docker
```

then i logged out and logged back in, and now it works.

**Comment by 3XX0** [comment]
@TharinduDR Did you have a chance to test CUDA on your host?

**Comment by TharinduDR** [comment]
@3XX0 I am sorry for the late reply, actually I think there is a problem in CUDA in my machine. because even though cat /proc/driver/nvidia/version gives an output nvidia-smi command says that no devices were found. So there might be a problem in my CUDA. I am trying to solve it.

**Comment by flx42** [comment]
ping @TharinduDR

**Comment by RomanSteinberg** [comment]
@TharinduDR What device do you have? Is it cuda-capable?

**Comment by TharinduDR** [comment]
It was a problem in my server, After reinstalling Ubuntu in the server it was working fine.
