### ISSUE TITLE
Failed to start nvidia-docker.service: Unit nvidia-docker.service not found.

### ISSUE THREAD

**Issue by janelu9** [NVIDIA/nvidia-docker#550]
I  have installed nvidia-docker2 by commond " apt-get install -y nvidia-docker2"
but when I run: systemctl start nvidia-docker 
it prints: Failed to start nvidia-docker.service: Unit nvidia-docker.service not found.

it also throws an error:"OSError: libnvidia-fatbinaryloader.so.384.90: cannot open shared object file: No such file or directory“ ,when I run "import mxnet"  in the  container created by nvidia-docker
--

**Comment by 3XX0** [comment]
nvidia-docker2 doesn't use a daemon, see [here](https://github.com/NVIDIA/nvidia-docker/wiki/About-version-2.0).
Please follow the issue template when reporting an issue, especially the last 4 bullet points.
