### ISSUE TITLE
can't install nvidia-docker 2.0 on ubuntu14.04

### ISSUE THREAD

**Issue by niewuya** [NVIDIA/nvidia-docker#551]
Hello. I have installed the docker on ubuntu14.04, but it got error " nvidia-docker2 : Depends: docker-ce (= 17.09.0~ce-0~ubuntu) but 17.11.0~ce-0~ubuntu is to be installed or docker-ee (= 17.09.0~ee-0~ubuntu) but it is not installable" when install nvidia-docker 2.0.
 I use the command "curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker.list" to add the repository, and I can't find the repository for ubuntu 14.04. How can I install nvidia-docker on Ubuntu 14.04. By the way, can I run multi tasks on the same GPU at the same time by using nvidia-docker? Thanks.

**Comment by 3XX0** [comment]
Using the 16.04 repository should be fine.
Regarding your Docker installation see [here](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0)#older-versions-of-docker) and [there](https://github.com/NVIDIA/nvidia-docker/wiki#setting-up). Edge releases are not supported so you probably need to pin the package version corresponding to your Docker install.

**Comment by niewuya** [comment]
Thanks for your reply.May I install nvidia-docker 1.0  on the 14.04? nvidia-docker 2.0 needs the cuda 9.0 . But the version of cuda in my system is 8.0.

**Comment by niewuya** [comment]
@3XX0 Thanks for your reply.May I install nvidia-docker 1.0 on the 14.04? nvidia-docker 2.0 needs the cuda 9.0 . But the version of cuda in my system is 8.0.

**Comment by 3XX0** [comment]
Yes you can but nvidia-docker 2.0 doesn't require CUDA 9.0. Only the nvidia driver needs to be installed (see [prerequisites](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0)#prerequisites))

**Comment by schelian** [comment]
How do I pin docker2 for Docker 17.05.0-ce?  The following lines did not work:

sudo apt-get install -y nvidia-docker2=2.0.1+docker17.05.0-ce
sudo apt-get install -y nvidia-docker2=2.0.1+docker17.05.0
sudo apt-get install -y nvidia-docker2=2.0.1+docker17.05
sudo apt-get install -y nvidia-docker2=2.0.1+docker17

The output of "sudo apt-cache search nvidia-docker2" was not helpful so maybe there's a list somewhere?

**Comment by 3XX0** [comment]
@schelian https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0)#older-versions-of-docker

**Comment by schelian** [comment]
Thanks @3XX0.  Never heard of the "madison" option for apt-cache.  Pretty unintuitive name but I guess [there's some history to it](https://unix.stackexchange.com/questions/276037/why-apt-madison/276040).
