### ISSUE TITLE
oci runtime error ,ldcache error : process /sbin/ldconfig failed with error code 1

### ISSUE THREAD

**Issue by codexie** [NVIDIA/nvidia-docker#552]
Hi,
     I have installed nvidia-docker2 ,cuda9.0 and nvidia-driver384.81,and the GPU is Tesla M40 . However,when I exec "docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi" , the  error occurs as follows :    
     Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: 
     running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real 
     --device=all --compute --utility --require=cuda>=9.0 --pid=9152 /data/docker/aufs/mnt/a5580b0483a1324f820c340aac1c491eb869899d3e868ec51bd99c2a66a18791] \\\\nvidia-container-cli:
     ldcache error : process /sbin/ldconfig failed with error code 1 \\\\n\\\"\"". 
     
     What can be the problem for the error and how to fix it ?
     Thank You

**Comment by flx42** [comment]
What's your OS distribution?

**Comment by codexie** [comment]
Thanks for reply. The os informations:  Linux version 3.10.106, (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) , CentOS Linux release 7.2 (Final) .

**Comment by 3XX0** [comment]
Please follow the issue template when filling an issue, especially the last 4 bullet points

**Comment by codexie** [comment]
Hi, 
  
  Also,when I set  nvidia-container-runtime :  debug = "/var/log/nvidia-container-runtime-hook.log" , 
 I find the error :
 /data/docker/aufs/mnt/75d291cf12ebe2595e0084eb46dbcdf789561a7aba1d9202fdd76e26f0642904
E1204 00:48:44.418920 1 nvc_ldcache.c:356] could not start /sbin/ldconfig: syscall limiting failed
I1204 00:48:44.453790 37876 nvc.c:286] shutting down library context
I1204 00:48:44.458257 37883 driver.c:169] terminating driver service
I1204 00:48:44.469263 37876 driver.c:208] driver service terminated successfully
 
and I find the  nvc_ldcache.c source file ,it's error may comes from the follow code:

   if ((ctx = seccomp_init(SCMP_ACT_ERRNO(EPERM))) == NULL)
                goto fail;
        for (size_t i = 0; i < nitems(syscalls); ++i) {
                if (seccomp_rule_add(ctx, SCMP_ACT_ALLOW, syscalls[i], 0) < 0)
                        goto fail;
        }
        if (seccomp_load(ctx) < 0)
                goto fail;
        rv = 0;
     fail:
        if (rv < 0)
             error_setx(err, "syscall limiting failed");
        seccomp_release(ctx);
        return (rv);

 Thanks for your help.

 Now,follow your tips. The host informations are as follows:

  [root@TENCENT64 /data]# uname -a
  Linux TENCENT64.site 3.10.106-1-tlinux2-0044 #1 SMP Mon Jul 17 15:20:12 CST 2017 x86_64 x86_64 
 x86_64 GNU/Linux
[root@TENCENT64 /var/log]# nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M40 24GB      On   | 0000:04:00.0     Off |                    0 |
| N/A   31C    P8    18W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M40 24GB      On   | 0000:05:00.0     Off |                    0 |
| N/A   31C    P8    17W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M40 24GB      On   | 0000:08:00.0     Off |                    0 |
| N/A   28C    P8    17W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M40 24GB      On   | 0000:09:00.0     Off |                    0 |
| N/A   32C    P8    17W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla M40 24GB      On   | 0000:85:00.0     Off |                    0 |
| N/A   30C    P8    16W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla M40 24GB      On   | 0000:86:00.0     Off |                    0 |
| N/A   29C    P8    17W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla M40 24GB      On   | 0000:89:00.0     Off |                    0 |
| N/A   29C    P8    18W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla M40 24GB      On   | 0000:8A:00.0     Off |                    0 |
| N/A   31C    P8    16W / 250W |      0MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


[root@TENCENT64 /boot]# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

[root@TENCENT64 /boot]# rpm -qa '*nvidia*'
nvidia-container-runtime-1.1.0-1.docker17.09.0.x86_64
libnvidia-container1-1.0.0-0.1.alpha.2.x86_64
nvidia-docker2-2.0.1-1.docker17.09.0.ce.noarch
libnvidia-container-tools-1.0.0-0.1.alpha.2.x86_64

[root@TENCENT64 /boot]# nvidia-container-cli -V
version: 1.0.0
build date: 2017-10-31T00:28+0000
build revision: ec15c7233bd2de821ad5127cb0de6b52d9d2083c
build compiler: gcc 4.8.5 20150623 (Red Hat 4.8.5-16)
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

**Comment by 3XX0** [comment]
Are you using a custom kernel/distribution?
Your output is weird, it shows `/sbin/ldconfig.real` and AUFS which suggest you are on an Ubuntu distribution but also Centos7/RHEL7.

What's the output of:
`cat /boot/config-$(uname -r) | grep -i seccomp`

**Comment by flx42** [comment]
ping @codexie

**Comment by codexie** [comment]
yes ,our company use custom kernel based linux kernel 3.10, it says  doesn't support seccomp  mode temporarily.Hope the problem is this,and the new kernel will support it soon ,  then I try it again.

**Comment by 3XX0** [comment]
Any update @codexie ?

**Comment by codexie** [comment]
Yes,  when the kernel updated to support  seccomp mode ,it works done.
Thanks a lot all of you
Best Wishes.
@3XX0 @flx42
