### ISSUE TITLE
failed to start NVIDIA docker plugin

### ISSUE THREAD

**Issue by hzfeng87** [NVIDIA/nvidia-docker#557]
---

### 1. Issue or feature description
I installed nvidia driver version 384.66 in directory /var/lib/nvidia-docker/volumes/nvidia_driver/384/ and didn't install driver 375 while installing cuda-8.0.61_375.26 . and installed nvidia-docker with rpm "nvidia-docker-1.0.1-1.x86_64.rpm".
nvidia-smi displays well.
Then, I configured the env "export LD_LIBRARY_PATH=/usr/lib64:/usr/local/cuda-8.0/lib64:/usr/local/lib/:/var/lib/nvidia-docker/volumes/nvidia_driver/384/lib:$LD_LIBRARY_PATH" .
OK , Now I want to start nvidia-docker, but the nvidia-docker-plugin started failed, the error was like this:
![image](https://user-images.githubusercontent.com/27279270/33543566-774e1690-d912-11e7-8032-112d095b50b6.png)
### 2. Steps to reproduce the issue
I checked the Q&A , found a similiar question. He resolved his problem with adding libnvidia-ml.so to ldconfig config and running loadconfig.

I used the same method but I still got the same error.

Is there the dependency between nvidia driver version and cuda toolkit  version? How can I resolve this problem?
Thanks

**Comment by flx42** [comment]
Can you run `nvidia-smi`?

**Comment by hzfeng87** [comment]
@flx42 yes， nvidia-smi works well.

**Comment by flx42** [comment]
You should try with nvidia-docker 2.0, it should work much better.

**Comment by hzfeng87** [comment]
@flx42 thanks ,  I reply late. I have resolved the problem by upgrading the nvidia driver to 384.81
