### ISSUE TITLE
why connot i install nvidia-docker-plugin?

### ISSUE THREAD

**Issue by janelu9** [NVIDIA/nvidia-docker#558]
it looks that it stoped after printing 'serving remote API as localhost:3476'

**Comment by janelu9** [comment]
ERROR : link /usr/lib/nvidia-cuda-mps-control /var/lib/nvidia-docker.........:invalid cross-device link

**Comment by flx42** [comment]
this is a limitation of nvidia-docker v1:
https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#known-limitations
You should use nvidia-docker v2 (look at the current README), if you can
