### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by simonm3** [NVIDIA/nvidia-docker#560]
I have cuda8 installed on my host and can import tensorflow without error. However when I try to import it from a jupyter notebook in the docker container I get the above message. My run command is:

docker run --runtime=nvidia --name registr -v /v1:/v1 -p 8888:8888 -p 8082:8082 simonm3/registr jupyter notebook

**Comment by flx42** [comment]
What's your Dockerfile?

**Comment by simonm3** [comment]
FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y &&\
apt-get install -y --no-install-recommends apt-utils &&\
apt-get install -y build-essential &&\
    apt-get install -y wget bzip2

# anaconda
ENV CONDA=/anaconda3
ENV PATH=$CONDA/bin:$PATH
RUN wget -O anaconda.sh "
https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" && \
/bin/bash anaconda.sh -b -p $CONDA && \
    rm -rf anaconda.sh

# OCR
RUN apt-get install -y libtesseract-dev libleptonica-dev tesseract-ocr-eng
tesseract-ocr tesseract-ocr-ell && \
apt-get install -y python-wand

# pip
RUN pip install keras Pillow PyYAML jupyter &&\
pip install numpy pandas scikit-learn tqdm tensorflow tensorflow-gpu
requests luigi &&\
pip install wand pyocr "biopython>=1.7"  &&\
pip install logcon nbextensions easyimap && \
pip install bcolz &&\
rm -rf /root/.cache/pip

# source code
COPY config /root
COPY worker /root/worker
ENV PYTHONPATH=$PYTHONPATH:/root/worker
WORKDIR /root
CMD ["python", "/root/worker/pipeline.py"]

**Comment by flx42** [comment]
Well yeah, you didn't install cuBLAS :) Please use our base images from DockerHub.
