### ISSUE TITLE
REST API for Version 2

### ISSUE THREAD

**Issue by juharris** [NVIDIA/nvidia-docker#563]
Looks like the nvidia-docker-plugin is deprecated since it's for v1.  Are there any plans to support the [REST API](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#rest-api) for v2?

**Comment by flx42** [comment]
Yes, as a separate GitHub project that we will release soon.
@guptaNswati is working on extracting the NVML/CUDA wrappers and also implementing golang wrappers for [DCGM](http://www.nvidia.com/object/data-center-gpu-manager.html).

**Comment by juharris** [comment]
Awesome thanks! Maybe DCGM is all I need then.

**Comment by xuchenCN** [comment]
Hi  @flx42 What's up about REST API for version 2.0 ?

**Comment by flx42** [comment]
@xuchenCN a few weeks away, I hope :)

**Comment by bkgoksel** [comment]
Any updates on this @flx42 ?

**Comment by guptaNswati** [comment]
@bkgoksel you can find NVML and DCGM go bindings here https://github.com/NVIDIA/gpu-monitoring-tools

**Comment by xuchenCN** [comment]
Hi @guptaNswati I'm trying to build gpu-monitoring-tools but I can't find some header file in project
```
# github.com/NVIDIA/gpu-monitoring-tools/bindings/go/dcgm
../../../dcgm/admin.go:8:10: fatal error: 'dcgm_agent.h' file not found

#include "dcgm_agent.h"
         ^
1 error generated.
```

**Comment by guptaNswati** [comment]
Yeah we don't have DCGM headers in the repo, you would need to install DCGM first. Also open monitoring issues in its repo.

**Comment by lagidigu** [comment]
I'm a little confused, is it possible to use the REST API for nvidia-docker v2?
