### ISSUE TITLE
Is this right when I install the nvidia-docker on ppc64 with ubuntu?

### ISSUE THREAD

**Issue by leearmy** [NVIDIA/nvidia-docker#566]
### 1. Issue or feature description
I did build from source file of nvidia-docker with 'make'. and then I did 'make install'. But I don't know is this completed? What can I do next step?

### 2. Information
-.ubuntu 16.04
-.docker-ce version : 17.06.0~ce-0~ubuntu
-.cuda version : cuda 8.0 and cudnn 6.0.21
-.git clone https://github.com/NVIDIA/nvidia-docker.git  ==> nvidia-source code

test_svr@ubuntu:~/data/nvidia-docker$ sudo make
..................
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'nvidia-docker2' in '../nvidia-docker2_2.0.1+docker17.03.2-1_all.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../nvidia-docker2_2.0.1+docker17.03.2-1_ppc64el.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source -i --after-build nvidia-docker2-2.0.1+docker17.03.2
dpkg-buildpackage: info: binary-only upload (no source included)
test_svr@ubuntu:~/data/nvidia-docker$ sudo make install
make: *** No rule to make target 'install'.  Stop.
test_svr@ubuntu:~/data/nvidia-docker$

**Comment by flx42** [comment]
Look at the ppc64le xenial instructions here:
https://nvidia.github.io/nvidia-docker
Then `apt-get install -y nvidia-docker`.

**Comment by leearmy** [comment]
Thank you so much!!!!!!! "flx42"
