### ISSUE TITLE
Why not release executable deb file for version 2.0?

### ISSUE THREAD

**Issue by ljf1239848066** [NVIDIA/nvidia-docker#569]
Why not release executable deb file for version 2.0?

**Comment by flx42** [comment]
I don't understand the question, we have deb packages for ubuntu and debina today.

**Comment by flx42** [comment]
We have a deb repository, but it's not under the usual GitHub "Releases"

**Comment by ljf1239848066** [comment]
Could you please provide the download url?

**Comment by flx42** [comment]
Instructions are here:
https://github.com/NVIDIA/nvidia-docker#xenial-x86_64

If you want direct download links you can take a look at this example:
https://github.com/NVIDIA/nvidia-docker/issues/516#issuecomment-344417128

**Comment by ljf1239848066** [comment]
Because of network problems, nvidia-docker cannot be installed directly on the linux machine online, So I  firstly download it on windows, then transfer it to linux machine to install.

**Comment by flx42** [comment]
Ok, so, did I answer your question then?
By the way, if you want to browse our packages, look at this branch:
https://github.com/NVIDIA/nvidia-docker/tree/gh-pages

**Comment by ljf1239848066** [comment]
Of course, yes. Thank you very much.
