### ISSUE TITLE
Error: nvidia-docker volumn setup

### ISSUE THREAD

**Issue by cooloney** [NVIDIA/nvidia-docker#57]
$ sudo nvidia-docker volumn setup
nvidia-docker: symbol lookup error: nvidia-docker: undefined symbol: nvmlInit_v2

**Comment by flx42** [comment]
What's your NVIDIA driver version?
You can copy/paste the output of `nvidia-smi`.

**Comment by cooloney** [comment]
$ nvidia-smi
Thu Mar 17 17:34:10 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 4.304...   Driver Version: 304.131        |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name                     | Bus-Id        Disp.  | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap| Memory-Usage         | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  NVS 300                  | 0000:01:00.0     N/A |                  N/A |
| N/A   55C  N/A     N/A /  N/A |  90%  462MB /  511MB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

**Comment by flx42** [comment]
Wow, that's a very old GPU and driver version. I'm afraid we don't support it in nvidia-docker. You would need to purchase a newer GPU!

**Comment by cooloney** [comment]
Sorry to hear that. I will try to ask for a newer one. Can I try this nvidia-docker on our Jetson TX1 platform?

Thanks.
-Bryan

**Comment by flx42** [comment]
Unfortunately, no. Officially, Docker only supports the x86-64 architecture. Some people succeeded in making it work on other architectures, but it might be a long journey to get there :)
