### ISSUE TITLE
Does nvidia-docker2 support ubuntu14.04?

### ISSUE THREAD

**Issue by ljf1239848066** [NVIDIA/nvidia-docker#570]
Does nvidia-docker2 support ubuntu14.04?

**Comment by flx42** [comment]
We don't officially provide packages for it, but I know that someone has tried the xenial repo and it seemed to work.

**Comment by ljf1239848066** [comment]
May be you'd better update `installation prerequisites` in [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0)#Prerequisites)

**Comment by flx42** [comment]
Well, as I said, you can still try the 16.04 packages on 14.04.
