### ISSUE TITLE
Error: container_linux.go:265: starting container process caused "process_linux.go:368: 

### ISSUE THREAD

**Issue by Yong-Zhuang** [NVIDIA/nvidia-docker#572]
Hi,
I have installed nvidia-docker2 ,cuda8.0 and nvidia-driver381.22,and the GPU is GeForce GTX1080Ti . However,when I exec "docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi" , the error occurs as follows :
container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=14419 /data/docker/aufs/mnt/9624eec9e6363397b4aae56bbb6cb8e2d47aca498ce0115f614d1103c3722a47]\\\\nnvidia-container-cli: initialization error: driver error: RPC: timed out\\\\n\\\"\""
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=14419 /data/docker/aufs/mnt/9624eec9e6363397b4aae56bbb6cb8e2d47aca498ce0115f614d1103c3722a47]\\\\nnvidia-container-cli: initialization error: driver error: RPC: timed out\\\\n\\\"\"".

The os informations:
Linux xian 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

The nvidia-smi informations:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 0000:04:00.0     Off |                  N/A |
| 26%   46C    P2    59W / 250W |  10673MiB / 11172MiB |     11%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 0000:05:00.0     Off |                  N/A |
| 23%   27C    P8    16W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 0000:08:00.0     Off |                  N/A |
| 23%   27C    P8    16W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 0000:09:00.0     Off |                  N/A |
| 23%   29C    P8    16W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 0000:84:00.0     Off |                  N/A |
| 23%   28C    P8    16W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 0000:85:00.0     Off |                  N/A |
| 23%   26C    P8    16W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 0000:88:00.0     Off |                  N/A |
| 23%   24C    P8    17W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  On   | 0000:89:00.0     Off |                  N/A |
| 23%   26C    P8    15W / 250W |  10623MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     12202    C   python                                       10663MiB |
|    1     12202    C   python                                       10613MiB |
|    2     12202    C   python                                       10613MiB |
|    3     12202    C   python                                       10613MiB |
|    4     12202    C   python                                       10613MiB |
|    5     12202    C   python                                       10613MiB |
|    6     12202    C   python                                       10613MiB |
|    7     12202    C   python                                       10613MiB |
+-----------------------------------------------------------------------------+

The docker informations:
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

run "nvidia-container-cli -V" I got:
version: 1.0.0
build date: 2017-10-30T23:47+00:00
build revision: ec15c7233bd2de821ad5127cb0de6b52d9d2083c
build compiler: gcc-5 5.4.0 20160609
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

run "cat /boot/config-$(uname -r) | grep -i seccomp" I got:
CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
CONFIG_SECCOMP_FILTER=y
CONFIG_SECCOMP=y

 Could you please tell me what could be the problem and how to fix it?

 Thank You

**Comment by 3XX0** [comment]
Can you also provide the library logs: https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting#generating-debugging-logs

**Comment by Yong-Zhuang** [comment]
Hi @3XX0,

the logs are as follows:

-- WARNING, the following logs are for debugging purposes only --

I1213 22:59:16.808241 16347 nvc.c:250] initializing library context (version=1.0.0, build=ec15c7233bd2de821ad5127cb0de6b52d9d2083c)
I1213 22:59:16.813092 16347 nvc.c:170] loading kernel module nvidia
I1213 22:59:16.813494 16347 nvc.c:182] loading kernel module nvidia_uvm
I1213 22:59:16.813592 16347 nvc.c:190] loading kernel module nvidia_modeset
I1213 22:59:16.813686 16347 nvc.c:225] using ldcache /etc/ld.so.cache
I1213 22:59:16.813697 16347 nvc.c:226] using unprivileged user 65534:65534
I1213 22:59:16.815216 16353 driver.c:134] starting driver service
W1213 22:59:41.850347 16347 driver.c:195] terminating driver service (forced)
I1213 22:59:44.646395 16347 driver.c:208] driver service terminated with signal 15

**Comment by 3XX0** [comment]
This is probably caused by your GPU being in Exclusive mode and you already have `python` processes running on all the GPUs.

Try stopping the `python` processes or removing the Exclusive mode with `sudo nvidia-smi -c 0`

**Comment by 3XX0** [comment]
ping @Yong-Zhuang

**Comment by Yong-Zhuang** [comment]
I run nvidia-smi, and I got

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 0000:04:00.0     Off |                  N/A |
| 23%   25C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 0000:05:00.0     Off |                  N/A |
| 23%   22C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 0000:08:00.0     Off |                  N/A |
| 23%   23C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 0000:09:00.0     Off |                  N/A |
| 23%   24C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 0000:84:00.0     Off |                  N/A |
| 23%   24C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 0000:85:00.0     Off |                  N/A |
| 23%   21C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 0000:88:00.0     Off |                  N/A |
| 23%   20C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  On   | 0000:89:00.0     Off |                  N/A |
| 23%   22C    P8     8W / 250W |      0MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


It can be seen there are no running processes.

However when I run:   nvidia-docker run --name tensorflow -it  gcr.io/tensorflow/tensorflow:latest-gpu
I got the same error message:

docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=8.0 --pid=41664 /data/docker/aufs/mnt/a542e14f71fb7b394da7c905c2ec9fbb27c4d8c31a3ce83026de4040a5547200]\\\\nnvidia-container-cli: initialization error: driver error: RPC: timed out\\\\n\\\"\"".


And then I check " nvidia-smi" again, I got


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 0000:04:00.0     Off |                  N/A |
| 23%   24C    P8     8W / 250W |   1357MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 0000:05:00.0     Off |                  N/A |
| 23%   22C    P8     9W / 250W |   1357MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 0000:08:00.0     Off |                  N/A |
| 23%   23C    P8     8W / 250W |   1357MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 0000:09:00.0     Off |                  N/A |
| 23%   24C    P8     9W / 250W |   1357MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 0000:84:00.0     Off |                  N/A |
| 23%   24C    P8     8W / 250W |   1357MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 0000:85:00.0     Off |                  N/A |
| 23%   21C    P8     9W / 250W |   1357MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 0000:88:00.0     Off |                  N/A |
| 23%   20C    P8     9W / 250W |      7MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  On   | 0000:89:00.0     Off |                  N/A |
| 23%   22C    P8     8W / 250W |      7MiB / 11172MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


Every GPU has some memory usage. I don't know why.

This is a server machine which I cannot use sudo command.

**Comment by Yong-Zhuang** [comment]
This is the log I got:

-- WARNING, the following logs are for debugging purposes only --

I1227 00:25:40.575367 41698 nvc.c:250] initializing library context (version=1.0.0, build=ec15c7233bd2de821ad5127cb0de6b52d9d2083c)
I1227 00:25:40.579725 41698 nvc.c:170] loading kernel module nvidia
I1227 00:25:40.580011 41698 nvc.c:182] loading kernel module nvidia_uvm
I1227 00:25:40.580090 41698 nvc.c:190] loading kernel module nvidia_modeset
I1227 00:25:40.580186 41698 nvc.c:225] using ldcache /etc/ld.so.cache
I1227 00:25:40.580196 41698 nvc.c:226] using unprivileged user 65534:65534
I1227 00:25:40.581639 41702 driver.c:134] starting driver service
W1227 00:26:05.616729 41698 driver.c:195] terminating driver service (forced)
I1227 00:26:06.438130 41698 driver.c:208] driver service terminated with signal 15

**Comment by flx42** [comment]
Having leftover allocated GPU memory when no process is running is often a symptom of a driver issue. Try upgrading your driver to 387.
