### ISSUE TITLE
Install new Python dependencies in Nvidia-docker

### ISSUE THREAD

**Issue by ankit1997** [NVIDIA/nvidia-docker#573]
Hello,
First of all, thank you to the open source community who built such an amazing platform!

How do you install python dependencies other than the ones which come by default (using pip3/sudo-apt), for example, scikit-image, keras, etc.?
I can open a terminal in the notebook. But it has only `pip` (for python2) installed by default and I cannot seem to use `sudo` to install pip3 ( `/bin/sh: 3: sudo: not found` )
Can someone please help me on this?

Also, any recommendation for a good learning website for docker (or nvidia-docker)? The official documentation looks very overwhelming (to a lot of people I'm sure).

Thank you.

**Comment by flx42** [comment]
You should be root inside the container, so you don't need to do `sudo apt-get`, you can just do `apt-get`.
You can still `apt-get install sudo` too :)

There are so many tutorials on learning Docker out there... I can't recommend one, start by learning about the Dockerfiles, it's quite easy to understand.

**Comment by ankit1997** [comment]
Thanks for the response.
But I'm not able to install `sudo` and `pip3` using that.
`E: Unable to locate package sudo`
and 
`E: Unable to locate package python3-pip`

What can be the problem?

**Comment by flx42** [comment]
Do `apt-get update` first.

**Comment by ankit1997** [comment]
It worked! Thank you so much.
I'll surely take a look at `Dockerfile`.
