### ISSUE TITLE
Not working behind a corporate proxy...

### ISSUE THREAD

**Issue by jinho99** [NVIDIA/nvidia-docker#574]
### 1. Issue or feature description
It doesn't seem to work in a corporate network where internet connections are allowed only through proxy.
The original plain docker command works with a proxy after adding http_proxy variables in /etc/default/docker, but 
the one for nvidia-docker can't be found. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
Linux pandora13 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
N/A

 - [ ] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Thu Dec 14 18:53:08 2017
Driver Version                      : 367.18

Attached GPUs                       : 8
GPU 0000:04:00.0
    Product Name                    : Graphics Device
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-e2a31267-8950-0dd6-bf6e-3339b7dfc3fd
    Minor Number                    : 0
    VBIOS Version                   : 86.04.17.00.01
    MultiGPU Board                  : No
    Board ID                        : 0x400
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.03
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    PCI
        Bus                         : 0x04
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B8010DE
        Bus Id                      : 0000:04:00.0
        Sub System Id               : 0x142519DA

 - [ ] Docker version from `docker version`
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:29 2017
 OS/Arch:      linux/amd64
 Experimental: false

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment]
You shouldn't have this issue with nvidia-docker 2.0.

**Comment by jinho99** [comment]
The problem was because of firewall issues beyond the proxy server and now fixed to be working fine. flx42, thanks
