### ISSUE TITLE
Nvidia-docker Jupyter-notebook fails to import installed module

### ISSUE THREAD

**Issue by ankit1997** [NVIDIA/nvidia-docker#576]
Hello,
I am installing python modules using the terminal present in the notebook via `pip3`.
`pip3 install tqdm` for example.
When I open Python console using `python3.5`, it successfully imports the module
```
# python3.5
>>> import tqdm # success
```
But inside the notebook, it `fails`.

I see that the `sys.executable` is different. 
In console, it is `/usr/bin/python3.5` whereas,
In notebook, it is `/usr/bin/python`. 
Probably this is causing the error. What is the proper way to fix this?

Thank you.

**Comment by flx42** [comment]
Sorry but I don't know. This issue is not related to nvidia-docker.
