### ISSUE TITLE
nvidia-container-cli: detection error: nvml error: not found

### ISSUE THREAD

**Issue by Zakaria-Ben** [NVIDIA/nvidia-docker#579]
Hi Guys, I'm having an issue with Cuda container.
I have a Macbook Pro mid 2010 with a GeForce 320M GPU. Cuda 6.5 runs perfectly on the host, but I have an issue with Cuda 6.5 container.

nvidia-smi :

+------------------------------------------------------+                       
| NVIDIA-SMI 340.102    Driver Version: 340.102        |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 320M        Off  | 0000:04:00.0     N/A |                  N/A |
| N/A   57C   P12    N/A /  N/A |    132MiB /   252MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

the Docker version I'm using is : 17.09.1-ce

When I want to use Nvidia container using :  `docker run --runtime=nvidia --rm nvidia/cuda:6.5-devel nvidia-smi` , I got this error : 

container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=6.5 --pid=24273 /var/lib/docker/overlay2/c8448e2b008c2310309a01f42e028c86f4a6d6698d99f49a99ba3fbeef3a87ec/merged]\\\\nnvidia-container-cli: detection error: nvml error: not found\\\\n\\\"\""
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=6.5 --pid=24273 /var/lib/docker/overlay2/c8448e2b008c2310309a01f42e028c86f4a6d6698d99f49a99ba3fbeef3a87ec/merged]\\\\nnvidia-container-cli: detection error: nvml error: not found\\\\n\\\"\"".

I'm really struggling with this issue.

**Comment by flx42** [comment]
Hello,

Macbooks are not supported. You need a Linux desktop/laptop:
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-macos-supported
https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0)#prerequisites

**Comment by flx42** [comment]
Well, we still do not support this hardware, your GPU is too ancient (and the driver is too old too).

**Comment by Zakaria-Ben** [comment]
Alright, Thanks.
