### ISSUE TITLE
failure running `sudo make install`

### ISSUE THREAD

**Issue by EvanZ** [NVIDIA/nvidia-docker#58]
I'm running this on an EC2 instance.

```
make -C /home/ubuntu/nvidia-docker/tools install
make[1]: Entering directory `/home/ubuntu/nvidia-docker/tools'
flag provided but not defined: --build-arg
See 'docker build --help'.
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/ubuntu/nvidia-docker/tools'
make: *** [install] Error 2

```

Thu Mar 17 21:58:31 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.79     Driver Version: 352.79         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   28C    P0    36W / 125W |     11MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by 3XX0** [comment]
`nvidia-docker` requires Docker 1.9.
See https://github.com/NVIDIA/nvidia-docker/wiki/Installation

**Comment by flx42** [comment]
I think the problem was identified, closing.
