### ISSUE TITLE
Cannot execute command with "run" argument

### ISSUE THREAD

**Issue by mirandaconrado** [NVIDIA/nvidia-docker#581]
When I try to do
```
nvidia-docker exec -i -t  my_tag /path/to/executable run /path/to/commands
```
it gives an error `ERROR: Unrecognized option: --runtime=nvidia`. The same command works perfectly for pure docker.

Looking at the script, it looks like the culprit is the loop that checks for some special keywords anywhere in the list of arguments. This seems to effectively prevent some combinations of commands from executing.

I'm also not sure why we traverse the full argument list, since `run` seems like it has to be the first argument to docker:
```
conrado@conrado-pc:~/workspace/ai-infra$ docker -i -t bazel-ci:latest run /bin/bash
unknown shorthand flag: 'i' in -i
conrado@conrado-pc:~/workspace/ai-infra$ docker run -i -t bazel-ci:latest /bin/bash
user@1185b37e32c7:/workspace$ exit
conrado@conrado-pc:~/workspace/ai-infra$ nvidia-docker run -i -t bazel-ci:latest /bin/bash
user@75758555e3eb:/workspace$ exit
conrado@conrado-pc:~/workspace/ai-infra$ nvidia-docker -i -t bazel-ci:latest run /bin/bash
unknown shorthand flag: 'i' in -i
```

I've been using the quick fix of adding
```
*)
   break
;;
```
at line 24 of the script and it has worked fine for me so far.

**Comment by flx42** [comment]
> I'm also not sure why we traverse the full argument list, since run seems like it has to be the first argument to docker

No. You can have any of the following:
```
Options:
      --config string      Location of client config files (default "/home/fabecassis/.docker")
  -D, --debug              Enable debug mode
      --help               Print usage
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/fabecassis/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/fabecassis/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/fabecassis/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit
```

**Comment by flx42** [comment]
This script was not really designed to be used for commands other than `run` or `create`, since we don't want to add back the complex parsing logic we had in 1.0.
We could still add more commands in the `case` for this. @3XX0 what do you think?

**Comment by flx42** [comment]
To avoid adding complexity to this script, I just want to add the following:
```
        --)
            break
        ;;
```
It might not solve your use case immediately, but if you add a `--` in the commands executed by your tool, it will be better all around.

This now works fine:
```
$ ./nvidia-docker -D exec -ti -- 547 ls -l run
total 16
drwxr-xr-x 2 dnsmasq nogroup 4096 Dec 19 18:00 dnsmasq
drwxrwxrwt 2 root    root    4096 Dec 14 00:49 lock
drwxr-xr-x 2 root    root    4096 Dec 14 00:49 mount
drwxr-xr-x 1 root    root    4096 Dec 19 17:56 systemd
-rw-rw-r-- 1 root    utmp       0 Dec 14 00:49 utmp
DEBU[0000] Error resize: Error response from daemon: rpc error: code = Unknown desc = containerd: process not found for container 
DEBU[0000] [hijack] End of stdout
```
