### ISSUE TITLE
Docker container data location

### ISSUE THREAD

**Issue by MonkeyWithAComputer** [NVIDIA/nvidia-docker#592]
Where are the jobs being saved for a docker container?

I used the NGC install guide on a local computer running a titan. When I created the new container I used: sudo nvidia-docker run --name digits -d -p 5000:5000 -v digits-jobs:/home/dev/digits_data/jobs/ -v /home/dev/digits_data/data/:/data/ nvcr.io/nvidia/digits:17.12

My goal was to set the path for my data and the path for where it saves the jobs. The data path is there, but the jobs do not get saved in the folder I specified.

Digits container version: 17.12

NVIDIA Docker: 1.0.1

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by flx42** [comment]
When you use `-v digits-jobs:[...]` you have a [named volume](https://docs.docker.com/engine/admin/volumes/volumes/). It won't use `./digits-jobs` as you might have been expecting. You would have to use `-v $(pwd)/digits-jobs:[...]`

You can use `docker volume inspect digits-jobs` to find the actual location.

**Comment by cliffwoolley** [comment]
Please refer questions about NGC containers to the NVIDIA GPU Cloud section
of the devtalk.nvidia.com forums.  You'll find that there's already an
answered question there about this issue in the DIGITS section.

Thanks,
Cliff
