### ISSUE TITLE
AWS Ubuntu Xenial version issue

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/nvidia-docker#593]
### 1. Issue or feature description
Running an AWS instance of xenial results in invalid version for install
### 2. Steps to reproduce the issue
1) spin up ubuntu image on aws.
2) install docker.io package

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kernel version from uname -a
Linux ip-172-31-21-158 4.4.0-1044-aws #53-Ubuntu SMP Mon Dec 11 13:49:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Docker version from `docker version`
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
$ dpkg -l '*nvidia*'
dpkg-query: no packages found matching *nvidia*

- [ ] `apt search docker`
docker.io/xenial-updates,now 1.13.1-0ubuntu1~16.04.2 amd64 [installed]
  Linux container runtime

- [ ] attempted install
```
$ sudo apt install -y nvidia-docker2=2.0.0+docker1.13.1-1 nvidia-container-runtime=1.0.0+docker1.13.1-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 1.13.1-0~ubuntu-xenial) but it is not installable or
                           docker-ee (= 1.13.1-0~ubuntu-xenial) but it is not installable or
                           docker-engine (= 1.13.1-0~ubuntu-xenial) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Unsure if this is an issue with 1.13.1-0 vs 1.13.1-1 or the fact that I don't see docker.io listed in dependencies.

**Comment by flx42** [comment]
Use our more recent packages instead:
```
$ sudo apt-get install -y docker.io nvidia-docker2=2.0.2+docker1.13.1-1 nvidia-container-runtime=1.1.1+docker1.13.1-1
```

**Comment by hyperbolic2346** [comment]
Sorry I missed those in the list from apt-cache. Thanks for the help.

**Comment by GSanchis** [comment]
How did you actually get around this? I'm running into the same problem with a Google Cloud machine, but I don't seem to get it fixed. I installed the repositories from 

```
https://nvidia.github.io/nvidia-docker/
```

but it still keeps complaining

```
$ sudo apt-get install nvidia-docker2=2.0.2+docker1.13.1-1 nvidia-container-runtime=1.1.1+docker1.13.1-1 docker.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker.io is already the newest version (1.13.1-0ubuntu6).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-engine (= 1.13.1-0~ubuntu-xenial) but it is not installable or
                           docker.io (= 1.13.1-0ubuntu1~16.04.2) but 1.13.1-0ubuntu6 is to be installed
E: Unable to correct problems, you have held broken packages.
```
with
```
$ docker -v
Docker version 1.13.1, build 092cba3
$ apt-cache showpkg docker.io
Package: docker.io
Versions: 
1.13.1-0ubuntu6 [...]
```
