### ISSUE TITLE
Secure and speedy builds

### ISSUE THREAD

**Issue by ruffsl** [NVIDIA/nvidia-docker#6]
Looks like we are still using `wget` to fetch the gpg key https://github.com/NVIDIA/nvidia-docker/commit/97ccc7e537ce52cdb2ef0fc29b17978420126b68. Using a check sum is much better than before, but this still requires two `apt-get update` calls for every build to install the wget prerequisite. I've suggested using gpg's key server function along with a high-availibility subset of a public keyserver pool in https://github.com/ruffsl/nvidia-docker/commit/2000a09da2f6651cc9757f995be1c56ee62d8d2b to circumvent this issue like in docker's docs, but no takers thus far. This is [Nvidia's key](http://ha.pool.sks-keyservers.net/pks/lookup?search=0x889BEE522DA690103C4B085ED88C3D385C37D3BE&op=vindex) correct? Is Nvida planning on running an independent key server?
![image](https://cloud.githubusercontent.com/assets/2293573/11155248/679cf7b2-8a12-11e5-9f0b-1320d5ade2f9.png)

**Comment by 3XX0** [comment]
Thanks for your input, the ```wget``` prerequisite has been removed.

**Comment by ruffsl** [comment]
Nice, creative solution. :+1: 
I spent some time looking at gpg for a similar feature, 
this should help build times.
