### ISSUE TITLE
Mesos REST API

### ISSUE THREAD

**Issue by kbokh** [NVIDIA/nvidia-docker#60]
There is REST API for mesos slave nodes ( /v1.0/mesos/cli). Is there any howto about using this api with mesos? I am using a mesos cluster for cuda based ML trainings and developed some tricks to select GPU  for dockerized  training processes. Investigation of  /v1.0/mesos/cli showed that the API provides configuration parameters for mesos slaves (attributes and resources) but it is not clear how it can be used with mesos frameworks (marathon, singularity) and nvidia-docker. I'd be grateful if someone could provide additional information about using  nvidia-docker-plugin REST API with a mesos ecosystem.

**Comment by 3XX0** [comment]
The `/mesos/cli` entrypoint generates `mesos-slave` arguments. 
It is composed  of a custom resource  and a custom attribute named `gpus`:

```sh
--attributes=gpus:<GPU-INFO>
--resources=gpus:{<GPU-UUID>,<GPU-UUID>...}
```

Where `<GPU-INFO>` is the output of `/gpu/info` zlib compressed and encoded in base64 (RFC 6920), and `<GPU-UUID>` is the UUID of a given GPU as reported by `/gpu/info`

```sh
# Run mesos-slave with GPU resources
mesos-slave --master=localhost:5050 `curl -s localhost:3476/mesos/cli`
```

Note that it is the responsibility of the framework to understand and consume these resources.
