### ISSUE TITLE
Support  Jupyter Notebooks

### ISSUE THREAD

**Issue by iramsey85** [NVIDIA/nvidia-docker#606]
### 1. Issue or feature description
Are there any plans to support juypter notebook images with GPU support enabled?

nvidia-docker run works for Jupyter/tensorflow, but GPU support is not available for that image.

**Comment by flx42** [comment]
It's already supported by TensorFlow.
```
$ docker run --runtime=nvidia -ti -p 8888:8888 tensorflow/tensorflow:1.5.0-rc1-gpu
```
