### ISSUE TITLE
Nvidia DIGITS - CPU with no graphical processing unit hardware.

### ISSUE THREAD

**Issue by chandanv2** [NVIDIA/nvidia-docker#609]
System configurations -
Processor Inter Core - i5-2400 CPU @3.10GHz X 4
8GB CPU RAM
No Grpahical Processing Unit.
OS - Ubuntu 16.04 LTS 64bit
I want to run  digits on my computer system in CPU mode only. So can we run digits on a system which has no Nvidia or other GPU? Please list the ways in which I can realise Digits with this limited hardware capabilities (preferably with Caffe framework) such that there is less burden on installing of various dependencies(for eg: Using docker). Also please let me know how to install without docker. If you have any information about the time required for training and other purposes, it would be of great help if you shared it. 

Thank You.

**Comment by flx42** [comment]
You should take a look at the Dockerfile for DIGITS 6.0 and then carve out the GPU parts to get a CPU image:
https://gitlab.com/nvidia/digits/blob/master/6.0/Dockerfile

**Comment by flx42** [comment]
Closing since this is not a supported use case.
