### ISSUE TITLE
developer.download.nvidia.com: Host not found

### ISSUE THREAD

**Issue by vponcelo** [NVIDIA/nvidia-docker#61]
Hi,

I cloned the project succesfully with:

`
git clone https://github.com/NVIDIA/nvidia-docker
`

and I have troubles at the beginning steps of the make install when retrieving some packages from the nvidia repositories:

`
Step 5 : RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY &&     apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub &&     echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub &&     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /" > /etc/apt/sources.list.d/cuda.list
 ---> Running in 4f8f2eb021fe
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.McNrxDbdy4 --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
?: developer.download.nvidia.com: Host not found
gpgkeys: http fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver internal error
gpg: WARNING: unable to fetch URI http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY: keyserver error
The command '/bin/sh -c apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY &&     apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub &&     echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub &&     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /" > /etc/apt/sources.list.d/cuda.list' returned a non-zero code: 2
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/user/nvidia-docker/tools'
make: *** [tools] Error 2
`

I am quite new using docker but I found similar problems compiling Dockerfiles, where apt-get udpate failed when retrieving other online package repositories too. I guess this could be related with this problem.

**Comment by 3XX0** [comment]
Looks like your DNS (inside the Docker) can't resolve our server address.
This could happen if your OS distribution uses a DNS forwarder (e.g. dnsmasq on Ubuntu) and Google DNS are not reachable (e.g. China).

Try changing the configuration of your [Docker DNS] (https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/) in `/etc/default/docker` using `--dns`.

**Comment by vponcelo** [comment]
Thanks for your answer. I tried to uncomment the highlighted line within the file you mentioned:

`
vponcel@cudahpc2:~/nvidia-docker$ sudo vi /etc/default/docker
# Docker Upstart and SysVinit configuration file

#
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/articles/systemd/
#

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
**DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"**

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
`

But the same problem occurs. I guess I should reboot the system for applying changes made in these these type of files, but I am not allowed to reboot this server right now. Anyway, did you refer to this for solving the DNS problem?

**Comment by flx42** [comment]
You don't need to reboot the whole machine, just Docker:
`sudo service docker restart`

**Comment by vponcelo** [comment]
thank you @flx42 I didn't think about that! 
I already restarted the docker service with the previous changes but does not seem to solve the DNS problem. Probably I either need some step in between or forward the DNS to another address. I have no idea.

**Comment by 3XX0** [comment]
Can you contact `8.8.8.8` from your host? What about in a container?
`nvidia-docker run ubuntu ping 8.8.8.8`

**Comment by vponcelo** [comment]
I tried both addresses 8.8.8.8 and 8.8.4.4 from the host and the docker container: 

`
docker run ubuntu ping 8.8.8.8
`

and I always did get responses. 

However, calling Nvidia-docker container,  as you suggested (instead of just docker I used), doesn't work since it couldn't be built because of the troubles when getting the packages. 

Any other suggestion? Thank you.

**Comment by 3XX0** [comment]
What's the output of
```sh
docker run ubuntu sh -c 'apt-get update && apt-get install -y --no-install-recommends dnsutils && dig developer.download.nvidia.com'
```
Also, try changing the `--dns` servers with the ones used by your host.

Note that you can install `nvidia-docker` without building it, see [quick start](https://github.com/NVIDIA/nvidia-docker/wiki#quick-start)

**Comment by vponcelo** [comment]
This was the output:

```
Err http://archive.ubuntu.com trusty InRelease

Err http://archive.ubuntu.com trusty-updates InRelease

Err http://archive.ubuntu.com trusty-security InRelease

Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  bind9-host libbind9-90 libdns100 libgeoip1 libgssapi-krb5-2 libisc95
  libisccc90 libisccfg90 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0
  liblwres90 libxml2
Suggested packages:
  rblcheck geoip-bin krb5-doc krb5-user
Recommended packages:
  geoip-database krb5-locales xml-core
The following NEW packages will be installed:
  bind9-host dnsutils libbind9-90 libdns100 libgeoip1 libgssapi-krb5-2
  libisc95 libisccc90 libisccfg90 libk5crypto3 libkeyutils1 libkrb5-3
  libkrb5support0 liblwres90 libxml2
0 upgraded, 15 newly installed, 0 to remove and 0 not upgraded.
Need to get 2171 kB of archives.
After this operation, 7534 kB of additional disk space will be used.
Err http://archive.ubuntu.com/ubuntu/ trusty/main libgeoip1 amd64 1.6.0-1
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libkrb5support0 amd64 1.12+dfsg-2ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libk5crypto3 amd64 1.12+dfsg-2ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libkeyutils1 amd64 1.5.6-1
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libkrb5-3 amd64 1.12+dfsg-2ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libgssapi-krb5-2 amd64 1.12+dfsg-2ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libxml2 amd64 2.9.1+dfsg1-3ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libisc95 amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libdns100 amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libisccc90 amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libisccfg90 amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main libbind9-90 amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main liblwres90 amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main bind9-host amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ trusty/main dnsutils amd64 1:9.9.5.dfsg-3
  Could not resolve 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/geoip/libgeoip1_1.6.0-1_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/k/krb5/libkrb5support0_1.12+dfsg-2ubuntu4_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/k/krb5/libk5crypto3_1.12+dfsg-2ubuntu4_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/k/keyutils/libkeyutils1_1.5.6-1_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/k/krb5/libkrb5-3_1.12+dfsg-2ubuntu4_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/k/krb5/libgssapi-krb5-2_1.12+dfsg-2ubuntu4_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.1+dfsg1-3ubuntu4_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/libisc95_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/libdns100_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/libisccc90_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/libisccfg90_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/libbind9-90_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/liblwres90_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/bind9-host_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/dnsutils_9.9.5.dfsg-3_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Comment by vponcelo** [comment]
Thank you @3XX0. I could install successfully nvidia-docker from your [quick start link](https://github.com/NVIDIA/nvidia-docker/wiki#quick-start).

However, I cannot create a full docker image using the apt-get update because it still give troubles about the host DNS. I tried your line instruction, first, with any modification in the `/etc/default/docker` file. Second, by adding Google DNS with `DOCKER_OPTS="--dns 8.8.8.8 8.8.4.4"`. Finally, by adding the 4 DNS used by my host. In all cases the output was:

```
Err http://archive.ubuntu.com trusty InRelease
Err http://archive.ubuntu.com trusty-updates InRelease
Err http://archive.ubuntu.com trusty-security InRelease
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
[...]
```

But the only different when I don't assign any DNS in the `/etc/default/docker` file (remaining all lines commented) are these messages appearing on the header:

```
INFO[2321] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]
INFO[2321] IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]
```

In my server I am not allowed to add the Google DNS explicitly, and it seems this give a conflict with the docker config. However, I think it shouldn't be a problem and should work anyway because I have access to these non-localhost DNS, indirectly.

**Comment by flx42** [comment]
It doesn't look like a `nvidia-docker` problem at all. So I'm closing, you should try going here:
https://docs.docker.com/opensource/get-help/

**Comment by flx42** [comment]
@loveJasmine please open a new issue
