### ISSUE TITLE
Debian Usage Issues/Expose existing images

### ISSUE THREAD

**Issue by sconeyard** [NVIDIA/nvidia-docker#611]
Hi guys,
so I want to use a NVIDIA GPU with JupyterHub. Based on https://github.com/jupyterhub/jupyterhub-deploy-docker . 
I installed all drivers on the host and it works locally but not for the Docker Image. Docker runs with the --default-runtime=nvidia. I am also able to test the installation running nvidia/cuda:8.0-devel nvidia-smi . 
How can I now give the docker containers inside the jupyterhub repo (I linked above) access to the GPU? 
Specifically I need to add it to this file: https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/singleuser/Dockerfile .
Any Ideas? As mentioned I am using debian, so I think that will make things harder.

**Comment by flx42** [comment]
If your image is `FROM nvidia/cuda` or if you manually add the CUDA libraries in your Dockerfile (by looking at our own Dockerfiles), then you will be able to use GPU code inside Jupyter.

For instance, it works out of the box with the TensorFlow images published on Docker Hub. Here is their dockerfile: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu

**Comment by flx42** [comment]
Also note that we don't provide Docker images based on Debian.
