### ISSUE TITLE
NVIDIA Digits Caffe Installation

### ISSUE THREAD

**Issue by chandanv2** [NVIDIA/nvidia-docker#616]
Even after setting CPU_ONLY :=1 in the Makefile.config after running cmake I am still getting CPU_ONLY as OFF. What might be the problem with this?
![cpu](https://user-images.githubusercontent.com/35568838/35207039-9831d738-ff38-11e7-9a9a-ac04581739d4.png)

**Comment by chandanv2** [comment]
I have removed the Cuda Support as well.

**Comment by cliffwoolley** [comment]
@chandanv2 -- this is not an nvidia-docker issue.
