### ISSUE TITLE
Support for other debian versions

### ISSUE THREAD

**Issue by romarcg** [NVIDIA/nvidia-docker#617]
How can nvidia-docker2, nvidia-container-runtime be installed in other linux distributions not listed in the webpage

I have been trying to install docker-nvidia2 in Debian (8) Jessie without success. I am able to install 17.12.0ce-0debian. As I don't see any mention of "other supported distributions", I wonder if is this installation possible?

So far when I try to install nvidia-container-runtime I get a dependency error:
> nvidia-container-runtime : Depends: libseccomp2 (>= 2.3.0) but 2.1.1-1 is to be installed

I am using the repository configuration instructions fro Debian Stretch. I could not find a supported entry for Jessie.

Information:

 - [ ] Kernel version from `uname -a`

Linux venus 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

 - [ ] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Mon Jan 22 15:18:54 2018
Driver Version                      : 367.57

Attached GPUs                       : 4
GPU 0000:05:00.0
    Product Name                    : Tesla K80
    Product Brand                   : Tesla
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Enabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0320615095340
    GPU UUID                        : GPU-8e8014b7-333e-7895-50c3-1922fb19e3ac
    Minor Number                    : 0
    VBIOS Version                   : 80.21.1B.00.01
    MultiGPU Board                  : Yes
    Board ID                        : 0x300
    GPU Part Number                 : 900-22080-0000-000
    Inforom Version
        Image Version               : 2080.0200.00.04
        OEM Object                  : 1.1
        ECC Object                  : 3.0
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x05
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x102D10DE
        Bus Id                      : 0000:05:00.0
        Sub System Id               : 0x106C10DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : N/A
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        Unknown                     : Not Active
    FB Memory Usage
        Total                       : 12205 MiB
        Used                        : 0 MiB
        Free                        : 12205 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 2 MiB
        Free                        : 16382 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Ecc Mode
        Current                     : Disabled
        Pending                     : Disabled
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : 0
        Double Bit ECC              : 0
        Pending                     : No
    Temperature
        GPU Current Temp            : 37 C
        GPU Shutdown Temp           : 93 C
        GPU Slowdown Temp           : 88 C
    Power Readings
        Power Management            : Supported
        Power Draw                  : 26.20 W
        Power Limit                 : 149.00 W
        Default Power Limit         : 149.00 W
        Enforced Power Limit        : 149.00 W
        Min Power Limit             : 100.00 W
        Max Power Limit             : 175.00 W
    Clocks
        Graphics                    : 324 MHz
        SM                          : 324 MHz
        Memory                      : 324 MHz
        Video                       : 405 MHz
    Applications Clocks
        Graphics                    : 562 MHz
        Memory                      : 2505 MHz
    Default Applications Clocks
        Graphics                    : 562 MHz
        Memory                      : 2505 MHz
    Max Clocks
        Graphics                    : 875 MHz
        SM                          : 875 MHz
        Memory                      : 2505 MHz
        Video                       : 540 MHz
    Clock Policy
        Auto Boost                  : On
        Auto Boost Default          : On
    Processes                       : None
...

 - [ ] Docker version from `docker version`

Docker version 17.12.0-ce, build c97c6d6

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version         Architecture    Description
+++-====================-===============-===============-==============================================
un  bumblebee-nvidia     <none>          <none>          (no description available)
un  libgl1-nvidia-altern <none>          <none>          (no description available)
un  libgl1-nvidia-glx    <none>          <none>          (no description available)
un  libglx-nvidia-altern <none>          <none>          (no description available)
ii  libnvidia-container- 1.0.0~alpha.2-1 amd64           NVIDIA container runtime library (command-line
ii  libnvidia-container1 1.0.0~alpha.2-1 amd64           NVIDIA container runtime library
rc  nvidia-346           346.46-0ubuntu1 amd64           NVIDIA binary driver - version 346.46
un  nvidia-346-uvm       <none>          <none>          (no description available)
un  nvidia-alternative   <none>          <none>          (no description available)
ii  nvidia-container-run 1.1.1+docker17. amd64           NVIDIA container runtime
un  nvidia-current       <none>          <none>          (no description available)
un  nvidia-docker        <none>          <none>          (no description available)
ii  nvidia-docker2       2.0.2+docker17. all             nvidia-docker CLI wrapper
un  nvidia-driver        <none>          <none>          (no description available)
un  nvidia-driver-binary <none>          <none>          (no description available)
un  nvidia-glx           <none>          <none>          (no description available)
un  nvidia-glx-dev       <none>          <none>          (no description available)
un  nvidia-glx-ia32      <none>          <none>          (no description available)
un  nvidia-glx-legacy-17 <none>          <none>          (no description available)
un  nvidia-glx-legacy-17 <none>          <none>          (no description available)
un  nvidia-glx-legacy-71 <none>          <none>          (no description available)
un  nvidia-glx-legacy-71 <none>          <none>          (no description available)
un  nvidia-glx-legacy-96 <none>          <none>          (no description available)
un  nvidia-glx-legacy-96 <none>          <none>          (no description available)
un  nvidia-installer-cle <none>          <none>          (no description available)
un  nvidia-kernel-340.65 <none>          <none>          (no description available)
un  nvidia-kernel-dkms   <none>          <none>          (no description available)
un  nvidia-kernel-source <none>          <none>          (no description available)
un  nvidia-libopencl1-34 <none>          <none>          (no description available)
un  nvidia-libopencl1-de <none>          <none>          (no description available)
un  nvidia-libvdpau1-ia3 <none>          <none>          (no description available)
un  nvidia-opencl-icd    <none>          <none>          (no description available)
rc  nvidia-opencl-icd-34 346.46-0ubuntu1 amd64           NVIDIA OpenCL ICD
un  nvidia-persistenced  <none>          <none>          (no description available)
un  nvidia-prime         <none>          <none>          (no description available)
un  nvidia-settings      <none>          <none>          (no description available)
un  nvidia-support       <none>          <none>          (no description available)
un  nvidia-va-driver     <none>          <none>          (no description available)
un  nvidia-vdpau-driver  <none>          <none>          (no description available)
rc  xserver-xorg-video-n 340.65-2        amd64           NVIDIA binary Xorg driver
un  xserver-xorg-video-n <none>          <none>          (no description available)

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`

version: 1.0.0
build date: 2017-10-30T23:47+00:00
build revision: ec15c7233bd2de821ad5127cb0de6b52d9d2083c
build compiler: gcc-5 5.4.0 20160609
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] Docker command, image and tag used

docker run --runtime=nvidia --rm nvidia/cuda:8.0-cudnn6-devel nvidia-smi

docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=8.0 --pid=10934 /var/lib/docker/aufs/mnt/f70de535aadabae5cfa0daa675960b80983c38c60a3deb925bbf589640e68110]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 127\\\\n\\\"\"": unknown.

**Comment by adampl** [comment]
Any update on this issue?

**Comment by 3XX0** [comment]
Closing as there are packages for debian 8.
