### ISSUE TITLE
CUDA / Docker & GPG error

### ISSUE THREAD

**Issue by MattiasM80** [NVIDIA/nvidia-docker#619]
### 1. Issue or feature description:
**Installation of cuda inside docker (ubuntu 16) fails**. From the docker build log:
```
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:2 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:4 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:6 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]
Hit:7 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release
Hit:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:9 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [801 B]
Ign:9 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg
Hit:11 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
Err:11 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
  Hash Sum mismatch
Fetched 1365 B in 0s (2658 B/s)
Reading package lists...
[91mW: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: The repository 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release' is not signed.
E: Failed to fetch store:/var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu1604_x86%5f64_Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

```
### 2. Steps to reproduce the issue
[Dockerfile.txt](https://github.com/NVIDIA/nvidia-docker/files/1653266/Dockerfile.txt)

**Comment by flx42** [comment]
Seems to be the same than https://github.com/NVIDIA/nvidia-docker/issues/571 and https://github.com/NVIDIA/nvidia-docker/issues/613.
But the reporter in #613 said the issue is now fixed for him. Where are you located?

**Comment by MattiasM80** [comment]
In the US.
Is there anything on my side that I can do to resolve this? Is there another way to install the Nvidia dependencies?

**Comment by flx42** [comment]
Can you do the wget mentioned here? https://github.com/NVIDIA/nvidia-docker/issues/613#issuecomment-359136112

**Comment by MattiasM80** [comment]
RUN wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Release
 ---> Running in 7e57c56dd794
[91m--2018-01-22 19:29:52--  http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Release
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... [0m[91m192.229.211.70, 2606:2800:21f:3aa:dcf:37b:1ed6:1fb
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|192.229.211.70|:80... [0m[91mconnected.
HTTP request sent, awaiting response... [0m[91m200 OK
Length: 564 [application/octet-stream]
Saving to: 'Release'
[0m[91m
     0K                                                       100% 72.2M=0s

[0m[91m2018-01-22 19:29:52 (72.2 MB/s) - 'Release' saved [564/564]

[0mRemoving intermediate container 7e57c56dd794

**Comment by MattiasM80** [comment]
@flx42 Anything I can do on my side to avoid this problem?

**Comment by flx42** [comment]
You can only workaround the problem. I suggest you use our prebuilt `devel` images on DockerHub, then remove the `cuda.list` file for now.

**Comment by MattiasM80** [comment]
When is a fix planned?
I need an ubuntu 16 image with cuda 8 (not 9). What docker FROM command should I use?
Could you be more specific on how to "remove the cuda.list file".  Thanks!

**Comment by flx42** [comment]
I don't know when it will be fixed.

This is a potential workaround:
```
FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

RUN rm /etc/apt/sources.list.d/cuda.list
```

**Comment by MattiasM80** [comment]
Thanks!
What would be the non devel equivalent for that base image be?
`FROM nvidia/cuda:8.0-cudnn6-ubuntu16.04` was not found.

**Comment by flx42** [comment]
`nvidia/cuda:8.0-cudnn6-runtime-ubuntu16.04`

**Comment by jedichien** [comment]
Here is my solution
in your Dockerfile add this line `RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub` before `apt-get update`

**Comment by flx42** [comment]
That's not a good idea. Let us understand what it going on first. Thanks.

**Comment by 3XX0** [comment]
@MattiasM80 Does it work for you now? If not, what's the output of `apt-key export 7FA2AF80` in the container after you just pulled it?

And after the `apt-get update` can you try the following command:
```
apt-key adv --verify /var/lib/apt/lists/developer.download.nvidia.com_compute_cuda_repos_ubuntu1604_x86%5f64_Release.gpg /var/lib/apt/lists/developer.download.nvidia.com_compute_cuda_repos_ubuntu1604_x86%5f64_Release```

**Comment by 3XX0** [comment]
@MattiasM80 Is it resolved?

**Comment by MattiasM80** [comment]
@flx42  FROM nvidia/cuda:8.0-cudnn6-runtime-ubuntu16.04 worked excellent.
@3XX0  I didn't get to try `apt-key adv --verify /var/lib/apt/lists/developer.download.nvidia.com_compute_cuda_repos_ubuntu1604_x86%5f64_Release.gpg /var/lib/apt/lists/developer.download.nvidia.com_compute_cuda_repos_ubuntu1604_x86%5f64_Release````

Excuse me for the late reply.

**Comment by TaylorHere** [comment]
I got the same errs, the I just rm all the source about NVIDIA things, but it’s not a good way.
