### ISSUE TITLE
An NVIDIA kernel module 'nvidia-uvm' appears to already be loaded in your kernel

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/nvidia-docker#62]
I'm upgrading my driver and hitting this error during install.

I've hit it before and found that `nvidia-docker` was causing the problem. Can you remind me which command I need to run to be able to move ahead with my driver installation?

**Comment by lukeyeager** [comment]
Solved it with some combination of these commands:
```
sudo service lightdm stop
sudo stop nvidia-digits-server
sudo service docker stop
sudo rmmod nvidia-uvm
```

**Comment by 3XX0** [comment]
`service nvidia-docker stop` should do it (if only used by `nvidia-docker`)

**Comment by JNingWei** [comment]
I also encountered the same problem. The reason for the error was that I accidentally selected "Install nvidia driver" during the installation of cuda.

So, during the installation of CUDA, when you encounter the following options:

> Install NVIDIA Accelerated Graphics Driver for Linux-x86_64 384.81?
> (y)es/(n)o/(q)uit:

Please select **q** , the problem will be solved.

**Comment by GigiCoding** [comment]
> I also encountered the same problem. The reason for the error was that I accidentally selected "Install nvidia driver" during the installation of cuda.
> 
> So, during the installation of CUDA, when you encounter the following options:
> 
> > Install NVIDIA Accelerated Graphics Driver for Linux-x86_64 384.81?
> > (y)es/(n)o/(q)uit:
> 
> Please select **q** , the problem will be solved.

Thank you so much! This solved my problem.

**Comment by zhangxiaoya** [comment]
@JNingWei you should select *n*

**Comment by bruce2233** [comment]
So how to upgrade driver version in Nvidia-driver?
