### ISSUE TITLE
Can't use nvidia-docker2 with kernel 4.13

### ISSUE THREAD

**Issue by novioleo** [NVIDIA/nvidia-docker#620]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

```bash
nvidia-docker run -it nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.1 --pid=7296 /var/lib/docker/aufs/mnt/f97ca85e7d43ffdb283e7e84b35e7abf0a5b0bc4ad3d9320f38560add748064a]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: cuda >= 9.1\\\\n\\\"\"": unknown.

```
smilar to #610 ,i wonder know is there any solution can let me run nvidia-docker with kernel 4.13.0...

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Kernel version from `uname -a`
4.13.0-25-generic
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Wed Jan 24 10:58:18 2018
Driver Version                      : 384.111

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1050
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-5cdb94af-9b82-f394-13fe-0d58db7f0721
    Minor Number                    : 0
    VBIOS Version                   : 86.07.3C.00.C0
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1C8D10DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x103C1D05
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 456000 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : 0 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 1999 MiB
        Used                        : 638 MiB
        Free                        : 1361 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 5 MiB
        Free                        : 251 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 5 %
        Memory                      : 2 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 44 C
        GPU Shutdown Temp           : 102 C
        GPU Slowdown Temp           : 97 C
        GPU Max Operating Temp      : 94 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1911 MHz
        SM                          : 1911 MHz
        Memory                      : 3504 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 3623
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 310 MiB
        Process ID                  : 3972
            Type                    : G
            Name                    : /opt/teamviewer/tv_bin/TeamViewer
            Used GPU Memory         : 11 MiB
        Process ID                  : 4156
            Type                    : G
            Name                    : compiz
            Used GPU Memory         : 139 MiB
        Process ID                  : 4862
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=7801649548480340489,16754878847385531583,131072 --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x1c8d --gpu-driver-vendor=Nvidia --gpu-driver-version=384.111 --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x591b --gpu-active-vendor-id=0x10de --gpu-active-device-id=0x1c8d --service-request-channel-token=3670A8F4BBE40735C59265A45B0F9423
            Used GPU Memory         : 174 MiB

 - [x] Docker version from `docker version`
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
ii  libnvidia-container-tools           1.0.0~alpha.3-1        amd64                  NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64          1.0.0~alpha.3-1        amd64                  NVIDIA container runtime library
ii  nvidia-375                          384.111-0ubuntu0.16.04 amd64                  Transitional package for nvidia-384
ii  nvidia-375-dev                      384.111-0ubuntu0.16.04 amd64                  Transitional package for nvidia-384-dev
ii  nvidia-384                          384.111-0ubuntu0.16.04 amd64                  NVIDIA binary driver - version 384.111
ii  nvidia-384-dev                      384.111-0ubuntu0.16.04 amd64                  NVIDIA binary Xorg driver development files
un  nvidia-common                       <无>                   <无>                   (无可用描述)
ii  nvidia-container-runtime            1.1.1+docker17.12.0-1  amd64                  NVIDIA container runtime
un  nvidia-docker                       <无>                   <无>                   (无可用描述)
ii  nvidia-docker2                      2.0.2+docker17.12.0-1  all                    nvidia-docker CLI wrapper
un  nvidia-driver-binary                <无>                   <无>                   (无可用描述)
un  nvidia-legacy-340xx-vdpau-driver    <无>                   <无>                   (无可用描述)
un  nvidia-libopencl1-384               <无>                   <无>                   (无可用描述)
un  nvidia-libopencl1-dev               <无>                   <无>                   (无可用描述)
un  nvidia-opencl-icd                   <无>                   <无>                   (无可用描述)
ii  nvidia-opencl-icd-384               384.111-0ubuntu0.16.04 amd64                  NVIDIA OpenCL ICD
un  nvidia-persistenced                 <无>                   <无>                   (无可用描述)
ii  nvidia-prime                        0.8.2                  amd64                  Tools to enable NVIDIA's Prime
ii  nvidia-settings                     361.42-0ubuntu1        amd64                  Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary              <无>                   <无>                   (无可用描述)
un  nvidia-smi                          <无>                   <无>                   (无可用描述)
un  nvidia-vdpau-driver                 <无>                   <无>                   (无可用描述)

 - [x] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.0
build date: 2018-01-11T00:16+00:00
build revision: 4a618459e8ba522d834bb2b4c665847fae8ce0ad
build compiler: gcc-5 5.4.0 20160609
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [x] Docker command, image and tag used
nvidia-docker run -it nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

**Comment by flx42** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-fix-unsatisfied-condition-cuda--xy

**Comment by novioleo** [comment]
@flx42 thks,you're so fast.....
