### ISSUE TITLE
Would it be possible to get a deb file for nvidia-docker 2?

### ISSUE THREAD

**Issue by mattdornfeld** [NVIDIA/nvidia-docker#621]

**Comment by flx42** [comment]
Did you look at the instructions? we have a deb package repository
https://github.com/NVIDIA/nvidia-docker#xenial-x86_64

**Comment by mattdornfeld** [comment]
@flx42 Yes I saw that. Sorry maybe I'm not as knowledgable about Ubuntu as I should be. I'm having trouble figuring out how I can find the actual .deb file from that info. Would that be possible to get?

**Comment by flx42** [comment]
Why do you need the deb file if you have a repository?

Anyway, you can use something like that:
```
wget https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64/nvidia-container-runtime_1.1.1+docker17.12.0-1_amd64.deb
```
You have 3 packages to get, on 3 different repos: libnvidia-container, nvidia-container-runtime and nvidia-docker2

You can browse the available files here: https://github.com/nvidia/nvidia-container-runtime/tree/gh-pages
