### ISSUE TITLE
RPM installation: 404 on repomd.xml

### ISSUE THREAD

**Issue by jodok** [NVIDIA/nvidia-docker#624]
i've configured yum as described in the docs:
```
[nvidia-docker]
repo_gpgcheck=1
sslverify=1
name=nvidia-docker
gpgkey=https://nvidia.github.io/nvidia-docker/gpgkey
enabled=1
baseurl=https://nvidia.github.io/nvidia-docker/centos7/x86_64
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
gpgcheck=1
```

however when running `yum install...` or `yum update` i receive:

`https://nvidia.github.io/nvidia-docker-runtime/centos7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

**Comment by flx42** [comment]
Not sure what you've done, but the repo is `nvidia-container-runtime`, not `nvidia-docker-runtime`.

The instructions provided here work fine: https://github.com/NVIDIA/nvidia-docker#centosrhel-7-x86_64
