### ISSUE TITLE
unable to run docker

### ISSUE THREAD

**Issue by atulyadavtech** [NVIDIA/nvidia-docker#625]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

Getting error while running as per the steps
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=3195 /var/lib/docker/overlay2/cc5e49ea978a61786a7f87cbe3cd97b482d21b7fdbd705dcbd50a0e29eade746/merged]\\\\nnvidia-container-cli: initialization error: load library failed: libcuda.so.1: cannot open shared object file: no such file or directory\\\\n\\\"\"": unknown.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`

 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
Docker version 17.12.0-ce, build c97c6d6
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
nvidia-docker2-2.0.2-1.docker17.12.0.ce.noarch
libnvidia-container-tools-1.0.0-0.1.alpha.3.x86_64
nvidia-container-runtime-1.1.1-1.docker17.12.0.x86_64
libnvidia-container1-1.0.0-0.1.alpha.3.x86_64

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.0
build date: 2018-01-11T00:23+0000
build revision: 4a618459e8ba522d834bb2b4c665847fae8ce0ad
build compiler: gcc 4.8.5 20150623 (Red Hat 4.8.5-16)
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
cat /var/log/nvidia-container-runtime-hook.log

-- WARNING, the following logs are for debugging purposes only --

I0131 07:01:34.751302 3217 nvc.c:250] initializing library context (version=1.0.0, build=4a618459e8ba522d834bb2b4c665847fae8ce0ad)
I0131 07:01:34.753325 3217 nvc.c:170] loading kernel module nvidia
E0131 07:01:34.757344 3217 nvc.c:172] could not load kernel module nvidia
I0131 07:01:34.757378 3217 nvc.c:182] loading kernel module nvidia_uvm
E0131 07:01:34.761353 3217 nvc.c:184] could not load kernel module nvidia_uvm
I0131 07:01:34.761387 3217 nvc.c:190] loading kernel module nvidia_modeset
E0131 07:01:34.765369 3217 nvc.c:192] could not load kernel module nvidia_modeset
I0131 07:01:34.765463 3217 nvc.c:225] using ldcache /etc/ld.so.cache
I0131 07:01:34.765476 3217 nvc.c:226] using unprivileged user 65534:65534

 - [ ] Docker command, image and tag used
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nvidia/cuda         latest              6f7e5aebc10a        46 hours ago        2.16GB

**Comment by atulyadavtech** [comment]
Working fine after installing driver

**Comment by cheapRoc** [comment]
@atulyadavtech Please list the drivers, thanks man.
