### ISSUE TITLE
nvidia-docker causes hard lockup on Fedora 27

### ISSUE THREAD

**Issue by johnfrombluff** [NVIDIA/nvidia-docker#626]
### 1. Issue or feature description
Running "sudo systemctl start nvidia-docker causes the machine to freeze. I cannot even ssh in from another machine.

### 2. Steps to reproduce the issue
As above. I'm sorry, but I'm very new to this technology. I've searched Google but can't find a similar issue. I'm also completely new to Docker. I'm an end user, not a developer. So I hope I haven't omitted any important information out of ignorance.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
Linux lounge 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
Cannot obtain dmesg output because of the hard lockup, i.e. it appears nothing is written to the log

 - [ ] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Sat Feb  3 13:35:20 2018
Driver Version                      : 390.25

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1080
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-fe1dc5d8-3d89-f57d-982c-177535321797
    Minor Number                    : 0
    VBIOS Version                   : 86.04.3B.00.F3
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.03
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B8010DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x37111458
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 5000 KB/s
        Rx Throughput               : 2000 KB/s
    Fan Speed                       : 0 %
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 8116 MiB
        Used                        : 566 MiB
        Free                        : 7550 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 6 MiB
        Free                        : 250 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 5 %
        Memory                      : 2 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 49 C
        GPU Shutdown Temp           : 99 C
        GPU Slowdown Temp           : 96 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 51.97 W
        Power Limit                 : 250.00 W
        Default Power Limit         : 250.00 W
        Enforced Power Limit        : 250.00 W
        Min Power Limit             : 125.00 W
        Max Power Limit             : 375.00 W
    Clocks
        Graphics                    : 1759 MHz
        SM                          : 1759 MHz
        Memory                      : 5103 MHz
        Video                       : 1582 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 2062 MHz
        SM                          : 2062 MHz
        Memory                      : 5103 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1078
            Type                    : G
            Name                    : /usr/libexec/Xorg
            Used GPU Memory         : 18 MiB
        Process ID                  : 1179
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 43 MiB
        Process ID                  : 1525
            Type                    : G
            Name                    : /usr/libexec/Xorg
            Used GPU Memory         : 204 MiB
        Process ID                  : 1654
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 259 MiB

 - [ ] Docker version from `docker version`
Docker version 17.12.0-ce, build c97c6d6

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
nvidia-driver-390.25-2.fc27.x86_64
nvidia-modprobe-390.25-1.fc27.x86_64
nvidia-driver-cuda-390.25-2.fc27.x86_64
nvidia-docker-1.0.1-1.x86_64
nvidia-texture-tools-2.0.8-13.fc25.x86_64
nvidia-container-runtime-1.1.1-1.docker17.12.0.x86_64
nvidia-persistenced-390.25-1.fc27.x86_64
dkms-nvidia-390.25-1.fc27.x86_64
nvidia-driver-libs-390.25-2.fc27.x86_64
libnvidia-container1-1.0.0-0.1.alpha.3.x86_64
nvidia-xconfig-390.25-1.fc27.x86_64
nvidia-driver-NVML-390.25-2.fc27.x86_64
nvidia-texture-tools-devel-2.0.8-13.fc25.x86_64
kmod-nvidia-4.14.14-300.fc27.x86_64-390.25-1.fc27.x86_64
nvidia-driver-cuda-libs-390.25-2.fc27.x86_64
nvidia-driver-NvFBCOpenGL-390.25-2.fc27.x86_64
nvidia-settings-390.25-1.fc27.x86_64
libnvidia-container-tools-1.0.0-0.1.alpha.3.x86_64
nvidia-driver-devel-390.25-2.fc27.x86_64
nvidia-libXNVCtrl-390.25-1.fc27.x86_64
nvidia-libXNVCtrl-devel-390.25-1.fc27.x86_64
akmod-nvidia-390.25-1.fc27.x86_64

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
I can't run this, because it causes the freeze

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

 - [ ] Docker command, image and tag used
sudo systemctl start nvidia-docker

**Comment by 3XX0** [comment]
Your system has both v1 install as well as pieces of v2. I suggest you purge your v1 install and only rely on nvidia-docker2.

Now regarding the freeze, this is most likely a driver issue. Try downgrading the drivers and check the logs of your previous boot with `journalctl -k -b -1` (assuming it's configured properly)

**Comment by johnfrombluff** [comment]
Thanks for your quick and helpful reply! I must reiterate, I'm a humble end-user, not a programmers. So again, please forgive me if I'm clueless. The fact that I have a mix of nvidia-docker v1 & v2 on my system is due to my confusion about how to install v2. 

I see you have provided RPMs for CentOS and RHEL, but I can't see any for Fedora (I'm on v27). I must have installed v2 somehow, but I forget how. Any chance of a Fedora repository? Or some rpmbuild instructions for compiling from sources?

Thanks so much,

John

**Comment by 3XX0** [comment]
If you run `rpm -qa '*nvidia*'` and don't see `nvidia-docker-1.0.1-1.x86_64` then you're good to go. 2.0 doesn't rely on a daemon hence doesn't have a service file.

This issue however is most likely caused by your driver. Does CUDA work on the host?

**Comment by johnfrombluff** [comment]
Hi again, I've managed to get nvidia-docker2 running by cloning your repo and hacking the .service file included and manually installing it under /etc. It works fine with the latest nvidia driver. So you can close this ticket. But can you add instructions on your wiki about installing on Fedora?  If that's a pain, then don't worry.  

Thanks,

John

**Comment by escorciav** [comment]
Hi @johnfrombluff 
I added an [issue](https://github.com/NVIDIA/nvidia-docker/issues/706) where I'm compiling instructions for Fedora users. Could you help me to add info there?
