### ISSUE TITLE
Repo offline or non responsive

### ISSUE THREAD

**Issue by dmzoneill** [NVIDIA/nvidia-docker#632]
deb https://nvidia.github.io/libnvidia-container/debian9/amd64 /
deb https://nvidia.github.io/nvidia-container-runtime/debian9/amd64 /
deb https://nvidia.github.io/nvidia-docker/debian9/amd64 /

**Comment by flx42** [comment]
@dmzoneill can you be more specific? what problem do you see?

**Comment by dmzoneill** [comment]
Apt hangs on this repository.

root@dave-pc:/# apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [63.0 kB]                                                         
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                                                                                   
Get:5 http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease [166 kB]                                                            
Get:6 http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease [166 kB]
Ign:7 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:8 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:9 http://cdn-fastly.deb.debian.org/debian stretch Release                      
Fetched 320 kB in 0s (339 kB/s)
Reading package lists... Done
root@dave-pc:/# 
root@dave-pc:/# mv /etc/apt/sources.list.d/nvidia-docker.list.bak /etc/apt/sources.list.d/nvidia-docker.list
root@dave-pc:/# 
root@dave-pc:/# apt-get update
Hit:3 http://security.debian.org/debian-security stretch/updates InRelease                  
Ign:5 http://dl.google.com/linux/chrome/deb stable InRelease                                                                               
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                                                                                 
Hit:1 http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease                                 
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease          
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease  
Hit:7 http://cdn-fastly.deb.debian.org/debian jessie-backports InRelease 
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch Release
0% [Working]^C               
root@dave-pc:/# 
root@dave-pc:/# 
root@dave-pc:/# cat /etc/apt/sources.list.d/nvidia-docker.list 
deb https://nvidia.github.io/libnvidia-container/debian9/amd64 /
deb https://nvidia.github.io/nvidia-container-runtime/debian9/amd64 /
deb https://nvidia.github.io/nvidia-docker/debian9/amd64 /

**Comment by dmzoneill** [comment]
![image](https://user-images.githubusercontent.com/15192260/36073532-4b2e8268-0f2a-11e8-9961-e995ef5e14b8.png)

**Comment by flx42** [comment]
The 404 is normal. It's a deb repository, not a website.
Try installing `apt-transport-https` and try again.

**Comment by dmzoneill** [comment]
hi please close this ticket, i believe there was an update to the ca bundle from debian repos.  seems to have fixed the issue.
