### ISSUE TITLE
Not all stable docker-ce versions are supported

### ISSUE THREAD

**Issue by mlushpenko** [NVIDIA/nvidia-docker#633]
17.03.1-ce [(2017-03-27)](https://docs.docker.com/release-notes/docker-ce/#17031-ce-2017-03-27) is a stable realease but not supported, guess it's just a typo of someone who was building the packages 

`apt-cache madison nvidia-docker2 nvidia-container-runtime | grep 17.03.1` produces nothing, but
`apt-cache madison nvidia-docker2 nvidia-container-runtime | grep 17.03.2` produces this:

```
nvidia-docker2 | 2.0.2+docker17.03.2-1 | https://nvidia.github.io/nvidia-docker/debian9/amd64  Packages
nvidia-docker2 | 2.0.1+docker17.03.2-1 | https://nvidia.github.io/nvidia-docker/debian9/amd64  Packages
nvidia-container-runtime | 1.1.1+docker17.03.2-1 | https://nvidia.github.io/nvidia-container-runtime/debian9/amd64  Packages
nvidia-container-runtime | 1.1.0+docker17.03.2-1 | https://nvidia.github.io/nvidia-container-runtime/debian9/amd64  Packages
```

and 17.03.2 is not a stable release.

Came across this when was trying to install it after intsalling kubespray which uses stable docker-ce release 17.03.1 and the error I am getting is:

```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 17.03.2~ce-0~debian-stretch) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by flx42** [comment]
https://docs.docker.com/release-notes/docker-ce/

**Comment by mlushpenko** [comment]
@flx42 would it be possible to get a build for 17.03.1?
https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages 

I am dependent on kubespray and they still use older repo and 17.03.1 is the latest there, or if you could tell me how I can do it from the source perhaps? Otherwise, I'll run into dependency/compatibility hell, thanks in advance.

**Comment by flx42** [comment]
Could kubespray be patched instead? That seems like the right thing to do.

cc @dholt who asked me the exact same question 3 days ago ;)

**Comment by mlushpenko** [comment]
It's a big project, not likely, although it does make sense and probably will happen at some point as they are behind on docker version quite a lot. If you could just tell me how I can do it myself I won't bother you much more :)

**Comment by mlushpenko** [comment]
@flx42 or perhaps adding some `Build from source` documentation to readme or wiki but 1-2 commands will do for now

**Comment by flx42** [comment]
Installing the `nvidia-container-runtime` for `17.03.2` should be just fine. Then you don't need the `nvidia-docker2` package. It's a very simple package that does two things: 1) provide a compatibility script called `nvidia-docker` 2) Register the docker runtime to the docker daemon.

You can register the new runtime yourself: https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup

**Comment by flx42** [comment]
Filed https://github.com/docker/docker.github.io/issues/5985

**Comment by mlushpenko** [comment]
thanks @flx42, I forgot to mention that docker is configured via systemd, so what I was looking for is here: https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup

With installing `nvidia-container-runtime` and adding `--add-runtime=nvidia=/usr/bin/nvidia-container-runtime` nvidia runtime is registered, but default runtime is still runc. Tried `--default-runtime` option as well, but nothing changes for now, will be testing more. Still, I guess it's a good idea to add build instructions in case someone wants to play with edge versions or so, you have some reasons not do do that? (Apart from being busy in general)

**Comment by dholt** [comment]
These are the variables I had to override to get kubespray to install docker-ce 17.03.2, which is compatible with the new NVIDIA container runtime. 

https://gist.github.com/dholt/a7917e5442d2782564da2b02bcce6318

It forces kubespray to use the newer Docker repo, which it should probably do anyway. I did not stray far from the official kubespray docker version (17.03.1) so I can't verify if newer versions will work.

**Comment by flx42** [comment]
https://github.com/docker/docker.github.io/commit/4ba34b4aecb3f35d1abda8d1a27f15179cb591af
Kubespray doesn't have any excuse now :)

**Comment by mlushpenko** [comment]
Thanks a lot @dholt, I got it working finally, installation wise. If nvidia-docker2 is installed, nvidia runtime becomes available and then ` --default-runtime=nvidia` options works for systemd. Closing the issue as 17.03.2 is already aded to stable releases thank to your issue @flx42
