### ISSUE TITLE
How to properly stop the nvidia-docker container

### ISSUE THREAD

**Issue by DaveBGld** [NVIDIA/nvidia-docker#637]
I've tried a few  ways to stop the nvidia-docker container.

**The first**, I run 

`sudo docker sd`

and then

`sudo docker stop <container id>` with the container id received from the sd command for the nvidia-docker container

This CRASHES my Ubuntu 16.04 computer

**The SECOND** method, is CTL-C or CTL-Z on the same terminal window where the nvidia-docker was ran, but then, it crashes and won't load again unless I reboot.

**A THIRD**  way I tried is

`sudo stop 'nvidia-docker'`

which results in ...

`stop: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
`

Being new to docker, I would like to see some documentation for properly and elegantly stopping an nvidia-docker container.

Thanks!!

**Comment by 3XX0** [comment]
This question is not related to `nvidia-docker` but rather how to use `docker`. I suggest you refer to the docker documentation or file an issue on [their repository](https://github.com/docker/docker-ce).
