### ISSUE TITLE
Is nvidia-docker2 required for K8S GPU?

### ISSUE THREAD

**Issue by cheyang** [NVIDIA/nvidia-docker#638]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

[k8s gpu](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) told us that we should install nvidia-docker2 for k8s GPU scheduler. But I think we only need to install nvidia-container-runtime, then configure /etc/docker/daemon.json. So my question is if nvidia-docker2 requires for K8s GPU scheduler. Thanks.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by cheyang** [comment]
@flx42 Can you help me to understand? Thanks.

**Comment by pineking** [comment]
nvidia-docker2 is not an essential step in k8s.

**Comment by 3XX0** [comment]
Yes, or at alternatively `nvidia-container-runtime` if you configure your docker daemon manually. See https://github.com/NVIDIA/k8s-device-plugin
