### ISSUE TITLE
NVIDIA-docker support in SUSE Enterprise OS

### ISSUE THREAD

**Issue by jithum77** [NVIDIA/nvidia-docker#639]
Hello All,

Is there any support for nvidia-docker on SUSE enterprise operating system? I tried to install the nvidia-docker2, but I cannot make it successful in anyway, tried to build the source, but the dependencies need to be downloaded separately while installing the built binary. Is there any way to do this? If so, kindly somehow provide a step by step procedure to do this. 

Thanks
Jithu

**Comment by flx42** [comment]
You should look at this issue for now: https://github.com/NVIDIA/nvidia-docker/issues/657

**Comment by gsgxnet** [comment]
Thx for the workaround solution. 
Are there any plans for some official support?

**Comment by flx42** [comment]
Maybe for OpenSUSE, yes. But I don't have a timeline yet.
However, with this [commit](https://github.com/NVIDIA/nvidia-container-runtime/commit/300aaf9bd4ab955d3cf1d5a8d69f7d1ca808e62c) you will be able to use the next CentOS package by just uncommenting the `user` line in the configuration file.

**Comment by flx42** [comment]
@jithum77 It's not available yet.

**Comment by Gitwangshuo** [comment]
it's already avaliable for suse12sp2 ?

**Comment by RenaudWasTaken** [comment]
This should be done now!

**Comment by FollonSaxBass** [comment]
Hi @RenaudWasTaken, may you provide a link to a guide on how to build nvidia-docker on SLES 12.4? I cannot manage to have it working on my instance with SLES 12.4 (yes, I'm obliged to use SLES).
Thank you in advance..
