### ISSUE TITLE
AWS EC2 setup

### ISSUE THREAD

**Issue by 3XX0** [NVIDIA/nvidia-docker#64]
Document the deployment of `nvidia-docker` containers on Amazon EC2.

**Comment by lsb** [comment]
This is very exciting!

We at Graphistry are working on automating our EC2 setup, and have our own attempts at https://github.com/graphistry/infrastructure . (This is a v1.) Happy to help in any way possible.

**Comment by 3XX0** [comment]
I updated the documentation: [Deploy on Amazon EC2](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2)
