### ISSUE TITLE
nvidia-docker2 depends docker-ce 17.12.0, when update to 18.02.0?

### ISSUE THREAD

**Issue by jinyu0310** [NVIDIA/nvidia-docker#641]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 17.12.0~ce-0~ubuntu) but 18.02.0~ce-0~ubuntu is to be installed or docker-ee (= 17.12.0~ee-0~ubuntu) but it is not installable

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [x] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by ghisvail** [comment]
Any news as to when the `nvidia-docker2` package will be refreshed for `docker-ce/18.02.0ce-0`?

**Comment by 3XX0** [comment]
`18.02` will not be supported as this is an edge release. See [here](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#which-docker-packages-are-supported).

**Comment by ghisvail** [comment]
> 18.02 will not be supported as this is an edge release

@3XX0 So the following [instructions](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2) are completely useless then? `docker-machines` creates instances with the `edge` repository be default, not `stable`, AFAIK.

Thoughts?

**Comment by 3XX0** [comment]
Yes, we need to update this (see the first line ;)) In the meantime you can use the following resources:

https://www.youtube.com/watch?v=1-NCTRKPfnw
http://docs.nvidia.com/ngc/ngc-aws-setup-guide/index.html
