### ISSUE TITLE
RHEL7.4 nvidia-container-cli: initialization error: driver error: timed out

### ISSUE THREAD

**Issue by Spydernaz** [NVIDIA/nvidia-docker#644]
Hi,

I was trying to get nvidia-docker to work when there were 4 GPU's installed. We are running this out of azure. nvidia-smi works on the desktop but when running from a container I am getting errors I saw previously that the nvidia-persistenced service seemed to resolve it, however I am still getting errors. Below is a dump. Running RHEL 7.4.

[root@HOST~]# nvidia-smi
Mon Feb 26 11:27:06 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00001128:00:00.0 Off |                    0 |
| N/A   41C    P0    70W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000B183:00:00.0 Off |                    0 |
| N/A   43C    P0    72W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000CCBF:00:00.0 Off |                    0 |
| N/A   48C    P0    55W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000F470:00:00.0 Off |                    0 |
| N/A   45C    P0    59W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[root@HOST~]# nvidia-docker run -it $DOCKER/nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=8244 /var/lib/docker/overlay2/5cde08538d0dbf11908813473366169b1003233bd434c135d83ae9299262e280/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.
[root@HOST~]# nvidia-persistenced
[root@HOST~]# nvidia-docker run -it $DOCKER/nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=8880 /var/lib/docker/overlay2/5176c2646995d12f6b9a519d27da215267c4dfa6bbe7a445863c59cf4336698d/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.

**Comment by flx42** [comment]
Check https://github.com/NVIDIA/nvidia-docker/issues/628

**Comment by Spydernaz** [comment]
Hi @flx42, I am already running the nvidia-persistenced.service (with the --persistence-mode argument)

**Comment by flx42** [comment]
Check the third column of nvidia-smi. Persistence mode is reported as "Off"
for each GPU.

Make sure the persistenced service is running and check its logs.

**Comment by Spydernaz** [comment]
Hi @flx42 , Sorry for the delay, I am still getting the error even though the GPU is running in Persistence Mode. This being said, after I run ```nvidia-persistenced``` I get:
```
[root@HOST~]# systemctl status nvidia-persistenced.service
● nvidia-persistenced.service - NVIDIA Persistence Daemon
   Loaded: loaded (/usr/lib/systemd/system/nvidia-persistenced.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Mar 02 13:17:36 gldyndaplua7d07 nvidia-persistenced[120278]: Started (120278)
Mar 02 13:17:36 gldyndaplua7d07 systemd[1]: Started NVIDIA Persistence Daemon.
Mar 02 13:20:46 gldyndaplua7d07 systemd[1]: Stopping NVIDIA Persistence Daemon...
Mar 02 13:20:49 gldyndaplua7d07 systemd[1]: Stopped NVIDIA Persistence Daemon.
Mar 02 13:24:30 gldyndaplua7d07 systemd[1]: Starting NVIDIA Persistence Daemon...
Mar 02 13:24:30 gldyndaplua7d07 systemd[1]: Started NVIDIA Persistence Daemon.
Mar 02 13:54:25 gldyndaplua7d07 systemd[1]: Starting NVIDIA Persistence Daemon...
Mar 02 13:54:25 gldyndaplua7d07 systemd[1]: Started NVIDIA Persistence Daemon.
Mar 02 13:54:49 gldyndaplua7d07 systemd[1]: Starting NVIDIA Persistence Daemon...
Mar 02 13:54:49 gldyndaplua7d07 systemd[1]: Started NVIDIA Persistence Daemon.
```

Below is what I did to reproduce the error in persistence mode.

```
[root@HOST~]# nvidia-docker run -it $DOCKER/nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=124902 /var/lib/docker/overlay2/ed0a23577c1203f6908b7bc05df7497a099f4477be0767eac6fdfa320295e5c5/merged]\\\\nnvidia-container-cli: initialization error: cuda error: initialization error\\\\n\\\"\"": unknown.
[root@HOST~]# nvidia-smi
Fri Mar  2 13:51:56 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000000B:00:00.0 Off |                    2 |
| N/A   34C    P8    34W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00001607:00:00.0 Off |                    0 |
| N/A   40C    P8    26W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00003931:00:00.0 Off |                    0 |
| N/A   38C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00005701:00:00.0 Off |                    0 |
| N/A   32C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[root@HOST~]#
```

Thanks

**Comment by 3XX0** [comment]
Your error is different than the original one (`cuda error: initialization error`)
This is most likely a driver installation issue, check that your driver is installed and works properly

**Comment by flx42** [comment]
@Spydernaz do you still have a problem? Anything interesting in `dmesg`? Try using a different driver, like `384`.

**Comment by Spydernaz** [comment]
Hi guys, yes I do, but I believe I found the issue. It looks like Azure was provisioning us a RHEL7.5 image. There is no support from NVIDIA nor Microsoft (no LIS either). Closing issue, apologies for the delay
