### ISSUE TITLE
Compatibility with hidepid procfs mount option

### ISSUE THREAD

**Issue by maleadt** [NVIDIA/nvidia-docker#645]
### 1. Issue description

The `nvidia-docker` infrastructure peeks through `procfs` while setting-up the container, which seems incompatible with the `hidepid` mount option (despite me being part of the whitelisted groups that _can_ access `procfs`).

### 2. Steps to reproduce the issue

Mount `procfs` with `hidepid` enabled and the current user being part of the allowed groups. For example:

```
$ mount | grep "/proc "
proc on /proc type proc (rw,relatime,gid=4,hidepid=2)
$ groups
adm
$ grep adm /etc/group
adm:x:4:...
```

Start a container:

```
$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=4629 /var/lib/docker/btrfs/subvolumes/206c028792aa58ccf3c6ade1b5b750d1f05752d30d964ef36f47140dec6ab9f2]\\\\nnvidia-container-cli: container error: stat failed: /proc/4629: no such file or directory\\\\n\\\"\"": unknown.
```

Disabling `hidepid` fixes the issue.

Running on Debian Stretch, with nvidia-docker 2.0.2 on docker 17.12.0.

**Comment by 3XX0** [comment]
I believe this is fixed in the latest release, feel free to reopen if it's not the case.
