### ISSUE TITLE
Want to run OpenGL apps in conatiner; VirtualGL doesn't work anymore.

### ISSUE THREAD

**Issue by jwatte** [NVIDIA/nvidia-docker#646]
Using the current nvidia-docker2 on Ubuntu 17.10 with docker-ce 17, I'd like to run GL applications from within the container.
I can run CUDA applications using the `nvidia/cuda` base container, and `nvidia-smi` returns card status.
I can also run general-purpose X applications inside a container by forwarding the X socket, which is helpful for extracting/running the Jetson Jetpack installer, for example.
However, I cannot run OpenGL applications using VirtualGL -- it seems to not work in nvidia-docker2.
Given that I have a number of data processing tools that use both OpenGL and CUDA, that I'd like to have a consistent container runtime environment for, this is a real problem for me.

It'd be super useful if you could make "running OpenGL applications" a first-class supported feature for nvidia-docker2.

**Comment by flx42** [comment]
It is supported now, you need to use our OpenGL base images: https://hub.docker.com/r/nvidia/opengl/

We also have some samples on GitLab, for instance: https://gitlab.com/nvidia/samples/blob/master/opengl/ubuntu16.04/turbovnc-virtualgl/Dockerfile

**Comment by jwatte** [comment]
I checked it out, and saw this:
"Display (e.g. X11, Wayland) is not officially supported.
GPU isolation requires driver 390+."

I need display, and the latest available release driver is 384...

**Comment by flx42** [comment]
Not officially supported doesn't mean it's impossible :)
It means, you are on your own. But really it's an open secret, you can very easily find how to expose the host X server. We even document that in our samples now.

> I need display, and the latest available release driver is 384...

No, the latest driver is `390.30` on our package repository:
http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/
And that's only if you need *GPU isolation* for EGL (e.g. if you want to run 4 EGL containers, each one having access to only one GPU).

**Comment by jwatte** [comment]
Alright, I'll have a poke-around. Thanks!
