### ISSUE TITLE
Support latest docker-ce on Debian stretch

### ISSUE THREAD

**Issue by davidwessman** [NVIDIA/nvidia-docker#647]
### 1. Issue or feature description
Upgraded to `docker-ce 17.12.1~ce~debian` and `nvidia-docker2` is pinned to `docker-ce 17.12.0~ce~debian` in this [Makefile](https://github.com/NVIDIA/nvidia-docker/blob/7a6370d39f8f57fa831772d5eaa19eb7dbb4b427/Makefile#L152). 

I can therefore not install `nvidia-docker2` without downgrading `docker-ce` as far as I can see.

### 2. Steps to reproduce the issue

- Upgrade to latest `docker-ce` on Debian stretch.
- Try to install `nvidia-docker2` 

## Edit

I realised you fixed this 4 hours ago... ;) 
When will the release be available?

**Comment by flx42** [comment]
The new packages should be released today (PST), just waiting to test one more thing with @3XX0

**Comment by Fish2** [comment]
Any news on the release wondering if i should downgrade my docker ?

**Comment by flx42** [comment]
@Fish2 sorry, pushed back to Thursday or Friday.

**Comment by Fish2** [comment]
@flx42 ok thanks for letting me know

**Comment by ghisvail** [comment]
Same here for the Ubuntu packages. Is there a particular reason why `nvidia-docker` has to be pinned at a specific Docker version. Version `17.12.1` does not feature that much changes compared to `17.12.0`.

**Comment by alexwitherspoon** [comment]
Any updates on the release? Thanks!

**Comment by flx42** [comment]
Done @alexwitherspoon, please try

**Comment by alexwitherspoon** [comment]
Confirmed working on Debian thanks @flx42 !

`root@core:~# nvidia-docker version
NVIDIA Docker: 2.0.3
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:21 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:15:56 2018
  OS/Arch:      linux/amd64
  Experimental: false`

`root@core:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
root@core:~# uname -a
Linux <hostname> 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux`

**Comment by Fish2** [comment]
This is back again with the new release of docker-ce

**Comment by flx42** [comment]
@Fish2 what are you seeing? I've released packages this morning

**Comment by flx42** [comment]
@Fish2 ok! thanks for confirming
