### ISSUE TITLE
nvidia-docker2 package for ppc64le

### ISSUE THREAD

**Issue by takmatsu** [NVIDIA/nvidia-docker#651]
I know nvidia-docker 1.0 is deprecated.
But nvidia-docker repository doesn't include nvidia-docker2.0 package for Power architecture.
And libnvidia-container, nvidia-container-runtime too.

I build them by own and it worked. But This is not convenient.

**Comment by flx42** [comment]
Sorry about that, it's on our list of things to do. But with GTC preparation, we have a long list.

**Comment by geoffrey-pascal** [comment]
would be useful. it's a pain to build it manually

**Comment by flx42** [comment]
Done, you can use the instructions on the README, it will also work for ppc64le.
Look at the FAQ for more details: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#do-you-support-powerpc64-ppc64

**Comment by geoffrey-pascal** [comment]
Thank you! Is it possible to have a package for Redhat ?
