### ISSUE TITLE
Enable driver in container on hosts with no GPU

### ISSUE THREAD

**Issue by flawaetz** [NVIDIA/nvidia-docker#653]
Curently nvidia-docker2 will not pass through the CUDA drivers to a container if the host machine does not have a GPU present.  This is true even if one sets `NVIDIA_VISIBLE_DEVICES=none` which, according to the docs, should result in "no GPU will be accessible, but driver capabilities will be enabled."

Without a GPU present the launch fails with error:
```
## docker run -e "NVIDIA_VISIBLE_DEVICES=none"  myhub/myImage:latest
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:345: container init caused \"process_linux.go:328: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --compute --utility --require=cuda>=9.0 --pid=11953 /var/lib/docker/aufs/mnt/dea150c020762a4599b2a22993d83a40ff84b619074a571605235c046c9c7bbe]\\\\nnvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"".
```

I think this is the same error as was reported here: https://github.com/NVIDIA/k8s-device-plugin/issues/17

The advice in that issue is to simply not install the driver on hosts without a GPU.  There are use cases, however, where having CUDA drivers present but no GPU would be helpful.  

`tensorflow-gpu` for example, will work without a GPU so long as CUDA is there.   Having just one image work on both GPU and non-GPU systems is desirable.

Could `NVIDIA_VISIBLE_DEVICES=none` be extended to support driver pass-through in the absence of an actual GPU?  Or perhaps an additional mode could be made?

**Comment by flx42** [comment]
Not sure what you are trying to do here.

> tensorflow-gpu for example, will work without a GPU so long as CUDA is there. Having just one image work on both GPU and non-GPU systems is desirable.

This seems like a problem with TF itself, if they don't have proper fallback.

**Comment by flawaetz** [comment]
I'm fundamentally trying to have monolithic docker images that support GPU and non-GPU environments with a static set of libraries available.  

It's already possible to install CUDA without a GPU present.  And `nvidia-docker2` will pass through drivers to a container without making a GPU available (`NVIDIA_VISIBLE_DEVICES=none`).   The desired functionality to expose drivers without a GPU on the host seems consistent with these capabilities.

My alternative is to either embed CUDA in the image or bind mount certain CUDA libraries from the host.  Both options introduce headaches that originally got me using `nvidia-docker`.

**Comment by flx42** [comment]
It seems like you have the same questions as in #652, so I'll close this one since you opened it 4 minutes later :)
