### ISSUE TITLE
Debian buster: nnvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 1

### ISSUE THREAD

**Issue by tobycheese** [NVIDIA/nvidia-docker#660]
### 1. Issue or feature description
`docker run --runtime=nvidia --rm  nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 nvidia-smi `

results in

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=2004 /var/lib/docker/overlay2/0765a24c941dbb710987be1a3ac397bc09cbfeac26c2d1f8f91f1434f91e0af2/merged]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 1\\\\n\\\"\"": unknown.`

### 2. Steps to reproduce the issue
I installed on Debian buster, but adding the repo for stretch. Is this bound to fail? nvidia-docker1 was working just fine. Do I need to downgrade, or is buster support here soon?

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Kernel version: Linux epsilon 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux
 - [x] Driver information from `nvidia-smi -a`: 390.25
 - [x] Docker version from `docker version`: 17.12.1-ce
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 - [x] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

[nvidia-packages.txt](https://github.com/NVIDIA/nvidia-docker/files/1798666/nvidia-packages.txt)
[nvidia-container-library-version.txt](https://github.com/NVIDIA/nvidia-docker/files/1798667/nvidia-container-library-version.txt)
[nvidia-container-runtime-hook.log](https://github.com/NVIDIA/nvidia-docker/files/1798671/nvidia-container-runtime-hook.log)

**Comment by flx42** [comment]
I have a fix for this, will test

**Comment by flx42** [comment]
Issue was fixed in https://github.com/NVIDIA/libnvidia-container/commit/cef6c8f1ede04d65e753c288eec19d4af9b1f16c, but it's not releases as a package yet.
You will need to `make && make install` the project from sources, or better `make deb` and `dpkg -i dist/libnvidia-container1[...]`

**Comment by tobycheese** [comment]
Thanks for the quick fix! I tried building from source but it fails due to not finding cuda.h. I have not installed cuda on my host, that's what I am using containers for. I couldn't quickly figure out how to install cuda on debian, the .run files from nvidia don't list ubuntu, and apt-get install nvidia-cuda-toolkit wants to install 256 packages, which I am not going to do on my host. I also tried building inside a docker container, but either I can't install cuda or can't get gcc-7 (what the host uses).

Guess I'll downgrade to nvidia-docker1 and wait for an updated package, which is something I can live with :-) Thanks again!

**Comment by flx42** [comment]
Ah, sorry.
Try "make docker-debian", if I'm not mistaken.

**Comment by OrBin** [comment]
@flx42 When will the fix be released?

**Comment by Trophime** [comment]
Hi, trying to rebuild from scratch with `make docker-ubuntu18.04` fails:
```
dpkg-deb: error: parsing file 'debian/nvidia-docker2/DEBIAN/control' near line 6 package 'nvidia-docker2':
 'Depends' field, reference to 'docker-ce': error in version: version number does not start with digit
dh_builddeb: dpkg-deb --build debian/nvidia-docker2 .. returned exit code 2
dh_builddeb: Aborting due to earlier error
debian/rules:7: recipe for target 'binary' failed
make: *** [binary] Error 2
```

same for debian flavor...
