### ISSUE TITLE
docker cuda Package Hash Sum mismatch

### ISSUE THREAD

**Issue by selsius** [NVIDIA/nvidia-docker#664]
Same issue as #658 

FROM gcr.io/tensorflow/tensorflow:1.5.0-gpu
RUN apt-get update

Gives this error:
[...]
Err:12 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
  Hash Sum mismatch
[...]
W: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: The repository 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release' is not signed.
E: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

using other tensorflow versions or adding rm -rf /var/lib/apt/lists/* to the Dockerfile does not help either.

**Comment by flx42** [comment]
It seems that this is often a transient issue, not under my control, unfortunately.
Do you still see the problem @selsius?

**Comment by selsius** [comment]
Hi @flx42, I just checked and it passes new.

**Comment by lnshi** [comment]
@flx42 it is happening again...

**Comment by ArvinSiChuan** [comment]
@flx42 Please ask for a CDN clear since it happens again in my region China, Shanghai.

**Comment by flx42** [comment]
@ArvinSiChuan try switching your repository to https and see if it fixes the issue.

**Comment by ArvinSiChuan** [comment]
@flx42 I'm already using https but it still happens. The logs are:  
```shell
Err:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
  Hash Sum mismatch
Get:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages [24.6 kB]
Fetched 140 kB in 4s (28.6 kB/s)
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
W: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release' is not signed.
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
```

**Comment by carusyte** [comment]
Encountering the same issue, too. Retried many times with no luck. Sorry for any inconvenience when I bumped this issue.
