### ISSUE TITLE
NVIDIA docker on windows?

### ISSUE THREAD

**Issue by redBirdTx** [NVIDIA/nvidia-docker#665]
Hi,

Not really any issues but a question  on OS. From past thread I read that NVIDIA docker is not for windows. Is it still the case now?

Thanks

best regards

**Comment by 3XX0** [comment]
Yes see https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported

**Comment by IoTFier** [comment]
What's the reason to not to support Windows? Many of us have Windows laptop with dedicated NVIDIA GPUs such as GTX 1060. Having your support will be very valuable.

Please reconsider in supporting windows as well instead of routing us thru work arounds.

Thanks,

**Comment by chenzhekl** [comment]
@IoTFier Because there is no GPU passthrough in Hyper-V on Windows 10 Pro, I guess.

**Comment by dims12** [comment]
Incredible.

**Comment by franjesus** [comment]
It would be useful still to have a devel image.

**Comment by ihexx** [comment]
With process isolation being released for windows containers on windows 10, are there any plans to change this, and have GPU-enabled windows containers?

**Comment by timotei** [comment]
@ihexx I think the issue here is not necessarily the process isolation, but rather GPU passthrough, since you'd need to be able to share the GPU somehow to the docker container. Also, it needs that 'nvidia' docker runtime, but haven't looked into details. 

Also, there are two docker variants on Windows: Docker via HyperV Linux VM (where you'd 100% need GPU passthrough) and natively. For the native part I think we need the proper driver to be compiled for windows - but I can't see/find the source code for that to even try :(

PS: some possibly related topic on the internets w/r/t the GPU Passthrough for the Hyper-V variant of docker. Haven't managed to try them myself yet though.

https://social.technet.microsoft.com/Forums/en-US/96a52f97-dc8c-48ae-8a99-2bfdbc05c526/gpu-pass-through-on-windows-10-hyperv?forum=win10itprovirt
https://www.reddit.com/r/HyperV/comments/8jwt5c/windows_10_hyperv_dda/

**Comment by marcoValkyriweb** [comment]
Hi, 

would this have any impact: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/gpu-acceleration

Though it requires that it must be a windows container and not a Linux one. According to: https://github.com/NVIDIA/nvidia-docker/issues/429 there is no GPU access in WSLv2, so can't attempt it with that either.

**Comment by FlamesoFF** [comment]
> Yes see https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported

99% nvida users on Windows

> No, we do not support Microsoft Windows

WTF?

**Comment by maximveksler** [comment]
I prefer nvidia to focus narrow and ship the best GPU support on linux then wide and attempt to hit Linux & Windows but releasing slower or buggier.

**Comment by rarvikar** [comment]
Can you please explain what do you exactly mean when you say "GPU passthrough is not available on Hyper-V" in Windows ?

"Passthrough mode", supported by Microsoft Hyper-V (and also Citrix XenServer and VMware ESX) simply hands off the entire GPU to the hypervisor for the benefit of one VM. However, no carving or segmentation is possible (which is what NVidia's vGPU feature does).

So considering that 90% of your customer base uses Windows are there any plans of adding support albeit one that conforms to Microsoft's "Passthrough Mode" to hand-off the entire GPU to the Hyper-V VM that hosts Docker containers ?
TIA !

**Comment by Pit-Storm** [comment]
I would although appriciate this feature for windows. But I know, that nearly 100% of servers (which this in most cases ist used for) are running linux. So this will not happen in near future...

**Comment by gedoensmax** [comment]
@Pit-Storm unexpected things happening ;) https://devblogs.microsoft.com/directx/directx-heart-linux/

**Comment by IoTFier** [comment]
> @Pit-Storm unexpected things happening ;) https://devblogs.microsoft.com/directx/directx-heart-linux/

@gedoensmax - yes - I am not sure when that change will hit Surface Book 2 with dGPU ?

**Comment by NicTanghe** [comment]
Ok but how does this help us ?
with us i mean users that are forced to use windows because of reasons and things.

**Comment by ShuyaoGu** [comment]
Would a Linux Virtual Machine inside Windows 10 make NVIDIA docker working?

**Comment by nvjmayo** [comment]
see also https://developer.nvidia.com/cuda/wsl

**Comment by 78Alpha** [comment]
Was currently installing this and the runtime on WSL 2, it worked out up until I tried to download the Nvidia docker, GitHub apparently had a server issue and a good 20%? Of repositories couldn't be accessed, so I couldn't download the other half... However, docker and the runtime installed fine. The driver works and all. So it's possible, in every way, it's just simply a choice of support. Either by Nvidia or the community.

**Comment by PhearZero** [comment]
For anyone still digging this helps a lot! It's apparently in the pipeline and you need the latest Windows builds, Just verified TensorFlow in docker. Cheers!

https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-wip
