### ISSUE TITLE
Publish Images Based on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cancan101** [NVIDIA/nvidia-docker#666]
This is a ticket to start tracking building images based on Ubuntu 18.04 LTS.

### 1. Issue or feature description

It looks like 18.04 (official) docker images are being published: https://hub.docker.com/r/library/ubuntu/ so it should be possible to start building and testing against them.

**Comment by dwSun** [comment]
good

**Comment by flx42** [comment]
It's still too early on our side, but this should happen at the end of the month.

**Comment by pisymbol** [comment]
Please, I depend on this. NVidia's lack of support of 17.10 has really hurt (I've had to use 17.04 docker images up until now since the nvidia-XXX drivers have completely diverged).

**Comment by dwSun** [comment]
any update？
when will cuda support 18.04 officially?

**Comment by flx42** [comment]
Bad news, it won't happen this week.  The release of CUDA 9.2 has been delayed so we can't get 18.04 images yet. CUDA 9.1 is not compatible with 18.04.

**Comment by pisymbol** [comment]
That sucks. Got an ETA though? A month? Three months? etc.

**Comment by mns6070** [comment]
@flx42 Are we still on track for delivery this week?

**Comment by flx42** [comment]
@dwSun this won't work with gcc 7.3.0 (shipped with bionic), you are limited to clang 3.X if I remember correctly.

**Comment by tycho01** [comment]
fwiw following @dwSun's instructions I get as far as installing all that then nvidia-docker (using readme instructions), but get a cuda error trying to run the actual readme example.

**Comment by dwSun** [comment]
Sorry for lack of details.
Tested with [TensorFlow 1.5 (GPU, CUDA 9.1, Generic)](https://github.com/mind/wheels/releases/download/tf1.5-gpu-generic/tensorflow-1.5.0-cp36-cp36m-linux_x86_64.whl) from tinymind. And mxnet-cu91mkl-1.1.0 from pypi. Running directly on host.

CPP examples which need be built are **NOT** tested, on host or inside nvidia-docker.

nvidia-docker can be installed, without cuda on host. I am using nvidia/cuda:9.1-cudnn7-runtime. this image based on ubuntu:16.04.
nvidia-smi inside nvidia-docker works as expected. But mxnet-cu91mkl-1.1.0 inside nvidia-docker stuck at image preprocessing.

**Comment by flx42** [comment]
> nvidia-docker can be installed, without cuda on host. I am using nvidia/cuda:9.1-cudnn7-runtime. this image based on ubuntu:16.04.

Yeah, that's the benefit of containers, you can still run ubuntu 16.04/14.04 or CentOS 6/7 containers on a Ubuntu 18.04 host, even if Ubuntu 18.04 doesn't have an official CUDA release right now.
This is not new :)

> But mxnet-cu91mkl-1.1.0 inside nvidia-docker stuck at image preprocessing.

This is probably unrelated.

**Comment by Titaniumtown** [comment]
I have cuda 9.2

**Comment by yf225** [comment]
@flx42 Will CUDA 9.2 be supporting Ubuntu 18.04? It doesn't seem to be on the OS version list: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu

**Comment by flx42** [comment]
It will be experimental support, using the ubuntu 17.10 repository.

**Comment by flx42** [comment]
Experimental images are out!

## CUDA 9.2 (EXPERIMENTAL)
- [`9.2-base-ubuntu18.04` (*9.2/base/Dockerfile*)](https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/base/Dockerfile)
- [`9.2-runtime-ubuntu18.04` (*9.2/runtime/Dockerfile*)](https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/runtime/Dockerfile)
- [`9.2-devel-ubuntu18.04` (*9.2/devel/Dockerfile*)](https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/devel/Dockerfile)
- [`9.2-cudnn7-runtime-ubuntu18.04` (*9.2/runtime/cudnn7/Dockerfile*)](https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/runtime/cudnn7/Dockerfile)
- [`9.2-cudnn7-devel-ubuntu18.04` (*9.2/devel/cudnn7/Dockerfile*)](https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/devel/cudnn7/Dockerfile)

**Comment by cancan101** [comment]
Any plans to have an 18.04 deb repos? Right now it looks like the Dockerfile uses the 1710: https://gitlab.com/nvidia/cuda/blob/ubuntu18.04/9.2/base/Dockerfile#L7
repos list: http://developer.download.nvidia.com/compute/cuda/repos/

**Comment by flx42** [comment]
Ubuntu 18.04 will get its deb repo for the next CUDA release: 10.0
I don't know when that will be.

Let me know if there is any problem with the current image.

**Comment by sursu** [comment]
Why is it that every time Ubuntu gets updated I cannot just start using the latest version of CUDA on it. Or vice-versa.
Do the dependencies really change so much?

I imagine that the updates need to go through some tests. If there are changes in functionalities, naming they need to be examined and addressed.
Does testing take that much time?

Or, to put it differently: what does "EXPERIMENTAL" mean? What are the caveats?

**Comment by tycho01** [comment]
@sursu have you had issues with it? I went through the readme instructions and successfully ran its test.

**Comment by sursu** [comment]
I'll have to install Ubuntu first in my machine with NVIDIA GPU, which I thought I'll postpone untill 18.04 supports CUDA 9.2.

The rest was just a curiosity.

**Comment by mrjj** [comment]
@dwSun 
> For those who speak chinese,
Chinese bash is wonderfully readable :) Thank you, helped a lot!
