### ISSUE TITLE
 THCudaCheck FAIL file=/root/torch-distro/extra/cutorch/lib/THC/THCGeneral.c line=70 error=35 : CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by mdasadul** [NVIDIA/nvidia-docker#668]
nvidia-smi

Wed Mar 14 15:49:53 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   48C    P0    76W / 149W |      0MiB / 11439MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

My docker instance is based on nvidia/cuda:8.0-runtime-ubuntu16.04

Any help will be appriciated

**Comment by flx42** [comment]
What's your Dockerfile? If you can share it.

**Comment by flx42** [comment]
IIRC, some torch packages will ship the CUDA toolkit libraries, so you might end up with libraries from CUDA 9.0, even if your base image is CUDA 8.0

**Comment by mdasadul** [comment]
My docker file is based on this file 
https://github.com/OpenNMT/OpenNMT/blob/master/Dockerfile

**Comment by flx42** [comment]
Was this `nvidia-smi` inside the container? If not, did you try inside the container?

**Comment by mdasadul** [comment]
Its same as above inside the container 
root@591961b12fcf:~/opennmt# nvidia-smi
Wed Mar 14 18:16:16 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   46C    P0    75W / 149W |      0MiB / 11439MiB |     83%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by flx42** [comment]
Hmmm, OK. And what's the output of `ldconfig -p | grep -E 'libcuda|libnvidia'` on the host?

**Comment by mdasadul** [comment]
Here is the output when I use the above mentioned command on host 
 libnvidia-wfb.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-wfb.so.1
        libnvidia-wfb.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-wfb.so.1
        libnvidia-tls.so.384.111 (libc6,x86-64, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
        libnvidia-tls.so.384.111 (libc6,x86-64, OS ABI: Linux 2.2.5) => /usr/lib/nvidia-384/libnvidia-tls.so.384.111
        libnvidia-tls.so.384.111 (libc6, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /usr/lib32/nvidia-384/tls/libnvidia-tls.so.384.111
        libnvidia-tls.so.384.111 (libc6, OS ABI: Linux 2.2.5) => /usr/lib32/nvidia-384/libnvidia-tls.so.384.111
        libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ptxjitcompiler.so.1
        libnvidia-ptxjitcompiler.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ptxjitcompiler.so.1
        libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
        libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so.1
        libnvidia-ml.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so.1
        libnvidia-ml.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so
        libnvidia-ml.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so
        libnvidia-ifr.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ifr.so.1
        libnvidia-ifr.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ifr.so.1
        libnvidia-ifr.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ifr.so
        libnvidia-ifr.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ifr.so
        libnvidia-gtk3.so.390.25 (libc6,x86-64) => /usr/lib/libnvidia-gtk3.so.390.25
        libnvidia-gtk2.so.390.25 (libc6,x86-64) => /usr/lib/libnvidia-gtk2.so.390.25
        libnvidia-glsi.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-glsi.so.384.111
        libnvidia-glsi.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-glsi.so.384.111
        libnvidia-glcore.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
        libnvidia-glcore.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-glcore.so.384.111
        libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fbc.so.1
        libnvidia-fbc.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-fbc.so.1
        libnvidia-fbc.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fbc.so
        libnvidia-fbc.so (libc6) => /usr/lib32/nvidia-384/libnvidia-fbc.so
        libnvidia-fatbinaryloader.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.111
        libnvidia-fatbinaryloader.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-fatbinaryloader.so.384.111
        libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-encode.so.1
        libnvidia-encode.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-encode.so.1
        libnvidia-encode.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-encode.so
        libnvidia-encode.so (libc6) => /usr/lib32/nvidia-384/libnvidia-encode.so
        libnvidia-eglcore.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-eglcore.so.384.111
        libnvidia-eglcore.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-eglcore.so.384.111
        libnvidia-egl-wayland.so.1.0.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-egl-wayland.so.1.0.1
        libnvidia-egl-wayland.so.1.0.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-egl-wayland.so.1.0.1
        libnvidia-container.so.1 (libc6,x86-64, OS ABI: Linux 3.10.0) => /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1
        libnvidia-compiler.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-compiler.so.384.111
        libnvidia-compiler.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-compiler.so.384.111
        libnvidia-compiler.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-compiler.so
        libnvidia-compiler.so (libc6) => /usr/lib32/nvidia-384/libnvidia-compiler.so
        libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-cfg.so.1
        libnvidia-cfg.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-cfg.so.1
        libnvidia-cfg.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-cfg.so
        libnvidia-cfg.so (libc6) => /usr/lib32/nvidia-384/libnvidia-cfg.so
        libcudart.so.8.0 (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0
        libcudart.so (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so
        libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
        libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so

**Comment by flx42** [comment]
it's probalby an issue with your docker image itself.
Try a CUDA sample inside the same base image, and tell me if it works.

**Comment by flx42** [comment]
No update, closing. Re-open if you have more information to share.
