### ISSUE TITLE
Is it possible to update cuda-8.0 to cuda-9.0 inside a container without restart it?

### ISSUE THREAD

**Issue by kohillyang** [NVIDIA/nvidia-docker#669]
I have made an image based on Cuda-8.0-devel, now I want to use cuda-9.0 instead but I don't want to reinstall software in that image, can I just update cuda to cuda-9.0?

**Comment by flx42** [comment]
Sure you can, they come from the same package repository. The packages have similar names, e.g. `cuda-cublas-8-0` -> `cuda-cublas-9-0`.
But it's not recommended, it will really bloat your container image.

**Comment by kohillyang** [comment]
Thanks a lot. I failed when I try to install by `apt install cuda-9.0`, while it works well if I use `apt install cuda-cublas-9-0` instead.

**Comment by flx42** [comment]
The `cuda-9-0` meta-package will try to install the driver.
You should use our official CUDA 9.0 images from DockerHub, or look at our Dockerfiles:
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/runtime/Dockerfile
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/devel/Dockerfile
