### ISSUE TITLE
file /etc/docker/daemon.json from install of nvidia-docker2-2.0.2-1.docker1.12.6.noarch conflicts with file from package docker-2:1.12.6-71.git3e8e77d.el7.x86_64

### ISSUE THREAD

**Issue by wangshuaizs** [NVIDIA/nvidia-docker#670]
When I tried to install nvidia-docker 2 on Centos 7.4, something went wrong "Transaction check error:
  file /etc/docker/daemon.json from install of nvidia-docker2-2.0.2-1.docker1.12.6.noarch conflicts with file from package docker-2:1.12.6-71.git3e8e77d.el7.x86_64".
I have tried the solution mentioned in #640, and luckily it worked, i can run tensorflow with GPU in docker. But what puzzles me is that I need to use NVIDIA GPU device plugin in Kubernetes (https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/), in which nvidia-docker 2 is needed as prerequisites. I wonder if the bug has been solved. If not, how can i use NVIDIA GPU device plugin in Kubernetes.

Thank you!

**Comment by pineking** [comment]
see https://github.com/NVIDIA/k8s-device-plugin#quick-start
For kubernetes, nvidia-docker2 is not required, if you have installed nvidia-container-runtime and setup it correctly.

**Comment by flx42** [comment]
Yes, I still think the `docker` package from Red Hat needs fixing...
