### ISSUE TITLE
Missing some nvidia/cuda libs in container

### ISSUE THREAD

**Issue by turengege** [NVIDIA/nvidia-docker#671]
I followed README.md. Everything seems fine but some libs are missing in the container.

- docker: 17.06.2-ce-2
- nvidia-docker2
- OS: CentOS 7.4 Linux 3.10.0-693.2.2.el7.x86_64

output of `ldconfig -p | grep -E 'libcuda|libnvidia'  |wc -l` :  
in container 
```	
        libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-ptxjitcompiler.so.1
	libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-opencl.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-ml.so.1
	libnvidia-fatbinaryloader.so.384.111 (libc6,x86-64) => /usr/lib64/libnvidia-fatbinaryloader.so.384.111
	libnvidia-compiler.so.384.111 (libc6,x86-64) => /usr/lib64/libnvidia-compiler.so.384.111
	libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-cfg.so.1
	libcudart.so.8.0 (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0
	libcudart.so (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so
	libcuda.so.1 (libc6,x86-64) => /usr/lib64/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib64/libcuda.so
```
in host
```
	libnvidia-tls.so.384.111 (libc6,x86-64, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /lib64/tls/libnvidia-tls.so.384.111
	libnvidia-tls.so.384.111 (libc6,x86-64, OS ABI: Linux 2.2.5) => /lib64/libnvidia-tls.so.384.111
	libnvidia-tls.so.384.111 (libc6, OS ABI: Linux 2.2.5) => /lib/libnvidia-tls.so.384.111
	libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /lib64/libnvidia-ptxjitcompiler.so.1
	libnvidia-ptxjitcompiler.so.1 (libc6) => /lib/libnvidia-ptxjitcompiler.so.1
	libnvidia-ptxjitcompiler.so (libc6,x86-64) => /lib64/libnvidia-ptxjitcompiler.so
	libnvidia-ptxjitcompiler.so (libc6) => /lib/libnvidia-ptxjitcompiler.so
	libnvidia-opencl.so.1 (libc6,x86-64) => /lib64/libnvidia-opencl.so.1
	libnvidia-opencl.so.1 (libc6) => /lib/libnvidia-opencl.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /lib64/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /lib/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /lib64/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /lib/libnvidia-ml.so
	libnvidia-ifr.so.1 (libc6,x86-64) => /lib64/libnvidia-ifr.so.1
	libnvidia-ifr.so.1 (libc6) => /lib/libnvidia-ifr.so.1
	libnvidia-ifr.so (libc6,x86-64) => /lib64/libnvidia-ifr.so
	libnvidia-ifr.so (libc6) => /lib/libnvidia-ifr.so
	libnvidia-gtk3.so.384.111 (libc6,x86-64) => /lib64/libnvidia-gtk3.so.384.111
	libnvidia-gtk2.so.384.111 (libc6,x86-64) => /lib64/libnvidia-gtk2.so.384.111
	libnvidia-glsi.so.384.111 (libc6,x86-64) => /lib64/libnvidia-glsi.so.384.111
	libnvidia-glsi.so.384.111 (libc6) => /lib/libnvidia-glsi.so.384.111
	libnvidia-glcore.so.384.111 (libc6,x86-64) => /lib64/libnvidia-glcore.so.384.111
	libnvidia-glcore.so.384.111 (libc6) => /lib/libnvidia-glcore.so.384.111
	libnvidia-fbc.so.1 (libc6,x86-64) => /lib64/libnvidia-fbc.so.1
	libnvidia-fbc.so.1 (libc6) => /lib/libnvidia-fbc.so.1
	libnvidia-fbc.so (libc6,x86-64) => /lib64/libnvidia-fbc.so
	libnvidia-fbc.so (libc6) => /lib/libnvidia-fbc.so
	libnvidia-fatbinaryloader.so.384.111 (libc6,x86-64) => /lib64/libnvidia-fatbinaryloader.so.384.111
	libnvidia-fatbinaryloader.so.384.111 (libc6) => /lib/libnvidia-fatbinaryloader.so.384.111
	libnvidia-encode.so.1 (libc6,x86-64) => /lib64/libnvidia-encode.so.1
	libnvidia-encode.so.1 (libc6) => /lib/libnvidia-encode.so.1
	libnvidia-encode.so (libc6,x86-64) => /lib64/libnvidia-encode.so
	libnvidia-encode.so (libc6) => /lib/libnvidia-encode.so
	libnvidia-eglcore.so.384.111 (libc6,x86-64) => /lib64/libnvidia-eglcore.so.384.111
	libnvidia-eglcore.so.384.111 (libc6) => /lib/libnvidia-eglcore.so.384.111
	libnvidia-egl-wayland.so.1.0.1 (libc6,x86-64) => /lib64/libnvidia-egl-wayland.so.1.0.1
	libnvidia-container.so.1 (libc6,x86-64, OS ABI: Linux 3.10.0) => /lib64/libnvidia-container.so.1
	libnvidia-compiler.so.384.111 (libc6,x86-64) => /lib64/libnvidia-compiler.so.384.111
	libnvidia-compiler.so.384.111 (libc6) => /lib/libnvidia-compiler.so.384.111
	libnvidia-cfg.so.1 (libc6,x86-64) => /lib64/libnvidia-cfg.so.1
	libnvidia-cfg.so (libc6,x86-64) => /lib64/libnvidia-cfg.so
	libcuda.so.1 (libc6,x86-64) => /lib64/libcuda.so.1
	libcuda.so.1 (libc6) => /lib/libcuda.so.1
	libcuda.so (libc6,x86-64) => /lib64/libcuda.so
	libcuda.so (libc6) => /lib/libcuda.so
```

`nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   29C    P0    27W / 250W |      0MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by 3XX0** [comment]
This is expected. If your container image needs additional capabilities, you can configure it through [NVIDIA_DRIVER_CAPABILITIES](https://github.com/NVIDIA/nvidia-container-runtime#nvidia_driver_capabilities).

**Comment by turengege** [comment]
thanks！

**Comment by phynias** [comment]
i'm having same issue. i have NVIDIA_DRIVER_CAPABILITIES set to all (also tried compute,video,graphics,utility) and i am missing many lib files.


host:

	libnvidia-wfb.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-wfb.so.1
	libnvidia-wfb.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-wfb.so.1
	libnvidia-tls.so.384.111 (libc6,x86-64, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
	libnvidia-tls.so.384.111 (libc6,x86-64, OS ABI: Linux 2.2.5) => /usr/lib/nvidia-384/libnvidia-tls.so.384.111
	libnvidia-tls.so.384.111 (libc6, hwcap: 0x8000000000000000, OS ABI: Linux 2.3.99) => /usr/lib32/nvidia-384/tls/libnvidia-tls.so.384.111
	libnvidia-tls.so.384.111 (libc6, OS ABI: Linux 2.2.5) => /usr/lib32/nvidia-384/libnvidia-tls.so.384.111
	libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ptxjitcompiler.so.1
	libnvidia-ptxjitcompiler.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ptxjitcompiler.so.1
	libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ml.so
	libnvidia-ifr.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ifr.so.1
	libnvidia-ifr.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-ifr.so.1
	libnvidia-ifr.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-ifr.so
	libnvidia-ifr.so (libc6) => /usr/lib32/nvidia-384/libnvidia-ifr.so
	libnvidia-gtk3.so.375.26 (libc6,x86-64) => /usr/lib/libnvidia-gtk3.so.375.26
	libnvidia-gtk2.so.375.26 (libc6,x86-64) => /usr/lib/libnvidia-gtk2.so.375.26
	libnvidia-glsi.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-glsi.so.384.111
	libnvidia-glsi.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-glsi.so.384.111
	libnvidia-glcore.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
	libnvidia-glcore.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-glcore.so.384.111
	libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fbc.so.1
	libnvidia-fbc.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-fbc.so.1
	libnvidia-fbc.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fbc.so
	libnvidia-fbc.so (libc6) => /usr/lib32/nvidia-384/libnvidia-fbc.so
	libnvidia-fatbinaryloader.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.111
	libnvidia-fatbinaryloader.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-fatbinaryloader.so.384.111
	libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-encode.so.1
	libnvidia-encode.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-encode.so.1
	libnvidia-encode.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-encode.so
	libnvidia-encode.so (libc6) => /usr/lib32/nvidia-384/libnvidia-encode.so
	libnvidia-eglcore.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-eglcore.so.384.111
	libnvidia-eglcore.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-eglcore.so.384.111
	libnvidia-egl-wayland.so.1.0.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-egl-wayland.so.1.0.1
	libnvidia-egl-wayland.so.1.0.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-egl-wayland.so.1.0.1
	libnvidia-container.so.1 (libc6,x86-64, OS ABI: Linux 3.10.0) => /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1
	libnvidia-compiler.so.384.111 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-compiler.so.384.111
	libnvidia-compiler.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-compiler.so.384.111
	libnvidia-compiler.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-compiler.so
	libnvidia-compiler.so (libc6) => /usr/lib32/nvidia-384/libnvidia-compiler.so
	libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-cfg.so.1
	libnvidia-cfg.so.1 (libc6) => /usr/lib32/nvidia-384/libnvidia-cfg.so.1
	libnvidia-cfg.so (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-cfg.so
	libnvidia-cfg.so (libc6) => /usr/lib32/nvidia-384/libnvidia-cfg.so
	libcudart.so.8.0 (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0
	libcudart.so (libc6,x86-64) => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so


container:

	libnvidia-tls.so.384.111 (libc6,x86-64, OS ABI: Linux 2.3.99) => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.384.111
	libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
	libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ifr.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1
	libnvidia-glsi.so.384.111 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.384.111
	libnvidia-glcore.so.384.111 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.384.111
	libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1
	libnvidia-fatbinaryloader.so.384.111 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.111
	libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
	libnvidia-eglcore.so.384.111 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.384.111
	libnvidia-compiler.so.384.111 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.384.111
	libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so

**Comment by flx42** [comment]
@phynias `libcudart` is not part of the driver, it is part of the CUDA toolkit, and needs to be shipped inside the container image.
