### ISSUE TITLE
nvidia-docker 2.0 Failed to initialize NVML: Insufficient Permissions

### ISSUE THREAD

**Issue by dllehr81** [NVIDIA/nvidia-docker#676]
Hey Folks,
  I did a fresh build and install of libnvidia, nvidia-container-runtime, and nvidia-docker 2.0 on a Rhel 7.4/ppc64le environment.  

I run
`docker run -ti --rm nvidia/cuda-ppc64le:9.1-base-centos7 bash`
Then `nvidia-smi`  I get the following error
`Failed to initialize NVML: Insufficient Permissions`

I get past the issue with the `--privileged` keyword.  I know there was talk about nvidia-docker 2.0 solving some Selinux problems.  Is that still the case?  

Here's the software stacks I'm running
```
libnvidia-container-static-1.0.0-0.1.ppc64le
libnvidia-container-tools-1.0.0-0.1.ppc64le
libnvidia-container-devel-1.0.0-0.1.ppc64le
libnvidia-container1-1.0.0-0.1.ppc64le
libnvidia-container1-debuginfo-1.0.0-0.1.ppc64le
nvidia-container-runtime-hook-1.3.0-1.ppc64le
nvidia-container-runtime-2.0.0-1.docker1.12.6.ppc64le
nvidia-docker2-2.0.3-1.docker1.12.6.noarch
docker-1.12.6-71.git3e8e77d.el7.ppc64le
```

**Comment by 3XX0** [comment]
Unfortunately there is not much we can do for Selinux, it depends on the system. You can try to run `nvidia-container-cli -k list | restorecon -v -f -` as root see if it fixes the problem.

If not, you will need to write a custom profile to allow the use of the nvidia labels inside the container (as returned by `semanage fcontext -l | grep -E 'nvidia|cuda'`)

**Comment by 3XX0** [comment]
See also: https://github.com/NVIDIA/nvidia-container-runtime/issues/28
