### ISSUE TITLE
Amazon Linux Installation Instructions - Wrong distribution identifier

### ISSUE THREAD

**Issue by felix-last** [NVIDIA/nvidia-docker#678]
I believe installation instructions of the readme don't work for amazon linux. Steps for amazon linux are described as:

```sh
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | \
  sudo tee /etc/yum.repos.d/nvidia-docker.repo
```

`echo $distribution` shows me `amzn2017.09`, but there is no repository for that version. 

I was successful setting distribution to `amzn2`.

**Comment by flx42** [comment]
Those instructions are for Amazon Linux 2.

As you noticed, it can't work for Amazon Linux 1, so you should use `amzn1` instead.
I mention this special case here: https://nvidia.github.io/nvidia-docker/
But not on the README.

**Comment by felix-last** [comment]
Thank you. I didn't realize this was Amazon Linux 1 :)
