### ISSUE TITLE
Ubuntu 14.04 install fails with missing dependency

### ISSUE THREAD

**Issue by josemonsalve2** [NVIDIA/nvidia-docker#679]
### 1. Issue or feature description
I am trying to install nvidia-docker2 on ubuntu14.04. I have faced several dependencies issues. Here are my attempts and dependencies errors:

for *2.0.3+docker17.12.1-1*, It fails because I need *2.0.0+docker17.12.1-1* which needs:
> Depends: libseccomp2 (>= 2.3.0) but 2.1.1-1ubuntu1~trusty4 is to be installed 
I tried installing 2.3.0 but the highest I can go is 2.2.3

So I downgraded my docker-ce to *17.09.1~ce-0~ubuntu* which lets me install *nvidia-container-runtime=2.0.0+docker17.09.1-1* but when I am about to install nvidia-docker2 I get this error: 

> nvidia-docker2 : Depends: docker-ce (= 17.09.1~ce-0~debian) but 17.09.1~ce-0~ubuntu is to be installed

### Machine information:
> uname -a
Linux vader 4.4.0-112-generic #135~14.04.1-Ubuntu SMP Tue Jan 23 20:41:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> docker -v
Docker version 17.09.1-ce, build 19e2cf6

I am not sure what to do about ~debian vs ~ubuntu in the dependencies. Any suggestion?

**Comment by flx42** [comment]
What's the content of `/etc/apt/sources.list.d/nvidia-docker.list`?

**Comment by josemonsalve2** [comment]
```
cat /etc/apt/sources.list.d/nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/debian9/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/debian9/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/debian9/$(ARCH) /
```

**Comment by josemonsalve2** [comment]
I see what's going on. Let me double check my first steps

**Comment by flx42** [comment]
You installed the wrong repository. :)

**Comment by josemonsalve2** [comment]
Hehehe! I am an idiot! Sorry about that!
