### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go:348

### ISSUE THREAD

**Issue by WeiSong123** [NVIDIA/nvidia-docker#683]
zhanghua@zhanghua-System-Product-Name:~$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from nvidia/cuda
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
95e837069dfa: Pull complete
fef4aadda783: Pull complete
343234bd5cf3: Pull complete
64e8786fc8c1: Pull complete
d6a4723d353c: Pull complete
Digest: sha256:3524adf9b563c27d9a0f6d0584355c1f4f4b38e90b66289b8f8de026a9162eee
Status: Downloaded newer image for nvidia/cuda:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=12146 /var/lib/docker/overlay2/28c0160c48634c32cace91556e51993fb8001b4d5fcb22c0fa829a468ff3ed7e/merged]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown

**Comment by k0105** [comment]
Same here. Ubuntu 16.04. Extremely annoying. I reinstalled a fresh system, installed Docker and Docker Compose (following the Digital Ocean tutorials) and then restarted and installed nvidia-docker2 the way described here. Docker itself runs fine, nvidia-docker does not. Any ideas?

**Comment by 3XX0** [comment]
Please follow the template when submitting an issue, this is most likely a driver installation issue.

**Comment by sidharthramesh98** [comment]
Same issue, I've been trying to run nvidia-docker. Nvidia driver version 384.13, CUDA 9.0. Any ideas why this is happening. Is it a driver mismatch?

**Comment by dashsd** [comment]
Getting the same issue on Ubuntu 16.04 with nvidia driver v390.48 and cuda v9.1.85. Even running the nvidia-smi test as per the NGC documentation fails.
However, with nvidia drivers v384.111 and v390.30, the nvidia-docker runs fine. I guess v390.48 has some incompatibility issues with the nv docker. I suggest following the guidelines as mentioned here: http://docs.nvidia.com/ngc/ngc-titan-setup-guide/index.html

**Comment by dashsd** [comment]
@flx42 nvidia-smi did work with 390.48 outside of docker. Didn't check deviceQuery though. Right now I am using 390.30. If 390.48 works as you mentioned, then it could definitely be an issue with the driver installation. Thanks for confirming :) I'll reinstall 390.48 and check if CUDA sample executes successfully.

**Comment by elrond79** [comment]
I was having the same problem, except with driver 390.30 and  cuda 9.0.176, in ubuntu 16.04.

I tried editing /etc/nvidia-container-runtime/config.toml, and commenting out this line:

# ldconfig = "@/sbin/ldconfig.real"

...and all of a sudden, it worked.  Not sure if this is something that's advisable / might have other reprecussions / etc, though...

**Comment by flx42** [comment]
@elrond79 this line seems unrelated to the problem initially mentioned in this thread.

@WeiSong123 let's try to refocus to your own problem, do you still have an issue?

**Comment by sidharthramesh98** [comment]
@flx42 the problem seems to go away when I used 390.48. I think its probably a driver error. I installed CUDA the last time from the runfile and it had 384.13. Installing it from the deb file install the right driver.

@WeiSong123, what was your driver version

**Comment by JiangKui007** [comment]
I meet the same issue. It's annoyed.

**Comment by JiangKui007** [comment]
报如下错误时：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=24351 /var/lib/docker/aufs/mnt/085a2f9697d8b4dfbf269d413e032b46e948fa619e82f7a50b0dbac97e716be6]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.

可能是nvidia driver/cuda/nvidia-docker2之间出了问题；
将三者彻底删除
apt-get purge nvidia driver-* cuda-* nvidia-docker2
apt-get update
重新安装cuda-9-0，会自动安装相应的nvidia driver-384 就用默认的版本
测试nvidia-smi通过
重新安装nvidia-docker2，
测试 docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi通过
 
问题解决

**Comment by zheng-xing** [comment]
@sidharthramesh98 Thanks.

I have exactly the same problem here with Centos 7.4 and nvidia driver 384.
The problem disappeared after installing nvidia driver 390.48.

**Comment by DrWeng** [comment]
I got the same error. I did uninstall/re-install the driver using different ways several times. It still did not work.

Then I turned of secure boot (removing secure boot key) in bios. It worked!!!

**Comment by JonShelley** [comment]
I got the same error. Once I commented out the following lines from the docker file 

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

I could launch the image but I can't accesses the gpus. :(

root@3ac4b61724c5:/myapps# nvidia-smi
Failed to initialize NVML: Unknown Error

I am using the following driver version

NVIDIA-SMI 396.26                 Driver Version: 396.26

**Comment by nmalkin** [comment]
A possible explanation for anyone who stumbles on this issue:

One of the last questions the Nvidia driver installer (at least in version 390.87) asks is:

> Would you like to run the nvidia-xconfig utility to automatically update your X configuration file so that the NVIDIA X driver will be used when you restart X?  Any pre-existing X configuration file will be backed up.

If you select "No" (which is the default option), then when you reboot, you'll get the exact error in the original report (`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348:…`).

If you reinstall the driver and say "Yes" to that question, the error will go away, even after rebooting. (This assumes that you didn't actually have some principled reason for not running `nvidia-xconfig` during the original install.)

**Comment by qualia0000** [comment]
> 报如下错误时：
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused "process_linux.go:385: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=24351 /var/lib/docker/aufs/mnt/085a2f9697d8b4dfbf269d413e032b46e948fa619e82f7a50b0dbac97e716be6]\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\n\""": unknown.
> 
> 可能是nvidia driver/cuda/nvidia-docker2之间出了问题；
> 将三者彻底删除
> apt-get purge nvidia driver-* cuda-* nvidia-docker2
> apt-get update
> 重新安装cuda-9-0，会自动安装相应的nvidia driver-384 就用默认的版本
> 测试nvidia-smi通过
> 重新安装nvidia-docker2，
> 测试 docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi通过
> 
> 问题解决

May I know if such operation influences the existing images that are associated with nvidia-docker?

**Comment by dardanbekteshi** [comment]
Had the same problem as the OP. Fixed it by commenting the following line in **/etc/nvidia-container-runtime/config.toml** file:

`root = "/run/nvidia/driver"`

Finally the file looked like this: 
```
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-runtime-hook.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "@/sbin/ldconfig.real"
```
