### ISSUE TITLE
net/http: TLS handshake timeout.

### ISSUE THREAD

**Issue by dingjiangang** [NVIDIA/nvidia-docker#684]
--rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from  #nvidia/cuda
22dc81ace0ea: Pulling fs layer 
1a8b3c87dba3: Pulling fs layer 
91390a1c435a: Pulling fs layer 
07844b14977e: Waiting 
b78396653dae: Waiting 
59876c12b10f: Waiting 
92ea808ac02a: Waiting 
569bd533d309: Waiting 
2db1f6a96615: Waiting 
2b9d78c87b7c: Waiting 
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/9b/9b8a74e9dc7640b2f9584db63a82e100e447a3011401a102139a9d1512ea046d/data?Expires=1522494527&Signature=LU~JbfoSTiVK1h-0VPxarXK7JDkBQyDXMFJmW7nGXriJXZIgE-MxOVC1rtp2tGBZgD3OWG8qweadnn~6139A2iGvqvfxwGHRM4bHzTRbeeiXYRmrACOPhBkxFUatBPt5glA-kzxag4oLPzjeUzh1KYs4HdySy5EmO1QDHZlDnEo_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout.
See 'docker run --help'.

i can not do this  step，why？

**Comment by flx42** [comment]
It's unrelated to `nvidia-docker`, probably a temporary issue with the CDN docker uses, or something blocked by your firewall.

Doing `docker pull nvidia/cuda` should give you the same error.
