### ISSUE TITLE
DIGITS on docker runs horribly slowly

### ISSUE THREAD

**Issue by panzerfrank** [NVIDIA/nvidia-docker#687]
_
### 2. nvidia-docker run -v /home/frank/IMAGENET:/data/IMAGENET: -v /home/frank/digits-jobs:/jobs -p 5000:5000 nvidia/digits:latest
Job Directory
/jobs/20180402-153401-0d61
Disk Size
103 MB
Network (train/val)
train_val.prototxt
Network (deploy)
deploy.prototxt
Network (original)
original.prototxt
Solver
solver.prototxt
Raw caffe output
caffe_output.log
Dataset
ImageNet-ILSVRC12-subset
Done 03:21:00 PM

Image Size
256x256
Image Type
COLOR
DB backend
lmdb
Create DB (train)
926339 images
Create DB (val)
102876 images

Classify Many  
Number of images to show per category 
9
Top N Predictions per Category  
Job Status Running
Initialized at 03:34:01 PM (1 second)
Running at 03:34:02 PM
Train Caffe Model Running 
8% Estimated time remaining: 19 hours, 21 minutes 

Initialized at 03:34:01 PM (1 second)
Running at 03:34:02 PM
Hardware
GeForce GTX 1080 Ti (#0)
Memory
4.09 GB / 10.9 GB (37.5%)
GPU Utilization
97%
Temperature
84 °C
Process #149
CPU Utilization
229.8%
Memory
3.01 GB (39.2%)

is this a KNOWN PROBLEM or is it normal.  Using a Native DIGITS The job takes FOUR HOURS

**Comment by flx42** [comment]
You should probably use the NGC containers: https://www.nvidia.com/en-us/gpu-cloud/deep-learning-containers/
