### ISSUE TITLE
Add packages for the Docker versions supported by KOPS

### ISSUE THREAD

**Issue by tals** [NVIDIA/nvidia-docker#689]
### Issue or feature description
For Debian8, There is no intersection between the supported version on the nvidia-docker apt repository and the ones supported by KOPS.
[Debian8 is the default distro KOPS uses.](https://github.com/kubernetes/kops/blob/master/docs/images.md#debian)

List of all supported versions: https://github.com/kubernetes/kops/blob/487dc33b7edfe6c9ac94fc8764170490312c8f85/nodeup/pkg/model/docker.go#L57

**Comment by flx42** [comment]
Don't they also support `17.09`? In this case, why can't they upgrade to `17.09.1`? we do provide a deb package for this version.

**Comment by flx42** [comment]
Docker CE 17.09.0 is not the latest version of the 17.09 branch, and this branch is not officially supported anymore by Docker since the beginning of the year:
https://docs.docker.com/install/#updates-and-patches

Won't fix.

**Comment by tals** [comment]
I had to fork this to get it working with KOPS/Kubernetes 1.8. It would be nice if nvidia-docker harmonized with the rest of the ecosystem.

**Comment by flx42** [comment]
Why not have KOPS support more recent versions of docker CE?

**Comment by tals** [comment]
I am not the maintainer of KOPS, but I did see Kubernetes/KOPS have their own way of validating Docker versions.

**Comment by flx42** [comment]
Which doesn't even match KOPS:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#external-dependencies

**Comment by tals** [comment]
KOPS trail behind Kubernetes by 1-2 releases.

KOPS 1.8, which was the latest stable release at the time this bug was opened, targets 1.11.2, 1.12.6, 1.13.1, and 17.03.2

**Comment by flx42** [comment]
Well, not exactly, since KOPS supports 17.09.0, right?

**Comment by tals** [comment]
correct!
...which is unsupported by nvidia-docker on debian8 😅

**Comment by flx42** [comment]
Sure, but I don't see why they can't go one minor version further.

**Comment by tals** [comment]
I'm not the maintainer of KOPS.
I just wanted to get nvidia-docker working with Kubernetes on AWS, and after spending over a day doing version matching between the different components, I thought I'd contribute something back to make this stuff easier for others (see the PR).

I guess the path forward for people on KOPS 1.8 is to either fork this repo and apply some patches, or to upgrade to KOPS 1.9.

**Comment by flx42** [comment]
Yes. I know you're not a KOPS maintainer.
My point, apologies if it didn't come across clearly, was that I think it will be more beneficial for the whole community to have KOPS support more recent versions of Docker, or at least the **latest** version of a CE stable release (which contain important bugfixes).

**Comment by tals** [comment]
Yeah I agree. I just didn't want to get into how they vet versions, and adding support for newer releases was easy here (major kudos for that btw -- you guys did good work here!)
