### ISSUE TITLE
Makefile contains syntax error for docker 18.03.0

### ISSUE THREAD

**Issue by haraldF** [NVIDIA/nvidia-docker#692]
The Makefile in the root directory contains:

```Makefile
ubuntu16.04: $(addsuffix -ubuntu16.04, 18.03.0, 17.12.1 17.12.0 17.09.1 17.09.0 17.06.2 17.03.2 1.13.1 1.12.6)
````

Notice the extra comma after `18.03.0` which should not be there. Please remove it in this line (and the lines below)

**Comment by flx42** [comment]
Fixed, thanks for reporting!
Just to double check, it was not causing any issue with the package itself, right?

**Comment by haraldF** [comment]
Thanks for the quick fix :) I stumbled over it because docker complained that commas are invalid in tag names, but didn't dig deeper.
