### ISSUE TITLE
Docker build issues.

### ISSUE THREAD

**Issue by R1234A** [NVIDIA/nvidia-docker#693]
OS - Ubuntu(16.04)-host
GPU - GTX 1060(6GB)
GPU architecture - Pascal(I guess)

I am trying to build caffe in docker container. But getting errors and have some doubts regarding dockers.
1)My host machine is taking by default 384.130 but according to [https://github.com/NVIDIA/nvidia-docker/wiki/CUDA](url) I have to downgrade to 375 version according to the link chart in my host machine. Is this right way ?

2)Then CUDA and CUDNN is not to be installed in host machine. Is it correct?

3)Inside docker container no nvidia drivers is to be installed. Am I right?

4)I have tried 1st step and 2nd step but when creating container for caffe with GPU support giving error at running test of caffe as : "cuda driver version is insufficient for cuda runtime version docker". What is the solution??

Please help for with all answers, because I am bit confused with these versions of host and docker.(with GPU)

**Comment by 3XX0** [comment]
1) 384.130 is fine if you want to run CUDA  <= 9.0
2) Yes
3) Yes
4) This error is coming from your Docker image, not nvidia-docker. You can check that CUDA is working properly from within an image by running a [sample](https://gitlab.com/nvidia/samples/blob/master/cuda/ubuntu16.04/cuda-samples/Dockerfile)

**Comment by R1234A** [comment]
I have to install cudnn inside container seprately??

**Comment by flx42** [comment]
No, cuDNN is included in some images, look at the tags we provide: https://hub.docker.com/r/nvidia/cuda/

**Comment by R1234A** [comment]
Which image should I use runtime or devel of CUDA-9.0 to build caffe with CUDA support and CUDNN support inside docker??

**Comment by flx42** [comment]
`9.0-cudnn7-devel`
