### ISSUE TITLE
Please assist - unable to run nvidia-docker-compose build 

### ISSUE THREAD

**Issue by eugenepptech** [NVIDIA/nvidia-docker#698]
Hi All,
Anyone can assist me for my issue unable to run nvidia-docker-compose build on my server?

---

### 1. Issue or feature description
unable to run the nvidia-docker-compose build

### 2. Steps to reproduce the issue
sudo nvidia-docker-compose build

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nvidia-docker-compose", line 55, in <module>
    resp = request.urlopen('http://{0}/docker/cli/json'.format(args.nvidia_docker_host)).read().decode()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

 - [ ] Kernel version from `uname -a` --> Linux gpusvr 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:46 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

 - [ ] Any relevant kernel output lines from `dmesg`
[Thu Apr 12 11:27:38 2018] device veth27f71e4 entered promiscuous mode
[Thu Apr 12 11:27:38 2018] IPv6: ADDRCONF(NETDEV_UP): veth27f71e4: link is not ready
[Thu Apr 12 11:27:38 2018] eth0: renamed from vethe4974ab
[Thu Apr 12 11:27:38 2018] IPv6: ADDRCONF(NETDEV_CHANGE): veth27f71e4: link becomes ready
[Thu Apr 12 11:27:38 2018] docker0: port 2(veth27f71e4) entered forwarding state
[Thu Apr 12 11:27:38 2018] docker0: port 2(veth27f71e4) entered forwarding state
[Thu Apr 12 11:27:53 2018] docker0: port 2(veth27f71e4) entered forwarding state
[Thu Apr 12 11:50:53 2018] docker0: port 2(veth27f71e4) entered disabled state
[Thu Apr 12 11:50:53 2018] vethe4974ab: renamed from eth0
[Thu Apr 12 11:50:53 2018] docker0: port 2(veth27f71e4) entered disabled state
[Thu Apr 12 11:50:53 2018] device veth27f71e4 left promiscuous mode
[Thu Apr 12 11:50:53 2018] docker0: port 2(veth27f71e4) entered disabled state

 - [ ] Driver information from `nvidia-smi -a`  
Driver Version : 384.111

 - [ ] Docker version from `docker version`
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:08:17 2017
 OS/Arch:       linux/ppc64le

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:06:35 2017
  OS/Arch:      linux/ppc64le
  Experimental: false

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
+++-====================================-=======================-=======================-=============================================================================
un  bumblebee-nvidia                     <none>                  <none>                  (no description available)
rc  nvidia-361                           361.119-0ubuntu1        ppc64el                 NVIDIA binary driver - version 361.119
ii  nvidia-384                           384.111-0ubuntu1        ppc64el                 NVIDIA binary driver - version 384.111
un  nvidia-common                        <none>                  <none>                  (no description available)
un  nvidia-cuda-dev                      <none>                  <none>                  (no description available)
un  nvidia-cuda-doc                      <none>                  <none>                  (no description available)
un  nvidia-cuda-gdb                      <none>                  <none>                  (no description available)
rc  nvidia-cuda-toolkit                  7.5.18-0ubuntu1         ppc64el                 NVIDIA CUDA development toolkit
un  nvidia-current                       <none>                  <none>                  (no description available)
ii  nvidia-docker                        1.0.1-1                 ppc64el                 NVIDIA Docker container tools
un  nvidia-driver-binary                 <none>                  <none>                  (no description available)
ii  nvidia-driver-local-repo-ubuntu1604- 1.0-1                   ppc64el                 nvidia-driver-local repository configuration files
un  nvidia-libopencl1                    <none>                  <none>                  (no description available)
un  nvidia-libopencl1-384                <none>                  <none>                  (no description available)
un  nvidia-libopencl1-dev                <none>                  <none>                  (no description available)
ii  nvidia-modprobe                      390.31-0ubuntu1         ppc64el                 Load the NVIDIA kernel driver and create device files
un  nvidia-opencl-dev                    <none>                  <none>                  (no description available)
un  nvidia-opencl-icd                    <none>                  <none>                  (no description available)
un  nvidia-opencl-icd-361                <none>                  <none>                  (no description available)
ii  nvidia-opencl-icd-384                384.111-0ubuntu1        ppc64el                 NVIDIA OpenCL ICD
un  nvidia-persistenced                  <none>                  <none>                  (no description available)
un  nvidia-prime                         <none>                  <none>                  (no description available)
un  nvidia-profiler                      <none>                  <none>                  (no description available)
ii  nvidia-settings                      396.18-0ubuntu0~gpu16.0 ppc64el                 Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary               <none>                  <none>                  (no description available)
un  nvidia-visual-profiler               <none>                  <none>                  (no description available)

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
nvidia-container-cli: command not found

**Comment by eugenepptech** [comment]
Dmesg log as below.

[Thu Apr 12 11:27:38 2018] device veth27f71e4 entered promiscuous mode
[Thu Apr 12 11:27:38 2018] IPv6: ADDRCONF(NETDEV_UP): veth27f71e4: link is not ready
[Thu Apr 12 11:27:38 2018] eth0: renamed from vethe4974ab
[Thu Apr 12 11:27:38 2018] IPv6: ADDRCONF(NETDEV_CHANGE): veth27f71e4: link becomes ready
[Thu Apr 12 11:27:38 2018] docker0: port 2(veth27f71e4) entered forwarding state
[Thu Apr 12 11:27:38 2018] docker0: port 2(veth27f71e4) entered forwarding state
[Thu Apr 12 11:27:53 2018] docker0: port 2(veth27f71e4) entered forwarding state
[Thu Apr 12 11:50:53 2018] docker0: port 2(veth27f71e4) entered disabled state
[Thu Apr 12 11:50:53 2018] vethe4974ab: renamed from eth0
[Thu Apr 12 11:50:53 2018] docker0: port 2(veth27f71e4) entered disabled state
[Thu Apr 12 11:50:53 2018] device veth27f71e4 left promiscuous mode
[Thu Apr 12 11:50:53 2018] docker0: port 2(veth27f71e4) entered disabled state

**Comment by flx42** [comment]
Hello @eugenepptech, we do not maintain nvidia-docker-compose.

You should switch to nvidia-docker2 (look at the latest instructions on GitHub), then with a recent version of compose you will be able to set the runtime: https://github.com/docker/compose/pull/5405
For instance: https://github.com/3XX0/prometheus-dcgm/blob/master/docker-compose.yml#L32

**Comment by eugenepptech** [comment]
okies.. thank you for the comment

**Comment by flx42** [comment]
Oh, you're using a Power machine. We still haven't released the packages for this architecture, sorry.
