### ISSUE TITLE
pycuda does not install with nvidia containers

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/nvidia-docker#70]
I use pycuda as one of the dependencies in my project, however I have not been able to install it with any normal methods for the nvidia docker images. I know pycuda will error out if trying to install it through pip, however there is a simple solution of exporting CUDA_ROOT.

https://codeyarns.com/2015/07/31/pip-install-error-with-pycuda/

However these instructions won't work because the cuda folder does not have a bin folder, it seems like things are installed differently. I looked for cuda.h and found it in these two folders:
/usr/include/hwloc/cuda.h
/usr/include/linux/cuda.h

Pointing to those folders with CUDA_ROOT did not fix it.

This is the error I keep getting: [full error](http://pastebin.com/7kjmmtUH)

I also tried looking for nvcc which looks like what is missing, but it is not in my file system even though everything else works.
https://github.com/lebedov/scikit-cuda/issues/83

**Comment by flx42** [comment]
You are probably using a `runtime` image of CUDA, see here:
https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#description
It doesn't include nvcc or the headers. You need a `devel` image for this.

Our caffe and DIGITS image are based on `runtime` images of CUDA/cuDNN, this is probably your problem. We discussed the reasons in another issue:
https://github.com/NVIDIA/nvidia-docker/issues/59

**Comment by alfredox10** [comment]
Interesting, great answer I will try to rebuild it with a devel cuda image, and then add caffe on top of it. I will let you know if that works.

**Comment by alfredox10** [comment]
Installing the additional headers on top did give me nvcc but was not enough to compile pycuda. I had to get the devel version and then put Caffe/CuDNN on top of that and that worked.

Thanks!

**Comment by flx42** [comment]
FYI, we have `devel` versions of the cuDNN images, you don't need to add cuDNN yourself.
