### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by zhaoxy2850** [NVIDIA/nvidia-docker#700]
Hi guys, 
       I've ran into a problem. My cuda version is, CUDA Version 8.0.61. I've already check the requirements(https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements) but I didn't see anything wrong. Any ideas will be appreciated! Thank you very much!

$ nvidia-smi
Thu Apr 12 22:59:13 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 705      Off  | 0000:01:00.0     N/A |                  N/A |
| 40%   47C    P0    N/A /  N/A |      0MiB /   964MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

root@f39ddf68b120:~# cat /usr/local/cuda/version.txt
CUDA Version 8.0.61

In the docker, here is the error: 
root@f39ddf68b120:/usr/local/cuda/samples/1_Utilities/deviceQuery# ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

**Comment by 3XX0** [comment]
What's the output of `nvidia-container-cli info` on the host?

**Comment by zhaoxy2850** [comment]
I've found the problem, thank you very much!
I didn't run the docker image with '--runtime=nvidia'. So the container couldn't load the nvidia driver. For anyone who faced the similar problem, you can run nvidia-smi in the container to see if the container can access to the driver.

**Comment by wangpengabc** [comment]
> I've found the problem, thank you very much!
> I didn't run the docker image with '--runtime=nvidia'. So the container couldn't load the nvidia driver. For anyone who faced the similar problem, you can run nvidia-smi in the container to see if the container can access to the driver.
I create the container with the command：

 nvidia-docker run --runtime=nvidia -it --name caffe_ssd_gpu -v /home/sdc/wangpeng/docker/caffe_ssd_gpu/swap:/home/swap linkernetworks/caffe-ssd:1.0-gpu /bin/bash

I add ”-runtime=nvidia “ ， it does work for me！Thanks！

**Comment by mxmoller** [comment]
You can also set the nvidia runtime as default, by adding "default-runtime": "nvidia", to your /etc/docker/daemon.json as described here: https://docs.nvidia.com/dgx/nvidia-container-runtime-upgrade/index.html#using-nv-container-runtime

This may be helpful if you mostly use nvidia docker images.
