### ISSUE TITLE
Missing the symbolic link of libnvcuvid.so to libnvcuvid.so.1 in Docker Container

### ISSUE THREAD

**Issue by chenjian158978** [NVIDIA/nvidia-docker#701]
**My Environment**

    # nvidia-container-cli info
    NVRM version:   384.111
    CUDA version:   9.0

    Device Index:   0
    Device Minor:   0
    Model:          Tesla P4
    GPU UUID:       GPU-4e91e54f-319e-2124-06ed-7b1d9258f9c1
    Bus Location:   00000000:04:00.0
    Architecture:   6.1

**Docker Information**

	# docker info
	Containers: 116
	 Running: 60
	 Paused: 0
	 Stopped: 56
	Images: 61
	Server Version: 17.06.2-ce
	Storage Driver: overlay
	 Backing Filesystem: extfs
	 Supports d_type: true
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins:
	 Volume: local
	 Network: bridge host macvlan null overlay
	 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
	Swarm: inactive
	Runtimes: nvidia runc
	Default Runtime: nvidia
	Init Binary: docker-init
	containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
	runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
	init version: 949e6fa
	Security Options:
	 seccomp
	  Profile: default
	Kernel Version: 3.10.0-693.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	OSType: linux
	Architecture: x86_64
	CPUs: 16
	Total Memory: 125.6GiB
	Name: master1
	ID: DFOM:HECH:OOCP:N5Q2:ZSV7:HHN6:GIX4:MAFI:KFHQ:C5VZ:WM6X:5G6V
	Docker Root Dir: /var/lib/docker
	Debug Mode (client): false
	Debug Mode (server): false
	Registry: https://index.docker.io/v1/
	Experimental: false
	Insecure Registries:
	 127.0.0.0/8
	Live Restore Enabled: false
	
	
**In Host OS**

	# ldconfig -p | grep libnvcuvid
		libnvcuvid.so.1 (libc6,x86-64) => /lib64/libnvcuvid.so.1
		libnvcuvid.so.1 (libc6) => /lib/libnvcuvid.so.1
		libnvcuvid.so (libc6,x86-64) => /lib64/libnvcuvid.so
		libnvcuvid.so (libc6) => /lib/libnvcuvid.so
		
**In Docker Container**

	# docker run --rm -ti --runtime=nvidia -e NVIDIA_DRIVER_CAPABILITIES=video,compute,utility nvidia/cuda:9.0-base ldconfig -p | grep libnvcuvid
		libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
		
We need the symbolic link of `libnvcuvid.so`, like 
	
	libnvcuvid.so -> libnvcuvid.so.1

**Question**

How can `nvidia-docker` to build this link automatically？

Or, should I build the link manually？

**Comment by flx42** [comment]
When executing an application, you don't need this symlink.  For instance, you shouldn't dlopen `libnvcuvid.so`, but you should dlopen `libnvcuvid.so.1` instead (the SONAME).

**Comment by chenjian158978** [comment]
@flx42 
I am sorry that your reply can not convince me. 
In the code of [nvc_mount.c](https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc_mount.c), there is a function called **symlink_libraries** which creates the symlink of **libcuda.so**. So, why should not make a symlink for **libnvcuvid.so**?

p.s. I am not good at C programming. Could you please explain it patiently? Thank you.

**Comment by flx42** [comment]
At runtime, some applications rely on [dlopen(3)](http://man7.org/linux/man-pages/man3/dlopen.3.html) to dynamically check if CUDA support is available. Those applications should be doing `dlopen("libcuda.so.1")`, unfortunately many applications incorrectly do `dlopen("libcuda.so")`, our workaround if for this use case only.

So, it depends what you are trying to achieve. Do you want to build an app? Or do you want to execute an app?

**Comment by chenjian158978** [comment]
@flx42 
Actually, I want to execute an app which is created by others. Those guys said they learned from the example codes of CUDA, and in that example, the codes use the symlink of **libnvcuvid.so**. In the meantime, I am confused that there is no more details about those example codes which I want to show you.

In my opinion, the libs, the bin and the symlinks should be the same in or out of docker containers. We should reduce the differences which you can compare that by yourself between the docker container and the host. Beacause most developers still work in the environment of host OS which has all useful libraries and symlinks.

**Comment by flx42** [comment]
I think our video samples were incorrect at one point. When executing, you don't need `libnvcuvid.so`, you only need `libnvcuvid.so.1`. Please ask the developers to change this.

**Comment by chenjian158978** [comment]
@flx42 OK，thank you for your time!
