### ISSUE TITLE
CUDA 6.5 supported ?

### ISSUE THREAD

**Issue by nyue** [NVIDIA/nvidia-docker#703]
Hi,

  If my driver (I have an old GPU) can only support CUDA 6.5, should I still consider using the current nvidia-docker ?

  I am only using the OpenGL aspect, not CUDA, in my container application.

Cheers

**Comment by flx42** [comment]
Hello,

If your driver is recent enough and you use our OpenGL docker image, I believe it might work. But it was not tested. Start by making sure that evertyhing works fine with the NVIDIA driver driving the display on the host.

**Comment by nyue** [comment]
Do you have an example Dockerfile to learn and reference from ? I see mostly example Dockerfile exercising the CUDA aspect but not the OpenGL aspect.

I am hoping to learn the process by building a Docker instance with nvidia opengl for the glxgears example found on CentOS

Thank you.

**Comment by flx42** [comment]
Try these samples:
https://gitlab.com/nvidia/samples/blob/master/opengl/ubuntu16.04/graphics-samples/Dockerfile
https://gitlab.com/nvidia/samples/blob/master/opengl/ubuntu16.04/glxgears/Dockerfile
