### ISSUE TITLE
How to limit access to specific GPU number

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [NVIDIA/nvidia-docker#705]
I will take an example situation to explain my case. I would like to be able to assign different GPUs to different containers.

I have a machine with 4 GPUs. I would like to create 3 containers.
With the following distribution:
- Container 1: Tensorflow => GPU 0 et 1
- Container 2: Caffe => GPU 2
- Container 3: PyTorch => GPU 3

How can I make sure that only GPUs 0 & 1 are accessible from *container1* and not all of them ?
I can launch all of them without any problem, however all the GPUs are available for all containers, which can lead to collisions between developers (if they do not know who is using what).

Example launch command for Tensorflow, i would like to modify it in order to be sure that only **GPU 0 and 1** are visible.

```shell
nvidia-docker run -d -p 6006:6006 -p 8888:8888 --name tensorflow_nb -e PASSWORD=my_password tensorflow/tensorflow:latest-gpu-py3
```

Thanks for the help.

**Comment by 3XX0** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#i-have-multiple-gpu-devices-how-can-i-isolate-them-between-my-containers

**Comment by DEKHTIARJonathan** [comment]
WOW ! My bad ... I'm closing this
