### ISSUE TITLE
nvidia docker can't run container 

### ISSUE THREAD

**Issue by kinglion811** [NVIDIA/nvidia-docker#709]
container can not run,the error is:
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:337: running prestart hook 0 caused \"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=15367 /media/disk1/docker/overlay/a8eb6bae2e936df319b13602471c9f199bf5bcb66de6e7a70310bd13105e5bef/merged]\\nnvidia-container-cli: initialization error: cuda error: invalid device ordinal\\n\"".

**Comment by ankitshah009** [comment]
Any solution to this problem. I am facing the same issue.

**Comment by 3XX0** [comment]
Please provide more information by following the issue template.
At the very least the logs, and `nvidia-smi` output

**Comment by kfryklund** [comment]
Thank you @3XX0 
Your advice helped me determine the issue on my end.  For me it ended up being an insufficient power issue.
