### ISSUE TITLE
flag provided but not defined: --add-host

### ISSUE THREAD

**Issue by SivaIntegrator** [NVIDIA/nvidia-docker#71]
Hi guys, it's my first issue on github so sorry if I miss something in the submitting procedure.

My Docker version is:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:             Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:             Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

The problem is when I want to add a new entry in etc/hosts file of my container at the building I get this error: 
"flag provided but not defined: --add-host"

Do you have any suggestion or should I just update my docker version? 1.9.1 seems enough recent

Thanks for your advices.

**Comment by flx42** [comment]
This doesn't seem to be related to `nvidia-docker`, but to Docker in general.

`--add-host` is only for `docker run`, not `docker build`.

**Comment by SivaIntegrator** [comment]
Oh right, I didn't notice the repository...
And do you think there is a way to add entry in etc/hosts with `docker build` ?

**Comment by flx42** [comment]
Maybe this issue might help you:
https://github.com/docker/docker/issues/10324
