### ISSUE TITLE
Version 2 Support for Solus

### ISSUE THREAD

**Issue by flauted** [NVIDIA/nvidia-docker#710]
1. Issue or feature description: Support for the Solus OS and eopkg.

3. Information to attach: I've left a comment on the [Solus forums](https://dev.solus-project.com/T3641). Evidence that nvidia-docker was possible with nvidia-docker 1.0.1 on the [Solus forums](https://dev.solus-project.com/T354). I can confirm that Cuda sans compiler is available and functioning via Conda on Solus. Not sure about other methods.

Many thanks!

**Comment by 3XX0** [comment]
There is no plan to support Solus OS, however you might be able to make it work by setting up every component manually:

- https://nvidia.github.io/nvidia-docker (optional)
- https://nvidia.github.io/nvidia-container-runtime
- https://nvidia.github.io/libnvidia-container
