### ISSUE TITLE
daemon.json conflicts with docker.service on Fedora 27

### ISSUE THREAD

**Issue by dgmackay** [NVIDIA/nvidia-docker#712]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
When I install nvidia-docker2, and try to start the docker daemon, it returns an error message, and will not start.

### 2. Steps to reproduce the issue
dnf install nvidia-docker2 (first time only, of course)
systemctl start docker

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
Installed nvidia-docker rpms.
nvidia-docker2-2.0.3-1.docker1.13.1.noarch
nvidia-container-runtime-2.0.0-1.docker1.13.1.x86_64
nvidia-container-runtime-hook-1.3.0-1.x86_64
libnvidia-container-tools-1.0.0-0.1.beta.1.x86_64
libnvidia-container1-1.0.0-0.1.beta.1.x86_64

output of journalctl -xe after systemctl start docker:
-- The start-up result is done.
Apr 21 10:35:54 jabberwock.macdev.com audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=registries comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 21 10:35:54 jabberwock.macdev.com audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=registries comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 21 10:35:54 jabberwock.macdev.com systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Apr 21 10:35:54 jabberwock.macdev.com dockerd-current[23054]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: runtimes: (from flag: [oci], from file: map[nvidia:map[path:/usr/bin/nvidia-container-runtime runtimeArgs:[]]])
Apr 21 10:35:54 jabberwock.macdev.com systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 10:35:54 jabberwock.macdev.com systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Apr 21 10:35:54 jabberwock.macdev.com audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=docker comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 21 10:35:54 jabberwock.macdev.com systemd[1]: docker.service: Unit entered failed state.
Apr 21 10:35:54 jabberwock.macdev.com systemd[1]: docker.service: Failed with result 'exit-code'.

contents of docker.service:
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target docker-containerd.service
Wants=docker-storage-setup.service
Requires=docker-containerd.service rhel-push-plugin.socket registries.service

[Service]
Type=notify
EnvironmentFile=/run/containers/registries.conf
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
Environment=GOTRACEBACK=crash
ExecStart=/usr/bin/dockerd-current \
          --add-runtime oci=/usr/libexec/docker/docker-runc-current \
          --default-runtime=oci \
          --authorization-plugin=rhel-push-plugin \
          --containerd /run/containerd.sock \
          --exec-opt native.cgroupdriver=systemd \
          --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
          --init-path=/usr/libexec/docker/docker-init-current \
          --seccomp-profile=/etc/docker/seccomp.json \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY \
          $REGISTRIES
ExecReload=/bin/kill -s HUP $MAINPID
TasksMax=8192
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0
Restart=on-abnormal
KillMode=process

[Install]
WantedBy=multi-user.target

I did see a reference in a closed trouble ticket to an nvidia-docker.service file that a Fedora user had while using nvidia-docker version 1.  That file was not provided in the version 2 rpms.  Was that an omission?

**Comment by dgmackay** [comment]
There was an issue with the installed fedora docker.  I ended up just getting docker-ce, and all is well.

**Comment by flx42** [comment]
You're using `docker-ce` now, but FYI I've documented the proper installation for this setup here:
https://github.com/NVIDIA/nvidia-docker#centos-7-docker-rhel-7475-docker

**Comment by fujie317** [comment]
I had hard time using swarm with docker. I need to set "live-restore" to false to make it work. But when I specify that option in "/etc/docker/daemon.json", docker failed to start with systemctl, which told me that there was a conflict between starting flag of docker and same option set in daemon.json. I took me a while to find where that "flag" was set. It turned out there was a line OPTIONS='--selinux-enabled --log-driver=journald --live-restore'. Deleting that "--live-restore" part and restart docker with systemctl worked, "docker swarm init" worked, too. Hope that helps. It appears this is a unique fedora set-up problem, not Unix docker in general.

**Comment by alphaDev23** [comment]
@fujie317 Thank you for commenting.  Your comment helped me resolve the issue.  While this is a docker/systemd issue, it is very frustrating when debugging turns into trial and error and google searching on non-descriptive terms because the logs do not identify the problem.  Nonsense.

Thank you again; you saved me a significant amount of time.
