### ISSUE TITLE
404 when trying to get ubuntu17.10/nvidia-docker.list

### ISSUE THREAD

**Issue by abaybektursun** [NVIDIA/nvidia-docker#713]
### 1. Issue or feature description
I am using official Ubuntu 17.10, when I try to add the package repositories,
https://nvidia.github.io/nvidia-docker/ubuntu17.10/nvidia-docker.list returns 404 and messes up my local nvidia-docker.list file.

### 2. Steps to reproduce the issue
If you have 
```bash
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```

**Comment by flx42** [comment]
hello, ubuntu 17.10 is not supported. The next one to be supported will be ubuntu 18.04 (in 1-2 weeks).

**Comment by flx42** [comment]
you can use the ubuntu 16.04 repo in the meantime, thanks.
