### ISSUE TITLE
Not able to run the docker with nvidia runtime 

### ISSUE THREAD

**Issue by pankajniet** [NVIDIA/nvidia-docker#715]
getting following error when trying to test/run the docker on centos7:

#docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=9244 /var/lib/docker/devicemapper/mnt/1a943f4be18626734c28e87e0badaf4aaf00e215eeeee9cbe72e7938458d8de2/rootfs]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.

**Comment by flx42** [comment]
Please re-open with more information.
