### ISSUE TITLE
Unable to locate package nvidia-docker2 when installing using apt-get

### ISSUE THREAD

**Issue by abdallahmohammed197** [NVIDIA/nvidia-docker#716]
_I've tried installing nvidia-docker2 using apt-get through terminal but it keeps showing me this output _

sudo apt-get install nvidia-docker2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvidia-docker2

i used to install nvidida-docker2 
`sudo apt-get update`
 `sudo apt-get install nvidia-docker2`

---

### i am using

 - [ ] `Linux ab 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

 - [ ] red kernel output lines from `dmesg`
`[    2.808644] sd 3:0:0:0: [sdb] No Caching mode page found
[    2.808647] sd 3:0:0:0: [sdb] Assuming drive cache: write through
[    2.808644] sd 3:0:0:0: [sdb] No Caching mode page found
[    2.808647] sd 3:0:0:0: [sdb] Assuming drive cache: write through`
 - [ ] when i run `nvidia-smi -a` output is: `nvidia-smi: `command` not found`

 - [ ] Docker version from `docker version`:
 `Version:`	18.03.0-ce
 API version:	`1.37`

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  nvidia-390     390.48-0ubun amd64        NVIDIA binary driver - version 39
un  nvidia-common  <none>       <none>       (no description available)
un  nvidia-driver- <none>       <none>       (no description available)
un  nvidia-legacy- <none>       <none>       (no description available)
un  nvidia-libopen <none>       <none>       (no description available)
un  nvidia-libopen <none>       <none>       (no description available)
un  nvidia-opencl- <none>       <none>       (no description available)
ii  nvidia-opencl- 390.48-0ubun amd64        NVIDIA OpenCL ICD
un  nvidia-persist <none>       <none>       (no description available)
ii  nvidia-prime   0.8.2        amd64        Tools to enable NVIDIA's Prime
ii  nvidia-setting 396.18-0ubun amd64        Tool for configuring the NVIDIA g
un  nvidia-setting <none>       <none>       (no description available)
un  nvidia-smi     <none>       <none>       (no description available)
un  nvidia-vdpau-d <none>       <none>       (no description available)
```

 - [ ] NVIDIA container library version from `nvidia-container-cli -V` output is: 
`nvidia-container-cli: command not found`

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment]
Are you on ubuntu 14.04? If yes, you are facing the following problem: #714 
It's not a problem we can fix on our side though, I've contacted the GitHub support.

**Comment by abdallahmohammed197** [comment]
@flx42 i am actually in ubuntu 16.04 LTS

**Comment by flx42** [comment]
Ok, what were the instructions you followed? Do you have any error message when adding the repository?

**Comment by abdallahmohammed197** [comment]
I've followed the instructions listed in this page [Installation (version 2.0)](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0))

i've tried removing nvidia-docker v1 at first like in the instructions using 
`docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f`
`sudo apt-get purge nvidia-docker`
the output for the second command was:
`E: Unable to locate package nvidia-docker`

Afterward tried to install nvidia-docker2 using:
`sudo apt-get install nvidia-docker2`
the output was:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvidia-docker2
```

**Comment by abdallahmohammed197** [comment]
I fixed the issue by adding the repository at first from here [https://nvidia.github.io/nvidia-docker/](https://nvidia.github.io/nvidia-docker/)

**Comment by Johnnyswong** [comment]
@abdallah197 I can't understand the Repository configuration step in the link.

`curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update`

What is $ID and $VERSION_ID in this configuration?

**Comment by bryanbocao** [comment]
Share my experience on Ubuntu 18.04 and 20.04.5
https://github.com/bryanbocao/quick-cheatsheets/issues/3#issuecomment-1092131051
