### ISSUE TITLE
Issues to install nvidia-docker2 in Ubuntu

### ISSUE THREAD

**Issue by tiagokv** [NVIDIA/nvidia-docker#717]
### 1. Issue or feature description

I'm trying to download and install `nvidia-docker2`, however the unmet dependency message pops-up.
Tried to pin the version, but no luck (see below). What am I doing wrong?

### 2. Steps to reproduce the issue

```shell
$ sudo apt-get install nvidia-docker2=2.0.3+docker17.12.1-1 nvidia-container-runtime=2.0.0+docker17.12.1-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 17.12.1~ce-0~ubuntu) but it is not installable or
                           docker-ee (= 17.12.1~ee-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Kernel version: 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Nvidia-smi: Successfully executed.
Docker version: Docker version 17.12.1-ce, build 7390fc6 (Docker.io installation)
Ubuntu version: Ubuntu 18.04
Nvidia-container-cli -V:
```
version: 1.0.0
build date: 2018-04-20T02:18+00:00
build revision: 8a946dc7bfcef6aa48d4a6a3c796617f876f1fca
build compiler: x86_64-linux-gnu-gcc-7 7.3.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```

**Comment by flx42** [comment]
>  Docker version: Docker version 17.12.1-ce, build 7390fc6 (Docker.io installation)

I guess you have ubuntu 18.04 then? We didn't release packages for this distro yet, it will happen very soon.

**Comment by tiagokv** [comment]
Would building from the source solve this?

**Comment by flx42** [comment]
no, but using the `docker-ce` package would.

**Comment by tiagokv** [comment]
Hum... It seems that only nightly builds from `docker-ce` are available for 18.04 and only for 18.05 version. I think there's no runaway them.
Is it obligatory to have `nvidia-docker2` to run a container with Nvidia integration? Running `docker run --runtime=nvidia [...]` was working except OpenGL within it (maybe it was another issue?)

**Comment by flx42** [comment]
You can use the xenial repository of docker-ce on 18.04, it works fine, I'm doing that right now.
But also, 18.04 is not officially released until... tomorrow. So I guess docker is also waiting for that.

**Comment by tiagokv** [comment]
Installing docker-ce from 16.04 worked and also doing the apt install with nvidia-docker2

**Comment by jongsepark** [comment]
Can we install nvidia-docker2 on 18.04 LTS???

**Comment by flx42** [comment]
@jongsepark sure, there are packages now.

**Comment by jongsepark** [comment]
Yes, it is what I'm seeing. Glad to know that it will be released soon! :)

**Comment by alshedivat** [comment]
Any update on `docker-ce `? It seems there's a version released for bionic (`18.03.1~ce-0~ubuntu`).

**Comment by flx42** [comment]
@alshedivat
Are you sure? Which repo do you have configured?
Compare 
https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/
vs
https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

**Comment by alshedivat** [comment]
@flx42 ah my mistake, looks like it's still xenial, got confused by the `18` in the version.

**Comment by olramde** [comment]
I installed docker-ce 18.05. However, installing nvidia-docker2 introduces a dependency error. (nvidia-docker2: Depends: docker-ce (= 18.03.1 ~ ce-0 ~ ubuntu) but it is not going to be installed or docker-ee (= 18.03.1 ~ ee-0 ~ ubuntu but it is not installable ) I use Ubuntu 18.04 LTS.

**Comment by petecog** [comment]
@olramde  i'm meeting the same issue. First time trying to use nvidia-docker since 18.04 upgrade. Did you manage to work around?

**Comment by flx42** [comment]
`docker-ce` is still not release for Ubuntu 18.04:
https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

If you want to use `docker-ce` released for xenial, you also need to use `nvidia-docker` for xenial.
Otherwise, use the `docker.io` package from Canonical.

**Comment by petecog** [comment]
ah, great. thanks for the clarification. I was getting stuck becuse I was trying to use bionic nvidia-docker.

**Comment by sisirkp** [comment]
I think docker-ce has come for Ubuntu 18.04 now. 
https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

**Comment by flx42** [comment]
Ubuntu 18.10 is not a LTS release, I don't think we will release packages for it.

**Comment by zixia** [comment]
Hmm... So I have to downgrade my desktop to 18.04 in order to use `nvidia-docker`?

It's not very convenient... sad.

**Comment by flx42** [comment]
@zixia You will have to use the 18.04 packages, it's likely to work, but `docker-ce` isn't even officially released on 18.10 AFAIK, so some manual process will be involved.

**Comment by drozzy** [comment]
This would be really useful to have. Is it hard to do?

**Comment by drozzy** [comment]
> I released packages for 18.04 today. It only supports `docker.io` for now, since I don't see a `docker-ce` package for bionic yet.

How do we install nvidia-docker with docker.io? Do we still follow this tutorial?
https://github.com/NVIDIA/nvidia-docker/blob/master/README.md#quickstart

In that case, `https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/nvidia-docker.list` shows "Unsupported distribution".

Thank you.

**Comment by drozzy** [comment]
Solution found here: https://github.com/NVIDIA/nvidia-docker/issues/848

```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

sudo apt-get install -y nvidia-docker2
sudo pkill -SIGHUP dockerd
```

**Comment by luna1230** [comment]
Hi @drozzy , I use the solution you metioned for  Ubuntu 16.04.5 LTS, but nvidia-docker2 still can't be installed . 
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.0~3-0~ubuntu-xenial) but it is not installable or
                           docker-ee (= 5:18.09.0~3-0~ubuntu-xenial) but it is not installable

**Comment by RenaudWasTaken** [comment]
Hello @luna1230 what is your version of docker?

It's likely you will have to pin the docker version: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version
