### ISSUE TITLE
nvidia-docker2 has unmet dependencies that are installed

### ISSUE THREAD

**Issue by Aidan-Kehoe** [NVIDIA/nvidia-docker#719]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
`The following packages have unmet dependencies:`
  `nvidia-docker2: Depends: docker-ce (= 18.03.0~ce-0~ubuntu) but 18.03.0~ce-0~ubuntu is to be installed`
`E: unable to correct problems, you have held broken packages.`
Note that this version of docker has been installed. Furthermore, the FAQ that has been referenced in previous issues has not helped this particular instance.

### 2. Steps to reproduce the issue
I installed docker-ce by following the instructions in their documentation.
When I try to install nvidia-docker2 using the following command: `sudo apt-get install -y nvidia-docker2` I get the error above. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by lukeyeager** [comment]
Me too. Here's the error I'm getting:
```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 18.03.0~ce-0~ubuntu) but 18.03.1~ce-0~ubuntu is to be installed or
                           docker-ee (= 18.03.0~ee-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by flx42** [comment]
@Aidan-Kehoe your issue doesn't make sense, we didn't release nvidia-docker2 for this version. can you provide the output of `dpkg -l '*nvidia*'`?

@lukeyeager your problem was simply that docker released 18.03.1 this morning, and we didn't have a nvidia-docker2 package matching this version. It's now done, please check.

**Comment by lukeyeager** [comment]
Good timing! I just verified that we're back in business. Thanks!

**Comment by Aidan-Kehoe** [comment]
@flx42 Sorry, I edited my original comment. The error was 18.03.0 not 18.02.0. Is the fix now that I must update docker-ce to 18.03.1? Just in case, here are the outputs to what you asked:


`dpkg -l '*nvidia*':`
`Desired=Unknown/Install/Remove/Purge/Hold`
`| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend`
`|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)`
`||/ Name           Version      Architecture Description`
`+++-==============-============-============-=================================`
`ii  nvidia-375     390.30-0ubun amd64        Transitional package for nvidia-3`
`ii  nvidia-390     390.48-0ubun amd64        NVIDIA binary driver - version 39`
`un  nvidia-common  <none>       <none>       (no description available)`
`un  nvidia-driver- <none>       <none>       (no description available)`
`un  nvidia-legacy- <none>       <none>       (no description available)`
`un  nvidia-libopen <none>       <none>       (no description available)`
`un  nvidia-libopen <none>       <none>       (no description available)`
`un  nvidia-opencl- <none>       <none>       (no description available)`
`ii  nvidia-opencl- 390.48-0ubun amd64        NVIDIA OpenCL ICD`
`un  nvidia-persist <none>       <none>       (no description available)`
`ii  nvidia-prime   0.8.5        amd64        Tools to enable NVIDIA's Prime`
`ii  nvidia-setting 396.18-0ubun amd64        Tool for configuring the NVIDIA g`
`un  nvidia-setting <none>       <none>       (no description available)`
`un  nvidia-smi     <none>       <none>       (no description available)`
`un  nvidia-vdpau-d <none>       <none>       (no description available)`

`dpkg -l '*docker*':`
`Desired=Unknown/Install/Remove/Purge/Hold`
`| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend`
`|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)`
`||/ Name           Version      Architecture Description`
`+++-==============-============-============-=================================`
`un  docker         <none>       <none>       (no description available)`
`ii  docker-ce      18.03.1~ce-0 amd64        Docker: the open-source applicati`
`un  docker-contain <none>       <none>       (no description available)`
`un  docker-doc     <none>       <none>       (no description available)`
`un  docker-ee      <none>       <none>       (no description available)`
`un  docker-engine  <none>       <none>       (no description available)`
`un  docker-engine- <none>       <none>       (no description available)`
`un  docker-runc    <none>       <none>       (no description available)`
`rc  docker.io      1.13.1-0ubun amd64        Linux container runtime`
`un  lxc-docker     <none>       <none>       (no description available)`
`un  lxc-docker-vir <none>       <none>       (no description available)`

**Comment by STH-Dev** [comment]
Same thing. Seems to happen every time the latest docker version changes:
```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 18.03.1~ce-0~ubuntu) but 18.04.0~ce~3-0~ubuntu is to be installed or
                           docker-ee (= 18.03.1~ee-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by STH-Dev** [comment]
Totally correct. flx42 - it is /etc/apt/sources.list.d/docker.list which is added by the docker auto-install script.

For anyone else, changing the docker.list from edge to stable fixes this.

Still, it would be nice if this just worked.

**Comment by flx42** [comment]
Wait, which docker auto-install script?
If you're still using `https://get.docker.com/`, that has not been the recommended way for a long time :)

The official instructions for ubuntu will make you install the `stable` repository only:
https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by Aidan-Kehoe** [comment]
@flx42 Yes it is, thank you very much.

**Comment by flx42** [comment]
Closing, the original problem was fixed.

**Comment by futurianh1k** [comment]
Recently I have same error on Ubuntu 18.04, CUDA 10
I have been using 410.48 included in CUDA10 installer.
After upgrading to 410.78, I could restart my docker.
