### ISSUE TITLE
cuDNN 5 Images

### ISSUE THREAD

**Issue by cancan101** [NVIDIA/nvidia-docker#72]
Looks like the RC for cuDNN 5 is out: https://developer.nvidia.com/cudnn

**Comment by flx42** [comment]
It will be done as soon as cuDNN is released! (out of RC).

**Comment by flx42** [comment]
Push to DockerHub incoming.

**Comment by tboquet** [comment]
@flx42 Tx for the support! I was searching for the tag in the wiki and it's not there yet, I had to verify on docker hub.

**Comment by flx42** [comment]
@tboquet: good call! I updated the wiki and the DockerHub front page for cuda.
Thanks!
