### ISSUE TITLE
Distribution "amzn2018.03" missing

### ISSUE THREAD

**Issue by efrainsteinbach** [NVIDIA/nvidia-docker#722]
I'm running an Amazon Linux image `amzn-ami-2017.09.l-amazon-ecs-optimized` on my EC2 VM. Following the [repo setup](https://nvidia.github.io/nvidia-docker/) for CentOS/RHEL-based distributions, I get this 'distribution' variable defined:

```
[root@x]# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
[root@x]# echo $distribution
amzn2018.03
```

But I get a 404 page at the URL of the subsequent curl:
https://nvidia.github.io/nvidia-docker/amzn2018.03/nvidia-docker.repo

I'm sorry if this is completely ignorant, I'm not familiar with Amazon/CentOS/Nvidia linux distributions.

Could someone tell me alternative 'distributions' (or AMIs that support ECS) that may work? Or simply a way to list the available distributions?

--

Kernel: 4.9.85-38.58.amzn1.x86_64 #1 SMP Wed Mar 14 01:17:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(I don't have nvidia-smi installed yet.)

**Comment by avimanyu786** [comment]
@efrainsteinbach Are you looking for this: 
https://nvidia.github.io/nvidia-docker/amzn2/nvidia-docker.repo ?

**Comment by flx42** [comment]
Fixed by https://github.com/NVIDIA/nvidia-docker/commit/f73a8da39be9601e0372ba7704554c0af3220c55
Please try again!

**Comment by efrainsteinbach** [comment]
sorry, yep, that works - thanks a lot!
