### ISSUE TITLE
nnvidia-container-cli: driver error: timed out when persistence mode is disabled | Azure N-nvidiaSeries VMs 

### ISSUE THREAD

**Issue by msLinuxNinja** [NVIDIA/nvidia-docker#723]
Hey NVIDIA!
### **1. Issue or feature description**
When running the sample **docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi** throws error:

[root@RH74NV yum.repos.d]# docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=4107 /var/lib/docker/overlay2/3d396bcc61c0fb4464b82f7b5d38acaf438bbdd4cf7bce2bba00a8869a582f58/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.

### **2. Steps to reproduce the issue**
Run command docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi with persistence mode disabled.
### **3. Information to [attach]**
 -Kernel version from `uname -a` 
[root@RH74NV yum.repos.d]# uname -a
Linux RH74NV 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 -**Driver information from `nvidia-smi -a`**
[root@RH74NV yum.repos.d]# nvidia-smi
Thu May  3 18:03:18 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+

 -**Docker version from `docker version`**
[root@RH74NV yum.repos.d]# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

 -**Docker command, image and tag used**
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi

**Extra Info**

It takes roughly a minute and a half on a NC24 VM (4 K80 GPUs) for nvidia-smi to return anything when either persistence mode or the persistenced daemon are disabled.

When persistence mode is enabled it takes about 4 seconds for nvidia-smi to query the GPUs.

The expected behavior would be for docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi to take longer to respond when persistence mode is disabled rather than error out.

Posibly related to #628 

Thanks!

**Comment by yee379** [comment]
after digging around the nvidia forums, it seemed like i could lower the latency running of nvidia-smi by keeping it in the backgroup with `nvidia-smi -l -i 0`. so i did that and then separately ran 

    # docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
    standard_init_linux.go:178: exec user process caused "permission denied"

**Comment by flx42** [comment]
@yee379 the `permission denied` is probably a different issue.

CUDA or NVML initialization might hangs, it might happen when the kernel module is encountering a problem. That's why we need the timeout, and that's also why we need to run those initializations in separate processes. It would be tricky to detect persistence mode because, well, you need to initialize NVML for that. I strongly recommend that you enable `nvidia-persistenced`, running `nvidia-smi` in a loop is not the right solution :)
