### ISSUE TITLE
Is nvidia-docker 2 support for MPS ready for production work load?

### ISSUE THREAD

**Issue by hehaifengcn** [NVIDIA/nvidia-docker#728]
Hi Nvidia-docker team

There is an open issue around MPS support (https://github.com/NVIDIA/nvidia-docker/issues/419) where @3XX0 answered that "With 2.0 it should work as long as you run the MPS server on the host and use --ipc=host. We're working torward a better integration though". 

I did some basic tests and confirmed that. Before MPS is officially supported by nvidia-docker (would be nice to know the timeline), would you recommend to run nvidia-docker v2 under MPS as it is for production or only for experimenting? Anything we should pay attention to?

If you think this question duplicates #419, feel free to close this one. 

Thanks

**Comment by WIZARD-CXY** [comment]
@hehaifengcn I run the command in #419 which 3xx0 provide. 
`
# Launch two containers on the second GPU device
sudo CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=1 nvidia-cuda-mps-control -d

docker run -ti --rm -e NVIDIA_VISIBLE_DEVICES=1 --runtime=nvidia --ipc=host nvidia/cuda
docker run -ti --rm -e NVIDIA_VISIBLE_DEVICES=1 --runtime=nvidia --ipc=host nvidia/cuda

echo quit | sudo nvidia-cuda-mps-control

`
But it didn't work out. How did you test it works? I didn't see logs in /var/log/nvidia-mps/control.log?

**Comment by flx42** [comment]
@WIZARD-CXY make sure the mps server is running properly. it probably didn't start

@hehaifengcn it's a complex question.
Excluding containers, MPS Volta is production ready. If we introduce MPS clients running in containers, then it's not a use case that's extensively tested by us, but if you do encounter an issue we will do our best to fix it or report it to the MPS team internally. A few recommendations:
- You clearly want to increase the size of `/dev/shm` with `--shm-size` (for Docker), it useful for MPS but also for many deep learning frameworks.
- You should also set the GPU in exclusive mode as a safety measure.
- With a NUMA system, make sure to pin the MPS server to the CPU sockets of the GPU(s).

The "better" integration would be to have libnvidia-container handle the lifecycle of the MPS server and all the details mentioned above.

**Comment by flx42** [comment]
Closing this one since we already have #419
