### ISSUE TITLE
"Error: unsupported Docker version"

### ISSUE THREAD

**Issue by stefanseefeld** [NVIDIA/nvidia-docker#73]
Simply trying to follow the documented steps to install and test nvidia-docker yields the above error message. I'm running docker 1.11.0 (build 4dc5990), on an Ubuntu 14.04 system.

**Comment by flx42** [comment]
Docker 1.11.0 was released yesterday, 30 minutes later I added support to nvidia-docker: 839fe262d2e26721c7d03a3dd173c84a5fe7a348

It's not part of the deb package or the tarball yet, we will create a new release soon.
In the mean time you can build the binaries, the tarball or the deb manually:
https://github.com/NVIDIA/nvidia-docker/wiki/Installation#building-from-sources

**Comment by stefanseefeld** [comment]
Oh, sounds like bad timing ! (I hadn't even realized that I upgraded my docker installation this morning to such a fresh version. :-) )
Thanks for addressing this so quickly !

**Comment by lazyest** [comment]
just to understand where I'm wrong, I've build nvidia-docker from sources, after trying to run getting this error:
nvidia-docker run --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/VolumeDriver.Mount: dial unix /var/lib/nvidia-docker/nvidia-docker.sock: connect: no such file or directory.

**Comment by lazyest** [comment]
well, I've recreate socket dir, seems to got functional one but now I'm having 
nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker-plugin | 2016/04/19 01:32:51 Received mount request for volume 'nvidia_driver_352.79'
nvidia-docker-plugin | 2016/04/19 01:32:51 Received mount request for volume 'nvidia_driver_352.79'
nvidia-docker-plugin | 2016/04/19 01:32:51 Received unmount request for volume 'nvidia_driver_352.79'
docker: Error response from daemon: no such volume: nvidia_driver_352.79.

this time I'm really confused :-/

**Comment by lazyest** [comment]
better result I've got is docker: Error response from daemon: no such volume: nvidia_driver_352.79.

**Comment by 3XX0** [comment]
How did you install it? through the deb or using `make install`?
Looks like your volume didn't get created properly. Do you have a "create request" in the logs?
What's in `/var/lib/nvidia-docker`?

**Comment by lazyest** [comment]
I've tried both ways indeed
First I've done make deb and install it
After tried to reinstall from bundled deb to (maybe) restore config
After tried to make install
ls -l /var/lib/docker/
total 28
drwx------  5 root          root   4096 Mar 24 15:38 aufs
drwx------ 31 root          root   4096 Apr 19 03:21 containers
drwx------  3 root          root   4096 Mar 24 15:38 image
drwxr-x---  3 root          root   4096 Mar 24 15:38 network
drwx------  3 root          root   4096 Apr 19 03:07 tmp
drwx------  2 root          root   4096 Mar 24 15:38 trust
drwx------ 25 nvidia-docker docker 4096 Apr 19 03:18 volumes

Maybe there is a doc about proper way of recreating volume?

**Comment by lazyest** [comment]
Maybe I can just remove/purge nvidia-docker and install back self-compiled deb? Didn't tried it for uncertain reasons :-)

**Comment by 3XX0** [comment]
Your installation looks really wrong, you shouldn't have anything related to `nvidia-docker` in `/var/lib/docker/` unless you did it manually.

Try purging `nvidia-docker` and reinstalling the deb. By default things will be installed in `/var/lib/nvidia-docker` not `/var/lib/docker/`

```sh
sudo apt-get purge nvidia-docker
make deb
dpkg -i [...]nvidia-docker.deb
```

Then try to run the `nvidia-smi` example and check the log of the plugin `/var/log/upstart/nvidia-docker.log`.

If you still have issues, I suggest you open a new issue so that we can track it properly.

**Comment by lazyest** [comment]
ok
