### ISSUE TITLE
Using apt-mirror to mirror repositories

### ISSUE THREAD

**Issue by NetAppRepoAdmin** [NVIDIA/nvidia-docker#730]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

---

1. I need to create a mirror of these apt repositories to move them to an environment without internet connection.  Using the repo URLs that get created in the source.list file for apt do not enable apt-mirror to work.

2. Steps to reproduce the issue
apt-mirror configuration file

```
############# config ##################
set base_path    /mnt/mirror/nvidia
set run_postmirror 0
set nthreads     20
set _tilde 0
############# end config ##############

deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64 /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64 /
deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64 /

clean https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64/
clean https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64/
clean https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/
```

I get the following errors when running apt-mirror
```
Psh: 1: cannot open nvidia.github.io/libnvidia-container/ubuntu16.04/amd64////Packages.gz: No such file
apt-mirror: can't open index in process_index_gz at /usr/bin/apt-mirror line 678.
Use of uninitialized value $distribution in concatenation (.) or string at /usr/bin/apt-mirror line 759.
Psh: 1: cannot open nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64////Packages.gz: No such file
apt-mirror: can't open index in process_index_gz at /usr/bin/apt-mirror line 678.
Use of uninitialized value $distribution in concatenation (.) or string at /usr/bin/apt-mirror line 759.
Psh: 1: cannot open nvidia.github.io/nvidia-docker/ubuntu16.04/amd64////Packages.gz: No such file
apt-mirror: can't open index in process_index_gz at /usr/bin/apt-mirror line 678.
```

I'm guessing some aspect of the issue is that github.io is an object store, not a file system based website, so something is not quite correct in the built paths and the Packages.gz files cannot be found

**Comment by flx42** [comment]
Mmm it's just that `Packages.gz` does **not** exist, but `Packages.xz` does:
https://github.com/NVIDIA/nvidia-docker/tree/gh-pages/ubuntu16.04/amd64
Looks like it's a bug with `apt-mirror`.

**Comment by NetAppRepoAdmin** [comment]
I had to manually update to the latest apt-mirror script.  The version I had on my system did not handle the .xz files.
