### ISSUE TITLE
permission denied starting new container

### ISSUE THREAD

**Issue by yee379** [NVIDIA/nvidia-docker#731]
### 1. Issue or feature description

i seem unable to run a container normally:

    # getenforce
    Permissive

    # docker run -it nvidia/cuda nvidia-smi
    standard_init_linux.go:178: exec user process caused "permission denied"

    # docker run -it nvidia/cuda sh -c "nvidia-smi"
    Tue May  8 23:37:48 2018
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 390.42                 Driver Version: 390.42                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  Tesla K80           Off  | 00000000:06:00.0 Off |                    0 |
    | N/A   27C    P8    26W / 149W |      0MiB / 11441MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+

this consequently is causing issues for my nvidia/k8s-device-plugin containers for kubernetes.

### 2. Steps to reproduce the issue

    # yum install -y nvidia-container-runtime-hook

    # yum install --downloadonly --downloaddir=/tmp/  nvidia-docker2-2.0.3-1.docker1.13.1.noarch nvidia-container-runtime-2.0.0-1.docker1.13.1.x86_64

    # rpm -Uhv --replacefiles /tmp/nvidia-container-runtime-2.0.0-1.docker1.13.1.x86_64.rpm /tmp/nvidia-docker2-2.0.3-1.docker1.13.1.noarch.rpm

    # sudo systemctl restart docker
    Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

    # cat <<EOF > /etc/systemd/system/docker.service.d/override.conf
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd-current --add-runtime=nvidia=/usr/bin/nvidia-container-runtime --default-runtime=nvidia --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current  \$OPTIONS \$DOCKER_STORAGE_OPTIONS \$DOCKER_NETWORK_OPTIONS \$ADD_REGISTRY \$BLOCK_REGISTRY \$INSECURE_REGISTRY \$REGISTRIES

    EOF

    # cat  /etc/docker/daemon.json
    {
    }

    # systemctl daemon-reload
    # sudo systemctl restart docker

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

    # uname -a
    Linux ocio-gpu01 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

    # docker --version
    Docker version 1.13.1, build 774336d/1.13.1

    # nvidia-smi
    Tue May  8 10:37:55 2018
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
    ...

    # nvidia-container-cli -V
    version: 1.0.0
    build date: 2018-04-26T23:10+0000
    build revision: 163054a04b21c4455c8cae7e47873d9f2a091f55
    build compiler: gcc 4.8.5 20150623 (Red Hat 4.8.5-16)
    build platform: x86_64
    build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

**Comment by flx42** [comment]
You should be able to install `nvidia-container-runtime` the normal way, without downloading the rpm. Why are you doing that?
Also, if you are registering the `nvidia` runtime manually, you don't even need to install the `nvidia-docker2` package.

Anything in `dmesg`?

**Comment by yee379** [comment]
hey @flx42, i thought `nvidia-container-runtime` needs to match the docker version i have, that's why i did an rpm download. "out of the box", after installing `nvidia-docker2`, docker complains about the duplicate runtime definitions - thats why i had to override systemctl and daemon.json.

in one terminal i run:

    # getenforce
    Permissive

    # docker run  --rm nvidia/cuda nvidia-smi
    standard_init_linux.go:178: exec user process caused "permission denied"

and in the another i run:

    # dmesg -wH

    [May11 15:26] docker0: port 1(veth24ec631) entered blocking state
    [  +0.007183] docker0: port 1(veth24ec631) entered disabled state
    [  +0.007228] device veth24ec631 entered promiscuous mode
    [  +0.006685] IPv6: ADDRCONF(NETDEV_UP): veth24ec631: link is not ready
    [  +0.123570] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
    [  +0.064778] IPv6: ADDRCONF(NETDEV_CHANGE): veth24ec631: link becomes ready
    [  +0.008370] docker0: port 1(veth24ec631) entered blocking state
    [  +0.007284] docker0: port 1(veth24ec631) entered forwarding state
    [  +2.114437] docker0: port 1(veth24ec631) entered disabled state
    [  +0.031442] docker0: port 1(veth24ec631) entered disabled state
    [  +0.025850] device veth24ec631 left promiscuous mode
    [  +0.006112] docker0: port 1(veth24ec631) entered disabled state

**Comment by flx42** [comment]
You can just do:
```
sudo yum install -y nvidia-container-runtime-2.0.0-1.docker1.13.1
```
And don't install the `nvidia-docker2` package if you modify the sytemd configuration, you won't get any conflict this way.

What's the output of `docker info`? 
And `sestatus`?

**Comment by yee379** [comment]
# docker info
    Containers: 48
     Running: 6
     Paused: 0
     Stopped: 42
    Images: 8
    Server Version: 1.13.1
    Storage Driver: overlay2
     Backing Filesystem: extfs
     Supports d_type: true
     Native Overlay Diff: true
    Logging Driver: journald
    Cgroup Driver: systemd
    Plugins:
     Volume: local
     Network: bridge host macvlan null overlay
    Swarm: inactive
    Runtimes: nvidia runc
    Default Runtime: nvidia
    Init Binary: docker-init
    containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
    runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f-dirty (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
    init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
    Security Options:
     seccomp
      Profile: default
     selinux
    Kernel Version: 3.10.0-693.21.1.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    OSType: linux
    Architecture: x86_64
    Number of Docker Hooks: 3
    CPUs: 48
    Total Memory: 251.3 GiB
    Name: ocio-gpu01
    ID: YOGV:NAPA:TMIF:TOD3:D32H:FCEP:GT3X:BDC7:VX4J:GVBM:U5BK:THWK
    Docker Root Dir: /opt/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    Experimental: false
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false
    Registries: docker.io (secure)


    # sestatus
    SELinux status:                 enabled
    SELinuxfs mount:                /sys/fs/selinux
    SELinux root directory:         /etc/selinux
    Loaded policy name:             targeted
    Current mode:                   permissive
    Mode from config file:          enforcing
    Policy MLS status:              enabled
    Policy deny_unknown status:     allowed
    Max kernel policy version:      28

**Comment by flx42** [comment]
Ah, forgot that with this version of docker you don't need `nvidia-container-runtime`, just `nvidia-container-runtime-hook`. Then, you can just copy the binary to the hook folder from Docker, more details here:
https://github.com/projectatomic/docker/tree/docker-17.03.1-ce#add-dockerhooks-exec-custom-hooks-for-prestartpoststop-containerspatch

It might not fix your problem though... does fully disabling SELinux changes anything?
