### ISSUE TITLE
Azure deployment - can't SSH: exit status 255

### ISSUE THREAD

**Issue by daltskin** [NVIDIA/nvidia-docker#732]
Following Azure deployment guide: https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Azure

Using docker-machine.exe (version 0.14.0, build 89b8332) on Windows 10 PowerShell (running as Admin)

Run:
`
docker-machine create --driver azure --azure-subscription-id <subkey-removed>
 -azure-location 'North Europe' --azure-size Standard_NV6 --azure-image canonical:UbuntuServer:16.04.0-LTS:latest azure01`

Returns:
`
Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`

Subsequent ssh attempts:

`docker-machine ssh azure01`

Returns:

`exit status 255`

Also, when will the guide be updated to v2.0?

Thanks,

**Comment by flx42** [comment]
> Also, when will the guide be updated to v2.0?

When we have an official image for Azure that includes the NVIDIA driver and nvidia-docker v2
