### ISSUE TITLE
After Driver Upgrade: docker: Error response from daemon: create nvidia_driver_396.24: VolumeDriver.Create: internal error, check logs for details.

### ISSUE THREAD

**Issue by vfbsilva** [NVIDIA/nvidia-docker#735]
### 1. Issue or feature description
Whenever I try to run a nvidia-docker container it reports: docker: Error response from daemon: create nvidia_driver_396.24: VolumeDriver.Create: internal error, check logs for details.

```
journalctl -n -u nvidia-docker:
mai 09 22:59:23 mordor nvidia-docker-plugin[2550]: /usr/bin/nvidia-docker-plugin | 2018/05/09 22:59:23 Received create request for volume 'nvidia_driver_396.24'
mai 09 22:59:23 mordor nvidia-docker-plugin[2550]: /usr/bin/nvidia-docker-plugin | 2018/05/09 22:59:23 Error: link /usr/bin/nvidia-cuda-mps-control /var/lib/nvidia-docker/>
```
~

### 2. Steps to reproduce the issue
Run a command like:
`nvidia-docker run nvidia/cuda nvidia-smi`
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`: Linux mordor 4.14.39-1-MANJARO #1 SMP PREEMPT Wed May 2 19:03:39 UTC 2018 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`: [  174.982949] nvidia-uvm: Loaded the UVM driver in 8 mode, major device number 239

 - [ ] Driver information from `nvidia-smi -a`:
Driver Version                      : 396.24

 - [ ] Docker version from `docker version`:  Version:       18.04.0-ce

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`: 396.24

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`: version: 1.0.0

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used: nvidia-docker run nvidia/cuda nvidia-smi

**Comment by flx42** [comment]
The log is truncated.

Any reason why you are not using nvidia-docker v2?

**Comment by vfbsilva** [comment]
@flx42 thanks for the swift reply. I did as you suggested and migrated to v2 and seems the issue is gone thanks a lot.

**Comment by Tchaikovic** [comment]
I have the same problem with nvidia-docker 1. I'm working with Ubuntu16.04.

error is: 
`
docker: Error response from daemon: create nvidia_driver_440.33.01: VolumeDriver.Create: internal error, check logs for details.
`

This error happened after a updated my cuda driver to 440.33.01 with CUDA 10.2 

I cannot use nvidia-docker 2, as that would not be compatible with OpenGL. 

This is the error log: 

Nov 28 22:31:16 lmi5604-CosmosVII-15 nvidia-docker-plugin[1463]: /usr/bin/nvidia-docker-plugin | 2019/11/28 22:31:16 Error: link /usr/lib32/nvidia-440/libnvidia-tls.so.440.33.01 /var/lib/nvidia-docker/volumes/nvidia_driver/440.33.01/lib/libnvidia-tls.so.440.33.01: file exists

Any idea on the why to solve this?

**Comment by vfbsilva** [comment]
Downgrade cuda?
