### ISSUE TITLE
caffe docker build error when make runtest.

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/nvidia-docker#739]
I want to build caffe in docker, my Dockerfile is as follows:

`FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04
MAINTAINER dongbin1@corp.netease.com

RUN apt-get update && apt-get install -y --no-install-recommends \
	libprotobuf-dev \
	libleveldb-dev \
	libsnappy-dev \
	libopencv-dev \
	libhdf5-serial-dev \
	protobuf-compiler \
	libboost-all-dev \
	libopenblas-dev \
	python-dev \
	libgflags-dev \
	libgoogle-glog-dev \
	liblmdb-dev \
	vim \
	python-pip \
	python-dev \
	python-numpy \
	build-essential \
	git \
	libatlas-base-dev \
	wget \
	zip \
	unzip && \
	rm -rf /var/lib/apt/lists/* 
RUN git config --global http.postBuffer 1048576000 
ENV CAFFE_ROOT=/root/
WORKDIR $CAFFE_ROOT

RUN pip install --upgrade pip
RUN ln /dev/null /dev/raw1394

RUN  wget https://github.com/BVLC/caffe/archive/master.zip && unzip master.zip && mv caffe-master caffe && rm master.zip && cd caffe && \
	cp Makefile.config.example Makefile.config && \
	pip install --disable-pip-version-check --upgrade pip && \
	pip install six --disable-pip-version-check --upgrade --ignore-installed six && \
	sed -i 's/CUDA_DIR := \/usr\/local\/cuda/CUDA_DIR := \/usr\/local\/cuda-8.0/g' Makefile.config && \
	sed -i 's/INCLUDE_DIRS := $(PYTHON_INCLUDE) \/usr\/local\/include/INCLUDE_DIRS := $(PYTHON_INCLUDE) \/usr\/local\/include \/usr\/include\/hdf5\/serial\/ \/usr\/local\/cuda-8.0\/targets\/x86_64-linux\/include/g' Makefile.config && \
	sed -i 's/LIBRARY_DIRS := $(PYTHON_LIB) \/usr\/local\/lib \/usr\/lib/LIBRARY_DIRS := $(PYTHON_LIB) \/usr\/local\/lib \/usr\/lib \/usr\/lib\/x86_64-linux-gnu\/hdf5\/serial\/ \/usr\/local\/cuda-8.0\/targets\/x86_64-linux\/lib/g' Makefile.config && \
	export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/cuda-8.0/targets/x86_64-linux/include/ && \
	make all -j8 && \
	make test -j8

RUN cd /root/caffe && make runtest -j8 && \
	cd python && \
	for req in $(cat requirements.txt); do pip install --disable-pip-version-check -i https://pypi.tuna.tsinghua.edu.cn/simple $req ; done && \
	cd .. && \
	make pycaffe && \
	export PYTHONPATH=/root/caffe/python:$PYTHONPATH && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /etc/apt/sources.list.d/*`

the build process is successful except the last RUN CMD, and I got errors when RUN make run test,
it says:
`E0518 06:43:38.770020   253 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0518 06:43:38.770401   253 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0518 06:43:38.770431   253 syncedmem.hpp:22] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version`

Then I comment the last RUN CMD, and build the image to caffe:no_runtest image, and I create a container based on the image, with docker run and nvidia-docker run respectively:
1. when run with docker:
`docker run -ti caffe:no_runtest bash
make test -j8
make runtest -j8`
I got the same error with the build log.
2. But when I run with nvidia-docker:
 `nvidia-docker run -ti caffe:no_runtest bash
make test -j8
make runtest -j8`
the code run without any error!   

I am so confused about that, and I want to know how I can build the image like in nvidia-docker run.
My GPU : 1080Ti,
Docker version:  17.09.0-ce
Please help me out,
Thank you very much.

**Comment by 3XX0** [comment]
If you need GPU support at build-time (e.g. run GPU test in this case), the only way is to configure your docker daemon to use the nvidia runtime by default.

https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#can-i-use-the-gpu-during-a-container-build-ie-docker-build

**Comment by Edwardmark** [comment]
@3XX0  Thank you very much, guy.
Best, 
Edward
