### ISSUE TITLE
dpkg: dependency problems

### ISSUE THREAD

**Issue by Roblaboy** [NVIDIA/nvidia-docker#741]
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker 依赖于 docker-engine (>= 1.9.0) | docker-ce | docker-ee；然而：
  未安装软件包 docker-engine。
  未安装软件包 docker-ce。
  未安装软件包 docker-ee。

dpkg: error processing package nvidia-docker (--install):
 依赖关系问题 - 仍未被配置
Processing triggers for ureadahead (0.100.0-16) ...
在处理时有错误发生：

**Comment by flx42** [comment]
You should install `nvidia-docker2` instead. And it looks like you didn't install docker. Or maybe you have the `docker.io` package from your distro (if it's Ubuntu).
