### ISSUE TITLE
How to use docker ee version with nvidia-docker

### ISSUE THREAD

**Issue by farooqte96** [NVIDIA/nvidia-docker#742]
Hi I tested docker checkpoint-restore feature on docker-ee-17.06 version. It works fine there. But i have to replace that with docker-ce-18.03 because nvidia-docker didn't support docker ee version. Now i am facing issue in checkpointing and restoring containers in docker-ce. Can anybody suggest how i can use nvidia-docker with docker-ee or how to properly checkpoint  & restore in docker-ce version.

docker version Output:
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: true

vrone@vrone:~$ docker checkpoint create looper2 checkpoint2
checkpoint2

vrone@vrone:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES

592f0043ff04        busybox             "/bin/sh -c 'i=0; wh…"   38 seconds ago      Up 37 seconds                           looper2

vrone@vrone:~$docker checkpoint ls looper2
Error response from daemon: open /var/lib/docker/containers/592f0043ff04726e74899d226bf7d71371c4bc74f8d4c7451e8b02c7ce301f1f/checkpoints/checkpoint2/config.json: no such file or directory

**Comment by flx42** [comment]
You can still use `docker-ee` and install the package `nvidia-container-runtime` (not `nvidia-docker2), then you register the runtime manually:
https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup

Let me know if that's possible, I've never used EE

**Comment by QuantumFractal** [comment]
I just had this same issue yesterday. I'm using RHEL7 with Docker EE. 

I performed the following, after setting up Nvidia's yum repo. 
```
> DOCKERVER=$(docker version --format '{{.Server.Version}}' | sed -r 's/-.*//')
> sudo yum install -y "nvidia-container-runtime-2.0.0-1.docker$DOCKERVER.x86_64"
```
Then I just followed the instructions listed above for setting up the engine.

**Comment by farooqte96** [comment]
@flx42 Thanks for addressing the issue. I have successfully installed nvidia-container-runtime. 
Can you confirm that to start a gpu enabled container do i need to issue nvidia-container-runtime command (like with nvidia-docker2 we used nvidia-docker run) or docker run --runtime=nvidia will be sufficient?

In your provided instructions, to setup docker engine with systemd drop-in file method didn't work for me because it made it unable to start properly. so i re-installed docker, updated the daemon.config file  & manully added default-runtime as nvidia 

At present my /etc/docker/daemon.json looks like this:
{
    "default-runtime": "nvidia",
    "experimental":true,
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi works fine with following result:

Wed May 23 07:08:03 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   45C    P8     5W /  N/A |     62MiB /  8112MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|

sudo dockerd --add-runtime=nvidia=/usr/bin/nvidia-container-runtime also works fine.

**Comment by flx42** [comment]
Glad to know it works!

**Comment by brickerino** [comment]
So, guys, you are saying that there is a way to checkoint and restore docker containers, running on GPU? Did i understand that correctly? I thought that there is no way to save and restore gpu application at the moment, am i wrong?

**Comment by scatenag** [comment]
I am also interested in save and restore gpu applications...
Did you succeed?

**Comment by ffkjjj15** [comment]
Hi, @brickerino @scatenag @farooqte96 if there have been any updates on checkpoint nvidia GPU? Thanks!
