### ISSUE TITLE
Installation fail on my centOS 7 machine running docker1.13.1

### ISSUE THREAD

**Issue by vincentcheng62** [NVIDIA/nvidia-docker#744]
### 1. Issue or feature description
Installation fail on my centOS 7 machine running docker1.13.1

### 2. Steps to reproduce the issue
 sudo yum install -y nvidia-docker2-2.0.3-1.docker1.13.1.noarch

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Error logging:

Loaded plugins: fastestmirror, langpacks
Repository libnvidia-container is listed more than once in the configuration
Repository nvidia-container-runtime is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirror.xtom.com.hk
 * epel: mirror.nes.co.id
 * extras: mirror.xtom.com.hk
 * updates: mirror.xtom.com.hk
Resolving Dependencies
--> Running transaction check
---> Package nvidia-docker2.noarch 0:2.0.3-1.docker1.13.1 will be installed
--> Processing Dependency: nvidia-container-runtime = 2.0.0-1.docker1.13.1 for package: nvidia-docker2-2.0.3-1.docker1.13.1.noarch
--> Running transaction check
---> Package nvidia-container-runtime.x86_64 0:2.0.0-1.docker1.13.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================
 Package                             Arch              Version                            Repository                           Size
====================================================================================================================================
Installing:
 nvidia-docker2                      noarch            2.0.3-1.docker1.13.1               nvidia-docker                       4.6 k
Installing for dependencies:
 nvidia-container-runtime            x86_64            2.0.0-1.docker1.13.1               nvidia-container-runtime            1.6 M

Transaction Summary
====================================================================================================================================
Install  1 Package (+1 Dependent package)

Total size: 1.6 M
Total download size: 1.6 M
Installed size: 5.4 M
Downloading packages:
nvidia-container-runtime-2.0.0-1.docker1.13.1.x86_64.rpm                                                     | 1.6 MB  00:00:02
Running transaction check
Running transaction test

Transaction check error:
  file /etc/docker/daemon.json from install of nvidia-docker2-2.0.3-1.docker1.13.1.noarch conflicts with file from package docker-2:1.13.1-63.git94f4240.el7.centos.x86_64

Error Summary
-------------
 Please help, thank you very much!

**Comment by flx42** [comment]
I've added instructions for your use case here:
https://github.com/NVIDIA/nvidia-docker#centos-7-docker-rhel-7475-docker

I've also added an entry in the wiki:
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#why-do-i-get-the-error-file-etcdockerdaemonjson-from-install-of-nvidia-docker2-conflicts-with-file-from-package-docker

Let me know if that works for you.
