### ISSUE TITLE
Fails for --> $ docker run --runtime=nvidia --rm nvidia/cuda:9.2-runtime-ubuntu18.04 nvidia-smi

### ISSUE THREAD

**Issue by vardhanv** [NVIDIA/nvidia-docker#745]
I have installed 390 drivers on 18.04 as follows:

sudo add-apt-repository -y ppa:graphics-drivers/ppa
sudo apt-get update
sudo apt-get -y install nvidia-390 nvidia-modprobe
sudo apt-get install -y nvidia-docker2

ubuntu@ip-172-31-27-85:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

Here is the error response. 

ubuntu@ip-172-31-27-85:~$ docker run --runtime=nvidia --rm nvidia/cuda:9.2-runtime-ubuntu18.04 nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.2 --pid=2274 /var/lib/docker/overlay2/eb5819e645d925849e19c102df9ee0ff5273e16aa38a28b61531a653a4bd5b36/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: cuda >= 9.2\\\\n\\\"\"": unknown.

**Comment by flx42** [comment]
For CUDA 9.2 you need a 396 driver. You can look at the documentation here:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

**Comment by vardhanv** [comment]
Thank you this worked. It was hard to figure out where to find the binary, since the equivalent
sudo apt-get -y install nvidia-390, does not exist.

But i did the following:
sudo apt-get -y install nvidia-driver-396
