### ISSUE TITLE
Error: Unsupported Docker version

### ISSUE THREAD

**Issue by randomrandom** [NVIDIA/nvidia-docker#75]
I follow the instructions but when I try to run nvidia-docker, I get the following error: "Error: Unsupported Docker version"

Here's the setup I'm using:
1. Ubuntu 14.04.4 LTS (3.13.0-85)
2. I'm using Nvidia Tesla K10
3. Nvidia-smi returns the following driver details: 352.63
4. Docker version returns:  "Version:      1.11.0"

Any ideas what might have gone wrong, or how I can fix this?

**Comment by randomrandom** [comment]
I tried reinstalling everything. I decided to used older version of docker - 1.10.3. Now I get: "Could not load UVM kernel module"

**Comment by randomrandom** [comment]
I fixed the "Could not load UVM kernel module" error. Looks like the problem was with the GPU driver. I had to install the nvidia-346-uvm in order to get this to work on 3.13.

I also used docker 1.10.3, so I have no idea if 1.11.0 would still cause the original issue

**Comment by flx42** [comment]
Hello,

See #73 for Docker 1.11.0
