### ISSUE TITLE
nvidia-docker fails on ppc64le server

### ISSUE THREAD

**Issue by jtfogarty** [NVIDIA/nvidia-docker#750]
### 1. Issue or feature description

We followed the installation step but we get the below;

### 2. Steps to reproduce the issue

$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from nvidia/cuda
297061f60c36: Pull complete
e9ccef17b516: Pull complete
dbc33716854d: Pull complete
8fe36b178d25: Pull complete
686596545a94: Pull complete
f081839f4369: Pull complete
d104a36a885f: Pull complete
0f528f58ddc9: Pull complete
8c90b5a33c71: Pull complete
ce0fe7ba4592: Pull complete
Digest: sha256:ea620731bb116b0ef882356f0f0ef8b32bc283dea7898d638c2166cc039c9243
Status: Downloaded newer image for nvidia/cuda:latest
standard_init_linux.go:190: exec user process caused "no such file or directory" 

$  docker run --runtime=nvidia --rm nvidia/cuda ls
standard_init_linux.go:190: exec user process caused "exec format error" 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
Linux m97 4.4.0-70-generic #91-Ubuntu SMP Wed Mar 22 12:46:23 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
[dmesg.txt](https://github.com/NVIDIA/nvidia-docker/files/2063888/dmesg.txt)

 - [ ] Driver information from `nvidia-smi -a`
[nvidia-smi-a.txt](https://github.com/NVIDIA/nvidia-docker/files/2063897/nvidia-smi-a.txt)

 - [ ] Docker version from `docker version`
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:18:47 2018
 OS/Arch:      linux/ppc64le
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:17:05 2018
  OS/Arch:      linux/ppc64le
  Experimental: false

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
[dpkg-nvidia.txt](https://github.com/NVIDIA/nvidia-docker/files/2063936/dpkg-nvidia.txt)

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
[nvidia-container-cli.txt](https://github.com/NVIDIA/nvidia-docker/files/2063935/nvidia-container-cli.txt)

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

nvidia-docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow:latest-gpu
standard_init_linux.go:190: exec user process caused "exec format error"
m97:/ds_public/data/minsky/nvidia$ tail -f /var/log/nvidia-container-runtime-hook.log
I0601 19:37:14.530926 41586 nvc_mount.c:115] mounting /dev/nvidia2 at /var/lib/docker/aufs/mnt/f7c89d7f63e691293314384a0982539b3bae120882987a737d045b2ae276f676/dev/nvidia2
I0601 19:37:14.531032 41586 nvc_mount.c:312] mounting /proc/driver/nvidia/gpus/000a:01:00.0 at /var/lib/docker/aufs/mnt/f7c89d7f63e691293314384a0982539b3bae120882987a737d045b2ae276f676/proc/driver/nvidia/gpus/000a:01:00.0
I0601 19:37:14.531101 41586 nvc_mount.c:349] whitelisting device node 195:2
I0601 19:37:14.531188 41586 nvc_mount.c:115] mounting /dev/nvidia3 at /var/lib/docker/aufs/mnt/f7c89d7f63e691293314384a0982539b3bae120882987a737d045b2ae276f676/dev/nvidia3
I0601 19:37:14.531298 41586 nvc_mount.c:312] mounting /proc/driver/nvidia/gpus/000b:01:00.0 at /var/lib/docker/aufs/mnt/f7c89d7f63e691293314384a0982539b3bae120882987a737d045b2ae276f676/proc/driver/nvidia/gpus/000b:01:00.0
I0601 19:37:14.531352 41586 nvc_mount.c:349] whitelisting device node 195:3
I0601 19:37:14.531386 41586 nvc_ldcache.c:327] executing /sbin/ldconfig.real from host at /var/lib/docker/aufs/mnt/f7c89d7f63e691293314384a0982539b3bae120882987a737d045b2ae276f676
I0601 19:37:14.728237 41586 nvc.c:311] shutting down library context
I0601 19:37:14.729317 41593 driver.c:183] terminating driver service
I0601 19:37:14.770854 41586 driver.c:224] driver service terminated successfully
 - [ ] Docker command, image and tag used

**Comment by 3XX0** [comment]
You want to use `nvidia/cuda-ppc64le`, PPC64 images are available [here](https://hub.docker.com/r/nvidia/cuda-ppc64le/)

**Comment by jtfogarty** [comment]
ah, silly mistake, please close
