### ISSUE TITLE
Ubuntu Repository Not Found

### ISSUE THREAD

**Issue by sckn** [NVIDIA/nvidia-docker#754]
Hi,

I tried install nvidia-docker on ubuntu 17.10. 
Repository URL return 404 status code.

`root@ubuntu:~# cat /etc/issue.net
Ubuntu 17.10
root@ubuntu:~# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
root@ubuntu:~# echo $distribution
ubuntu17.10
root@ubuntu:~#
root@ubuntu:~# curl -o /dev/null -v -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list
*   Trying 185.199.111.153...
* TCP_NODELAY set
* Connected to nvidia.github.io (185.199.111.153) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3182 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=www.github.com
*  start date: Mar 23 00:00:00 2017 GMT
*  expire date: May 13 12:00:00 2020 GMT
*  subjectAltName: host "nvidia.github.io" matched cert's "*.github.io"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
} [5 bytes data]
> GET /nvidia-docker/ubuntu17.10/nvidia-docker.list HTTP/1.1
> Host: nvidia.github.io
> User-Agent: curl/7.55.1
> Accept: */*
>
{ [5 bytes data]
< HTTP/1.1 404 Not Found
< Server: GitHub.com
< Content-Type: text/html; charset=utf-8
< ETag: "583c90dd-247c"
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
< X-GitHub-Request-Id: B6A6:1A98:1789181:1FB046F:5B1690ED
< Content-Length: 9340
< Accept-Ranges: bytes
< Date: Tue, 05 Jun 2018 13:43:51 GMT
< Via: 1.1 varnish
< Age: 682
< Connection: keep-alive
< X-Served-By: cache-fra19139-FRA
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1528206232.816803,VS0,VE0
< Vary: Accept-Encoding
< X-Fastly-Request-ID: 47ec1cac9c6883aa5c6ce4e55fe7056d8a6094cd
<
{ [2134 bytes data]
* Connection #0 to host nvidia.github.io left intact
root@ubuntu:~#`

**Comment by flx42** [comment]
We don't support 17.10.
You should use the 18.04 repository instead, if you really want to stay on 17.10

**Comment by sckn** [comment]
Thank you.
