### ISSUE TITLE
NGC can be used on both Azure and AWS

### ISSUE THREAD

**Issue by omartin2010** [NVIDIA/nvidia-docker#755]
### 1. Issue or feature description

Wiki's [FAQ page](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#platform-support) mentions specifically : Alternatively, you can leverage NGC to deploy optimized container images on AWS.. It should be mentioned something like : Alternatively, you can leverage NGC to deploy optimized container images on AWS and on Azure.

### 2. Steps to reproduce the issue

N/A

**Comment by flx42** [comment]
Fixed, thanks!
