### ISSUE TITLE
Model computation slows down when using cpu-quota and cpu-period options

### ISSUE THREAD

**Issue by codax0r** [NVIDIA/nvidia-docker#757]
Hi,

I hope this is the right corner to place this question: 
I'm currently playing around with nvidia-docker2 and Tensorflow. I remarked that when starting the container with `docker run --runtime nvidia -d --name tftest2 --memory=3g --cpu-period=100000 --cpu-quota=100000 server1077.cs.technik.fhnw.ch:443/custom/tensorflow:wide_deep` (Full access to CPU) it is running as 2 times as fast than starting the container with `docker run --runtime nvidia -d --name tftest --cpu-period=100000 --cpu-quota=50000 --memory=3g server1077.cs.technik.fhnw.ch:443/custom/tensorflow:wide_deep`... It seems to be logic somewhat but i cannot explain exactly why? Does the GPU only have half of the bandwith to the CPU or what's the point behind this?

Thanks for answering my questions :).

**Comment by cliffwoolley** [comment]
It stands to reason that your experiment appears to have uncovered a CPU bottleneck in the training of your particular model (when with full shares of the CPU, you're quite likely still not saturating the GPU, given this result).  You would have to do some profiling to figure out why.

**Comment by codax0r** [comment]
ah. Thanks, yes i understand :). I misunderstood something in the docker documentation about the cpu-periods.. Many thanks!
