### ISSUE TITLE
Make a roadmap section please.

### ISSUE THREAD

**Issue by al3x609** [NVIDIA/nvidia-docker#762]
for future features.

**Comment by al3x609** [comment]
yes, I have a project  that use ParaView _a frontend tool  for rendering VTK apps_, I put this in  a container, but I have a limitation, ParaView use openGL, but only with Nvidia-docker I cannot get GL library support, or maybe I'm newbie on the matter, For now on container I need run this: 
`./NVIDIA-Linux-x86_64-367.124.run --no-kernel-module-source -z --no-kernel-module -N -b -a -s -q --no-x-check && ` 

> what it means to run the driver installer again but without installing kernel modules to get GL support inside the container; I think this is not the cleanest solution, but it is the only thing that comes to mind for now.

for the previous the support of openGL can be good in the future, I believe.
yesterday I read about a project of Nvida

[https://github.com/NVIDIA/libglvnd]() but I'm not sure if this, can help me in this aspect about docker, nvida-docker and openGL.

Can you give me an idea about this? thanks

**Comment by flx42** [comment]
OpenGL is supported with nvidia-docker 2.
We have OpenGL images, with libglvnd:
https://hub.docker.com/r/nvidia/opengl/

We have OpenGL + CUDA images here:
https://hub.docker.com/r/nvidia/cudagl/

We also have a headless VTK sample here:
https://gitlab.com/nvidia/samples/blob/master/opengl/ubuntu16.04/vtk/Dockerfile
That should allow you to get a headless ParaView rendering server.

**Comment by al3x609** [comment]
Thanks a lot for the advice.
