### ISSUE TITLE
Use nvprof in nvidia-docker?

### ISSUE THREAD

**Issue by linrio** [NVIDIA/nvidia-docker#765]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

How to use `nvprof ` tool in nvidia-docker ?
I want to profile the applications in container. How to use the nvprof in nvidia-docker ? I run with:

`sudo nvidia-docker run --privileged --security-opt seccomp=unconfined -it -v `pwd`:/paddle /dev /bin/bash`

It does not work.

[cuda-memcheck and nvprof unable to collect debugging information inside container](https://github.com/NVIDIA/nvidia-docker/issues/454)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment]
CUDA 9.0: `apt-get install -y cuda-command-line-tools-9-0`
CUDA 9.1: `apt-get install -y cuda-nvprof-9-1`
CUDA 9.2: `apt-get install -y cuda-nvprof-9-2`

**Comment by linrio** [comment]
@flx42 Tks. You mean during the building container step I should install cuda-nvprof-9-* in Dockerfile?

**Comment by flx42** [comment]
yes, or you can do that in your terminal if you don't want to bake nvprof in the image you ship.

**Comment by linrio** [comment]
@flx42 
I install the nvprof during building docker container:

```
...
 ---> 3f9cc70edb06
Step 4/13 : RUN apt-get update && apt-get install -y --no-install-recommends     ca-certificates     build-essential     git     python     python-pip     cuda-nvprof
-9-1
...
Setting up cuda-license-9-1 (9.1.85-1) ...
*** LICENSE AGREEMENT ***
By using this software you agree to fully comply with the terms and 
conditions of the EULA (End User License Agreement). The EULA is located
at /usr/local/cuda-9.1/doc/EULA.txt. The EULA can also be found at
http://docs.nvidia.com/cuda/eula/index.html. If you do not agree to the
terms and conditions of the EULA, do not use the software.

Setting up cuda-nvprof-9-1 (9.1.85-1) ...
...
```
However, I start up the container:
`sudo docker run -v /home/linlf/project/xyz:/xyz --runtime=nvidia -t -i containerID`

In container, I execute:
```
root@36a85cef0656:~/research# nvprof
bash: nvprof: command not found
```

What's this problem?

**Comment by flx42** [comment]
It's probably not in your PATH, the binary is at `/usr/local/cuda/bin/nvprof`

**Comment by linrio** [comment]
@flx42 Actually I only install the nvprof tools in cuda-9.1, so the cuda-9.1/bin only include the nvprof:

```
#ls /usr/local/cuda-9.1/bin/
nvprof
```

**Comment by linrio** [comment]
@flx42 Hi,
Some events/metrics of nvprof is nonsupport in CUDA-8.0 ?

**Comment by flx42** [comment]
@linrio that I don't know, I don't maintain nvprof. Try this forum:
https://devtalk.nvidia.com/

**Comment by linrio** [comment]
Ok. Tks!
