### ISSUE TITLE
Can nvidia-docker enable CUDA for images without specific drivers/support built-in?

### ISSUE THREAD

**Issue by funkypenguin** [NVIDIA/nvidia-docker#766]
Hey guys,

Hopefully a quick question, I'm trying to get my head around nvidia-docker.. [emby/embyserver](https://hub.docker.com/r/emby/embyserver/) is a container with a version of ffmpeg compiled for CUDA support.

I _think_ from reading https://github.com/NVIDIA/nvidia-docker/issues/531 that provided I use docker-nvidia wrapper (as opposed to just "docker"), and pass NVIDIA_DRIVER_CAPABILITIES=compute,utility,video as an environment variable, that nvidia-docker will mount the necessary libraries etc into my container "on-the-fly", and ffmpeg will "just work".

Sadly, this is not the case (I've probably misunderstood), and I get our old friend:

```
[h264_cuvid @ 0x1ec8780] Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x1ec8780] Failed loading nvcuvid.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (libx264))
  Stream #0:1 -> #0:1 (truehd (native) -> vorbis (libvorbis))
Error while opening decoder for input stream #0:0 : Operation not permitted
```

Further, libnvcuvid.so.1 is nowhere to be found on the container's filesystem.

**Should** I be able to do this, or should I be rebuilding an Emby container from nvidia/cuda as a base?

Cheers!
D

**Comment by flx42** [comment]
The variable that triggers our runtime or not is `NVIDIA_VISIBLE_DEVICES=all`, so you need to do something like that:
```
$ docker run -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,video ubuntu:16.04
```
