### ISSUE TITLE
Docker 18.05.0

### ISSUE THREAD

**Issue by hdiethelm** [NVIDIA/nvidia-docker#767]
Please update to Docker to 18.05.0 for Ubuntu 18.04. I can't run it at the moment.

And there is now way to download old Docker versions.

**Comment by flx42** [comment]
Use `docker.io` packaged by Canonical, that's the only version that seems to be officially supported on bionic.

**Comment by shiquanwang** [comment]
@flx42 please check below links:
* https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/
* https://github.com/docker/for-linux/issues/290#issuecomment-398933337

Ubuntu 18.04 has a stable docker-ce 18.03 now, please update nvidia-docker2 to this version. Many thanks.

**Comment by flx42** [comment]
@shiquanwang thanks for the heads-up! Will do that tomorrow morning.

**Comment by flx42** [comment]
Pushed, please test!

**Comment by shiquanwang** [comment]
thanks, using now.
