### ISSUE TITLE
Cannot install nvidia-docker2 / unmet dependencies

### ISSUE THREAD

**Issue by hlalibe** [NVIDIA/nvidia-docker#768]
Hi all,

My issue seems similar to https://github.com/NVIDIA/nvidia-docker/issues/719 but it's closed so i understand i need to open a new one ? Sorry, new to Git,
---

### 1. Issue or feature description
Cannot install nvidia-docker2, i get the error message:
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  nvidia-docker2 : Depends: docker-ce (= 18.03.1~ce-0~ubuntu) but 18.05.0~ce~3-0~ubuntu is to be installed or
>                            docker-ee (= 18.03.1~ee-0~ubuntu) but it is not installable
> E: Unable to correct problems, you have held broken packages.

### 2. Steps to reproduce the issue
sudo apt-get install -y nvidia-docker2

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Kernel version from `uname -a`: Linux hugues-MS-7B09 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
there is a km of info in there, not sure what is relevant

 - [ ] Driver information from `nvidia-smi -a`
TITAN Xp / 384.130

 - [ ] Docker version from `docker version`
18.05.0-ce  / 1.37  / go1.9.5  / f150324

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
returns command not found

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment]
Edge releases are not supported:
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#which-docker-packages-are-supported
You should disable the `edge` channel from your Docker repository entry in `/etc/apt/sources.list` or `/etc/apt/sources.list.d/...`

**Comment by hlalibe** [comment]
thanks @flx42 
i have edited this file:
/etc/apt/sources.list.d
and replaced that line:
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial edge
by that line:
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

then i ran:
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

which went through ok,
then when i run:
sudo apt-get install -y nvidia-docker2

i get exactly the same error message as my OP.

Sorry, maybe it's super obvious what i'm missing, but this is all new to me.

**Comment by flx42** [comment]
You need to remove `docker-ce`, then reinstall it (it will replace the edge version by the stable version).
