### ISSUE TITLE
Cannot download nvidia-docker repository

### ISSUE THREAD

**Issue by npowell88** [NVIDIA/nvidia-docker#769]
[The main page](https://github.com/NVIDIA/nvidia-docker) references how to get the repository file for yum. However, it seems [the url](https://nvidia.github.io/nvidia-docker/rhel7.2/nvidia-docker.repo) created by the distribution and curl lines does not exist. What do I do to get this repo file?

**Comment by flx42** [comment]
RHEL 7.2 is old, not sure we support that. Try with `rhel7.4` or `rhel7.5` in the URL.

**Comment by npowell88** [comment]
Thanks.
