### ISSUE TITLE
nvidia-docker volume setup Error with Docker version 1.11.0, build 4dc5990

### ISSUE THREAD

**Issue by shenghuofei** [NVIDIA/nvidia-docker#77]
install(user is root):
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-beta.3/nvidia-docker_1.0.0.beta.3_amd64.tar.xz
tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker_1.0.0.beta.3_amd64.tar.xz && rm /tmp/nvidia-docker*.tar.xz
when run:nvidia-docker volume setup has error:
nvidia-docker | 2016/04/18 16:12:09 Error: unsupported Docker version

**Comment by lazyest** [comment]
same with .deb packaged version

**Comment by flx42** [comment]
Hello @shenghuofei and @lazyest 

See #73 for Docker 1.11.0.
We will release a new deb soon.
