### ISSUE TITLE
Why there are so many versions for nvidia-docker2?

### ISSUE THREAD

**Issue by kensou97** [NVIDIA/nvidia-docker#772]
Hi,recently I'm working on a script which can help install nvidia-docker automatically on different offline machines. 
    I tried nvidia-docker 1.0 first,it's easy to install and seems to work well except the known limitations mentioned in the wiki.
    Then I tried 2.0 because it seems to be more elegant.But I found it's hard to install,not only because I've to collect the dependencies and make a local yum repository,but also there are different packages for different docker-ce versions. I got confused.
Can you provide some suggestions?Thank you.

**Comment by flx42** [comment]
It's because for now we have to match the version of `runc` used by your `docker-ce` release. It will probably change in a few months, the ecosystem is changing fast.
