### ISSUE TITLE
nvidia-docker2 : Depends: docker.io for Ubuntu 18.04; I am using Docker 18.03.1-ce which is on Bionic stable

### ISSUE THREAD

**Issue by TaakoMagnusen** [NVIDIA/nvidia-docker#773]
### 1. Issue or feature description

I have installed CUDA 9.2 and CuDNN 7.1.14 on Ubuntu 18.04 Bionic.

I have also installed Docker 18.03.1-ce which is on Bionics stable branch as of today.

When i try to install nvidia-docker2 i get this

```
sudo apt-get install nvidia-docker2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker.io (= 17.12.1-0ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### 2. Steps to reproduce the issue
Attempt to install nvidia-docker2 on ubuntu 18.04 Bionic with docker-18.03.1-ce.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment]
The docker package for bionic was released a few hours, I will publish our new package tomorrow.

**Comment by flx42** [comment]
Pushed!

**Comment by djibi2** [comment]
This doesn't appear to have the correct version of docker-ce for bionic stable.  This package requires 
` docker-ce (= 18.03.1~ce~3-0~ubuntu)|docker-ee (= 18.03.1~ee~3-0~ubuntu)` (line 35 Makefile)
but bionic stable has `docker-ce_18.03.1~ce-0~ubuntu.`

**Comment by flx42** [comment]
@djibi2 no that's the right package for bionic:
```
sudo apt-cache policy docker-ce
docker-ce:
  Installed: (none)
  Candidate: 18.03.1~ce~3-0~ubuntu
  Version table:
     18.03.1~ce~3-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
```
But yes, unfortunately they changed the versioning scheme **again**.

The xenial package does not have the `~3`, that's probably what you have.

**Comment by djibi2** [comment]
Sorry, my mistake.   I forgot that I had modified my docker.list file to point at the "artful" releases before the "bionic" release were made.

Everything installs as expected.

**Comment by TiborUdvari** [comment]
I had the problem with the versioning scheme changing ... But setting the version manually works, no problems. `sudo apt-get install docker-ce=18.03.1~ce~3-0~ubuntu`
