### ISSUE TITLE
nvidia-docker v2: error while loading shared libraries: libEGL.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by xsbreakaway** [NVIDIA/nvidia-docker#776]
There is an error when I run my image after updating the version of nvidia-docker to version 2.
**error while loading shared libraries: libEGL.so.1: cannot open shared object file**

I found that there are many shared libraries in path /usr/local/nvidia/lib64 of container when I use nvidia-docker v1. 
![image](https://user-images.githubusercontent.com/10703556/41914871-f62aeb54-7986-11e8-9b8b-51340c1461cf.png)
But there is nothing of container when I use nvidia-docker v2 to run the same image.

I had tried the NVIDIA_DRIVER_CAPABILITIES environment variable.
![image](https://user-images.githubusercontent.com/10703556/41914617-4266cdcc-7986-11e8-8db0-36b74b08c304.png)
But this is no help.

**Comment by flx42** [comment]
In nvidia-docker v2, libEGL comes from [libglvnd](https://github.com/NVIDIA/libglvnd). Do `ldconfig -p | grep libEGL` to find its location.

**Comment by xsbreakaway** [comment]
in container：
![image](https://user-images.githubusercontent.com/10703556/41949470-1e1629a4-79f4-11e8-9552-ff9ba5d200a1.png)
out container：
![image](https://user-images.githubusercontent.com/10703556/41949480-2adaba06-79f4-11e8-9872-7f1c9c46ccea.png)
There is libEGL out container (path:/usr/lib64/nvidia/libEGL.so.1).

What should I do to mount libraries to container by nvidia-docker v2?

**Comment by xsbreakaway** [comment]
Thank you for reply. 
You mean that I should change my base image?
I can run my image smoothly by nvidia-docker v1. Is there any way to mount libraries on container instead of changing my base image by nvidia-docker v2?

**Comment by den-is** [comment]
@flx42 above links are dead :((

**Comment by RenaudWasTaken** [comment]
https://gitlab.com/nvidia/cudagl

**Comment by srmocher** [comment]
I didn't have the option of changing the base image but was able to resolve this error by mounting the `.so` file from the host into the container.
