### ISSUE TITLE
exited while loding the image.

### ISSUE THREAD

**Issue by gerrard008** [NVIDIA/nvidia-docker#779]
Download the tgz from github to my mac, create a copy of Docker.ubuntu file and and modified as below.

$ more Dockerfile
ARG VERSION_ID
FROM ubuntu:16.04
# packaging dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        dh-make \
        fakeroot \
        build-essential \
        devscripts \
        lsb-release && \
    rm -rf /var/lib/apt/lists/*
# packaging
ARG PKG_VERS
ARG PKG_REV
ARG RUNTIME_VERSION
ARG DOCKER_VERSION
ENV DEBFULLNAME "NVIDIA CORPORATION"
ENV DEBEMAIL "cudatools@nvidia.com"
ENV REVISION "$PKG_VERS-$PKG_REV"
ENV RUNTIME_VERSION $RUNTIME_VERSION
ENV DOCKER_VERSION $DOCKER_VERSION
ENV SECTION ""
# output directory
ENV DIST_DIR=/tmp/nvidia-docker2-$PKG_VERS
RUN mkdir -p $DIST_DIR
# nvidia-docker 2.0
COPY nvidia-docker $DIST_DIR/nvidia-docker
COPY daemon.json $DIST_DIR/daemon.json
WORKDIR $DIST_DIR
COPY debian ./debian
RUN sed -i "s;@VERSION@;${REVISION#*+};" debian/changelog && \
    if [ "$REVISION" != "$(dpkg-parsechangelog --show-field=Version)" ]; then exit 1; fi
CMD export DISTRIB="$(lsb_release -cs)" && \
    debuild --preserve-env --dpkg-buildpackage-hook='sh debian/prepare' -i -us -uc -b && \
    mv /tmp/*.deb /dist

$ bdocker build -t nvidia_docker .

docker image ls
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
<none>                                       <none>              89a2df7b2d7c        19 seconds ago      405MB
ubuntu                                       16.04               5e8b97a2a082        2 weeks ago         114MB

$ docker save 89a2df7b2d7c -o nvidia-docker-ubuntu.tgz

scp this image to the ubuntu vm from my mac.

$ docker image load -i nvidia-docker-ubuntu.tgz

# docker image ls
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
nvidia-docker           latest              89a2df7b2d7c        30 hours ago        405 MB

# docker run  nvidia-docker

# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
34c92aa1f512        nvidia-docker       "/bin/bash"         12 seconds ago      Exited (0) 12 seconds ago                       sad_banach

What do i need to do to get this image running?

**Comment by flx42** [comment]
You can't run nvidia-docker on a Mac. But you can use the docker CLI on your Mac to access a remote docker daemon from a Linux machine with GPUs and nvidia-docker (following the instructions in the README).
