### ISSUE TITLE
Unable to install nvidia-docker in Ubuntu 16.04

### ISSUE THREAD

**Issue by dikshya29** [NVIDIA/nvidia-docker#782]
I am trying to install nvidia-docker on a Ubuntu 16.04 server. nvidia drivers and docker are successfully installed. I am following the official documentation for installation, but I am getting the following errors when I do `sudo apt-get update` -

`Err:5 https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  Packages`                                    
  `Recv failure: Connection reset by peer`

`W: The repository 'https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  Release' does not have a Release file.`
`N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.`
`N: See apt-secure(8) manpage for repository creation and user configuration details.`
`E: Failed to fetch https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64/Packages  Recv failure: Connection reset by peer`
`E: Some index files failed to download. They have been ignored, or old ones used instead.`

Docker version - **1.37**
NVIDIA drivers version - **396.24.02** 

Am I missing something? Any help will be appreciated

**Comment by 3XX0** [comment]
`Recv failure: Connection reset by peer`: This is a network issue on your end (e.g. HTTP proxy)

**Comment by dikshya29** [comment]
What sites do I need to add to our list of allowed sites? Those links all appear as 404s.
