### ISSUE TITLE
caffe training on nvcr docker with multiple GPUs is much slower than the host

### ISSUE THREAD

**Issue by encorechow** [NVIDIA/nvidia-docker#788]
I used 8-gpu caffe training within the newest nvcr docker container. Surprisingly, the training speed was reduced significantly (like 2 times slower). I was wondering if anybody has this problem? I guess it may be the problem of nccl. When I used single gpu to train, the seed was nearly the same. Here is the topology of my gpus:
          **GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity**
**GPU0**     X      PIX     PHB     PHB     SYS     SYS     SYS     SYS     0-13,28-41
**GPU1**    PIX      X      PHB     PHB     SYS     SYS     SYS     SYS     0-13,28-41
**GPU2**    PHB     PHB      X      PIX     SYS     SYS     SYS     SYS     0-13,28-41
**GPU3**    PHB     PHB     PIX      X      SYS     SYS     SYS     SYS     0-13,28-41
**GPU4**    SYS     SYS     SYS     SYS      X      PIX     PHB     PHB     14-27,42-55
**GPU5**    SYS     SYS     SYS     SYS     PIX      X      PHB     PHB     14-27,42-55
**GPU6**    SYS     SYS     SYS     SYS     PHB     PHB      X      PIX     14-27,42-55
**GPU7**    SYS     SYS     SYS     SYS     PHB     PHB     PIX      X      14-27,42-55

Here are some details:
CUDA: 9.0
CUDNN: 7
GPUs: 8 Telsa-M40
Caffe model: ResNet-101

I can provide more information if needed. Thanks for any reply.

**Comment by flx42** [comment]
Since it's a question related to nvcr, you should ask on the dedicated forum:
https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/

**Comment by drnikolaev** [comment]
@encorechow what is the version you run?
