### ISSUE TITLE
Wrong path in environment variable

### ISSUE THREAD

**Issue by LuisAyuso** [NVIDIA/nvidia-docker#789]
### 1. Issue or feature description

The path provided in LD_LIBRARY_PATH does not exist: it points to to 
``` LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 ``` but libraries are in 
``` /usr/local/cuda/lib64/```
### 2. Steps to reproduce the issue

- nvidia/cuda:9.1-devel-centos7
- type env

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Kernel version from `uname -a` 
Linux 7d2581f6a11e 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment]
This is normal. This `LD_LIBRARY_PATH` points to the path where the driver libraries are installed when using nvidia-docker v1. If you are using nvidia-docker v2, this variable has no effect and is harmless.

The libraries in `/usr/local/cuda/lib64/` are already in `ld.so.cache`:
```
root@dc4df078359e:/# ldconfig -p | grep libcublas
        libcublas.so.9.0 (libc6,x86-64) => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcublas.so.9.0
        libcublas.so (libc6,x86-64) => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcublas.so
```
