### ISSUE TITLE
No space left when pulling Docker Digits on AWS

### ISSUE THREAD

**Issue by PiersCasimir** [NVIDIA/nvidia-docker#792]
I've searched as best I can...

When running this command:

docker pull nvcr.io/nvidia/digits:18.01

I get this error:

failed to register layer: Error processing tar file(exit status 1): write /usr/share/vim/vim74/syntax/sisu.vim: no space left on device

Does anyone know a fix, please?

**Comment by flx42** [comment]
This is a docker issue, you probably don't have enough space on your `/` partition. Try launching an instance with more storage.
