### ISSUE TITLE
Got CUDNN_STATUS_NOT_INITIALIZED although PyTorch and Lua Torch correctly recognize CUDA & CuDNN

### ISSUE THREAD

**Issue by Amir-Arsalan** [NVIDIA/nvidia-docker#793]
**environment**

```
OS: Ubuntu 16.04.3 LTS
PyTorch version: 0.5.0a0+1483bb7
How you installed PyTorch (conda, pip, source): source
Python version: 3.5.2
torch.backends.cudnn.version(): 7104
CUDA version: 9.0.176
NVIDIA driver version: 390.48 (tried with 390.67 as well)
GPU: Pascal Titan-X (CUDA compute capability 6.1)
```

In a Singularity container, I pull the NVIDIA's Docker hub image for Cuda 9.0 and CuDNN 7.0 and compile PyTorch from source and try to run the CIFAR classification code from here (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py). As described in the link, I move the network and mini batches to GPU to do the training. However I get the following error at the beginning of training, when I want to convert the model modules to CuDNN modules:

`RuntimeError: CuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

Doing `device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")` will correctly show me `cuda:0`. Then I do `net.to(device)` but I still get this error.

I get the same exact error with Lua Torch when trying to run an old code of mine. So the problem has nothing to do with PyTorch. I need to mention that this problem exists only after the recent updates to the NVIDIA's docker hub image since about a month ago. I had not built a new image since about two months ago until 10 days ago. Since about 10 days ago I've been facing this issue and haven't been able to run my code anymore. So I'm assuming some stuff have happened since two months ago and before 10 days ago in the Docker image file. I initially posted an issue to PyTorch's GitHub repository here (https://github.com/pytorch/pytorch/issues/9289). You can get some more information regarding what things I tried from that issue too.

I would appreciate if someone from NVIDIA can take a look at the recent revisions in either CuDNN or the Docker image to see what things have changed that might be responsible for this issue. 

Here's how I build my Singularity container on a **Ubuntu 16.04** machine and then copy it to our servers which run **CentOS 7.4**:

```
BootStrap: docker
From: nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

apt-get -y update && apt-get -y install locales
locale-gen en_US.UTF-8
apt-get -y update && apt-get -y install make \
                                        dpkg \
                                        wget \
                                        g++ \
                                        gcc \
                                        xvfb \
                                        libyaml-cpp-dev \
                                        git \
                                        cmake \
                                        vim \
                                        curl \
                                        ca-certificates \
                                        software-properties-common \
                                        python3 \
                                        python3-pip \
                                        zlib1g-dev \
                                        freeglut3-dev \
                                        mesa-utils \
                                        libreadline-dev \
                                        gnuplot \
                                        gnuplot-qt \
                                        unzip \
                                        libboost-all-dev

pip3 install --upgrade pip==9.0.3
yes y | pip3 uninstall setuptools
pip3 install -U setuptools
pip3 install -U pyyaml
pip3 install multiprocess \
                        joblib \
                        scipy \
                        numpy \
                        transforms3d \
                        matplotlib \
                        mkl \
                        mkl-devel \
                        cffi \
                        Pillow \
                        h5py 

apt-get install -y python3-setuptools

# PyTorch
cd /
mkdir /repo-src && cd /repo-src
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python3 setup.py install

# TorchVision
cd /
mkdir torchvision && cd torchvision
git clone --recursive https://github.com/pytorch/vision.git
cd vision
python3 setup.py install
```

After building your container you can test it as follow:

`singularity shell --nv -B /home:/home --nv pytorch.img`

`/home:home/` will bind your home directory to the home directory in the container. `--nv` flag lets the container use the NVIDIA driver installed on your machine.

After making the changes in the cifar classification example code to move the model to GPU, I do `python3 ~/Desktop/cifar10_tutorial.py`. That's when I get `RuntimeError: CuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

**Comment by flx42** [comment]
We do not support Singularity. Please provide a repro with Docker or LXC for both the build and the execution.

**Comment by Amir-Arsalan** [comment]
@flx42 It looks like I need to use Singularity for my current project. But my point is there has been some changes in the Docker or recent updates of CuDNN that are causing this. I've been building my Singularity containers since 8-10 months ago with the exact same script: I always pulled from NVIDIA's Docker image and then continued the build. I never had any issues until very recently.

**Comment by flx42** [comment]
There might be still something wrong about the runtime environment that could surface this issue.
If @ngimel has no clue about what changed, I don't either, sorry.

**Comment by Amir-Arsalan** [comment]
@flx42 @ngimel Just an update: The same problem persists even with the recent updates 3 days ago in Docker Hub.

**Comment by flx42** [comment]
Please create a repro with a Dockerfile, otherwise I can't look at it.

**Comment by Amir-Arsalan** [comment]
@flx42 @ngimel This does not happen anymore after the last update in the Docker image contents from NVIDIA. It would be good if you can identify the change that led to this so that you can prevent this from happening again. 

Btw, sorry that I could not use Docker to reproduce this. For some reason I cannot Docker for my work and therefore, it was/is impossible to do this through Docker.
