### ISSUE TITLE
Upgrading Nvidia device driver

### ISSUE THREAD

**Issue by trstovall** [NVIDIA/nvidia-docker#794]
What steps related to nvidia-docker2 are needed to upgrade the device driver on the host machine?  My current driver supports CUDA <= 9.0.  Seeking to use CUDA 9.2 images without disturbing CUDA 8.0 and CUDA 9.0 containers.

**Comment by flx42** [comment]
You can update the device driver on your machine and you will still be able to run CUDA 8.0 and CUDA 9.0 containers, there is nothing specific to nvidia-docker here. But you will have to stop existing GPU containers before you do the upgrade.

**Comment by trstovall** [comment]
> stop existing GPU containers before you do the upgrade.

Thanks, that's what I needed.
