### ISSUE TITLE
Unmet dependency for docker-ce

### ISSUE THREAD

**Issue by WackyOne** [NVIDIA/nvidia-docker#795]
When installing nvidia-docker2 on Ubuntu 16.04, I get this dependency message:
```
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 18.03.1~ce-0~ubuntu) but 18.06.0~ce~3-0~ubuntu is to be installed or
                           docker-ee (= 18.03.1~ee-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
What is the correct course of action?
1. Ignore the dependency?
2. Wait for an update of nvidia-docker2?
3. Revert docker-ce?

```
$ apt list -a search docker-ce
Listing... Done
docker-ce/xenial,now 18.06.0~ce~3-0~ubuntu amd64 [installed]
docker-ce/xenial,unknown 18.03.1~ce-0~ubuntu amd64
```

**Comment by Megacrafter127** [comment]
Do any of the solutions from [this](https://github.com/NVIDIA/nvidia-docker/issues/643) closed issue help?

**Comment by WackyOne** [comment]
@Megacrafter127 thanks for that pointer. I think what I get out of that discussion is that my option 3 is what should be selected.

**Comment by RenaudWasTaken** [comment]
Hello!

If this hasn't been resolved by now, https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version

You need to pin the version to get the one for 18.03.1
