### ISSUE TITLE
debian package link broken

### ISSUE THREAD

**Issue by hylda7** [NVIDIA/nvidia-docker#796]
In your quickstart readme.md, I got ERROR 404 file not found. I use debian.
```sh
# Add the package repositories
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.repo | \
  sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo
```

**Comment by flx42** [comment]
What's the output of `cat /etc/os-release`?

**Comment by hylda7** [comment]
user@foyer:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
user@foyer:~$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
user@foyer:~$ echo $distribution
debian
