### ISSUE TITLE
Failed to install nvidia-docker when docker is stalled with binary files

### ISSUE THREAD

**Issue by m3ngyang** [NVIDIA/nvidia-docker#798]
### 1. Issue or feature description
Failed to install nvidia-docker when docker is stalled with binary files, since the dependency check is written in the control script of debian package. Is it reasonable to cancel this check in the scripts ?

### 2. Steps to reproduce the issue
1. install docker with binary files
2. install nvidia-docker

**Comment by flx42** [comment]
In this case, you are better off installing the package `nvidia-container-runtime` instead, since the `nvidia-docker2` package is just a bash script + `daemon.json` to register the runtime + dependency on `docker-ce`.
https://github.com/nvidia/nvidia-container-runtime
