### ISSUE TITLE
Docker file for CUDA toolkit+CUDNN+opencv

### ISSUE THREAD

**Issue by grafana2018** [NVIDIA/nvidia-docker#799]
Hi Team,

I want to run docker container with CUDA toolkit+CUDNN+opencv.
Is there any way to install all of them by using "dockerfile" and run as a container.
If possible please let me know dockerfile example for above all.

Regards,
Sreenath

**Comment by flx42** [comment]
We can't publish Dockerfiles for every possible use case. If you don't mind how OpenCV was compiled, you can install the official packages from your distro (e.g. `apt-get install -y libopencv-dev` in your `Dockerfile`).

If you want to compile OpenCV from sources to customize it, I have an example here:
https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.caffe_server#L26-L41
