### ISSUE TITLE
Invalid Debian Repository?

### ISSUE THREAD

**Issue by sargun** [NVIDIA/nvidia-docker#800]
The installation instructions say the sources.list file should be at: `https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list`, for my distribution that is `https://nvidia.github.io/nvidia-docker/ubuntu16.04/nvidia-docker.list`. This has the contents:

```
deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/$(ARCH) /
```
Unfortunately, these are "incorrect".

**Comment by flx42** [comment]
`man sources.list` :)

**Comment by sargun** [comment]
Shouldn't it be `$(ARCH)` not `$(ARCH )`?

**Comment by flx42** [comment]
Where did you see `$(ARCH )`?

**Comment by flx42** [comment]
ping @sargun: did you solve the problem?

**Comment by sargun** [comment]
It was `/$(ARCH) /` that was breaking some of our internal mirroring tools, replacing it with `/$(ARCH)/` fixed it.

**Comment by redfish-lee** [comment]
@sargun still don't work, respond error 
```
E: Malformed entry 2 in list file /etc/apt/sources.list.d/nvidia-docker.list (Suite)
E: The list of sources could not be read.
```

And I add it manually with 
```
deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64/
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64/
deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/
```
still don't work

**Comment by VJatla** [comment]
For Debain10,

curl -s -L https://nvidia.github.io/nvidia-docker/debian10/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
