### ISSUE TITLE
Ubuntu 16.04: nvidia-docker2 : The following packages have unmet dependencies:

### ISSUE THREAD

**Issue by hamzafar** [NVIDIA/nvidia-docker#801]
Hi,

I have been trying to install nvidia-docker-2, on my ubuntu 16.04. and also tried to the solutions available at the [thread](https://github.com/NVIDIA/nvidia-docker/issues/643) but unable to install nvidia-docker2.

When I run the command at terminal **sudo apt-get install -y nvidia-docker2** I get following error:

![nvid-1](https://user-images.githubusercontent.com/6842017/43476200-0125fd1c-9509-11e8-9dfb-f91aa2ce493d.png)

And when I have run the other command that is mentioned in the [thread2](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version) I am getting the following issue:

![nvid2](https://user-images.githubusercontent.com/6842017/43476215-091456a4-9509-11e8-8181-8c328bfe8bcd.png)

I am not sure how to resolve these issue. Any recommendation will be highly appreciated.

Regards
Hamza Zafar

**Comment by flx42** [comment]
You also need to follow the official instructions to setup the Docker package repository:
https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by hamzafar** [comment]
Hi @flx42, thanks. I have successfully configured docker.
