### ISSUE TITLE
Instructions to use a local jobs directory are wrong.

### ISSUE THREAD

**Issue by LeitchP** [NVIDIA/nvidia-docker#803]
I tried to use the instructions to use a local jobs folder from here:
[https://docs.nvidia.com/deeplearning/digits/digits-user-guide/index.html](https://docs.nvidia.com/deeplearning/digits/digits-user-guide/index.html)

It says to use this:
-v /home/username/digits-jobs:/workspace/jobs
but this is what worked (this was digits5):
-v /home/username/digits-jobs:/jobs

**Comment by flx42** [comment]
You should report the issue here: https://devtalk.nvidia.com/default/board/228/container-digits/
