### ISSUE TITLE
NVIDIA driver lost after os upgrade and reboot

### ISSUE THREAD

**Issue by xuto2** [NVIDIA/nvidia-docker#804]
### 1. Issue or feature description
NVIDIA driver is lost after rebooting the machine (as required by os upgrade).

### 2. Steps to reproduce the issue
* Create an Ubuntu VM with an older OS image version (In our case we're using the below version, note it's not the latest version in the SKU)
    "osImageOffer": "UbuntuServer",
    "osImagePublisher": "Canonical",
    "osImageSKU": "16.04-LTS",
    "osImageVersion": "16.04.201801260",
* Install NVIDIA-driver 396.26 and nvidia-docer2(2.0.0+docker1.13.1-1) (in our case, we install them as part of the cloud-init command of the VM creation)
* Confirm the driver is working:
  **run nvidia-smi and it prints out the GPU information
  ** dmesg | grep nvidia also prints out the driver information
*Reboot the VM as indicated by the existence of /var/run/reboot-required
*The driver is not working
**run nvidia-smi and got message saying that it cannot communicate to the driver
**dmesg | grep nvidia shows nothing.
*Notice the os version is upgraded to the latest one.

In contrast, if we create the VM with the latest OS image then rebooting would not cause the issue.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by 3XX0** [comment]
Closing since this is not an issue with nvidia-docker.

If you are changing kernel, you need to have the nvidia driver compiled against it.
So make sure to setup DKMS or alternatively use [driver containers](https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(EXPERIMENTAL)) which take care of that.
