### ISSUE TITLE
Setup local mirror for CentOS/RHEL

### ISSUE THREAD

**Issue by ddeimeke** [NVIDIA/nvidia-docker#805]
Hi!

In our company only a few machines have direct access to the internet.

This is the reason why I need to setup a local mirror of CentOS/RHEL packages.

Can you please give me a starting URL for `wget --mirror`?

Thanks a lot

Dirk

**Comment by flx42** [comment]
Hi @ddeimeke, our repositories are hosted under the same git repository as the project, so look at the following:
https://github.com/NVIDIA/nvidia-docker/issues/635#issuecomment-365160098

Someone else from the community had a similar approach for our rpms:
https://github.com/NVIDIA/nvidia-docker/issues/706#issuecomment-382578153
However there is no need to use `rpm -i` here, you can setup a yum repository pointing to a local folder, same way as for the deb repository.

Let me know if that works for you.

**Comment by ddeimeke** [comment]
Works perfectly well for me.

Thanks a lot!
