### ISSUE TITLE
Multi-stage build usage for cuda,cudnn,opencv and ffmpeg

### ISSUE THREAD

**Issue by grafana2018** [NVIDIA/nvidia-docker#806]
Hi,

I am planning to write multi-stage build dockerfile for below:
  cuda9.2
  cudnn7.1
  opencv3.4.2 &
 ffmpeg

Please let me know if there is any sample Dockerfile available if any or please provide me an example.

**Comment by flx42** [comment]
We provide prebuilt images on DockerHub, you can use that as your `FROM`: https://hub.docker.com/r/nvidia/cuda/

The Dockerfiles are here:
CUDA 9.2: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.2/devel/Dockerfile
cuDNN 7.1: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.2/devel/cudnn7/Dockerfile

For OpenCV:
https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.caffe_server#L26-L41

For ffmpeg:
https://gitlab.com/nvidia/samples/blob/master/cuda/ubuntu16.04/ffmpeg-gpu/Dockerfile

**Comment by flx42** [comment]
I don't have a Dockerfile that does exactly what you want, but I provided you all the pieces. Read the Dockerfiles I pointed you to, read about multi-stage builds, and you should be able to do it.
