### ISSUE TITLE
CUDA_MPS_ACTIVE_THREAD_PERCENTAGE doesn't control the GPU usage

### ISSUE THREAD

**Issue by andrewjguo** [NVIDIA/nvidia-docker#807]
H nvidia-docker teami,

I'm following the instructions here [#419](https://github.com/NVIDIA/nvidia-docker/issues/419) to run a CUDA program inside the container, with GPU in exclusive mode and MPS daemon running. I tried to modify the CUDA_MPS_ACTIVE_THREAD_PERCENTAGE env variable inside the container to control the GPU usage. It's sort of working, because the execution time does depend on this variable, however, the GPU usage read from nvidia-smi can still climb up to 99% even if I set this env variable to 1. Feels like the variable doesn't have too much to do with the GPU usage.

Hope this is the right place for this question, really appreciate your help. Thanks

**Comment by flx42** [comment]
I think you are just misunderstanding what utilization is:
```
$ nvidia-smi --help-query-gpu | grep utilization -A2

"utilization.gpu"
Percent of time over the past sample period during which one or more kernels was executing on the GPU.
The sample period may be between 1 second and 1/6 second depending on the product.
```

Hence, if you have a CUDA kernel with only one thread running for 1s, utilization will be 100% since a CUDA kernel was active, even if the GPU was clearly under-utilized.

This is independent from partitioning the available GPU compute resources, which is what `CUDA_MPS_ACTIVE_THREAD_PERCENTAGE` does.

**Comment by andrewjguo** [comment]
Thanks for this detail explanation @flx42, it really helps! So I guess there is no easy way to verify if the `CUDA_MPS_ACTIVE_THREAD_PERCENTAGE` partitions the resources correctly. I was trying to saturate the GPU, and check if the resources/active threads could be actually limited to some value, but I was not able to find a way out.

**Comment by flx42** [comment]
Using `nvprof` might give you better metrics on the number of SMs that are being used by your kernels.

**Comment by lighttime0** [comment]
Hi Nvidia-docker team

I want to measure the number of SMs that are being used by CUDA kernels. But I can't find the way to do it in `nvprof` doc. I wish your help, and really appreciate. Thanks.
