### ISSUE TITLE
nvidia-docker is support gpu memory limit and ALU limit ?

### ISSUE THREAD

**Issue by kongsys** [NVIDIA/nvidia-docker#810]
### 1. Issue or feature description
nvidia-docker is support gpu memory limit  and ALU limit ?

**Comment by flx42** [comment]
There is no CUDA API to limit memory usage, with or without nvidia-docker.

Not sure what you want/mean by "ALU limit", the closest thing might be `CUDA_MPS_ACTIVE_THREAD_PERCENTAGE`, only available on Volta GPUs, and will require extra work to setup the MPS server. It's described here:
https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf
