### ISSUE TITLE
Missing centos7 (rhel7.5) repository?

### ISSUE THREAD

**Issue by Fiddich** [NVIDIA/nvidia-docker#811]
I am trying to sync the libnvidia-container, nvidia-container-runtime and nvidia-docker repositories directly in our Satellite server environment.

However, I get # Unsupported distribution! # Check https://nvidia.github.io/nvidia-docker

I used 
https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64
etcetera

Sincerely Pieter

**Comment by Fiddich** [comment]
Hi, the repo works properly, when I disable repo_gpgcheck (http proxy related)

The only open issue is that sha512 apparently is not supported by Red Hat Satellite 6 (Pulp)

100.0% Complete 100%
Output:
Yum Metadata: The checksum type 'sha512' is unknown.
Errors:
PLP1005: The checksum type 'sha512' is unknown.

I will try fetching them locally and import them as a temporary workaround

**Comment by Fiddich** [comment]
Ok, I could fetch all packages except nvidia-docker (both 1.x or 2)
No package nvidia-docker2 available.

**Comment by flx42** [comment]
Thanks @Fiddich!
