### ISSUE TITLE
AssertionError:  Found no NVIDIA driver on your system. Docker container, nvidia-docker

### ISSUE THREAD

**Issue by lab9001** [NVIDIA/nvidia-docker#812]
Hello,

I installed docker, nvidia-docker, and nvidia driver. For some reason, from within a docker container, a pytorch script does not detect the GPU and the driver. 

### 2. Steps to reproduce the issue: Try to run a script, written in pytorch, from within a docker container.

lab@01:~/pytorch_fnet$ ./docker/start_docker.sh

root@c295e3b7cf53:~/projects/pytorch_fnet# ./scripts/test_run.sh 
+ BUFFER_SIZE=1
+ N_ITER=16
+ RUN_DIR=saved_models/TEST
+ PATH_DATASET_CSV=data/csvs/test_run.csv
+ GPU_IDS=0
+++ dirname ./scripts/test_run.sh
++ cd ./scripts
++ pwd
+ cd /root/projects/pytorch_fnet/scripts/..
+ rm -r saved_models/TEST
+ python train_model.py --n_iter 16 --path_dataset_csv data/csvs/test_run.csv --buffer_size 1 --path_run_dir saved_models/TEST --gpu_ids 0
Traceback (most recent call last):
  File "train_model.py", line 161, in <module>
    main()
  File "train_model.py", line 98, in main
    nn_kwargs=opts.nn_kwargs,
  File "/root/projects/pytorch_fnet/fnet/fnet_model.py", line 25, in __init__
    self._init_model(nn_kwargs=self.nn_kwargs)
  File "/root/projects/pytorch_fnet/fnet/fnet_model.py", line 35, in _init_model
    self.net.cuda(self.gpu_ids[0])
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 124, in _apply
    param.data = fn(param.data)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 147, in <lambda>
    return self._apply(lambda t: t.cuda(device_id))
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/_utils.py", line 58, in _cuda
    with torch.cuda.device(device):
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/cuda/__init__.py", line 125, in __enter__
    _lazy_init()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/cuda/__init__.py", line 58, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
root@c295e3b7cf53:~/projects/pytorch_fnet# exit
exit

lab@01:~/pytorch_fnet$ nvidia-smi
Thu Aug 23 16:42:49 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.51                 Driver Version: 396.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:03:00.0  On |                  Off |
| 26%   41C    P8    16W / 250W |   1636MiB / 24433MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2374      G   /usr/lib/xorg/Xorg                            65MiB |
|    0      2455      G   /usr/bin/gnome-shell                          93MiB |
|    0      6906      G   /usr/lib/xorg/Xorg                           995MiB |
|    0      7064      G   /usr/bin/gnome-shell                         471MiB |
|    0      9251      G   /usr/lib/firefox/firefox                       3MiB |
|    0     39386      G   /usr/lib/firefox/firefox                       3MiB |
+-----------------------------------------------------------------------------+
lab@01:~/pytorch_fnet$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

lab@01:~/pytorch_fnet$ python --version
Python 2.7.15rc1

la@01:~$ nvidia-docker version
NVIDIA Docker: 2.0.3
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by flx42** [comment]
What is this `./docker/start_docker.sh` script?

**Comment by flx42** [comment]
It probably comes from the image. Does `docker run --runtime=nvidia -ti nvidia/cuda:9.0-base nvidia-smi` work?

**Comment by lab9001** [comment]
No, it doesn't work:
lab@01:~$ docker run --runtime=nvidia -ti nvidia/cuda:9.0-base nvidia-smi
Unable to find image 'nvidia/cuda:9.0-base' locally
9.0-base: Pulling from nvidia/cuda
8ee29e426c26: Already exists 
6e83b260b73b: Already exists 
e26b65fd1143: Already exists 
40dca07f8222: Already exists 
b420ae9e10b3: Already exists 
a579c1327556: Already exists 
b440bb8df79e: Already exists 
de3b2ccf9562: Already exists 
Digest: sha256:94b332ebec92d8e0db4371b441f6164527ef2b0fb58f0cebdc86e812201adf8e
Status: Downloaded newer image for nvidia/cuda:9.0-base
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=3461 /var/lib/docker/overlay2/34e4161521801e8d8f7cb71bf53f5f9eed19798cfeb2cedc06de23059f1ef388/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.

**Comment by lab9001** [comment]
Ubuntu 18.04

**Comment by lab9001** [comment]
Do you have any idea what could  be wrong with either the nvidia-docker installation or the image? Thank you very much in advance!

**Comment by flx42** [comment]
Try installing the CUDA samples (package `cuda-samples-9-2` from the official NVIDIA repository) then launch one of the sample and check if it works.

**Comment by RenaudWasTaken** [comment]
Closing as there were no followups. Feel free to reopen.
