### ISSUE TITLE
SE Linux Permissions

### ISSUE THREAD

**Issue by andyneff** [NVIDIA/nvidia-docker#814]
### 1. Issue

I just updated my machine today, and when I run an nvidia-docker container, I get the following in `/var/log/messages`

```
Aug 30 16:12:35 viola audit[25758]: AVC avc:  denied  { entrypoint } for  pid=25758 comm="nvidia-docker" path="/usr/bin/docker" dev="sdc3" ino=12832289 scontext=unconfined_u:system_r:xserver_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_runtime_exec_t:s0 tclass=file permissive=0
```

Same happens with `docker-compose`

I can change the secontext on `nvidia-docker` and that fixes it. So the main question I have

`semanage fcontext -l | grep nvidia` reveals the context rule causing the problem

```
/usr/bin/nvidia.*                                  regular file       system_u:object_r:xserver_exec_t:s0 
```

Which I suspect come from the nvidia cuda driver rpms I get from the official nvidia Fedora 27 cuda repo (Since there is still no Fedora 28 Repo).

If the context for `nvidia-docker` is indeed wrong, then maybe the nvidia-docker rpms should add a special rule, like

```
/usr/bin/nvidia-docker                           regular file       system_u:object_r:container_runtime_exec_t:s0
```

~~My understanding of selinux is still pretty weak, so I could be way off base here.~~

### 2. Steps to reproduce the issue

```
nvidia-docker run -it --rm nvidia/cuda nvidia-smi
ls -lZ /usr/bin/docker /usr/bin/nvidia-docker
```

#### Failure output

```
[root@computer bin]# nvidia-docker run -it --rm nvidia/cuda nvidia-smi
/usr/bin/nvidia-docker: line 34: /usr/bin/docker: Permission denied
/usr/bin/nvidia-docker: line 34: /usr/bin/docker: Success
-rwxr-xr-x. 1 root root system_u:object_r:container_runtime_exec_t:s0 33069424 Aug 21 13:27 /usr/bin/docker
-rwxr-xr-x. 1 root root system_u:object_r:xserver_exec_t:s0                721 Aug 21 20:25 /usr/bin/nvidia-docker
```

#### Workaround

~~sudo chcon system_u:object_r:container_runtime_exec_t:s0 /usr/bin/nvidia-docker
ls -lZ /usr/bin/docker /usr/bin/nvidia-docker~~

##### Update
```
semanage fcontext -a -f f -t container_runtime_exec_t -s system_u /usr/bin/nvidia-docker
nvidia-docker run -it --rm nvidia/cuda echo hi
```

#### Workaround output

```
-rwxr-xr-x. 1 root root system_u:object_r:container_runtime_exec_t:s0 33069424 Aug 21 13:27 /usr/bin/docker
-rwxr-xr-x. 1 root root system_u:object_r:container_runtime_exec_t:s0      721 Aug 21 20:25 /usr/bin/nvidia-docker
hi
```

### 3. Additional Information

 - Kernel version: 4.17.19-200.fc28.x86_64 #1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Docker version: 18.06.1-ce
 - NVIDIA docker version: 2.0.3
 - NVIDIA container library version: 1.0.0
 - NVIDIA Driver version: 396.44-1.fc27
 - OS: Fedora 28

https://fedoraproject.org/wiki/PackagingDrafts/SELinux#File_contexts

**Comment by scott-vsi** [comment]
This also affects nvidia-docker v1

**Comment by fyang93** [comment]
Had the same issue on CentOS 7

**Comment by Rovanion** [comment]
To work around this issue as a user on a machine with SELinux such as CentOS 7 you can run the following commands:

```
$ sudo semanage fcontext -t container_runtime_exec_t /usr/bin/nvidia-docker
$ sudo restorecon -v /usr/bin/nvidia-docker
```

I look forward to this issue being fixed in the package itself.

**Comment by rdwrt** [comment]
I think there is a typo here:

> ```
> $ sudo semanage fcontext -t container_runtime_exec_t /usr/bin/nvidia-docker
> ```

**Comment by Rovanion** [comment]
Ah, yes, there was an -a missing. Edited the comment for posterity.

**Comment by Rovanion** [comment]
Has this issue been resolved in master?

**Comment by andyneff** [comment]
Not really afaik. However, with the new "native" support, you don't need `nvidia-docker` anymore, so this path is "deprecated"

**Comment by Rovanion** [comment]
Could someone provide a link on how to set up the new implementation?

**Comment by jasonheffner** [comment]
I wasn't aware this has been integrated either ..

https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)

Also in the readme..

Note that with the release of Docker 19.03, usage of nvidia-docker2 packages are deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime. If you are an existing user of the nvidia-docker2 packages, review the instructions in the “Upgrading with nvidia-docker2” section.

**Comment by Rovanion** [comment]
Thank you!

Den fre 20 sep. 2019 kl 15:14 skrev Jason Heffner <notifications@github.com

**Comment by m-reuter** [comment]
another workaround:

sudo mv nvidia-docker nvidia-docker.copy
sudo cp nvidia-docker.copy nvidia-docker
sudo rm nvidia-docker.copy
