### ISSUE TITLE
nvidia-docker vs nvidia-container-runtime

### ISSUE THREAD

**Issue by al3x609** [NVIDIA/nvidia-docker#815]
What is the difference between this two projects?

Can I use this for Singularity containers?

**Comment by flx42** [comment]
`nvidia-container-runtime` is a modified [`runc`](https://github.com/opencontainers/runc) with a prestart hook that calls into [`libnvidia-container`](https://github.com/NVIDIA/libnvidia-container). But it is not specific to docker, it can work anywhere an OCI runtime is expected.

The `nvidia-docker2` package is tiny, it simply registers this runtime to the docker daemon by adding an entry in `/etc/docker/daemon.json`.

For Singularity, they now have an integration with `libnvidia-container`, so you can skip the `nvidia-container-runtime` and `nvidia-docker2` packages altogether.
