### ISSUE TITLE
error with nvidia/cuda:9.2-cudnn7-runtime

### ISSUE THREAD

**Issue by dwSun** [NVIDIA/nvidia-docker#817]
run this command:
```sh
docker run --runtime=nvidia --rm nvidia/cuda:9.2-cudnn7-runtime nvidia-smi
```

got this:
```sh
8ee29e426c26: Already exists 
6e83b260b73b: Already exists 
e26b65fd1143: Already exists 
40dca07f8222: Already exists 
b420ae9e10b3: Already exists 
838f2b6d86b5: Pull complete 
624ff3713e92: Pull complete 
ecc57e829639: Pull complete 
c29db5d7fc7e: Pull complete 
ab9e1358fc61: Pull complete 
Digest: sha256:590e407c60bcdd2f0b359950bac4cbee20c846d588473b91fd8b75bc9da36b06
Status: Downloaded newer image for nvidia/cuda:9.2-cudnn7-runtime
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.2 --pid=6487 /var/lib/docker/btrfs/subvolumes/278ab9933b95ca06d2217f7ecda336aff5bdf3c3e8e2f9ff6c1ec3428c2c501c]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: cuda >= 9.2\\\\n\\\"\"": unknown.

```

but with this :
```sh
docker run --runtime=nvidia --rm nvidia/cuda:9.1-cudnn7-runtime nvidia-smi
```
everything looks fine:
```sh
```
Unable to find image 'nvidia/cuda:9.1-cudnn7-runtime' locally
9.1-cudnn7-runtime: Pulling from nvidia/cuda
8ee29e426c26: Already exists 
6e83b260b73b: Already exists 
e26b65fd1143: Already exists 
40dca07f8222: Already exists 
b420ae9e10b3: Already exists 
a58c0f97f243: Pull complete 
f0f47fee17ca: Pull complete 
de3b2ccf9562: Pull complete 
0f1e0e3d9e5b: Pull complete 
6c84ad5a5bae: Pull complete 
Digest: sha256:fdf2b55d25f50cca70901bfc2746961cc4ea9e89b48840ebee9607803a07bfaf
Status: Downloaded newer image for nvidia/cuda:9.1-cudnn7-runtime
Mon Sep  3 15:05:32 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   53C    P5    20W / 120W |      0MiB /  6076MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by cliffwoolley** [comment]
For CUDA 9.2, you need driver 396.xx or later.
