### ISSUE TITLE
Nvidia Docker in docker machine

### ISSUE THREAD

**Issue by Bit-Beast** [NVIDIA/nvidia-docker#819]
Is it possible to run CUDA applications in a container in docker machine? If yes,how?

**Comment by Bit-Beast** [comment]
Thanks for the answer!!
Few more doubts (I am not sure if this is the right place to ask these)

I am creating docker-machine using virtualbox driver which has tiny core linux.  

How to install cuda driver in Tiny core linux?

 Or is it possible to use virtualbox with Ubuntu as OS in docker machine?

Also nvidia-smi doesn't work in docker machine. Any idea how to resolve that?

**Comment by flx42** [comment]
You would have to figure out how to passthrough the GPU device to the virtual machine, and *then* install the CUDA driver inside the guest OS. This is outside the scope of `nvidia-docker`, so you are on your own here.
