### ISSUE TITLE
nvidia-docker in nvidia linux repositories

### ISSUE THREAD

**Issue by jendap** [NVIDIA/nvidia-docker#82]
Can you please add nvidia-docker to linux repositories?

Ubuntu ppa would be nice. Or just add it to nvidia rpm and deb repos? For example here: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64

**Comment by 3XX0** [comment]
We plan on doing it when we get out of beta (relatively soon)

**Comment by jendap** [comment]
Cool. Thanks.

**Comment by jendap** [comment]
@3XX0 are you getting out of beta?

**Comment by 3XX0** [comment]
A lot of things are moving with CUDA 8 and Pascal out and we might tag RC3 before the final release.
Also, it may be wise to wait for Dockercon since it's most likely going to bring more users to the mix and help us identify any blocker before 1.0.

**Comment by jendap** [comment]
That's the beauty of having it in repo - once can run apt-get upgrade - and get your changes.

Should we recommend it in tensorflow? The hack using variables we recomend is not good. But if you change instructions every other week? That is also not great.

BTW: Have you at least talked with Docker folks if this is the right way to do it? Is this what Docker folks expect to be the main way special hardware should be wired into docker?

**Comment by Kaixhin** [comment]
I will also have to submit PRs to various repos (Theano, Lasagne, mxnet etc.) to update their docs when I move my files to use the Docker plugin. Currently I would recommend the following: ``docker run -it `curl -s localhost:3476/docker/cli` kaixhin/cuda-caffe``. I can point users to this repo with respect to installing `nvidia-docker`, but the command to run the containers needs to be stable.

**Comment by 3XX0** [comment]
The commands are stable but I would recommend using `nvidia-docker` rather than `docker` as it will perform additional version checks (see today's issue #106 for example).
The only instructions that will change is how to install it. @jendap I will try to do my best to have our packages distributed through our repo asap.

Yes we had multiple discussion with the Docker folks.
It's not perfect but there are no other ways to do what's needed at the moment.
I will probably discuss a proposal I have at Dockercon see if we can work something out. The idea would be to extend Docker to support hooks. I can already see several other applications (e.g. Security policy, Infiniband).

**Comment by Kaixhin** [comment]
@jendap What's the use case for the plugin then? According to the wiki, [`run` and `create`](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#description) are modified, but the rest of the commands are passed through. It seems that `nvidia-docker` only mounts the required files [with the right metadata](https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection#nvidia-docker) (regardless of version checking)? My plan is to move over to `nvidia/cuda` for base images, but for now I can work on adding them to `kaixhin/cuda` to ease the transition.

**Comment by 3XX0** [comment]
Everything is explained in the documentation. `nvidia-docker` and `nvidia-docker-plugin` work in pair, the plugin handles the creation and mounts of the [driver files](https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-driver).

`nvidia-docker` is similar to ```docker run -it `curl -s localhost:3476/docker/cli```` except that it checks the [image/driver compatibility](https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection) and enables remote deployment.

**Comment by Kaixhin** [comment]
@3XX0 Thanks for clarifying. I could work this out from the [nvidia docker](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker) page, but it might also help to have the summary you just gave on the [Why NVIDIA Docker](https://github.com/NVIDIA/nvidia-docker/wiki/Why%20NVIDIA%20Docker) page?

**Comment by jendap** [comment]
Thank you @3XX0! I will update all of our documentation to send people to nvidia-docker. Hence the repo will be nice.

**Comment by flx42** [comment]
Sorry, we're late, but we're working on it...

**Comment by jeffstokes72** [comment]
Still working on it @flx42  ?

**Comment by flx42** [comment]
@jeffstokes72: we're working on a new approach for enabling GPU support in Docker and other container technologies. We should be able to have this new package on a NVIDIA package repository.
However, for `nvidia-docker`, I don't think it will happen, sorry.

**Comment by 3XX0** [comment]
Closing, our repositories are live!
