### ISSUE TITLE
Can I set CUDA_MPS_ACTIVE_THREAD_PERCENTAGE for each container?

### ISSUE THREAD

**Issue by lighttime0** [NVIDIA/nvidia-docker#822]
Hi Nvidia-docker team,

I'm wondering can I set CUDA_MPS_ACTIVE_THREAD_PERCENTAGE for each container, so I can share a GPU between multiple containers and control the GPU utilization of each container.

Thanks.

**Comment by flx42** [comment]
Sure, it should work. But you have to do it manually.
There are multiple issues on MPS already: #419 #728 #807 #810

**Comment by Sakuralbj** [comment]
Is CUDA_MPS_ACTIVE_THREAD_PERCENTAGE can limit the GPU usage of tensorflow task container in Volta-GPU?@flx42
