### ISSUE TITLE
unable to import tensorflow, ImportError: libcublas.so.9.0

### ISSUE THREAD

**Issue by sathiez** [NVIDIA/nvidia-docker#823]
when I import tensorflow I get the below mentioned error,
"ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory"
but libcublas.so.9.0 is avalable,
$**ldconfig -p | grep libcublas** (shows)
libcublas.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcublas.so.9.0

$**nvcc --version** 
Cuda compilation tools, release 9.0, V9.0.176
Cudnn-version - 7.0.5
#**docker run --runtime nvidia --rm nvidia/cuda nvidia-smi**
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0  On |                  N/A |
| 29%   35C    P8    N/A /  75W |   1047MiB /  4038MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by gqoew** [comment]
Hi,

I am currently facing the same issue. When I import `tensorflow` inside my custom container, I get the error

> ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
> Failed to load the native TensorFlow runtime.

My host machine config:

- cuda 9.0
- nvidia-docker2

In my container, started with:


docker run -it --runtime=nvidia MyCustomImage

**Comment by flx42** [comment]
Which docker image are you using?
It's likely a problem from the image itself.

**Comment by gqoew** [comment]
@flx42 

I use `python:3.6.5-jessie`:

```
docker run -it --runtime=nvidia python:3.6.5-jessie
```

Then, I installed tensorflow via `pip install tensorflow-gpu`. After this, `import tensorflow `retruns `ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory` in python shell.

Do I need to add something to the image?

**Comment by gqoew** [comment]
@flx42 Thanks, I understand now. Do I still need to install Cuda on the host?

**Comment by flx42** [comment]
No, you only need to have the NVIDIA driver on the host.  You don't need the CUDA **toolkit**

**Comment by sathiez** [comment]
Eventhough I have nvidia/cuda docker image in my host. I get the same error, I build my image using  "s2i build 'src-folder' seldonio/seldon-core-s2i-python3:0.1 'imageName"

**Comment by gqoew** [comment]
@flx42 

I tried to build the image `nvidia/cuda:9.0-base` (https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile)
However it seems there is the problem with the checksum step. I opened an issue in the related repository (https://gitlab.com/nvidia/cuda/issues/21)

**Comment by gqoew** [comment]
@flx42 

I tried using `nvidia/cuda:9.0-base` from dockerhub:

```
docker run -it --runtime=nvidia nvidia/cuda:9.0-base
```

Then, I installed tensorflow via `pip install tensorflow-gpu`. After this, `import tensorflow` **still returns** `ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory` in python shell.

Also, `ldconfig -p | grep libcublas` returns no results.

**Comment by sathiez** [comment]
@flx42 
Hi,
where can I get nvidia/cuda.sh file?
 source2image (s2i) supports only .sh files instead of docker file

**Comment by sathiez** [comment]
On using runtime images I am unable to build image. I get the following error,
|"Step 16/46 : FROM ${repository}:9.0-base-ubuntu16.04
**invalid reference format** "

**Comment by flx42** [comment]
@gqoew the `base` image tags do not bundle libcublas, you need to install it. Look at the official TensorFlow dockerfile.

@sathiez we do not support your tool.

**Comment by SumNeuron** [comment]
@flx42  I have looked at the official TF docker file (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/nvidia.Dockerfile) but I still get things like 

E: Unable to locate package libcudnn7
E: Unable to locate package libnccl2
