### ISSUE TITLE
nvidia runtime in kubernetes

### ISSUE THREAD

**Issue by sathiez** [NVIDIA/nvidia-docker#828]
I can able to run my cuda image using 
"docker run --runtime nvidia imgname"
But when I deploy in kubernetes  I get the following error for tensorflow 
"ImportError: libcuda.so.1: cannot open shared object file: No such file or directory"
How to access "--runtime nvidia" in kubernetes.

**Comment by RenaudWasTaken** [comment]
Hello!

Did you take a look at https://github.com/NVIDIA/k8s-device-plugin ?

**Comment by RenaudWasTaken** [comment]
Closing since there weren't any followups
