### ISSUE TITLE
Can't run docker cuda 10 image, with tesla and driver 390 (and 9.1 cuda on the host)

### ISSUE THREAD

**Issue by adegomme** [NVIDIA/nvidia-docker#835]
Hello, 

I'm trying to load a recent docker image with cuda 10 ( nvidia/cuda:10.0-devel-ubuntu18.04 ) on a system with a V100 and driver 390.87 , which should be enough if I read https://github.com/NVIDIA/nvidia-docker/wiki/CUDA .

But I get 
docker run --runtime=nvidia -ti --rm nvidia/cuda:10.0-devel-ubuntu18.04 nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:
402: container init caused \"process_linux.go:
385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=2728 /home/docker/overlay2/d046c7eaf170a19d4defb25a4af7d46be3aad66a1025d445a37ee2f06ee13ff3/merged]
nvidia-container-cli: requirement error: unsatisfied condition: driver < 385\\\\n\\\"\"": unknown.

which is odd. The requirement seems to be pretty strict : driver>=384,driver<385 instead of simply >=384
Is this expected ?

cuda 9.1 is installed on the host, 10 is not, but this should not be necessary, if I'm reading https://github.com/NVIDIA/nvidia-docker/wiki/CUDA 
Then it's also a bit odd that 9.2 version of the docker image requires it and fails with a "unsatisfied condition: cuda >= 9.2" message . 
9.1 version works as expected.

 - [x] Kernel version from `uname -a` : 4.18.0-2-amd64
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`  : Driver Version: 390.87
 - [x] Docker version from `docker version` : 18.06.1-ce
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
everything is 390.87, except 
nvidia-cuda-dev     9.1.85-4+b1  
nvidia-container-runtime           2.0.0+docker18.06.1-1                
nvidia-container-runtime-hook      1.4.0-1   
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.0
build date: 2018-09-20T20:23+00:00
 - [x] NVIDIA container library logs : 
[nvidia-container-runtime-hook.log](https://github.com/NVIDIA/nvidia-docker/files/2442248/nvidia-container-runtime-hook.log)
attached
 - [x] Docker command, image and tag used
docker run --runtime=nvidia -ti --rm nvidia/cuda:10.0-devel-ubuntu18.04 nvidia-smi

**Comment by flx42** [comment]
@adegomme sorry, the wiki page was incorrect. I've fixed it now.
It **has** to be `384` OR `400` to get CUDA 10 support. Versions in-between won't work.

**Comment by adegomme** [comment]
Hi,
We tried on another system we have with two K40c (+a quadro), with 384.111 driver (and cuda 9.0 on the host), but it also fails, with a message stating that the expression for requirements seems invalid :

docker run --runtime=nvidia -ti --rm nvidia/cuda:10.0-devel-ubuntu18.04 nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=11183 /var/lib/docker/overlay2/9af74c82a2afd489cbaf8bcb8a4d513816cd8452d99b6496433c07dc549959f3/merged]\\\\nnvidia-container-cli: requirement error: invalid expression\\\\n\\\"\"": unknown.

ps: could it be possible to make these messages more user friendly? These big lines tend to frighten and confuse users.

Best regards

**Comment by flx42** [comment]
> ps: could it be possible to make these messages more user friendly? These big lines tend to frighten and confuse users.

We have limited options here, our output is compacted by `runc` and `docker`.

In your case, you need to upgrade libnvidia-container to to https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.0
Your current version of libnvidia-container doesn't recognize the expression `brand=tesla`

**Comment by adegomme** [comment]
So, updating from the beta to the release changed the error
"process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=6650 /var/lib/docker/overlay2/1009f7ebb78e6c68200fc47baeeb5ae57013db16c03e93e786dfc90b874b818e/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.

This is more coherent with the bogus quadro GPU we have on the system, which is the first in the nvidia-smi list

https://github.com/NVIDIA/libnvidia-container/blob/master/src/cli/configure.c (~ l256) seems to check GPUs one by one and fail if one does not match. Setting -e NVIDIA_VISIBLE_DEVICES=1,2 was the key here to avoid the quadro and go to the Teslas.

Maybe extending the check to validate if other available GPUs than the first match the requirements would be nice ?
Best regards and thanks for the help.

**Comment by flx42** [comment]
> Maybe extending the check to validate if other available GPUs than the first match the requirements would be nice ?

This works as intended, the start will fail if *any* GPU doesn't match, because you would not be able to use it with CUDA 10.0.

**Comment by harahu** [comment]
@flx42 I have the same issue as others here: A Tesla GPU coupled with a too high driver version: 390.116

I want to downgrade to 384.x in order to use cuda 10. I can find lots of documentation on how to _install_ nvidia drivers, but not how to downgrade them. For instance if I try:
`$ sudo apt install nvidia-384`, I get this message:
`nvidia-384 is already the newest version (390.116-0ubuntu0.18.04.1).`

Is there a quick and easy way to do this (in my case only using CLI on Ubuntu Xenial)?

**Comment by fengyuentau** [comment]
The cuda version on my machine is `NVIDIA-SMI 384.145                Driver Version: 384.145`. Still cannot run cuda 10 images.

I wonder if cuda version of `384.145` is counted as version in-between `384` and `400`?
