### ISSUE TITLE
Docker 1.11.0 incompatibility

### ISSUE THREAD

**Issue by arassadin** [NVIDIA/nvidia-docker#84]
Following the official instruction,

> nvidia-docker run --rm nvidia/cuda nvidia-smi

I'm getting

**nvidia-docker | 2016/04/21 16:29:46 Error: unsupported Docker version**

> docker --version

**Docker version 1.11.0, build 4dc5990**

**Ubuntu 14.04**, latest **nvidia-docker**

I can see on Wiki
> Docker >= 1.9

in requirements. If it supports only limited number of **Docker** versions, please specify it. If it's compatibility bug - now you aware J.

**Comment by flx42** [comment]
see #73 
Sorry about that, we need to regenerate a new package, but first we want to get some fixes in the code before the next release.

**Comment by arassadin** [comment]
Ok, thanks. Just glad that you aware.

**Comment by narfanator** [comment]
I'm now getting this issue, possibly on Docker 12? What's the officially supported Docker version?

**Comment by flx42** [comment]
@narfanator see #294
