### ISSUE TITLE
Mirroring yum/rpm repos to internal repo server

### ISSUE THREAD

**Issue by b1r63r** [NVIDIA/nvidia-docker#840]
### 2. wget -np -nH -c -m --directory-prefix=/repos/nvidia-docker/centos7/x86_64/ --cut-dirs=3 http://nvidia.github.io/nvidia-docker/centos7/x86_64/
Connecting to nvidia.github.io|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-09 15:02:18 ERROR 404: Not Found.

### 3. We need to be able to mirror these repos to internal repo-server since the docker hosts we need to install this on cannot have internet access. I can find no documentation on how to do it for these 3 repos:
baseurl=https://nvidia.github.io/libnvidia-container/centos7/$basearch
baseurl=https://nvidia.github.io/nvidia-container-runtime/centos7/$basearch
baseurl=https://nvidia.github.io/nvidia-docker/centos7/$basearch

**Comment by flx42** [comment]
We have an option documented here:
https://github.com/NVIDIA/nvidia-docker/issues/635#issuecomment-365160098
You can adapt it for the RPM repository by changing the `baseurl` fields.

**Comment by RenaudWasTaken** [comment]
Closing as this seems to have been resolved.
