### ISSUE TITLE
Failing with debian host O/S, openSUSE container O/S

### ISSUE THREAD

**Issue by Avalon-PN** [NVIDIA/nvidia-docker#843]
I have a debian stretch host with working docker-ce and cuda packages:
```
||/ Name                          Version             Architecture        Description
+++-=============================-===================-===================-===============================================================
ii  docker-ce                     18.06.1~ce~3-0~debi amd64               Docker: the open-source application container engine
ii  libcuda1:amd64                390.87-2~bpo9+1     amd64               NVIDIA CUDA Driver Library
ii  nvidia-container-runtime      2.0.0+docker18.06.1 amd64               NVIDIA container runtime
ii  nvidia-container-runtime-hook 1.4.0-1             amd64               NVIDIA container runtime hook
ii  nvidia-docker2                2.0.3+docker18.06.1 all                 nvidia-docker CLI wrapper
ii  nvidia-driver                 390.87-2~bpo9+1     amd64               NVIDIA metapackage
```
I can run `nvidia-docker run --rm nvidia/cuda:9.1-devel nvidia-smi` successfully.  (The container is using Ubuntu 16.04.5 LTS.  It appears that the host's nvidia libraries from `/usr/lib/x86_64-linux-gnu/` have been mapped into the container.)

Another container/image is based on OpenSUSE 42.3 and I cannot run the `nvidia-smi` command due to this error: *Failed to initialize NVML: Driver/library version mismatch*

Specific details of the Host/Container are as follows:

- [x] The kernel modules are loaded:  
    ```
    # cat /proc/driver/nvidia/version
    NVRM version: NVIDIA UNIX x86_64 Kernel Module  390.87  Tue Aug 21 12:33:05 PDT 2018
    GCC version:  gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
    ```
- [x] The devices are available:  
    ```
    # ls -al /dev/nvidia*
    crw-rw-rw- 1 root root 246,   0 Oct 22 00:46 /dev/nvidia-uvm
    crw-rw-rw- 1 root root 246,   1 Oct 22 00:46 /dev/nvidia-uvm-tools
    crw-rw-rw- 1 root root 195,   0 Oct 22 00:46 /dev/nvidia0
    crw-rw-rw- 1 root root 195, 255 Oct 22 00:46 /dev/nvidiactl
    ```
- [x] `ldconfig` is setup with these directories in the search path:  
    ```
    /usr/local/cuda/lib64
    /usr/local/cuda-9.1/targets/x86_64-linux/lib
    /usr/local/nvidia/lib
    /usr/local/nvidia/lib64
    ```
- [x] docker runtime has been set to `nvidia`:
    ```
    # docker inspect ....
            "Runtime": "nvidia",
                "com.nvidia.cuda.version": "9.1.85",
                "com.nvidia.volumes.needed": "nvidia_driver",
    ```
- [x] I'm not sure which of these environment variables are used inside an _openSUSE_ operating system, but these appear to be the standard set:
    ```
            "Env": [
                "NVIDIA_REQUIRE_CUDA=cuda>=9.1",
                "CUDA_PKG_VERSION=9-1=9.1.85-1",
                "CUDA_VERSION=9.1.85",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
            ],
    ```
- [x] The container has these [zypper](https://en.opensuse.org/SDB:Zypper_manual_(plain)) packages installed:
    ```
    # zypper --no-refresh  packages --installed-only | grep -Ei "cuda|nvidia" 
    i+ | cuda       | cuda-9-1                          | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-command-line-tools-9-1       | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-compiler-9-1                 | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-cublas-9-1                   | 9.1.85.3-1                      | x86_64
    ...
    i  | cuda       | cuda-drivers                      | 396.44-1                        | x86_64
    ...
    i  | cuda       | cuda-runtime-9-1                  | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-samples-9-1                  | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-toolkit-9-1                  | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-tools-9-1                    | 9.1.85-1                        | x86_64
    i  | cuda       | cuda-visual-tools-9-1             | 9.1.85-1                        | x86_64
    i  | cuda       | nvidia-computeG04                 | 396.44-0                        | x86_64
    ...
    ```
- [x] The host's nvidia libraries from `/usr/lib/x86_64-linux-gnu/` do *NOT* appear to have been mapped into the container (where that directory does _not_ exist).

1. What does the `"com.nvidia.volumes.needed": "nvidia_driver"` mean?  (Can I find/inspect this volume somewhere/somehow?)
1. Can you tell me if/how the host's kernel driver libraries get made available to the container?
1. Is this version of debian host & openSUSE container a working configuration?  (We had an earlier instance with debian/jessie and openSUSE/13.2 which I believe worked OK.)
1. Can you suggest a fix for the `Driver/library version mismatch` error ?

**Comment by flx42** [comment]
>  The container has these zypper packages installed:
> [...]
> i  | cuda       | cuda-drivers                      | 396.44-1     

That's your problem, you should not install the device drivers inside the container.

> What does the "com.nvidia.volumes.needed": "nvidia_driver" mean? (Can I find/inspect this volume somewhere/somehow?)

You do not need to care since you are running nvidia-docker v2. For v2, just make sure you set the environment variable `NVIDIA_VISIBLE_DEVICES` in your Dockerfile to mark the container as a GPU container. The documentation is here:
https://github.com/nvidia/nvidia-container-runtime#nvidia_visible_devices

And here's how we set those variables in our CUDA 9.0 container image for CentOS 7:
https://gitlab.com/nvidia/cuda/blob/centos7/9.0/base/Dockerfile#L29-31

**Comment by Avalon-PN** [comment]
Thanks, Felix!
Yes, that was it.  I also removed `nvidia-computeG04` which was providing a different version of `/usr/lib64/libnvidia-ml.so.1` than I needed.

As an aside, I'm curious (from your second link/URL) whether setting `ENV CUDA_PKG_VERSION 9-0-$CUDA_VERSION-1` would have a different syntax for debian-based distros vs redhat.  i.e. I thought debian would have used an "=" after the 9-0, whereas package managers using RPMs might not?  However, as this is not mentioned in the documentation, perhaps I'm mistaken?

**Comment by flx42** [comment]
`CUDA_PKG_VERSION` is just for build purposes :) It has no effect at runtime.
And yes, it's different for deb packages.
