### ISSUE TITLE
cudaGetDeviceCount returned 3

### ISSUE THREAD

**Issue by dllehr81** [NVIDIA/nvidia-docker#844]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### Error

Receive `cudaGetDeviceCount returned 3` when running `deviceQuery` in a container.

This error doesn't always occur, but when it finally does, every other container will fail the same way until a reboot is issued.

This error only occurs in containers..running `deviceQuery` on the host works successfully

So far this only occurs when using `nvidia-docker2` and `cuda10`

### Steps to reproduce the issue
```
# Startup instance of Cuda 10 container
`nvidia-docker run --ti nvidia/cuda-ppc64le:10.0-runtime-ubuntu18.04`
# Install cuda samples
`apt-get update && apt-get install -y cuda-samples-10-0`
# Make deviceQuery
`cd /usr/local/cuda-10.0/samples/1_Utilities/deviceQuery`
`make`
#Execute deviceQuery
`./deviceQuery`
```

### Software Levels)
Distro: `Ubuntu 18.04`
cuda_level: `10.0.130-1`
nvidia-docker_level: `nvidia-docker2                                  2.0.3+docker18.06.1-1 `
nvidia-container-runtime_level: `nvidia-container-runtime                        2.0.0+docker18.06.1-1`
docker_level:  ` docker-ce                                       18.06.1~ce~3-0~ubuntu `
nvidia-smi: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000004:04:00.0 Off |                    0 |
| N/A   30C    P0    42W / 300W |      0MiB / 31744MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000004:05:00.0 Off |                    0 |
| N/A   29C    P0    41W / 300W |      0MiB / 31744MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000035:03:00.0 Off |                    0 |
| N/A   27C    P0    40W / 300W |      0MiB / 31744MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000035:04:00.0 Off |                    0 |
| N/A   32C    P0    41W / 300W |      0MiB / 31744MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by flx42** [comment]
Could be a driver bug, anything in the kernel log when this happens?

**Comment by dllehr81** [comment]
No, nothing stands out. Every message from `nvidia` occurred when we initially booted up and loaded the kernel module.  

Can you think of a way the driver would behave differently if it was in a container, vs. the host?

**Comment by dllehr81** [comment]
I should also clarify, whenever this starts happening.  Running `deviceQuery` and other commands from the host OS always work.  It's only when in a container that they start to fail.  Hence my question about any reason a driver would behave differently when executed by libcuda from a container vs the host.

**Comment by flx42** [comment]
mmm, OK. In this case I would use `strace` and compare the traces on the host and inside the container. It might provide some insight on what is failing inside the container.

**Comment by dllehr81** [comment]
@flx42 I had looked at the strace between host and container...everything looked to be in order...the box was rebooted before I had a chance to save off the traces....we had a similar issue happen today on a cuda 9.2 kubernetes cluster.  The versions were different, but same result...RC3 on a container while the host was successful.  I have the straces from both if you'd care to look?
[strace-failpod.txt](https://github.com/NVIDIA/nvidia-docker/files/2530473/strace-failpod.txt)
[strace-good.txt](https://github.com/NVIDIA/nvidia-docker/files/2530474/strace-good.txt)

**Comment by flx42** [comment]
How come libcuda.so is in `/usr/local/nvidia`?
```
open("/usr/local/nvidia/lib64/libcuda.so.1", O_RDONLY|O_CLOEXEC) = 3
```
You are not running our device plugin?

**Comment by dllehr81** [comment]
This particular error was on kubernetes...I believe their plugin was using the `nvidia-docker` volume plugin...the original error wasn't, it was pure `nvidia-docker2`  We can wait until it recreates on a cuda10 box again if that would help

**Comment by flx42** [comment]
Yeah, please share the traces (with `-f`) with `nvidia-docker2`.

**Comment by flx42** [comment]
Any update @dllehr81?

**Comment by RenaudWasTaken** [comment]
Any updates on this? This seems to be a worrying bug.

**Comment by dllehr81** [comment]
Hey Everyone...this one was pretty pervasive a month ago.  Since we've moved to the 410.72 driver, we haven't been this.  We did have another issue with that driver.  But it was with Ubuntu, and on the host OS, so nothing involving nvidia-docker.  If you want we can close this.  I can reopen if the problem comes back in future driver updates?

**Comment by RenaudWasTaken** [comment]
Sounds good! Thanks for your help :)

**Comment by dllehr81** [comment]
@RenaudWasTaken We gave recreated this issue

`nvidia-container-runtime-hook-1.4.0-2.ppc64le`
NVIDIA driver: `418.40.04-4`
Container: `nvidia/cuda-ppc64le:10.1-runtime-ubuntu18.04`

**Comment by dllehr81** [comment]
@RenaudWasTaken We are seeing these errors intermittently, normally we see it when we switch to a new driver (which coincides with our release changes)  Hence seeing it in November, then not for awhile.  Back then the goal was to collect some straces from the host(worked) and the container(failed)  Is there more data we can collect?  Or is there some area I can look at to try and get you  more information?  I can setup a call if you'd like to try and debug some possible ideas?

**Comment by RenaudWasTaken** [comment]
Sorry for not looking into this, I'll try to take a look at it this week.
In all likelihood I'll have to bubble up this to the driver team.

**Comment by dllehr81** [comment]
I created an issue in NVONLINE...do you have availability into that service?  If so, I'll add you to the bug tracker as well.
Douglas LehrBare Metal Linux DeveloperMaster Inventor720-349-7986
 
 
----- Original message -----From: Renaud Gaubert <notifications@github.com>To: NVIDIA/nvidia-docker <nvidia-docker@noreply.github.com>Cc: Douglas Lehr <dllehr@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [NVIDIA/nvidia-docker] cudaGetDeviceCount returned 3 (#844)Date: Sun, May 5, 2019 11:42 PM 
Sorry for not looking into this, I'll try to take a look at it this week.In all likelihood I'll have to bubble up this to the driver team.

**Comment by RenaudWasTaken** [comment]
Looks like, it got routed to myself internally :D

**Comment by slmatrix** [comment]
has there been any update to fix the problem? I have the exact same problem and frankly, I am tired.

**Comment by slmatrix** [comment]
```
./bin/x86_64/linux/release/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 30
-> unknown error
Result = FAIL
```

this is with **NVIDIA-SMI 418.67**

**Comment by RenaudWasTaken** [comment]
After some internal investigations, this seems to be linked to this specific issue: https://bugzilla.redhat.com/show_bug.cgi?id=1746415
