### ISSUE TITLE
Wiki update?

### ISSUE THREAD

**Issue by melvyniandrag** [NVIDIA/nvidia-docker#847]
Might be worth mentioning in the [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-the-nvidia-driver) that the package manager installation of the cuda drivers might cause issues with [32 bit applications](https://github.com/ValveSoftware/steam-for-linux/issues/5778). The issue is compatibility with Steam, and my main uses for my power house gpus are CUDA and gaming, and I'm sure there are many similar people out there. Kind of a shame that the package manager installer for the 410 driver doesn't play nice with Steam. Just spent a while researching this sisue, might be worth it to mention it in the wiki.

**Comment by flx42** [comment]
This isn't exclusive to containers so I don't think the `nvidia-docker` wiki is the right place. We prefer to defer to the official NVIDIA forum for driver installation issues: https://devtalk.nvidia.com/
