### ISSUE TITLE
Using Linux Mint

### ISSUE THREAD

**Issue by tkocou** [NVIDIA/nvidia-docker#848]
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Why isn't there an alternative method to pull the relevant files? Linux Mint 19 is a derivative of supported Ubuntu 18.04.**

**Comment by 3XX0** [comment]
Linux Mint is not supported, if you wish to install nvidia-docker on it, you will need to register the ubuntu 18.04 repositories manually:

```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
```

**Comment by tkocou** [comment]
Thank you. The instructions worked correctly.

**Comment by RenaudWasTaken** [comment]
Closing as the issue seems resolved.

**Comment by KumarAniket** [comment]
On running docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi, I am getting the following error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=13462 /var/lib/docker/overlay2/98c0f7cb0ad21bd9e7f88e05273008e88c160b5b8e73cd4fdccecb4571daf58e/merged]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.
