### ISSUE TITLE
Deprecating kaixhin/cuda

### ISSUE THREAD

**Issue by Kaixhin** [NVIDIA/nvidia-docker#85]
Great work on this repo! Looks like `nvidia-docker` is on beta status and will hopefully see a proper release soon, so I'm happy to work on deprecating [`kaixhin/cuda`](https://hub.docker.com/r/kaixhin/cuda/). I've done an early test where I've installed `nvidia-docker-plugin` from the [deb file](https://github.com/NVIDIA/nvidia-docker/wiki/Installation#installing-from-binaries), replaced `kaixhin/cudnn` with `nvidia/cuda:7.5-cudnn4-devel` in a Docker image for Torch, built it, and then ran it with ``sudo docker run -it `curl -s localhost:3476/docker/cli` torch``. Successfully ran `nvidia-smi` and played around with Torch's CudaTensors.

Is that all I need to do? Tell people to install the plugin and then update the command they use to run images?

**Comment by 3XX0** [comment]
Yes, however be aware that if you use `docker` instead of `nvidia-docker`, you won't be able to perform CUDA version checks and remote deployments (see [internals](https://github.com/NVIDIA/nvidia-docker/wiki/Internals))

**Comment by Kaixhin** [comment]
My images are still restricted to the exact (major + minor) driver versions, so having a [range](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements) is an improvement. For the same reason, not being able to check CUDA versions is fine.

The wiki for [remote deployments](https://github.com/NVIDIA/nvidia-docker/wiki/Remote-deployment) only has a diagram at the moment. It appears to be running a CUDA-enabled container on a remote machine transparently? Again, I don't think it should be an issue.

I will probably start work on porting this weekend, but will need https://github.com/NVIDIA/nvidia-docker/issues/40 to be fixed eventually. Presumably by the first official release. Feel free to close unless you think there are other issues I should be aware of.

**Comment by flx42** [comment]
ping @3XX0 to fill the gaps in the remote deployment doc :)

**Comment by 3XX0** [comment]
Will do

**Comment by Kaixhin** [comment]
Sorry, two more questions. Is the `curl -s localhost:3476/docker/cli` command likely to change? And given https://github.com/NVIDIA/nvidia-docker/issues/7, is `nvidia/cuda` going to be available in the next half year?

**Comment by 3XX0** [comment]
We intend to keep plugin APIs and Docker images compatibility for the duration of 1.X
So no that won't change and yes all the images already published will stay that way.

**Comment by jimfleming** [comment]
Sorry to resurrect this thread—@3XX0, is this there any more info on remote deployment available? This page is pretty sparse: https://github.com/NVIDIA/nvidia-docker/wiki/Remote-deployment

I can open a separate issue if that's preferable.

**Comment by flx42** [comment]
You can find details here: https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

The page you linked should only provide technical details about the implementation.

**Comment by flx42** [comment]
And this:
https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#running-it-remotely

**Comment by jimfleming** [comment]
Thanks! The second one has what I need.

**Comment by Kaixhin** [comment]
Now that my [Dockerfiles](https://github.com/Kaixhin/dockerfiles) are based on `nvidia/cuda` you may want to add them to your list of [third-party images](https://github.com/NVIDIA/nvidia-docker/wiki/Third-party)? Either as a group or individual ones e.g. for Torch and MXNet.

**Comment by 3XX0** [comment]
The third party section only lists official project images, otherwise it could get confusing for users.
