### ISSUE TITLE
apt sources list download script doesn't work on Devuan

### ISSUE THREAD

**Issue by eyalroz** [NVIDIA/nvidia-docker#851]
I use Devuan ASCII (the systemd-free version of Debian 9 stretch). The installation instructions [here](https://nvidia.github.io/nvidia-docker/) suggest running the following:
```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
```

But this fails, for two reasons:
1. `/etc/os-release` doesn't have a `$VERSION_ID` variable
2. The `$ID` is `devuan`, and AFAICT, there's no folder or symlink starting with this name on the server

The first issue can be solved by running `VERSION_ID=$(cat /etc/debian_version)`. And that would work for plain vanilla Debian as well (not sure about Ubuntu).

For the second issue alone, you could add some script code for substituting devuan with debian (e.g. used sed), or perhaps use the `ID_LIKE` field in `/etc/os_release`

But if we consider both issues, it might be better to support Devuan "properly", in the sense of having a devuan1 and devuan2 folders, or having those symlinked to debian8 and debian9.

**Comment by 3XX0** [comment]
Devuan is not supported, you can always specify the debian release which correspond to your devuan one manually instead of relying on `/etc/os-release`

**Comment by eyalroz** [comment]
> Devuan is not supported

Well, I didn't ask for official support for Devuan, just for making it easier to install on Devuan - without hurting support for other distributions.
