### ISSUE TITLE
Does nvidia-docker use GPU depending on specific docker image like nvidia/cuda

### ISSUE THREAD

**Issue by Cherishty** [NVIDIA/nvidia-docker#852]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
Does nvidia-docker use GPU via specific docker image like nvidia/cuda

### 2. Steps to reproduce the issue
When installing nvidia for docker step by step, I finally realize that it relies on **nvidia/cuda** as (based) docker image which provides basic runtime environment,  do I get the right point?
That is to say, if I build a tensorflow-gpu docker image without nvidia/cuda, for example, based on centos, then it means I can **NOT** run my tensorflow module in container?

**Comment by flx42** [comment]
>  That is to say, if I build a tensorflow-gpu docker image without nvidia/cuda, for example, based on centos, then it means I can NOT run my tensorflow module in container?

Sure you can, you just need to set environment variables:
https://github.com/nvidia/nvidia-container-runtime#environment-variables-oci-spec
Here's how we do it in our official CUDA 10.0 Dockerfile based on CentOS 7: https://gitlab.com/nvidia/cuda/blob/centos7/10.0/base/Dockerfile#L22-25
