### ISSUE TITLE
The second command for Debian does not work

### ISSUE THREAD

**Issue by jgalaz84** [NVIDIA/nvidia-docker#853]
$ sudo apt-key add -distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
gpg: conflicting commands

**Comment by 3XX0** [comment]
The command is correct, you just didn't copy it right

```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -

distribution=$(. /etc/os-release;echo $ID$VERSION_ID)

curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update
```

**Comment by jgalaz84** [comment]
Hi Jonathan,
Yes, I quickly realized that somehow the copy/paste hadn't worked properly
(didn't find a way to delete my comment, though! Sorry, my bad).
Thanks!

-----------------------
Jesus G. Galaz-Montoya, Ph.D.
jgalaz@gmail.com, jgalaz@stanford.edu
Chiu Lab, NCMI
Department of Bioengineering
SLAC National Accelerator Laboratory
Stanford University
Stanford, CA 94305, USA
