### ISSUE TITLE
unsupported version on ubuntu studio 18.04.1 LTS

### ISSUE THREAD

**Issue by carlozousa** [NVIDIA/nvidia-docker#855]
Hello,

I have a fresh install and docker is working fine. Since I have a nvidia quadro p400 I would like to use the GPU for additional processing on the containers.

Any ideas?

Thanks

Carlos

curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
>   sudo tee /etc/apt/sources.list.d/nvidia-docker.list
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker

**Comment by ytooyama** [comment]
I have not been able to reproduce this issue.

Add cuda-repo and install the cuda-driver package.

* https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-the-nvidia-driver

And Install the nvidia-docker2,nvidia-container-runtime packages.

```
$ apt-cache madison docker.io
 docker.io | 17.12.1-0ubuntu1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
$ apt-cache madison nvidia-docker2 nvidia-container-runtime|grep docker17.12.1
nvidia-docker2 | 2.0.3+docker17.12.1-1 | https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  Packages
nvidia-container-runtime | 2.0.0+docker17.12.1-1 | https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  Packages
$ sudo apt-get install -y nvidia-docker2=2.0.3+docker17.12.1-1 nvidia-container-runtime=2.0.0+docker17.12.1-1

$ sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:03:00.0 Off |                  N/A |
| 26%   35C    P0    39W / 180W |      0MiB /  8119MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by larroy** [comment]
I used p3.16xlarge on us-west-2 with AMI: ami-0cfe27c75afee11df

root@ip-172-31-17-200:/home/piotr# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
root@ip-172-31-17-200:/home/piotr# curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker

root@ip-172-31-17-200:/home/piotr# echo $distribution
ubuntu18.10

**Comment by RenaudWasTaken** [comment]
Hello!

What is the distribution you are trying to install nvidia-docker on?

**Comment by carlozousa** [comment]
ubuntu studio 18.04.1 lts ...

A sex, 23/11/2018, 20:54, Renaud Gaubert <notifications@github.com>
escreveu:

**Comment by RenaudWasTaken** [comment]
Are you still reproducing that bug?

On an aws Ubuntu 18.04 that command is successful.

**Comment by RenaudWasTaken** [comment]
Closing as no further comment from the user was given.
Feel free to reopen if you have the information given by the following command: `cat . /etc/os-release`

**Comment by havetc** [comment]
I had the same problem with ubuntu 16.04. It think the problem may be the README not being clear enough about the installation command. I tried to copy & paste the whole instruction block "add the package repositories" and I had the same error, but when I copied the command separately it worked.

**Comment by Omer95** [comment]
in  `curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \` just replace $distribution with your distro ID and VERSION_ID which you can get from the command  `cat /etc/os-release` for example ubuntu18.04
