### ISSUE TITLE
Error response from daemon: OCI runtime create failed:

### ISSUE THREAD

**Issue by sebo313** [NVIDIA/nvidia-docker#858]
### 1. Issue or feature description
I installed nvidia-docker on my server and when trying to test the installation with the command  `sudo nvidia-docker run --rm nvidia/cuda nvidia-smi` , i get following error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.

Any idea on how to solve this issue?

### 2. Steps to reproduce the issue
`command: sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
`
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Kernel version from `uname -a`
Linux System-Product-Name 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Mon Nov 12 16:15:22 2018
Driver Version                      : 384.130

Attached GPUs                       : 2
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1070
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-b1d715d4-1640-9424-a7c6-de252f50887f
    Minor Number                    : 0
    VBIOS Version                   : 86.04.50.00.72
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B8110DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x61733842
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 8x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : 0 %
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 8112 MiB
        Used                        : 0 MiB
        Free                        : 8112 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 2 MiB
        Free                        : 254 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 44 C
        GPU Shutdown Temp           : 99 C
        GPU Slowdown Temp           : 96 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 31.37 W
        Power Limit                 : 151.00 W
        Default Power Limit         : 151.00 W
        Enforced Power Limit        : 151.00 W
        Min Power Limit             : 75.00 W
        Max Power Limit             : 170.00 W
    Clocks
        Graphics                    : 1594 MHz
        SM                          : 1594 MHz
        Memory                      : 4006 MHz
        Video                       : 1442 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1999 MHz
        SM                          : 1999 MHz
        Memory                      : 4004 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : None

GPU 00000000:02:00.0
    Product Name                    : GeForce GTX 1070
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-3f984f95-fe5f-d3ee-2e43-dd4b95bae20e
    Minor Number                    : 1
    VBIOS Version                   : 86.04.50.40.0A
    MultiGPU Board                  : No
    Board ID                        : 0x200
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x02
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B8110DE
        Bus Id                      : 00000000:02:00.0
        Sub System Id               : 0x33011462
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 2
            Link Width
                Max                 : 16x
                Current             : 8x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : 0 %
    Performance State               : P5
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 8114 MiB
        Used                        : 0 MiB
        Free                        : 8114 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 2 MiB
        Free                        : 254 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 2 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 48 C
        GPU Shutdown Temp           : 99 C
        GPU Slowdown Temp           : 96 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 10.90 W
        Power Limit                 : 151.00 W
        Default Power Limit         : 151.00 W
        Enforced Power Limit        : 151.00 W
        Min Power Limit             : 75.00 W
        Max Power Limit             : 170.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 810 MHz
        Video                       : 569 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1936 MHz
        SM                          : 1936 MHz
        Memory                      : 4004 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : None

 - [ ] Docker version from `docker version`
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-===============================================
un  libnvidia-container-t <none>          <none>          (no description available)
hi  nvidia-384            384.130-0ubuntu amd64           NVIDIA binary driver - version 384.130
un  nvidia-common         <none>          <none>          (no description available)
un  nvidia-container-runt <none>          <none>          (no description available)
rc  nvidia-container-runt 1.4.0-1         amd64           NVIDIA container runtime hook
ii  nvidia-cuda-dev       7.5.18-0ubuntu1 amd64           NVIDIA CUDA development files
ii  nvidia-cuda-doc       7.5.18-0ubuntu1 all             NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb       7.5.18-0ubuntu1 amd64           NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit   7.5.18-0ubuntu1 amd64           NVIDIA CUDA development toolkit
ii  nvidia-docker         1.0.1-1         amd64           NVIDIA Docker container tools
rc  nvidia-docker2        2.0.3+docker18. all             nvidia-docker CLI wrapper
un  nvidia-driver         <none>          <none>          (no description available)
un  nvidia-driver-binary  <none>          <none>          (no description available)
un  nvidia-legacy-340xx-v <none>          <none>          (no description available)
un  nvidia-libopencl1     <none>          <none>          (no description available)
un  nvidia-libopencl1-384 <none>          <none>          (no description available)
un  nvidia-libopencl1-dev <none>          <none>          (no description available)
ii  nvidia-modprobe       410.72-0ubuntu1 amd64           Load the NVIDIA kernel driver and create device
ii  nvidia-opencl-dev:amd 7.5.18-0ubuntu1 amd64           NVIDIA OpenCL development files
un  nvidia-opencl-icd     <none>          <none>          (no description available)
ii  nvidia-opencl-icd-384 384.130-0ubuntu amd64           NVIDIA OpenCL ICD
un  nvidia-persistenced   <none>          <none>          (no description available)
ii  nvidia-prime          0.8.2           amd64           Tools to enable NVIDIA's Prime
ii  nvidia-profiler       7.5.18-0ubuntu1 amd64           NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings       410.48-0ubuntu1 amd64           Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binar <none>          <none>          (no description available)
un  nvidia-smi            <none>          <none>          (no description available)
un  nvidia-vdpau-driver   <none>          <none>          (no description available)
ii  nvidia-visual-profile 7.5.18-0ubuntu1 amd64           NVIDIA Visual Profiler for CUDA and OpenCL

**Comment by mvish7** [comment]
Hello,
Did you manage to solve this issue? If yes can you please share the solution?
