### ISSUE TITLE
Install to /usr/local by default

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/nvidia-docker#86]
> At the root directory of the repository issue make to build the binaries or alternatively make install. The later will also take care of installing the binaries at the location set by the environment variable PREFIX(/usr/bin by default).

Usually, PREFIX defaults to `/usr/local` and you can override it with `PREFIX=/usr` if you're sure you know what you're doing.

https://www.freebsd.org/doc/en/books/porters-handbook/porting-prefix.html

Is there any reason not to set a similar default for `nvidia-docker`?

**Comment by 3XX0** [comment]
`/usr/local` in the BSD world is really different from the Linux one.
But yes, I was planning to change it for the `make install` path, however right now the `PREFIX` environment variable is shared with the packaging scripts as well.

**Comment by lukeyeager** [comment]
Ok BSD was a bad example. Here's a better one:

> The default value of prefix should be /usr/local
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

Clearly not a big issue. Just thought it was strange and wanted to point it out.
