### ISSUE TITLE
 docker: Error response from daemon  unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown. 

### ISSUE THREAD

**Issue by Wutever** [NVIDIA/nvidia-docker#861]
---

### 1. Issue or feature description

I run the command `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
`

### 2. Steps to reproduce the issue
hit enter
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=3088 /var/lib/docker/overlay2/681b52ecc456f043441a3ea22321c4b3842a182ec7ab15b094a24e614eb481c2/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.
`

**Comment by asolano** [comment]
Hi,

I was getting the same error on an older GTX 1070 card. 
Have you tried using a previous tag, like `nvidia/cuda:9.0-runtime` instead?

Best,

Alfredo

**Comment by Wutever** [comment]
> Hi,
> 
> I was getting the same error on an older GTX 1070 card.
> Have you tried using a previous tag, like `nvidia/cuda:9.0-runtime` instead?
> 
> Best,
> 
> Alfredo

Hi, I am using GTX1080, will it also cause problem?

**Comment by RenaudWasTaken** [comment]
Hello!

Cuda 10 has some driver and brand requirements, as highlighted by this table:
https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements

It seems here that you don't have the correct driver. You should either:
- Run cuda-9.0-runtime as suggested above
- Upgrade your driver
