### ISSUE TITLE
how can i install nvidia-docker with cuda9.0?

### ISSUE THREAD

**Issue by ds-gong** [NVIDIA/nvidia-docker#863]
now i already install nvidia-docker:

zyserver01@gds:~$ docker -v
Docker version 18.09.0, build 4d60db4

i creat a container,but cuda version is 10.0,such as:

root@9832218fc1e4:/# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

because i want to use cuda 9.0 vsersion, how can i install nvidia-docker with cuda-9.0 ?

**Comment by zocker-160** [comment]
does this work for you?
``` $ docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi```

**Comment by ds-gong** [comment]
it work normal.
![default](https://user-images.githubusercontent.com/39584112/48667847-aaade400-eb1a-11e8-8171-aa6772e9bc3d.png)

**Comment by ds-gong** [comment]
it seems no install cuda9.0,but find cuda dir,such as ：
![default](https://user-images.githubusercontent.com/39584112/48667877-928a9480-eb1b-11e8-9cbe-b2f883c9494a.png)

**Comment by RenaudWasTaken** [comment]
Hello!

Please follow the installation guide: https://github.com/NVIDIA/nvidia-docker#quickstart

**Comment by ds-gong** [comment]
@RenaudWasTaken 
hello! i already run a container,such as：
![default](https://user-images.githubusercontent.com/39584112/48670081-7b17cf80-eb4c-11e8-9c2e-bde2cda58505.png)

image nvidia/cuda:9.0-base size is 134M,but latest image have 2.24GB and nvcc -V can work,so I feel no install cuda9.0～
i use image nvidia/cuda:9.0-base run a container,but can't find nvcc -V,..
can you tell me how should i do？thanks～

**Comment by AssassinCrow** [comment]
> Hello!
> 
> For nvidia-docker, please follow the installation guide: https://github.com/NVIDIA/nvidia-docker#quickstart
> To use CUDA 9.0 please run a container as mentioned by @ds-gong :
> `$ docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`

Thank you, thank you so much. You saved me. I really really appreciate your great and simple trouble shoot :)
