### ISSUE TITLE
Provide some documentation verbiate for ubuntu-derivative 

### ISSUE THREAD

**Issue by tin6150** [NVIDIA/nvidia-docker#866]
### 1. Issue or feature description

Can you please add some info so that folks with Ubuntu derivative distro can at least give the ubuntu instruction a try?  
I have a "linuxmint18.3" and another running Zorin OS.  I have tried to decipher what the ubuntu1404 string might be but no luck.  I can't get beyond the step of
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list

Thanks!
Tin

**Comment by RenaudWasTaken** [comment]
Linux Mint is not supported, if you wish to install nvidia-docker on it, you will need to register the ubuntu 18.04 repositories manually: https://github.com/NVIDIA/nvidia-docker/issues/848#issuecomment-434801801

You can see the list of distros either on the main page or on the gh-pages branch: https://github.com/NVIDIA/nvidia-docker/tree/gh-pages
