### ISSUE TITLE
Nvidia Docker - MPS on all GPUs (Nvidia-DGX1)

### ISSUE THREAD

**Issue by menewol** [NVIDIA/nvidia-docker#868]
Hi,

We are currently trying to setup the NVIDIA MPS (EXPERIMENTAL) example and get it to run on all 8  GPUs but are running into some issues.
At first we had problems with the IPC in the docker-compose, because the nbody examples were not able to join the ipc of the docker daemon. This was resolve by using ipc: host.

NVIDIA_VISIBLE_DEVICES=all is set and the nvidia-cuda-mps-control daemon is started. When we start the examples wit docker-compose up, the mps-server starts on all GPUs independetly and also the mps-daemon is reporting, that all GPUs are available.
But the nbody only runs on GPU0 and won't scale to other GPUs, as we expected. (CUDA_ACTIVE_THREAD_PERCENTAGE was set to several values but neither made a change)

We also tried running multiple to exceed the memory limit of a sinigle GPU, to get the MPS-Daemon to schedule further containers onto different GPUs, but ended up using only a single GPU.

Output of nvidia-smi:

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     45865      C   nvidia-cuda-mps-server                       418MiB |
|    0     51818    M+C   ./nbody                                      438MiB |
|    0     51882    M+C   ./nbody                                      438MiB |
|    0     51898    M+C   ./nbody                                      438MiB |
|    1     45865      C   nvidia-cuda-mps-server                       418MiB |
|    2     45865      C   nvidia-cuda-mps-server                       418MiB |
|    3     45865      C   nvidia-cuda-mps-server                       418MiB |
|    4     45865      C   nvidia-cuda-mps-server                       418MiB |
|    5     45865      C   nvidia-cuda-mps-server                       418MiB |
|    6     45865      C   nvidia-cuda-mps-server                       418MiB |
|    7     45865      C   nvidia-cuda-mps-server                       418MiB |
+-----------------------------------------------------------------------------+

Output of /var/log/nvidia-mps/control.log 
 Accepting connection...
NEW UI
UI closed
Accepting connection...
User did not send valid credentials
Accepting connection...
NEW CLIENT 51818 from user 0: Server already exists
Accepting connection...
User did not send valid credentials
Accepting connection...
NEW CLIENT 51882 from user 0: Server already exists
Accepting connection...
User did not send valid credentials
Accepting connection...
NEW CLIENT 51898 from user 0: Server already exists
Accepting connection...
NEW CLIENT 51818 from user 0: Server already exists
Accepting connection...
NEW CLIENT 51882 from user 0: Server already exists
Accepting connection...
NEW CLIENT 51898 from user 0: Server already exists

<details>
 <summary>Click here to see debug information></summary>
 - [ 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux] Kernel version from `uname -a`
 - [ doesnt show any useful GPU information besides GPUBoardSerialNumber/PCI_BUS_ID ] Any relevant kernel output lines from `dmesg`
 - [384.145] Driver information from `nvidia-smi -a` See attached for GPU0 => [1]
 - [ 18.03.1-ce ] Docker version from `docker version` [2]
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'` [3]
 - [ 1.0.0 ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used => using the MPS-nbody Sample delivered with https://gitlab.com/nvidia/samples/tree/master/mps

[1]==============NVSMI LOG==============

Timestamp                           : Thu Nov 22 12:23:04 2018
Driver Version                      : 384.145

Attached GPUs                       : 8
GPU 00000000:06:00.0
    Product Name                    : Tesla V100-SXM2-16GB
    Product Brand                   : Tesla
    Display Mode                    : Enabled
    Display Active                  : Disabled
    Persistence Mode                : Enabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0324917174879
    GPU UUID                        : GPU-86e60957-0cc5-7959-855b-28f0d7bac243
    Minor Number                    : 0
    VBIOS Version                   : 88.00.18.00.01
    MultiGPU Board                  : No
    Board ID                        : 0x600
    GPU Part Number                 : 692-2G503-0202-000
    Inforom Version
        Image Version               : G503.0202.00.01
        OEM Object                  : 1.1
        ECC Object                  : 5.0
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x06
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1DB110DE
        Bus Id                      : 00000000:06:00.0
        Sub System Id               : 0x121210DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 961000 KB/s
        Rx Throughput               : 7654000 KB/s
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 16152 MiB
        Used                        : 1742 MiB
        Free                        : 14410 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 18 MiB
        Free                        : 16366 MiB
    Compute Mode                    : Exclusive_Process
    Utilization
        Gpu                         : 100 %
        Memory                      : 1 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : Enabled
        Pending                     : Enabled
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : 0
            Double Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : 0
                Total               : 0
        Aggregate
            Single Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : 0
            Double Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : 0
                Total               : 0
    Retired Pages
        Single Bit ECC              : 0
        Double Bit ECC              : 0
        Pending                     : No
    Temperature
        GPU Current Temp            : 67 C
        GPU Shutdown Temp           : 90 C
        GPU Slowdown Temp           : 87 C
        GPU Max Operating Temp      : 83 C
        Memory Current Temp         : 60 C
        Memory Max Operating Temp   : 85 C
    Power Readings
        Power Management            : Supported
        Power Draw                  : 296.43 W
        Power Limit                 : 300.00 W
        Default Power Limit         : 300.00 W
        Enforced Power Limit        : 300.00 W
        Min Power Limit             : 100.00 W
        Max Power Limit             : 300.00 W
    Clocks
        Graphics                    : 1507 MHz
        SM                          : 1507 MHz
        Memory                      : 877 MHz
        Video                       : 1350 MHz
    Applications Clocks
        Graphics                    : 1312 MHz
        Memory                      : 877 MHz
    Default Applications Clocks
        Graphics                    : 1312 MHz
        Memory                      : 877 MHz
    Max Clocks
        Graphics                    : 1530 MHz
        SM                          : 1530 MHz
        Memory                      : 877 MHz
        Video                       : 1372 MHz
    Max Customer Boost Clocks
        Graphics                    : 1530 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 45865
            Type                    : C
            Name                    : nvidia-cuda-mps-server
            Used GPU Memory         : 418 MiB
        Process ID                  : 51818
            Type                    : M+C
            Name                    : ./nbody
            Used GPU Memory         : 438 MiB
        Process ID                  : 51882
            Type                    : M+C
            Name                    : ./nbody
            Used GPU Memory         : 438 MiB
        Process ID                  : 51898
            Type                    : M+C
            Name                    : ./nbody
            Used GPU Memory         : 438 MiB

[2]
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

[3]  https://imgur.com/a/A8oo8fb
</details>

**Comment by menewol** [comment]
Can anyone confirm that she/he, at least, read this issue?

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the delayed answer, a few notes:
> At first we had problems with the IPC in the docker-compose, because the nbody examples were not able to join the ipc of the docker daemon. This was resolve by using ipc: host.

Do you mind pasting the logs / errors? I am not seeing this error ans I suspect your mps-daemon container is not starting which is why they can't join the ipc.
You shouldn't be running on the host.

> NVIDIA_VISIBLE_DEVICES=all is set and the nvidia-cuda-mps-control daemon is started. When we start the examples wit docker-compose up, the mps-server starts on all GPUs independetly and also the mps-daemon is reporting, that all GPUs are available.
> But the nbody only runs on GPU0 and won't scale to other GPUs, as we expected. (CUDA_ACTIVE_THREAD_PERCENTAGE was set to several values but neither made a change)

This is because by default the nbody sample will only run on one GPU, you will need to also set the command line parameters (in mps/cuda-samples) to `CMD ["./nbody", "-benchmark", "-i=10000", "-numdevices=8"]`

Closing for now, feel free to reopen if you still have issues with the IPC :)!

**Comment by kkurni** [comment]
@RenaudWasTaken do you use AWS ECS to launch your container?

I have a problem running this docker container with ipc: host inside the ECS container.

It works if I run it manually with docker run --ipc=Host
