### ISSUE TITLE
Dockerfile of nvidia/mps is 404

### ISSUE THREAD

**Issue by CodeJuan** [NVIDIA/nvidia-docker#869]
### 1. Issue or feature description
I'm a new user of MPS, I try to get the details info of image [nvidia/mps](https://hub.docker.com/r/nvidia/mps/).
But the link of Dockerfile https://github.com/NVIDIA/mps/blob/master/Dockerfile  is 404.
I was wondering if I could get the available link of nvidia/mps?
Thank you.

**Comment by RenaudWasTaken** [comment]
Hello!

Thanks for reporting this!
I've updated the link, alternatively you have some more documentation here: https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL)

**Comment by CodeJuan** [comment]
> Hello!
> 
> Thanks for reporting this!
> I've updated the link, alternatively you have some more documentation here: https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL)

Thanks for your replying.
The new link of Dockerfile is https://gitlab.com/nvidia/samples/blob/master/mps/cuda-samples/Dockerfile is available, it's CMD is `CMD ["./nbody", "-benchmark", "-i=10000"]`. 
But as described by pod diagram, the CMD or Entrypoing of MPS container is `nvidia-cuda-mps-server -f`.

![image](https://user-images.githubusercontent.com/5423628/49068713-67621c80-f262-11e8-9ea2-09896d240496.png)

So I'm a little puzzle of this.

**Comment by flx42** [comment]
https://gitlab.com/nvidia/mps/blob/master/Dockerfile
