### ISSUE TITLE
Conflict: volume name must be unique

### ISSUE THREAD

**Issue by kbokh** [NVIDIA/nvidia-docker#87]
When using the next command:
```docker run -ti `curl -s http://localhost:3476/v1.0/docker/cli?dev=0+1\&vol=nvidia_driver` cuda```
the next message is presented:
`docker: Error response from daemon: create nvidia_driver_352.79: conflict: volume name must be unique`

The docker endpoint (curl -s http://localhost:3476/v1.0/docker/cli?dev=0+1\&vol=nvidia_driver) output the next:
 `--device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0 --device=/dev/nvidia1 --volume-driver=nvidia-docker --volume=nvidia_driver_352.79:/usr/local/nvidia:ro`

**Comment by 3XX0** [comment]
What's the output of `docker volume ls` ?
Also did you try restarting Docker `sudo restart docker`?

**Comment by 3XX0** [comment]
Any update?

**Comment by kbokh** [comment]
OS: CentOS7
Docker version 1.11.1, build 5604cbe
Cuda: 352.93

Output of docker volume ls:
`DRIVER              VOLUME NAME
local               nvidia_driver_352.93`

Output of curl -s http://localhost:3476/v1.0/docker/cli?dev=0+1\&vol=nvidia_driver:
`--device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0 --device=/dev/nvidia1 --volume-driver=nvidia-docker --volume=nvidia_driver_352.93:/usr/local/nvidia:ro`

Output of docker run -ti `curl -s http://localhost:3476/v1.0/docker/cli?dev=0+1\&vol=nvidia_driver` cudnn:
`docker: Error response from daemon: create nvidia_driver_352.93: conflict: volume name must be unique.`

**Comment by 3XX0** [comment]
Using the RestAPI relies on the `nvidia-docker-plugin`, you shouldn't mix both installation (standalone/plugin). You need to remove the volume created manually:

`nvidia-docker volume rm nvidia_driver_352.93`

**Comment by kbokh** [comment]
It works! Thank you. I'v faced problem with invalid cross-device link. I have /usr and /var on the different partitions. 
I fixed it by adding:
```Environment="VOL_DIR=/usr/local/nvidia-docker/volumes"```
and modifying the next row 
```ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR -v $VOL_DIR ```
in nvidia-docker.service
