### ISSUE TITLE
Minimum supported Docker version problem on Rhel 7

### ISSUE THREAD

**Issue by giraygokirmak** [NVIDIA/nvidia-docker#872]
Although it says:
"What is the minimum supported Docker version?
Docker 1.12 which adds support for custom container runtimes."
At the documentation, when we try to install on rhel 7 with docker-ee 1.13, nvidia-docker2 says that it requires at least 1.18 and won't install unless we install docker 1.18

**Comment by RenaudWasTaken** [comment]
Hello!

Note that the support story for docker-ee is "best effort".
It doesn't really make sense for us to support docker-ee as using a runtime that isn't the default one means you won't get support from docker.

You can still however use docker-ee and install the package `nvidia-container-runtime` (not `nvidia-docker2`), then you register the runtime manually:
https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup

The following command line *should* install the package:
```
> DOCKERVER=$(docker version --format '{{.Server.Version}}' | sed -r 's/-.*//')
> sudo yum install -y "nvidia-container-runtime-2.0.0-1.docker$DOCKERVER.x86_64"
```
