### ISSUE TITLE
nvidia-docker has no installation candidate on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by aleksejs-fomins** [NVIDIA/nvidia-docker#874]
I installed docker-ce following the instructions on the [official](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1) website. Then I added the [nvidia repositories](https://nvidia.github.io/nvidia-docker/). Attempts to install nvidia-docker result in

```
alfomi@HIFOLNXWSH52-01:~$ sudo apt-get install nvidia-docker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nvidia-docker is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nvidia-docker2

E: Package 'nvidia-docker' has no installation candidate
```
Unfortunately, I require the 1st version of the docker, as it is a pre-requisite for another software

```
$ uname -a
Linux HIFOLNXWSH52-01 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by RenaudWasTaken** [comment]
Hello!

This is outside the support path and you should really ask the maintainers of your software to depend on nvidia-docker2.

That being said there are two possible solutions:
- Use the ubuntu16.04 packages (`curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu16.04/nvidia-docker.list |  sudo tee /etc/apt/sources.list.d/nvidia-docker.list`
- Build from source

**Comment by RenaudWasTaken** [comment]
Feel Free to reopen if you have any issues with the above
