### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by anamf** [NVIDIA/nvidia-docker#875]
### 1. Issue or feature description

I get an "executable file not found in $PATH" error when trying to run nvidia/cuda image with docker. 

### 2. Steps to reproduce the issue

Docker 17.03.2.ce installed as a module on HPC
package nvidia-docker2-2.0.3-1.docker17.03.2.ce.noarch installed using rpm with --nodeps option
GPU  Driver Version: 390.67

These are the commands I have tried:
```
$ docker run --runtime=nvidia --rm nvidia/cuda:9.1-devel nvidia-smi
exec: "nvidia-container-runtime-hook": executable file not found in $PATH
docker: Error response from daemon: oci runtime error: exec: "nvidia-container-runtime-hook": executable file not found in $PATH.
ERRO[0000] error getting events from daemon: context canceled


$ docker run --rm nvidia/cuda:9.0-base nvidia-smi
container_linux.go:247: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: context canceled
```
Can you please point me to the right direction? Is nvidia-docker2 properly installed?
```
$ systemctl status nvidia-docker
● nvidia-docker.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

Thanks,
Ana

**Comment by RenaudWasTaken** [comment]
Hello!

It looks like your installation of the nvidia-docker2 packages isn't correct. What steps did you follow?
What is the output of `yum list installed | grep nvidia`

Thanks!

**Comment by RenaudWasTaken** [comment]
Reading this a bit more it seems like you installed with the `--nodeps` option. This looks like it prevented the nvidia packages from being installed incorrectly.

**Comment by anamf** [comment]
Thanks @RenaudWasTaken, could be that, do you know if there are any instructions on how to install nvidia-docker2 from the source code?

**Comment by RenaudWasTaken** [comment]
Hello!

What's preventing you from installing the rpm packages correctly?

**Comment by anamf** [comment]
My docker installation is not the traditional rpm package, I use it as a module on the HPC (module load docker), so nvidia-docker says there is a missing dependency. That is why I tried to install nvidia-docker2 using rpm and the --nodeps option.

I have also tried to install docker directly (using yum), but I believe my CentOS version is rather old (7.2) and I am struggling to get the right dependencies. 

So that is why I was thinking it might be worth taking a look at the installation of nvidia-docker2 from sources?

**Comment by RenaudWasTaken** [comment]
Hello!

You are a bit outside the supported path here, the best you can do here is to track down all the dependencies of the packages and install them one by one.

Below is a succinct summary of nvidia-docker packages dependency. Note that not all base (i.e: core utils packages) dependencies are shown.
![out](https://user-images.githubusercontent.com/2519571/50231160-6d08d900-03ae-11e9-9a05-245b7a6b38e7.jpg)
