### ISSUE TITLE
File has Unexpected Size on Ubuntu 18.04

### ISSUE THREAD

**Issue by csrwl** [NVIDIA/nvidia-docker#877]
**After following the code below on Ubuntu 18.04,**

curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

**The following error message shows up**

Err:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
  File has unexpected size (40587 != 33901). Mirror sync in progress? [IP: 183.214.10.142 443]
  Hashes of expected file:
   - Filesize:33901 [weak]
   - SHA256:ada3b63d8229648317922f810461ea11d03effd07289d966f03962b131e50956
   - SHA1:8c65897f47b0249cc1eef8acd8f3c5f014480c03 [weak]
   - MD5Sum:c051aac1e991199d4868714dfeb5017e [weak]
  Release file created at: Tue, 23 Oct 2018 18:29:19 +0000
Fetched 1365 B in 3s (400 B/s)
Reading package lists... Done
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (40587 != 33901). Mirror sync in progress? [IP: 183.214.10.142 443]
   Hashes of expected file:
    - Filesize:33901 [weak]
    - SHA256:ada3b63d8229648317922f810461ea11d03effd07289d966f03962b131e50956
    - SHA1:8c65897f47b0249cc1eef8acd8f3c5f014480c03 [weak]
    - MD5Sum:c051aac1e991199d4868714dfeb5017e [weak]
   Release file created at: Tue, 23 Oct 2018 18:29:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**The result of wget https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/Release is:**

Origin: NVIDIA
Label: NVIDIA CUDA
Architecture: x86_64
Date: Tue, 06 Nov 2018 23:45:57 +0000
MD5Sum:
 6d39c0ebacbe177afdc4764164cd2747            12741 Packages
 fca3449155ce97b5696260198d36b830             3879 Packages.gz
SHA1:
 e6b58bcda7c4e8a7274419bf38e8c25eddffa885            12741 Packages
 6f5c45c230728b52a17a3593b16899f5cc3df493             3879 Packages.gz
SHA256:
 2fcf5efb29233137c034b2e5e1655ab8189bd5795d5ba0142aab6e349d581f50            12741 Packages
 471541e85b0ff722eb4562f4668cbd1d034f3e6ed85bf00c0685dd5d587a1530             3879 Packages.gz

**Additional Info**
Driver Version: 415.18
CUDA Version: 10.0
Docker:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Many thanks for your help!

**Comment by RenaudWasTaken** [comment]
Hello!

This looks like a CUDA package bug (separate from this repository). I'll try to followup internally.
Thanks for signaling this, I'll get back to this when I have more information.

**Comment by csrwl** [comment]
Appreciate your help!

**Comment by RenaudWasTaken** [comment]
Hello!

Are you still seeing this error?
If so I suggest you remove that repository from your apt sources, clear your apt cache and update before adding it back :)

Feel free to reopen if you see that issue again!

**Comment by rjeli** [comment]
Getting this when I `apt-get update` in `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`. Worked perfectly yesterday. Should I just wait for the "mirror sync" to complete..?

**Comment by leonmax** [comment]
We have the same problem and break out CI at the moment

**Comment by dharampal123** [comment]
sudo apt-get clean
sudo apt-get update

Works for me !!

**Comment by ReyRen** [comment]
> sudo apt-get clean
> sudo apt-get update
> 
> Works for me !!

It is, the weird thing is I use `apt-get` rather than `apt` to get work

**Comment by azuryl** [comment]
> Getting this when I `apt-get update` in `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`. Worked perfectly yesterday. Should I just wait for the "mirror sync" to complete..?
cuda 11.1 can not work

**Comment by elezar** [comment]
Please see the link from https://github.com/NVIDIA/nvidia-docker/issues/1009#issuecomment-1083945079

Note that this may be due to a CDN issue with the CUDA downloads repositories and are not specific to NVIDIA docker. Closing this issue.

**Comment by elezar** [comment]
> > Getting this when I `apt-get update` in `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`. Worked perfectly yesterday. Should I just wait for the "mirror sync" to complete..?
> > cuda 11.1 can not work

@azuryl Please see the link from https://github.com/NVIDIA/nvidia-docker/issues/1009#issuecomment-1083945079

Note that this may be due to a CDN issue with the CUDA downloads repositories and are not specific to NVIDIA docker. Closing this issue.
