### ISSUE TITLE
Wiki page install nvidia-docker2 in Ubuntu have ambiguous instruction

### ISSUE THREAD

**Issue by giranntu** [NVIDIA/nvidia-docker#879]
> Installing version 2.0
> Make sure you have installed the NVIDIA driver and a supported version of Docker for your distribution (see prerequisites).
> 
> If you have a custom /etc/docker/daemon.json, the nvidia-docker2 package might override it.
> 
> Ubuntu distributions
> Install the repository for your distribution by following the instructions here.
> Install the nvidia-docker2 package and reload the Docker daemon configuration:

When we go to the link in step1 instruction link.
There is no Ubuntu installation script there. 
So I think it might be helpful to add the script to install in distribution Ubuntu.

Thanks!

**Comment by guptaNswati** [comment]
Which script are you referring to? 

For Ubuntu, these are installation instructions:

**1. Add Repository**
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

**2. Install the package**
sudo apt-get install nvidia-docker2
sudo pkill -SIGHUP dockerd

**Comment by RenaudWasTaken** [comment]
Closing as there are some manual steps to follow that can't really be automated
