### ISSUE TITLE
Is it possible to run Nvidia v2 Docker container in a Docker container?

### ISSUE THREAD

**Issue by tangzhankun** [NVIDIA/nvidia-docker#882]
**Is it possible to run Nvidia Docker v2 in a Docker container?**
I have a server with two GPU cards but that server's OS environment is not recommended to change (it has the driver installed). So I'm thinking to start a container with GPU devices mounted and run Nvidia Docker v2 containers in it.

**Comment by RenaudWasTaken** [comment]
Hello!

This is an untested path, and you will hit a number of issues related to docker in docker. I wouldn't recommend running nvidia-docker in a docker container :)
