### ISSUE TITLE
Bad interpreter error with nvidia-docker2

### ISSUE THREAD

**Issue by djglowny** [NVIDIA/nvidia-docker#883]
I am currently attempting to install and test nvidia-docker on a Fedora 29 system, and I have followed the suggested install process for Fedora by using the following commands:
```
curl -s -L https://nvidia.github.io/nvidia-docker/centos7/nvidia-docker.repo | \
  sudo tee /etc/yum.repos.d/nvidia-docker.repo
sudo dnf install nvidia-docker2
sudo pkill -SIGHUP dockerd
```
However, I have come across the following error output when running the `nvidia-docker` command after install:
```
/usr/bin/nvidia-docker: /usr/bin/docker: /bin/sh: bad interpreter: Permission denied
/usr/bin/nvidia-docker: line 34: /usr/bin/docker: Success
```

**Comment by fsmenyao** [comment]
I have the same problem as you when I use following command:
`docker --runtime=nvidia run --rm ufoym/deepo nvidia-smi`
Then I use the following commands instead of that one:
`docker run --runtime=nvidia --rm ufoym/deepo nvidia-smi`
and it works.

**Comment by fsmenyao** [comment]
I have the same problem as you when I use following command:
docker --runtime=nvidia run --rm ufoym/deepo nvidia-smi
Then my elder brother LvJC told me to use the following commands instead of that one:
docker run --runtime=nvidia --rm ufoym/deepo nvidia-smi
and it works！

**Comment by fsmenyao** [comment]
I have the same problem as you when I use following command:
`docker --runtime=nvidia run --rm ufoym/deepo nvidia-smi`
Then my elder brother LvJC told me to use the following commands instead of that one:
`docker run --runtime=nvidia --rm ufoym/deepo nvidia-smi`
and it works！

**Comment by RenaudWasTaken** [comment]
Hello!

Looks like you figured out the issue here. You need to make sure that the options specified in your systemd file aren't repeated in your /etc/docker/daemon.json file (prefer the config file).

If you have any other question feel free to reopen!
Thanks!
