### ISSUE TITLE
isolating gpu using with NV_GPU and nvidia-docker makes the docker image not usable in different machines

### ISSUE THREAD

**Issue by ahmedtalbi** [NVIDIA/nvidia-docker#884]
### 1. Issue or feature description
Using the bellow command makes the docker image not usable when pulled in a different machine. 
the first machine has 3 GPUs (ids 0,1 and 2) and the second one has only 1

### 2. Steps to reproduce the issue
 **xhost + &&NV_GPU=2 nvidia-docker run --rm  -v /home:/var/log/training -it**

and I get the following error:

**docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=0,1,2 --compute --utility --require=cuda>=9.0 --pid=23863 /var/lib/docker/overlay2/dcf4bf3e196acbf5f13ea841313ee74091f0882eebc754a0a8444e9f69b7f825/merged]\\\\nnvidia-container-cli: device error: unknown device id: 1\\\\n\\\"\"": unknown.
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)**

I am using cuda-9-0 on both machines
same docker version 18.06.1-ce

I assumed that isolating the gpu is the problem, as the version with normal gpu access doesn't cause any issue.

**Comment by RenaudWasTaken** [comment]
Hello!

This is the expected behavior, when you set NV_GPU to the value 2, it means you want it to expose the 3rd device on your machine (it starts at 0).

So when you move from a machine with 3 GPUs to 1 GPU, this will fail as there isn't a 3rd device on your machine.
