### ISSUE TITLE
does nvidia-docker support Ubuntu 18.04.1 LTS?

### ISSUE THREAD

**Issue by Pallavi-code** [NVIDIA/nvidia-docker#891]
sudo apt-get update is failing after adding nivida-docker repos to sources.list. 

Version info:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Error:
 sudo apt-get update
Get:1 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  InRelease
Ign:1 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  InRelease
Get:2 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  InRelease
Ign:2 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  InRelease
Get:3 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  InRelease
Ign:3 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  InRelease
Get:4 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release [574 B]
Get:5 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release [574 B]
Get:6 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release [574 B]
Get:4 file:/var/nvinfer-runtime-trt-repo-3.0.4-ga-cuda9.0  Release [574 B]
Get:5 file:/var/nvinfer-runtime-trt-repo-4.0.1-ga-cuda9.0  Release [574 B]
Get:6 file:/var/nvinfer-runtime-trt-repo-5.0.0-rc-cuda9.0  Release [574 B]
Ign:8 http://ubuntu-cloud.archive.canonical.com/ubuntu bionic-updates/rocky InRelease
Ign:11 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Hit:12 http://ubuntu-cloud.archive.canonical.com/ubuntu bionic-updates/rocky Release
Hit:13 http://in.archive.ubuntu.com/ubuntu bionic InRelease
Hit:16 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release
Get:18 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Hit:19 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:22 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Err:9 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 165.225.104.34 80]
Err:15 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 165.225.104.34 80]
Err:20 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 165.225.104.34 80]
Fetched 158 kB in 1min 31s (1,742 B/s)
Reading package lists... Done
W: Failed to fetch http://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64/InRelease  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 165.225.104.34 80]
W: Failed to fetch http://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64/InRelease  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 165.225.104.34 80]
W: Failed to fetch http://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64/InRelease  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 165.225.104.34 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by RenaudWasTaken** [comment]
Hello!

It seems pretty likely that this is an issue on your side with your networking, as this seem to work with a fresh AWS instance.
You should make sure that you can curl pages like:
- https://github.com/NVIDIA/nvidia-docker
- http://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64/InRelease

If it fails, check that you have the correct packages like `apt-transport-https` and that you can resolve the github URLs.

Feel free to reop
