### ISSUE TITLE
solved - Error on "docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi"

### ISSUE THREAD

**Issue by fardok** [NVIDIA/nvidia-docker#893]
hi everyone!

i solved that error

docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi

error is because librarys dont connect to right place
there's two ways to fix that:

    docker run --runtime=nvidia --rm nvidia/cuda:9.0-base bash
    inside container write: ldconfig
    then for check that is all ok write nvidia-smi
    then in another console write: docker ps and find your container
    then save them to disk: docker commit c3f279d17e0a newname/newname:fixed
    instead of c3f279d17e0a write container id from docker ps
    thats all

    docker run --runtime=nvidia --rm nvidia/cuda:9.0-base ldconfig ;nvidia-smi ____________________________________________^^^^^^^^^^ ldconfig; nvidia-smi

thats all

**Comment by fardok** [comment]
i write that issue because i cant find any another solution in internet

**Comment by guptaNswati** [comment]
Can you please share some context about which error were you getting?

**Comment by RenaudWasTaken** [comment]
Hello!

Can you share some more context here? I usually close issues after around a month of inactivity.

**Comment by RenaudWasTaken** [comment]
Closing as no new activity.
