### ISSUE TITLE
Nvidia-docker 2.0 repository incompatible with latest docker CE release on CentOs7.6

### ISSUE THREAD

**Issue by coreyryanhanson** [NVIDIA/nvidia-docker#894]
### 1. Issue or feature description
I've been noticing dependency conflicts caused by NVIDIA docker when running software updates. It appears that the latest version supported is docker18.03.1, but the docker CE repo has introduced version docker18.09.

### 2. Steps to reproduce the issue
Use official repos for docker CE and NVIDIA docker on centos7.6 and run software update.

**Comment by RenaudWasTaken** [comment]
@coreyryanhanson was your issue fixed in #896 ?

**Comment by RenaudWasTaken** [comment]
closing as no new activity.
