### ISSUE TITLE
question about nvidia-driver

### ISSUE THREAD

**Issue by zlcnju** [NVIDIA/nvidia-docker#897]
**wiki** 
> The recommended way is to use your package manager and install the cuda-drivers package (or equivalent).

**Question 1**: As described in the wiki above [how-do-i-install-the-nvidia-driver](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-the-nvidia-driver), the cuda-driver should be installed. Can I work it out that the cuda-driver is another express way of nvidia-driver?  And does it mean that i don't need to install the complete cuda(ues yum instead cuda-driver instead of cuda)? Because the size of the make a big difference, it is important for me.

**Question 2**: I find the docker images install the cuda too, so i wonder does it make a conflict if i install the cuda 8.0 and use cuda 9.0 in the docker.

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the late reply.

> **Question 1**: As described in the wiki above [how-do-i-install-the-nvidia-driver](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-the-nvidia-driver), the cuda-driver should be installed. Can I work it out that the cuda-driver is another express way of nvidia-driver

No, you should install the driver and nvidia-docker

> **Question 2**: I find the docker images install the cuda too, so i wonder does it make a conflict if i install the cuda 8.0 and use cuda 9.0 in the docker.

NVIDIA Drivers are backwards compatible, meaning you can run any CUDA 8.0 image and CUDA 9.0 image if you have a driver that supports CUDA 9.0
