### ISSUE TITLE
Can't run docker cuda, with tesla P4 and 396.37

### ISSUE THREAD

**Issue by huyutuo** [NVIDIA/nvidia-docker#898]
when I run this 
docker run -it --rm --runtime nvidia nvidia/cuda nvidia-smi
it shows 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=54870 /var/lib/docker/overlay2/c8ed88df54e863e37fb131406d02f620e2a72d810813ac141246ee86683fbed9/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.

when i run this 
 docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
it shows
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.0 --pid=55812 /var/lib/docker/overlay2/4493971d67d5236d20b76c76e6762ad2782f6d76595574076067e1524c60fab8/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.

when i run this
docker run --runtime=nvidia --rm nvidia/cuda:9.2-devel nvidia-smi
it shows
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=9.2 --pid=42502 /var/lib/docker/overlay2/df36f0f68ceebc9498e9db3ae61647cc3cf727269b0c2d1dc03bfa81cf13dace/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.

my GPU and driver is 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:02:00.0 Off |                    0 |
| N/A   51C    P0    25W /  75W |   2483MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P4            Off  | 00000000:84:00.0 Off |                  N/A |
| N/A   30C    P8     6W /  75W |     10MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P4            Off  | 00000000:85:00.0 Off |                  N/A |
| N/A   30C    P8     6W /  75W |     10MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     33167      C   python                                      2473MiB |
+-----------------------------------------------------------------------------+

what i can't understand is 
because my GPU is tesla, my driver only in 384.130-385.0 can run nvidia/docker-10?
my GUP is tesla p4 , can i run nvidia/docker-9.2

**Comment by RenaudWasTaken** [comment]
It's most likely a problem with your driver installation.

You probably can't run a CUDA sample outside your container. I would suggest to reinstall your driver. 

Feel free to re-open if this doesn't fix your issue.
