### ISSUE TITLE
nvidia-docker not working correctly on machines where sudo is required to run docker

### ISSUE THREAD

**Issue by elezar** [NVIDIA/nvidia-docker#9]
On machines where sudo permissions are required for docker (see for exampel the discussion on```/etc/sudoers``` from http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/), the ```nvidia-docker``` script does not seem to work as expected.

I have tried the following:
1. Added ```alias docker='sudo /usr/bin/docker'``` to ```~/.bashrc```
2. Added ```alias docker='sudo /usr/bin/docker'``` to ```~/.profile```

But the alias not correctly propagated to ```nvidia-docker```.

Adding ```alias docker='sudo /usr/bin/docker'``` to the top of the ```nvidia-docker``` script directly allows for the script to work correctly in this setting.

Any pointers on how this could be addressed locally?

**Comment by 3XX0** [comment]
Aliases are not propagated through non-interactive shells hence your error.
What you can do instead is using sudo on the nvidia-docker script:
```alias docker='sudo nvidia-docker'```

**Comment by elezar** [comment]
The problem is that I have only been given sudo access (without password)
for running "/usr/bin/docker" on this particular machine. This means that I
cannot use an alias for nvidia-docker directly.

**Comment by 3XX0** [comment]
You should now be able to do: ```DOCKER='sudo docker' ./nvidia-docker``
