### ISSUE TITLE
nvidia-docker install failure because of packages unmet problem on Ubuntu 16.04 

### ISSUE THREAD

**Issue by Chinamebro** [NVIDIA/nvidia-docker#902]
The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.0~3-0~ubuntu-xenial) but 5:18.09.1~3-0~ubuntu-xenial is to be installed or docker-ee (= 5:18.09.0~3-0~ubuntu-xenial) but it is not installable
E: Unable to correct problems, you have held broken packages.

dpkg -l '*nvidia*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
un  nvidia-common                                 <none>                      <none>                      (no description available)
un  nvidia-legacy-340xx-vdpau-driver              <none>                      <none>                      (no description available)
un  nvidia-libopencl1-dev                         <none>                      <none>                      (no description available)
un  nvidia-prime                                  <none>                      <none>                      (no description available)
un  nvidia-vdpau-driver                           <none>                      <none>                      (no description available)

dpkg -l '*docker*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
un  docker                                        <none>                      <none>                      (no description available)
ii  docker-ce                                     5:18.09.1~3-0~ubuntu-xenial amd64                       Docker: the open-source application container engine
ii  docker-ce-cli                                 5:18.09.1~3-0~ubuntu-xenial amd64                       Docker CLI: the open-source application container engine
un  docker-engine                                 <none>                      <none>                      (no description available)
un  docker-engine-cs                              <none>                      <none>                      (no description available)
un  docker.io                                     <none>                      <none>                      (no description available)
un  lxc-docker                                    <none>                      <none>                      (no description available)
un  lxc-docker-virtual-package                    <none>                      <none>                      (no description available)

nvidia-smi
Thu Jan 10 01:51:35 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   38C    P8    20W / 215W |    285MiB /  7951MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1128      G   /usr/lib/xorg/Xorg                           166MiB |
|    0      2488      G   compiz                                       118MiB |
+-----------------------------------------------------------------------------+

**Comment by deano2point0** [comment]
Same issue here. Ubuntu 16.04.

**Comment by makslevental** [comment]
```
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt autoremove
sudo apt-get install docker-ce=5:18.09.0~3-0~ubuntu-bionic
```

**Comment by RenaudWasTaken** [comment]
Hello!

Docker release a new version, you can either downgrade to 18.09.0 or wait until Monday for Nvidia docker packages to come out.

**Comment by rmmcnulty9** [comment]
@RenaudWasTaken you said "wait until Monday" it is now Tuesday and I don't see any new `nvidia-docker` releases. Will this issue be updated/closed when there is a release?

**Comment by Fish2** [comment]
This is getting a bit frustrating every docker update with have this issue

**Comment by RenaudWasTaken** [comment]
Hello!

We're sorry this is taking a little bit longer than expected. We are currently running tests to make sure everything is working fine.

Automating the pipeline for releasing new packages is one of the reason this is taking a bit longer than planed.

In the meantime you can always stay (or downgrade) on the 18.09.0 release as this is still working.

Thank you for your patience.

**Comment by RenaudWasTaken** [comment]
Hello!

We've released the packages a few hours ago :)
