### ISSUE TITLE
nvidia not getting installed in docker image

### ISSUE THREAD

**Issue by sathiez** [NVIDIA/nvidia-docker#904]
I built image with s2i which has seldon wrapper. Wrapper image os version is 

**PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian**

My host os is 

**NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"**

Nvidia driver in my host :
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   51C    P0    38W /  N/A |    678MiB /  8114MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
 

I built the image with cuda 9.0 in which, when I import tensorflow(gpu). I get the following message,

**2019-01-13 12:15:38.183238: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-13 12:15:38.188659: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
2019-01-13 12:15:38.188700: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:157] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
2019-01-13 12:15:38.189212: I tensorflow/core/common_runtime/direct_session.cc:307] Device mapping:
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device**

How to solve this issue?

**Comment by sathiez** [comment]
1. Issue or feature description

nvidia is not installed in docker container when I run image with "--runtime nvidia" so I am getting the following error when I import tensorflow 

**2019-01-13 12:15:38.183238: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-13 12:15:38.188659: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
2019-01-13 12:15:38.188700: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:157] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
2019-01-13 12:15:38.189212: I tensorflow/core/common_runtime/direct_session.cc:307] Device mapping:
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device**

2. Steps to reproduce the issue

Use s2i build with seldon core wrapper  as mentioned in below link, 
[(https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/python.md)]


_nvidia-container-cli -k -d /dev/tty info_
-- WARNING, the following logs are for debugging purposes only --

I0114 04:33:38.507908 7944 nvc.c:281] initializing library context (version=1.0.0, build=881c88e2e5bb682c9bb14e68bd165cfb64563bb1)
I0114 04:33:38.507930 7944 nvc.c:255] using root /
I0114 04:33:38.507934 7944 nvc.c:256] using ldcache /etc/ld.so.cache
I0114 04:33:38.507937 7944 nvc.c:257] using unprivileged user 1000:1000
W0114 04:33:38.510436 7945 nvc.c:186] failed to set inheritable capabilities
W0114 04:33:38.510455 7945 nvc.c:187] skipping kernel modules load due to failure
I0114 04:33:38.510652 7946 driver.c:133] starting driver service
I0114 04:33:38.544614 7944 nvc_info.c:433] requesting driver information with ''
I0114 04:33:38.545023 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.390.87
I0114 04:33:38.545251 7944 nvc_info.c:149] skipping /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.390.87
I0114 04:33:38.545554 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.390.87
I0114 04:33:38.545778 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.390.87
I0114 04:33:38.545824 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.390.87
I0114 04:33:38.546086 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.390.87
I0114 04:33:38.546130 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.390.87
I0114 04:33:38.546160 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.390.87
I0114 04:33:38.546567 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.390.87
I0114 04:33:38.546604 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.390.87
I0114 04:33:38.546847 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.390.87
I0114 04:33:38.546882 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.390.87
I0114 04:33:38.547121 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.390.87
I0114 04:33:38.547146 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.390.87
I0114 04:33:38.547387 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.390.87
I0114 04:33:38.547541 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.390.87
I0114 04:33:38.547637 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.390.87
I0114 04:33:38.547855 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.390.87
I0114 04:33:38.548073 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.390.87
I0114 04:33:38.548098 7944 nvc_info.c:147] selecting /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.390.87
I0114 04:33:38.548363 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/tls/libnvidia-tls.so.390.87
I0114 04:33:38.548502 7944 nvc_info.c:149] skipping /usr/lib/i386-linux-gnu/libnvidia-tls.so.390.87
I0114 04:33:38.548736 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-ptxjitcompiler.so.390.87
I0114 04:33:38.548948 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-opencl.so.390.87
I0114 04:33:38.549181 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-ml.so.390.87
I0114 04:33:38.549439 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-ifr.so.390.87
I0114 04:33:38.549683 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-glsi.so.390.87
I0114 04:33:38.550028 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-glcore.so.390.87
I0114 04:33:38.550302 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-fbc.so.390.87
I0114 04:33:38.550568 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-fatbinaryloader.so.390.87
I0114 04:33:38.550833 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-encode.so.390.87
I0114 04:33:38.551088 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-eglcore.so.390.87
I0114 04:33:38.551321 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvidia-compiler.so.390.87
I0114 04:33:38.551541 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libnvcuvid.so.390.87
I0114 04:33:38.551811 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libcuda.so.390.87
I0114 04:33:38.552132 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libGLX_nvidia.so.390.87
I0114 04:33:38.552321 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libGLESv2_nvidia.so.390.87
I0114 04:33:38.552471 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libGLESv1_CM_nvidia.so.390.87
I0114 04:33:38.552710 7944 nvc_info.c:147] selecting /usr/lib/i386-linux-gnu/libEGL_nvidia.so.390.87
W0114 04:33:38.552728 7944 nvc_info.c:298] missing library libvdpau_nvidia.so
W0114 04:33:38.552731 7944 nvc_info.c:302] missing compat32 library libnvidia-cfg.so
W0114 04:33:38.552734 7944 nvc_info.c:302] missing compat32 library libvdpau_nvidia.so
I0114 04:33:38.552924 7944 nvc_info.c:228] selecting /usr/bin/nvidia-smi
I0114 04:33:38.552939 7944 nvc_info.c:228] selecting /usr/bin/nvidia-debugdump
I0114 04:33:38.552949 7944 nvc_info.c:228] selecting /usr/bin/nvidia-persistenced
I0114 04:33:38.552961 7944 nvc_info.c:228] selecting /usr/bin/nvidia-cuda-mps-control
I0114 04:33:38.552977 7944 nvc_info.c:228] selecting /usr/bin/nvidia-cuda-mps-server
W0114 04:33:38.552993 7944 nvc_info.c:252] missing device /dev/nvidia-uvm-tools
I0114 04:33:38.552996 7944 nvc_info.c:365] listing device /dev/nvidiactl
I0114 04:33:38.552998 7944 nvc_info.c:365] listing device /dev/nvidia-uvm
I0114 04:33:38.553001 7944 nvc_info.c:365] listing device /dev/nvidia-modeset
I0114 04:33:38.553023 7944 nvc_info.c:269] listing ipc /run/nvidia-persistenced/socket
W0114 04:33:38.553035 7944 nvc_info.c:273] missing ipc /tmp/nvidia-mps
I0114 04:33:38.553037 7944 nvc_info.c:489] requesting device information with ''
I0114 04:33:38.559326 7944 nvc_info.c:519] listing device /dev/nvidia0 (GPU-e572b8ee-523e-f7be-a359-33149791a02a at 00000000:01:00.0)
NVRM version:   390.87
CUDA version:   9.1

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 1080 with Max-Q Design
Brand:          GeForce
GPU UUID:       GPU-e572b8ee-523e-f7be-a359-33149791a02a
Bus Location:   00000000:01:00.0
Architecture:   6.1
I0114 04:33:38.559343 7944 nvc.c:318] shutting down library context
I0114 04:33:38.559639 7946 driver.c:192] terminating driver service
I0114 04:33:38.564512 7944 driver.c:233] driver service terminated successfully


_nvidia-smi -a_

==============NVSMI LOG==============

Timestamp                           : Mon Jan 14 10:28:27 2019
Driver Version                      : 390.87

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1080 with Max-Q Design
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-e572b8ee-523e-f7be-a359-33149791a02a
    Minor Number                    : 0
    VBIOS Version                   : 86.04.8A.00.69
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1BE010DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x088B1028
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 8x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 4000 KB/s
        Rx Throughput               : 1000 KB/s
    Fan Speed                       : N/A
    Performance State               : P3
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 8114 MiB
        Used                        : 371 MiB
        Free                        : 7743 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 6 MiB
        Free                        : 250 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 1 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 46 C
        GPU Shutdown Temp           : 99 C
        GPU Slowdown Temp           : 94 C
        GPU Max Operating Temp      : 91 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : 27.42 W
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 1290 MHz
        SM                          : 1290 MHz
        Memory                      : 2999 MHz
        Video                       : 1164 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1708 MHz
        SM                          : 1708 MHz
        Memory                      : 5005 MHz
        Video                       : 1544 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1476
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 18 MiB
        Process ID                  : 1519
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 48 MiB
        Process ID                  : 5563
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=7688536423843166974,1734777938762548615,131072 --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=4778472773925218874
            Used GPU Memory         : 61 MiB
        Process ID                  : 12631
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 145 MiB
        Process ID                  : 13360
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 95 MiB


Docker command used:
sudo docker run --runtime  nvidia -p 5000:5000 <imagename>
sudo nvidia-docker run  -p 5000:5000 <imagename>

**Comment by sathiez** [comment]
After using **NVIDIA_VISIBLE_DEVICES=all** now I can able to use nvdia-smi inside docker, but still I am getting the following error 

**2019-01-14 10:58:31.828997: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-14 10:58:31.834895: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
2019-01-14 10:58:31.834941: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: 7a52b07f170d
2019-01-14 10:58:31.834949: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: 7a52b07f170d
2019-01-14 10:58:31.835018: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2019-01-14 10:58:31.835050: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 390.87.0**

**Comment by RenaudWasTaken** [comment]
It seems like you aren't using one of the official docker image.
You need to set a bit more variables:
- NVIDIA_VISIBLE_DEVICES=all 
- NVIDIA_DRIVER_CAPABILITIES=compute,utility

Should fix your issue.
Feel free to reopen if this doesn't fix the problem.

**Comment by sathiez** [comment]
Yes, that did the trick!!!! Thank you very much

**Comment by RenaudWasTaken** [comment]
@tbchj please open a separate issue and provide more information on what bugs you are encountering and what you are trying to achieve.

As for documentation on the variables it is available here : Github.com/NVIDIA/nvidia-container-runtime
