### ISSUE TITLE
file /etc/docker/daemon.json conflicts between attempted installs of nvidia-docker2-2.0.3-1.docker1.13.1.noarch and docker-2:1.13.1-88.git07f3374.el7.centos.x86_64

### ISSUE THREAD

**Issue by daili0518** [NVIDIA/nvidia-docker#906]
docker version 1.13.1

when i yum install -y nvidia-docker2-2.0.3-1.docker1.13.1.noarch then output
file /etc/docker/daemon.json conflicts between attempted installs of nvidia-docker2-2.0.3-1.docker1.13.1.noarch and docker-2:1.13.1-88.git07f3374.el7.centos.x86_64

**Comment by RenaudWasTaken** [comment]
Hello!

You should resolve the conflict by hand if there is an already existing daemon.json.
Either manually remove the file or use `--replacefiles` as suggested here: https://stackoverflow.com/questions/21246680/disable-yum-transaction-check-for-file-conflict

Feel free to reopen if the issue wasn't solved.
