### ISSUE TITLE
Does the GPU number always start from 0 in container?

### ISSUE THREAD

**Issue by tjliupeng** [NVIDIA/nvidia-docker#907]
As the FAQ says, NVIDIA_VISIBLE_DEVICES can isolate the GPUs in container. In the container, if I use tensorflow, I need to specify the GPU number in the code. Does the number always start from 0 no matter which GPUs are assigned when the container starts?

**Comment by RenaudWasTaken** [comment]
Hello!

From inside a container, you can expect the GPUs to always start at 0!
