### ISSUE TITLE
ubuntu:18.10 support

### ISSUE THREAD

**Issue by lcxw** [NVIDIA/nvidia-docker#908]
I hava install ubuntu-18.10 on my computer, I want to use the ubuntu to sue tensorflow with cuda ,but the official tensorflow dos't support cuda after 9.0. Later, I found the project that can use the tensorflow with in docker ,but I can't install the nvidia-docker ,is sys that 'Unsupported distribution!'.please help me,
thanks .

**Comment by RenaudWasTaken** [comment]
Hello!

CUDA isn't supported on ubuntu 18.10, therefore the support you'll get is only best effort.
You can always install the nvidia-docker version for ubuntu 18.04:
```shell
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

# Install nvidia-docker2 and reload the Docker daemon configuration
sudo apt-get install -y nvidia-docker2
```

**Comment by kno** [comment]
You need to install bionic version of docker-ce:
`sudo apt install docker-ce=5:18.09.1~3-0~ubuntu-bionic`

**Comment by jamesmbourne** [comment]
Thanks @kno! That specific version wasn't compatiable with `nvidia-docker2`I had to install:

```bash
sudo apt install docker-ce=5:18.09.2~3-0~ubuntu-bionic
```

(`09.2` instead of `09.1`) on Ubuntu 18.10.

**Comment by protectedvar** [comment]
E: Version '5:18.09.2~3-0~ubuntu-bionic' for 'docker-ce' was not found
same problem..  how to install nvidia-docker on 18.10?

**Comment by lshem16** [comment]
@protectedvar you need to add the repo 

`sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"`
then
`sudo apt-get update`
and try again
