### ISSUE TITLE
Ubuntu 18.10 is definitely missing

### ISSUE THREAD

**Issue by DimanNe** [NVIDIA/nvidia-docker#909]
Here is an [excerpt](https://nvidia.github.io/nvidia-docker/):

> If you feel something is missing or requires additional information, please let us know by filing a new issue.

So, Ubuntu 18.10 is definitely missing in the list.
Is (K)Ubuntu 18.10 really so different from 18.04 that you excluded it?

**Comment by RenaudWasTaken** [comment]
Hello!

CUDA isn't supported on ubuntu 18.10 (it's not an LTS version), therefore the support you'll get is only best effort.
You can always install the nvidia-docker version for ubuntu 18.04:
```shell
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

# Install nvidia-docker2 and reload the Docker daemon configuration
sudo apt-get install -y nvidia-docker2
```

**Comment by DimanNe** [comment]
Thanks, it worked.

I would also mention that while installing docker one should specify its exact version:
```
sudo aptitude install docker-ce=5:18.09.1~3-0~ubuntu-bionic
```

**Comment by GauthierPLM** [comment]
@RenaudWasTaken Nvidia [offers packages for Ubuntu 18.10](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1810) on its website, so I guess Cuda is officially supported on that platform, isn't it?
It seems strange for me that Cuda is available for download ([and even has a repo](http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1810/x86_64/)) for Ubuntu 18.10 but not nvidia-docker...
