### ISSUE TITLE
GPU becomes unavailable after computer wakes up

### ISSUE THREAD

**Issue by vochicong** [NVIDIA/nvidia-docker#910]
I'd like to share a link
https://github.com/tensorflow/tensorflow/issues/5777
that maybe useful if after your computer wakes up from suspension,

- nvidia-docker stops working
- cuda on the host stops working
- nvidia-smi shows the GPU

**Comment by joshuastough** [comment]
Seems to have worked for some (including me), though the discussion is unrelated to sleeping:
`sudo apt install nvidia-modprobe`
[ https://github.com/tensorflow/tensorflow/issues/19266](https://github.com/tensorflow/tensorflow/issues/19266)

Dell Precision 5530 with P2000
Ubuntu 18.04.2 LTS
Nvidia driver 390.77
Cuda 9.0

**Comment by 4ndt3s** [comment]
Same problem here... any solution?
