### ISSUE TITLE
Can mps help to increase the GPU utilization?

### ISSUE THREAD

**Issue by GoodJoey** [NVIDIA/nvidia-docker#911]
I'm trying to find a way to increase the GPU utilization for training/inference.
I try to put several low-gpuMemory and low-gpuUtil tasks on the same GPU with mps, hoping this can help increasing the GPU utilization (just like muti-thread on cpu).
i ran 1 mnist training on my 1080ti, the speed was about 100000 samples/sec. GPU-util was about 30%.
when i ran 2 mnist training on the 1080ti at the same time with mps, the speed decrease to 50000, and the GPU-util was still about 30%. 
the ideal result: the speed for each task is 100000samples/sec, gpu-util about 60%. 
Am i doing something wrong?  Or maybe mps doesn't help the performance in this case? 
My mps setup is:
# Launch two containers on the second GPU device
sudo CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=1 nvidia-cuda-mps-control -d

docker run -ti --rm -e NVIDIA_VISIBLE_DEVICES=1 --runtime=nvidia --ipc=host nvidia/cuda
docker run -ti --rm -e NVIDIA_VISIBLE_DEVICES=1 --runtime=nvidia --ipc=host nvidia/cuda

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the late reply. Here you aren't using MPS but your containers are time sliced on the GPU which explains the problems you are seeing.

I would suggest to have the mps-control deaemon use the same IPC as host.
You might run in other issues though, you probably should start from the swarm file that we published.
See the wiki: https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL)
