### ISSUE TITLE
Depends: docker-ce (= 5:18.09.1~3-0~ubuntu-bionic) but it is not installable

### ISSUE THREAD

**Issue by joedborg** [NVIDIA/nvidia-docker#913]
### 1. Issue or feature description
`apt install` fails due to dependency issue. 

### 2. Steps to reproduce the issue
Follow README steps in README for Ubuntu 18.04.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.1~3-0~ubuntu-bionic) but it is not installable or
                           docker-ee (= 5:18.09.1~3-0~ubuntu-bionic) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This can be resolved by manually pinning the required `docker-*e` package in apt, but this isn't necessary nor neat.

**Comment by Idolized22** [comment]
Please this guide about how to install docker-ce 
I will re comment to let you know if it worked. 
I have just installed it. 
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04 
(This guide isn't mine )

**Comment by lukeyeager** [comment]
> This can be resolved by manually pinning the required `docker-*e` package in apt, but this isn't necessary nor neat.

More specifically ...
```bash
sudo apt install 'docker-ce=5:18.09.1~3-0~ubuntu-xenial'
sudo apt install nvidia-docker2
```

**Comment by tardis89** [comment]
I am experiencing this same problem on my machines and @lukeyeager's manual downgrade fixed the issue. Is it expected now to install this specific version of docker-ce or is there going to be an update soon where nvidia-docker2 will be able to use the most recent version of docker-ce?

Another note. This problem did not occur until I performed a dist-upgrade on my Ubuntu 16.04 LTS 64-bit installation. The normal upgrade process did not break it.

**Comment by RenaudWasTaken** [comment]
Hello!

nvidia-docker can use the latest version of docker-ce. If you have it, follow the install instructions on the README.

If you don't, pin the nvidia-docker2 and nvidia-container-runtime package versions as mentioned in the FAQ: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version

**Comment by thesby** [comment]
Is ubuntu 18.04 supported now ? Why does the problem still happen when I pin the version of `nvidia-docker2 nvidia-container-runtime`

```
sudo apt install nvidia-docker2=2.0.3+docker18.09.3-1  nvidia-container-runtime=2.0.0+docker18.09.3-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.3~3-0~ubuntu-xenial) but 5:18.09.3~3-0~ubuntu-bionic is to be installed or
                           docker-ee (= 5:18.09.3~3-0~ubuntu-xenial) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by joedborg** [comment]
Yeah, for this to work you need to pin all 3, for example:

```
docker-ce=18.06.0~ce~3-0~ubuntu
nvidia-container-runtime=2.0.0+docker18.06.0-1
nvidia-docker2=2.0.3+docker18.06.0-1
```

I really hope Nvidia fix this soon.

**Comment by ericspod** [comment]
> Hello!
> 
> nvidia-docker can use the latest version of docker-ce. If you have it, follow the install instructions on the README.
> 
> If you don't, pin the nvidia-docker2 and nvidia-container-runtime package versions as mentioned in the FAQ: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version

Hi @RenaudWasTaken the solution in the FAQ doesn't work on Ubuntu 16.04, the instructions from @Idolized22 (with bionic replaced with xenial) allowed me to install docker-ce=5:18.09.7~3-0~ubuntu-xenial (not the latest version) which does now allow nvidia-docker2 to install.

**Comment by leimao** [comment]
> Is ubuntu 18.04 supported now ? Why does the problem still happen when I pin the version of `nvidia-docker2 nvidia-container-runtime`
> 
> ```
> sudo apt install nvidia-docker2=2.0.3+docker18.09.3-1  nvidia-container-runtime=2.0.0+docker18.09.3-1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  nvidia-docker2 : Depends: docker-ce (= 5:18.09.3~3-0~ubuntu-xenial) but 5:18.09.3~3-0~ubuntu-bionic is to be installed or
>                            docker-ee (= 5:18.09.3~3-0~ubuntu-xenial) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> I have installed docker-ce on my ubuntu 18.04
> 
> ```
> docker info
> Containers: 1
>  Running: 0
>  Paused: 0
>  Stopped: 1
> Images: 1
> Server Version: 18.09.3
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
> runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
> init version: fec3683
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.18.0-16-generic
> Operating System: Ubuntu 18.04.2 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 12
> Total Memory: 7.785GiB
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
> 
> WARNING: No swap limit support
> ```

This problem happened to me as well when Docker has just upgraded their version.

**Comment by RenaudWasTaken** [comment]
We published new packages with a different architecture (nvidia-container-runtime 3.0.0).

You should never see this issue again!
