### ISSUE TITLE
nvidia-docker instaaltion issue

### ISSUE THREAD

**Issue by deo999** [NVIDIA/nvidia-docker#918]
getting following error docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:293: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown.

**Comment by yannan0911** [comment]
same problem..

**Comment by RenaudWasTaken** [comment]
Hello!

Please fill the issue template. It's very hard to help you if you don't detail your setup...

**Comment by NoSyu** [comment]
I've got the same error on docker-ce, not nvidia-docker. I guess this post is helpful to solve this issue.
https://forums.docker.com/t/centos7-docker-hello-world-fails/68941/3

Simple solutions
- Update the kernel version (or)
- Downgrade the docker version

**Comment by wlwinston** [comment]
> getting following error docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:293: copying bootstrap data to pipe caused "write init-p: broken pipe"": unknown.

 update your linux kernel version  can fix this problem

**Comment by oiooj** [comment]
> > getting following error docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:293: copying bootstrap data to pipe caused "write init-p: broken pipe"": unknown.
> 
> update your linux kernel version can fix this problem

Yes, fixed by update linux kernel

**Comment by sunformoon** [comment]
I got the same error on my 14.04 OS. Then I upgraded my OS to 16.04, which solved the issue. But I would say be careful when you decide to upgrade your OS.
