### ISSUE TITLE
PyOpenCL nvidia-docker container

### ISSUE THREAD

**Issue by gautam1858** [NVIDIA/nvidia-docker#919]
I have been trying to make a container for PyOpenCL for use in DGX Cluster, but for some unknown reasons those containers are not working on Nvidia GPU clusters and its throwing out this error mentioned in below code. 

Since many researchers are also working on PyOpenCL, it will be great to see a docker container for PyOpenCL which works with Nvidia DGX clusters.

```
import pyopencl as cl
platform = cl.get_platforms()
```
```
Error:
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
```

**Comment by RenaudWasTaken** [comment]
Just to let you know that we've acked the request.
We are still debating if we should be doing this, however given the current load of the team and the fact that this isn't a priority, don't expect any changes on this front for a while.

**Comment by gautam1858** [comment]
Can you help me build this container and give pointers to resources where I can debug and get it done ?

**Comment by RenaudWasTaken** [comment]
I would expect that you are missing some environment variables: https://github.com/NVIDIA/nvidia-container-runtime#environment-variables-oci-spec
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/10.1/base/Dockerfile#L31-32

**Comment by gautam1858** [comment]
Ok thank you will try out

**Comment by RenaudWasTaken** [comment]
Hello!

Unfortunately after some discussions internally, we've arrived at the decision that CUDA is our innovation platform, so we don't believe we should be spending our energy in creating & maintaining OpenCL images.

Closing this, feel free to ask if you have more questions around building one :)

**Comment by edmald** [comment]
Hi, @gautam1858 did you solve this issue? I am facing the same. 
I will appreciate your help.
