### ISSUE TITLE
Question about the nvidia-docker , RPM-based

### ISSUE THREAD

**Issue by jameslam0250** [NVIDIA/nvidia-docker#923]
We use the CentOS 7 (docker-ce), RHEL 7.4/7.5 (docker-ce) method to install the nvidia-docker. whilst nvidia-smi functional when CUDA 9.0 with 39x driver to drive P40 Tesla

However, when we use the repo. something is missing inside the github and we urge for help
--> Processing Dependency: docker-ce = 3:18.09.2 for package: nvidia-docker2-2.0.3-1.docker18.09.2.ce.noarch
--> Running transaction check
---> Package libnvidia-container-tools.x86_64 0:1.0.1-1 will be installed
--> Processing Dependency: libnvidia-container1(x86-64) >= 1.0.1-1 for package: libnvidia-container-tools-1.0.1-1.x86_64
--> Processing Dependency: libnvidia-container.so.1(NVC_1.0)(64bit) for package: libnvidia-container-tools-1.0.1-1.x86_64
--> Processing Dependency: libnvidia-container.so.1()(64bit) for package: libnvidia-container-tools-1.0.1-1.x86_64
---> Package nvidia-docker2.noarch 0:2.0.3-1.docker18.09.2.ce will be installed
--> Processing Dependency: docker-ce = 3:18.09.2 for package: nvidia-docker2-2.0.3-1.docker18.09.2.ce.noarch
--> Running transaction check
---> Package libnvidia-container1.x86_64 0:1.0.1-1 will be installed
---> Package nvidia-docker2.noarch 0:2.0.3-1.docker18.09.2.ce will be installed
--> Processing Dependency: docker-ce = 3:18.09.2 for package: nvidia-docker2-2.0.3-1.docker18.09.2.ce.noarch
--> Finished Dependency Resolution
Error: Package: nvidia-docker2-2.0.3-1.docker18.09.2.ce.noarch (nvidia-docker)
           Requires: docker-ce = 3:18.09.2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

We tried to use the docker-ce, docker-ce-cli from the original docker (non-GPU based). It stucks at the nvidia-smi testing phase.

**Comment by RenaudWasTaken** [comment]
What version of docker do you have on your machine?
It seems like you don't have the docker18.09.2 version.

In which case you can either upgrade docker or pin the version of nvidia-docker to the version of docker you have.

**Comment by RenaudWasTaken** [comment]
Feel free to reopen if you have any questions!
