### ISSUE TITLE
nvidia-docker | 2019/03/02 22:27:16 Error: failed to run docker command

### ISSUE THREAD

**Issue by Hiker01** [NVIDIA/nvidia-docker#929]
I can start docker service and nvidia-docker service and I can also run docker command. However when I use nvidia-docker run ... I got this error : nvidia-docker | 2019/03/02 22:27:16 Error: failed to run docker command

docker version: 18.03.1-ce
nvidia-docker version: 1.0.1

docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-03-02 22:13:54 CST; 16min ago
     Docs: https://docs.docker.com
 Main PID: 19503 (dockerd)
   Memory: 38.4M
   CGroup: /system.slice/docker.service
           忖19503 /usr/bin/dockerd -H unix://
           忖19513 docker-containerd --config /var/run/docker/containerd/containerd.toml

Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.591476859+08:00" level=info msg="[grap...pper"
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.627095652+08:00" level=info msg="Graph...onds"
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.627681174+08:00" level=warning msg="mo...ound"
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.628773112+08:00" level=info msg="Loadi...art."
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.829632706+08:00" level=info msg="Defau...ress"
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.943203614+08:00" level=info msg="Loadi...one."
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.975544886+08:00" level=info msg="Docke....1-ce
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.975699774+08:00" level=info msg="Daemo...tion"
Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.983632670+08:00" level=info msg="API l...sock"
Mar 02 22:13:54 s4 systemd[1]: Started Docker Application Container Engine.
Hint: Some lines were ellipsized, use -l to show in full.

nvidia-docker.service - NVIDIA Docker plugin
   Loaded: loaded (/usr/lib/systemd/system/nvidia-docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-03-02 22:20:41 CST; 10min ago
     Docs: https://github.com/NVIDIA/nvidia-docker/wiki
  Process: 19941 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
  Process: 19931 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
 Main PID: 19930 (nvidia-docker-p)
   Memory: 7.3M
   CGroup: /system.slice/nvidia-docker.service
           忖19930 /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker

Mar 02 22:20:41 s4 systemd[1]: Starting NVIDIA Docker plugin...
Mar 02 22:20:41 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:41 L...ory
Mar 02 22:20:41 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:41 L...ary
Mar 02 22:20:41 s4 systemd[1]: Started NVIDIA Docker plugin.
Mar 02 22:20:45 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:45 D...ces
Mar 02 22:20:46 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:46 P...mes
Mar 02 22:20:46 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:46 S...ker
Mar 02 22:20:46 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:46 S...476
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by RenaudWasTaken** [comment]
Hello!

Please upgrade to the version 2.
Feel free to open a different issue if you hit the bug.

**Comment by Hiker01** [comment]
Cause I'm using centos7, and nvidia-docker2 are not supported by my kernel.

**Comment by RenaudWasTaken** [comment]
Hello!

Nvidia-docker is supported on centos7, see the instructions on the README :)

**Comment by bjtudujunlin** [comment]
> I can start docker service and nvidia-docker service and I can also run docker command. However when I use nvidia-docker run ... I got this error : nvidia-docker | 2019/03/02 22:27:16 Error: failed to run docker command
> 
> docker version: 18.03.1-ce
> nvidia-docker version: 1.0.1
> 
> docker.service - Docker Application Container Engine
> Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
> Active: active (running) since Sat 2019-03-02 22:13:54 CST; 16min ago
> Docs: https://docs.docker.com
> Main PID: 19503 (dockerd)
> Memory: 38.4M
> CGroup: /system.slice/docker.service
> 忖19503 /usr/bin/dockerd -H unix://
> 忖19513 docker-containerd --config /var/run/docker/containerd/containerd.toml
> 
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.591476859+08:00" level=info msg="[grap...pper"
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.627095652+08:00" level=info msg="Graph...onds"
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.627681174+08:00" level=warning msg="mo...ound"
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.628773112+08:00" level=info msg="Loadi...art."
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.829632706+08:00" level=info msg="Defau...ress"
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.943203614+08:00" level=info msg="Loadi...one."
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.975544886+08:00" level=info msg="Docke....1-ce
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.975699774+08:00" level=info msg="Daemo...tion"
> Mar 02 22:13:54 s4 dockerd[19503]: time="2019-03-02T22:13:54.983632670+08:00" level=info msg="API l...sock"
> Mar 02 22:13:54 s4 systemd[1]: Started Docker Application Container Engine.
> Hint: Some lines were ellipsized, use -l to show in full.
> 
> nvidia-docker.service - NVIDIA Docker plugin
> Loaded: loaded (/usr/lib/systemd/system/nvidia-docker.service; disabled; vendor preset: disabled)
> Active: active (running) since Sat 2019-03-02 22:20:41 CST; 10min ago
> Docs: https://github.com/NVIDIA/nvidia-docker/wiki
> Process: 19941 ExecStartPost=/bin/sh -c /bin/echo unix://$SOCK_DIR/nvidia-docker.sock > $SPEC_FILE (code=exited, status=0/SUCCESS)
> Process: 19931 ExecStartPost=/bin/sh -c /bin/mkdir -p $( dirname $SPEC_FILE ) (code=exited, status=0/SUCCESS)
> Main PID: 19930 (nvidia-docker-p)
> Memory: 7.3M
> CGroup: /system.slice/nvidia-docker.service
> 忖19930 /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker
> 
> Mar 02 22:20:41 s4 systemd[1]: Starting NVIDIA Docker plugin...
> Mar 02 22:20:41 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:41 L...ory
> Mar 02 22:20:41 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:41 L...ary
> Mar 02 22:20:41 s4 systemd[1]: Started NVIDIA Docker plugin.
> Mar 02 22:20:45 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:45 D...ces
> Mar 02 22:20:46 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:46 P...mes
> Mar 02 22:20:46 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:46 S...ker
> Mar 02 22:20:46 s4 nvidia-docker-plugin[19930]: /usr/bin/nvidia-docker-plugin | 2019/03/02 22:20:46 S...476
> Hint: Some lines were ellipsized, use -l to show in full.

Hello！
Have you resolved this issue，I Encountered the same problem with centos7 and nvidia-docker1

**Comment by memaldi** [comment]
Hi,

I have the same issue. I can't upgrade to nvidia-docker v2 because it is not compatible with Hadoop YARN 3.1.0 and I can't upgrade it. Any hint to solve this?

Thanks!
