### ISSUE TITLE
requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.(I couldn't get help with similar questions before.)

### ISSUE THREAD

**Issue by kudou1994** [NVIDIA/nvidia-docker#931]
sudo docker run --runtime=nvidia -p 8508:8500 --mount type=bind,source=/tmp/export,target=/models/yyq -e MODEL_NAME=yyq -t tensorflow/serving:latest-gpu

docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=6970 /var/lib/docker/overlay2/be703c71bd745b392a8a6756dc47e151bee1a1402b770ed21c5047054354212f/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.
----------------------------------------------------
when i try to test:  sudo nvidia-docker run --rm nvidia/cuda:9.0-devel nvidia-smi
it's ok.

Ubuntu16.04
python3.6
Driver Version: 390.77
CUDA:9.0.176
CUDNN:7.0.5
tensorflow-gpu 1.12
The latest version of docker

**Comment by kudou1994** [comment]
gtx 1080ti
Docker version 18.09.1, build 4c52b90

**Comment by kudou1994** [comment]
sudo docker run --rm --runtime=nvidia nvidia/cuda:9.0-devel -p 8508:8500 --mount type=bind,source=/tmp/export,target=/models/yyq -e MODEL_NAME=yyq -t tensorflow/serving:latest-gpu
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"-p\": executable file not found in $PATH": unknown.

**Comment by RenaudWasTaken** [comment]
Hello!

Upgrade your driver or use cuda 9 images

**Comment by kudou1994** [comment]
> Hello!
> 
> Upgrade your driver or use cuda 9 images

sorry, could you tell me how to use cuda 9 images with my command:
sudo docker run --runtime=nvidia -p 8508:8500 --mount type=bind,source=/tmp/export,target=/models/yyq -e MODEL_NAME=yyq -t tensorflow/serving:latest-gpu
------------------------------------------------------------------------------
or upgrade my driver? my Driver Version: 390.77, What version should I upgrade to?

**Comment by RenaudWasTaken** [comment]
Upgrade to the latest driver version or use an older version of tensorflow (rather than the latest image)
