### ISSUE TITLE
sorry, could you tell me how to use cuda 9 images with my command: sudo docker run --runtime=nvidia -p 8508:8500 --mount type=bind,source=/tmp/export,target=/models/yyq -e MODEL_NAME=yyq -t tensorflow/serving:latest-gpu

### ISSUE THREAD

**Issue by kudou1994** [NVIDIA/nvidia-docker#932]
Hello!

Upgrade your driver or use cuda 9 images

_Originally posted by @RenaudWasTaken in https://github.com/NVIDIA/nvidia-docker/issues/931#issuecomment-469067029_

sorry, could you tell me how to use cuda 9 images with my command:
sudo docker run --runtime=nvidia -p 8508:8500 --mount type=bind,source=/tmp/export,target=/models/yyq -e MODEL_NAME=yyq -t tensorflow/serving:latest-gpu

**Comment by kudou1994** [comment]
sudo nvidia-docker run nvidia/cuda:9.0-base -p 8508:8500 --mount type=bind,source=/tmp/export,target=/models/yyq -e MODEL_NAME=yyq -t tensorflow/serving:latest-gpu
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"-p\": executable file not found in $PATH": unknown.
ERRO[0004] error waiting for container: context canceled

**Comment by RenaudWasTaken** [comment]
Answered here: https://github.com/NVIDIA/nvidia-docker/issues/931#issuecomment-469071870
