### ISSUE TITLE
Any side effects of default-runtime=nvidia?

### ISSUE THREAD

**Issue by xkortex** [NVIDIA/nvidia-docker#935]
This is a pretty general question. With `runtime: nvidia` getting deprecated in docker-compose, it seems the main recommended way to readily use the nvidia runtime is put `default-runtime=nvidia` in `daemon.json`. 

What, if any, are the consequences of using nvidia as the default runtime for containers that do not need gpu, as opposed to the default? (which i think is runc?) If it's not a container image with nvidia libraries, will this affect anything at all? 

Thanks.

**Comment by Dazog** [comment]
where is the document showing depreciation?

**Comment by xkortex** [comment]
The option `runtime: whatever` was deprecated when docker-compose advanced from 2 to 3. Here is an [issue](https://github.com/docker/app/issues/241) brought up due to the loss of that argument. I know of a couple people around my office that were thrown off by this, and several just stuck with `version: 2` dc.yml instead of modifying `daemon.json`, because momentum. 

It would be nice to update to dc 3, but since I know very little about the underlying tech, I just want to make sure that setting default runtime to nvidia isn't going to mess up other workflows.

**Comment by D34DC3N73R** [comment]
https://github.com/NVIDIA/nvidia-container-runtime 

> A modified version of runc adding a custom pre-start hook to all containers.
If environment variable NVIDIA_VISIBLE_DEVICES is set in the OCI spec, the hook will configure GPU access for the container by leveraging nvidia-container-cli from project libnvidia-container.

The assumption could be made that if `NVIDIA_VISIBLE_DEVICES` is not set, the hook would not configure GPU access. Furthermore,

>NVIDIA_VISIBLE_DEVICES
>This variable controls which GPUs will be made accessible inside the container.

>Possible values
>`0,1,2`, `GPU-fef8089b` …: a comma-separated list of GPU UUID(s) or index(es).
>`all`: all GPUs will be accessible, this is the default value in our container images.
>`none`: no GPU will be accessible, but driver capabilities will be enabled.
>`void` or empty or unset: nvidia-container-runtime will have the same behavior as `runc`.

**Comment by RenaudWasTaken** [comment]
> What, if any, are the consequences of using nvidia as the default runtime for containers that do not need gpu, as opposed to the default? 

We wrap runc and follow closely (exactly) the runc version associated to a specific docker version. So no technical "consequences" as in the end you call into the same runc as docker (this is especially true for non GPU containers). You do lose docker support if you are an EE customer.

> The option runtime: whatever was deprecated when docker-compose advanced from 2 to 3. Here is an issue brought up due to the loss of that argument. I know of a couple people around my office that were thrown off by this, and several just stuck with version: 2 dc.yml instead of modifying daemon.json, because momentum.

We'll be moving to a `docker run --gpu` model, which should solve this question in docker compose v3.
Unfortunately, I don't have a timeline for the compose update.
