### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344 

### ISSUE THREAD

**Issue by mjuarezqc** [NVIDIA/nvidia-docker#937]
Hello, 

I'm currently experiencing an issue running nvidia-docker2 on the following system:

ubuntu 16.04
* Kernel 4.15.0-45-generic
nvidia-docker2_2.0.3+docker18.09.2-1_all.deb
* installed via debian package
Docker version 18.09.2, build 6247962

The issue is that whenever I invoke the -v option and any suboptions of volume flag docker returns an error.

docker run --runtime=nvidia -v /path1:/path1:rshared -v /path2:/path2:rshared --rm -it nvidia/cuda /bin/bash

Error Message:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log --ldcache=/etc/ld.so.cache configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=9416 /path/docker/overlay2/496796451de897c3b6ec4117f4dfde55e099f52535efc8a7c14873885d634eca/merged]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig.real failed with error code: 1\\\\n\\\"\"": unknown.

Debug Log:

[nvidia-container-runtime-hook-clean.log](https://github.com/NVIDIA/nvidia-docker/files/2963094/nvidia-container-runtime-hook-clean.log)

Thank You 

-Marc

**Comment by haitaoh** [comment]
i have the same question too.
i use `docker image ls` and find that:
nvidia/cuda             9.0-base            411830f910a9        2 weeks ago         135MB
nvidia/cuda             latest                  d9a8427c8dd9      7 weeks ago         2.35GB
9.0-base is correct while latest is wrong.

**Comment by shizhaojingszj** [comment]
maybe GPU is broken....

**Comment by RenaudWasTaken** [comment]
In the logs it says mount failed, no space left on device.
Do you have a specific partition scheme?

**Comment by RenaudWasTaken** [comment]
Closing as no answer in a few months!
