### ISSUE TITLE
X server built-in

### ISSUE THREAD

**Issue by Immortalin** [NVIDIA/nvidia-docker#938]
Is it possible to run [this](https://gitlab.com/nvidia/samples/blob/master/opengl/ubuntu16.04/turbovnc-virtualgl/Dockerfile) with a built-in X server instead of an external one?

**Comment by lfelipesv** [comment]
Yes, it is possible... but I need more details to guide you through it.

Best Regards,

Felipe.

**Comment by RenaudWasTaken** [comment]
The brief answer is no, it's not supported and the nvidia driver will fail when creating your GLX context.
On tesla GPUs however, you will have access to one 4k display.

**Comment by Immortalin** [comment]
What about xdummy?

**Comment by lfelipesv** [comment]
@Immortalin , actually i used the script you sent to build the prototype of a platform I was working on couple months ago using AWS GPU Instances + Docker + Nvidia Docker + Robotics simulators... It worked in the tests...

I created a display in the server using xinit on the gpu... then I passed the display via parameter to initiate my docker container, and it worked fine... The final version of the platform still use this strategy...

Is it similar to what you are trying to achieve?

**Comment by Immortalin** [comment]
@lfelipesv yes except my computer's GPU does not have the virtual display function so I am looking to use a headless x server

**Comment by lfelipesv** [comment]
@Immortalin, by a headless x server do you mean you dont have a monitor? (sorry for the noob question) If yes, I am doing the same as I am using a server on the cloud without GUI.

**Comment by Immortalin** [comment]
Yes. But the newer GPUs has hardware/driver level support for "emulating" a display. The traditional way is to use Xdummy.

**Comment by lfelipesv** [comment]
So, you can base your dockerfile on the link you sent (this is what I did)... and you can install the nvidia-docker package and send nvidia as the runtime and the the emulated display as the display using docker run in your headless server... It should work

Are you experiencing errors to do that?
