### ISSUE TITLE
404 Link in the FAQ Section

### ISSUE THREAD

**Issue by JADG14** [NVIDIA/nvidia-docker#939]
### 1. Issue or feature description
In the [FAQ](https://github.com/nvidia/nvidia-docker/wiki/Frequently-Asked-Questions#do-you-support-powerpc64-ppc64le), there is a dead link in the section regarding support for Docker Compose.

"You can find an example here."

Link in question: https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/docker-compose.yml

**Comment by JADG14** [comment]
I believe this is the correct link...?

https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/docker/docker-compose.yml

**Comment by guptaNswati** [comment]
Fixed!
