### ISSUE TITLE
Linux (RedHat) installation issue

### ISSUE THREAD

**Issue by maknctu** [NVIDIA/nvidia-docker#94]
How to install package with Linux (RedHat) ?? Does current available package support Linux ?? I am unable to run make files with error message "Unsupported Docker version"..

**Comment by flx42** [comment]
Use those instructions:
https://github.com/NVIDIA/nvidia-docker#other-distributions

If you have the message "Unsupported Docker version" then your version of Docker is probably too old (you can check with `docker version`).
