### ISSUE TITLE
Quick start instructions suggest versions of Docker which break the dependency. Maybe just take it out?

### ISSUE THREAD

**Issue by ChanceNCounter** [NVIDIA/nvidia-docker#941]
Past issues suggest that this package is "tightly coupled" to the version of Docker for which it was most recently modified.

However, the quick start instructions _right up front_ offer two different avenues to install a version of Docker which may or may not match.

It's my understanding from past issues that you guys can't do anything about the hard dependency. That's fine, but please stop advising new users to create extra work for themselves!

Alternatively, you could shift the burden, explicitly switching *to* a version dependency whenever you discover that a Docker update creates meaningful problems. Googling seems to indicate that most people who alter the dependency to '>=' wind up with a working system. Undefined behavior sucks, but which experience would you prefer by default, downgrading a running package because you hit an error, or downgrading a minor release because a vendor *thinks* you *might* hit an error - the same vendor who advised you to choose that release in the first place?

Anyway, please consider replacing those instructions with the advice that the aptitude package is dependent on a specific version of Docker. This would have saved a lot of people a lot of time, and also saved you the trouble of closing this and many past issues.

**Comment by RenaudWasTaken** [comment]
Hello!

We'll be changing the instructions to point to the new --gpu option as soon as 19.03 is out :)
This will solve the the hard dependency to the runtime.

Thanks for suggesting other alternatives :)
