### ISSUE TITLE
[DOC] need adding an example about isolating GPU

### ISSUE THREAD

**Issue by jeng1220** [NVIDIA/nvidia-docker#943]
### 1. Issue or feature description
I found that many docker beginners don't understand how to isolate GPU for container although we already posted the information at "[I have multiple GPU devices, how can I isolate them between my containers?](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#i-have-multiple-gpu-devices-how-can-i-isolate-them-between-my-containers)"
The key is that they need a simple example, such as 
```
$ docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=2,3 $IMAGE_ID
```
Otherwise, they may try to type some commands like `$ export NVIDIA_VISIBLE_DEVICES=2,3`, then find that it doesn't work

so It will be better to add such example at "[I have multiple GPU devices, how can I isolate them between my containers?](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#i-have-multiple-gpu-devices-how-can-i-isolate-them-between-my-containers)"

**Comment by RenaudWasTaken** [comment]
Done, thanks for the suggestion!
