### ISSUE TITLE
New Docker stable v18.09.4

### ISSUE THREAD

**Issue by tiangolo** [NVIDIA/nvidia-docker#944]
### 1. Issue or feature description

The latest Docker stable version is `v18.09.4` ([released 5 hours ago](https://github.com/docker/engine/releases/tag/v18.09.4))

Nvidia Docker still requires version `18.09.3`.

### 2. Steps to reproduce the issue

In a new Ubuntu 18.04.1 LTS, install Docker:

```bash
# Download Docker
curl -fsSL get.docker.com -o get-docker.sh
# Install Docker using the stable channel (instead of the default "edge")
CHANNEL=stable sh get-docker.sh
# Remove Docker install script
rm get-docker.sh
```

Then install `nvidia-docker` following the default instructions, the following error is shown:

```bash
$ sudo apt-get install -y nvidia-docker2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.3~3-0~ubuntu-bionic) but 5:18.09.4~3-0~ubuntu-bionic is to be installed or
                           docker-ee (= 5:18.09.3~3-0~ubuntu-bionic) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [x] Kernel version from `uname -a`: 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`: `NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1`
 - [x] Docker version from `docker version`: `18.09.4`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`: 
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by tiangolo** [comment]
This seems to be solved in the latest version `2.0.3+docker18.09.4-1`. I just updated everything in my local machine and it seemed to work well.

**Comment by RenaudWasTaken** [comment]
Ah yes sorry!

I published an update last Thursday and forgot to mention it here... 

With the - - gpu option in the next Docker release, this problem will go away!

I'll publish some more information in the next few weeks!

**Comment by tiangolo** [comment]
Excellent. Thank you!
