### ISSUE TITLE
_E: Unable to locate package nvidia-docker2

### ISSUE THREAD

**Issue by lab9001** [NVIDIA/nvidia-docker#953]
### 1. Issue or feature description
I know this issue came up earlier, but none of the solutions are working in my case:

sudo apt-get install nvidia-docker2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvidia-docker2

### 2. Steps to reproduce the issue
sudo apt-get install nvidia-docker2

### 3. Information 

sudo wget https://nvidia.github.io/nvidia-docker/gpgkey
--2019-04-10 05:58:01--  https://nvidia.github.io/nvidia-docker/gpgkey
Resolving proxy.)... 141.42.5.215
Connecting to proxy.)|141.42.5.215|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3163 (3.1K) [application/octet-stream]
Saving to: ‘gpgkey.6’

gpgkey.6            100%[===================>]   3.09K  --.-KB/s    in 0s      

2019-04-10 05:58:01 (39.7 MB/s) - ‘gpgkey.6’ saved [3163/3163]

labor:~$  sudo apt-key add gpgkey.6
OK

labor:~$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
>   sudo tee /etc/apt/sources.list.d/nvidia-docker.list

labor:~$ sudo apt-get update
.....
labor:~$ sudo apt-get install nvidia-docker2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvidia-docker2

**docker version:**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Wed Jun 20 21:43:51 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Wed Jun 20 21:42:00 2018
  OS/Arch:      linux/amd64
  Experimental: false

dpkg -l | grep docker
ii  docker-ce                                  18.03.1~ce~3-0~ubuntu                        amd64        Docker: the open-source application container engine

uname -a
Linux 4.17.0-041700-generic #201806041953 SMP Mon Jun 4 19:55:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

nvidia-smi
-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:21:00.0  On |                  Off |
| 26%   53C    P8    15W / 250W |    352MiB / 24446MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2802      G   /usr/lib/xorg/Xorg                            57MiB |
|    0      3126      G   /usr/bin/gnome-shell                          57MiB |
|    0      3607      G   /usr/lib/xorg/Xorg                           145MiB |
|    0      3720      G   /usr/bin/gnome-shell                          89MiB |
+-----------------------------------------------------------------------------+

Also the prerequistes have been installed. Is there a way to check if they were correctly installed?

Thank you for your help!

**Comment by RenaudWasTaken** [comment]
You aren't doing the apt-get update.

**Comment by lab9001** [comment]
I did it (the apt-get update).

Is there a way to check, if the prerequesites have been correctly installed? How looks your /etc/apt/sources.list? Would be very helpfu if you could post what's in your's after the prerequisites have been installed.

**Comment by lab9001** [comment]
When I look in my /etc/apt/sources.list.d/nvidia-docke.list then it's empty. Is tehre something in yours?

**Comment by RenaudWasTaken** [comment]
Please run the full instructions:
```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

# Install nvidia-docker2 and reload the Docker daemon configuration
sudo apt-get install -y nvidia-docker2
sudo pkill -SIGHUP dockerd
```

**Comment by Wei-Zhuo** [comment]
> Please run the full instructions:
> 
> ```
> curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
>   sudo apt-key add -
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
>   sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> sudo apt-get update
> 
> # Install nvidia-docker2 and reload the Docker daemon configuration
> sudo apt-get install -y nvidia-docker2
> sudo pkill -SIGHUP dockerd
> ```

Hello, I am sure that I follow the full instructions as you suggested, but I still get the `E: Unable to locate package nvidia-docker2`. I am trying to install nvidia-docker2 on NVIDIA A100, Ubuntu 20.04. I have no idea why this error comes out. Would you mind giving me any suggestions?

**Comment by elezar** [comment]
Could you confirm that the file `/etc/apt/sources.list.d/nvidia-docker.list` file and has the contents as expected [here](https://github.com/NVIDIA/nvidia-docker/blob/gh-pages/ubuntu18.04/nvidia-docker.list).

**Comment by Wei-Zhuo** [comment]
> Could you confirm that the file `/etc/apt/sources.list.d/nvidia-docker.list` file and has the contents as expected [here](https://github.com/NVIDIA/nvidia-docker/blob/gh-pages/ubuntu18.04/nvidia-docker.list).

Thanks for your reply. I figure out where the problem comes from. I find no `tee` out when I do `curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`. The `$distribution` will be `Ubuntu20.04`, so no answers respond.

**Comment by Wei-Zhuo** [comment]
> @Wei-Zhuo you mentioned `Ubuntu20.04`? GitHub pages (which is being used to host the repos at present) is case sensitive and as such `Ubuntu20.04` is not a valid distribution while `ubuntu20.04` is.
> 
> @sherwoac since the `ubuntu20.04` folders are symlinks to `ubuntu18.04` making the replacement will continue to work. It is, however not necessary which is why we refer to the `ubuntu18.04` URLs directly in the `.list` file. The packages that end up being installed are the same.
Oh, I see. I made a silly mistake.
Thanks for the reply, a lot.

**Comment by kkuchynskyi** [comment]
> I noticed that this site: `https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list` has this output: `deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) / #deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) / deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) / #deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) / deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /` so I just copied this output into: `/etc/apt/sources.list.d/nvidia-docker.list` and changed 18->20: `deb https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/$(ARCH) / #deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) / deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu20.04/$(ARCH) / #deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) / deb https://nvidia.github.io/nvidia-docker/ubuntu20.04/$(ARCH) / ` then I ran: `sudo apt update; sudo apt install nvidia-docker2`
> 
> and now it works! Nvidia just need to update: [their website](https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list)

It has worked for ubuntu 21.04 as well.

**Comment by mathpopo** [comment]
> sudo apt install nvidia-docker2

(base) chenxin@chenxin-Nitro-AN515-52:/etc/apt/sources.list.d$ cat nvidia-docker.list
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/$(ARCH) /
###deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu20.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu20.04/$(ARCH) /
###deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu20.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu20.04/$(ARCH) /
(base) chenxin@chenxin-Nitro-AN515-52:/etc/apt/sources.list.d$ cat nvidia-container-toolkit.list
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu20.04/$(ARCH) /
(base) chenxin@chenxin-Nitro-AN515-52:/etc/apt/sources.list.d$ cat nvidia-container-runtime.list
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu20.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu20.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu20.04/$(ARCH) /
#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu20.04/$(ARCH) /
(base) chenxin@chenxin-Nitro-AN515-52:/etc/apt/sources.list.d$ uname -a
Linux chenxin-Nitro-AN515-52 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
(base) chenxin@chenxin-Nitro-AN515-52:/etc/apt/sources.list.d$ sudo apt install nvidia-docker2
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 nvidia-docker2
