### ISSUE TITLE
RPM's for CentOS are not signed

### ISSUE THREAD

**Issue by Rovanion** [NVIDIA/nvidia-docker#956]
### 1. Issue or feature description
The packages in the nvidia-docker repository are not signed. This means that there is no way for me as a customer to be sure that the packages have not been tempered with either at rest or in transit.

### 2. Steps to reproduce the issue
If you look at the [repository configuration file](https://nvidia.github.io/nvidia-docker/centos7/nvidia-docker.repo) given in the [repository configuration documentation]( https://nvidia.github.io/nvidia-docker/) you will find that each repository entry has `gpgcheck=0` specified. This means that yum is instructed to not verify the signatures of packages before attempting to install them on the system. If we set this value to 1 the installation of the packages will fail, either because the signature is invalid or because it does not exist.

### 3. Requested course of action
I would recommend you sign your packages. It is not very hard to do and large corporate IT departments generally frown on installing random stuff from the internet, i.e. if this became known a park of DGX:es could fast become unusable.

**Comment by RenaudWasTaken** [comment]
> The packages in the nvidia-docker repository are not signed. This means that there is no way for me as a customer to be sure that the packages have not been tempered with either at rest or in transit.

Hello!

The package metadata are signed, this allows yum to verify that the packages haven't been tampered with :)

**Comment by Rovanion** [comment]
Right, that allows yum to verify (because the metadata of the repository contains checksums of the files in the repository) that the contents of the repository is the same as when the repository was signed. Whether that is worse than individual package signing will depend on the security details of the implemented processes.

Posterity: Remember to set `repo_gpgcheck=1` if you manage your own repofiles.
