### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: exec: "nvidia-container-runtime-hook": executable file not found in $PATH: unknown.

### ISSUE THREAD

**Issue by cris1403** [NVIDIA/nvidia-docker#958]
### 1. Issue or feature description

Issue on installing nvidia-docker on a Ubuntu 16.04 desktop. Tensorflow installed in an Anaconda environemnt, works well using my GPU (GTX 980). 

### 2. Steps to reproduce the issue

`docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`

`docker: Error response from daemon: OCI runtime create failed: exec: "nvidia-container-runtime-hook": executable file not found in $PATH: unknown.`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`

`-- WARNING, the following logs are for debugging purposes only --

I0422 10:57:54.584073 24621 nvc.c:281] initializing library context (version=1.0.2, build=ff40da533db929bf515aca59ba4c701a65a35e6b)
I0422 10:57:54.584110 24621 nvc.c:255] using root /
I0422 10:57:54.584117 24621 nvc.c:256] using ldcache /etc/ld.so.cache
I0422 10:57:54.584122 24621 nvc.c:257] using unprivileged user 1001:1001
W0422 10:57:54.623194 24622 nvc.c:186] failed to set inheritable capabilities
W0422 10:57:54.623255 24622 nvc.c:187] skipping kernel modules load due to failure
I0422 10:57:54.623597 24623 driver.c:133] starting driver service
I0422 10:57:54.646522 24621 nvc_info.c:434] requesting driver information with ''
I0422 10:57:54.671535 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/vdpau/libvdpau_nvidia.so.410.78
I0422 10:57:54.671868 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/tls/libnvidia-tls.so.410.78
I0422 10:57:54.676668 24621 nvc_info.c:150] skipping /usr/lib/nvidia-410/libnvidia-tls.so.410.78
I0422 10:57:54.676727 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-ptxjitcompiler.so.410.78
I0422 10:57:54.696184 24621 nvc_info.c:148] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.78
I0422 10:57:54.696275 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-ml.so.410.78
I0422 10:57:54.706616 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-ifr.so.410.78
I0422 10:57:54.706764 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-glsi.so.410.78
I0422 10:57:54.706847 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-glcore.so.410.78
I0422 10:57:54.714679 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-fbc.so.410.78
I0422 10:57:54.714788 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-fatbinaryloader.so.410.78
I0422 10:57:54.715375 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-encode.so.410.78
I0422 10:57:54.715442 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-eglcore.so.410.78
I0422 10:57:54.725591 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-compiler.so.410.78
I0422 10:57:54.725729 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvidia-cfg.so.410.78
I0422 10:57:54.736106 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libnvcuvid.so.410.78
I0422 10:57:54.736406 24621 nvc_info.c:148] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.410.78
I0422 10:57:54.737383 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libGLX_nvidia.so.410.78
I0422 10:57:54.737959 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libGLESv2_nvidia.so.410.78
I0422 10:57:54.738520 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libGLESv1_CM_nvidia.so.410.78
I0422 10:57:54.738576 24621 nvc_info.c:148] selecting /usr/lib/nvidia-410/libEGL_nvidia.so.410.78
I0422 10:57:54.751572 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/vdpau/libvdpau_nvidia.so.410.78
I0422 10:57:54.753471 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/tls/libnvidia-tls.so.410.78
I0422 10:57:54.755478 24621 nvc_info.c:150] skipping /usr/lib32/nvidia-410/libnvidia-tls.so.410.78
I0422 10:57:54.758384 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-ptxjitcompiler.so.410.78
I0422 10:57:54.761757 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-ml.so.410.78
I0422 10:57:54.766695 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-ifr.so.410.78
I0422 10:57:54.768770 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-glsi.so.410.78
I0422 10:57:54.778832 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-glcore.so.410.78
I0422 10:57:54.779780 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-fbc.so.410.78
I0422 10:57:54.780645 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-fatbinaryloader.so.410.78
I0422 10:57:54.785882 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-encode.so.410.78
I0422 10:57:54.799686 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-eglcore.so.410.78
I0422 10:57:54.808885 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvidia-compiler.so.410.78
I0422 10:57:54.819525 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libnvcuvid.so.410.78
I0422 10:57:54.820275 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libGLX_nvidia.so.410.78
I0422 10:57:54.827145 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libGLESv2_nvidia.so.410.78
I0422 10:57:54.827546 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libGLESv1_CM_nvidia.so.410.78
I0422 10:57:54.843421 24621 nvc_info.c:148] selecting /usr/lib32/nvidia-410/libEGL_nvidia.so.410.78
W0422 10:57:54.843476 24621 nvc_info.c:299] missing library libnvidia-opticalflow.so
W0422 10:57:54.843486 24621 nvc_info.c:303] missing compat32 library libnvidia-cfg.so
W0422 10:57:54.843495 24621 nvc_info.c:303] missing compat32 library libcuda.so
W0422 10:57:54.843504 24621 nvc_info.c:303] missing compat32 library libnvidia-opencl.so
W0422 10:57:54.843511 24621 nvc_info.c:303] missing compat32 library libnvidia-opticalflow.so
I0422 10:57:54.844156 24621 nvc_info.c:229] selecting /usr/lib/nvidia-410/bin/nvidia-smi
I0422 10:57:54.844207 24621 nvc_info.c:229] selecting /usr/lib/nvidia-410/bin/nvidia-debugdump
I0422 10:57:54.844242 24621 nvc_info.c:229] selecting /usr/lib/nvidia-410/bin/nvidia-persistenced
I0422 10:57:54.844281 24621 nvc_info.c:229] selecting /usr/lib/nvidia-410/bin/nvidia-cuda-mps-control
I0422 10:57:54.844323 24621 nvc_info.c:229] selecting /usr/lib/nvidia-410/bin/nvidia-cuda-mps-server
W0422 10:57:54.844349 24621 nvc_info.c:253] missing device /dev/nvidia-uvm-tools
I0422 10:57:54.844354 24621 nvc_info.c:366] listing device /dev/nvidiactl
I0422 10:57:54.844361 24621 nvc_info.c:366] listing device /dev/nvidia-uvm
I0422 10:57:54.844365 24621 nvc_info.c:366] listing device /dev/nvidia-modeset
I0422 10:57:54.844388 24621 nvc_info.c:270] listing ipc /run/nvidia-persistenced/socket
W0422 10:57:54.844402 24621 nvc_info.c:274] missing ipc /tmp/nvidia-mps
I0422 10:57:54.844408 24621 nvc_info.c:490] requesting device information with ''
I0422 10:57:54.850714 24621 nvc_info.c:520] listing device /dev/nvidia0 (GPU-0f9393b3-06cf-b58a-5590-b06f477dfd24 at 00000000:06:00.0)
NVRM version:   410.78
CUDA version:   10.0

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 980
Brand:          GeForce
GPU UUID:       GPU-0f9393b3-06cf-b58a-5590-b06f477dfd24
Bus Location:   00000000:06:00.0
Architecture:   5.2
I0422 10:57:54.850749 24621 nvc.c:318] shutting down library context
I0422 10:57:54.851290 24623 driver.c:192] terminating driver service
I0422 10:57:54.859807 24621 driver.c:233] driver service terminated successfully
`

 - [ ] Kernel version from `uname -a`
`Linux bi-linux01 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

 - [ ] Any relevant kernel output lines from `dmesg`
`[    5.971414] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  410.78  Sat Nov 10 22:09:04 CST 2018 (using threaded interrupts)
[    5.994283] PKCS#7 signature not signed with a trusted key
[    5.995041] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  410.78  Sat Nov 10 22:07:09 CST 2018
[    5.995444] PKCS#7 signature not signed with a trusted key`

`[    8.992573] EDAC sbridge: Seeking for: PCI ID 8086:2fbb
[    8.992604] EDAC sbridge: CPU SrcID #0, Ha #0, Channel #1 has DIMMs, but ECC is disabled
[    8.992610] EDAC sbridge: Couldn't find mci handler
[    8.992612] EDAC sbridge: Failed to register device with error -19.
`

`[   10.176415] input: HDA NVidia HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:03.0/0000:03:00.0/0000:04:09.0/0000:06:00.1/sound/card1/input14
[   10.176462] input: HDA NVidia HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:03.0/0000:03:00.0/0000:04:09.0/0000:06:00.1/sound/card1/input15
[   10.176501] input: HDA NVidia HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:03.0/0000:03:00.0/0000:04:09.0/0000:06:00.1/sound/card1/input16
[   10.176538] input: HDA NVidia HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:03.0/0000:03:00.0/0000:04:09.0/0000:06:00.1/sound/card1/input17
[   11.616912] PKCS#7 signature not signed with a trusted key
[   11.624420] PKCS#7 signature not signed with a trusted key
[   11.722552] PKCS#7 signature not signed with a trusted key
[   11.722585] PKCS#7 signature not signed with a trusted key
[   11.724213] PKCS#7 signature not signed with a trusted key
[   11.829708] PKCS#7 signature not signed with a trusted key
[   11.829709] PKCS#7 signature not signed with a trusted key
[   11.844130] PKCS#7 signature not signed with a trusted key
[   11.844766] PKCS#7 signature not signed with a trusted key
[   11.958348] PKCS#7 signature not signed with a trusted key
[   11.979822] PKCS#7 signature not signed with a trusted key`

 - [ ] Driver information from `nvidia-smi -a`

`==============NVSMI LOG==============

Timestamp                           : Mon Apr 22 13:03:18 2019
Driver Version                      : 410.78
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:06:00.0
    Product Name                    : GeForce GTX 980
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-0f9393b3-06cf-b58a-5590-b06f477dfd24
    Minor Number                    : 0
    VBIOS Version                   : 84.04.31.00.82
    MultiGPU Board                  : No
    Board ID                        : 0x600
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x06
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x13C010DE
        Bus Id                      : 00000000:06:00.0
        Sub System Id               : 0x29833842
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 8x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 1000 KB/s
        Rx Throughput               : 6000 KB/s
    Fan Speed                       : 0 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : N/A
            HW Power Brake Slowdown : N/A
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 4040 MiB
        Used                        : 418 MiB
        Free                        : 3622 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 5 MiB
        Free                        : 251 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 5 %
        Memory                      : 9 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 55 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 91 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 16.44 W
        Power Limit                 : 185.00 W
        Default Power Limit         : 185.00 W
        Enforced Power Limit        : 185.00 W
        Min Power Limit             : 100.00 W
        Max Power Limit             : 231.00 W
    Clocks
        Graphics                    : 135 MHz
        SM                          : 135 MHz
        Memory                      : 324 MHz
        Video                       : 405 MHz
    Applications Clocks
        Graphics                    : 1266 MHz
        Memory                      : 3505 MHz
    Default Applications Clocks
        Graphics                    : 1266 MHz
        Memory                      : 3505 MHz
    Max Clocks
        Graphics                    : 1531 MHz
        SM                          : 1531 MHz
        Memory                      : 3505 MHz
        Video                       : 1408 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1788
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 235 MiB
        Process ID                  : 11439
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 85 MiB
        Process ID                  : 12981
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=9265336173885051406,18215864254877433692,131072 --enable-crash-reporter=7dd42f6d-b163-47ca-830c-5b1b2648c262, --gpu-preferences=KAAAAAAAAACAAAAAAQAAAAAAAAAAAGAAAAAAAAEAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=12649565056258512986
            Used GPU Memory         : 93 MiB`

 - [ ] Docker version from `docker version`

`Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false`

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

`Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-=======================================================================================
ii  libnvidia-container-tools                 1.0.2-1                   amd64                     NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                1.0.2-1                   amd64                     NVIDIA container runtime library
ii  nvidia-410                                410.78-0ubuntu0~gpu16.04. amd64                     NVIDIA binary driver - version 410.78
un  nvidia-common                             <none>                    <none>                    (no description available)
ii  nvidia-container-runtime                  2.0.0+docker18.09.5-3     amd64                     NVIDIA container runtime
ii  nvidia-container-runtime-hook             1.4.0-1                   amd64                     NVIDIA container runtime hook
un  nvidia-docker                             <none>                    <none>                    (no description available)
ii  nvidia-docker2                            2.0.3+docker18.09.5-3     all                       nvidia-docker CLI wrapper
un  nvidia-driver-binary                      <none>                    <none>                    (no description available)
un  nvidia-legacy-340xx-vdpau-driver          <none>                    <none>                    (no description available)
un  nvidia-libopencl1-410                     <none>                    <none>                    (no description available)
un  nvidia-libopencl1-dev                     <none>                    <none>                    (no description available)
un  nvidia-opencl-icd                         <none>                    <none>                    (no description available)
ii  nvidia-opencl-icd-410                     410.78-0ubuntu0~gpu16.04. amd64                     NVIDIA OpenCL ICD
un  nvidia-persistenced                       <none>                    <none>                    (no description available)
ii  nvidia-prime                              0.8.2                     amd64                     Tools to enable NVIDIA's Prime
ii  nvidia-settings                           418.56-0ubuntu0~gpu16.04. amd64                     Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                    <none>                    <none>                    (no description available)
un  nvidia-smi                                <none>                    <none>                    (no description available)
un  nvidia-vdpau-driver                       <none>                    <none>                    (no description available)`

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`

`version: 1.0.2
build date: 2019-03-26T03:56+00:00
build revision: ff40da533db929bf515aca59ba4c701a65a35e6b
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections`

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

 - [ ] Docker command, image and tag used

`command used:  nvidia-docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
image: nvidia/cuda
tag:  latest`

**Comment by RenaudWasTaken** [comment]
What is the output of `which nvidia-container-runtime-hook`?
Can you also paste the output of your docker systemd unit file?

**Comment by cris1403** [comment]
well ... in the meantime I installed Ubuntu 18.04 on my desktop and nvidia-docker 2.0 works!
