### ISSUE TITLE
Remove "volume setup" for 1.0.0

### ISSUE THREAD

**Issue by 3XX0** [NVIDIA/nvidia-docker#96]
`nvidia-docker volume setup` does more harm than good.
For example, users often forget to execute it between driver upgrades or mix plugin/standalone installations. Moreover this approach is not in line with what Docker supports officially.

Now that the plugin is fairly stable, we plan to remove `volume setup` for the first 1.0.0 release.

**Comment by flx42** [comment]
If you object, speak now or forever hold your peace :)

**Comment by lsb** [comment]
What are the implications for plugin vs standalone?

**Comment by flx42** [comment]
You will have to use the plugin. Is that a problem?

**Comment by jendap** [comment]
Thank you for this. This was a weird thing.

**Comment by flx42** [comment]
@jendap yeah... but it was sometimes a necessary workaround when we didn't have solid deb and rpm packages.
