### ISSUE TITLE
nvidia-docker as a snap?

### ISSUE THREAD

**Issue by andaag** [NVIDIA/nvidia-docker#961]
I'm not sure if this is even feasible, but it'd be really nice.

I'm currently using kata-containers as a snap package, which means I don't require any custom repositories. See https://github.com/kata-containers/packaging/tree/master/snap

nvidia-docker is one of my very few custom repositories. Being able to upgrade distro independently of your repo would be fantastic.

**Comment by RenaudWasTaken** [comment]
We'll be transitioning to a new packaging mechanism as we roll the new `--gpu` option, the nvidia-docker packages are likely to be deprecated.

We're still investigating, but if possible we'd like a solution that is first containerized (e.g: docker plugin install nvidia/something) and then have a package fallback.

In any case snaps aren't going to be available for nvidia-docker :)
