### ISSUE TITLE
deploy nvidia-docker in AWS EC2

### ISSUE THREAD

**Issue by xiaohai12** [NVIDIA/nvidia-docker#962]
I have a question about using nvidia-docker in the AWS EC2

I create a docker container and it ran well in the AWS EC2 without setting according to the link below (since I don't have permission the get the user key)
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

however, the speed of my instance which used Tesla V100 is lower then 1080 ti in my own server(not AWS), which is quilt wired. 
So my question is that whether the lower speed of AWS instance is caused by not configuring nvidia-docker on EC2 or other reason,

**Comment by RenaudWasTaken** [comment]
Can you describe your workload and the speed on both on instances?
Do you have specific code we can take a look at?
What is the configuration of your own server?
What driver version and CUDA version are you using, ....?

nvidia-docker isn't expected to have any impacts on your running programs.

**Comment by RenaudWasTaken** [comment]
Closing as no answer for more than a month.
