### ISSUE TITLE
Unsupported distribution

### ISSUE THREAD

**Issue by dackdel** [NVIDIA/nvidia-docker#963]
`curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list`

I get 

`# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker`

Running ubuntu 19.04. Is there a way for me to install the nvidia-docker meant for 18.04?

**Comment by RenaudWasTaken** [comment]
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | \ sudo tee /etc/apt/sources.list.d/nvidia-docker.list

Keep in mind that you only get best effort support if you are outside the ubuntu LTS

**Comment by sliawatimena** [comment]
I am running ubuntu 18.10 as echo $distribution
I put the correct password for it. Please help. Thank you very much in advance.

```
suryadi@xtal:~$ sudo curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | \ sudo tee /etc/apt/sources.list.d/nvidia-docker.list
[sudo] password for suryadi: 
Command ' sudo' not found, did you mean:

  command 'sudo' from deb sudo
  command 'sudo' from deb sudo-ldap

Try: sudo apt install <deb name>


(23) Failed writing body

```

**Comment by Ethyling** [comment]
The `\ sudo` tries to execute the command ' sudo' (note the space at the beginning). Remove the `\` and it will be good. Also the sudo on curl is not useful I think

**Comment by kulievvitaly** [comment]
I have the same problem with unsupported distribution. I use linux mint 19. It is based on ubuntu 18.04. Simple fix of this problem:

    distribution="ubuntu18.04"

**Comment by muntakim1** [comment]
> I have the same problem with unsupported distribution. I use linux mint 19. It is based on ubuntu 18.04. Simple fix of this problem:
> 
> ```
> distribution="ubuntu18.04"
> ```

This approach works for me too.

**Comment by mdasari823** [comment]
You can use `distribution="ubuntu18.04"` even if you use Linux Mint. It works fine.
