### ISSUE TITLE
I'm getting signature expired messages in apt after successfully adding current gpg key to apt

### ISSUE THREAD

**Issue by mercury00** [NVIDIA/nvidia-docker#965]
I still get the same message after apt-key add of that gpgkey.

```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key --keyring /etc/apt/trusted.gpg.d/nvidia-docker.gpg add -

OK

apt update

The following signatures were invalid: EXPKEYSIG C45B1676A04EA552 NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>
```

_Originally posted by @mercury00 in https://github.com/NVIDIA/nvidia-docker/issues/837#issuecomment-486038963_

**Comment by mercury00** [comment]
Just to add; it appears the problem here is that while nvidia updated their gpg public key, they haven't updated the signature signing their packages in the InRelease file:

InRelease file:
```-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEiLH4d5Jo/+sbd9/gxFsWdqBOpVIFAlywKTIACgkQxFsWdqBO
pVLviwf/R1uf+3n7quGgTGE2Tp3d33LHhNRfQiIWklt62Bi8ao8wXQutUPuTZbhg
rsAzM/3OofkycvJVXeE+JMYfexPdqTToacAgUSa4p0z8ZLoe53op42/NZXRUDQif
Mp3wznXDgEMPZ7WpK8VTE6hkOcr2tg26WRyi0z4AUv8xkX451dTc7ZzZWfGzJ2Mh
AhHm6J58iU/3APrh+35+CfzXfIAPIycwr5xBZFgMiur7DZ2XevtHNiIHoT3sSG3T
rM7ufGl/NVfyu1ajoU4zwLh3azSNOuwT3YoL93hms1EEeDqRxvre7YTHlgaGDhLZ
VUdwvLOk0SZPwdds1b636SePBkA+Tg==
=kIQg
-----END PGP SIGNATURE-----```

**Comment by Ethyling** [comment]
I can't reproduce it. Could you give us the content of `/etc/os-release` ?

**Comment by mercury00** [comment]
Ubuntu 18.04.

I discovered the problem: This may be helpful for others.

After deleting the gpg keyfile several times (and the sources.list file for nvidia-docker) and trying over and over, I was still getting this message.

Inspecting apt more closely, it appears apt will retain the old, invalid nvidia keys in the `/etc/apt/trusted.gpg` file, and use those rather than later, identically indexed keys in `/etc/apt/trusted.gpg.d/nvidia-docker.gpg` file.  If you don't like your `trusted.gpg` file to be a mess of old keys from other repos and try to keep them in their own, managed files (such as for automated configuration via ansible), you'll want to delete out old keys in `trusted.gpg` as well as the files in `trusted.gpg.d\` folder, via
`apt-key del DDCAE044F796ECB0`
You may have to run the command more than once.

**Comment by mercury00** [comment]
This has bit me for a cluster installation; I'll be adding the task to delete all the old nvidia signing keys (expired keys) in the `trusted.gpg` file - if anyone is getting an EXPKEYSIG error, checking all your old and redundant signing keys via `apt-key list` may help you find them.

**Comment by RenaudWasTaken** [comment]
Looks like this is solved, thanks for detailing your solution!
