### ISSUE TITLE
No Driver Docker container for Ubuntu 18.04

### ISSUE THREAD

**Issue by vsabella** [NVIDIA/nvidia-docker#968]
https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(Beta)

Instructions for Ubuntu 18.04 have you pulling a docker container which was not published / does not exist.

**Comment by Ethyling** [comment]
Yes, sorry. We are currently working to add the support for Ubuntu18.04 but we need to fix the build on it before. You can follow and use the changes from this PR if you need: https://gitlab.com/nvidia/driver/merge_requests/15.

**Comment by Ethyling** [comment]
The docker images for Ubuntu18.04 are available on Docker hub now. See https://hub.docker.com/r/nvidia/driver/tags. I will update the documentation soon. Thank you for your report.
