### ISSUE TITLE
cuDNN in a CentOS 6 image

### ISSUE THREAD

**Issue by jakirkham** [NVIDIA/nvidia-docker#97]
Thanks for providing these building blocks. They are definitely a nice place for people to start. One thing that would be really nice (if possible) would be to have cuDNN included in a CentOS 6 image. If this is not possible, it would be nice to understand why it is not possible and whether or not that might change. Thanks again for providing these.

**Comment by flx42** [comment]
It should be possible to provide that, which version of cuDNN do you need?

**Comment by jakirkham** [comment]
Awesome. Ideally v5.
