### ISSUE TITLE
nvidia-docker supports the latest cuda10.1?

### ISSUE THREAD

**Issue by mk123qwe** [NVIDIA/nvidia-docker#970]
nvidia-docker supports the latest cuda10.1?

**Comment by takanokage** [comment]
It would appear that the answer is yes: [nvidia/cuda:tags](https://hub.docker.com/r/nvidia/cuda/tags)

**Comment by RenaudWasTaken** [comment]
Yes!

**Comment by xuejipeng** [comment]
@RenaudWasTaken  I want to make sure if nvidia-docker and nvidia-docker2 both support cuda10.1?

**Comment by xuejipeng** [comment]
when i run  `nvidia-docker run -ti --rm   nvidia/cuda:10.1-devel-ubuntu16.04` i can't get nvidia-smi command and when i run `nvidia-docker run -ti --rm   nvidia/cuda:9.2-base-ubuntu16.04` it's work.
my driver version is 410.79 and GPU is Tesla.

**Comment by zetyquickly** [comment]
@xuejipeng Have you resolved this issue?

**Comment by xuejipeng** [comment]
@zetyquickly  You should check that your versions are correct.
https://github.com/NVIDIA/nvidia-docker/wiki/CUDA
