### ISSUE TITLE
E: Package 'nvidia-docker2' has no installation candidate

### ISSUE THREAD

**Issue by hanklin3** [NVIDIA/nvidia-docker#972]
---

### 2. Steps to reproduce the issue
Ran
```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
```
$ sudo apt-get install -y nvidia-docker2
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nvidia-docker2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'nvidia-docker2' has no installation candidate
```

cat /etc/apt/sources.list.d/nvidia-docker.list
```
deb https://nvidia.github.io/libnvidia-container/ubuntu14.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu14.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu14.04/$(ARCH) /
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
Linux irn1-vdi-cuda03 4.4.0-142-generic #168~14.04.1-Ubuntu SMP Sat Jan 19 11:26:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
==============NVSMI LOG==============

Timestamp                           : Fri May  3 19:40:19 2019
Driver Version                      : 410.92
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:02:00.0
    Product Name                    : GRID P40-4Q
    Product Brand                   : Grid
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Enabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-0651ad90-1de4-11b2-b393-fccff9bb63b5
    Minor Number                    : 0
    VBIOS Version                   : 00.00.00.00.00
    MultiGPU Board                  : No
    Board ID                        : 0x200
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : VGPU
    GRID Licensed Product
        Product Name                : Quadro Virtual Data Center Workstation
        License Status              : Licensed
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x02
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B3810DE
        Bus Id                      : 00000000:02:00.0
        Sub System Id               : 0x11EB10DE
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : N/A
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 4096 MiB
        Used                        : 1659 MiB
        Free                        : 2437 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 0 MiB
        Free                        : 256 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 1 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : N/A
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 1303 MHz
        SM                          : 1303 MHz
        Memory                      : 3615 MHz
        Video                       : 1177 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1588
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 743 MiB
        Process ID                  : 3694
            Type                    : C+G
            Name                    : /usr/lib/vmware/viewagent/VMwareBlastServer/VMwareBlastServer
            Used GPU Memory         : 244 MiB
        Process ID                  : 4243
            Type                    : G
            Name                    : compiz
            Used GPU Memory         : 208 MiB
        Process ID                  : 26716
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=6352451789095890990,9681563911430251328,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=10593858493328464213
            Used GPU Memory         : 113 MiB

 - [ ] Docker version from `docker version`
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:10:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:08:26 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-=======================================================
un  libgl1-nvidia-alternative <none>            <none>            (no description available)
un  nvidia-common             <none>            <none>            (no description available)
un  nvidia-libopencl1-dev     <none>            <none>            (no description available)
un  nvidia-prime              <none>            <none>            (no description available)
un  nvidia-vdpau-driver       <none>            <none>            (no description available)

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used
Collapse

**Comment by RenaudWasTaken** [comment]
What docker version is on your host?

**Comment by hanklin3** [comment]
How do I check?

**Comment by RenaudWasTaken** [comment]
`docker version`

**Comment by hanklin3** [comment]
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:10:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:08:26 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by RenaudWasTaken** [comment]
Sorry about the late reply.
When you do an apt-get update do you see the nvidia repo (nvidia.github.io) in the list of updated repos?

**Comment by houcharlie** [comment]
I also had the same issue, and I do see nvidia.github.io in the list of updated repos

**Comment by hanklin3** [comment]
Yes I do see it. My pc is actually a VMware machine, not sure if that makes a difference.

**Comment by Ethyling** [comment]
@hanklin3 Could you try this:
```
sudo apt-get install nvidia-docker2=2.0.3+docker18.06.0-1 nvidia-container-runtime=2.0.0+docker18.06.0-1
```
It should install the right version of `nvidia-docker2` matching your docker version

**Comment by hanklin3** [comment]
$ sudo apt-get install nvidia-docker2=2.0.3+docker18.06.0-1 nvidia-container-runtime=2.0.0+docker18.06.0-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-container-runtime : Depends: nvidia-container-runtime-hook (< 2.0.0) but it is not installable
 nvidia-docker2 : Depends: docker-ce (= 18.06.0~ce~3-0~ubuntu) but 18.06.0~ce-0~ubuntu-uber1 is to be installed or
                           docker-ee (= 18.06.0~ee~3-0~ubuntu) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Ethyling** [comment]
Do you have Docker currently installed? If so, what is the package version? You can check and get this information doing `apt list --installed | grep docker`.
Can you give us the output of `apt list --installed | grep nvidia` please?

**Comment by hanklin3** [comment]
$ apt list --installed | grep docker

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

docker-ce/unknown,now 18.06.0~ce-0~ubuntu amd64 [installed,automatic]

apt list --installed | grep nvidia

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

I think no output for nvidia

**Comment by Ethyling** [comment]
Thank you.
How did you install your Docker package? It's seems like it's not a package from the docker repository. Currently your docker-ce package version is `18.06.0~ce-0~ubuntu` and the official package version matching your docker version is `18.06.0~ce~3-0~ubuntu`. Our packages require a specific version of the docker-ce package and that's why it's not working. I would recommend you to reinstall docker following the official instructions: https://docs.docker.com/install/linux/docker-ce/ubuntu/
