### ISSUE TITLE
couldn't find binary nvidia-container-cli

### ISSUE THREAD

**Issue by GoodJoey** [NVIDIA/nvidia-docker#973]
installed nvidia-docker2 following the guide,
but when run 'docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi', it says can't find nvidia-container-cli.
where can i get nvidia-container-cli? 
Thanks very much.

**Comment by RenaudWasTaken** [comment]
Hi!

Please show:
- the output of your docker configuration file (/etc/docker/daemon.json)
- the output of your docker systemd file 
- the output of the following command `which nvidia-container-cli`

**Comment by GoodJoey** [comment]
nvidia-container-cli the file is not exist.
I copied the nvidia-container-cli from another host, and it worked.
close this issue.
