### ISSUE TITLE
Ubuntu 1804: unmet dependencies

### ISSUE THREAD

**Issue by joeroback** [NVIDIA/nvidia-docker#974]
Ubuntu 18.04, docker-ce stable

```
sudo apt install nvidia-docker2 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.5~3-0~ubuntu-bionic) but 5:18.09.6~3-0~ubuntu-bionic is to be installed or
                           docker-ee (= 5:18.09.5~3-0~ubuntu-bionic) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
```
ii  docker-ce                                  5:18.09.6~3-0~ubuntu-bionic                  amd64        Docker: the open-source application container engine
ii  docker-ce-cli                              5:18.09.6~3-0~ubuntu-bionic                  amd64        Docker CLI: the open-source application container engine
```

Note I work for NVIDIA and I have been trying to use nvidia-docker2 for a while now but it always does stuff like this. Seems that the nvidia-docker2 is too strict with package versions. It is really annoying to the point that its hardly usable if have to keep babysitting nvidia-docker2 .. once it installed and stays installs, it works great.

I also wish it supported non-LTS, since we could use docker to build/run an LTS image but have the latest and greatest linux desktop, etc. But that is a whole other thing, I guess.

**Comment by Ethyling** [comment]
It should be fixed. The strict requirement on the docker version is necessary to be working well. We are aware of this and we are working to resolve this issue.

**Comment by pxxgogo** [comment]
You should use [this method](https://medium.com/@sh.tsang/docker-tutorial-5-nvidia-docker-2-0-installation-in-ubuntu-18-04-cb80f17cac65) to install docker-ce first.
