### ISSUE TITLE
Error: ubuntu18.04/arm64  Release Not Found

### ISSUE THREAD

**Issue by releasethekragle** [NVIDIA/nvidia-docker#975]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description

Running Ubuntu LTS 18.04 on Jetson TX2 DevKit

### 2. Steps to reproduce the issue

`sudo apt-get update`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

```
Err:15 https://nvidia.github.io/nvidia-docker/ubuntu18.04/arm64  Release
  404  Not Found [IP: 185.199.111.153 443]
E: The repository 'https://nvidia.github.io/nvidia-docker/ubuntu18.04/arm64  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Skipping acquire of configured file 'stable/source/Sources' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' does not seem to provide it (sources.list entry misspelt?)
```

Errors listed attached:
[Ubuntu 18.04 LTS Error.pdf](https://github.com/NVIDIA/nvidia-docker/files/3149844/Ubuntu.18.04.LTS.Error.pdf)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
nvidia-container-cli: command not found
 - [x] Kernel version from `uname -a`
Linux jetdev-desktop 4.9.140-tegra #1 SMP PREEMPT Wed Mar 13 00:30:11 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux
 - [x] Driver information from `nvidia-smi -a`
Linux jetdev-desktop 4.9.140-tegra #1 SMP PREEMPT Wed Mar 13 00:30:11 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux
 - [x] Docker version from `docker version`
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:51:35 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/arm64
  Experimental:     false

**Comment by RenaudWasTaken** [comment]
Same comment as here: NVIDIA/nvidia-container-runtime#58 (comment)

We don't support ARM.

**Comment by gogobook** [comment]
Try this https://askubuntu.com/questions/917081/how-to-get-rid-of-arm64-in-apt
It's work.

**Comment by xiaozhouX** [comment]
> Same comment as here: [NVIDIA/nvidia-container-runtime#58](https://github.com/NVIDIA/nvidia-container-runtime/issues/58) (comment)
> 
> We don't support ARM.

Is there any plan to support ARM ?

**Comment by klueska** [comment]
ARM is supported on a subset of OSs today.

The support matrix can be found here:
https://nvidia.github.io/nvidia-docker/
