### ISSUE TITLE
How to save the nvidia-docker on my host machine?

### ISSUE THREAD

**Issue by AnaRhisT94** [NVIDIA/nvidia-docker#978]
Hi,
I'm using nvidia-docker, and I changed the following command: (from nvidia web)
nvidia-docker run -it --rm -v /home/unknown1/Desktop/myFolder:/mnt/myFolder 

to this command:

nvidia-docker run -it my_docker -v /home/unknown1/Desktop/myFolder:/mnt/myFolder 

But I'm not sure this will work after closing the docker.

Commands like "docker, commit, docker commit" aren't found when I try to use them.

**Comment by RenaudWasTaken** [comment]
Hello!

nvidia-docker is really just a docker wrapper. The only thing nvidia-docker does is add the `--runtime` argument to the docker CLI (i.e: `docker run --runtime ... = nvidia-docker run ...`).

docker commit will work in exactly the same way whether you use docker or nvidia-docker.
