### ISSUE TITLE
Building projects using Caffe package

### ISSUE THREAD

**Issue by ruffsl** [NVIDIA/nvidia-docker#98]
Not sure if this is the place for this, but I was trying to build some c++ code using caffe, and rather than building caffe from source, I thought I try building against with what comes with nvidia's caffe packages:
* `caffe-nv`
* `caffe-nv-tools`
* `libcaffe-nv0-dev`
* `libcaffe-nv0`

So I changed the [caffe Dockerfile](https://github.com/NVIDIA/nvidia-docker/blob/9bb9af4be07034c468ba4c4adc047a9f4df89975/ubuntu-14.04/caffe/Dockerfile) to point `FROM nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04
`

I got close, but hit a snag when I received a `No such file or directory #include "caffe/proto/caffe.pb.h"` error, as I checked that it existed nowhere in the image. Could the protobuff files be packaged with the rest of caffe, or do I still need to build caffe from source?

**Comment by flx42** [comment]
This looks like a bug indeed, I will try to get this fixed for the next package release.

\<shameless_plug> If you want to do inference in C++ with Caffe, you can also look at the code I released before GTC: https://github.com/NVIDIA/gpu-rest-engine \</shameless_plug>

**Comment by flx42** [comment]
Moved the issue to https://github.com/NVIDIA/caffe/issues/148
Closing this one.
Thanks for the report @ruffsl
