### ISSUE TITLE
Hello Not support version 396.37

### ISSUE THREAD

**Issue by zhouwei713** [NVIDIA/nvidia-docker#981]
Hello
this is the version

Status: Downloaded newer image for nvidia/cuda:latest
Fri May 17 09:38:09 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   24C    P8     9W / 250W |      0MiB / 22919MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

and this is the error when I want to start the docker of tensorflow-gpu

# docker run --runtime=nvidia -it tensorflow/tensorflow:latest-gpu bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=410338 /SkyDiscovery/docker/overlay2/fa93f99a963b70cbb6e203c69ba4d6ac61611865c10a8e8cf385dca6df93f9b9/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: driver >= 410\\\\n\\\"\"": unknown.

**Comment by RenaudWasTaken** [comment]
Hello!

Please update your drivers to a more recent driver version or use an earlier version of tensorflow.
Sorry for the delay.
