### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by JsBlueCat** [NVIDIA/nvidia-docker#982]
i'm using nvidia-418,titan V,ubuntu 18.04,using tensorflow/tensorflow:0.12.1-gpu-py3 images
with nvidia-docker. 
Runing the command 
```
sudo docker run -it --rm --runtime=nvidia -v $PWD:/tmp -w /tmp jsbluecat/tensorflow:fcn python ./FCN_plus.py
``` 
but it throws out the error 
```
E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F tensorflow/core/kernels/conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms
```
does docker share the gpu resources? did someone meet the same question?

i run the same code in cpu,and it works. and in docker container , it test the cuda sample it shows pass??? 

so how can i solve this problem

**Comment by RenaudWasTaken** [comment]
Hello!

We can't help you if you don't paste your code here :)

> does docker share the gpu resources?
Can you detail what you mean by this question :)

**Comment by RenaudWasTaken** [comment]
Closing as information was not provided :)
