### ISSUE TITLE
ppc64le RHEL 7.6 meet this error "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.

### ISSUE THREAD

**Issue by Eloring** [NVIDIA/nvidia-docker#985]
### ENV
RHEL 7.6
ppc64le (IBM Power8)
Docker version: 18.03.1-ce
Driver version: 418.67 
CUDA Version: 10.1
CuDNN Version: 7.6
2GPU: Tesla K80
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67             Driver Version: 418.67           CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000002:03:00.0 Off |                  Off |
| N/A   39C    P0    55W / 149W |      0MiB / 12206MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000002:04:00.0 Off |                  Off |
| N/A   30C    P0    42W / 149W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

---

I have read carefully the documentation and frequently asked questions, unfortunately, the error still exist.

### 1. Issue description

$ docker run --rm nvidia/cuda-ppc64le nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.

### 2. Steps to reproduce the issue

I have follow this [RHEL 7.4/7.5 (docker)](https://github.com/NVIDIA/nvidia-docker#centos-7-docker-rhel-7475-docker) and the FAQ [docker-ce on ppc64le](https://github.com/nvidia/nvidia-docker/wiki/Frequently-Asked-Questions#do-you-support-powerpc64-ppc64le)

~~~
$ docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
$ yum remove nvidia-docker

$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.repo | \
  sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo

$ yum install -y nvidia-container-runtime-hook

$ docker run --rm nvidia/cuda-ppc64le nvidia-smi
~~~

### BTW

I followed this [if you use docker-ce with CentOS/RHEL on ppc64le, you need to register the nvidia runtime manually](https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup)

~~~
yum install nvidia-container-runtime
~~~
add this _--add-runtime=nvidia=/usr/bin/nvidia-container-runtime_ to _/docker.service.d/override.conf_

and I tried the other two registration methods separately

Unfortunately, none of them works.

**Comment by dbs4261** [comment]
I have had the same exact issue on RHEL 7.6 with an x86_64 platform and Docker EE version 18.09.6 any advice would be helpful.

**Comment by Eloring** [comment]
@dbs4261 In my case, if using the original docker distribution offered by RHEL 7.6 (Docker version 1.13.1), nvidia-docker works well.
However, I have to use docker with version >= 17 for _multi-stage build_. If you don't have to worry about the docker version, you can try this method.

**Comment by RenaudWasTaken** [comment]
To setup the runtime with docker-ce follow this guide: https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup

Afterwards you'll be able to use the `--runtime` option.
If you want containers to be GPU enabled during `docker build` you'll have to set the runtime as default (which is also explained in the above link).
