### ISSUE TITLE
nvidia-smi error

### ISSUE THREAD

**Issue by Eyshika** [NVIDIA/nvidia-docker#988]
Ran
`nvidia-smi`

Got error 

> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure
 > that the latest NVIDIA driver is installed and running.

**Comment by RenaudWasTaken** [comment]
Hello!

Please reopen an issue in which you have filled the [issue template](https://github.com/NVIDIA/nvidia-docker/blob/master/.github/ISSUE_TEMPLATE.md).

Thanks!
