### ISSUE TITLE
nvidia-uvm dont auto mount in container?

### ISSUE THREAD

**Issue by liucimin** [NVIDIA/nvidia-docker#997]
### 1. Issue or feature description
I have meet a problem is that the nvidia-docker dont auto mount device /dev/nvidia-uvm in container which is started by nvidia-docker.
If i use images with cuda,there is no problem.
But if i use images without cuda,i have to use --device /dev/nvidia-uvm in docker run command to mount the nvidia-uvm in container.If i dont use the args,i cannot use cuda in the container.

### 2. Steps to reproduce the issue

docker run --runtime=nvidia    -e NVIDIA_VISIBLE_DEVICES=0 -e CUDA_VISIBLE_DEVICES=0     -v /usr/local/:/usr/local/ -v /usr/lib64:/usr/lib64      -it --rm   centos bash

  root@544e3e9f9f4b:/# mount |grep nvi
tmpfs on /proc/driver/nvidia type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=555)
/dev/mapper/vg_centos7-root on /usr/bin/nvidia-smi type ext4 (ro,nosuid,nodev,relatime,data=ordered)
/dev/mapper/vg_centos7-root on /usr/bin/nvidia-debugdump type ext4 (ro,nosuid,nodev,relatime,data=ordered)
/dev/mapper/vg_centos7-root on /usr/bin/nvidia-persistenced type ext4 (ro,nosuid,nodev,relatime,data=ordered)
/dev/mapper/vg_centos7-root on /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.384.183 type ext4 (ro,nosuid,nodev,relatime,data=ordered)
/dev/mapper/vg_centos7-root on /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.384.183 type ext4 (ro,nosuid,nodev,relatime,data=ordered)
devtmpfs on /dev/nvidiactl type devtmpfs (ro,nosuid,noexec,size=251791088k,nr_inodes=62947772,mode=755)
devtmpfs on /dev/nvidia0 type devtmpfs (ro,nosuid,noexec,size=251791088k,nr_inodes=62947772,mode=755)
proc on /proc/driver/nvidia/gpus/0000:00:17.0 type proc (ro,nosuid,nodev,noexec,relatime)
root@544e3e9f9f4b:/#
root@544e3e9f9f4b:/# cd /dev/
root@544e3e9f9f4b:/dev# ls
console  core  fd  full  mqueue  null  nvidia0  nvidiactl  ptmx  pts  random  shm  stderr  stdin  stdout  tty  urandom  zero
root@544e3e9f9f4b:/dev# ll |grep nvid
bash: ll: command not found
root@544e3e9f9f4b:/dev# ls  |grep nvid
nvidia0
nvidiactl

We can see a gpu is in the container.But there no nvidia-uvm.So if i use cuda it will crash.

When we use 
docker run --runtime=nvidia   --device /dev/nvidia-uvm -e NVIDIA_VISIBLE_DEVICES=0 -e CUDA_VISIBLE_DEVICES=0     -v /usr/local/:/usr/local/ -v /usr/lib64:/usr/lib64      -it --rm    d3596e4c92a2   bash

it become right~

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by RenaudWasTaken** [comment]
/dev/nvidia-uvm is mounted in the container. Looks like you are trying to build your own custom image. In which case please check the CUDA images: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/10.1/base/Dockerfile#L31-32

Namely you'll want to make sure you have set both NVIDIA_VISIBLE_DEVICES and 
`NVIDIA_DRIVER_CAPABILITIES`
```
docker run -it --runtime nvidia nvidia/cuda:10.0-runtime-ubuntu16.04 ls /dev 
console  full	 nvidia-uvm	   nvidia1    pts     stderr  tty
core	 mqueue  nvidia-uvm-tools  nvidiactl  random  stdin   urandom
fd	 null	 nvidia0	   ptmx       shm     stdout  zero
```

**Comment by liucimin** [comment]
@RenaudWasTaken 
I mean if i use a image not with cuda and cudnn.
I should mount the cuda lib in the contianer.
BUT IF i just mount the cuda lib,and not mount the nvidia-uvm the container should use  --privileged .

**Comment by RenaudWasTaken** [comment]
> I mean if i use a image not with cuda and cudnn.
> I should mount the cuda lib in the contianer.
> BUT IF i just mount the cuda lib,and not mount the nvidia-uvm the container should use --privileged .

If you mount CUDA and CUDNN from the host (`/usr/local/:/usr/local/ -v /usr/lib64:/usr/lib64`) your image is going to depend on what is on the host.
In other words, your container will have a different behavior on different nodes which defeats the purpose of containers :)

I might add that by mounting `/usr/lib` you are likely going to break some of the binaries inside your container.

**Comment by liucimin** [comment]
@RenaudWasTaken 
Thx for your reply.
Now my problem is that if i use nvidia-docker2 ,the image i use should install cuda in the image?When i use  -e NVIDIA_VISIBLE_DEVICES = 0 to send the env for nvidia-docker.The nviadia-docker just give me the nvidia card in the container.It dont send the /dev/nvidia-uvm in the container.
It is right?

**Comment by RenaudWasTaken** [comment]
What prevents you from using the normal cuda images?
