### ISSUE TITLE
nvidia Docker2 has unmet dependencies that are installed  - 18.09.6-3

### ISSUE THREAD

**Issue by NicoMandel** [NVIDIA/nvidia-docker#999]
### 1. Issue or feature description
I wanted to run the [nVidia two days to a demo tutorial](https://github.com/dusty-nv/jetson-inference/blob/master/docs/digits-setup.md) on my Ubuntu 18.04 Laptop
after the host PC setup install with make failed due to unknown errors, I tried to go ahead with the docker installation. Now this apparently seems not to be able to install either.

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: docker-ce (= 5:18.09.6~3-0~ubuntu-xenial) but 5:18.09.6~3-0~ubuntu-bionic is to be installed or
                           docker-ee (= 5:18.09.6~3-0~ubuntu-xenial) but it is not installable
E: Unable to correct problems, you have held broken packages.`
```
With:
```

docker -v
Docker version 18.09.6, build 481bc77

```
Installed via the instructions from the [docker-ce documentation](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

`sudo docker run hello-world`

Outputs:
```
Hello from Docker!
This message shows that your installation appears to be working correctly. [...]etc.
```

### 2. Steps to reproduce the issue
run 

`sudo apt-get install -y nvidia-docker2`

or:

`sudo apt-get install -y nvidia-docker2=2.0.3+docker18.09.6-3 nvidia-container-runtime=2.0.0+docker18.09.6-3`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [X ] Driver information from `nvidia-smi -a`
```
Driver Version                      : 418.67
CUDA Version                        : 10.1

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1060 with Max-Q Design

```

 - [X ] Docker version from `docker version`

` 18.09.6, build 481bc77`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used
### 4. Related issues and already tried fixes
#974  which points to this [FAQ fix](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version)
#887 does not work either - same error as stated above
#719 - /etc/apt/sources.list.d. only contains
```
cuda-10-1-local-10.1.168-418.67.list                 isv:ownCloud:desktop.list       ros-latest.list.save
cuda-10-1-local-10.1.168-418.67.list.save            isv:ownCloud:desktop.list.save  smathot-ubuntu-cogscinl-bionic.list
graphics-drivers-ubuntu-ppa-xenial.list              nvidia-docker.list              smathot-ubuntu-cogscinl-bionic.list.save
graphics-drivers-ubuntu-ppa-xenial.list.distUpgrade  nvidia-docker.list.save         teejee2008-ubuntu-ppa-bionic.list
graphics-drivers-ubuntu-ppa-xenial.list.save         ros-latest.list                 teejee2008-ubuntu-ppa-bionic.list.save
```
and no `docker.list`
unkown fix:
`apt-cache policy docker-ce`
has no xenial releases, only bionic/stable packages
and `docker version ` shows the last line `Experimental:     false`

Any hints on what to do? Any help would be greatly appreciated. 
I would love to learn how to work with the Nvidia graphics card in my Laptop, but when neither the caffe default build or build instructions work, nor the docker, I am really running out of ideas..
Nico

**Comment by Ethyling** [comment]
It seems that you are using the repository for Ubuntu16.04 on your Ubuntu18.04. I would recommend you to do:
```
sudo apt purge -y libnvidia-container-tools libnvidia-container1:amd64 nvidia-container-runtime nvidia-container-runtime-hook nvidia-docker2
sudo rm /etc/apt/sources.list.d/nvidia-docker.list
```
And then follow https://github.com/NVIDIA/nvidia-docker#quickstart

**Comment by bparaj** [comment]
In my case, I had to re-install docker. Commands I ran:

    # Remove existing.
    $ apt-get remove docker docker-engine docker.io containerd runc

    # https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce
    # Execute steps 1-4 from the section "Set up the repository" and
    # steps 1-2 from "Install Docker CE" from the above page.

    # Follow installation steps for Ubuntu on https://github.com/NVIDIA/nvidia-docker

**Comment by NicoMandel** [comment]
@Ethyling it seems that you are correct. Somehow it had slipped my attention that in the
`/etc/apt/sources.list.d `there is a file called nvidia-docker.list. within this list, the debian link was still set to 16.04, I do not know how I made that mistake, but my colleague picked up on it. Manually changing the 16.04 to 18.04 worked. Thanks
